import { translations } from "@/lib/i18n";

type AuthFlowCopy = {
  loginDescription: string;
  linkExpiry: string;
  accessLinkSent: string;
  sendAccessLink: string;
  registrationLinkSent: string;
  registrationLinkExplanation: string;
  verifyingAccess: string;
  completingRegistration: string;
  accessSuccess: string;
  registrationSuccess: string;
  invalidAccessLink: string;
  invalidRegistrationLink: string;
  missingAccessLink: string;
  missingRegistrationLink: string;
};

export const authFlowCopy: Record<keyof typeof translations, AuthFlowCopy> = {
  en: {
    loginDescription: "Enter your email address to receive a sign-in link.",
    linkExpiry: "The link expires automatically after 10 minutes.",
    accessLinkSent: "If this email address is registered, you will receive a link valid for 10 minutes.",
    sendAccessLink: "Send sign-in link",
    registrationLinkSent: "Check your email: the link is valid for 10 minutes.",
    registrationLinkExplanation: "You will receive a secure link to complete registration and access your account.",
    verifyingAccess: "Verifying your sign-in link...",
    completingRegistration: "Completing your registration...",
    accessSuccess: "You are signed in.",
    registrationSuccess: "Registration complete.",
    invalidAccessLink: "This sign-in link is invalid or has expired. Request a new one.",
    invalidRegistrationLink: "This registration link is invalid or has expired. Request a new one.",
    missingAccessLink: "The sign-in link is missing. Request a new one to continue.",
    missingRegistrationLink: "The registration link is missing. Request a new one to continue.",
  },
  it: {
    loginDescription: "Inserisci la tua e-mail per ricevere un link di accesso.",
    linkExpiry: "Il link scade automaticamente dopo 10 minuti.",
    accessLinkSent: "Se l’e-mail è registrata, riceverai un link valido per 10 minuti.",
    sendAccessLink: "Invia link di accesso",
    registrationLinkSent: "Controlla la tua e-mail: il link è valido per 10 minuti.",
    registrationLinkExplanation: "Riceverai un link sicuro per completare la registrazione e accedere al tuo account.",
    verifyingAccess: "Verifica del link di accesso in corso...",
    completingRegistration: "Completamento della registrazione in corso...",
    accessSuccess: "Accesso completato.",
    registrationSuccess: "Registrazione completata.",
    invalidAccessLink: "Il link di accesso non è valido o è scaduto. Richiedine uno nuovo.",
    invalidRegistrationLink: "Il link di registrazione non è valido o è scaduto. Richiedine uno nuovo.",
    missingAccessLink: "Manca il link di accesso. Richiedine uno nuovo per continuare.",
    missingRegistrationLink: "Manca il link di registrazione. Richiedine uno nuovo per continuare.",
  },
  es: {
    loginDescription: "Introduce tu correo electrónico para recibir un enlace de acceso.",
    linkExpiry: "El enlace caduca automáticamente después de 10 minutos.",
    accessLinkSent: "Si el correo está registrado, recibirás un enlace válido durante 10 minutos.",
    sendAccessLink: "Enviar enlace de acceso",
    registrationLinkSent: "Revisa tu correo: el enlace es válido durante 10 minutos.",
    registrationLinkExplanation: "Recibirás un enlace seguro para completar el registro y acceder a tu cuenta.",
    verifyingAccess: "Verificando el enlace de acceso...",
    completingRegistration: "Completando el registro...",
    accessSuccess: "Has iniciado sesión.",
    registrationSuccess: "Registro completado.",
    invalidAccessLink: "El enlace de acceso no es válido o ha caducado. Solicita uno nuevo.",
    invalidRegistrationLink: "El enlace de registro no es válido o ha caducado. Solicita uno nuevo.",
    missingAccessLink: "Falta el enlace de acceso. Solicita uno nuevo para continuar.",
    missingRegistrationLink: "Falta el enlace de registro. Solicita uno nuevo para continuar.",
  },
  fr: {
    loginDescription: "Saisissez votre adresse e-mail pour recevoir un lien de connexion.",
    linkExpiry: "Le lien expire automatiquement après 10 minutes.",
    accessLinkSent: "Si cette adresse e-mail est enregistrée, vous recevrez un lien valable 10 minutes.",
    sendAccessLink: "Envoyer le lien de connexion",
    registrationLinkSent: "Consultez votre e-mail : le lien est valable 10 minutes.",
    registrationLinkExplanation: "Vous recevrez un lien sécurisé pour terminer l’inscription et accéder à votre compte.",
    verifyingAccess: "Vérification du lien de connexion...",
    completingRegistration: "Finalisation de l’inscription...",
    accessSuccess: "Connexion réussie.",
    registrationSuccess: "Inscription terminée.",
    invalidAccessLink: "Ce lien de connexion est invalide ou a expiré. Demandez-en un nouveau.",
    invalidRegistrationLink: "Ce lien d’inscription est invalide ou a expiré. Demandez-en un nouveau.",
    missingAccessLink: "Le lien de connexion est manquant. Demandez-en un nouveau pour continuer.",
    missingRegistrationLink: "Le lien d’inscription est manquant. Demandez-en un nouveau pour continuer.",
  },
  de: {
    loginDescription: "Gib deine E-Mail-Adresse ein, um einen Anmeldelink zu erhalten.",
    linkExpiry: "Der Link läuft nach 10 Minuten automatisch ab.",
    accessLinkSent: "Wenn diese E-Mail-Adresse registriert ist, erhältst du einen 10 Minuten gültigen Link.",
    sendAccessLink: "Anmeldelink senden",
    registrationLinkSent: "Prüfe dein E-Mail-Postfach: Der Link ist 10 Minuten gültig.",
    registrationLinkExplanation: "Du erhältst einen sicheren Link, um die Registrierung abzuschließen und auf dein Konto zuzugreifen.",
    verifyingAccess: "Anmeldelink wird überprüft...",
    completingRegistration: "Registrierung wird abgeschlossen...",
    accessSuccess: "Du bist angemeldet.",
    registrationSuccess: "Registrierung abgeschlossen.",
    invalidAccessLink: "Dieser Anmeldelink ist ungültig oder abgelaufen. Fordere einen neuen an.",
    invalidRegistrationLink: "Dieser Registrierungslink ist ungültig oder abgelaufen. Fordere einen neuen an.",
    missingAccessLink: "Der Anmeldelink fehlt. Fordere einen neuen an, um fortzufahren.",
    missingRegistrationLink: "Der Registrierungslink fehlt. Fordere einen neuen an, um fortzufahren.",
  },
  pt: {
    loginDescription: "Insira seu e-mail para receber um link de acesso.",
    linkExpiry: "O link expira automaticamente após 10 minutos.",
    accessLinkSent: "Se este e-mail estiver cadastrado, você receberá um link válido por 10 minutos.",
    sendAccessLink: "Enviar link de acesso",
    registrationLinkSent: "Verifique seu e-mail: o link é válido por 10 minutos.",
    registrationLinkExplanation: "Você receberá um link seguro para concluir o cadastro e acessar sua conta.",
    verifyingAccess: "Verificando o link de acesso...",
    completingRegistration: "Concluindo o cadastro...",
    accessSuccess: "Acesso concluído.",
    registrationSuccess: "Cadastro concluído.",
    invalidAccessLink: "Este link de acesso é inválido ou expirou. Solicite um novo.",
    invalidRegistrationLink: "Este link de cadastro é inválido ou expirou. Solicite um novo.",
    missingAccessLink: "O link de acesso não foi encontrado. Solicite um novo para continuar.",
    missingRegistrationLink: "O link de cadastro não foi encontrado. Solicite um novo para continuar.",
  },
  ru: {
    loginDescription: "Введите адрес электронной почты, чтобы получить ссылку для входа.",
    linkExpiry: "Срок действия ссылки автоматически истекает через 10 минут.",
    accessLinkSent: "Если этот адрес зарегистрирован, вы получите ссылку, действующую 10 минут.",
    sendAccessLink: "Отправить ссылку для входа",
    registrationLinkSent: "Проверьте почту: ссылка действует 10 минут.",
    registrationLinkExplanation: "Вы получите защищённую ссылку, чтобы завершить регистрацию и войти в аккаунт.",
    verifyingAccess: "Проверка ссылки для входа...",
    completingRegistration: "Завершение регистрации...",
    accessSuccess: "Вход выполнен.",
    registrationSuccess: "Регистрация завершена.",
    invalidAccessLink: "Ссылка для входа недействительна или срок её действия истёк. Запросите новую.",
    invalidRegistrationLink: "Ссылка для регистрации недействительна или срок её действия истёк. Запросите новую.",
    missingAccessLink: "Ссылка для входа отсутствует. Запросите новую, чтобы продолжить.",
    missingRegistrationLink: "Ссылка для регистрации отсутствует. Запросите новую, чтобы продолжить.",
  },
  zh: {
    loginDescription: "输入电子邮箱以接收登录链接。",
    linkExpiry: "链接将在 10 分钟后自动失效。",
    accessLinkSent: "如果此邮箱已注册，您将收到一个有效期为 10 分钟的链接。",
    sendAccessLink: "发送登录链接",
    registrationLinkSent: "请查看邮箱：链接有效期为 10 分钟。",
    registrationLinkExplanation: "您将收到一个安全链接，用于完成注册并访问账户。",
    verifyingAccess: "正在验证登录链接...",
    completingRegistration: "正在完成注册...",
    accessSuccess: "登录成功。",
    registrationSuccess: "注册完成。",
    invalidAccessLink: "此登录链接无效或已过期。请重新申请。",
    invalidRegistrationLink: "此注册链接无效或已过期。请重新申请。",
    missingAccessLink: "未找到登录链接。请重新申请后继续。",
    missingRegistrationLink: "未找到注册链接。请重新申请后继续。",
  },
  ja: {
    loginDescription: "ログインリンクを受け取るメールアドレスを入力してください。",
    linkExpiry: "リンクは10分後に自動的に期限切れになります。",
    accessLinkSent: "このメールアドレスが登録済みの場合、10分間有効なリンクが届きます。",
    sendAccessLink: "ログインリンクを送信",
    registrationLinkSent: "メールを確認してください。リンクの有効期限は10分です。",
    registrationLinkExplanation: "登録を完了してアカウントにアクセスするための安全なリンクが届きます。",
    verifyingAccess: "ログインリンクを確認しています...",
    completingRegistration: "登録を完了しています...",
    accessSuccess: "ログインしました。",
    registrationSuccess: "登録が完了しました。",
    invalidAccessLink: "このログインリンクは無効か、有効期限が切れています。新しいリンクをリクエストしてください。",
    invalidRegistrationLink: "この登録リンクは無効か、有効期限が切れています。新しいリンクをリクエストしてください。",
    missingAccessLink: "ログインリンクがありません。続行するには新しいリンクをリクエストしてください。",
    missingRegistrationLink: "登録リンクがありません。続行するには新しいリンクをリクエストしてください。",
  },
  ko: {
    loginDescription: "로그인 링크를 받을 이메일 주소를 입력하세요.",
    linkExpiry: "링크는 10분 후 자동으로 만료됩니다.",
    accessLinkSent: "이 이메일 주소가 등록되어 있으면 10분 동안 유효한 링크를 보내드립니다.",
    sendAccessLink: "로그인 링크 보내기",
    registrationLinkSent: "이메일을 확인하세요. 링크는 10분 동안 유효합니다.",
    registrationLinkExplanation: "가입을 완료하고 계정에 액세스할 수 있는 보안 링크를 보내드립니다.",
    verifyingAccess: "로그인 링크를 확인하는 중...",
    completingRegistration: "가입을 완료하는 중...",
    accessSuccess: "로그인되었습니다.",
    registrationSuccess: "가입이 완료되었습니다.",
    invalidAccessLink: "로그인 링크가 유효하지 않거나 만료되었습니다. 새 링크를 요청하세요.",
    invalidRegistrationLink: "가입 링크가 유효하지 않거나 만료되었습니다. 새 링크를 요청하세요.",
    missingAccessLink: "로그인 링크가 없습니다. 계속하려면 새 링크를 요청하세요.",
    missingRegistrationLink: "가입 링크가 없습니다. 계속하려면 새 링크를 요청하세요.",
  },
  ar: {
    loginDescription: "أدخل بريدك الإلكتروني لتلقي رابط تسجيل الدخول.",
    linkExpiry: "تنتهي صلاحية الرابط تلقائيًا بعد 10 دقائق.",
    accessLinkSent: "إذا كان هذا البريد مسجلًا، فستتلقى رابطًا صالحًا لمدة 10 دقائق.",
    sendAccessLink: "إرسال رابط تسجيل الدخول",
    registrationLinkSent: "تحقق من بريدك الإلكتروني: الرابط صالح لمدة 10 دقائق.",
    registrationLinkExplanation: "ستتلقى رابطًا آمنًا لإكمال التسجيل والوصول إلى حسابك.",
    verifyingAccess: "جارٍ التحقق من رابط تسجيل الدخول...",
    completingRegistration: "جارٍ إكمال التسجيل...",
    accessSuccess: "تم تسجيل الدخول.",
    registrationSuccess: "اكتمل التسجيل.",
    invalidAccessLink: "رابط تسجيل الدخول غير صالح أو انتهت صلاحيته. اطلب رابطًا جديدًا.",
    invalidRegistrationLink: "رابط التسجيل غير صالح أو انتهت صلاحيته. اطلب رابطًا جديدًا.",
    missingAccessLink: "رابط تسجيل الدخول غير موجود. اطلب رابطًا جديدًا للمتابعة.",
    missingRegistrationLink: "رابط التسجيل غير موجود. اطلب رابطًا جديدًا للمتابعة.",
  },
  hi: {
    loginDescription: "साइन-इन लिंक पाने के लिए अपना ईमेल पता दर्ज करें।",
    linkExpiry: "लिंक 10 मिनट बाद अपने-आप समाप्त हो जाता है।",
    accessLinkSent: "यदि यह ईमेल पता पंजीकृत है, तो आपको 10 मिनट तक मान्य लिंक मिलेगा।",
    sendAccessLink: "साइन-इन लिंक भेजें",
    registrationLinkSent: "अपना ईमेल देखें: लिंक 10 मिनट तक मान्य है।",
    registrationLinkExplanation: "पंजीकरण पूरा करने और अपने खाते में जाने के लिए आपको एक सुरक्षित लिंक मिलेगा।",
    verifyingAccess: "साइन-इन लिंक की जाँच हो रही है...",
    completingRegistration: "पंजीकरण पूरा हो रहा है...",
    accessSuccess: "आप साइन इन हो गए हैं।",
    registrationSuccess: "पंजीकरण पूरा हुआ।",
    invalidAccessLink: "यह साइन-इन लिंक अमान्य है या समाप्त हो गया है। नया लिंक माँगें।",
    invalidRegistrationLink: "यह पंजीकरण लिंक अमान्य है या समाप्त हो गया है। नया लिंक माँगें।",
    missingAccessLink: "साइन-इन लिंक नहीं मिला। आगे बढ़ने के लिए नया लिंक माँगें।",
    missingRegistrationLink: "पंजीकरण लिंक नहीं मिला। आगे बढ़ने के लिए नया लिंक माँगें।",
  },
  pl: {
    loginDescription: "Wpisz adres e-mail, aby otrzymać link do logowania.",
    linkExpiry: "Link wygaśnie automatycznie po 10 minutach.",
    accessLinkSent: "Jeśli ten adres e-mail jest zarejestrowany, otrzymasz link ważny przez 10 minut.",
    sendAccessLink: "Wyślij link do logowania",
    registrationLinkSent: "Sprawdź pocztę: link jest ważny przez 10 minut.",
    registrationLinkExplanation: "Otrzymasz bezpieczny link, aby dokończyć rejestrację i uzyskać dostęp do konta.",
    verifyingAccess: "Weryfikowanie linku do logowania...",
    completingRegistration: "Kończenie rejestracji...",
    accessSuccess: "Zalogowano.",
    registrationSuccess: "Rejestracja zakończona.",
    invalidAccessLink: "Link do logowania jest nieprawidłowy lub wygasł. Poproś o nowy.",
    invalidRegistrationLink: "Link rejestracyjny jest nieprawidłowy lub wygasł. Poproś o nowy.",
    missingAccessLink: "Brakuje linku do logowania. Poproś o nowy, aby kontynuować.",
    missingRegistrationLink: "Brakuje linku rejestracyjnego. Poproś o nowy, aby kontynuować.",
  },
  nl: {
    loginDescription: "Vul je e-mailadres in om een aanmeldlink te ontvangen.",
    linkExpiry: "De link verloopt automatisch na 10 minuten.",
    accessLinkSent: "Als dit e-mailadres geregistreerd is, ontvang je een link die 10 minuten geldig is.",
    sendAccessLink: "Aanmeldlink versturen",
    registrationLinkSent: "Controleer je e-mail: de link is 10 minuten geldig.",
    registrationLinkExplanation: "Je ontvangt een beveiligde link om je registratie te voltooien en toegang te krijgen tot je account.",
    verifyingAccess: "Aanmeldlink controleren...",
    completingRegistration: "Registratie voltooien...",
    accessSuccess: "Je bent aangemeld.",
    registrationSuccess: "Registratie voltooid.",
    invalidAccessLink: "Deze aanmeldlink is ongeldig of verlopen. Vraag een nieuwe aan.",
    invalidRegistrationLink: "Deze registratielink is ongeldig of verlopen. Vraag een nieuwe aan.",
    missingAccessLink: "De aanmeldlink ontbreekt. Vraag een nieuwe aan om verder te gaan.",
    missingRegistrationLink: "De registratielink ontbreekt. Vraag een nieuwe aan om verder te gaan.",
  },
  tr: {
    loginDescription: "Giriş bağlantısı almak için e-posta adresinizi girin.",
    linkExpiry: "Bağlantının süresi 10 dakika sonra otomatik olarak dolar.",
    accessLinkSent: "Bu e-posta adresi kayıtlıysa 10 dakika geçerli bir bağlantı alırsınız.",
    sendAccessLink: "Giriş bağlantısı gönder",
    registrationLinkSent: "E-postanızı kontrol edin: bağlantı 10 dakika geçerlidir.",
    registrationLinkExplanation: "Kaydı tamamlamak ve hesabınıza erişmek için güvenli bir bağlantı alacaksınız.",
    verifyingAccess: "Giriş bağlantısı doğrulanıyor...",
    completingRegistration: "Kayıt tamamlanıyor...",
    accessSuccess: "Giriş yapıldı.",
    registrationSuccess: "Kayıt tamamlandı.",
    invalidAccessLink: "Bu giriş bağlantısı geçersiz veya süresi dolmuş. Yeni bir bağlantı isteyin.",
    invalidRegistrationLink: "Bu kayıt bağlantısı geçersiz veya süresi dolmuş. Yeni bir bağlantı isteyin.",
    missingAccessLink: "Giriş bağlantısı eksik. Devam etmek için yeni bir bağlantı isteyin.",
    missingRegistrationLink: "Kayıt bağlantısı eksik. Devam etmek için yeni bir bağlantı isteyin.",
  },
  sv: {
    loginDescription: "Ange din e-postadress för att få en inloggningslänk.",
    linkExpiry: "Länken upphör automatiskt att gälla efter 10 minuter.",
    accessLinkSent: "Om e-postadressen är registrerad får du en länk som gäller i 10 minuter.",
    sendAccessLink: "Skicka inloggningslänk",
    registrationLinkSent: "Kontrollera din e-post: länken gäller i 10 minuter.",
    registrationLinkExplanation: "Du får en säker länk för att slutföra registreringen och komma åt ditt konto.",
    verifyingAccess: "Verifierar inloggningslänken...",
    completingRegistration: "Slutför registreringen...",
    accessSuccess: "Du är inloggad.",
    registrationSuccess: "Registreringen är klar.",
    invalidAccessLink: "Inloggningslänken är ogiltig eller har gått ut. Begär en ny.",
    invalidRegistrationLink: "Registreringslänken är ogiltig eller har gått ut. Begär en ny.",
    missingAccessLink: "Inloggningslänken saknas. Begär en ny för att fortsätta.",
    missingRegistrationLink: "Registreringslänken saknas. Begär en ny för att fortsätta.",
  },
  da: {
    loginDescription: "Indtast din e-mailadresse for at modtage et loginlink.",
    linkExpiry: "Linket udløber automatisk efter 10 minutter.",
    accessLinkSent: "Hvis e-mailadressen er registreret, modtager du et link, der er gyldigt i 10 minutter.",
    sendAccessLink: "Send loginlink",
    registrationLinkSent: "Tjek din e-mail: linket er gyldigt i 10 minutter.",
    registrationLinkExplanation: "Du modtager et sikkert link til at fuldføre registreringen og få adgang til din konto.",
    verifyingAccess: "Kontrollerer loginlink...",
    completingRegistration: "Fuldfører registreringen...",
    accessSuccess: "Du er logget ind.",
    registrationSuccess: "Registreringen er fuldført.",
    invalidAccessLink: "Loginlinket er ugyldigt eller udløbet. Bed om et nyt.",
    invalidRegistrationLink: "Registreringslinket er ugyldigt eller udløbet. Bed om et nyt.",
    missingAccessLink: "Loginlinket mangler. Bed om et nyt for at fortsætte.",
    missingRegistrationLink: "Registreringslinket mangler. Bed om et nyt for at fortsætte.",
  },
  no: {
    loginDescription: "Skriv inn e-postadressen din for å få en påloggingslenke.",
    linkExpiry: "Lenken utløper automatisk etter 10 minutter.",
    accessLinkSent: "Hvis e-postadressen er registrert, får du en lenke som er gyldig i 10 minutter.",
    sendAccessLink: "Send påloggingslenke",
    registrationLinkSent: "Sjekk e-posten din: lenken er gyldig i 10 minutter.",
    registrationLinkExplanation: "Du får en sikker lenke for å fullføre registreringen og få tilgang til kontoen din.",
    verifyingAccess: "Bekrefter påloggingslenken...",
    completingRegistration: "Fullfører registreringen...",
    accessSuccess: "Du er logget inn.",
    registrationSuccess: "Registreringen er fullført.",
    invalidAccessLink: "Påloggingslenken er ugyldig eller utløpt. Be om en ny.",
    invalidRegistrationLink: "Registreringslenken er ugyldig eller utløpt. Be om en ny.",
    missingAccessLink: "Påloggingslenken mangler. Be om en ny for å fortsette.",
    missingRegistrationLink: "Registreringslenken mangler. Be om en ny for å fortsette.",
  },
  fi: {
    loginDescription: "Anna sähköpostiosoitteesi, niin saat kirjautumislinkin.",
    linkExpiry: "Linkki vanhenee automaattisesti 10 minuutin kuluttua.",
    accessLinkSent: "Jos sähköpostiosoite on rekisteröity, saat linkin, joka on voimassa 10 minuuttia.",
    sendAccessLink: "Lähetä kirjautumislinkki",
    registrationLinkSent: "Tarkista sähköpostisi: linkki on voimassa 10 minuuttia.",
    registrationLinkExplanation: "Saat suojatun linkin rekisteröinnin viimeistelyyn ja tilillesi kirjautumiseen.",
    verifyingAccess: "Tarkistetaan kirjautumislinkkiä...",
    completingRegistration: "Viimeistellään rekisteröintiä...",
    accessSuccess: "Kirjautuminen onnistui.",
    registrationSuccess: "Rekisteröinti valmis.",
    invalidAccessLink: "Kirjautumislinkki on virheellinen tai vanhentunut. Pyydä uusi linkki.",
    invalidRegistrationLink: "Rekisteröintilinkki on virheellinen tai vanhentunut. Pyydä uusi linkki.",
    missingAccessLink: "Kirjautumislinkki puuttuu. Pyydä uusi linkki jatkaaksesi.",
    missingRegistrationLink: "Rekisteröintilinkki puuttuu. Pyydä uusi linkki jatkaaksesi.",
  },
  uk: {
    loginDescription: "Введіть електронну пошту, щоб отримати посилання для входу.",
    linkExpiry: "Термін дії посилання автоматично завершується через 10 хвилин.",
    accessLinkSent: "Якщо цю адресу зареєстровано, ви отримаєте посилання, дійсне протягом 10 хвилин.",
    sendAccessLink: "Надіслати посилання для входу",
    registrationLinkSent: "Перевірте пошту: посилання дійсне протягом 10 хвилин.",
    registrationLinkExplanation: "Ви отримаєте захищене посилання, щоб завершити реєстрацію та увійти до облікового запису.",
    verifyingAccess: "Перевірка посилання для входу...",
    completingRegistration: "Завершення реєстрації...",
    accessSuccess: "Вхід виконано.",
    registrationSuccess: "Реєстрацію завершено.",
    invalidAccessLink: "Посилання для входу недійсне або термін його дії минув. Запросіть нове.",
    invalidRegistrationLink: "Посилання для реєстрації недійсне або термін його дії минув. Запросіть нове.",
    missingAccessLink: "Посилання для входу відсутнє. Запросіть нове, щоб продовжити.",
    missingRegistrationLink: "Посилання для реєстрації відсутнє. Запросіть нове, щоб продовжити.",
  },
  cs: {
    loginDescription: "Zadejte svůj e-mail a obdržíte přihlašovací odkaz.",
    linkExpiry: "Platnost odkazu automaticky vyprší po 10 minutách.",
    accessLinkSent: "Pokud je tato e-mailová adresa registrovaná, obdržíte odkaz platný 10 minut.",
    sendAccessLink: "Odeslat přihlašovací odkaz",
    registrationLinkSent: "Zkontrolujte e-mail: odkaz platí 10 minut.",
    registrationLinkExplanation: "Obdržíte zabezpečený odkaz k dokončení registrace a přístupu ke svému účtu.",
    verifyingAccess: "Ověřování přihlašovacího odkazu...",
    completingRegistration: "Dokončování registrace...",
    accessSuccess: "Přihlášení proběhlo úspěšně.",
    registrationSuccess: "Registrace je dokončena.",
    invalidAccessLink: "Tento přihlašovací odkaz je neplatný nebo jeho platnost vypršela. Požádejte o nový.",
    invalidRegistrationLink: "Tento registrační odkaz je neplatný nebo jeho platnost vypršela. Požádejte o nový.",
    missingAccessLink: "Přihlašovací odkaz chybí. Požádejte o nový a pokračujte.",
    missingRegistrationLink: "Registrační odkaz chybí. Požádejte o nový a pokračujte.",
  },
};

export function localizedAuthError(message: string, copy: AuthFlowCopy) {
  if (message === "Invalid or expired access token") return copy.invalidAccessLink;
  if (message === "Invalid registration token" || message === "Invalid or expired registration token") {
    return copy.invalidRegistrationLink;
  }
  return message;
}
