export type CommunityMarketplaceCopy = {
  checkoutNotice: string;
  refreshPurchases: string;
  title: string;
  description: string;
  sellTemplate: string;
  stripeMissingUrl: string;
  removedForReview: string;
  retryError: string;
  reviewSaved: string;
  codeUnavailable: string;
  copyError: string;
  downloadSuccess: string;
  manifestCopied: string;
  codeCopied: string;
  productError: string;
  ownProductError: string;
  seller: string;
  copyCode: string;
  openEditor: string;
  downloadTemplate: string;
  openingPayment: string;
  buy: string;
  loginToBuy: string;
  moderationPrompt: string;
  removeListing: string;
  noListings: string;
  loadError: string;
  updating: string;
  retry: string;
  purchasesTitle: string;
  purchasesDescription: string;
  orderStatus: string;
  statusPending: string;
  statusPaid: string;
  statusRefunded: string;
  paymentPending: string;
  suspendedAccess: string;
  updateRating: string;
  rateTemplate: string;
  ratingLabel: string;
  stars: string;
  optionalComment: string;
  submitRating: string;
  refunded: string;
  noPurchases: string;
  loadingOrders: string;
  errorLoadingOrders: string;
};

export const communityMarketplaceCopy: Record<string, CommunityMarketplaceCopy> = {
  en: {
    checkoutNotice: "Payment complete? Access will be enabled once Stripe confirms the payment.", refreshPurchases: "Refresh purchases",
    title: "Community templates", description: "Products published by developers. Code is available only after payment is confirmed. Tatik retains 15% of the price; the seller receives the remaining 85% before payment-provider fees.",
    sellTemplate: "Sell your template", stripeMissingUrl: "Stripe did not return a payment link.", removedForReview: "Template removed from the marketplace for review.",
    retryError: "Could not refresh the marketplace. Please try again shortly.", reviewSaved: "Review saved. Thank you for your feedback!",
    codeUnavailable: "Template code is unavailable.", copyError: "Could not copy the template.", downloadSuccess: "Template downloaded.",
    manifestCopied: "Complete project manifest copied. Use “Open in editor” to load the files separately.", codeCopied: "Code copied.",
    productError: "Could not retrieve the purchased template.", ownProductError: "Could not retrieve your template.", seller: "by",
    copyCode: "Copy code", openEditor: "Open in editor", downloadTemplate: "Download template", openingPayment: "Opening payment…", buy: "Buy", loginToBuy: "Sign in to buy",
    moderationPrompt: "Legal or ethical reason for removing this template:", removeListing: "Remove from marketplace",
    noListings: "No community templates have been published yet.", loadError: "Community templates are temporarily unavailable.", updating: "Refreshing…", retry: "Retry",
    purchasesTitle: "Your community purchases", purchasesDescription: "Copying and downloading are authorized by the server only for paid, non-refunded orders.",
    orderStatus: "Status", statusPending: "Pending", statusPaid: "Paid", statusRefunded: "Refunded", paymentPending: "Payment is awaiting provider confirmation; the code is not available yet.",
    suspendedAccess: "Access temporarily suspended: this template was removed from the marketplace for administrative review.",
    updateRating: "Update your rating", rateTemplate: "Rate this template (purchasers only)", ratingLabel: "Rating from 1 to 5", stars: "stars",
    optionalComment: "Optional comment", submitRating: "Submit rating", refunded: "Order refunded: access to the code has been revoked.",
    noPurchases: "You have no community purchases yet.", loadingOrders: "Loading purchases…", errorLoadingOrders: "Could not load purchases.",
  },
  it: {
    checkoutNotice: "Pagamento completato? L’accesso si attiva appena Stripe conferma il pagamento.", refreshPurchases: "Aggiorna acquisti",
    title: "Template della community", description: "Prodotti pubblicati dagli sviluppatori. Il codice è disponibile solo dopo la conferma del pagamento. Tatik trattiene il 15% del prezzo; il venditore riceve il restante 85% prima delle commissioni del provider di pagamento.",
    sellTemplate: "Vendi il tuo template", stripeMissingUrl: "Stripe non ha restituito il link di pagamento.", removedForReview: "Template rimosso dal marketplace per una verifica.",
    retryError: "Non è stato possibile aggiornare il marketplace. Riprova tra poco.", reviewSaved: "Recensione salvata. Grazie per il feedback!",
    codeUnavailable: "Codice del template non disponibile.", copyError: "Impossibile copiare il template.", downloadSuccess: "Template scaricato.",
    manifestCopied: "Manifest completo copiato. Usa «Apri nell’editor» per caricare i file separatamente.", codeCopied: "Codice copiato.",
    productError: "Impossibile recuperare il template acquistato.", ownProductError: "Impossibile recuperare il tuo template.", seller: "di",
    copyCode: "Copia codice", openEditor: "Apri nell’editor", downloadTemplate: "Scarica template", openingPayment: "Apertura pagamento…", buy: "Acquista", loginToBuy: "Accedi per acquistare",
    moderationPrompt: "Motivo legale o etico per rimuovere il template:", removeListing: "Rimuovi dal marketplace",
    noListings: "Non è ancora stato pubblicato alcun template della community.", loadError: "Al momento non è possibile caricare i template della community.", updating: "Aggiornamento…", retry: "Riprova",
    purchasesTitle: "I tuoi acquisti dalla community", purchasesDescription: "Il server autorizza copia e download solo per ordini pagati e non rimborsati.",
    orderStatus: "Stato", statusPending: "In attesa", statusPaid: "Pagato", statusRefunded: "Rimborsato", paymentPending: "Pagamento in attesa di conferma dal provider; il codice non è ancora accessibile.",
    suspendedAccess: "Accesso temporaneamente sospeso: il template è stato rimosso dal marketplace per una verifica amministrativa.",
    updateRating: "Aggiorna la tua valutazione", rateTemplate: "Valuta il template (solo per gli acquirenti)", ratingLabel: "Valutazione da 1 a 5", stars: "stelle",
    optionalComment: "Commento facoltativo", submitRating: "Invia valutazione", refunded: "Ordine rimborsato: l’accesso al codice è stato revocato.",
    noPurchases: "Non hai ancora acquisti dalla community.", loadingOrders: "Caricamento acquisti…", errorLoadingOrders: "Impossibile caricare gli acquisti.",
  },
  es: {
    checkoutNotice: "¿Se completó el pago? El acceso se activará cuando Stripe confirme el pago.", refreshPurchases: "Actualizar compras",
    title: "Plantillas de la comunidad", description: "Productos publicados por desarrolladores. El código solo está disponible tras confirmar el pago. Tatik retiene el 15 % del precio; el vendedor recibe el 85 % restante antes de las comisiones del proveedor de pago.",
    sellTemplate: "Vende tu plantilla", stripeMissingUrl: "Stripe no proporcionó un enlace de pago.", removedForReview: "Plantilla retirada del marketplace para su revisión.",
    retryError: "No se pudo actualizar el marketplace. Inténtalo de nuevo dentro de unos minutos.", reviewSaved: "Reseña guardada. ¡Gracias por tus comentarios!",
    codeUnavailable: "El código de la plantilla no está disponible.", copyError: "No se pudo copiar la plantilla.", downloadSuccess: "Plantilla descargada.",
    manifestCopied: "Manifiesto completo copiado. Usa «Abrir en el editor» para cargar los archivos por separado.", codeCopied: "Código copiado.",
    productError: "No se pudo recuperar la plantilla comprada.", ownProductError: "No se pudo recuperar tu plantilla.", seller: "por",
    copyCode: "Copiar código", openEditor: "Abrir en el editor", downloadTemplate: "Descargar plantilla", openingPayment: "Abriendo el pago…", buy: "Comprar", loginToBuy: "Inicia sesión para comprar",
    moderationPrompt: "Motivo legal o ético para retirar esta plantilla:", removeListing: "Retirar del marketplace",
    noListings: "Todavía no se han publicado plantillas de la comunidad.", loadError: "No se pueden cargar las plantillas de la comunidad en este momento.", updating: "Actualizando…", retry: "Reintentar",
    purchasesTitle: "Tus compras de la comunidad", purchasesDescription: "El servidor solo autoriza copiar y descargar pedidos pagados y no reembolsados.",
    orderStatus: "Estado", statusPending: "Pendiente", statusPaid: "Pagado", statusRefunded: "Reembolsado", paymentPending: "El pago espera la confirmación del proveedor; el código todavía no está disponible.",
    suspendedAccess: "Acceso suspendido temporalmente: la plantilla se retiró del marketplace para una revisión administrativa.",
    updateRating: "Actualizar tu valoración", rateTemplate: "Valorar plantilla (solo compradores)", ratingLabel: "Valoración de 1 a 5", stars: "estrellas",
    optionalComment: "Comentario opcional", submitRating: "Enviar valoración", refunded: "Pedido reembolsado: se revocó el acceso al código.",
    noPurchases: "Aún no tienes compras de la comunidad.", loadingOrders: "Cargando compras…", errorLoadingOrders: "No se pudieron cargar las compras.",
  },
  fr: {
    checkoutNotice: "Paiement effectué ? L’accès sera activé dès que Stripe aura confirmé le paiement.", refreshPurchases: "Actualiser les achats",
    title: "Modèles de la communauté", description: "Produits publiés par des développeurs. Le code n’est disponible qu’après confirmation du paiement. Tatik retient 15 % du prix ; le vendeur reçoit les 85 % restants avant les frais du prestataire de paiement.",
    sellTemplate: "Vendre votre modèle", stripeMissingUrl: "Stripe n’a pas fourni de lien de paiement.", removedForReview: "Modèle retiré de la marketplace pour vérification.",
    retryError: "Impossible d’actualiser la marketplace. Réessayez dans quelques instants.", reviewSaved: "Avis enregistré. Merci pour votre retour !",
    codeUnavailable: "Le code du modèle est indisponible.", copyError: "Impossible de copier le modèle.", downloadSuccess: "Modèle téléchargé.",
    manifestCopied: "Manifeste complet copié. Utilisez « Ouvrir dans l’éditeur » pour charger les fichiers séparément.", codeCopied: "Code copié.",
    productError: "Impossible de récupérer le modèle acheté.", ownProductError: "Impossible de récupérer votre modèle.", seller: "par",
    copyCode: "Copier le code", openEditor: "Ouvrir dans l’éditeur", downloadTemplate: "Télécharger le modèle", openingPayment: "Ouverture du paiement…", buy: "Acheter", loginToBuy: "Connectez-vous pour acheter",
    moderationPrompt: "Motif juridique ou éthique du retrait de ce modèle :", removeListing: "Retirer de la marketplace",
    noListings: "Aucun modèle de la communauté n’a encore été publié.", loadError: "Impossible de charger les modèles de la communauté pour le moment.", updating: "Actualisation…", retry: "Réessayer",
    purchasesTitle: "Vos achats de la communauté", purchasesDescription: "Le serveur autorise la copie et le téléchargement uniquement pour les commandes payées et non remboursées.",
    orderStatus: "Statut", statusPending: "En attente", statusPaid: "Payé", statusRefunded: "Remboursé", paymentPending: "Paiement en attente de confirmation du prestataire ; le code n’est pas encore disponible.",
    suspendedAccess: "Accès temporairement suspendu : le modèle a été retiré de la marketplace pour vérification administrative.",
    updateRating: "Modifier votre évaluation", rateTemplate: "Évaluer le modèle (acheteurs uniquement)", ratingLabel: "Évaluation de 1 à 5", stars: "étoiles",
    optionalComment: "Commentaire facultatif", submitRating: "Envoyer l’évaluation", refunded: "Commande remboursée : l’accès au code a été révoqué.",
    noPurchases: "Vous n’avez pas encore acheté de modèle de la communauté.", loadingOrders: "Chargement des achats…", errorLoadingOrders: "Impossible de charger les achats.",
  },
  de: {
    checkoutNotice: "Zahlung abgeschlossen? Der Zugriff wird freigeschaltet, sobald Stripe die Zahlung bestätigt.", refreshPurchases: "Käufe aktualisieren",
    title: "Community-Vorlagen", description: "Von Entwicklern veröffentlichte Produkte. Der Code ist erst nach bestätigter Zahlung verfügbar. Tatik behält 15 % des Preises ein; der Verkäufer erhält die übrigen 85 % vor den Gebühren des Zahlungsanbieters.",
    sellTemplate: "Vorlage verkaufen", stripeMissingUrl: "Stripe hat keinen Zahlungslink zurückgegeben.", removedForReview: "Vorlage zur Prüfung aus dem Marketplace entfernt.",
    retryError: "Der Marketplace konnte nicht aktualisiert werden. Bitte versuche es gleich noch einmal.", reviewSaved: "Bewertung gespeichert. Vielen Dank für dein Feedback!",
    codeUnavailable: "Vorlagencode nicht verfügbar.", copyError: "Vorlage konnte nicht kopiert werden.", downloadSuccess: "Vorlage heruntergeladen.",
    manifestCopied: "Vollständiges Manifest kopiert. Verwende „Im Editor öffnen“, um die Dateien einzeln zu laden.", codeCopied: "Code kopiert.",
    productError: "Gekaufte Vorlage konnte nicht abgerufen werden.", ownProductError: "Deine Vorlage konnte nicht abgerufen werden.", seller: "von",
    copyCode: "Code kopieren", openEditor: "Im Editor öffnen", downloadTemplate: "Vorlage herunterladen", openingPayment: "Zahlung wird geöffnet…", buy: "Kaufen", loginToBuy: "Zum Kaufen anmelden",
    moderationPrompt: "Rechtlicher oder ethischer Grund für die Entfernung dieser Vorlage:", removeListing: "Aus dem Marketplace entfernen",
    noListings: "Es wurden noch keine Community-Vorlagen veröffentlicht.", loadError: "Community-Vorlagen können derzeit nicht geladen werden.", updating: "Wird aktualisiert…", retry: "Erneut versuchen",
    purchasesTitle: "Deine Community-Käufe", purchasesDescription: "Der Server erlaubt Kopieren und Herunterladen nur bei bezahlten, nicht erstatteten Bestellungen.",
    orderStatus: "Status", statusPending: "Ausstehend", statusPaid: "Bezahlt", statusRefunded: "Erstattet", paymentPending: "Zahlung wartet auf Bestätigung durch den Anbieter; der Code ist noch nicht verfügbar.",
    suspendedAccess: "Zugriff vorübergehend ausgesetzt: Die Vorlage wurde zur administrativen Prüfung aus dem Marketplace entfernt.",
    updateRating: "Bewertung aktualisieren", rateTemplate: "Vorlage bewerten (nur Käufer)", ratingLabel: "Bewertung von 1 bis 5", stars: "Sterne",
    optionalComment: "Optionaler Kommentar", submitRating: "Bewertung senden", refunded: "Bestellung erstattet: Der Zugriff auf den Code wurde widerrufen.",
    noPurchases: "Du hast noch keine Community-Vorlagen gekauft.", loadingOrders: "Käufe werden geladen…", errorLoadingOrders: "Käufe konnten nicht geladen werden.",
  },
  pt: {
    checkoutNotice: "Pagamento concluído? O acesso será ativado assim que a Stripe confirmar o pagamento.", refreshPurchases: "Atualizar compras",
    title: "Modelos da comunidade", description: "Produtos publicados por programadores. O código só fica disponível após a confirmação do pagamento. A Tatik retém 15% do preço; o vendedor recebe os restantes 85% antes das taxas do fornecedor de pagamentos.",
    sellTemplate: "Venda o seu modelo", stripeMissingUrl: "A Stripe não devolveu uma ligação de pagamento.", removedForReview: "Modelo removido do marketplace para análise.",
    retryError: "Não foi possível atualizar o marketplace. Tente novamente dentro de momentos.", reviewSaved: "Avaliação guardada. Obrigado pelo seu feedback!",
    codeUnavailable: "Código do modelo indisponível.", copyError: "Não foi possível copiar o modelo.", downloadSuccess: "Modelo transferido.",
    manifestCopied: "Manifesto completo copiado. Use «Abrir no editor» para carregar os ficheiros separadamente.", codeCopied: "Código copiado.",
    productError: "Não foi possível obter o modelo comprado.", ownProductError: "Não foi possível obter o seu modelo.", seller: "por",
    copyCode: "Copiar código", openEditor: "Abrir no editor", downloadTemplate: "Transferir modelo", openingPayment: "A abrir o pagamento…", buy: "Comprar", loginToBuy: "Inicie sessão para comprar",
    moderationPrompt: "Motivo legal ou ético para remover este modelo:", removeListing: "Remover do marketplace",
    noListings: "Ainda não foram publicados modelos da comunidade.", loadError: "Não é possível carregar os modelos da comunidade neste momento.", updating: "A atualizar…", retry: "Tentar novamente",
    purchasesTitle: "As suas compras da comunidade", purchasesDescription: "O servidor só autoriza copiar e transferir encomendas pagas e não reembolsadas.",
    orderStatus: "Estado", statusPending: "Pendente", statusPaid: "Pago", statusRefunded: "Reembolsado", paymentPending: "O pagamento aguarda confirmação do fornecedor; o código ainda não está disponível.",
    suspendedAccess: "Acesso temporariamente suspenso: o modelo foi removido do marketplace para análise administrativa.",
    updateRating: "Atualizar avaliação", rateTemplate: "Avaliar modelo (apenas compradores)", ratingLabel: "Avaliação de 1 a 5", stars: "estrelas",
    optionalComment: "Comentário opcional", submitRating: "Enviar avaliação", refunded: "Encomenda reembolsada: o acesso ao código foi revogado.",
    noPurchases: "Ainda não tem compras da comunidade.", loadingOrders: "A carregar compras…", errorLoadingOrders: "Não foi possível carregar as compras.",
  },
  ru: {
    checkoutNotice: "Оплата завершена? Доступ откроется после подтверждения оплаты Stripe.", refreshPurchases: "Обновить покупки",
    title: "Шаблоны сообщества", description: "Продукты, опубликованные разработчиками. Код доступен только после подтверждения оплаты. Tatik удерживает 15% цены; продавец получает оставшиеся 85% до вычета комиссии платёжного провайдера.",
    sellTemplate: "Продать шаблон", stripeMissingUrl: "Stripe не вернул ссылку на оплату.", removedForReview: "Шаблон удалён с маркетплейса для проверки.",
    retryError: "Не удалось обновить маркетплейс. Повторите попытку позже.", reviewSaved: "Отзыв сохранён. Спасибо за обратную связь!",
    codeUnavailable: "Код шаблона недоступен.", copyError: "Не удалось скопировать шаблон.", downloadSuccess: "Шаблон скачан.",
    manifestCopied: "Полный манифест скопирован. Используйте «Открыть в редакторе», чтобы загрузить файлы отдельно.", codeCopied: "Код скопирован.",
    productError: "Не удалось получить купленный шаблон.", ownProductError: "Не удалось получить ваш шаблон.", seller: "автор",
    copyCode: "Скопировать код", openEditor: "Открыть в редакторе", downloadTemplate: "Скачать шаблон", openingPayment: "Открытие оплаты…", buy: "Купить", loginToBuy: "Войдите, чтобы купить",
    moderationPrompt: "Юридическая или этическая причина удаления шаблона:", removeListing: "Удалить с маркетплейса",
    noListings: "Шаблоны сообщества пока не опубликованы.", loadError: "Сейчас не удаётся загрузить шаблоны сообщества.", updating: "Обновление…", retry: "Повторить",
    purchasesTitle: "Ваши покупки сообщества", purchasesDescription: "Сервер разрешает копирование и скачивание только для оплаченных и не возвращённых заказов.",
    orderStatus: "Статус", statusPending: "Ожидает", statusPaid: "Оплачен", statusRefunded: "Возврат", paymentPending: "Ожидается подтверждение оплаты провайдером; код пока недоступен.",
    suspendedAccess: "Доступ временно приостановлен: шаблон удалён с маркетплейса для административной проверки.",
    updateRating: "Изменить оценку", rateTemplate: "Оценить шаблон (только покупатели)", ratingLabel: "Оценка от 1 до 5", stars: "звёзд",
    optionalComment: "Комментарий (необязательно)", submitRating: "Отправить отзыв", refunded: "Заказ возвращён: доступ к коду отозван.",
    noPurchases: "У вас пока нет покупок сообщества.", loadingOrders: "Загрузка покупок…", errorLoadingOrders: "Не удалось загрузить покупки.",
  },
  zh: {
    checkoutNotice: "已完成付款？Stripe 确认付款后即可获得访问权限。", refreshPurchases: "刷新购买记录",
    title: "社区模板", description: "由开发者发布的产品。付款确认后才能获取代码。Tatik 收取价格的 15%；卖家在扣除支付服务商费用前获得其余 85%。",
    sellTemplate: "出售你的模板", stripeMissingUrl: "Stripe 未返回付款链接。", removedForReview: "模板已从市场下架以供审核。",
    retryError: "无法刷新市场，请稍后重试。", reviewSaved: "评价已保存，感谢反馈！",
    codeUnavailable: "模板代码不可用。", copyError: "无法复制模板。", downloadSuccess: "模板已下载。",
    manifestCopied: "完整项目清单已复制。使用“在编辑器中打开”分别加载文件。", codeCopied: "代码已复制。",
    productError: "无法获取已购买的模板。", ownProductError: "无法获取你的模板。", seller: "作者",
    copyCode: "复制代码", openEditor: "在编辑器中打开", downloadTemplate: "下载模板", openingPayment: "正在打开付款…", buy: "购买", loginToBuy: "登录后购买",
    moderationPrompt: "下架此模板的法律或伦理原因：", removeListing: "从市场下架",
    noListings: "社区尚未发布模板。", loadError: "暂时无法加载社区模板。", updating: "正在刷新…", retry: "重试",
    purchasesTitle: "你的社区购买记录", purchasesDescription: "服务器仅允许复制和下载已付款且未退款的订单。",
    orderStatus: "状态", statusPending: "待处理", statusPaid: "已付款", statusRefunded: "已退款", paymentPending: "付款正在等待支付服务商确认，暂时无法获取代码。",
    suspendedAccess: "访问暂时暂停：该模板已从市场下架，正在接受管理审核。",
    updateRating: "更新评价", rateTemplate: "评价模板（仅限买家）", ratingLabel: "1 至 5 星评分", stars: "星",
    optionalComment: "可选评论", submitRating: "提交评价", refunded: "订单已退款：代码访问权限已撤销。",
    noPurchases: "你还没有社区购买记录。", loadingOrders: "正在加载购买记录…", errorLoadingOrders: "无法加载购买记录。",
  },
  ja: {
    checkoutNotice: "支払いは完了しましたか？Stripe が支払いを確認するとアクセスが有効になります。", refreshPurchases: "購入履歴を更新",
    title: "コミュニティテンプレート", description: "開発者が公開した商品です。コードは支払いの確認後に利用できます。Tatik は価格の15%を受け取り、販売者には決済サービスの手数料を差し引く前の残り85%が支払われます。",
    sellTemplate: "テンプレートを販売", stripeMissingUrl: "Stripe から決済リンクが返されませんでした。", removedForReview: "確認のためテンプレートをマーケットプレイスから削除しました。",
    retryError: "マーケットプレイスを更新できませんでした。しばらくしてから再試行してください。", reviewSaved: "レビューを保存しました。ご意見ありがとうございます！",
    codeUnavailable: "テンプレートコードを利用できません。", copyError: "テンプレートをコピーできませんでした。", downloadSuccess: "テンプレートをダウンロードしました。",
    manifestCopied: "プロジェクト全体のマニフェストをコピーしました。「エディターで開く」からファイルを個別に読み込んでください。", codeCopied: "コードをコピーしました。",
    productError: "購入したテンプレートを取得できませんでした。", ownProductError: "自分のテンプレートを取得できませんでした。", seller: "販売者",
    copyCode: "コードをコピー", openEditor: "エディターで開く", downloadTemplate: "テンプレートをダウンロード", openingPayment: "決済を開いています…", buy: "購入", loginToBuy: "購入するにはログイン",
    moderationPrompt: "テンプレートを削除する法的または倫理的な理由：", removeListing: "マーケットプレイスから削除",
    noListings: "コミュニティテンプレートはまだ公開されていません。", loadError: "現在コミュニティテンプレートを読み込めません。", updating: "更新中…", retry: "再試行",
    purchasesTitle: "コミュニティでの購入", purchasesDescription: "支払い済みで返金されていない注文のみ、サーバーがコピーとダウンロードを許可します。",
    orderStatus: "ステータス", statusPending: "保留中", statusPaid: "支払い済み", statusRefunded: "返金済み", paymentPending: "決済サービスによる確認待ちです。コードはまだ利用できません。",
    suspendedAccess: "アクセスは一時停止中です。管理者の確認のため、テンプレートがマーケットプレイスから削除されました。",
    updateRating: "評価を更新", rateTemplate: "テンプレートを評価（購入者のみ）", ratingLabel: "1〜5の評価", stars: "つ星",
    optionalComment: "任意のコメント", submitRating: "評価を送信", refunded: "返金済みのため、コードへのアクセスは取り消されました。",
    noPurchases: "コミュニティでの購入はまだありません。", loadingOrders: "購入履歴を読み込み中…", errorLoadingOrders: "購入履歴を読み込めませんでした。",
  },
  ko: {
    checkoutNotice: "결제가 완료되었나요? Stripe가 결제를 확인하면 접근 권한이 활성화됩니다.", refreshPurchases: "구매 내역 새로고침",
    title: "커뮤니티 템플릿", description: "개발자가 게시한 제품입니다. 결제가 확인된 후에만 코드를 이용할 수 있습니다. Tatik은 가격의 15%를 보유하며 판매자는 결제 제공업체 수수료 차감 전 나머지 85%를 받습니다.",
    sellTemplate: "템플릿 판매", stripeMissingUrl: "Stripe에서 결제 링크를 반환하지 않았습니다.", removedForReview: "검토를 위해 템플릿을 마켓플레이스에서 삭제했습니다.",
    retryError: "마켓플레이스를 새로 고칠 수 없습니다. 잠시 후 다시 시도하세요.", reviewSaved: "리뷰를 저장했습니다. 의견을 보내 주셔서 감사합니다!",
    codeUnavailable: "템플릿 코드를 사용할 수 없습니다.", copyError: "템플릿을 복사할 수 없습니다.", downloadSuccess: "템플릿을 다운로드했습니다.",
    manifestCopied: "전체 프로젝트 매니페스트를 복사했습니다. 파일을 각각 불러오려면 ‘편집기에서 열기’를 사용하세요.", codeCopied: "코드를 복사했습니다.",
    productError: "구매한 템플릿을 가져올 수 없습니다.", ownProductError: "내 템플릿을 가져올 수 없습니다.", seller: "판매자",
    copyCode: "코드 복사", openEditor: "편집기에서 열기", downloadTemplate: "템플릿 다운로드", openingPayment: "결제 창 여는 중…", buy: "구매", loginToBuy: "구매하려면 로그인",
    moderationPrompt: "이 템플릿을 삭제하는 법적 또는 윤리적 사유:", removeListing: "마켓플레이스에서 삭제",
    noListings: "아직 게시된 커뮤니티 템플릿이 없습니다.", loadError: "현재 커뮤니티 템플릿을 불러올 수 없습니다.", updating: "새로 고치는 중…", retry: "다시 시도",
    purchasesTitle: "커뮤니티 구매 내역", purchasesDescription: "결제가 완료되고 환불되지 않은 주문만 서버에서 복사 및 다운로드를 허용합니다.",
    orderStatus: "상태", statusPending: "대기 중", statusPaid: "결제 완료", statusRefunded: "환불됨", paymentPending: "결제 제공업체의 확인을 기다리는 중이며 아직 코드를 이용할 수 없습니다.",
    suspendedAccess: "접근이 일시 중지되었습니다. 관리 검토를 위해 템플릿이 마켓플레이스에서 삭제되었습니다.",
    updateRating: "평가 수정", rateTemplate: "템플릿 평가 (구매자 전용)", ratingLabel: "1~5점 평가", stars: "점",
    optionalComment: "선택 댓글", submitRating: "평가 제출", refunded: "주문이 환불되어 코드 접근 권한이 취소되었습니다.",
    noPurchases: "아직 커뮤니티 구매 내역이 없습니다.", loadingOrders: "구매 내역 불러오는 중…", errorLoadingOrders: "구매 내역을 불러올 수 없습니다.",
  },
  ar: {
    checkoutNotice: "هل اكتمل الدفع؟ سيُفعّل الوصول فور تأكيد Stripe للدفع.", refreshPurchases: "تحديث المشتريات",
    title: "قوالب المجتمع", description: "منتجات ينشرها المطورون. لا يتاح الرمز إلا بعد تأكيد الدفع. تحتفظ Tatik بنسبة 15% من السعر، ويحصل البائع على نسبة 85% المتبقية قبل رسوم مزود الدفع.",
    sellTemplate: "بع قالبك", stripeMissingUrl: "لم يُرجع Stripe رابط الدفع.", removedForReview: "أُزيل القالب من السوق للمراجعة.",
    retryError: "تعذّر تحديث السوق. حاول مرة أخرى بعد قليل.", reviewSaved: "حُفظ التقييم. شكرًا لملاحظاتك!",
    codeUnavailable: "رمز القالب غير متاح.", copyError: "تعذّر نسخ القالب.", downloadSuccess: "تم تنزيل القالب.",
    manifestCopied: "نُسخ ملف المشروع الكامل. استخدم «فتح في المحرر» لتحميل الملفات كلًّا على حدة.", codeCopied: "تم نسخ الرمز.",
    productError: "تعذّر استرداد القالب المشترى.", ownProductError: "تعذّر استرداد قالبك.", seller: "بواسطة",
    copyCode: "نسخ الرمز", openEditor: "فتح في المحرر", downloadTemplate: "تنزيل القالب", openingPayment: "جارٍ فتح الدفع…", buy: "شراء", loginToBuy: "سجّل الدخول للشراء",
    moderationPrompt: "السبب القانوني أو الأخلاقي لإزالة هذا القالب:", removeListing: "إزالة من السوق",
    noListings: "لم تُنشر قوالب المجتمع بعد.", loadError: "يتعذّر تحميل قوالب المجتمع حاليًا.", updating: "جارٍ التحديث…", retry: "إعادة المحاولة",
    purchasesTitle: "مشترياتك من المجتمع", purchasesDescription: "لا يسمح الخادم بالنسخ والتنزيل إلا للطلبات المدفوعة وغير المستردة.",
    orderStatus: "الحالة", statusPending: "قيد الانتظار", statusPaid: "مدفوع", statusRefunded: "مسترد", paymentPending: "بانتظار تأكيد مزود الدفع؛ الرمز غير متاح بعد.",
    suspendedAccess: "تم تعليق الوصول مؤقتًا: أُزيل القالب من السوق للمراجعة الإدارية.",
    updateRating: "تحديث تقييمك", rateTemplate: "قيّم القالب (للمشترين فقط)", ratingLabel: "تقييم من 1 إلى 5", stars: "نجوم",
    optionalComment: "تعليق اختياري", submitRating: "إرسال التقييم", refunded: "تم رد المبلغ وإلغاء الوصول إلى الرمز.",
    noPurchases: "ليس لديك مشتريات من المجتمع بعد.", loadingOrders: "جارٍ تحميل المشتريات…", errorLoadingOrders: "تعذّر تحميل المشتريات.",
  },
  hi: {
    checkoutNotice: "क्या भुगतान पूरा हुआ? Stripe द्वारा भुगतान की पुष्टि होते ही पहुँच सक्रिय होगी।", refreshPurchases: "खरीद रीफ़्रेश करें",
    title: "कम्युनिटी टेम्पलेट", description: "डेवलपर द्वारा प्रकाशित उत्पाद। भुगतान की पुष्टि के बाद ही कोड उपलब्ध होगा। Tatik कीमत का 15% रखता है; भुगतान प्रदाता की फीस से पहले विक्रेता को शेष 85% मिलता है।",
    sellTemplate: "अपना टेम्पलेट बेचें", stripeMissingUrl: "Stripe ने भुगतान लिंक नहीं दिया।", removedForReview: "समीक्षा के लिए टेम्पलेट मार्केटप्लेस से हटाया गया।",
    retryError: "मार्केटप्लेस रीफ़्रेश नहीं हो सका। थोड़ी देर बाद फिर प्रयास करें।", reviewSaved: "समीक्षा सहेजी गई। प्रतिक्रिया के लिए धन्यवाद!",
    codeUnavailable: "टेम्पलेट कोड उपलब्ध नहीं है।", copyError: "टेम्पलेट कॉपी नहीं हो सका।", downloadSuccess: "टेम्पलेट डाउनलोड हो गया।",
    manifestCopied: "पूरा प्रोजेक्ट मैनिफ़ेस्ट कॉपी हुआ। फ़ाइलें अलग-अलग लोड करने के लिए “एडिटर में खोलें” चुनें।", codeCopied: "कोड कॉपी हुआ।",
    productError: "खरीदा हुआ टेम्पलेट प्राप्त नहीं हो सका।", ownProductError: "आपका टेम्पलेट प्राप्त नहीं हो सका।", seller: "द्वारा",
    copyCode: "कोड कॉपी करें", openEditor: "एडिटर में खोलें", downloadTemplate: "टेम्पलेट डाउनलोड करें", openingPayment: "भुगतान खोला जा रहा है…", buy: "खरीदें", loginToBuy: "खरीदने के लिए साइन इन करें",
    moderationPrompt: "इस टेम्पलेट को हटाने का कानूनी या नैतिक कारण:", removeListing: "मार्केटप्लेस से हटाएँ",
    noListings: "अभी तक कम्युनिटी टेम्पलेट प्रकाशित नहीं हुए हैं।", loadError: "अभी कम्युनिटी टेम्पलेट लोड नहीं हो सकते।", updating: "रीफ़्रेश हो रहा है…", retry: "फिर कोशिश करें",
    purchasesTitle: "आपकी कम्युनिटी खरीद", purchasesDescription: "सर्वर केवल भुगतान किए गए और वापस न किए गए ऑर्डर के लिए कॉपी और डाउनलोड की अनुमति देता है।",
    orderStatus: "स्थिति", statusPending: "लंबित", statusPaid: "भुगतान हुआ", statusRefunded: "रिफ़ंड हुआ", paymentPending: "भुगतान प्रदाता की पुष्टि की प्रतीक्षा में है; कोड अभी उपलब्ध नहीं है।",
    suspendedAccess: "पहुँच अस्थायी रूप से रोकी गई है: प्रशासनिक समीक्षा के लिए टेम्पलेट मार्केटप्लेस से हटाया गया है।",
    updateRating: "अपनी रेटिंग अपडेट करें", rateTemplate: "टेम्पलेट रेट करें (केवल खरीदार)", ratingLabel: "1 से 5 तक रेटिंग", stars: "सितारे",
    optionalComment: "वैकल्पिक टिप्पणी", submitRating: "रेटिंग भेजें", refunded: "ऑर्डर का रिफ़ंड किया गया: कोड की पहुँच रद्द है।",
    noPurchases: "आपने अभी कम्युनिटी से कुछ नहीं खरीदा है।", loadingOrders: "खरीद लोड हो रही है…", errorLoadingOrders: "खरीद लोड नहीं हो सकी।",
  },
  pl: {
    checkoutNotice: "Płatność zakończona? Dostęp zostanie włączony po potwierdzeniu płatności przez Stripe.", refreshPurchases: "Odśwież zakupy",
    title: "Szablony społeczności", description: "Produkty opublikowane przez deweloperów. Kod jest dostępny dopiero po potwierdzeniu płatności. Tatik zatrzymuje 15% ceny, a sprzedawca otrzymuje pozostałe 85% przed opłatami dostawcy płatności.",
    sellTemplate: "Sprzedaj swój szablon", stripeMissingUrl: "Stripe nie zwrócił linku do płatności.", removedForReview: "Szablon usunięto z marketplace do weryfikacji.",
    retryError: "Nie udało się odświeżyć marketplace. Spróbuj ponownie za chwilę.", reviewSaved: "Opinia zapisana. Dziękujemy za komentarz!",
    codeUnavailable: "Kod szablonu jest niedostępny.", copyError: "Nie udało się skopiować szablonu.", downloadSuccess: "Szablon pobrany.",
    manifestCopied: "Skopiowano pełny manifest projektu. Użyj opcji „Otwórz w edytorze”, aby wczytać pliki osobno.", codeCopied: "Kod skopiowany.",
    productError: "Nie udało się pobrać kupionego szablonu.", ownProductError: "Nie udało się pobrać własnego szablonu.", seller: "autor",
    copyCode: "Kopiuj kod", openEditor: "Otwórz w edytorze", downloadTemplate: "Pobierz szablon", openingPayment: "Otwieranie płatności…", buy: "Kup", loginToBuy: "Zaloguj się, aby kupić",
    moderationPrompt: "Prawny lub etyczny powód usunięcia tego szablonu:", removeListing: "Usuń z marketplace",
    noListings: "Nie opublikowano jeszcze szablonów społeczności.", loadError: "Nie można teraz wczytać szablonów społeczności.", updating: "Odświeżanie…", retry: "Ponów próbę",
    purchasesTitle: "Twoje zakupy społeczności", purchasesDescription: "Serwer zezwala na kopiowanie i pobieranie tylko opłaconych, niezwróconych zamówień.",
    orderStatus: "Status", statusPending: "Oczekuje", statusPaid: "Opłacono", statusRefunded: "Zwrócono", paymentPending: "Oczekiwanie na potwierdzenie dostawcy płatności; kod nie jest jeszcze dostępny.",
    suspendedAccess: "Dostęp tymczasowo zawieszony: szablon usunięto z marketplace do kontroli administracyjnej.",
    updateRating: "Zaktualizuj ocenę", rateTemplate: "Oceń szablon (tylko kupujący)", ratingLabel: "Ocena od 1 do 5", stars: "gwiazdek",
    optionalComment: "Komentarz (opcjonalnie)", submitRating: "Wyślij ocenę", refunded: "Zamówienie zwrócono; dostęp do kodu został cofnięty.",
    noPurchases: "Nie masz jeszcze zakupów społeczności.", loadingOrders: "Wczytywanie zakupów…", errorLoadingOrders: "Nie udało się wczytać zakupów.",
  },
  nl: {
    checkoutNotice: "Is de betaling afgerond? Toegang wordt geactiveerd zodra Stripe de betaling bevestigt.", refreshPurchases: "Aankopen vernieuwen",
    title: "Communitysjablonen", description: "Producten die door ontwikkelaars zijn gepubliceerd. De code is pas beschikbaar nadat de betaling is bevestigd. Tatik houdt 15% van de prijs in; de verkoper ontvangt de overige 85% vóór kosten van de betaalprovider.",
    sellTemplate: "Verkoop je sjabloon", stripeMissingUrl: "Stripe heeft geen betalingslink teruggegeven.", removedForReview: "Sjabloon voor controle uit de marketplace verwijderd.",
    retryError: "De marketplace kon niet worden vernieuwd. Probeer het zo meteen opnieuw.", reviewSaved: "Beoordeling opgeslagen. Bedankt voor je feedback!",
    codeUnavailable: "Sjablooncode is niet beschikbaar.", copyError: "Sjabloon kon niet worden gekopieerd.", downloadSuccess: "Sjabloon gedownload.",
    manifestCopied: "Het volledige projectmanifest is gekopieerd. Gebruik ‘Openen in editor’ om de bestanden afzonderlijk te laden.", codeCopied: "Code gekopieerd.",
    productError: "Gekocht sjabloon kon niet worden opgehaald.", ownProductError: "Je sjabloon kon niet worden opgehaald.", seller: "door",
    copyCode: "Code kopiëren", openEditor: "Openen in editor", downloadTemplate: "Sjabloon downloaden", openingPayment: "Betaling openen…", buy: "Kopen", loginToBuy: "Log in om te kopen",
    moderationPrompt: "Juridische of ethische reden om dit sjabloon te verwijderen:", removeListing: "Verwijderen uit marketplace",
    noListings: "Er zijn nog geen communitysjablonen gepubliceerd.", loadError: "Communitysjablonen kunnen momenteel niet worden geladen.", updating: "Vernieuwen…", retry: "Opnieuw proberen",
    purchasesTitle: "Je communityaankopen", purchasesDescription: "De server staat kopiëren en downloaden alleen toe voor betaalde, niet-terugbetaalde bestellingen.",
    orderStatus: "Status", statusPending: "In afwachting", statusPaid: "Betaald", statusRefunded: "Terugbetaald", paymentPending: "De betaling wacht op bevestiging van de provider; de code is nog niet beschikbaar.",
    suspendedAccess: "Toegang tijdelijk opgeschort: het sjabloon is voor administratieve controle uit de marketplace verwijderd.",
    updateRating: "Je beoordeling bijwerken", rateTemplate: "Sjabloon beoordelen (alleen kopers)", ratingLabel: "Beoordeling van 1 tot 5", stars: "sterren",
    optionalComment: "Optionele opmerking", submitRating: "Beoordeling verzenden", refunded: "Bestelling terugbetaald: toegang tot de code is ingetrokken.",
    noPurchases: "Je hebt nog geen communityaankopen.", loadingOrders: "Aankopen laden…", errorLoadingOrders: "Aankopen konden niet worden geladen.",
  },
  tr: {
    checkoutNotice: "Ödeme tamamlandı mı? Stripe ödemeyi onayladığında erişim açılır.", refreshPurchases: "Satın alımları yenile",
    title: "Topluluk şablonları", description: "Geliştiriciler tarafından yayınlanan ürünler. Kod yalnızca ödeme onaylandıktan sonra kullanılabilir. Tatik fiyatın %15'ini alır; satıcı ödeme sağlayıcısı ücretleri düşülmeden önce kalan %85'i alır.",
    sellTemplate: "Şablonunu sat", stripeMissingUrl: "Stripe ödeme bağlantısı döndürmedi.", removedForReview: "Şablon inceleme için pazaryerinden kaldırıldı.",
    retryError: "Pazaryeri yenilenemedi. Lütfen biraz sonra tekrar deneyin.", reviewSaved: "Değerlendirme kaydedildi. Geri bildiriminiz için teşekkürler!",
    codeUnavailable: "Şablon kodu kullanılamıyor.", copyError: "Şablon kopyalanamadı.", downloadSuccess: "Şablon indirildi.",
    manifestCopied: "Tam proje manifesti kopyalandı. Dosyaları ayrı yüklemek için “Düzenleyicide aç” seçeneğini kullanın.", codeCopied: "Kod kopyalandı.",
    productError: "Satın alınan şablon alınamadı.", ownProductError: "Kendi şablonunuz alınamadı.", seller: "satıcı",
    copyCode: "Kodu kopyala", openEditor: "Düzenleyicide aç", downloadTemplate: "Şablonu indir", openingPayment: "Ödeme açılıyor…", buy: "Satın al", loginToBuy: "Satın almak için giriş yapın",
    moderationPrompt: "Bu şablonun kaldırılması için yasal veya etik neden:", removeListing: "Pazaryerinden kaldır",
    noListings: "Henüz topluluk şablonu yayınlanmadı.", loadError: "Topluluk şablonları şu anda yüklenemiyor.", updating: "Yenileniyor…", retry: "Tekrar dene",
    purchasesTitle: "Topluluk satın alımlarınız", purchasesDescription: "Sunucu, yalnızca ödenmiş ve iade edilmemiş siparişler için kopyalama ve indirmeye izin verir.",
    orderStatus: "Durum", statusPending: "Beklemede", statusPaid: "Ödendi", statusRefunded: "İade edildi", paymentPending: "Ödeme sağlayıcının onayı bekleniyor; kod henüz kullanılamaz.",
    suspendedAccess: "Erişim geçici olarak askıya alındı: şablon yönetim incelemesi için pazaryerinden kaldırıldı.",
    updateRating: "Değerlendirmeni güncelle", rateTemplate: "Şablonu değerlendir (yalnızca alıcılar)", ratingLabel: "1 ile 5 arası puan", stars: "yıldız",
    optionalComment: "İsteğe bağlı yorum", submitRating: "Değerlendirme gönder", refunded: "Sipariş iade edildi: kod erişimi iptal edildi.",
    noPurchases: "Henüz topluluktan satın alımınız yok.", loadingOrders: "Satın alımlar yükleniyor…", errorLoadingOrders: "Satın alımlar yüklenemedi.",
  },
  sv: {
    checkoutNotice: "Är betalningen slutförd? Åtkomsten aktiveras när Stripe har bekräftat betalningen.", refreshPurchases: "Uppdatera köp",
    title: "Communitymallar", description: "Produkter publicerade av utvecklare. Koden blir tillgänglig först när betalningen har bekräftats. Tatik behåller 15 % av priset; säljaren får resterande 85 % före betalningsleverantörens avgifter.",
    sellTemplate: "Sälj din mall", stripeMissingUrl: "Stripe returnerade ingen betalningslänk.", removedForReview: "Mallen har tagits bort från marknadsplatsen för granskning.",
    retryError: "Det gick inte att uppdatera marknadsplatsen. Försök igen om en stund.", reviewSaved: "Omdömet har sparats. Tack för din feedback!",
    codeUnavailable: "Mallkoden är inte tillgänglig.", copyError: "Det gick inte att kopiera mallen.", downloadSuccess: "Mallen har laddats ned.",
    manifestCopied: "Hela projektmanifestet har kopierats. Använd ”Öppna i editorn” för att läsa in filerna separat.", codeCopied: "Koden har kopierats.",
    productError: "Det gick inte att hämta den köpta mallen.", ownProductError: "Det gick inte att hämta din mall.", seller: "av",
    copyCode: "Kopiera kod", openEditor: "Öppna i editorn", downloadTemplate: "Ladda ned mall", openingPayment: "Öppnar betalningen…", buy: "Köp", loginToBuy: "Logga in för att köpa",
    moderationPrompt: "Juridiskt eller etiskt skäl till att ta bort mallen:", removeListing: "Ta bort från marknadsplatsen",
    noListings: "Inga communitymallar har publicerats ännu.", loadError: "Det går inte att läsa in communitymallarna just nu.", updating: "Uppdaterar…", retry: "Försök igen",
    purchasesTitle: "Dina köp från communityn", purchasesDescription: "Servern tillåter kopiering och nedladdning endast för betalda beställningar som inte har återbetalats.",
    orderStatus: "Status", statusPending: "Väntar", statusPaid: "Betald", statusRefunded: "Återbetald", paymentPending: "Betalningen väntar på leverantörens bekräftelse; koden är inte tillgänglig ännu.",
    suspendedAccess: "Åtkomsten är tillfälligt avstängd: mallen har tagits bort för administrativ granskning.",
    updateRating: "Uppdatera ditt betyg", rateTemplate: "Betygsätt mallen (endast köpare)", ratingLabel: "Betyg från 1 till 5", stars: "stjärnor",
    optionalComment: "Valfri kommentar", submitRating: "Skicka betyg", refunded: "Beställningen återbetalades: åtkomsten till koden har återkallats.",
    noPurchases: "Du har inga köp från communityn ännu.", loadingOrders: "Läser in köp…", errorLoadingOrders: "Det gick inte att läsa in köpen.",
  },
  da: {
    checkoutNotice: "Er betalingen gennemført? Adgangen aktiveres, når Stripe har bekræftet betalingen.", refreshPurchases: "Opdater køb",
    title: "Fællesskabsskabeloner", description: "Produkter udgivet af udviklere. Koden er først tilgængelig, når betalingen er bekræftet. Tatik beholder 15 % af prisen; sælgeren modtager de resterende 85 % før betalingsudbyderens gebyrer.",
    sellTemplate: "Sælg din skabelon", stripeMissingUrl: "Stripe returnerede ikke et betalingslink.", removedForReview: "Skabelonen er fjernet fra markedspladsen til gennemgang.",
    retryError: "Markedspladsen kunne ikke opdateres. Prøv igen om lidt.", reviewSaved: "Anmeldelsen er gemt. Tak for din feedback!",
    codeUnavailable: "Skabelonkoden er ikke tilgængelig.", copyError: "Skabelonen kunne ikke kopieres.", downloadSuccess: "Skabelonen er downloadet.",
    manifestCopied: "Det komplette projektmanifest er kopieret. Brug »Åbn i editor« for at indlæse filerne separat.", codeCopied: "Koden er kopieret.",
    productError: "Den købte skabelon kunne ikke hentes.", ownProductError: "Din skabelon kunne ikke hentes.", seller: "af",
    copyCode: "Kopiér kode", openEditor: "Åbn i editor", downloadTemplate: "Download skabelon", openingPayment: "Åbner betaling…", buy: "Køb", loginToBuy: "Log ind for at købe",
    moderationPrompt: "Juridisk eller etisk grund til at fjerne skabelonen:", removeListing: "Fjern fra markedspladsen",
    noListings: "Der er endnu ikke udgivet skabeloner fra fællesskabet.", loadError: "Fællesskabsskabeloner kan ikke indlæses lige nu.", updating: "Opdaterer…", retry: "Prøv igen",
    purchasesTitle: "Dine køb fra fællesskabet", purchasesDescription: "Serveren tillader kun kopiering og download af betalte ordrer, der ikke er refunderet.",
    orderStatus: "Status", statusPending: "Afventer", statusPaid: "Betalt", statusRefunded: "Refunderet", paymentPending: "Betalingen afventer udbyderens bekræftelse; koden er ikke tilgængelig endnu.",
    suspendedAccess: "Adgangen er midlertidigt suspenderet: Skabelonen er fjernet fra markedspladsen til administrativ gennemgang.",
    updateRating: "Opdater din vurdering", rateTemplate: "Vurdér skabelonen (kun købere)", ratingLabel: "Vurdering fra 1 til 5", stars: "stjerner",
    optionalComment: "Valgfri kommentar", submitRating: "Send vurdering", refunded: "Ordren er refunderet: Adgangen til koden er tilbagekaldt.",
    noPurchases: "Du har endnu ingen køb fra fællesskabet.", loadingOrders: "Indlæser køb…", errorLoadingOrders: "Køb kunne ikke indlæses.",
  },
  no: {
    checkoutNotice: "Er betalingen fullført? Tilgangen aktiveres når Stripe har bekreftet betalingen.", refreshPurchases: "Oppdater kjøp",
    title: "Fellesskapsmaler", description: "Produkter publisert av utviklere. Koden blir tilgjengelig først etter at betalingen er bekreftet. Tatik beholder 15 % av prisen; selgeren mottar de resterende 85 % før gebyrer fra betalingsleverandøren.",
    sellTemplate: "Selg malen din", stripeMissingUrl: "Stripe returnerte ingen betalingslenke.", removedForReview: "Malen er fjernet fra markedsplassen for gjennomgang.",
    retryError: "Markedsplassen kunne ikke oppdateres. Prøv igjen om litt.", reviewSaved: "Anmeldelsen er lagret. Takk for tilbakemeldingen!",
    codeUnavailable: "Malens kode er ikke tilgjengelig.", copyError: "Malen kunne ikke kopieres.", downloadSuccess: "Malen er lastet ned.",
    manifestCopied: "Hele prosjektmanifestet er kopiert. Bruk «Åpne i editor» for å laste inn filene hver for seg.", codeCopied: "Koden er kopiert.",
    productError: "Den kjøpte malen kunne ikke hentes.", ownProductError: "Din egen mal kunne ikke hentes.", seller: "av",
    copyCode: "Kopier kode", openEditor: "Åpne i editor", downloadTemplate: "Last ned mal", openingPayment: "Åpner betaling…", buy: "Kjøp", loginToBuy: "Logg inn for å kjøpe",
    moderationPrompt: "Juridisk eller etisk grunn til å fjerne malen:", removeListing: "Fjern fra markedsplassen",
    noListings: "Ingen fellesskapsmaler er publisert ennå.", loadError: "Fellesskapsmalene kan ikke lastes inn akkurat nå.", updating: "Oppdaterer…", retry: "Prøv igjen",
    purchasesTitle: "Dine kjøp fra fellesskapet", purchasesDescription: "Serveren tillater bare kopiering og nedlasting for betalte bestillinger som ikke er refundert.",
    orderStatus: "Status", statusPending: "Venter", statusPaid: "Betalt", statusRefunded: "Refundert", paymentPending: "Betalingen venter på bekreftelse fra leverandøren; koden er ikke tilgjengelig ennå.",
    suspendedAccess: "Tilgangen er midlertidig suspendert: Malen er fjernet fra markedsplassen for administrativ gjennomgang.",
    updateRating: "Oppdater vurderingen din", rateTemplate: "Vurder malen (kun kjøpere)", ratingLabel: "Vurdering fra 1 til 5", stars: "stjerner",
    optionalComment: "Valgfri kommentar", submitRating: "Send vurdering", refunded: "Bestillingen er refundert: Tilgangen til koden er tilbakekalt.",
    noPurchases: "Du har ingen kjøp fra fellesskapet ennå.", loadingOrders: "Laster inn kjøp…", errorLoadingOrders: "Kunne ikke laste inn kjøp.",
  },
  fi: {
    checkoutNotice: "Maksu suoritettu? Käyttöoikeus aktivoituu, kun Stripe vahvistaa maksun.", refreshPurchases: "Päivitä ostokset",
    title: "Yhteisön mallit", description: "Kehittäjien julkaisemia tuotteita. Koodi on saatavilla vasta, kun maksu on vahvistettu. Tatik pidättää hinnasta 15 %; myyjä saa jäljelle jäävät 85 % ennen maksupalvelun kuluja.",
    sellTemplate: "Myy mallisi", stripeMissingUrl: "Stripe ei palauttanut maksulinkkiä.", removedForReview: "Malli poistettiin markkinapaikalta tarkistusta varten.",
    retryError: "Markkinapaikkaa ei voitu päivittää. Yritä hetken kuluttua uudelleen.", reviewSaved: "Arvostelu tallennettu. Kiitos palautteestasi!",
    codeUnavailable: "Mallin koodi ei ole saatavilla.", copyError: "Mallia ei voitu kopioida.", downloadSuccess: "Malli ladattu.",
    manifestCopied: "Koko projektin luettelotiedosto kopioitiin. Lataa tiedostot erikseen valitsemalla ”Avaa editorissa”.", codeCopied: "Koodi kopioitiin.",
    productError: "Ostettua mallia ei voitu hakea.", ownProductError: "Omaa malliasi ei voitu hakea.", seller: "tekijä",
    copyCode: "Kopioi koodi", openEditor: "Avaa editorissa", downloadTemplate: "Lataa malli", openingPayment: "Avataan maksua…", buy: "Osta", loginToBuy: "Kirjaudu sisään ostaaksesi",
    moderationPrompt: "Oikeudellinen tai eettinen syy mallin poistamiseen:", removeListing: "Poista markkinapaikalta",
    noListings: "Yhteisön malleja ei ole vielä julkaistu.", loadError: "Yhteisön malleja ei voi ladata juuri nyt.", updating: "Päivitetään…", retry: "Yritä uudelleen",
    purchasesTitle: "Yhteisöostoksesi", purchasesDescription: "Palvelin sallii kopioinnin ja lataamisen vain maksetuille, palauttamattomille tilauksille.",
    orderStatus: "Tila", statusPending: "Odottaa", statusPaid: "Maksettu", statusRefunded: "Hyvitetty", paymentPending: "Maksu odottaa maksupalvelun vahvistusta; koodi ei ole vielä saatavilla.",
    suspendedAccess: "Käyttöoikeus on tilapäisesti keskeytetty: malli poistettiin markkinapaikalta hallinnollista tarkistusta varten.",
    updateRating: "Päivitä arviosi", rateTemplate: "Arvioi malli (vain ostajille)", ratingLabel: "Arvio 1–5", stars: "tähteä",
    optionalComment: "Valinnainen kommentti", submitRating: "Lähetä arvio", refunded: "Tilaus hyvitettiin: koodin käyttöoikeus on peruutettu.",
    noPurchases: "Sinulla ei ole vielä yhteisöostoksia.", loadingOrders: "Ladataan ostoksia…", errorLoadingOrders: "Ostoksia ei voitu ladata.",
  },
  uk: {
    checkoutNotice: "Оплату завершено? Доступ активується після підтвердження платежу Stripe.", refreshPurchases: "Оновити покупки",
    title: "Шаблони спільноти", description: "Продукти, опубліковані розробниками. Код доступний лише після підтвердження оплати. Tatik утримує 15% ціни; продавець отримує решту 85% до вирахування комісій платіжного провайдера.",
    sellTemplate: "Продати свій шаблон", stripeMissingUrl: "Stripe не повернув посилання для оплати.", removedForReview: "Шаблон вилучено з маркетплейсу для перевірки.",
    retryError: "Не вдалося оновити маркетплейс. Спробуйте ще раз трохи пізніше.", reviewSaved: "Відгук збережено. Дякуємо за відгук!",
    codeUnavailable: "Код шаблону недоступний.", copyError: "Не вдалося скопіювати шаблон.", downloadSuccess: "Шаблон завантажено.",
    manifestCopied: "Повний маніфест проєкту скопійовано. Скористайтеся «Відкрити в редакторі», щоб завантажити файли окремо.", codeCopied: "Код скопійовано.",
    productError: "Не вдалося отримати придбаний шаблон.", ownProductError: "Не вдалося отримати ваш шаблон.", seller: "автор",
    copyCode: "Копіювати код", openEditor: "Відкрити в редакторі", downloadTemplate: "Завантажити шаблон", openingPayment: "Відкриття оплати…", buy: "Придбати", loginToBuy: "Увійдіть, щоб придбати",
    moderationPrompt: "Юридична або етична причина вилучення шаблону:", removeListing: "Вилучити з маркетплейсу",
    noListings: "Шаблони спільноти ще не опубліковані.", loadError: "Зараз неможливо завантажити шаблони спільноти.", updating: "Оновлення…", retry: "Спробувати ще раз",
    purchasesTitle: "Ваші покупки спільноти", purchasesDescription: "Сервер дозволяє копіювання та завантаження лише для оплачених і не відшкодованих замовлень.",
    orderStatus: "Статус", statusPending: "Очікує", statusPaid: "Оплачено", statusRefunded: "Повернено", paymentPending: "Очікується підтвердження оплати провайдером; код поки недоступний.",
    suspendedAccess: "Доступ тимчасово призупинено: шаблон вилучено з маркетплейсу для адміністративної перевірки.",
    updateRating: "Оновити оцінку", rateTemplate: "Оцініть шаблон (лише покупці)", ratingLabel: "Оцінка від 1 до 5", stars: "зірок",
    optionalComment: "Коментар (необов’язково)", submitRating: "Надіслати оцінку", refunded: "Замовлення відшкодовано: доступ до коду відкликано.",
    noPurchases: "У вас ще немає покупок спільноти.", loadingOrders: "Завантаження покупок…", errorLoadingOrders: "Не вдалося завантажити покупки.",
  },
  cs: {
    checkoutNotice: "Platba dokončena? Přístup se aktivuje, jakmile Stripe platbu potvrdí.", refreshPurchases: "Obnovit nákupy",
    title: "Komunitní šablony", description: "Produkty zveřejněné vývojáři. Kód je dostupný až po potvrzení platby. Tatik si ponechá 15 % ceny; prodejce získá zbývajících 85 % před odečtením poplatků poskytovatele plateb.",
    sellTemplate: "Prodávat šablonu", stripeMissingUrl: "Stripe nevrátil platební odkaz.", removedForReview: "Šablona byla odebrána z tržiště ke kontrole.",
    retryError: "Tržiště se nepodařilo obnovit. Zkuste to za chvíli znovu.", reviewSaved: "Recenze uložena. Děkujeme za zpětnou vazbu!",
    codeUnavailable: "Kód šablony není dostupný.", copyError: "Šablonu se nepodařilo zkopírovat.", downloadSuccess: "Šablona byla stažena.",
    manifestCopied: "Byl zkopírován úplný manifest projektu. Jednotlivé soubory načtete pomocí možnosti „Otevřít v editoru“.", codeCopied: "Kód byl zkopírován.",
    productError: "Zakoupenou šablonu se nepodařilo načíst.", ownProductError: "Vaši šablonu se nepodařilo načíst.", seller: "autor",
    copyCode: "Kopírovat kód", openEditor: "Otevřít v editoru", downloadTemplate: "Stáhnout šablonu", openingPayment: "Otevírání platby…", buy: "Koupit", loginToBuy: "Přihlaste se a nakupujte",
    moderationPrompt: "Právní nebo etický důvod odebrání této šablony:", removeListing: "Odebrat z tržiště",
    noListings: "Zatím nebyly zveřejněny žádné komunitní šablony.", loadError: "Komunitní šablony momentálně nelze načíst.", updating: "Obnovování…", retry: "Zkusit znovu",
    purchasesTitle: "Vaše komunitní nákupy", purchasesDescription: "Server povoluje kopírování a stahování pouze u zaplacených objednávek bez vrácení peněz.",
    orderStatus: "Stav", statusPending: "Čeká", statusPaid: "Zaplaceno", statusRefunded: "Vráceno", paymentPending: "Čeká se na potvrzení platby poskytovatelem; kód zatím není dostupný.",
    suspendedAccess: "Přístup je dočasně pozastaven: šablona byla odebrána z tržiště kvůli administrativní kontrole.",
    updateRating: "Aktualizovat hodnocení", rateTemplate: "Ohodnotit šablonu (pouze kupující)", ratingLabel: "Hodnocení od 1 do 5", stars: "hvězdiček",
    optionalComment: "Volitelný komentář", submitRating: "Odeslat hodnocení", refunded: "Objednávka byla vrácena: přístup ke kódu byl odebrán.",
    noPurchases: "Zatím nemáte žádné komunitní nákupy.", loadingOrders: "Načítání nákupů…", errorLoadingOrders: "Nákupy se nepodařilo načíst.",
  },
};
