type CommercialSeoCopy = {
  marketplaceTitle: string;
  marketplaceDescription: string;
  marketplaceHeading: string;
  marketplaceIntro: string;
  pricingTitle: string;
  pricingDescription: string;
  pricingHeading: string;
  pricingIntro: string;
  schoolsTitle: string;
  schoolsDescription: string;
  schoolsHeading: string;
  schoolsIntro: string;
};

export const commercialSeoCopy: Record<string, CommercialSeoCopy> = {
  it: {
    marketplaceTitle: "Template web | Tatik.space Pro",
    marketplaceDescription: "Esplora template web gratuiti e premium. Anteprima, checkout e accesso rapido per i template a pagamento; i listing degli sviluppatori sono sottoposti a controllo e revisione.",
    marketplaceHeading: "Template per dare forma al tuo prossimo progetto",
    marketplaceIntro: "Esplora template web gratuiti e premium, controlla l’anteprima prima dell’acquisto e copia il codice solo quando il template è gratuito o hai già ottenuto l’accesso.",
    pricingTitle: "Prezzi e piani | Tatik.space Pro",
    pricingDescription: "Scopri il piano Pro con prova gratuita di 60 giorni, vantaggi premium e fino a 2 bonus fedeltà ogni 30 giorni. Pensato per crescere senza frizioni.",
    pricingHeading: "Scegli il piano più adatto al tuo percorso",
    pricingIntro: "Inizia con una prova gratuita di 60 giorni. Pro costa €5,99 nel primo mese e €7,99 al mese al rinnovo; attiva funzioni premium e fino a 2 bonus fedeltà ogni 30 giorni.",
    schoolsTitle: "Programma scuole | Tatik.space Pro",
    schoolsDescription: "Richiedi un corso scolastico di 30 giorni per un massimo di 30 studenti. L’istituzione deve essere approvata; gli inviti agli studenti usano token monouso.",
    schoolsHeading: "Un ambiente di lavoro condiviso per il tuo corso",
    schoolsIntro: "Il programma scuole offre 30 giorni di accesso per corso per un massimo di 30 studenti. L’istituzione deve essere approvata da Tatik.",
  },
  en: {
    marketplaceTitle: "Web templates | Tatik.space Pro",
    marketplaceDescription: "Explore free and premium web templates. Preview them before buying and complete checkout in a few steps; developer listings are reviewed before publication.",
    marketplaceHeading: "Templates to shape your next project",
    marketplaceIntro: "Explore free and premium web templates, preview them before buying, and copy code only when a template is free or you already have access.",
    pricingTitle: "Plans and pricing | Tatik.space Pro",
    pricingDescription: "Discover the Pro plan with a 60-day free trial, premium benefits, and up to 2 loyalty rewards every 30 days. Built to grow without friction.",
    pricingHeading: "Choose the plan that fits your workflow",
    pricingIntro: "Start with a 60-day free trial. Pro costs €5.99 for the first month and €7.99 per month on renewal; unlock premium access and up to 2 loyalty rewards every 30 days.",
    schoolsTitle: "School program | Tatik.space Pro",
    schoolsDescription: "Request a 30-day school course for up to 30 students. The institution must be approved; student invitations use single-use tokens.",
    schoolsHeading: "A shared workspace for your course",
    schoolsIntro: "The school program gives 30 days of access per course for up to 30 students. The institution must be approved by Tatik.",
  },
  es: {
    marketplaceTitle: "Plantillas web | Tatik.space Pro",
    marketplaceDescription: "Explora plantillas web gratuitas y premium. Consulta la vista previa antes de comprar y completa el checkout en pocos pasos; los listados de desarrolladores se revisan antes de publicarse.",
    marketplaceHeading: "Plantillas para dar forma a tu próximo proyecto",
    marketplaceIntro: "Explora plantillas web gratuitas y premium, revisa la vista previa antes de comprar y copia el código solo si la plantilla es gratuita o ya tienes acceso.",
    pricingTitle: "Planes y precios | Tatik.space Pro",
    pricingDescription: "Descubre el plan Pro con prueba gratuita de 60 días, ventajas premium y hasta 2 bonos de fidelidad cada 30 días. Diseñado para crecer sin fricciones.",
    pricingHeading: "Elige el plan ideal para tu flujo de trabajo",
    pricingIntro: "Empieza con una prueba gratuita de 60 días. Pro cuesta 5,99 € el primer mes y 7,99 € al mes en la renovación; accede a funciones premium y hasta 2 bonos de fidelidad cada 30 días.",
    schoolsTitle: "Programa escolar | Tatik.space Pro",
    schoolsDescription: "Solicita un curso escolar de 30 días para un máximo de 30 estudiantes. La institución debe estar aprobada; las invitaciones usan tokens de un solo uso.",
    schoolsHeading: "Un espacio de trabajo compartido para tu curso",
    schoolsIntro: "El programa escolar ofrece 30 días de acceso por curso para un máximo de 30 estudiantes. La institución debe ser aprobada por Tatik.",
  },
  fr: {
    marketplaceTitle: "Modèles web | Tatik.space Pro",
    marketplaceDescription: "Découvrez des modèles web gratuits et premium. Prévisualisez-les avant l’achat et terminez le checkout en quelques étapes ; les annonces des développeurs sont vérifiées avant publication.",
    marketplaceHeading: "Des modèles pour concrétiser votre prochain projet",
    marketplaceIntro: "Découvrez des modèles web gratuits et premium, prévisualisez-les avant l’achat et copiez le code uniquement si le modèle est gratuit ou si vous avez déjà accès.",
    pricingTitle: "Offres et tarifs | Tatik.space Pro",
    pricingDescription: "Découvrez le plan Pro avec un essai gratuit de 60 jours, des avantages premium et jusqu’à 2 bonus de fidélité chaque 30 jours. Pensé pour grandir sans friction.",
    pricingHeading: "Choisissez le plan adapté à votre workflow",
    pricingIntro: "Commencez par un essai gratuit de 60 jours. Pro coûte 5,99 € le premier mois puis 7,99 € par mois au renouvellement ; profitez d’un accès premium et jusqu’à 2 bonus de fidélité chaque 30 jours.",
    schoolsTitle: "Programme scolaire | Tatik.space Pro",
    schoolsDescription: "Demandez un cours scolaire de 30 jours pour un maximum de 30 élèves. L’établissement doit être approuvé ; les invitations utilisent des jetons à usage unique.",
    schoolsHeading: "Un espace de travail partagé pour votre cours",
    schoolsIntro: "Le programme scolaire offre 30 jours d’accès par cours pour un maximum de 30 élèves. L’établissement doit être approuvé par Tatik.",
  },
  de: {
    marketplaceTitle: "Webvorlagen | Tatik.space Pro",
    marketplaceDescription: "Entdecke kostenlose und Premium-Webvorlagen. Prüfe die Vorschau vor dem Kauf und schließe den Checkout in wenigen Schritten ab; Entwicklerangebote werden vor der Veröffentlichung geprüft.",
    marketplaceHeading: "Vorlagen für dein nächstes Webprojekt",
    marketplaceIntro: "Entdecke kostenlose und Premium-Webvorlagen, prüfe die Vorschau vor dem Kauf und kopiere den Code nur, wenn die Vorlage kostenlos ist oder du bereits Zugriff hast.",
    pricingTitle: "Tarife und Preise | Tatik.space Pro",
    pricingDescription: "Entdecke den Pro-Plan mit 60 Tagen kostenloser Testphase, Premium-Vorteilen und bis zu 2 Treueboni alle 30 Tage. Für Wachstum ohne Reibungsverluste.",
    pricingHeading: "Wähle den passenden Tarif für deinen Workflow",
    pricingIntro: "Starte mit 60 Tagen kostenloser Testphase. Pro kostet im ersten Monat 5,99 € und danach 7,99 € pro Monat bei Verlängerung; erhalte Premium-Zugang und bis zu 2 Treueboni alle 30 Tage.",
    schoolsTitle: "Schulprogramm | Tatik.space Pro",
    schoolsDescription: "Beantrage einen 30-tägigen Schulkurs für höchstens 30 Lernende. Die Einrichtung muss genehmigt werden; Einladungen erfolgen mit einmalig verwendbaren Tokens.",
    schoolsHeading: "Ein gemeinsamer Arbeitsbereich für deinen Kurs",
    schoolsIntro: "Das Schulprogramm bietet 30 Tage Zugang pro Kurs für höchstens 30 Lernende. Die Einrichtung muss von Tatik genehmigt werden.",
  },
  pt: {
    marketplaceTitle: "Modelos web | Tatik.space Pro",
    marketplaceDescription: "Explore modelos web gratuitos e premium. Veja a prévia antes de comprar e conclua o checkout em poucos passos; os anúncios de desenvolvedores são revisados antes da publicação.",
    marketplaceHeading: "Modelos para dar forma ao seu próximo projeto",
    marketplaceIntro: "Explore modelos web gratuitos e premium, veja a prévia antes de comprar e copie o código apenas quando o modelo for gratuito ou você já tiver acesso.",
    pricingTitle: "Planos e preços | Tatik.space Pro",
    pricingDescription: "Descubra o plano Pro com teste gratuito de 60 dias, benefícios premium e até 2 bónus de fidelidade a cada 30 dias. Pensado para crescer sem fricções.",
    pricingHeading: "Escolha o plano ideal para o seu fluxo de trabalho",
    pricingIntro: "Comece com um teste gratuito de 60 dias. O Pro custa 5,99 € no primeiro mês e 7,99 € por mês na renovação; desbloqueie acesso premium e até 2 bónus de fidelidade a cada 30 dias.",
    schoolsTitle: "Programa escolar | Tatik.space Pro",
    schoolsDescription: "Solicite um curso escolar de 30 dias para até 30 estudantes. A instituição deve ser aprovada; os convites usam tokens de uso único.",
    schoolsHeading: "Um espaço de trabalho partilhado para o seu curso",
    schoolsIntro: "O programa escolar oferece 30 dias de acesso por curso para até 30 estudantes. A instituição deve ser aprovada pela Tatik.",
  },
  ru: {
    marketplaceTitle: "Веб-шаблоны | Tatik.space Pro",
    marketplaceDescription: "Изучайте бесплатные и премиум шаблоны. Просматривайте их перед покупкой и оформляйте заказ за несколько шагов; предложения разработчиков проходят проверку перед публикацией.",
    marketplaceHeading: "Шаблоны для вашего следующего проекта",
    marketplaceIntro: "Изучайте бесплатные и премиум шаблоны, просматривайте их перед покупкой и копируйте код только в том случае, если шаблон бесплатный или доступ уже получен.",
    pricingTitle: "Тарифы и цены | Tatik.space Pro",
    pricingDescription: "Изучите тариф Pro с бесплатным пробным периодом 60 дней, премиальными преимуществами и до 2 бонусов лояльности каждые 30 дней. Подходит для роста без лишних препятствий.",
    pricingHeading: "Выберите тариф, который подходит вашему workflow",
    pricingIntro: "Начните с бесплатного пробного периода на 60 дней. Pro стоит €5,99 в первый месяц и €7,99 в месяц при продлении; получите премиальный доступ и до 2 бонусов лояльности каждые 30 дней.",
    schoolsTitle: "Школьная программа | Tatik.space Pro",
    schoolsDescription: "Подайте заявку на 30-дневный школьный курс для до 30 учеников. Учреждение должно быть одобрено; приглашения используют одноразовые токены.",
    schoolsHeading: "Общее рабочее пространство для вашего курса",
    schoolsIntro: "Школьная программа предоставляет 30 дней доступа на курс для до 30 учеников. Учреждение должно быть одобрено Tatik.",
  },
  zh: {
    marketplaceTitle: "网页模板 | Tatik.space Pro",
    marketplaceDescription: "浏览免费与高级网页模板。购买前先预览，并在几步内完成结账；开发者发布的模板会接受审核后再上线。",
    marketplaceHeading: "为下一项目精选模板",
    marketplaceIntro: "浏览免费与高级网页模板，购买前先预览，且仅当模板免费或您已获得访问权限时才复制代码。",
    pricingTitle: "方案与价格 | Tatik.space Pro",
    pricingDescription: "了解 Pro 方案，包含 60 天免费试用、高级权益以及每 30 天最多 2 个忠诚奖励。专为顺畅增长而设计。",
    pricingHeading: "选择最适合你工作流的方案",
    pricingIntro: "从 60 天免费试用开始。Pro 首月 €5.99，续订后每月 €7.99；解锁高级功能，并在每 30 天内获得最多 2 个忠诚奖励。",
    schoolsTitle: "学校计划 | Tatik.space Pro",
    schoolsDescription: "申请为期 30 天的学校课程，最多 30 名学生。机构必须通过审核；学生邀请使用一次性令牌。",
    schoolsHeading: "为课程提供共享工作空间",
    schoolsIntro: "学校计划为每个课程提供 30 天访问权限，最多 30 名学生。该机构必须获得 Tatik 批准。",
  },
  ja: {
    marketplaceTitle: "Webテンプレート | Tatik.space Pro",
    marketplaceDescription: "無料・プレミアムのWebテンプレートを探索。購入前にプレビューを確認し、数ステップで決済を完了できます。開発者の出品物は公開前に審査されます。",
    marketplaceHeading: "次のプロジェクトを形にするテンプレート",
    marketplaceIntro: "無料・プレミアムのWebテンプレートを探索し、購入前にプレビューを確認できます。無料テンプレートまたはアクセス権がある場合にのみコードをコピーできます。",
    pricingTitle: "料金プラン | Tatik.space Pro",
    pricingDescription: "60日間の無料トライアル、プレミアム特典、30日ごとに最大2件のロイヤリティボーナスを備えた Pro プランをご利用いただけます。スムーズな成長に特化しています。",
    pricingHeading: "ワークフローに合ったプランを選択",
    pricingIntro: "60日間の無料トライアルから始められます。Pro は初月 €5.99、更新後は月額 €7.99。プレミアムアクセスと、30日ごとに最大2件のロイヤリティボーナスを利用できます。",
    schoolsTitle: "学校向けプログラム | Tatik.space Pro",
    schoolsDescription: "最大30名の学生を対象とした30日間の学校コースを申請できます。機関承認が必要で、学生招待には一度だけ使えるトークンを使用します。",
    schoolsHeading: "コースで共有できるワークスペース",
    schoolsIntro: "学校プログラムでは、1コースごとに最大30名の学生に30日間アクセスを提供します。機関の承認は Tatik によって行われます。",
  },
  ko: {
    marketplaceTitle: "웹 템플릿 | Tatik.space Pro",
    marketplaceDescription: "무료 및 프리미엄 웹 템플릿을 살펴보세요. 구매 전 미리보기를 확인하고 몇 단계만으로 결제를 완료할 수 있습니다. 개발자 목록은 공개 전 검토됩니다.",
    marketplaceHeading: "다음 프로젝트를 완성하는 템플릿",
    marketplaceIntro: "무료 및 프리미엄 웹 템플릿을 둘러보고 구매 전 미리보기를 확인하세요. 무료 템플릿이거나 이미 접근 권한이 있는 경우에만 코드를 복사할 수 있습니다.",
    pricingTitle: "요금제 및 가격 | Tatik.space Pro",
    pricingDescription: "60일 무료 체험, 프리미엄 혜택, 30일마다 최대 2개의 로열티 보너스를 제공하는 Pro 플랜을 만나보세요. 원활한 성장을 위해 설계되었습니다.",
    pricingHeading: "업무 흐름에 맞는 플랜 선택",
    pricingIntro: "60일 무료 체험으로 시작하세요. Pro는 첫 달 €5.99, 갱신 시 월 €7.99입니다. 프리미엄 접근 권한과 30일마다 최대 2개의 로열티 보너스를 누리세요.",
    schoolsTitle: "학교 프로그램 | Tatik.space Pro",
    schoolsDescription: "최대 30명의 학생을 대상으로 한 30일 학교 과정을 신청할 수 있습니다. 기관 승인이 필요하며, 학생 초대는 일회용 토큰을 사용합니다.",
    schoolsHeading: "코스를 위한 공용 작업 공간",
    schoolsIntro: "학교 프로그램은 코스당 최대 30명의 학생에게 30일 동안 접근 권한을 제공합니다. 기관 승인 절차는 Tatik에서 진행합니다.",
  },
  ar: {
    marketplaceTitle: "قوالب الويب | Tatik.space Pro",
    marketplaceDescription: "استكشف قوالب الويب المجانية والمميزة. اعرضها قبل الشراء وأكمل الدفع خلال بضع خطوات؛ تخضع قوائم المطورين للمراجعة قبل النشر.",
    marketplaceHeading: "قوالب لتشكيل مشروعك القادم",
    marketplaceIntro: "استكشف قوالب الويب المجانية والمميزة، وافحصها قبل الشراء، ولا تنسَ أن نسخ الكود مسموح فقط في القوالب المجانية أو عندما يكون لديك حق الوصول بالفعل.",
    pricingTitle: "الأسعار والخطط | Tatik.space Pro",
    pricingDescription: "اكتشف خطة Pro مع تجربة مجانية لمدة 60 يومًا، ومزايا مميزة، وحتى 2 مكافآت ولاء كل 30 يومًا. مصممة للنمو السلس دون تعقيدات.",
    pricingHeading: "اختر الخطة المناسبة لتدفقك العملي",
    pricingIntro: "ابدأ بتجربة مجانية لمدة 60 يومًا. تبلغ تكلفة Pro €5.99 في الشهر الأول ثم €7.99 شهريًا عند التجديد؛ احصل على وصول مميز وحتى 2 مكافآت ولاء كل 30 يومًا.",
    schoolsTitle: "برنامج المدارس | Tatik.space Pro",
    schoolsDescription: "اطلب دورة مدرسية لمدة 30 يومًا لحتى 30 طالبًا. يلزم موافقة المؤسسة؛ تستخدم الدعوات رموزًا لمرة واحدة.",
    schoolsHeading: "مساحة عمل مشتركة لدورتك",
    schoolsIntro: "يوفر برنامج المدارس وصولًا لمدة 30 يومًا لكل دورة لحتى 30 طالبًا. يجب أن توافق Tatik على المؤسسة.",
  },
  hi: {
    marketplaceTitle: "वेब टेम्पलेट्स | Tatik.space Pro",
    marketplaceDescription: "मुफ़्त और प्रीमियम वेब टेम्पलेट्स देखें। खरीद से पहले उनका प्रीव्यू देखें और कुछ चरणों में भुगतान पूरा करें; डेवलपर लिस्टिंग्स को प्रकाशन से पहले समीक्षा की जाती है।",
    marketplaceHeading: "अपने अगले प्रोजेक्ट के लिए सही टेम्पलेट",
    marketplaceIntro: "मुफ़्त और प्रीमियम वेब टेम्पलेट्स देखें, खरीद से पहले प्रीव्यू सत्यापित करें और केवल तभी कोड कॉपी करें जब टेम्पलेट मुफ़्त हो या आपके पास एक्सेस हो।",
    pricingTitle: "योजना और कीमतें | Tatik.space Pro",
    pricingDescription: "60 दिन की मुफ्त ट्रायल, प्रीमियम फीचर्स, और हर 30 दिन में अधिकतम 2 लॉयल्टी बोनस के साथ Pro प्लान देखें। बिना झंझट के ग्रोथ के लिए तैयार।",
    pricingHeading: "अपने वर्कफ़्लो के लिए सही प्लान चुनें",
    pricingIntro: "60 दिनों की मुफ्त ट्रायल से शुरू करें। Pro का पहला महीना €5.99 है, फिर नवीनीकरण पर €7.99 प्रति माह; प्रीमियम एक्सेस और हर 30 दिनों में अधिकतम 2 लॉयल्टी बोनस पाएं।",
    schoolsTitle: "स्कूल प्रोग्राम | Tatik.space Pro",
    schoolsDescription: "अधिकतम 30 विद्यार्थियों के लिए 30-दिवसीय स्कूल कोर्स का अनुरोध करें। संस्था की मंज़ूरी आवश्यक है; विद्यार्थी आमंत्रण एकबार उपयोग होने वाले टोकन से होते हैं।",
    schoolsHeading: "आपके पाठ्यक्रम के लिए साझा कार्यक्षेत्र",
    schoolsIntro: "स्कूल प्रोग्राम प्रत्येक पाठ्यक्रम के लिए अधिकतम 30 विद्यार्थियों को 30 दिनों का उपयोग देता है। संस्था को Tatik की मंज़ूरी चाहिए।",
  },
  pl: {
    marketplaceTitle: "Szablony internetowe | Tatik.space Pro",
    marketplaceDescription: "Przeglądaj bezpłatne i premium szablony internetowe. Sprawdź podgląd przed zakupem i dokończ zakup w kilku krokach; oferty deweloperów są sprawdzane przed publikacją.",
    marketplaceHeading: "Szablony, które pomogą zrealizować twój kolejny projekt",
    marketplaceIntro: "Przeglądaj bezpłatne i premium szablony internetowe, sprawdzaj podgląd przed zakupem i kopiuj kod tylko wtedy, gdy szablon jest bezpłatny albo masz już dostęp.",
    pricingTitle: "Plany i ceny | Tatik.space Pro",
    pricingDescription: "Odkryj plan Pro z 60-dniowym darmowym okresem próbny, premiowymi benefitami i aż 2 bonusami lojalnościowymi co 30 dni. Stworzony, aby rozwijać się bez kompromisów.",
    pricingHeading: "Wybierz plan dopasowany do Twojego workflow",
    pricingIntro: "Rozpocznij od 60-dniowego bezpłatnego okresu próbnego. Pro kosztuje 5,99 € w pierwszym miesiącu, a następnie 7,99 € miesięcznie przy odnowieniu; uzyskaj dostęp premium i aż 2 bonusy lojalnościowe co 30 dni.",
    schoolsTitle: "Program dla szkół | Tatik.space Pro",
    schoolsDescription: "Złóż wniosek o 30-dniowy kurs dla maksymalnie 30 uczniów. Wymagana jest akceptacja placówki; zaproszenia wykorzystują jednorazowe tokeny.",
    schoolsHeading: "Wspólna przestrzeń do pracy nad kursem",
    schoolsIntro: "Program szkolny zapewnia 30 dni dostępu do kursu dla maksymalnie 30 uczniów. Placówka musi uzyskać zgodę Tatik.",
  },
  nl: {
    marketplaceTitle: "Websjablonen | Tatik.space Pro",
    marketplaceDescription: "Ontdek gratis en premium websjablonen. Bekijk vooraf het voorbeeld en voltooi de checkout in enkele stappen; ontwikkelaarsaanbiedingen worden gecontroleerd voordat ze worden gepubliceerd.",
    marketplaceHeading: "Sjablonen om jouw volgende project vorm te geven",
    marketplaceIntro: "Ontdek gratis en premium websjablonen, bekijk ze vooraf en kopieer code alleen wanneer een sjabloon gratis is of je al toegang hebt.",
    pricingTitle: "Abonnementen en prijzen | Tatik.space Pro",
    pricingDescription: "Ontdek het Pro-abonnement met 60 dagen gratis proefperiode, premium voordelen en maximaal 2 loyaliteitsbonussen per 30 dagen. Ontworpen voor groei zonder compromissen.",
    pricingHeading: "Kies het abonnement dat bij jouw workflow past",
    pricingIntro: "Start met 60 dagen gratis proefperiode. Pro kost €5,99 in de eerste maand en daarna €7,99 per maand bij verlenging; krijg premium toegang en maximaal 2 loyaliteitsbonussen per 30 dagen.",
    schoolsTitle: "Scholenprogramma | Tatik.space Pro",
    schoolsDescription: "Vraag een schoolcursus van 30 dagen aan voor maximaal 30 leerlingen. Goedkeuring van de instelling is vereist; uitnodigingen gebruiken eenmalige tokens.",
    schoolsHeading: "Een gedeelde werkplek voor je cursus",
    schoolsIntro: "Het scholenprogramma biedt 30 dagen toegang per cursus voor maximaal 30 leerlingen. De instelling moet worden goedgekeurd door Tatik.",
  },
  tr: {
    marketplaceTitle: "Web şablonları | Tatik.space Pro",
    marketplaceDescription: "Ücretsiz ve premium web şablonlarını keşfedin. Satın almadan önce önizlemeyi inceleyin ve birkaç adımda ödeme işlemini tamamlayın; geliştirici listeleri yayın öncesi kontrol edilir.",
    marketplaceHeading: "Bir sonraki projenizin şekillenmesi için şablonlar",
    marketplaceIntro: "Ücretsiz ve premium web şablonlarını keşfedin, satın almadan önce önizlemelerini inceleyin ve kodu yalnızca ücretsiz bir şablonda veya zaten erişiminiz varsa kopyalayın.",
    pricingTitle: "Planlar ve fiyatlar | Tatik.space Pro",
    pricingDescription: "60 günlük ücretsiz deneme, premium avantajlar ve her 30 günde en fazla 2 sadakat bonusu sunan Pro planını keşfedin. Sorunsuz büyüme için tasarlandı.",
    pricingHeading: "İş akışınıza uygun planı seçin",
    pricingIntro: "60 günlük ücretsiz denemeyle başlayın. Pro ilk ay €5,99, yenilemede aylık €7,99; premium erişim ve her 30 günde en fazla 2 sadakat bonusu kazanın.",
    schoolsTitle: "Okul programı | Tatik.space Pro",
    schoolsDescription: "En fazla 30 öğrenci için 30 günlük bir okul kursu talep edin. Kurum onayı gerekir; öğrenci davetlerinde tek kullanımlık tokenlar kullanılır.",
    schoolsHeading: "Kursunuz için ortak çalışma alanı",
    schoolsIntro: "Okul programı, her kurs için en fazla 30 öğrenciye 30 günlük erişim sunar. Kurum Tatik tarafından onaylanmalıdır.",
  },
  sv: {
    marketplaceTitle: "Webbmallar | Tatik.space Pro",
    marketplaceDescription: "Utforska kostnadsfria webbmallar och premiummallar. Förhandsgranska innan du köper och slutför betalningen i några steg; utvecklarannonser granskas innan publicering.",
    marketplaceHeading: "Mallar för ditt nästa webbprojekt",
    marketplaceIntro: "Utforska kostnadsfria webbmallar och premiummallar, förhandsgranska dem innan du köper och kopiera koden endast om mallen är gratis eller du redan har tillgång.",
    pricingTitle: "Abonnemang och priser | Tatik.space Pro",
    pricingDescription: "Upptäck Pro-planen med 60 dagars gratis provperiod, premiumfördelar och upp till 2 lojalitetsbonusar var 30:e dag. Byggd för tillväxt utan kompromisser.",
    pricingHeading: "Välj det abonnemang som passar ditt arbetsflöde",
    pricingIntro: "Börja med 60 dagars gratis provperiod. Pro kostar 5,99 € första månaden och därefter 7,99 € per månad vid förnyelse; få premiumåtkomst och upp till 2 lojalitetsbonusar var 30:e dag.",
    schoolsTitle: "Skolprogram | Tatik.space Pro",
    schoolsDescription: "Ansök om en 30-dagars skolkurs för högst 30 elever. Skolan måste godkännas; elevinbjudningar använder engångstoken.",
    schoolsHeading: "En gemensam arbetsyta för kursen",
    schoolsIntro: "Skolprogrammet ger 30 dagars åtkomst per kurs för högst 30 elever. Tatik måste godkänna skolan.",
  },
  da: {
    marketplaceTitle: "Webskabeloner | Tatik.space Pro",
    marketplaceDescription: "Udforsk gratis og premium webskabeloner. Se forhåndsvisningen før køb og afslut betalingen i få trin; udviklerannoncer kontrolleres før publicering.",
    marketplaceHeading: "Skabeloner til dit næste webprojekt",
    marketplaceIntro: "Udforsk gratis og premium webskabeloner, se forhåndsvisningen før køb og kopier kun kode, hvis skabelonen er gratis eller du allerede har adgang.",
    pricingTitle: "Abonnementer og priser | Tatik.space Pro",
    pricingDescription: "Udforsk Pro-planen med 60 dages gratis prøveperiode, premiumfordele og op til 2 loyalitetsbonusser hver 30. dag. Designet til vækst uden kompromiser.",
    pricingHeading: "Vælg det abonnement, der passer til dit workflow",
    pricingIntro: "Start med 60 dages gratis prøveperiode. Pro koster 5,99 € den første måned og derefter 7,99 € om måneden ved fornyelse; få premiumadgang og op til 2 loyalitetsbonusser hver 30. dag.",
    schoolsTitle: "Skoleprogram | Tatik.space Pro",
    schoolsDescription: "Ansøg om et 30-dages skolekursus for højst 30 elever. Institutionen skal godkendes; elevinvitationer bruger engangstokens.",
    schoolsHeading: "Et fælles arbejdsområde til dit kursus",
    schoolsIntro: "Skoleprogrammet giver 30 dages adgang pr. kursus for højst 30 elever. Institutionen skal godkendes af Tatik.",
  },
  no: {
    marketplaceTitle: "Webmaler | Tatik.space Pro",
    marketplaceDescription: "Utforsk gratis og premium webmaler. Se forhåndsvisningen før kjøp og fullfør betalingen i få trinn; utvikleroppføringer granskes før publisering.",
    marketplaceHeading: "Maler for ditt neste webprosjekt",
    marketplaceIntro: "Utforsk gratis og premium webmaler, se forhåndsvisningen før kjøp og kopier kun kode når malen er gratis eller du allerede har tilgang.",
    pricingTitle: "Abonnement og priser | Tatik.space Pro",
    pricingDescription: "Oppdag Pro-planen med 60 dagers gratis prøveperiode, premiumfordeler og opptil 2 lojalitetsbonuser hver 30. dag. Bygget for vekst uten kompromisser.",
    pricingHeading: "Velg abonnementet som passer arbeidsflyten din",
    pricingIntro: "Start med 60 dagers gratis prøveperiode. Pro koster €5,99 den første måneden og deretter €7,99 per måned ved fornyelse; få premiumtilgang og opptil 2 lojalitetsbonuser hver 30. dag.",
    schoolsTitle: "Skoleprogram | Tatik.space Pro",
    schoolsDescription: "Søk om et 30-dagers skolekurs for opptil 30 elever. Institusjonen må godkjennes; invitasjoner bruker engangstokener.",
    schoolsHeading: "Et felles arbeidsområde for kurset",
    schoolsIntro: "Skoleprogrammet gir 30 dagers tilgang per kurs for opptil 30 elever. Tatik må godkjenne institusjonen.",
  },
  fi: {
    marketplaceTitle: "Verkkosivupohjat | Tatik.space Pro",
    marketplaceDescription: "Tutustu maksuttomiin ja premium-verkkosivupohjiin. Tarkista esikatselu ennen ostoa ja viimeistele maksu muutamassa vaiheessa; kehittäjien ilmoitukset tarkistetaan ennen julkaisemista.",
    marketplaceHeading: "Pohjia seuraavaan verkkoprojektiisi",
    marketplaceIntro: "Tutustu maksuttomiin ja premium-verkkosivupohjiin, tarkista esikatselu ennen ostoa ja kopioi koodi vain, jos pohja on ilmainen tai sinulla on jo käyttöoikeus.",
    pricingTitle: "Tilaukset ja hinnat | Tatik.space Pro",
    pricingDescription: "Tutustu Pro-tuotteeseen, joka sisältää 60 päivän ilmaisen kokeilun, premium-etuja ja jopa 2 lojaalisuusbonusta joka 30. päivä. Suunniteltu kasvulle ilman kompromisseja.",
    pricingHeading: "Valitse työskentelytapaan sopiva tilaus",
    pricingIntro: "Aloita 60 päivän ilmaisella kokeilulla. Pro maksaa 5,99 € ensimmäiseltä kuukaudelta ja 7,99 € kuukaudessa uusittaessa; hanki premium-käyttöoikeus ja jopa 2 lojaalisuusbonusta joka 30. päivä.",
    schoolsTitle: "Kouluohjelma | Tatik.space Pro",
    schoolsDescription: "Hae 30 päivän koulukurssia enintään 30 oppilaalle. Oppilaitos tarvitsee hyväksynnän; oppilaskutsut käyttävät kertakäyttöisiä tunnisteita.",
    schoolsHeading: "Yhteinen työtila kurssillesi",
    schoolsIntro: "Kouluohjelma tarjoaa 30 päivän käyttöoikeuden kurssia kohden enintään 30 oppilaalle. Tatikin on hyväksyttävä oppilaitos.",
  },
  uk: {
    marketplaceTitle: "Вебшаблони | Tatik.space Pro",
    marketplaceDescription: "Переглядайте безкоштовні та преміум вебшаблони. Огляньте попередній перегляд перед покупкою та завершіть оплату за кілька кроків; пропозиції розробників перевіряються перед публікацією.",
    marketplaceHeading: "Шаблони для вашого наступного вебпроєкту",
    marketplaceIntro: "Переглядайте безкоштовні та преміум вебшаблони, оцінюйте попередній перегляд перед покупкою та копіюйте код лише якщо шаблон безкоштовний або доступ уже надано.",
    pricingTitle: "Плани й ціни | Tatik.space Pro",
    pricingDescription: "Дізнайтеся про тариф Pro з 60-денним безкоштовним пробним періодом, преміальними перевагами та до 2 бонусів лояльності кожні 30 днів. Розроблено для росту без компромісів.",
    pricingHeading: "Виберіть план під ваш workflow",
    pricingIntro: "Почніть із 60-денного безкоштовного пробного періоду. Pro коштує €5,99 за перший місяць і €7,99 на місяць під час поновлення; отримайте преміум-доступ і до 2 бонусів лояльності кожні 30 днів.",
    schoolsTitle: "Шкільна програма | Tatik.space Pro",
    schoolsDescription: "Подайте заявку на 30-денний шкільний курс для максимум 30 учнів. Заклад треба затвердити; запрошення використовують одноразові токени.",
    schoolsHeading: "Спільний робочий простір для вашого курсу",
    schoolsIntro: "Шкільна програма дає 30 днів доступу на курс для максимум 30 учнів. Заклад має бути схвалений Tatik.",
  },
  cs: {
    marketplaceTitle: "Webové šablony | Tatik.space Pro",
    marketplaceDescription: "Procházejte bezplatné a prémiové webové šablony. Zkontrolujte náhled před zakoupením a dokončete platbu během několika kroků; nabídky vývojářů jsou před publikací ověřovány.",
    marketplaceHeading: "Šablony pro váš další webový projekt",
    marketplaceIntro: "Procházejte bezplatné a prémiové webové šablony, zkontrolujte náhled před zakoupením a kopírujte kód pouze tehdy, když je šablona zdarma nebo máte již přístup.",
    pricingTitle: "Tarify a ceny | Tatik.space Pro",
    pricingDescription: "Objevte plán Pro se 60denní zkušební dobou zdarma, prémiovými výhodami a až 2 loajálními bonusy každých 30 dní. Navrženo pro růst bez kompromisů.",
    pricingHeading: "Vyberte tarif podle svého workflow",
    pricingIntro: "Začněte 60denní zkušební dobou zdarma. Pro stojí 5,99 € za první měsíc a při obnovení 7,99 € měsíčně; získejte prémiový přístup a až 2 loajální bonusy každých 30 dní.",
    schoolsTitle: "Školní program | Tatik.space Pro",
    schoolsDescription: "Požádejte o 30denní školní kurz pro maximálně 30 studentů. Instituce musí být schválena; pozvánky používají jednorázové tokeny.",
    schoolsHeading: "Společný pracovní prostor pro váš kurz",
    schoolsIntro: "Školní program poskytuje 30 dní přístupu na kurz pro maximálně 30 studentů. Instituce musí být schválena Tatik.",
  },
};
