type DeploymentPageCopy = {
  title: string;
  backHome: string;
  warningTitle: string;
  warningText: string;
  stepsTitle: string;
  stepOne: string;
  stepTwo: string;
  stepThree: string;
  openEditor: string;
  seoTitle: string;
  seoDescription: string;
};

export const deploymentPageCopy: Record<string, DeploymentPageCopy> = {
  en: {
    title: "Publishing", backHome: "Back to Home", warningTitle: "Direct deployment is not available",
    warningText: "Tatik.space Pro does not currently publish projects to a hosting service, create production URLs, or provide a working Deploy button. The editor lets you work with project files and save or download them; publishing must be completed separately with an external provider.",
    stepsTitle: "General steps with an external provider",
    stepOne: "Open the project in the editor and save its files. For local files, verify that changes were saved to the intended folder.",
    stepTwo: "Upload or connect the code with your chosen provider, following its documentation. Procedures and requirements depend on the provider and project type.",
    stepThree: "Configure the build, environment variables, domain, and publishing settings directly with the provider.",
    openEditor: "Open the editor", seoTitle: "Publish projects with an external provider | Tatik.space Pro",
    seoDescription: "Tatik.space Pro does not currently offer direct deployment or production hosting. Learn how to save or download your project and publish it with an external provider.",
  },
  it: {
    title: "Pubblicazione", backHome: "Torna alla Home", warningTitle: "Il deploy diretto non è disponibile",
    warningText: "Tatik.space Pro al momento non pubblica i progetti su un hosting, non crea URL di produzione e non offre un pulsante Deploy operativo. L’editor consente di lavorare sui file e di salvarli o scaricarli; la pubblicazione va completata separatamente presso un provider esterno.",
    stepsTitle: "Procedura generale con un provider esterno",
    stepOne: "Apri il progetto nell’editor e salva i file. Per i file locali, verifica che le modifiche siano state salvate nella cartella desiderata.",
    stepTwo: "Carica o collega il codice al provider scelto seguendo la sua documentazione. Le procedure e i requisiti dipendono dal provider e dal tipo di progetto.",
    stepThree: "Configura build, variabili d’ambiente, dominio e impostazioni di pubblicazione direttamente nel provider.",
    openEditor: "Apri l’editor", seoTitle: "Pubblica i progetti con un provider esterno | Tatik.space Pro",
    seoDescription: "Tatik.space Pro non offre attualmente il deploy diretto né hosting di produzione. Scopri come salvare o scaricare il progetto e pubblicarlo con un provider esterno.",
  },
  es: {
    title: "Publicación", backHome: "Volver al inicio", warningTitle: "El despliegue directo no está disponible",
    warningText: "Actualmente, Tatik.space Pro no publica proyectos en un servicio de alojamiento, no crea URL de producción ni ofrece un botón de despliegue operativo. El editor permite trabajar con los archivos del proyecto, guardarlos o descargarlos; la publicación debe completarse por separado con un proveedor externo.",
    stepsTitle: "Pasos generales con un proveedor externo",
    stepOne: "Abre el proyecto en el editor y guarda sus archivos. Si son archivos locales, comprueba que los cambios se hayan guardado en la carpeta prevista.",
    stepTwo: "Sube o conecta el código al proveedor que elijas siguiendo su documentación. Los procedimientos y requisitos dependen del proveedor y del tipo de proyecto.",
    stepThree: "Configura la compilación, las variables de entorno, el dominio y las opciones de publicación directamente en el proveedor.",
    openEditor: "Abrir el editor", seoTitle: "Publica proyectos con un proveedor externo | Tatik.space Pro",
    seoDescription: "Tatik.space Pro no ofrece actualmente despliegue directo ni alojamiento de producción. Aprende a guardar o descargar tu proyecto y publicarlo con un proveedor externo.",
  },
  fr: {
    title: "Publication", backHome: "Retour à l’accueil", warningTitle: "Le déploiement direct n’est pas disponible",
    warningText: "Tatik.space Pro ne publie actuellement pas les projets sur un service d’hébergement, ne crée pas d’URL de production et ne propose pas de bouton de déploiement fonctionnel. L’éditeur permet de travailler sur les fichiers du projet, de les enregistrer ou de les télécharger ; la publication doit être effectuée séparément auprès d’un fournisseur externe.",
    stepsTitle: "Étapes générales avec un fournisseur externe",
    stepOne: "Ouvrez le projet dans l’éditeur et enregistrez ses fichiers. Pour les fichiers locaux, vérifiez que les modifications ont été enregistrées dans le dossier prévu.",
    stepTwo: "Téléversez le code ou connectez-le au fournisseur de votre choix en suivant sa documentation. Les procédures et exigences dépendent du fournisseur et du type de projet.",
    stepThree: "Configurez la compilation, les variables d’environnement, le domaine et les paramètres de publication directement chez le fournisseur.",
    openEditor: "Ouvrir l’éditeur", seoTitle: "Publier des projets avec un fournisseur externe | Tatik.space Pro",
    seoDescription: "Tatik.space Pro ne propose actuellement ni déploiement direct ni hébergement de production. Découvrez comment enregistrer ou télécharger votre projet et le publier avec un fournisseur externe.",
  },
  de: {
    title: "Veröffentlichen", backHome: "Zurück zur Startseite", warningTitle: "Direktes Deployment ist nicht verfügbar",
    warningText: "Tatik.space Pro veröffentlicht Projekte derzeit nicht bei einem Hosting-Anbieter, erstellt keine Produktions-URLs und bietet keine funktionsfähige Deploy-Schaltfläche. Im Editor kannst du Projektdateien bearbeiten, speichern oder herunterladen; die Veröffentlichung muss separat bei einem externen Anbieter erfolgen.",
    stepsTitle: "Allgemeine Schritte bei einem externen Anbieter",
    stepOne: "Öffne das Projekt im Editor und speichere die Dateien. Prüfe bei lokalen Dateien, ob die Änderungen im gewünschten Ordner gespeichert wurden.",
    stepTwo: "Lade den Code gemäß der Dokumentation deines Anbieters hoch oder verbinde ihn damit. Ablauf und Anforderungen hängen vom Anbieter und Projekttyp ab.",
    stepThree: "Konfiguriere Build, Umgebungsvariablen, Domain und Veröffentlichungseinstellungen direkt beim Anbieter.",
    openEditor: "Editor öffnen", seoTitle: "Projekte mit einem externen Anbieter veröffentlichen | Tatik.space Pro",
    seoDescription: "Tatik.space Pro bietet derzeit weder direktes Deployment noch Produktionshosting. Erfahre, wie du dein Projekt speicherst oder herunterlädst und extern veröffentlichst.",
  },
  pt: {
    title: "Publicação", backHome: "Voltar ao início", warningTitle: "A implementação direta não está disponível",
    warningText: "Atualmente, o Tatik.space Pro não publica projetos num serviço de alojamento, não cria URLs de produção nem disponibiliza um botão de implementação funcional. O editor permite trabalhar nos ficheiros do projeto, guardá-los ou transferi-los; a publicação tem de ser feita separadamente através de um fornecedor externo.",
    stepsTitle: "Passos gerais com um fornecedor externo",
    stepOne: "Abra o projeto no editor e guarde os ficheiros. No caso de ficheiros locais, confirme que as alterações foram guardadas na pasta pretendida.",
    stepTwo: "Carregue ou ligue o código ao fornecedor escolhido, seguindo a documentação deste. Os procedimentos e requisitos dependem do fornecedor e do tipo de projeto.",
    stepThree: "Configure a compilação, as variáveis de ambiente, o domínio e as definições de publicação diretamente no fornecedor.",
    openEditor: "Abrir o editor", seoTitle: "Publique projetos com um fornecedor externo | Tatik.space Pro",
    seoDescription: "Atualmente, o Tatik.space Pro não oferece implementação direta nem alojamento de produção. Saiba como guardar ou transferir o projeto e publicá-lo através de um fornecedor externo.",
  },
  ru: {
    title: "Публикация", backHome: "На главную", warningTitle: "Прямое развёртывание недоступно",
    warningText: "В настоящее время Tatik.space Pro не публикует проекты на хостинге, не создаёт рабочие URL для production и не предоставляет действующую кнопку Deploy. В редакторе можно работать с файлами проекта, сохранять и скачивать их; публикацию необходимо выполнять отдельно у внешнего провайдера.",
    stepsTitle: "Общие шаги для внешнего провайдера",
    stepOne: "Откройте проект в редакторе и сохраните файлы. Для локальных файлов убедитесь, что изменения сохранены в нужной папке.",
    stepTwo: "Загрузите код или подключите его к выбранному провайдеру, следуя его документации. Процедуры и требования зависят от провайдера и типа проекта.",
    stepThree: "Настройте сборку, переменные окружения, домен и параметры публикации непосредственно у провайдера.",
    openEditor: "Открыть редактор", seoTitle: "Публикация проектов через внешнего провайдера | Tatik.space Pro",
    seoDescription: "Tatik.space Pro пока не предоставляет прямое развёртывание и production-хостинг. Узнайте, как сохранить или скачать проект и опубликовать его у внешнего провайдера.",
  },
  zh: {
    title: "发布", backHome: "返回主页", warningTitle: "目前不支持直接部署",
    warningText: "Tatik.space Pro 目前不会将项目发布到托管服务、创建生产环境网址，也没有可用的 Deploy 按钮。你可以在编辑器中处理项目文件并保存或下载；发布需要通过外部服务商另行完成。",
    stepsTitle: "使用外部服务商的一般步骤",
    stepOne: "在编辑器中打开项目并保存文件。如果使用本地文件，请确认更改已保存到目标文件夹。",
    stepTwo: "按照所选服务商的文档上传代码或连接代码库。具体流程和要求取决于服务商及项目类型。",
    stepThree: "直接在服务商处配置构建、环境变量、域名和发布设置。",
    openEditor: "打开编辑器", seoTitle: "通过外部服务商发布项目 | Tatik.space Pro",
    seoDescription: "Tatik.space Pro 目前不提供直接部署或生产环境托管。了解如何保存或下载项目，并通过外部服务商发布。",
  },
  ja: {
    title: "公開", backHome: "ホームに戻る", warningTitle: "Tatik からの直接デプロイには対応していません",
    warningText: "Tatik.space Pro は現在、ホスティングへのプロジェクト公開、本番 URL の作成、動作する Deploy ボタンを提供していません。エディターではプロジェクトファイルの編集、保存、ダウンロードができます。公開作業は外部プロバイダーで別途行ってください。",
    stepsTitle: "外部プロバイダーを使う一般的な手順",
    stepOne: "エディターでプロジェクトを開いてファイルを保存します。ローカルファイルの場合は、変更が目的のフォルダーに保存されたことを確認してください。",
    stepTwo: "プロバイダーのドキュメントに従って、コードをアップロードするか接続します。手順や要件はプロバイダーとプロジェクトの種類によって異なります。",
    stepThree: "ビルド、環境変数、ドメイン、公開設定はプロバイダー側で直接設定してください。",
    openEditor: "エディターを開く", seoTitle: "外部プロバイダーを使ってプロジェクトを公開 | Tatik.space Pro",
    seoDescription: "Tatik.space Pro は現在、直接デプロイや本番ホスティングを提供していません。プロジェクトを保存またはダウンロードし、外部プロバイダーで公開する方法を確認できます。",
  },
  ko: {
    title: "게시", backHome: "홈으로 돌아가기", warningTitle: "직접 배포는 지원되지 않습니다",
    warningText: "현재 Tatik.space Pro는 호스팅 서비스에 프로젝트를 게시하거나 프로덕션 URL을 만들지 않으며, 작동하는 Deploy 버튼도 제공하지 않습니다. 편집기에서 프로젝트 파일을 편집하고 저장하거나 다운로드할 수 있으며, 게시 작업은 외부 제공업체에서 별도로 완료해야 합니다.",
    stepsTitle: "외부 제공업체를 이용하는 일반적인 단계",
    stepOne: "편집기에서 프로젝트를 열고 파일을 저장하세요. 로컬 파일은 변경 사항이 원하는 폴더에 저장되었는지 확인하세요.",
    stepTwo: "선택한 제공업체의 문서를 참고해 코드를 업로드하거나 연결하세요. 절차와 요구 사항은 제공업체 및 프로젝트 유형에 따라 다릅니다.",
    stepThree: "빌드, 환경 변수, 도메인 및 게시 설정은 제공업체에서 직접 구성하세요.",
    openEditor: "편집기 열기", seoTitle: "외부 제공업체를 통한 프로젝트 게시 | Tatik.space Pro",
    seoDescription: "Tatik.space Pro는 현재 직접 배포나 프로덕션 호스팅을 제공하지 않습니다. 프로젝트를 저장하거나 다운로드하고 외부 제공업체를 통해 게시하는 방법을 알아보세요.",
  },
  ar: {
    title: "النشر", backHome: "العودة إلى الصفحة الرئيسية", warningTitle: "النشر المباشر غير متاح",
    warningText: "لا تنشر Tatik.space Pro المشاريع حاليًا على خدمات الاستضافة، ولا تنشئ عناوين إنتاج، ولا توفر زر Deploy يعمل. يتيح المحرر العمل على ملفات المشروع وحفظها أو تنزيلها؛ ويجب إكمال النشر بشكل منفصل لدى مزود خارجي.",
    stepsTitle: "خطوات عامة باستخدام مزود خارجي",
    stepOne: "افتح المشروع في المحرر واحفظ ملفاته. بالنسبة إلى الملفات المحلية، تأكد من حفظ التغييرات في المجلد المطلوب.",
    stepTwo: "ارفع التعليمات البرمجية أو اربطها بالمزود الذي تختاره باتباع وثائقه. تختلف الإجراءات والمتطلبات حسب المزود ونوع المشروع.",
    stepThree: "اضبط عملية البناء ومتغيرات البيئة والنطاق وإعدادات النشر مباشرة لدى المزود.",
    openEditor: "فتح المحرر", seoTitle: "انشر المشاريع باستخدام مزود خارجي | Tatik.space Pro",
    seoDescription: "لا يوفر Tatik.space Pro حاليًا النشر المباشر أو استضافة الإنتاج. تعرّف على كيفية حفظ المشروع أو تنزيله ونشره باستخدام مزود خارجي.",
  },
  hi: {
    title: "प्रकाशित करना", backHome: "होम पर वापस जाएँ", warningTitle: "सीधा डिप्लॉयमेंट उपलब्ध नहीं है",
    warningText: "Tatik.space Pro अभी प्रोजेक्ट को होस्टिंग सेवा पर प्रकाशित नहीं करता, प्रोडक्शन URL नहीं बनाता और काम करने वाला Deploy बटन नहीं देता। एडिटर में प्रोजेक्ट फ़ाइलों पर काम करके उन्हें सहेजा या डाउनलोड किया जा सकता है; प्रकाशन बाहरी प्रदाता के माध्यम से अलग से पूरा करना होगा।",
    stepsTitle: "बाहरी प्रदाता के साथ सामान्य चरण",
    stepOne: "एडिटर में प्रोजेक्ट खोलें और फ़ाइलें सहेजें। स्थानीय फ़ाइलों के लिए पुष्टि करें कि बदलाव सही फ़ोल्डर में सहेजे गए हैं।",
    stepTwo: "चुने हुए प्रदाता के दस्तावेज़ों के अनुसार कोड अपलोड करें या कनेक्ट करें। प्रक्रिया और आवश्यकताएँ प्रदाता तथा प्रोजेक्ट के प्रकार पर निर्भर करती हैं।",
    stepThree: "बिल्ड, पर्यावरण चर, डोमेन और प्रकाशन सेटिंग सीधे प्रदाता के यहाँ कॉन्फ़िगर करें।",
    openEditor: "एडिटर खोलें", seoTitle: "बाहरी प्रदाता से प्रोजेक्ट प्रकाशित करें | Tatik.space Pro",
    seoDescription: "Tatik.space Pro अभी सीधे डिप्लॉयमेंट या प्रोडक्शन होस्टिंग की सुविधा नहीं देता। जानें कि प्रोजेक्ट कैसे सहेजें या डाउनलोड करें और बाहरी प्रदाता से प्रकाशित करें।",
  },
  pl: {
    title: "Publikowanie", backHome: "Wróć na stronę główną", warningTitle: "Bezpośrednie wdrażanie nie jest dostępne",
    warningText: "Tatik.space Pro nie publikuje obecnie projektów w usługach hostingowych, nie tworzy produkcyjnych adresów URL i nie udostępnia działającego przycisku Deploy. Edytor umożliwia pracę z plikami projektu oraz ich zapisywanie lub pobieranie; publikację należy przeprowadzić osobno u zewnętrznego dostawcy.",
    stepsTitle: "Ogólne kroki u zewnętrznego dostawcy",
    stepOne: "Otwórz projekt w edytorze i zapisz pliki. W przypadku plików lokalnych sprawdź, czy zmiany zostały zapisane w odpowiednim folderze.",
    stepTwo: "Prześlij kod lub połącz go z wybranym dostawcą zgodnie z jego dokumentacją. Procedury i wymagania zależą od dostawcy oraz rodzaju projektu.",
    stepThree: "Skonfiguruj kompilację, zmienne środowiskowe, domenę i ustawienia publikacji bezpośrednio u dostawcy.",
    openEditor: "Otwórz edytor", seoTitle: "Publikuj projekty u zewnętrznego dostawcy | Tatik.space Pro",
    seoDescription: "Tatik.space Pro nie oferuje obecnie bezpośredniego wdrażania ani hostingu produkcyjnego. Dowiedz się, jak zapisać lub pobrać projekt i opublikować go u zewnętrznego dostawcy.",
  },
  nl: {
    title: "Publiceren", backHome: "Terug naar home", warningTitle: "Directe deployment is niet beschikbaar",
    warningText: "Tatik.space Pro publiceert projecten momenteel niet bij een hostingdienst, maakt geen productie-URL's aan en biedt geen werkende Deploy-knop. In de editor kun je projectbestanden bewerken, opslaan of downloaden; publiceren moet je apart doen via een externe provider.",
    stepsTitle: "Algemene stappen met een externe provider",
    stepOne: "Open het project in de editor en sla de bestanden op. Controleer bij lokale bestanden of wijzigingen in de juiste map zijn opgeslagen.",
    stepTwo: "Upload de code of koppel deze aan de provider van je keuze volgens diens documentatie. De procedure en vereisten verschillen per provider en projecttype.",
    stepThree: "Configureer build, omgevingsvariabelen, domein en publicatie-instellingen rechtstreeks bij de provider.",
    openEditor: "Editor openen", seoTitle: "Projecten publiceren via een externe provider | Tatik.space Pro",
    seoDescription: "Tatik.space Pro biedt momenteel geen directe deployment of productiehosting. Lees hoe je je project opslaat of downloadt en via een externe provider publiceert.",
  },
  tr: {
    title: "Yayınlama", backHome: "Ana sayfaya dön", warningTitle: "Doğrudan dağıtım kullanılamıyor",
    warningText: "Tatik.space Pro şu anda projeleri bir barındırma hizmetinde yayınlamaz, üretim URL'leri oluşturmaz ve çalışan bir Deploy düğmesi sunmaz. Düzenleyicide proje dosyaları üzerinde çalışabilir, dosyaları kaydedebilir veya indirebilirsiniz; yayınlama işlemi harici bir sağlayıcıda ayrıca tamamlanmalıdır.",
    stepsTitle: "Harici sağlayıcıyla genel adımlar",
    stepOne: "Projeyi düzenleyicide açın ve dosyaları kaydedin. Yerel dosyalarda değişikliklerin istenen klasöre kaydedildiğini doğrulayın.",
    stepTwo: "Sağlayıcının belgelerini izleyerek kodu seçtiğiniz sağlayıcıya yükleyin veya bağlayın. İşlem ve gereksinimler sağlayıcıya ve proje türüne göre değişir.",
    stepThree: "Derleme, ortam değişkenleri, etki alanı ve yayınlama ayarlarını doğrudan sağlayıcıda yapılandırın.",
    openEditor: "Düzenleyiciyi aç", seoTitle: "Projeleri harici bir sağlayıcıyla yayınlayın | Tatik.space Pro",
    seoDescription: "Tatik.space Pro şu anda doğrudan dağıtım veya üretim barındırması sunmaz. Projenizi nasıl kaydedip indireceğinizi ve harici bir sağlayıcıyla yayınlayacağınızı öğrenin.",
  },
  sv: {
    title: "Publicering", backHome: "Tillbaka till startsidan", warningTitle: "Direkt driftsättning är inte tillgänglig",
    warningText: "Tatik.space Pro publicerar för närvarande inte projekt på en värdtjänst, skapar inga produktions-URL:er och erbjuder ingen fungerande Deploy-knapp. I editorn kan du arbeta med projektfiler och spara eller ladda ned dem; publiceringen måste slutföras separat hos en extern leverantör.",
    stepsTitle: "Allmänna steg hos en extern leverantör",
    stepOne: "Öppna projektet i editorn och spara filerna. Kontrollera att ändringar i lokala filer har sparats i avsedd mapp.",
    stepTwo: "Ladda upp eller anslut koden till den leverantör du väljer enligt leverantörens dokumentation. Rutiner och krav beror på leverantören och projekttypen.",
    stepThree: "Konfigurera byggprocess, miljövariabler, domän och publiceringsinställningar direkt hos leverantören.",
    openEditor: "Öppna editorn", seoTitle: "Publicera projekt med en extern leverantör | Tatik.space Pro",
    seoDescription: "Tatik.space Pro erbjuder för närvarande inte direkt driftsättning eller produktionshosting. Läs hur du sparar eller laddar ned projektet och publicerar det hos en extern leverantör.",
  },
  da: {
    title: "Udgivelse", backHome: "Tilbage til forsiden", warningTitle: "Direkte udrulning er ikke tilgængelig",
    warningText: "Tatik.space Pro udgiver i øjeblikket ikke projekter på en hostingtjeneste, opretter ikke produktions-URL'er og tilbyder ikke en fungerende Deploy-knap. I editoren kan du arbejde med projektfiler og gemme eller downloade dem; udgivelsen skal gennemføres separat hos en ekstern udbyder.",
    stepsTitle: "Generelle trin hos en ekstern udbyder",
    stepOne: "Åbn projektet i editoren, og gem filerne. Kontrollér for lokale filer, at ændringerne er gemt i den ønskede mappe.",
    stepTwo: "Upload eller forbind koden til den valgte udbyder ved at følge udbyderens dokumentation. Fremgangsmåde og krav afhænger af udbyderen og projekttypen.",
    stepThree: "Konfigurér build, miljøvariabler, domæne og udgivelsesindstillinger direkte hos udbyderen.",
    openEditor: "Åbn editoren", seoTitle: "Udgiv projekter hos en ekstern udbyder | Tatik.space Pro",
    seoDescription: "Tatik.space Pro tilbyder i øjeblikket ikke direkte udrulning eller produktionshosting. Se, hvordan du gemmer eller downloader projektet og udgiver det hos en ekstern udbyder.",
  },
  no: {
    title: "Publisering", backHome: "Tilbake til forsiden", warningTitle: "Direkte utrulling er ikke tilgjengelig",
    warningText: "Tatik.space Pro publiserer for øyeblikket ikke prosjekter på en vertstjeneste, oppretter ikke produksjonsadresser og tilbyr ikke en fungerende Deploy-knapp. I redigeringsverktøyet kan du arbeide med prosjektfiler og lagre eller laste dem ned; publiseringen må fullføres separat hos en ekstern leverandør.",
    stepsTitle: "Generelle trinn hos en ekstern leverandør",
    stepOne: "Åpne prosjektet i redigeringsverktøyet og lagre filene. For lokale filer må du kontrollere at endringene er lagret i riktig mappe.",
    stepTwo: "Last opp eller koble koden til leverandøren du velger, ved å følge dokumentasjonen deres. Fremgangsmåte og krav avhenger av leverandøren og prosjekttypen.",
    stepThree: "Konfigurer bygging, miljøvariabler, domene og publiseringsinnstillinger direkte hos leverandøren.",
    openEditor: "Åpne redigeringsverktøyet", seoTitle: "Publiser prosjekter med en ekstern leverandør | Tatik.space Pro",
    seoDescription: "Tatik.space Pro tilbyr foreløpig ikke direkte utrulling eller produksjonshotell. Se hvordan du lagrer eller laster ned prosjektet og publiserer det hos en ekstern leverandør.",
  },
  fi: {
    title: "Julkaiseminen", backHome: "Takaisin etusivulle", warningTitle: "Suora käyttöönotto ei ole käytettävissä",
    warningText: "Tatik.space Pro ei tällä hetkellä julkaise projekteja hosting-palveluun, luo tuotanto-URL-osoitteita eikä tarjoa toimivaa Deploy-painiketta. Editorissa voit käsitellä projektitiedostoja sekä tallentaa tai ladata ne; julkaisu on tehtävä erikseen ulkoisen palveluntarjoajan kautta.",
    stepsTitle: "Yleiset vaiheet ulkoisen palveluntarjoajan kanssa",
    stepOne: "Avaa projekti editorissa ja tallenna sen tiedostot. Tarkista paikallisten tiedostojen kohdalla, että muutokset tallentuivat oikeaan kansioon.",
    stepTwo: "Lataa koodi valitsemallesi palveluntarjoajalle tai yhdistä se sinne palveluntarjoajan ohjeiden mukaisesti. Menettelyt ja vaatimukset riippuvat palveluntarjoajasta ja projektin tyypistä.",
    stepThree: "Määritä koonti, ympäristömuuttujat, verkkotunnus ja julkaisuasetukset suoraan palveluntarjoajan palvelussa.",
    openEditor: "Avaa editori", seoTitle: "Julkaise projekteja ulkoisen palveluntarjoajan avulla | Tatik.space Pro",
    seoDescription: "Tatik.space Pro ei tällä hetkellä tarjoa suoraa käyttöönottoa tai tuotantohostingia. Lue, miten tallennat tai lataat projektin ja julkaiset sen ulkoisen palveluntarjoajan kautta.",
  },
  uk: {
    title: "Публікація", backHome: "На головну", warningTitle: "Пряме розгортання недоступне",
    warningText: "Tatik.space Pro наразі не публікує проєкти на хостингу, не створює production-адрес і не має робочої кнопки Deploy. У редакторі можна працювати з файлами проєкту, зберігати або завантажувати їх; публікацію потрібно окремо виконати через зовнішнього провайдера.",
    stepsTitle: "Загальні кроки із зовнішнім провайдером",
    stepOne: "Відкрийте проєкт у редакторі та збережіть файли. Для локальних файлів перевірте, чи записано зміни до потрібної папки.",
    stepTwo: "Завантажте код або підключіть його до вибраного провайдера відповідно до його документації. Процедури й вимоги залежать від провайдера та типу проєкту.",
    stepThree: "Налаштуйте збірку, змінні середовища, домен і параметри публікації безпосередньо у провайдера.",
    openEditor: "Відкрити редактор", seoTitle: "Публікуйте проєкти через зовнішнього провайдера | Tatik.space Pro",
    seoDescription: "Tatik.space Pro наразі не надає прямого розгортання чи production-хостингу. Дізнайтеся, як зберегти або завантажити проєкт і опублікувати його через зовнішнього провайдера.",
  },
  cs: {
    title: "Publikování", backHome: "Zpět na domovskou stránku", warningTitle: "Přímé nasazení není k dispozici",
    warningText: "Tatik.space Pro v současnosti nepublikuje projekty na hosting, nevytváří produkční adresy URL a nenabízí funkční tlačítko Deploy. V editoru můžete pracovat se soubory projektu a ukládat nebo stahovat je; publikování je nutné dokončit samostatně u externího poskytovatele.",
    stepsTitle: "Obecný postup u externího poskytovatele",
    stepOne: "Otevřete projekt v editoru a uložte jeho soubory. U místních souborů ověřte, že se změny uložily do požadované složky.",
    stepTwo: "Nahrajte kód nebo jej propojte s vybraným poskytovatelem podle jeho dokumentace. Postupy a požadavky závisejí na poskytovateli a typu projektu.",
    stepThree: "Nastavte sestavení, proměnné prostředí, doménu a možnosti publikování přímo u poskytovatele.",
    openEditor: "Otevřít editor", seoTitle: "Publikujte projekty pomocí externího poskytovatele | Tatik.space Pro",
    seoDescription: "Tatik.space Pro v současnosti nenabízí přímé nasazení ani produkční hosting. Zjistěte, jak projekt uložit nebo stáhnout a publikovat u externího poskytovatele.",
  },
};
