export const developerListingLanguageGuidance: Record<string, string> = {
  en: "For international visibility, write the title and description in English. Automatic translations are not available yet.",
  it: "Per raggiungere utenti internazionali, scrivi titolo e descrizione in inglese. Le traduzioni automatiche non sono ancora disponibili.",
  es: "Para llegar a usuarios internacionales, escribe el título y la descripción en inglés. Las traducciones automáticas aún no están disponibles.",
  fr: "Pour toucher un public international, rédigez le titre et la description en anglais. Les traductions automatiques ne sont pas encore disponibles.",
  de: "Für internationale Sichtbarkeit solltest du Titel und Beschreibung auf Englisch verfassen. Automatische Übersetzungen sind noch nicht verfügbar.",
  pt: "Para alcançar utilizadores internacionais, escreva o título e a descrição em inglês. As traduções automáticas ainda não estão disponíveis.",
  ru: "Чтобы привлечь международную аудиторию, укажите название и описание на английском. Автоматический перевод пока недоступен.",
  zh: "如需触达国际用户，请使用英文填写标题和描述。自动翻译功能暂不可用。",
  ja: "海外のユーザーにも届けるには、タイトルと説明を英語で入力してください。自動翻訳はまだ利用できません。",
  ko: "국제 사용자에게 노출하려면 제목과 설명을 영어로 작성하세요. 자동 번역은 아직 제공되지 않습니다.",
  ar: "للوصول إلى مستخدمين دوليين، اكتب العنوان والوصف باللغة الإنجليزية. الترجمة التلقائية غير متاحة بعد.",
  hi: "अंतरराष्ट्रीय उपयोगकर्ताओं तक पहुँचने के लिए शीर्षक और विवरण अंग्रेज़ी में लिखें। स्वचालित अनुवाद अभी उपलब्ध नहीं हैं।",
  pl: "Aby dotrzeć do międzynarodowych użytkowników, wpisz tytuł i opis po angielsku. Automatyczne tłumaczenia nie są jeszcze dostępne.",
  nl: "Schrijf de titel en beschrijving in het Engels om internationale gebruikers te bereiken. Automatische vertalingen zijn nog niet beschikbaar.",
  tr: "Uluslararası kullanıcılara ulaşmak için başlık ve açıklamayı İngilizce yazın. Otomatik çeviri henüz kullanılamıyor.",
  sv: "Skriv titel och beskrivning på engelska för att nå användare internationellt. Automatiska översättningar är inte tillgängliga ännu.",
  da: "Skriv titel og beskrivelse på engelsk for at nå internationale brugere. Automatiske oversættelser er endnu ikke tilgængelige.",
  no: "Skriv tittel og beskrivelse på engelsk for å nå internasjonale brukere. Automatiske oversettelser er ikke tilgjengelige ennå.",
  fi: "Tavoita kansainväliset käyttäjät kirjoittamalla otsikko ja kuvaus englanniksi. Automaattiset käännökset eivät ole vielä käytettävissä.",
  uk: "Щоб охопити міжнародну аудиторію, напишіть назву й опис англійською. Автоматичний переклад поки недоступний.",
  cs: "Chcete-li oslovit mezinárodní uživatele, napište název a popis anglicky. Automatické překlady zatím nejsou k dispozici.",
};
