type DocumentationPageCopy = {
  title: string;
  home: string;
  introHeading: string;
  intro: string;
  editorHeading: string;
  editorSteps: string[];
  featuresHeading: string;
  features: [string, string][];
  availabilityHeading: string;
  deployment: string;
  collaboration: string;
  apiHeading: string;
  api: string;
  formatsHeading: string;
  formatsIntro: string;
  formatGroups: string[];
  marketplaceHeading: string;
  marketplaceIntro: string;
  marketplaceRules: string[];
  marketplaceWarning: string;
  schoolsHeading: string;
  schoolsIntro: string;
  schoolsRules: string[];
  schoolsWarning: string;
  seoTitle: string;
  seoDescription: string;
};

export const documentationPageCopy: Record<string, DocumentationPageCopy> = {
  en: {
    title: "Documentation",
    home: "Back to Home",
    introHeading: "Introduction",
    intro: "This guide describes features verified in the current Tatik.space Pro interface. Availability can vary by account and by how a file or project was opened.",
    editorHeading: "Using the editor",
    editorSteps: [
      "Sign in and open Editor from the site navigation.",
      "Use the File menu to create or upload files, or open a local folder when your browser supports folder access.",
      "Select a file to edit it. Use Save or the available download options to keep a copy of your work.",
      "Use Preview for supported web projects. It does not run every language or project configuration.",
    ],
    featuresHeading: "Main features",
    features: [
      ["Code editor and preview", "Edit project files in the browser. Preview supports selected web content; it is not a general build or deployment environment."],
      ["AI assistant", "An AI assistant panel is available in the editor. Its responses depend on service configuration; automatic code fixes and keyboard shortcuts are not guaranteed."],
      ["Files and folders", "Create files and folders, upload files, and open local folders where your browser allows it. Local files and cloud-project files have different save destinations."],
      ["Backups", "Use Backup to create and restore project snapshots. Confirm that a backup completed before relying on it."],
    ],
    availabilityHeading: "Current feature status",
    deployment: "Direct publishing is not currently available in Tatik.space Pro. There is no working one-click Deploy flow or Tatik production hosting URL. Publish saved files through an external hosting provider.",
    collaboration: "The Collaboration page currently uses a fixed demo project and a generated demo user ID. It is not connected to your actual project or team; do not use it to invite real collaborators or share production data.",
    apiHeading: "API availability",
    api: "A public customer-facing REST API reference is not currently available. The app’s internal API is not documented here as a supported integration.",
    formatsHeading: "Supported languages and file formats",
    formatsIntro: "The editor recognizes supported file types and applies syntax highlighting. Preview is available only for compatible web content; recognizing a file does not mean it can be run or deployed.",
    formatGroups: ["Web and data", "Programming languages", "Configuration and documentation", "Images and local assets"],
    marketplaceHeading: "Developer marketplace",
    marketplaceIntro: "Developers can submit digital resources for review. Uploaded content remains private until the listing is approved and a purchase is verified.",
    marketplaceRules: [
      "Create a seller profile and accept the seller terms; connect Stripe and complete its verification before requesting payouts.",
      "Create a draft listing and upload its file. The current upload limit is 2 MB per file; only staff can approve, reject, or publish a listing.",
      "Tatik records a 15% commission on sales. Refunds, disputes, and anti-fraud holds can reduce or suspend the available balance.",
    ],
    marketplaceWarning: "Do not upload malware, credentials, another person’s personal data, or material you do not have rights to distribute. Payouts require an active Stripe Connect account with payments and payouts enabled.",
    schoolsHeading: "School program",
    schoolsIntro: "An approved institution can run a course for 30 days with up to 30 students. Pending or approved but unredeemed invitations also count toward the limit; student access ends when the course expires.",
    schoolsRules: [
      "An authenticated school contact submits the institution details and accepts the program terms.",
      "A Tatik administrator or staff member must approve the institution.",
      "The school contact creates and approves an invitation for a student; its token is temporary, personal, non-transferable, and single-use.",
      "The authenticated student redeems the token. The school can revoke a member’s access; these actions are recorded in the audit log.",
    ],
    schoolsWarning: "Invitations currently generate a token for the school to deliver through a controlled channel. Automatic invitation emails must be configured separately before public use.",
    seoTitle: "Tatik.space Pro documentation | Verified product guide",
    seoDescription: "Learn how to use the Tatik.space Pro editor, file tools, backups, developer marketplace, and school program, including current feature limitations.",
  },
  it: {
    title: "Documentazione",
    home: "Torna alla Home",
    introHeading: "Introduzione",
    intro: "Questa guida descrive le funzioni verificate nell’interfaccia attuale di Tatik.space Pro. La disponibilità può variare in base all’account e al modo in cui è stato aperto un file o un progetto.",
    editorHeading: "Usare l’editor",
    editorSteps: [
      "Accedi e apri Editor dalla navigazione del sito.",
      "Dal menu File puoi creare o caricare file, oppure aprire una cartella locale se il browser supporta questa funzione.",
      "Seleziona un file per modificarlo. Usa Salva o le opzioni di download disponibili per conservarne una copia.",
      "Usa Anteprima per i progetti web supportati. Non esegue tutti i linguaggi o tutte le configurazioni di progetto.",
    ],
    featuresHeading: "Funzioni principali",
    features: [
      ["Editor e anteprima", "Modifica i file del progetto nel browser. L’anteprima supporta alcuni contenuti web; non è un ambiente generico di build o pubblicazione."],
      ["Assistente AI", "Nell’editor è disponibile un pannello di assistenza AI. Le risposte dipendono dalla configurazione del servizio; non sono garantite correzioni automatiche né scorciatoie da tastiera."],
      ["File e cartelle", "Crea cartelle e file, carica file e apri cartelle locali quando il browser lo consente. File locali e file del progetto cloud hanno destinazioni di salvataggio diverse."],
      ["Backup", "Usa Backup per creare e ripristinare snapshot del progetto. Verifica che il backup sia stato completato prima di farci affidamento."],
    ],
    availabilityHeading: "Stato attuale delle funzioni",
    deployment: "La pubblicazione diretta non è attualmente disponibile in Tatik.space Pro. Non è presente un flusso Deploy funzionante con un clic né un URL di hosting di produzione Tatik. Pubblica i file salvati tramite un provider esterno.",
    collaboration: "La pagina Collaborazione usa un progetto demo fisso e un ID utente demo generato. Non è collegata al progetto o al team reale dell’utente: non usarla per invitare collaboratori o condividere dati di produzione.",
    apiHeading: "Disponibilità delle API",
    api: "Al momento non è disponibile una documentazione pubblica delle API REST per i clienti. Le API interne dell’app non sono descritte qui come integrazione supportata.",
    formatsHeading: "Linguaggi e formati supportati",
    formatsIntro: "L’editor riconosce i tipi di file supportati e applica l’evidenziazione della sintassi. L’anteprima è disponibile solo per contenuti web compatibili: riconoscere un file non significa poterlo eseguire o pubblicare.",
    formatGroups: ["Web e dati", "Linguaggi di programmazione", "Configurazione e documentazione", "Immagini e risorse locali"],
    marketplaceHeading: "Marketplace sviluppatori",
    marketplaceIntro: "Gli sviluppatori possono candidare risorse digitali per la revisione. I file caricati restano privati finché il listing non è approvato e l’acquisto verificato.",
    marketplaceRules: [
      "Crea un profilo venditore e accetta i relativi termini; collega Stripe e completa la verifica prima di richiedere payout.",
      "Crea un listing in bozza e carica il file. Il limite attuale è 2 MB per file; solo lo staff può approvare, rifiutare o pubblicare un listing.",
      "Tatik registra una commissione del 15% sulle vendite. Rimborsi, contestazioni e controlli antifrode possono ridurre o sospendere il saldo disponibile.",
    ],
    marketplaceWarning: "Non caricare malware, credenziali, dati personali di terzi o materiale di cui non possiedi i diritti. I payout richiedono un account Stripe Connect attivo con pagamenti e payout abilitati.",
    schoolsHeading: "Programma scuole",
    schoolsIntro: "Un istituto approvato può attivare un corso di 30 giorni per un massimo di 30 studenti. Anche gli inviti pendenti o approvati ma non riscattati occupano un posto; l’accesso termina alla scadenza del corso.",
    schoolsRules: [
      "Un referente autenticato invia i dati dell’istituto e accetta i termini del programma.",
      "L’istituto deve essere approvato da un amministratore o collaboratore Tatik.",
      "Il referente crea e approva un invito per lo studente. Il token è temporaneo, personale, non trasferibile e monouso.",
      "Lo studente autenticato riscatta il token. La scuola può revocare l’accesso di un membro; le operazioni sono registrate nell’audit.",
    ],
    schoolsWarning: "Gli inviti generano attualmente un token che la scuola deve consegnare tramite un canale controllato. Prima dell’uso pubblico è necessario configurare separatamente l’invio automatico delle email.",
    seoTitle: "Documentazione Tatik.space Pro | Guida alle funzioni verificate",
    seoDescription: "Scopri come usare editor, file, backup, marketplace sviluppatori e programma scuole di Tatik.space Pro, con i limiti attuali delle funzioni.",
  },
  es: {
    title: "Documentación", home: "Volver al inicio", introHeading: "Introducción",
    intro: "Esta guía describe las funciones comprobadas en la interfaz actual de Tatik.space Pro. La disponibilidad puede variar según la cuenta y cómo se haya abierto el archivo o proyecto.",
    editorHeading: "Uso del editor",
    editorSteps: ["Inicia sesión y abre Editor desde la navegación del sitio.", "Usa el menú Archivo para crear o subir archivos, o abrir una carpeta local si tu navegador lo permite.", "Selecciona un archivo para editarlo. Usa Guardar o las opciones de descarga disponibles para conservar una copia.", "Usa Vista previa con proyectos web compatibles. No ejecuta todos los lenguajes ni todas las configuraciones."],
    featuresHeading: "Funciones principales",
    features: [["Editor y vista previa", "Edita archivos en el navegador. La vista previa admite ciertos contenidos web; no es un entorno general de compilación o publicación."], ["Asistente de IA", "El editor incluye un panel de asistencia de IA. Las respuestas dependen de la configuración del servicio; no se garantizan correcciones automáticas ni atajos de teclado."], ["Archivos y carpetas", "Crea y carga archivos y carpetas, y abre carpetas locales cuando el navegador lo permite. Los archivos locales y los del proyecto en la nube tienen destinos de guardado distintos."], ["Copias de seguridad", "Usa Backup para crear y restaurar instantáneas del proyecto. Comprueba que la copia se haya completado antes de confiar en ella."]],
    availabilityHeading: "Estado actual de las funciones",
    deployment: "Tatik.space Pro no permite publicar proyectos directamente por ahora. No hay un flujo Deploy operativo con un clic ni una URL de producción alojada por Tatik. Publica los archivos guardados con un proveedor externo.",
    collaboration: "La página Colaboración utiliza un proyecto de demostración fijo y un ID de usuario generado. No está conectada a tu proyecto o equipo real; no la uses para invitar a colaboradores reales ni compartir datos de producción.",
    apiHeading: "Disponibilidad de API", api: "Actualmente no hay una referencia pública de la API REST para clientes. La API interna de la aplicación no se documenta aquí como integración compatible.",
    formatsHeading: "Lenguajes y formatos compatibles", formatsIntro: "El editor reconoce los tipos de archivo compatibles y resalta la sintaxis. La vista previa solo funciona con contenido web compatible; reconocer un archivo no significa que pueda ejecutarse o publicarse.",
    formatGroups: ["Web y datos", "Lenguajes de programación", "Configuración y documentación", "Imágenes y recursos locales"],
    marketplaceHeading: "Marketplace para desarrolladores", marketplaceIntro: "Los desarrolladores pueden proponer recursos digitales para su revisión. Los archivos subidos permanecen privados hasta que se apruebe el anuncio y se verifique la compra.",
    marketplaceRules: ["Crea un perfil de vendedor y acepta sus condiciones; conecta Stripe y completa la verificación antes de solicitar pagos.", "Crea un anuncio en borrador y sube el archivo. El límite actual es de 2 MB por archivo; solo el equipo puede aprobar, rechazar o publicar anuncios.", "Tatik registra una comisión del 15 % por venta. Los reembolsos, las disputas y las retenciones antifraude pueden reducir o suspender el saldo disponible."],
    marketplaceWarning: "No subas malware, credenciales, datos personales de terceros ni material cuyos derechos no tengas. Los pagos requieren una cuenta Stripe Connect activa con pagos y retiros habilitados.",
    schoolsHeading: "Programa escolar", schoolsIntro: "Una institución aprobada puede ofrecer un curso de 30 días para un máximo de 30 estudiantes. Las invitaciones pendientes o aprobadas pero no canjeadas también cuentan para el límite; el acceso termina al finalizar el curso.",
    schoolsRules: ["Un responsable autenticado envía los datos de la institución y acepta las condiciones del programa.", "Un administrador o miembro del equipo de Tatik debe aprobar la institución.", "El responsable crea y aprueba una invitación para el estudiante. El token es temporal, personal, intransferible y de un solo uso.", "El estudiante autenticado canjea el token. La escuela puede revocar el acceso de un miembro; las acciones quedan registradas en el registro de auditoría."],
    schoolsWarning: "Actualmente, las invitaciones generan un token que la escuela debe entregar por un canal controlado. El envío automático de correos debe configurarse por separado antes del uso público.",
    seoTitle: "Documentación de Tatik.space Pro | Guía de funciones verificadas", seoDescription: "Aprende a usar el editor, los archivos, las copias de seguridad, el marketplace y el programa escolar de Tatik.space Pro, con sus limitaciones actuales.",
  },
  fr: {
    title: "Documentation", home: "Retour à l’accueil", introHeading: "Introduction",
    intro: "Ce guide décrit les fonctionnalités vérifiées dans l’interface actuelle de Tatik.space Pro. Leur disponibilité peut varier selon le compte et la manière dont un fichier ou projet a été ouvert.",
    editorHeading: "Utiliser l’éditeur",
    editorSteps: ["Connectez-vous et ouvrez l’éditeur depuis la navigation du site.", "Dans le menu Fichier, créez ou importez des fichiers, ou ouvrez un dossier local si votre navigateur le permet.", "Sélectionnez un fichier pour le modifier. Utilisez Enregistrer ou les options de téléchargement pour en conserver une copie.", "Utilisez l’aperçu pour les projets web compatibles. Il ne prend pas en charge tous les langages ni toutes les configurations."],
    featuresHeading: "Fonctionnalités principales",
    features: [["Éditeur et aperçu", "Modifiez les fichiers du projet dans le navigateur. L’aperçu prend en charge certains contenus web ; ce n’est pas un environnement général de compilation ou de déploiement."], ["Assistant IA", "Un panneau d’assistance IA est disponible dans l’éditeur. Les réponses dépendent de la configuration du service ; les corrections automatiques et raccourcis clavier ne sont pas garantis."], ["Fichiers et dossiers", "Créez et importez des fichiers ou dossiers et ouvrez des dossiers locaux si le navigateur le permet. Les fichiers locaux et ceux du projet cloud ont des destinations d’enregistrement différentes."], ["Sauvegardes", "Utilisez Backup pour créer et restaurer des instantanés du projet. Vérifiez qu’une sauvegarde est terminée avant de vous y fier."]],
    availabilityHeading: "État actuel des fonctionnalités",
    deployment: "La publication directe n’est pas encore disponible dans Tatik.space Pro. Il n’existe pas de processus Deploy opérationnel en un clic ni d’URL de production hébergée par Tatik. Publiez les fichiers enregistrés via un hébergeur externe.",
    collaboration: "La page Collaboration utilise actuellement un projet de démonstration fixe et un identifiant utilisateur généré. Elle n’est pas reliée à votre projet ou équipe réelle ; ne l’utilisez pas pour inviter de vrais collaborateurs ni partager des données de production.",
    apiHeading: "Disponibilité de l’API", api: "Il n’existe pas actuellement de référence publique de l’API REST destinée aux clients. L’API interne de l’application n’est pas documentée ici comme une intégration prise en charge.",
    formatsHeading: "Langages et formats pris en charge", formatsIntro: "L’éditeur reconnaît les types de fichiers pris en charge et applique la coloration syntaxique. L’aperçu ne concerne que les contenus web compatibles ; la reconnaissance d’un fichier ne signifie pas qu’il peut être exécuté ou publié.",
    formatGroups: ["Web et données", "Langages de programmation", "Configuration et documentation", "Images et ressources locales"],
    marketplaceHeading: "Marketplace des développeurs", marketplaceIntro: "Les développeurs peuvent proposer des ressources numériques à la révision. Les fichiers restent privés jusqu’à l’approbation de l’annonce et à la vérification de l’achat.",
    marketplaceRules: ["Créez un profil vendeur et acceptez les conditions ; connectez Stripe et terminez sa vérification avant de demander un versement.", "Créez une annonce en brouillon et importez son fichier. La limite actuelle est de 2 Mo par fichier ; seul le personnel peut approuver, refuser ou publier une annonce.", "Tatik comptabilise une commission de 15 % sur les ventes. Remboursements, litiges et contrôles antifraude peuvent réduire ou suspendre le solde disponible."],
    marketplaceWarning: "N’importez aucun logiciel malveillant, identifiant, donnée personnelle d’un tiers ni contenu dont vous ne détenez pas les droits. Les versements nécessitent un compte Stripe Connect actif avec paiements et versements activés.",
    schoolsHeading: "Programme scolaire", schoolsIntro: "Un établissement approuvé peut organiser un cours de 30 jours pour 30 élèves maximum. Les invitations en attente ou approuvées mais non utilisées comptent aussi dans la limite ; l’accès prend fin à l’expiration du cours.",
    schoolsRules: ["Un référent authentifié soumet les informations de l’établissement et accepte les conditions du programme.", "Un administrateur ou membre de l’équipe Tatik doit approuver l’établissement.", "Le référent crée et approuve une invitation pour l’élève. Le jeton est temporaire, personnel, incessible et à usage unique.", "L’élève authentifié utilise le jeton. L’établissement peut révoquer l’accès d’un membre ; ces actions sont consignées dans le journal d’audit."],
    schoolsWarning: "Les invitations génèrent actuellement un jeton que l’établissement doit transmettre par un canal contrôlé. L’envoi automatique d’e-mails doit être configuré séparément avant toute utilisation publique.",
    seoTitle: "Documentation Tatik.space Pro | Guide des fonctionnalités vérifiées", seoDescription: "Découvrez l’éditeur Tatik.space Pro, les fichiers, les sauvegardes, la marketplace et le programme scolaire, avec leurs limites actuelles.",
  },
  de: {
    title: "Dokumentation", home: "Zurück zur Startseite", introHeading: "Einführung",
    intro: "Diese Anleitung beschreibt Funktionen, die in der aktuellen Tatik.space-Pro-Oberfläche geprüft wurden. Die Verfügbarkeit kann je nach Konto und Öffnungsart einer Datei oder eines Projekts variieren.",
    editorHeading: "Den Editor verwenden",
    editorSteps: ["Melde dich an und öffne den Editor über die Seitennavigation.", "Erstelle oder lade Dateien über das Menü Datei hoch oder öffne einen lokalen Ordner, sofern dein Browser dies unterstützt.", "Wähle eine Datei zum Bearbeiten aus. Verwende Speichern oder die verfügbaren Downloadoptionen, um eine Kopie aufzubewahren.", "Nutze die Vorschau für unterstützte Webprojekte. Sie führt nicht jede Sprache und Projektkonfiguration aus."],
    featuresHeading: "Wichtige Funktionen",
    features: [["Code-Editor und Vorschau", "Bearbeite Projektdateien im Browser. Die Vorschau unterstützt ausgewählte Webinhalte; sie ist keine allgemeine Build- oder Bereitstellungsumgebung."], ["KI-Assistent", "Im Editor ist ein KI-Assistent verfügbar. Antworten hängen von der Dienstkonfiguration ab; automatische Codekorrekturen und Tastenkürzel sind nicht garantiert."], ["Dateien und Ordner", "Erstelle und lade Dateien und Ordner hoch und öffne lokale Ordner, sofern der Browser dies zulässt. Lokale Dateien und Cloud-Projektdateien werden an unterschiedlichen Orten gespeichert."], ["Backups", "Verwende Backup, um Projektsnapshots zu erstellen und wiederherzustellen. Prüfe, ob ein Backup abgeschlossen wurde, bevor du dich darauf verlässt."]],
    availabilityHeading: "Aktueller Funktionsumfang",
    deployment: "Direktes Veröffentlichen ist in Tatik.space Pro derzeit nicht verfügbar. Es gibt keinen funktionierenden Ein-Klick-Deploy-Ablauf und keine von Tatik gehostete Produktions-URL. Veröffentliche gespeicherte Dateien über einen externen Hosting-Anbieter.",
    collaboration: "Die Seite Zusammenarbeit verwendet derzeit ein festes Demo-Projekt und eine generierte Demo-Benutzer-ID. Sie ist nicht mit deinem echten Projekt oder Team verbunden; lade dort keine echten Mitwirkenden ein und teile keine Produktionsdaten.",
    apiHeading: "API-Verfügbarkeit", api: "Eine öffentliche REST-API-Referenz für Kunden ist derzeit nicht verfügbar. Die interne API der App wird hier nicht als unterstützte Integration dokumentiert.",
    formatsHeading: "Unterstützte Sprachen und Dateiformate", formatsIntro: "Der Editor erkennt unterstützte Dateitypen und hebt die Syntax hervor. Die Vorschau funktioniert nur mit kompatiblen Webinhalten; eine erkannte Datei kann deshalb nicht automatisch ausgeführt oder veröffentlicht werden.",
    formatGroups: ["Web und Daten", "Programmiersprachen", "Konfiguration und Dokumentation", "Bilder und lokale Ressourcen"],
    marketplaceHeading: "Entwickler-Marktplatz", marketplaceIntro: "Entwickler können digitale Ressourcen zur Prüfung einreichen. Hochgeladene Dateien bleiben privat, bis das Angebot genehmigt und der Kauf bestätigt wurde.",
    marketplaceRules: ["Erstelle ein Verkäuferprofil und akzeptiere die Bedingungen; verbinde Stripe und schließe die Verifizierung ab, bevor du Auszahlungen beantragst.", "Erstelle ein Angebotsentwurf und lade die Datei hoch. Das aktuelle Limit beträgt 2 MB pro Datei; nur Mitarbeitende können Angebote genehmigen, ablehnen oder veröffentlichen.", "Tatik verbucht 15 % Provision auf Verkäufe. Rückerstattungen, Streitfälle und Betrugsprüfungen können das verfügbare Guthaben verringern oder sperren."],
    marketplaceWarning: "Lade keine Schadsoftware, Zugangsdaten, personenbezogenen Daten anderer oder Inhalte hoch, an denen du keine Rechte hast. Auszahlungen erfordern ein aktives Stripe-Connect-Konto mit aktivierten Zahlungen und Auszahlungen.",
    schoolsHeading: "Schulprogramm", schoolsIntro: "Eine genehmigte Einrichtung kann einen 30-tägigen Kurs für höchstens 30 Lernende durchführen. Ausstehende oder genehmigte, aber noch nicht eingelöste Einladungen zählen ebenfalls zum Limit; der Zugang endet mit dem Kurs.",
    schoolsRules: ["Eine angemeldete Kontaktperson übermittelt die Einrichtungsdaten und akzeptiert die Programmregeln.", "Ein Tatik-Administrator oder Mitarbeitender muss die Einrichtung genehmigen.", "Die Kontaktperson erstellt und genehmigt eine Einladung. Das Token ist befristet, persönlich, nicht übertragbar und nur einmal verwendbar.", "Die angemeldete Person löst das Token ein. Die Schule kann den Zugang eines Mitglieds widerrufen; diese Aktionen werden protokolliert."],
    schoolsWarning: "Einladungen erzeugen derzeit ein Token, das die Schule über einen kontrollierten Kanal übermitteln muss. Der automatische E-Mail-Versand muss vor der öffentlichen Nutzung separat eingerichtet werden.",
    seoTitle: "Tatik.space-Pro-Dokumentation | Geprüfter Produktleitfaden", seoDescription: "Erfahre mehr über Editor, Dateien, Backups, Entwickler-Marktplatz und Schulprogramm von Tatik.space Pro sowie deren aktuelle Einschränkungen.",
  },
  pt: {
    title: "Documentação", home: "Voltar ao início", introHeading: "Introdução",
    intro: "Este guia descreve funcionalidades verificadas na interface atual do Tatik.space Pro. A disponibilidade pode variar consoante a conta e a forma como o ficheiro ou projeto foi aberto.",
    editorHeading: "Utilizar o editor",
    editorSteps: ["Inicie sessão e abra o Editor na navegação do site.", "No menu Ficheiro, crie ou carregue ficheiros, ou abra uma pasta local se o navegador permitir.", "Selecione um ficheiro para o editar. Use Guardar ou as opções de transferência disponíveis para manter uma cópia.", "Use a Pré-visualização em projetos web compatíveis. Não executa todas as linguagens nem todas as configurações."],
    featuresHeading: "Funcionalidades principais",
    features: [["Editor e pré-visualização", "Edite ficheiros do projeto no navegador. A pré-visualização suporta determinados conteúdos web; não é um ambiente geral de compilação ou publicação."], ["Assistente de IA", "O editor inclui um painel de assistência por IA. As respostas dependem da configuração do serviço; não são garantidas correções automáticas nem atalhos de teclado."], ["Ficheiros e pastas", "Crie e carregue ficheiros e pastas e abra pastas locais quando o navegador permitir. Os ficheiros locais e os do projeto na nuvem têm destinos de gravação diferentes."], ["Cópias de segurança", "Use Backup para criar e restaurar snapshots do projeto. Confirme que a cópia foi concluída antes de depender dela."]],
    availabilityHeading: "Estado atual das funcionalidades",
    deployment: "A publicação direta ainda não está disponível no Tatik.space Pro. Não existe um fluxo Deploy funcional com um clique nem um URL de produção alojado pela Tatik. Publique os ficheiros guardados através de um fornecedor externo.",
    collaboration: "A página Colaboração usa atualmente um projeto de demonstração fixo e um ID de utilizador gerado. Não está ligada ao seu projeto ou equipa reais; não a use para convidar colaboradores nem partilhar dados de produção.",
    apiHeading: "Disponibilidade da API", api: "Atualmente não existe uma referência pública da API REST para clientes. A API interna da aplicação não está documentada aqui como integração suportada.",
    formatsHeading: "Linguagens e formatos suportados", formatsIntro: "O editor reconhece tipos de ficheiro suportados e destaca a sintaxe. A pré-visualização só funciona com conteúdos web compatíveis; reconhecer um ficheiro não significa que possa ser executado ou publicado.",
    formatGroups: ["Web e dados", "Linguagens de programação", "Configuração e documentação", "Imagens e recursos locais"],
    marketplaceHeading: "Marketplace de programadores", marketplaceIntro: "Os programadores podem submeter recursos digitais para revisão. Os ficheiros carregados permanecem privados até à aprovação do anúncio e à confirmação da compra.",
    marketplaceRules: ["Crie um perfil de vendedor e aceite os termos; ligue o Stripe e conclua a verificação antes de pedir pagamentos.", "Crie um anúncio em rascunho e carregue o ficheiro. O limite atual é de 2 MB por ficheiro; só a equipa pode aprovar, rejeitar ou publicar anúncios.", "A Tatik regista uma comissão de 15% nas vendas. Reembolsos, contestações e controlos antifraude podem reduzir ou suspender o saldo disponível."],
    marketplaceWarning: "Não carregue malware, credenciais, dados pessoais de terceiros ou materiais sem os direitos necessários. Os pagamentos exigem uma conta Stripe Connect ativa com pagamentos e levantamentos ativados.",
    schoolsHeading: "Programa escolar", schoolsIntro: "Uma instituição aprovada pode realizar um curso de 30 dias para até 30 estudantes. Convites pendentes ou aprovados mas ainda não utilizados também contam para o limite; o acesso termina com o curso.",
    schoolsRules: ["Um representante autenticado envia os dados da instituição e aceita os termos do programa.", "A instituição tem de ser aprovada por um administrador ou membro da equipa Tatik.", "O representante cria e aprova um convite para o estudante. O token é temporário, pessoal, intransmissível e de utilização única.", "O estudante autenticado resgata o token. A escola pode revogar o acesso de um membro; as ações ficam registadas."],
    schoolsWarning: "Atualmente, os convites geram um token que a escola deve entregar por um canal controlado. O envio automático de emails tem de ser configurado separadamente antes da utilização pública.",
    seoTitle: "Documentação do Tatik.space Pro | Guia de funcionalidades verificadas", seoDescription: "Saiba como usar o editor, ficheiros, cópias de segurança, marketplace e programa escolar do Tatik.space Pro, incluindo as limitações atuais.",
  },
  ru: {
    title: "Документация", home: "На главную", introHeading: "Введение",
    intro: "В этом руководстве описаны функции, проверенные в текущем интерфейсе Tatik.space Pro. Их доступность может зависеть от аккаунта и способа открытия файла или проекта.",
    editorHeading: "Работа в редакторе",
    editorSteps: ["Войдите в систему и откройте редактор через навигацию сайта.", "В меню «Файл» создавайте и загружайте файлы или открывайте локальную папку, если браузер это поддерживает.", "Выберите файл для редактирования. Используйте сохранение или доступные варианты загрузки, чтобы оставить копию.", "Используйте предпросмотр для поддерживаемых веб-проектов. Он поддерживает не все языки и конфигурации."],
    featuresHeading: "Основные функции",
    features: [["Редактор кода и предпросмотр", "Редактируйте файлы проекта в браузере. Предпросмотр поддерживает отдельные веб-форматы и не является универсальной средой сборки или публикации."], ["ИИ-ассистент", "В редакторе доступна панель ИИ-ассистента. Ответы зависят от конфигурации сервиса; автоматические исправления кода и горячие клавиши не гарантируются."], ["Файлы и папки", "Создавайте и загружайте файлы и папки, открывайте локальные папки, если это разрешает браузер. Локальные файлы и файлы облачного проекта сохраняются в разные места."], ["Резервные копии", "Используйте Backup для создания и восстановления снимков проекта. Убедитесь, что копирование завершено, прежде чем полагаться на него."]],
    availabilityHeading: "Текущий статус функций",
    deployment: "Прямая публикация в Tatik.space Pro пока недоступна. Нет работающего размещения Deploy в один клик или производственного URL от Tatik. Публикуйте сохранённые файлы через внешнего хостинг-провайдера.",
    collaboration: "На странице совместной работы используется фиксированный демонстрационный проект и сгенерированный ID пользователя. Она не связана с вашим реальным проектом или командой; не приглашайте там реальных участников и не передавайте производственные данные.",
    apiHeading: "Доступность API", api: "Публичная документация REST API для клиентов сейчас отсутствует. Внутренний API приложения не представлен здесь как поддерживаемая интеграция.",
    formatsHeading: "Поддерживаемые языки и форматы", formatsIntro: "Редактор распознаёт поддерживаемые типы файлов и подсвечивает синтаксис. Предпросмотр работает только с совместимым веб-контентом; распознавание файла не означает возможность его запуска или публикации.",
    formatGroups: ["Веб и данные", "Языки программирования", "Конфигурация и документация", "Изображения и локальные ресурсы"],
    marketplaceHeading: "Маркетплейс разработчиков", marketplaceIntro: "Разработчики могут отправлять цифровые материалы на проверку. Загруженные файлы остаются закрытыми до одобрения объявления и подтверждения покупки.",
    marketplaceRules: ["Создайте профиль продавца и примите условия; подключите Stripe и завершите проверку до запроса выплат.", "Создайте черновик объявления и загрузите файл. Текущий лимит — 2 МБ на файл; одобрять, отклонять и публиковать объявления может только персонал.", "Tatik удерживает комиссию 15% с продаж. Возвраты, споры и антифрод-проверки могут уменьшить доступный баланс или приостановить выплаты."],
    marketplaceWarning: "Не загружайте вредоносное ПО, учётные данные, персональные данные других лиц или материалы без необходимых прав. Для выплат нужна активная учётная запись Stripe Connect с включёнными платежами и выплатами.",
    schoolsHeading: "Школьная программа", schoolsIntro: "Одобренное учреждение может проводить курс длительностью 30 дней для максимум 30 учеников. Ожидающие или одобренные, но не использованные приглашения также учитываются; доступ заканчивается вместе с курсом.",
    schoolsRules: ["Авторизованный представитель отправляет сведения об учреждении и принимает условия программы.", "Учреждение должен одобрить администратор или сотрудник Tatik.", "Представитель создаёт и одобряет приглашение ученику. Токен временный, личный, непередаваемый и одноразовый.", "Ученик входит в систему и использует токен. Школа может отозвать доступ участника; действия записываются в журнал аудита."],
    schoolsWarning: "Сейчас приглашение создаёт токен, который школа должна передать по контролируемому каналу. Автоматическую отправку приглашений по электронной почте необходимо настроить отдельно до публичного использования.",
    seoTitle: "Документация Tatik.space Pro | Проверенное руководство", seoDescription: "Узнайте об редакторе, файлах, резервных копиях, маркетплейсе разработчиков и школьной программе Tatik.space Pro, включая текущие ограничения.",
  },
  zh: {
    title: "使用文档", home: "返回首页", introHeading: "简介",
    intro: "本指南介绍了在当前 Tatik.space Pro 界面中验证过的功能。功能可用性可能因账户以及文件或项目的打开方式而异。",
    editorHeading: "使用编辑器",
    editorSteps: ["登录后，从网站导航中打开编辑器。", "在“文件”菜单中创建或上传文件；如果浏览器支持，也可以打开本地文件夹。", "选择文件进行编辑。使用保存或可用的下载选项保留副本。", "对受支持的 Web 项目使用预览。预览并不支持运行所有语言和项目配置。"],
    featuresHeading: "主要功能",
    features: [["代码编辑器和预览", "在浏览器中编辑项目文件。预览支持部分 Web 内容，并非通用的构建或部署环境。"], ["AI 助手", "编辑器提供 AI 助手面板。回复取决于服务配置；不保证自动修复代码或提供键盘快捷键。"], ["文件和文件夹", "创建、上传文件和文件夹，并在浏览器允许时打开本地文件夹。本地文件与云端项目文件的保存位置不同。"], ["备份", "使用 Backup 创建和恢复项目快照。依赖备份前，请确认备份已完成。"]],
    availabilityHeading: "当前功能状态",
    deployment: "Tatik.space Pro 目前不支持直接发布项目。没有可用的一键 Deploy 流程，也没有由 Tatik 托管的生产环境网址。请通过外部托管服务发布已保存的文件。",
    collaboration: "协作页面目前使用固定演示项目和生成的演示用户 ID。它未连接到你的实际项目或团队；请勿用它邀请真实协作者或共享生产数据。",
    apiHeading: "API 可用性", api: "目前没有面向客户的公开 REST API 参考文档。此处不会将应用内部 API 描述为受支持的集成接口。",
    formatsHeading: "支持的语言和文件格式", formatsIntro: "编辑器可识别受支持的文件类型并突出显示语法。预览仅适用于兼容的 Web 内容；识别文件不代表可以运行或部署它。",
    formatGroups: ["Web 与数据", "编程语言", "配置与文档", "图像与本地资源"],
    marketplaceHeading: "开发者市场", marketplaceIntro: "开发者可以提交数字资源供审核。上传内容在商品通过审核且购买得到验证之前均保持私有。",
    marketplaceRules: ["创建卖家资料并接受卖家条款；申请付款前连接 Stripe 并完成验证。", "创建草稿商品并上传文件。目前每个文件上限为 2 MB；只有工作人员可以批准、拒绝或发布商品。", "Tatik 对销售记录 15% 的佣金。退款、争议和反欺诈审查可能减少或暂停可用余额。"],
    marketplaceWarning: "请勿上传恶意软件、凭据、他人的个人数据或你无权分发的材料。收款需要启用付款和提现功能的有效 Stripe Connect 账户。",
    schoolsHeading: "学校计划", schoolsIntro: "经批准的机构可开设为期 30 天、最多 30 名学生的课程。待处理或已批准但尚未兑换的邀请也计入名额；课程到期后学生访问权限结束。",
    schoolsRules: ["已登录的学校联系人提交机构信息并接受计划条款。", "机构须经 Tatik 管理员或工作人员批准。", "联系人为学生创建并批准邀请。令牌有时限、仅限本人使用、不可转让且只能使用一次。", "学生登录后兑换令牌。学校可撤销成员访问权限；相关操作会记录在审计日志中。"],
    schoolsWarning: "目前，邀请会生成令牌，由学校通过受控渠道交给学生。公开使用前须单独配置自动邀请邮件。",
    seoTitle: "Tatik.space Pro 文档 | 已验证功能指南", seoDescription: "了解 Tatik.space Pro 编辑器、文件、备份、开发者市场和学校计划，以及目前的功能限制。",
  },
  ja: {
    title: "ドキュメント", home: "ホームに戻る", introHeading: "はじめに",
    intro: "このガイドでは、現在の Tatik.space Pro の画面で確認できる機能を説明します。利用可否はアカウントやファイル・プロジェクトの開き方によって異なる場合があります。",
    editorHeading: "エディターの使い方",
    editorSteps: ["ログインし、サイトのナビゲーションからエディターを開きます。", "「ファイル」メニューでファイルを作成・アップロードするか、ブラウザーが対応している場合はローカルフォルダーを開きます。", "編集するファイルを選択します。「保存」または利用可能なダウンロード機能でコピーを保管してください。", "対応する Web プロジェクトではプレビューを利用できます。すべての言語や構成を実行できるわけではありません。"],
    featuresHeading: "主な機能",
    features: [["コードエディターとプレビュー", "ブラウザーでプロジェクトファイルを編集できます。プレビューは一部の Web コンテンツに対応しますが、汎用のビルド・デプロイ環境ではありません。"], ["AI アシスタント", "エディターで AI アシスタントパネルを利用できます。応答はサービス設定に依存し、自動修正やキーボードショートカットは保証されません。"], ["ファイルとフォルダー", "ファイルやフォルダーの作成・アップロード、ブラウザーが許可する場合のローカルフォルダー表示に対応します。ローカルファイルとクラウドプロジェクトでは保存先が異なります。"], ["バックアップ", "Backup でプロジェクトのスナップショットを作成・復元できます。利用する前にバックアップの完了を確認してください。"]],
    availabilityHeading: "現在の機能状況",
    deployment: "Tatik.space Pro では現在、プロジェクトの直接公開に対応していません。利用可能なワンクリック Deploy や Tatik の本番ホスティング URL はありません。保存したファイルは外部ホスティングサービスで公開してください。",
    collaboration: "コラボレーションページは固定のデモプロジェクトと生成されたデモユーザー ID を使用しています。実際のプロジェクトやチームには接続されていないため、実ユーザーの招待や本番データの共有には使用しないでください。",
    apiHeading: "API の提供状況", api: "現在、顧客向けの公開 REST API リファレンスはありません。アプリ内部 API は、サポート対象の連携機能としてここでは案内していません。",
    formatsHeading: "対応言語とファイル形式", formatsIntro: "エディターは対応するファイル形式を認識し、構文を強調表示します。プレビューは互換性のある Web コンテンツに限られ、ファイルを認識できても実行や公開が可能とは限りません。",
    formatGroups: ["Web とデータ", "プログラミング言語", "設定とドキュメント", "画像とローカルアセット"],
    marketplaceHeading: "開発者マーケットプレイス", marketplaceIntro: "開発者はデジタルリソースを審査に提出できます。出品が承認され購入が確認されるまで、アップロードしたファイルは非公開です。",
    marketplaceRules: ["販売者プロフィールを作成して規約に同意し、Stripe を接続して本人確認を完了してから出金を申請します。", "下書きの出品を作成してファイルをアップロードします。現在の上限は1ファイルあたり2 MBです。承認・却下・公開はスタッフのみが行えます。", "Tatik は売上の15%を手数料として記録します。返金、紛争、不正対策の保留により、利用可能残高が減少または停止することがあります。"],
    marketplaceWarning: "マルウェア、認証情報、第三者の個人データ、配布権のない素材をアップロードしないでください。出金には支払いと出金が有効な Stripe Connect アカウントが必要です。",
    schoolsHeading: "学校向けプログラム", schoolsIntro: "承認された機関は最大30名の学生を対象に、30日間のコースを実施できます。保留中または承認済みで未使用の招待も定員に含まれ、コース終了時に学生のアクセスも終了します。",
    schoolsRules: ["認証済みの学校担当者が機関情報を提出し、プログラム規約に同意します。", "機関は Tatik の管理者またはスタッフによる承認が必要です。", "担当者が学生への招待を作成・承認します。トークンは期限付き、本人専用、譲渡不可で、1回のみ使用できます。", "学生がログインしてトークンを利用します。学校はメンバーのアクセスを取り消せます。操作は監査ログに記録されます。"],
    schoolsWarning: "現在、招待ではトークンが生成され、学校が管理された経路で学生に届けます。一般公開前に招待メールの自動送信を別途設定する必要があります。",
    seoTitle: "Tatik.space Pro ドキュメント | 確認済み機能ガイド", seoDescription: "Tatik.space Pro のエディター、ファイル、バックアップ、開発者マーケットプレイス、学校向けプログラムと現在の制限を紹介します。",
  },
  ko: {
    title: "문서", home: "홈으로 돌아가기", introHeading: "소개",
    intro: "이 가이드는 현재 Tatik.space Pro 인터페이스에서 확인된 기능을 설명합니다. 계정 및 파일이나 프로젝트를 연 방식에 따라 이용 가능 여부가 달라질 수 있습니다.",
    editorHeading: "편집기 사용",
    editorSteps: ["로그인한 뒤 사이트 메뉴에서 편집기를 여세요.", "파일 메뉴에서 파일을 만들거나 업로드하고, 브라우저가 지원하면 로컬 폴더를 여세요.", "편집할 파일을 선택하세요. 저장 또는 제공되는 다운로드 옵션으로 작업 사본을 보관하세요.", "지원되는 웹 프로젝트에서 미리보기를 사용하세요. 모든 언어와 프로젝트 설정을 실행할 수 있는 것은 아닙니다."],
    featuresHeading: "주요 기능",
    features: [["코드 편집기 및 미리보기", "브라우저에서 프로젝트 파일을 편집합니다. 미리보기는 일부 웹 콘텐츠를 지원하며 일반적인 빌드 또는 배포 환경은 아닙니다."], ["AI 도우미", "편집기에서 AI 도우미 패널을 사용할 수 있습니다. 응답은 서비스 설정에 따라 달라지며 자동 코드 수정이나 키보드 단축키는 보장되지 않습니다."], ["파일 및 폴더", "파일과 폴더를 만들고 업로드하며 브라우저가 허용하면 로컬 폴더를 열 수 있습니다. 로컬 파일과 클라우드 프로젝트 파일의 저장 위치는 다릅니다."], ["백업", "Backup으로 프로젝트 스냅샷을 만들고 복원하세요. 백업에 의존하기 전에 완료되었는지 확인하세요."]],
    availabilityHeading: "현재 기능 상태",
    deployment: "현재 Tatik.space Pro에서는 프로젝트를 직접 게시할 수 없습니다. 작동하는 원클릭 Deploy 절차나 Tatik 프로덕션 호스팅 URL이 없습니다. 저장한 파일은 외부 호스팅 제공업체를 통해 게시하세요.",
    collaboration: "협업 페이지는 고정된 데모 프로젝트와 생성된 데모 사용자 ID를 사용합니다. 실제 프로젝트나 팀과 연결되어 있지 않으므로 실제 협업자를 초대하거나 프로덕션 데이터를 공유하지 마세요.",
    apiHeading: "API 제공 여부", api: "현재 고객용 공개 REST API 참조 문서는 제공되지 않습니다. 앱 내부 API는 지원되는 통합 인터페이스로 문서화되어 있지 않습니다.",
    formatsHeading: "지원 언어 및 파일 형식", formatsIntro: "편집기는 지원되는 파일 형식을 인식하고 구문을 강조 표시합니다. 미리보기는 호환되는 웹 콘텐츠에 한정되며, 파일 인식이 실행 또는 게시를 보장하지 않습니다.",
    formatGroups: ["웹 및 데이터", "프로그래밍 언어", "구성 및 문서", "이미지 및 로컬 자산"],
    marketplaceHeading: "개발자 마켓플레이스", marketplaceIntro: "개발자는 디지털 리소스를 검토 요청으로 제출할 수 있습니다. 등록이 승인되고 구매가 확인될 때까지 업로드한 파일은 비공개로 유지됩니다.",
    marketplaceRules: ["판매자 프로필을 만들고 약관에 동의하세요. 지급을 요청하기 전에 Stripe를 연결하고 인증을 완료하세요.", "초안 등록 항목을 만들고 파일을 업로드하세요. 현재 파일당 제한은 2MB이며, 승인·거절·게시 권한은 직원에게만 있습니다.", "Tatik은 판매액의 15%를 수수료로 기록합니다. 환불, 분쟁 및 사기 방지 보류로 사용 가능 잔액이 줄거나 중단될 수 있습니다."],
    marketplaceWarning: "악성코드, 자격 증명, 타인의 개인정보 또는 배포 권한이 없는 자료를 업로드하지 마세요. 지급을 받으려면 결제와 지급이 활성화된 Stripe Connect 계정이 필요합니다.",
    schoolsHeading: "학교 프로그램", schoolsIntro: "승인된 기관은 최대 30명의 학생을 대상으로 30일 과정에 접근할 수 있습니다. 대기 중이거나 승인됐지만 사용하지 않은 초대도 정원에 포함되며 과정 만료 시 학생 접근이 종료됩니다.",
    schoolsRules: ["인증된 학교 담당자가 기관 정보를 제출하고 프로그램 약관에 동의합니다.", "Tatik 관리자 또는 직원이 기관을 승인해야 합니다.", "담당자가 학생 초대를 만들고 승인합니다. 토큰은 기간 제한이 있고 개인 전용이며 양도할 수 없고 한 번만 사용할 수 있습니다.", "인증된 학생이 토큰을 사용합니다. 학교는 구성원의 접근 권한을 취소할 수 있으며 모든 작업은 감사 로그에 기록됩니다."],
    schoolsWarning: "현재 초대 토큰은 학교가 통제된 채널로 학생에게 전달해야 합니다. 공개 사용 전에 초대 이메일 자동 발송을 별도로 설정해야 합니다.",
    seoTitle: "Tatik.space Pro 문서 | 검증된 기능 안내", seoDescription: "Tatik.space Pro 편집기, 파일, 백업, 개발자 마켓플레이스와 학교 프로그램 및 현재 제한 사항을 알아보세요.",
  },
  ar: {
    title: "التوثيق", home: "العودة إلى الرئيسية", introHeading: "مقدمة",
    intro: "يوضح هذا الدليل الميزات التي تم التحقق منها في واجهة Tatik.space Pro الحالية. قد يختلف توفرها حسب الحساب وطريقة فتح الملف أو المشروع.",
    editorHeading: "استخدام المحرر",
    editorSteps: ["سجّل الدخول وافتح المحرر من قائمة الموقع.", "استخدم قائمة الملفات لإنشاء الملفات أو تحميلها، أو افتح مجلدًا محليًا إذا كان المتصفح يدعم ذلك.", "حدّد ملفًا لتحريره. استخدم الحفظ أو خيارات التنزيل المتاحة للاحتفاظ بنسخة.", "استخدم المعاينة لمشاريع الويب المدعومة. لا تشغّل جميع اللغات أو إعدادات المشاريع."],
    featuresHeading: "الميزات الرئيسية",
    features: [["محرر الشيفرة والمعاينة", "حرّر ملفات المشروع في المتصفح. تدعم المعاينة بعض محتوى الويب وليست بيئة عامة للبناء أو النشر."], ["مساعد الذكاء الاصطناعي", "تتوفر لوحة مساعد الذكاء الاصطناعي في المحرر. تعتمد الإجابات على إعداد الخدمة؛ ولا نضمن الإصلاح التلقائي للشيفرة أو اختصارات لوحة المفاتيح."], ["الملفات والمجلدات", "أنشئ الملفات والمجلدات وحمّلها وافتح المجلدات المحلية عندما يسمح المتصفح. تختلف وجهات حفظ الملفات المحلية عن ملفات المشروع السحابي."], ["النسخ الاحتياطية", "استخدم Backup لإنشاء لقطات للمشروع واستعادتها. تأكد من اكتمال النسخ قبل الاعتماد عليها."]],
    availabilityHeading: "حالة الميزات الحالية",
    deployment: "لا يتوفر النشر المباشر حاليًا في Tatik.space Pro. لا توجد عملية Deploy فعالة بنقرة واحدة ولا عنوان إنتاج مستضاف من Tatik. انشر الملفات المحفوظة عبر مزود استضافة خارجي.",
    collaboration: "تستخدم صفحة التعاون مشروعًا تجريبيًا ثابتًا ومعرّف مستخدم تجريبيًا مولّدًا. وهي غير متصلة بمشروعك أو فريقك الفعلي؛ لا تستخدمها لدعوة متعاونين حقيقيين أو مشاركة بيانات الإنتاج.",
    apiHeading: "توفر API", api: "لا تتوفر حاليًا وثائق عامة لواجهة REST API مخصصة للعملاء. ولا نوثق واجهة التطبيق الداخلية هنا على أنها تكامل مدعوم.",
    formatsHeading: "اللغات وتنسيقات الملفات المدعومة", formatsIntro: "يتعرف المحرر على أنواع الملفات المدعومة ويبرز الصياغة. تعمل المعاينة مع محتوى الويب المتوافق فقط؛ والتعرف على الملف لا يعني إمكانية تشغيله أو نشره.",
    formatGroups: ["الويب والبيانات", "لغات البرمجة", "الإعدادات والتوثيق", "الصور والموارد المحلية"],
    marketplaceHeading: "سوق المطورين", marketplaceIntro: "يمكن للمطورين تقديم موارد رقمية للمراجعة. تبقى الملفات المحمّلة خاصة حتى اعتماد العرض والتحقق من الشراء.",
    marketplaceRules: ["أنشئ ملف بائع واقبل الشروط؛ اربط Stripe وأكمل التحقق قبل طلب المدفوعات.", "أنشئ عرضًا مسودة وحمّل الملف. الحد الحالي 2 ميغابايت لكل ملف؛ ولا يملك صلاحية الاعتماد أو الرفض أو النشر إلا الموظفون.", "تسجل Tatik عمولة بنسبة 15% على المبيعات. قد تؤدي المبالغ المستردة والنزاعات ومراجعات مكافحة الاحتيال إلى خفض الرصيد المتاح أو تعليقه."],
    marketplaceWarning: "لا تحمّل برمجيات ضارة أو بيانات اعتماد أو بيانات شخصية للغير أو مواد لا تملك حقوق توزيعها. تتطلب المدفوعات حساب Stripe Connect نشطًا مع تفعيل المدفوعات والتحويلات.",
    schoolsHeading: "برنامج المدارس", schoolsIntro: "يمكن للمؤسسة المعتمدة تقديم دورة لمدة 30 يومًا لما يصل إلى 30 طالبًا. وتُحتسب الدعوات المعلقة أو المعتمدة غير المستخدمة ضمن الحد؛ وينتهي وصول الطلاب بانتهاء الدورة.",
    schoolsRules: ["يرسل ممثل المدرسة المسجل بيانات المؤسسة ويوافق على شروط البرنامج.", "يجب أن يوافق مسؤول أو موظف في Tatik على المؤسسة.", "ينشئ الممثل دعوة للطالب ويوافق عليها. الرمز مؤقت وشخصي وغير قابل للتحويل ويُستخدم مرة واحدة.", "يستخدم الطالب المسجل الرمز. يمكن للمدرسة إلغاء وصول أحد الأعضاء، وتُسجل العمليات في سجل التدقيق."],
    schoolsWarning: "تنشئ الدعوات حاليًا رمزًا تسلّمه المدرسة عبر قناة خاضعة للرقابة. يجب إعداد إرسال الدعوات تلقائيًا بالبريد بشكل منفصل قبل الاستخدام العام.",
    seoTitle: "توثيق Tatik.space Pro | دليل الميزات المؤكدة", seoDescription: "تعرّف على محرر Tatik.space Pro والملفات والنسخ الاحتياطية وسوق المطورين وبرنامج المدارس والقيود الحالية.",
  },
  hi: {
    title: "दस्तावेज़", home: "होम पर वापस जाएँ", introHeading: "परिचय",
    intro: "यह गाइड Tatik.space Pro के मौजूदा इंटरफ़ेस में सत्यापित सुविधाओं का वर्णन करती है। उपलब्धता खाते और फ़ाइल या प्रोजेक्ट खोलने के तरीके के अनुसार बदल सकती है।",
    editorHeading: "एडिटर का उपयोग",
    editorSteps: ["साइन इन करें और साइट नेविगेशन से एडिटर खोलें।", "फ़ाइल मेनू से फ़ाइल बनाएँ या अपलोड करें, अथवा ब्राउज़र समर्थन करे तो स्थानीय फ़ोल्डर खोलें।", "संपादन के लिए फ़ाइल चुनें। काम की प्रति रखने के लिए सेव या उपलब्ध डाउनलोड विकल्पों का उपयोग करें।", "समर्थित वेब प्रोजेक्ट के लिए प्रीव्यू उपयोग करें। यह हर भाषा या प्रोजेक्ट कॉन्फ़िगरेशन नहीं चला सकता।"],
    featuresHeading: "मुख्य सुविधाएँ",
    features: [["कोड एडिटर और प्रीव्यू", "ब्राउज़र में प्रोजेक्ट फ़ाइलें संपादित करें। प्रीव्यू कुछ वेब सामग्री के लिए है; यह सामान्य बिल्ड या डिप्लॉयमेंट वातावरण नहीं है।"], ["AI सहायक", "एडिटर में AI सहायक पैनल उपलब्ध है। जवाब सेवा कॉन्फ़िगरेशन पर निर्भर हैं; स्वतः कोड सुधार या कीबोर्ड शॉर्टकट की गारंटी नहीं है।"], ["फ़ाइलें और फ़ोल्डर", "फ़ाइलें और फ़ोल्डर बनाएँ या अपलोड करें तथा ब्राउज़र अनुमति दे तो स्थानीय फ़ोल्डर खोलें। स्थानीय और क्लाउड प्रोजेक्ट फ़ाइलें अलग-अलग स्थानों पर सहेजी जाती हैं।"], ["बैकअप", "प्रोजेक्ट स्नैपशॉट बनाने और पुनर्स्थापित करने के लिए Backup का उपयोग करें। उस पर निर्भर होने से पहले पुष्टि करें कि बैकअप पूरा हुआ है।"]],
    availabilityHeading: "मौजूदा सुविधा स्थिति",
    deployment: "Tatik.space Pro में अभी सीधे प्रकाशन की सुविधा उपलब्ध नहीं है। एक-क्लिक Deploy प्रक्रिया या Tatik होस्टेड प्रोडक्शन URL उपलब्ध नहीं है। सहेजी गई फ़ाइलों को बाहरी होस्टिंग प्रदाता से प्रकाशित करें।",
    collaboration: "Collaboration पेज एक निश्चित डेमो प्रोजेक्ट और बनाए गए डेमो उपयोगकर्ता ID का उपयोग करता है। यह आपके वास्तविक प्रोजेक्ट या टीम से जुड़ा नहीं है; वास्तविक सहयोगियों को आमंत्रित करने या प्रोडक्शन डेटा साझा करने के लिए इसका उपयोग न करें।",
    apiHeading: "API उपलब्धता", api: "ग्राहकों के लिए सार्वजनिक REST API संदर्भ अभी उपलब्ध नहीं है। ऐप के आंतरिक API को समर्थित एकीकरण के रूप में यहाँ दस्तावेज़ित नहीं किया गया है।",
    formatsHeading: "समर्थित भाषाएँ और फ़ाइल फ़ॉर्मेट", formatsIntro: "एडिटर समर्थित फ़ाइल प्रकार पहचानकर सिंटैक्स हाइलाइट करता है। प्रीव्यू केवल संगत वेब सामग्री के लिए है; फ़ाइल की पहचान का अर्थ यह नहीं कि उसे चलाया या प्रकाशित किया जा सकता है।",
    formatGroups: ["वेब और डेटा", "प्रोग्रामिंग भाषाएँ", "कॉन्फ़िगरेशन और दस्तावेज़", "छवियाँ और स्थानीय संसाधन"],
    marketplaceHeading: "डेवलपर मार्केटप्लेस", marketplaceIntro: "डेवलपर डिजिटल संसाधन समीक्षा के लिए जमा कर सकते हैं। लिस्टिंग स्वीकृत और खरीद सत्यापित होने तक अपलोड की गई फ़ाइलें निजी रहती हैं।",
    marketplaceRules: ["विक्रेता प्रोफ़ाइल बनाएँ और शर्तें स्वीकार करें; भुगतान माँगने से पहले Stripe जोड़ें और सत्यापन पूरा करें।", "ड्राफ़्ट लिस्टिंग बनाएँ और फ़ाइल अपलोड करें। वर्तमान सीमा प्रति फ़ाइल 2 MB है; केवल कर्मचारी लिस्टिंग स्वीकृत, अस्वीकार या प्रकाशित कर सकते हैं।", "Tatik बिक्री पर 15% कमीशन दर्ज करता है। रिफंड, विवाद और धोखाधड़ी-जाँच उपलब्ध शेष राशि घटा या रोक सकती हैं।"],
    marketplaceWarning: "मैलवेयर, क्रेडेंशियल, किसी अन्य व्यक्ति का निजी डेटा या ऐसा सामग्री अपलोड न करें जिसके वितरण अधिकार आपके पास नहीं हैं। भुगतान के लिए सक्रिय Stripe Connect खाते में भुगतान और निकासी सक्षम होना आवश्यक है।",
    schoolsHeading: "स्कूल कार्यक्रम", schoolsIntro: "स्वीकृत संस्थान अधिकतम 30 विद्यार्थियों के लिए 30-दिन का कोर्स चला सकता है। लंबित या स्वीकृत लेकिन उपयोग न किए गए आमंत्रण भी सीमा में गिने जाते हैं; कोर्स समाप्त होने पर विद्यार्थियों की पहुँच समाप्त हो जाती है।",
    schoolsRules: ["प्रमाणित स्कूल संपर्क संस्था का विवरण भेजता है और कार्यक्रम की शर्तें स्वीकार करता है।", "Tatik व्यवस्थापक या कर्मचारी को संस्था स्वीकृत करनी होगी।", "संपर्क व्यक्ति विद्यार्थी के लिए आमंत्रण बनाकर स्वीकृत करता है। टोकन अस्थायी, व्यक्तिगत, गैर-हस्तांतरणीय और एक बार उपयोग योग्य है।", "प्रमाणित विद्यार्थी टोकन का उपयोग करता है। स्कूल सदस्य की पहुँच रद्द कर सकता है; कार्रवाइयाँ ऑडिट लॉग में दर्ज होती हैं।"],
    schoolsWarning: "अभी आमंत्रण एक टोकन बनाते हैं जिसे स्कूल नियंत्रित माध्यम से विद्यार्थी तक पहुँचाता है। सार्वजनिक उपयोग से पहले स्वचालित आमंत्रण ईमेल अलग से कॉन्फ़िगर करना होगा।",
    seoTitle: "Tatik.space Pro दस्तावेज़ | सत्यापित सुविधाओं की गाइड", seoDescription: "Tatik.space Pro एडिटर, फ़ाइलों, बैकअप, डेवलपर मार्केटप्लेस, स्कूल कार्यक्रम और उनकी मौजूदा सीमाओं के बारे में जानें।",
  },
  pl: {
    title: "Dokumentacja", home: "Wróć na stronę główną", introHeading: "Wprowadzenie",
    intro: "Ten przewodnik opisuje funkcje sprawdzone w obecnym interfejsie Tatik.space Pro. Dostępność może zależeć od konta oraz sposobu otwarcia pliku lub projektu.",
    editorHeading: "Korzystanie z edytora",
    editorSteps: ["Zaloguj się i otwórz Edytor z nawigacji strony.", "W menu Plik utwórz lub prześlij pliki albo otwórz folder lokalny, jeśli obsługuje to przeglądarka.", "Wybierz plik do edycji. Użyj opcji Zapisz lub dostępnych opcji pobierania, aby zachować kopię.", "Korzystaj z podglądu w obsługiwanych projektach internetowych. Nie uruchamia on wszystkich języków ani konfiguracji."],
    featuresHeading: "Główne funkcje",
    features: [["Edytor kodu i podgląd", "Edytuj pliki projektu w przeglądarce. Podgląd obsługuje wybrane treści internetowe; nie jest ogólnym środowiskiem kompilacji ani wdrażania."], ["Asystent AI", "W edytorze dostępny jest panel asystenta AI. Odpowiedzi zależą od konfiguracji usługi; automatyczne poprawki kodu i skróty klawiszowe nie są gwarantowane."], ["Pliki i foldery", "Twórz i przesyłaj pliki oraz foldery i otwieraj foldery lokalne, jeśli pozwala na to przeglądarka. Pliki lokalne i pliki projektu w chmurze mają różne miejsca zapisu."], ["Kopie zapasowe", "Użyj Backup, aby tworzyć i przywracać migawki projektu. Przed poleganiem na kopii sprawdź, czy tworzenie zakończyło się pomyślnie."]],
    availabilityHeading: "Aktualny stan funkcji",
    deployment: "Bezpośrednie publikowanie nie jest obecnie dostępne w Tatik.space Pro. Nie ma działającego wdrożenia jednym kliknięciem ani produkcyjnego adresu hostowanego przez Tatik. Opublikuj zapisane pliki u zewnętrznego dostawcy hostingu.",
    collaboration: "Strona Współpraca korzysta obecnie ze stałego projektu demonstracyjnego i wygenerowanego demonstracyjnego identyfikatora użytkownika. Nie łączy się z Twoim prawdziwym projektem ani zespołem; nie zapraszaj tam rzeczywistych współpracowników ani nie udostępniaj danych produkcyjnych.",
    apiHeading: "Dostępność API", api: "Publiczna dokumentacja REST API dla klientów nie jest obecnie dostępna. Wewnętrzne API aplikacji nie jest tu opisane jako obsługiwana integracja.",
    formatsHeading: "Obsługiwane języki i formaty plików", formatsIntro: "Edytor rozpoznaje obsługiwane typy plików i podświetla składnię. Podgląd działa tylko dla zgodnych treści internetowych; rozpoznanie pliku nie oznacza możliwości jego uruchomienia lub publikacji.",
    formatGroups: ["Internet i dane", "Języki programowania", "Konfiguracja i dokumentacja", "Obrazy i zasoby lokalne"],
    marketplaceHeading: "Marketplace dla deweloperów", marketplaceIntro: "Deweloperzy mogą zgłaszać zasoby cyfrowe do sprawdzenia. Przesłane pliki pozostają prywatne do czasu zatwierdzenia oferty i zweryfikowania zakupu.",
    marketplaceRules: ["Utwórz profil sprzedawcy i zaakceptuj warunki; połącz Stripe i zakończ weryfikację przed złożeniem wniosku o wypłatę.", "Utwórz szkic oferty i prześlij plik. Obecny limit wynosi 2 MB na plik; tylko personel może zatwierdzać, odrzucać lub publikować oferty.", "Tatik nalicza 15% prowizji od sprzedaży. Zwroty, spory i kontrole antyfraudowe mogą zmniejszyć lub zawiesić dostępne saldo."],
    marketplaceWarning: "Nie przesyłaj złośliwego oprogramowania, danych logowania, danych osobowych innych osób ani materiałów, do których dystrybucji nie masz praw. Wypłaty wymagają aktywnego konta Stripe Connect z włączonymi płatnościami i wypłatami.",
    schoolsHeading: "Program szkolny", schoolsIntro: "Zatwierdzona placówka może prowadzić 30-dniowy kurs dla maksymalnie 30 uczniów. Oczekujące lub zatwierdzone, ale niewykorzystane zaproszenia również wliczają się do limitu; dostęp kończy się z końcem kursu.",
    schoolsRules: ["Zalogowany przedstawiciel szkoły przesyła dane placówki i akceptuje warunki programu.", "Placówka musi uzyskać akceptację administratora lub pracownika Tatik.", "Przedstawiciel tworzy i zatwierdza zaproszenie dla ucznia. Token jest tymczasowy, osobisty, nieprzenoszalny i jednorazowy.", "Zalogowany uczeń realizuje token. Szkoła może odebrać dostęp członkowi; działania są zapisywane w dzienniku audytu."],
    schoolsWarning: "Zaproszenia generują obecnie token, który szkoła przekazuje wybranym kanałem. Przed publicznym użyciem trzeba osobno skonfigurować automatyczną wysyłkę e-maili z zaproszeniami.",
    seoTitle: "Dokumentacja Tatik.space Pro | Przewodnik po sprawdzonych funkcjach", seoDescription: "Poznaj edytor, pliki, kopie zapasowe, marketplace deweloperski i program szkolny Tatik.space Pro oraz ich aktualne ograniczenia.",
  },
  nl: {
    title: "Documentatie", home: "Terug naar home", introHeading: "Inleiding",
    intro: "Deze handleiding beschrijft functies die zijn gecontroleerd in de huidige interface van Tatik.space Pro. Beschikbaarheid kan verschillen per account en per manier waarop een bestand of project is geopend.",
    editorHeading: "De editor gebruiken",
    editorSteps: ["Log in en open Editor via de navigatie van de site.", "Maak of upload bestanden via het menu Bestand, of open een lokale map als je browser dit ondersteunt.", "Selecteer een bestand om het te bewerken. Gebruik Opslaan of de beschikbare downloadopties om een kopie te bewaren.", "Gebruik Voorbeeld voor ondersteunde webprojecten. Niet elke taal of projectconfiguratie kan worden uitgevoerd."],
    featuresHeading: "Belangrijkste functies",
    features: [["Code-editor en voorbeeld", "Bewerk projectbestanden in de browser. De voorbeeldweergave ondersteunt bepaalde webinhoud en is geen algemene build- of implementatieomgeving."], ["AI-assistent", "De editor bevat een AI-assistentpaneel. Antwoorden zijn afhankelijk van de serviceconfiguratie; automatische codecorrecties en sneltoetsen zijn niet gegarandeerd."], ["Bestanden en mappen", "Maak en upload bestanden en mappen en open lokale mappen als je browser dit toestaat. Lokale bestanden en cloudprojectbestanden worden op verschillende locaties opgeslagen."], ["Back-ups", "Gebruik Backup om projectsnapshots te maken en te herstellen. Controleer of een back-up is voltooid voordat je erop vertrouwt."]],
    availabilityHeading: "Huidige functiestatus",
    deployment: "Direct publiceren is momenteel niet beschikbaar in Tatik.space Pro. Er is geen werkende Deploy-functie met één klik en geen productie-URL die door Tatik wordt gehost. Publiceer opgeslagen bestanden via een externe hostingprovider.",
    collaboration: "De samenwerkingspagina gebruikt momenteel een vast demoproject en een gegenereerde demo-gebruikers-ID. Deze is niet gekoppeld aan je echte project of team; nodig er geen echte medewerkers uit en deel geen productiegegevens.",
    apiHeading: "API-beschikbaarheid", api: "Er is momenteel geen openbare REST API-documentatie voor klanten. De interne API van de app wordt hier niet beschreven als een ondersteunde integratie.",
    formatsHeading: "Ondersteunde talen en bestandsindelingen", formatsIntro: "De editor herkent ondersteunde bestandstypen en markeert de syntaxis. Voorbeeldweergave werkt alleen voor compatibele webinhoud; herkenning betekent niet dat een bestand kan worden uitgevoerd of gepubliceerd.",
    formatGroups: ["Web en gegevens", "Programmeertalen", "Configuratie en documentatie", "Afbeeldingen en lokale assets"],
    marketplaceHeading: "Marktplaats voor ontwikkelaars", marketplaceIntro: "Ontwikkelaars kunnen digitale bronnen ter beoordeling indienen. Geüploade bestanden blijven privé totdat de aanbieding is goedgekeurd en de aankoop is geverifieerd.",
    marketplaceRules: ["Maak een verkopersprofiel en accepteer de voorwaarden; koppel Stripe en voltooi de verificatie voordat je een uitbetaling aanvraagt.", "Maak een conceptaanbieding en upload het bestand. De huidige limiet is 2 MB per bestand; alleen medewerkers kunnen aanbiedingen goedkeuren, afwijzen of publiceren.", "Tatik registreert 15% commissie op verkopen. Terugbetalingen, geschillen en fraudebeoordelingen kunnen het beschikbare saldo verlagen of blokkeren."],
    marketplaceWarning: "Upload geen malware, inloggegevens, persoonsgegevens van anderen of materiaal waarvoor je geen distributierechten hebt. Uitbetalingen vereisen een actief Stripe Connect-account met ingeschakelde betalingen en uitbetalingen.",
    schoolsHeading: "Scholenprogramma", schoolsIntro: "Een goedgekeurde instelling kan een cursus van 30 dagen aanbieden aan maximaal 30 studenten. Openstaande of goedgekeurde maar niet ingewisselde uitnodigingen tellen ook mee; toegang eindigt wanneer de cursus afloopt.",
    schoolsRules: ["Een ingelogde contactpersoon dient de instellingsgegevens in en accepteert de programmavoorwaarden.", "Een Tatik-beheerder of medewerker moet de instelling goedkeuren.", "De contactpersoon maakt en keurt een uitnodiging voor een student goed. De token is tijdelijk, persoonlijk, niet overdraagbaar en eenmalig.", "De ingelogde student wisselt de token in. De school kan de toegang van een lid intrekken; acties worden vastgelegd in het auditlogboek."],
    schoolsWarning: "Uitnodigingen leveren momenteel een token op dat de school via een gecontroleerd kanaal moet versturen. Automatische e-mails met uitnodigingen moeten vóór openbaar gebruik apart worden ingesteld.",
    seoTitle: "Documentatie van Tatik.space Pro | Gids met geverifieerde functies", seoDescription: "Lees over de editor, bestanden, back-ups, ontwikkelaarsmarktplaats en het scholenprogramma van Tatik.space Pro, inclusief de huidige beperkingen.",
  },
  tr: {
    title: "Belgeler", home: "Ana sayfaya dön", introHeading: "Giriş",
    intro: "Bu kılavuz, Tatik.space Pro'nun mevcut arayüzünde doğrulanan özellikleri açıklar. Kullanılabilirlik hesaba ve dosya ya da projenin açılma biçimine göre değişebilir.",
    editorHeading: "Düzenleyiciyi kullanma",
    editorSteps: ["Oturum açın ve site menüsünden Düzenleyici'yi açın.", "Dosya menüsünden dosya oluşturun veya yükleyin; tarayıcınız destekliyorsa yerel bir klasör açın.", "Düzenlemek için bir dosya seçin. Çalışmanızın kopyasını saklamak için Kaydet'i veya indirme seçeneklerini kullanın.", "Desteklenen web projelerinde Önizleme'yi kullanın. Her dil veya proje yapılandırması çalıştırılamaz."],
    featuresHeading: "Temel özellikler",
    features: [["Kod düzenleyici ve önizleme", "Proje dosyalarını tarayıcıda düzenleyin. Önizleme belirli web içeriklerini destekler; genel amaçlı bir derleme veya dağıtım ortamı değildir."], ["Yapay zekâ asistanı", "Düzenleyicide yapay zekâ asistan paneli bulunur. Yanıtlar hizmet yapılandırmasına bağlıdır; otomatik kod düzeltmeleri ve klavye kısayolları garanti edilmez."], ["Dosyalar ve klasörler", "Dosya ve klasör oluşturup yükleyin, tarayıcı izin veriyorsa yerel klasörleri açın. Yerel dosyalar ve bulut projesi dosyaları farklı konumlara kaydedilir."], ["Yedekler", "Proje anlık görüntülerini oluşturmak ve geri yüklemek için Backup'ı kullanın. Güvenmeden önce yedeklemenin tamamlandığını doğrulayın."]],
    availabilityHeading: "Mevcut özellik durumu",
    deployment: "Tatik.space Pro'da doğrudan yayınlama şu anda kullanılamıyor. Çalışan tek tıklamalı Deploy akışı veya Tatik üretim barındırma adresi yoktur. Kaydedilen dosyaları harici bir barındırma sağlayıcısıyla yayınlayın.",
    collaboration: "İş birliği sayfası sabit bir demo projesi ve oluşturulmuş demo kullanıcı kimliği kullanır. Gerçek projenize veya ekibinize bağlı değildir; gerçek iş arkadaşlarını davet etmek veya üretim verisi paylaşmak için kullanmayın.",
    apiHeading: "API kullanılabilirliği", api: "Müşterilere yönelik herkese açık REST API belgesi şu anda yoktur. Uygulamanın dahili API'si desteklenen entegrasyon olarak burada belgelenmemiştir.",
    formatsHeading: "Desteklenen diller ve dosya biçimleri", formatsIntro: "Düzenleyici desteklenen dosya türlerini tanır ve söz dizimini vurgular. Önizleme yalnızca uyumlu web içeriklerinde çalışır; dosyanın tanınması çalıştırılabileceği veya yayınlanabileceği anlamına gelmez.",
    formatGroups: ["Web ve veri", "Programlama dilleri", "Yapılandırma ve belgeler", "Görseller ve yerel varlıklar"],
    marketplaceHeading: "Geliştirici pazaryeri", marketplaceIntro: "Geliştiriciler dijital kaynakları incelemeye sunabilir. Yüklenen içerik, liste onaylanıp satın alma doğrulanana kadar gizli kalır.",
    marketplaceRules: ["Satıcı profili oluşturup koşulları kabul edin; ödeme talep etmeden önce Stripe'ı bağlayıp doğrulamayı tamamlayın.", "Taslak liste oluşturup dosyayı yükleyin. Dosya başına mevcut sınır 2 MB'tır; listeyi yalnızca personel onaylayabilir, reddedebilir veya yayınlayabilir.", "Tatik satışlardan %15 komisyon kaydeder. İadeler, anlaşmazlıklar ve dolandırıcılık kontrolleri kullanılabilir bakiyeyi azaltabilir veya durdurabilir."],
    marketplaceWarning: "Kötü amaçlı yazılım, kimlik bilgileri, başkasının kişisel verileri veya dağıtım hakkınız olmayan materyalleri yüklemeyin. Ödeme için ödemeler ve transferler etkin bir Stripe Connect hesabı gerekir.",
    schoolsHeading: "Okul programı", schoolsIntro: "Onaylanan kurum, en fazla 30 öğrenci için 30 günlük kurs düzenleyebilir. Bekleyen veya onaylanmış ancak kullanılmamış davetler de sınıra dahildir; kurs bitince öğrenci erişimi sona erer.",
    schoolsRules: ["Oturum açmış okul yetkilisi kurum bilgilerini gönderir ve program koşullarını kabul eder.", "Kurumun bir Tatik yöneticisi veya personeli tarafından onaylanması gerekir.", "Yetkili, öğrenci için davet oluşturup onaylar. Token süreli, kişisel, devredilemez ve tek kullanımlıktır.", "Oturum açmış öğrenci tokenı kullanır. Okul bir üyenin erişimini iptal edebilir; işlemler denetim kaydına alınır."],
    schoolsWarning: "Davetler şu anda okulun kontrollü bir kanalla öğrenciye iletmesi gereken bir token oluşturur. Herkese açık kullanımdan önce otomatik davet e-postaları ayrıca yapılandırılmalıdır.",
    seoTitle: "Tatik.space Pro belgeleri | Doğrulanmış özellikler kılavuzu", seoDescription: "Tatik.space Pro düzenleyicisi, dosyaları, yedekleri, geliştirici pazaryerini ve okul programını mevcut kısıtlamalarıyla öğrenin.",
  },
  sv: {
    title: "Dokumentation", home: "Tillbaka till startsidan", introHeading: "Introduktion",
    intro: "Den här guiden beskriver funktioner som har verifierats i det aktuella Tatik.space Pro-gränssnittet. Tillgängligheten kan variera beroende på konto och hur en fil eller ett projekt öppnades.",
    editorHeading: "Använda redigeraren",
    editorSteps: ["Logga in och öppna Redigeraren via webbplatsens navigering.", "Skapa eller ladda upp filer via menyn Arkiv, eller öppna en lokal mapp om webbläsaren stöder det.", "Välj en fil för redigering. Använd Spara eller tillgängliga nedladdningsalternativ för att behålla en kopia.", "Använd Förhandsgranskning för projekt som stöds. Den kör inte alla språk eller projektkonfigurationer."],
    featuresHeading: "Huvudfunktioner",
    features: [["Kodredigerare och förhandsgranskning", "Redigera projektfiler i webbläsaren. Förhandsgranskningen stöder visst webbinnehåll och är inte en allmän bygg- eller distributionsmiljö."], ["AI-assistent", "En AI-assistentpanel finns i redigeraren. Svaren beror på tjänstens konfiguration; automatiska kodfixar och kortkommandon garanteras inte."], ["Filer och mappar", "Skapa och ladda upp filer och mappar och öppna lokala mappar när webbläsaren tillåter det. Lokala filer och molnprojektfiler sparas på olika platser."], ["Säkerhetskopior", "Använd Backup för att skapa och återställa projektsnapshots. Kontrollera att en säkerhetskopia är klar innan du förlitar dig på den."]],
    availabilityHeading: "Aktuell funktionsstatus",
    deployment: "Direktpublicering är inte tillgänglig i Tatik.space Pro just nu. Det finns inget fungerande Deploy-flöde med ett klick och ingen produktionsadress som hostas av Tatik. Publicera sparade filer via en extern webbhotellstjänst.",
    collaboration: "Samarbetssidan använder ett fast demoprojekt och ett genererat demoanvändar-ID. Den är inte ansluten till ditt riktiga projekt eller team; bjud inte in riktiga samarbetspartner eller dela produktionsdata där.",
    apiHeading: "API-tillgänglighet", api: "Det finns för närvarande ingen offentlig REST API-referens för kunder. Appens interna API dokumenteras inte här som en integration som stöds.",
    formatsHeading: "Språk och filformat som stöds", formatsIntro: "Redigeraren känner igen filtyper som stöds och markerar syntax. Förhandsgranskningen fungerar bara med kompatibelt webbinnehåll; igenkänning innebär inte att filen kan köras eller publiceras.",
    formatGroups: ["Webb och data", "Programmeringsspråk", "Konfiguration och dokumentation", "Bilder och lokala resurser"],
    marketplaceHeading: "Utvecklarmarknadsplats", marketplaceIntro: "Utvecklare kan skicka in digitala resurser för granskning. Uppladdade filer förblir privata tills annonsen har godkänts och köpet verifierats.",
    marketplaceRules: ["Skapa en säljarprofil och godkänn villkoren; anslut Stripe och slutför verifieringen innan du begär utbetalning.", "Skapa ett utkast till annons och ladda upp filen. Den aktuella gränsen är 2 MB per fil; endast personal kan godkänna, avslå eller publicera annonser.", "Tatik registrerar 15 % provision på försäljning. Återbetalningar, tvister och bedrägerikontroller kan minska eller pausa det tillgängliga saldot."],
    marketplaceWarning: "Ladda inte upp skadlig kod, inloggningsuppgifter, någon annans personuppgifter eller material som du saknar distributionsrätt till. Utbetalningar kräver ett aktivt Stripe Connect-konto med betalningar och utbetalningar aktiverade.",
    schoolsHeading: "Skolprogram", schoolsIntro: "En godkänd institution kan hålla en kurs i 30 dagar för högst 30 elever. Väntande eller godkända men outnyttjade inbjudningar räknas också in; elevåtkomsten upphör när kursen löper ut.",
    schoolsRules: ["En inloggad skolkontakt skickar in institutionsuppgifterna och godkänner programmets villkor.", "En Tatik-administratör eller medarbetare måste godkänna institutionen.", "Kontakten skapar och godkänner en inbjudan till eleven. Tokenen är tillfällig, personlig, inte överförbar och kan bara användas en gång.", "Den inloggade eleven löser in tokenen. Skolan kan återkalla en medlems åtkomst; åtgärderna registreras i granskningsloggen."],
    schoolsWarning: "Inbjudningar skapar för närvarande en token som skolan måste lämna till mottagaren via en kontrollerad kanal. Automatisk e-postinbjudan måste konfigureras separat före offentlig användning.",
    seoTitle: "Dokumentation för Tatik.space Pro | Verifierad produktguide", seoDescription: "Läs om redigeraren, filer, säkerhetskopior, utvecklarmarknadsplatsen och skolprogrammet i Tatik.space Pro, inklusive aktuella begränsningar.",
  },
  da: {
    title: "Dokumentation", home: "Tilbage til forsiden", introHeading: "Introduktion",
    intro: "Denne vejledning beskriver funktioner, der er verificeret i den aktuelle Tatik.space Pro-grænseflade. Tilgængeligheden kan variere efter konto og måden, en fil eller et projekt blev åbnet på.",
    editorHeading: "Brug af editoren",
    editorSteps: ["Log ind, og åbn Editor fra webstedets navigation.", "Opret eller upload filer via menuen Filer, eller åbn en lokal mappe, hvis browseren understøtter det.", "Vælg en fil, der skal redigeres. Brug Gem eller de tilgængelige downloadmuligheder for at beholde en kopi.", "Brug Forhåndsvisning til understøttede webprojekter. Den kan ikke køre alle sprog eller projektkonfigurationer."],
    featuresHeading: "Vigtige funktioner",
    features: [["Kodeeditor og forhåndsvisning", "Rediger projektfiler i browseren. Forhåndsvisning understøtter udvalgt webindhold og er ikke et generelt build- eller publiceringsmiljø."], ["AI-assistent", "Editoren har et AI-assistentpanel. Svar afhænger af tjenestens konfiguration; automatiske kodeændringer og tastaturgenveje garanteres ikke."], ["Filer og mapper", "Opret og upload filer og mapper, og åbn lokale mapper, hvis browseren tillader det. Lokale filer og cloudprojektfiler gemmes forskellige steder."], ["Sikkerhedskopier", "Brug Backup til at oprette og gendanne projektsnapshots. Kontrollér, at sikkerhedskopien er fuldført, før du stoler på den."]],
    availabilityHeading: "Aktuel funktionsstatus",
    deployment: "Direkte publicering er ikke tilgængelig i Tatik.space Pro i øjeblikket. Der er ikke et fungerende Deploy-flow med ét klik eller en produktionsadresse hostet af Tatik. Publicér gemte filer via en ekstern hostingudbyder.",
    collaboration: "Samarbejdssiden bruger et fast demoprojekt og et genereret demobruger-id. Den er ikke forbundet med dit rigtige projekt eller team; brug den ikke til at invitere rigtige samarbejdspartnere eller dele produktionsdata.",
    apiHeading: "API-tilgængelighed", api: "Der findes i øjeblikket ingen offentlig REST API-reference til kunder. Appens interne API dokumenteres ikke her som en understøttet integration.",
    formatsHeading: "Understøttede sprog og filformater", formatsIntro: "Editoren genkender understøttede filtyper og fremhæver syntaks. Forhåndsvisning virker kun med kompatibelt webindhold; genkendelse betyder ikke, at filen kan køres eller publiceres.",
    formatGroups: ["Web og data", "Programmeringssprog", "Konfiguration og dokumentation", "Billeder og lokale ressourcer"],
    marketplaceHeading: "Udviklermarkedsplads", marketplaceIntro: "Udviklere kan indsende digitale ressourcer til gennemgang. Uploadede filer forbliver private, indtil opslaget er godkendt og købet verificeret.",
    marketplaceRules: ["Opret en sælgerprofil, og acceptér vilkårene; tilslut Stripe, og gennemfør verificeringen, før du anmoder om udbetaling.", "Opret et udkast til et opslag, og upload filen. Den aktuelle grænse er 2 MB pr. fil; kun medarbejdere kan godkende, afvise eller udgive opslag.", "Tatik registrerer 15 % provision af salg. Refunderinger, tvister og kontrol mod svindel kan reducere eller sætte den tilgængelige saldo på pause."],
    marketplaceWarning: "Upload ikke malware, legitimationsoplysninger, andres persondata eller materiale, du ikke har rettigheder til at distribuere. Udbetaling kræver en aktiv Stripe Connect-konto med betalinger og udbetalinger aktiveret.",
    schoolsHeading: "Skoleprogram", schoolsIntro: "En godkendt institution kan afholde et kursus på 30 dage for højst 30 elever. Afventende eller godkendte, men ubrugte invitationer tæller også med; elevadgangen slutter, når kurset udløber.",
    schoolsRules: ["En logget skolekontakt indsender institutionsoplysninger og accepterer programmets vilkår.", "En Tatik-administrator eller medarbejder skal godkende institutionen.", "Kontakten opretter og godkender en invitation til eleven. Tokenet er midlertidigt, personligt, ikke-overdrageligt og kan kun bruges én gang.", "Den loggede elev indløser tokenet. Skolen kan tilbagekalde et medlems adgang; handlinger registreres i revisionsloggen."],
    schoolsWarning: "Invitationer opretter aktuelt et token, som skolen skal videregive via en kontrolleret kanal. Automatisk e-mail med invitationer skal konfigureres separat før offentlig brug.",
    seoTitle: "Tatik.space Pro-dokumentation | Verificeret produktvejledning", seoDescription: "Læs om editor, filer, sikkerhedskopier, udviklermarkedsplads og skoleprogram i Tatik.space Pro samt deres aktuelle begrænsninger.",
  },
  no: {
    title: "Dokumentasjon", home: "Tilbake til forsiden", introHeading: "Introduksjon",
    intro: "Denne veiledningen beskriver funksjoner som er bekreftet i det nåværende Tatik.space Pro-grensesnittet. Tilgjengeligheten kan variere etter konto og hvordan en fil eller et prosjekt ble åpnet.",
    editorHeading: "Bruke editoren",
    editorSteps: ["Logg inn og åpne Editor fra navigasjonen på nettstedet.", "Opprett eller last opp filer fra Fil-menyen, eller åpne en lokal mappe hvis nettleseren støtter det.", "Velg en fil for redigering. Bruk Lagre eller tilgjengelige nedlastingsalternativer for å beholde en kopi.", "Bruk Forhåndsvisning for støttede webprosjekter. Den kjører ikke alle språk eller prosjektkonfigurasjoner."],
    featuresHeading: "Hovedfunksjoner",
    features: [["Kodeeditor og forhåndsvisning", "Rediger prosjektfiler i nettleseren. Forhåndsvisningen støtter utvalgt webinnhold og er ikke et generelt bygge- eller distribusjonsmiljø."], ["AI-assistent", "En AI-assistent er tilgjengelig i editoren. Svar avhenger av tjenestekonfigurasjonen; automatiske kodefikser og tastatursnarveier er ikke garantert."], ["Filer og mapper", "Opprett og last opp filer og mapper, og åpne lokale mapper når nettleseren tillater det. Lokale filer og skyprosjektfiler lagres på ulike steder."], ["Sikkerhetskopier", "Bruk Backup til å opprette og gjenopprette prosjektsnapshots. Kontroller at en sikkerhetskopi er fullført før du stoler på den."]],
    availabilityHeading: "Gjeldende funksjonsstatus",
    deployment: "Direkte publisering er ikke tilgjengelig i Tatik.space Pro nå. Det finnes ingen fungerende Deploy-flyt med ett klikk eller produksjonsadresse hos Tatik. Publiser lagrede filer via en ekstern hostingleverandør.",
    collaboration: "Samarbeidssiden bruker et fast demoprosjekt og en generert demo-bruker-ID. Den er ikke koblet til ditt faktiske prosjekt eller team; ikke inviter virkelige samarbeidspartnere eller del produksjonsdata der.",
    apiHeading: "API-tilgjengelighet", api: "Det finnes for øyeblikket ingen offentlig REST API-referanse for kunder. Appens interne API dokumenteres ikke her som en støttet integrasjon.",
    formatsHeading: "Språk og filformater som støttes", formatsIntro: "Editoren gjenkjenner støttede filtyper og markerer syntaks. Forhåndsvisning fungerer bare med kompatibelt webinnhold; gjenkjenning betyr ikke at filen kan kjøres eller publiseres.",
    formatGroups: ["Web og data", "Programmeringsspråk", "Konfigurasjon og dokumentasjon", "Bilder og lokale ressurser"],
    marketplaceHeading: "Markedsplass for utviklere", marketplaceIntro: "Utviklere kan sende inn digitale ressurser til vurdering. Opplastede filer forblir private til oppføringen er godkjent og kjøpet bekreftet.",
    marketplaceRules: ["Opprett en selgerprofil og godta vilkårene; koble til Stripe og fullfør verifiseringen før du ber om utbetaling.", "Opprett et utkast til oppføring og last opp filen. Gjeldende grense er 2 MB per fil; bare ansatte kan godkjenne, avslå eller publisere oppføringer.", "Tatik registrerer 15 % provisjon på salg. Refusjoner, tvister og svindelkontroller kan redusere eller stanse tilgjengelig saldo."],
    marketplaceWarning: "Ikke last opp skadelig programvare, påloggingsinformasjon, andres personopplysninger eller materiale du ikke har distribusjonsrett til. Utbetalinger krever en aktiv Stripe Connect-konto med betalinger og utbetalinger aktivert.",
    schoolsHeading: "Skoleprogram", schoolsIntro: "En godkjent institusjon kan holde et 30-dagers kurs for opptil 30 elever. Ventende eller godkjente, men ikke innløste invitasjoner teller også med; elevtilgangen avsluttes når kurset utløper.",
    schoolsRules: ["En innlogget skolekontakt sender inn institusjonsopplysninger og godtar programvilkårene.", "Institusjonen må godkjennes av en Tatik-administrator eller medarbeider.", "Kontakten oppretter og godkjenner en invitasjon til eleven. Tokenet er midlertidig, personlig, ikke-overførbart og kan brukes én gang.", "Den innloggede eleven løser inn tokenet. Skolen kan tilbakekalle tilgangen til et medlem; handlinger registreres i revisjonsloggen."],
    schoolsWarning: "Invitasjoner oppretter for øyeblikket et token som skolen må levere via en kontrollert kanal. Automatisk e-postinvitasjon må konfigureres separat før offentlig bruk.",
    seoTitle: "Tatik.space Pro-dokumentasjon | Veiledning til verifiserte funksjoner", seoDescription: "Les om editoren, filer, sikkerhetskopier, utviklermarkedsplassen og skoleprogrammet i Tatik.space Pro, inkludert dagens begrensninger.",
  },
  fi: {
    title: "Dokumentaatio", home: "Takaisin etusivulle", introHeading: "Johdanto",
    intro: "Tässä oppaassa kuvataan Tatik.space Pron nykyisessä käyttöliittymässä varmennetut ominaisuudet. Saatavuus voi vaihdella tilin ja tiedoston tai projektin avaustavan mukaan.",
    editorHeading: "Editorin käyttäminen",
    editorSteps: ["Kirjaudu sisään ja avaa Editor sivuston navigaatiosta.", "Luo tai lataa tiedostoja Tiedosto-valikosta tai avaa paikallinen kansio, jos selaimesi tukee sitä.", "Valitse muokattava tiedosto. Säilytä kopio käyttämällä tallennusta tai käytettävissä olevia latausvaihtoehtoja.", "Käytä esikatselua tuetuissa verkkoprojekteissa. Se ei suorita kaikkia kieliä tai projektimäärityksiä."],
    featuresHeading: "Tärkeimmät ominaisuudet",
    features: [["Koodieditori ja esikatselu", "Muokkaa projektitiedostoja selaimessa. Esikatselu tukee valittua verkkosisältöä; se ei ole yleiskäyttöinen koonti- tai käyttöönottopalvelu."], ["Tekoälyavustaja", "Editorissa on tekoälyavustajan paneeli. Vastaukset riippuvat palvelun asetuksista; automaattisia koodikorjauksia tai pikanäppäimiä ei taata."], ["Tiedostot ja kansiot", "Luo ja lataa tiedostoja ja kansioita sekä avaa paikallisia kansioita selaimen salliessa. Paikalliset tiedostot ja pilviprojektin tiedostot tallentuvat eri kohteisiin."], ["Varmuuskopiot", "Luo ja palauta projektin tilannekuvia Backup-toiminnolla. Varmista varmuuskopion valmistuminen ennen siihen luottamista."]],
    availabilityHeading: "Ominaisuuksien nykytila",
    deployment: "Suora julkaiseminen ei ole tällä hetkellä käytettävissä Tatik.space Prossa. Käytössä ei ole toimivaa yhden napsautuksen Deploy-toimintoa eikä Tatikin tuotantohotelliosoitetta. Julkaise tallennetut tiedostot ulkoisen palveluntarjoajan kautta.",
    collaboration: "Yhteistyösivu käyttää tällä hetkellä kiinteää demoprojektia ja luotua demokäyttäjätunnusta. Se ei ole yhteydessä oikeaan projektiisi tai tiimiisi; älä kutsu siellä oikeita yhteistyökumppaneita tai jaa tuotantotietoja.",
    apiHeading: "API:n saatavuus", api: "Asiakkaille tarkoitettua julkista REST API -viitettä ei ole tällä hetkellä saatavilla. Sovelluksen sisäistä APIa ei kuvata tässä tuettuna integraationa.",
    formatsHeading: "Tuetut kielet ja tiedostomuodot", formatsIntro: "Editori tunnistaa tuetut tiedostotyypit ja korostaa syntaksin. Esikatselu toimii vain yhteensopivan verkkosisällön kanssa; tiedoston tunnistaminen ei tarkoita, että sen voi suorittaa tai julkaista.",
    formatGroups: ["Verkko ja data", "Ohjelmointikielet", "Määritykset ja dokumentaatio", "Kuvat ja paikalliset resurssit"],
    marketplaceHeading: "Kehittäjien markkinapaikka", marketplaceIntro: "Kehittäjät voivat lähettää digitaalisia resursseja tarkistettavaksi. Ladatut tiedostot pysyvät yksityisinä, kunnes listaus hyväksytään ja osto vahvistetaan.",
    marketplaceRules: ["Luo myyjäprofiili ja hyväksy ehdot; yhdistä Stripe ja suorita vahvistus ennen maksun pyytämistä.", "Luo listausluonnos ja lataa tiedosto. Nykyinen tiedostokohtainen raja on 2 Mt; vain henkilökunta voi hyväksyä, hylätä tai julkaista listauksen.", "Tatik kirjaa myynnistä 15 %:n provision. Palautukset, kiistat ja petostarkistukset voivat pienentää tai jäädyttää käytettävissä olevan saldon."],
    marketplaceWarning: "Älä lataa haittaohjelmia, kirjautumistietoja, muiden henkilötietoja tai aineistoa, jonka jakeluun sinulla ei ole oikeuksia. Maksut edellyttävät aktiivista Stripe Connect -tiliä, jolla maksut ja tilitykset ovat käytössä.",
    schoolsHeading: "Kouluohjelma", schoolsIntro: "Hyväksytty oppilaitos voi järjestää 30 päivän kurssin enintään 30 opiskelijalle. Odottavat tai hyväksytyt mutta lunastamattomat kutsut lasketaan mukaan rajaan; opiskelijoiden käyttöoikeus päättyy kurssin lopussa.",
    schoolsRules: ["Kirjautunut koulun yhteyshenkilö lähettää oppilaitoksen tiedot ja hyväksyy ohjelman ehdot.", "Tatikin ylläpitäjän tai työntekijän on hyväksyttävä oppilaitos.", "Yhteyshenkilö luo ja hyväksyy opiskelijakutsun. Tunniste on määräaikainen, henkilökohtainen, siirtokelvoton ja kertakäyttöinen.", "Kirjautunut opiskelija lunastaa tunnisteen. Koulu voi perua jäsenen käyttöoikeuden; toiminnot tallennetaan auditointilokiin."],
    schoolsWarning: "Kutsu luo tällä hetkellä tunnisteen, jonka koulu toimittaa hallitun kanavan kautta. Automaattinen kutsusähköposti on määritettävä erikseen ennen julkista käyttöä.",
    seoTitle: "Tatik.space Pro -dokumentaatio | Varmennettujen ominaisuuksien opas", seoDescription: "Tutustu Tatik.space Pron editoriin, tiedostoihin, varmuuskopioihin, kehittäjien markkinapaikkaan ja kouluohjelmaan sekä niiden nykyisiin rajoituksiin.",
  },
  uk: {
    title: "Документація", home: "На головну", introHeading: "Вступ",
    intro: "У цьому посібнику описано функції, перевірені в поточному інтерфейсі Tatik.space Pro. Доступність може залежати від облікового запису та способу відкриття файлу чи проєкту.",
    editorHeading: "Робота з редактором",
    editorSteps: ["Увійдіть і відкрийте редактор у навігації сайту.", "У меню «Файл» створюйте або завантажуйте файли чи відкривайте локальну теку, якщо браузер це підтримує.", "Виберіть файл для редагування. Скористайтеся збереженням або доступним завантаженням, щоб залишити копію.", "Використовуйте попередній перегляд для сумісних вебпроєктів. Він підтримує не всі мови та конфігурації."],
    featuresHeading: "Основні функції",
    features: [["Редактор коду та попередній перегляд", "Редагуйте файли проєкту в браузері. Попередній перегляд підтримує окремий вебвміст і не є універсальним середовищем збирання чи розгортання."], ["Помічник ШІ", "У редакторі доступна панель помічника ШІ. Відповіді залежать від налаштувань сервісу; автоматичне виправлення коду й комбінації клавіш не гарантуються."], ["Файли й теки", "Створюйте та завантажуйте файли й теки, а також відкривайте локальні теки, якщо це дозволяє браузер. Локальні файли й файли хмарного проєкту зберігаються в різних місцях."], ["Резервні копії", "Створюйте та відновлюйте знімки проєкту за допомогою Backup. Переконайтеся, що копіювання завершилося, перш ніж покладатися на нього."]],
    availabilityHeading: "Поточний стан функцій",
    deployment: "Пряма публікація в Tatik.space Pro наразі недоступна. Немає робочого розгортання в один клік або виробничої адреси від Tatik. Публікуйте збережені файли через зовнішній хостинг.",
    collaboration: "Сторінка співпраці використовує фіксований демонстраційний проєкт і згенерований демонстраційний ідентифікатор користувача. Вона не підключена до вашого реального проєкту чи команди; не запрошуйте там справжніх учасників і не поширюйте виробничі дані.",
    apiHeading: "Доступність API", api: "Публічної довідки REST API для клієнтів наразі немає. Внутрішній API застосунку тут не описано як підтримувану інтеграцію.",
    formatsHeading: "Підтримувані мови й формати файлів", formatsIntro: "Редактор розпізнає підтримувані типи файлів і підсвічує синтаксис. Попередній перегляд працює лише із сумісним вебвмістом; розпізнавання не означає, що файл можна запустити чи опублікувати.",
    formatGroups: ["Веб і дані", "Мови програмування", "Конфігурація та документація", "Зображення й локальні ресурси"],
    marketplaceHeading: "Маркетплейс розробників", marketplaceIntro: "Розробники можуть подати цифрові ресурси на перевірку. Завантажені файли залишаються приватними, доки оголошення не схвалять і покупку не підтвердять.",
    marketplaceRules: ["Створіть профіль продавця й прийміть умови; підключіть Stripe та пройдіть перевірку перед запитом виплат.", "Створіть чернетку оголошення й завантажте файл. Поточне обмеження — 2 МБ на файл; схвалювати, відхиляти й публікувати оголошення може лише персонал.", "Tatik обліковує комісію 15% з продажів. Повернення, суперечки та перевірки шахрайства можуть зменшити або призупинити доступний баланс."],
    marketplaceWarning: "Не завантажуйте шкідливе ПЗ, облікові дані, персональні дані інших осіб або матеріали без прав на поширення. Для виплат потрібен активний обліковий запис Stripe Connect з увімкненими платежами та виплатами.",
    schoolsHeading: "Шкільна програма", schoolsIntro: "Схвалений заклад може проводити курс тривалістю 30 днів для максимум 30 учнів. Очікувані або схвалені, але не використані запрошення також враховуються; доступ учнів завершується разом із курсом.",
    schoolsRules: ["Авторизований представник закладу надсилає його дані та приймає умови програми.", "Заклад має схвалити адміністратор або працівник Tatik.", "Представник створює та схвалює запрошення для учня. Токен тимчасовий, особистий, непередаваний і одноразовий.", "Авторизований учень активує токен. Заклад може скасувати доступ учасника; дії записуються в журналі аудиту."],
    schoolsWarning: "Наразі запрошення створює токен, який заклад має передати контрольованим каналом. Автоматичне надсилання листів-запрошень потрібно окремо налаштувати до публічного використання.",
    seoTitle: "Документація Tatik.space Pro | Посібник із перевірених функцій", seoDescription: "Дізнайтеся про редактор Tatik.space Pro, файли, резервні копії, маркетплейс розробників і шкільну програму та їхні поточні обмеження.",
  },
  cs: {
    title: "Dokumentace", home: "Zpět na hlavní stránku", introHeading: "Úvod",
    intro: "Tento průvodce popisuje funkce ověřené v aktuálním rozhraní Tatik.space Pro. Dostupnost se může lišit podle účtu a způsobu otevření souboru nebo projektu.",
    editorHeading: "Práce v editoru",
    editorSteps: ["Přihlaste se a otevřete Editor v navigaci webu.", "V nabídce Soubor vytvářejte nebo nahrávejte soubory, případně otevřete místní složku, pokud to prohlížeč podporuje.", "Vyberte soubor k úpravě. Pomocí uložení nebo dostupných možností stažení si ponechte kopii.", "Náhled používejte u podporovaných webových projektů. Nespustí všechny jazyky ani konfigurace."],
    featuresHeading: "Hlavní funkce",
    features: [["Editor kódu a náhled", "Upravujte soubory projektu v prohlížeči. Náhled podporuje vybraný webový obsah; nejde o obecné prostředí pro sestavení ani nasazení."], ["Asistent AI", "V editoru je k dispozici panel asistenta AI. Odpovědi závisí na konfiguraci služby; automatické opravy kódu ani klávesové zkratky nejsou zaručeny."], ["Soubory a složky", "Vytvářejte a nahrávejte soubory a složky a otevírejte místní složky, pokud to prohlížeč umožňuje. Místní soubory a soubory cloudového projektu se ukládají na různá místa."], ["Zálohy", "Pomocí Backup vytvářejte a obnovujte snímky projektu. Než se na zálohu spolehnete, ověřte její dokončení."]],
    availabilityHeading: "Aktuální stav funkcí",
    deployment: "Přímé publikování zatím není v Tatik.space Pro dostupné. Není k dispozici funkční nasazení jedním kliknutím ani produkční adresa hostovaná službou Tatik. Uložené soubory publikujte přes externího poskytovatele hostingu.",
    collaboration: "Stránka Spolupráce aktuálně používá pevný demo projekt a vygenerované demo ID uživatele. Není připojena k vašemu skutečnému projektu ani týmu; nezvěte přes ni skutečné spolupracovníky ani nesdílejte produkční data.",
    apiHeading: "Dostupnost API", api: "Veřejná dokumentace REST API pro zákazníky nyní není dostupná. Interní API aplikace zde není popsáno jako podporovaná integrace.",
    formatsHeading: "Podporované jazyky a formáty souborů", formatsIntro: "Editor rozpoznává podporované typy souborů a zvýrazňuje syntaxi. Náhled funguje pouze pro kompatibilní webový obsah; rozpoznání souboru neznamená, že jej lze spustit nebo publikovat.",
    formatGroups: ["Web a data", "Programovací jazyky", "Konfigurace a dokumentace", "Obrázky a místní zdroje"],
    marketplaceHeading: "Marketplace pro vývojáře", marketplaceIntro: "Vývojáři mohou předkládat digitální zdroje ke kontrole. Nahrané soubory zůstávají soukromé, dokud není nabídka schválena a nákup ověřen.",
    marketplaceRules: ["Vytvořte profil prodejce a přijměte podmínky; před žádostí o výplatu propojte Stripe a dokončete ověření.", "Vytvořte návrh nabídky a nahrajte soubor. Aktuální limit je 2 MB na soubor; nabídky může schvalovat, odmítat a publikovat pouze personál.", "Tatik účtuje 15% provizi z prodeje. Refundace, spory a kontroly proti podvodům mohou dostupný zůstatek snížit nebo pozastavit."],
    marketplaceWarning: "Nenahrávejte malware, přihlašovací údaje, osobní údaje jiných osob ani materiály, k jejichž šíření nemáte práva. Výplaty vyžadují aktivní účet Stripe Connect s povolenými platbami a výplatami.",
    schoolsHeading: "Školní program", schoolsIntro: "Schválená instituce může pořádat 30denní kurz pro nejvýše 30 studentů. Do limitu se počítají také čekající nebo schválené, ale nevyužité pozvánky; přístup skončí s kurzem.",
    schoolsRules: ["Přihlášený zástupce školy odešle údaje o instituci a přijme podmínky programu.", "Instituci musí schválit správce nebo pracovník Tatik.", "Zástupce vytvoří a schválí pozvánku pro studenta. Token je dočasný, osobní, nepřenosný a jednorázový.", "Přihlášený student token uplatní. Škola může členovi odebrat přístup; akce se zaznamenávají do auditního protokolu."],
    schoolsWarning: "Pozvánky nyní vytvářejí token, který škola předá určeným kontrolovaným kanálem. Automatické e-mailové pozvánky je před veřejným použitím nutné nastavit samostatně.",
    seoTitle: "Dokumentace Tatik.space Pro | Průvodce ověřenými funkcemi", seoDescription: "Poznejte editor, soubory, zálohy, marketplace pro vývojáře a školní program Tatik.space Pro včetně jejich aktuálních omezení.",
  },
};

const supportedExtensions = [
  "HTML, HTM, CSS, SCSS, Sass, Less, JavaScript, JSX, TypeScript, TSX, JSON, XML, Vue, Svelte",
  "Python, Java, C, C++, C#, PHP, Ruby, Go, Rust, Kotlin, Swift, Objective-C, Dart, Lua, R",
  "SQL, Markdown, YAML, YML, TOML, INI, CONF, Shell, Bash, Zsh, Fish, Dockerfile, Makefile",
  "PNG, JPG, JPEG, GIF, SVG, WEBP, AVIF, APNG, BMP, TIFF, TIF, ICO, HEIC; MP3, WAV, OGG, MP4, WEBM, MOV; WOFF, WOFF2, TTF, OTF",
];

export { supportedExtensions };
