const backupCopy = {
  en: {
    panelTitle: 'Backup management', panelDescription: '10 local backups on this PC + 2 online backups — always access your files',
    encryptedBy: 'Encrypted by', createBackup: 'Create backup', newBackup: 'Create new backup',
    createDescription: 'Save the project state. Choose whether to save locally (PC) or online (cloud).',
    backupType: 'Backup type', local: 'Local', online: 'Online', name: 'Backup name *',
    namePlaceholder: 'e.g. Stable release 1.0', description: 'Description (optional)',
    descriptionPlaceholder: 'Add a description to remember what it contains…', cancel: 'Cancel',
    creating: 'Creating…', localBackups: 'Local', onlineBackups: 'Online',
    loading: 'Loading backups…', loadingOnline: 'Loading online backups…',
    noLocal: 'No local backups', firstLocal: 'Create your first local backup to save it on this PC',
    noOnline: 'No online backups', firstOnline: 'Create an online backup to sync files to the cloud',
    olderBackups: 'Older backups (type not set)', nameRequired: 'Enter a name for the backup',
    deleteConfirm: 'Are you sure you want to delete this backup?',
    restoreConfirm: 'Are you sure you want to restore this backup? Unsaved changes will be lost.',
    created: '{type} backup created successfully!', savingLocal: 'Saving backup locally…',
    savedLocal: 'Backup saved locally!', createError: 'Error creating backup: {error}',
    deleted: 'Backup deleted successfully!', deleteError: 'Error deleting backup: {error}',
    restored: 'Backup restored successfully!', restoreError: 'Error restoring backup: {error}',
    localCreated: 'Local backup created!', localDeleted: 'Local backup deleted!', localRestored: 'Local backup restored!',
    restoreLabel: 'Restore backup', deleteLabel: 'Delete backup',
  },
  it: {
    panelTitle: 'Gestione backup', panelDescription: '10 backup locali su questo PC + 2 backup online — accedi sempre ai tuoi file',
    encryptedBy: 'Crittografia di', createBackup: 'Crea backup', newBackup: 'Crea nuovo backup',
    createDescription: 'Salva lo stato del progetto. Scegli se salvare localmente (PC) o online (cloud).',
    backupType: 'Tipo di backup', local: 'Locale', online: 'Online', name: 'Nome backup *',
    namePlaceholder: 'es. Versione stabile 1.0', description: 'Descrizione (facoltativa)',
    descriptionPlaceholder: 'Aggiungi una descrizione per ricordare cosa contiene…', cancel: 'Annulla',
    creating: 'Creazione…', localBackups: 'Locali', onlineBackups: 'Online',
    loading: 'Caricamento backup…', loadingOnline: 'Caricamento backup online…',
    noLocal: 'Nessun backup locale', firstLocal: 'Crea il tuo primo backup locale per salvare su questo PC',
    noOnline: 'Nessun backup online', firstOnline: 'Crea un backup online per sincronizzare i file nel cloud',
    olderBackups: 'Backup precedenti (senza tipo)', nameRequired: 'Inserisci un nome per il backup',
    deleteConfirm: 'Vuoi davvero eliminare questo backup?',
    restoreConfirm: 'Vuoi davvero ripristinare questo backup? Le modifiche non salvate andranno perse.',
    created: 'Backup {type} creato con successo!', savingLocal: 'Salvataggio locale del backup…',
    savedLocal: 'Backup salvato localmente!', createError: 'Errore durante la creazione del backup: {error}',
    deleted: 'Backup eliminato con successo!', deleteError: 'Errore durante l’eliminazione del backup: {error}',
    restored: 'Backup ripristinato con successo!', restoreError: 'Errore durante il ripristino del backup: {error}',
    localCreated: 'Backup locale creato!', localDeleted: 'Backup locale eliminato!', localRestored: 'Backup locale ripristinato!',
    restoreLabel: 'Ripristina backup', deleteLabel: 'Elimina backup',
  },
  es: {
    panelTitle: 'Gestión de copias de seguridad', panelDescription: '10 copias locales en este PC + 2 copias online: accede siempre a tus archivos',
    encryptedBy: 'Cifrado por', createBackup: 'Crear copia', newBackup: 'Crear nueva copia',
    createDescription: 'Guarda el estado del proyecto. Elige si quieres guardar localmente (PC) o en línea (nube).',
    backupType: 'Tipo de copia', local: 'Local', online: 'En línea', name: 'Nombre de la copia *',
    namePlaceholder: 'p. ej., Versión estable 1.0', description: 'Descripción (opcional)',
    descriptionPlaceholder: 'Añade una descripción para recordar qué contiene…', cancel: 'Cancelar',
    creating: 'Creando…', localBackups: 'Locales', onlineBackups: 'En línea',
    loading: 'Cargando copias…', loadingOnline: 'Cargando copias en línea…',
    noLocal: 'No hay copias locales', firstLocal: 'Crea tu primera copia local para guardarla en este PC',
    noOnline: 'No hay copias en línea', firstOnline: 'Crea una copia en línea para sincronizar archivos en la nube',
    olderBackups: 'Copias anteriores (sin tipo)', nameRequired: 'Introduce un nombre para la copia',
    deleteConfirm: '¿Seguro que quieres eliminar esta copia?',
    restoreConfirm: '¿Seguro que quieres restaurar esta copia? Se perderán los cambios sin guardar.',
    created: '¡Copia {type} creada correctamente!', savingLocal: 'Guardando la copia localmente…',
    savedLocal: '¡Copia guardada localmente!', createError: 'Error al crear la copia: {error}',
    deleted: '¡Copia eliminada correctamente!', deleteError: 'Error al eliminar la copia: {error}',
    restored: '¡Copia restaurada correctamente!', restoreError: 'Error al restaurar la copia: {error}',
    localCreated: '¡Copia local creada!', localDeleted: '¡Copia local eliminada!', localRestored: '¡Copia local restaurada!',
    restoreLabel: 'Restaurar copia', deleteLabel: 'Eliminar copia',
  },
  fr: {
    panelTitle: 'Gestion des sauvegardes', panelDescription: '10 sauvegardes locales sur ce PC + 2 sauvegardes en ligne — accédez toujours à vos fichiers',
    encryptedBy: 'Chiffré par', createBackup: 'Créer une sauvegarde', newBackup: 'Créer une sauvegarde',
    createDescription: 'Enregistrez l’état du projet. Choisissez un enregistrement local (PC) ou en ligne (cloud).',
    backupType: 'Type de sauvegarde', local: 'Locale', online: 'En ligne', name: 'Nom de la sauvegarde *',
    namePlaceholder: 'ex. : Version stable 1.0', description: 'Description (facultatif)',
    descriptionPlaceholder: 'Ajoutez une description pour vous rappeler son contenu…', cancel: 'Annuler',
    creating: 'Création…', localBackups: 'Locales', onlineBackups: 'En ligne',
    loading: 'Chargement des sauvegardes…', loadingOnline: 'Chargement des sauvegardes en ligne…',
    noLocal: 'Aucune sauvegarde locale', firstLocal: 'Créez votre première sauvegarde locale pour l’enregistrer sur ce PC',
    noOnline: 'Aucune sauvegarde en ligne', firstOnline: 'Créez une sauvegarde en ligne pour synchroniser les fichiers dans le cloud',
    olderBackups: 'Sauvegardes précédentes (type non défini)', nameRequired: 'Saisissez un nom pour la sauvegarde',
    deleteConfirm: 'Voulez-vous vraiment supprimer cette sauvegarde ?',
    restoreConfirm: 'Voulez-vous vraiment restaurer cette sauvegarde ? Les modifications non enregistrées seront perdues.',
    created: 'Sauvegarde {type} créée avec succès !', savingLocal: 'Enregistrement local de la sauvegarde…',
    savedLocal: 'Sauvegarde enregistrée localement !', createError: 'Erreur lors de la création de la sauvegarde : {error}',
    deleted: 'Sauvegarde supprimée !', deleteError: 'Erreur lors de la suppression de la sauvegarde : {error}',
    restored: 'Sauvegarde restaurée !', restoreError: 'Erreur lors de la restauration de la sauvegarde : {error}',
    localCreated: 'Sauvegarde locale créée !', localDeleted: 'Sauvegarde locale supprimée !', localRestored: 'Sauvegarde locale restaurée !',
    restoreLabel: 'Restaurer la sauvegarde', deleteLabel: 'Supprimer la sauvegarde',
  },
  de: {
    panelTitle: 'Sicherungsverwaltung', panelDescription: '10 lokale Sicherungen auf diesem PC + 2 Online-Sicherungen — jederzeit Zugriff auf deine Dateien',
    encryptedBy: 'Verschlüsselt von', createBackup: 'Sicherung erstellen', newBackup: 'Neue Sicherung erstellen',
    createDescription: 'Speichere den Projektstatus. Wähle eine lokale Speicherung (PC) oder online (Cloud).',
    backupType: 'Sicherungstyp', local: 'Lokal', online: 'Online', name: 'Name der Sicherung *',
    namePlaceholder: 'z. B. Stabile Version 1.0', description: 'Beschreibung (optional)',
    descriptionPlaceholder: 'Füge eine Beschreibung hinzu, damit du den Inhalt wiedererkennst…', cancel: 'Abbrechen',
    creating: 'Wird erstellt…', localBackups: 'Lokal', onlineBackups: 'Online',
    loading: 'Sicherungen werden geladen…', loadingOnline: 'Online-Sicherungen werden geladen…',
    noLocal: 'Keine lokalen Sicherungen', firstLocal: 'Erstelle deine erste lokale Sicherung auf diesem PC',
    noOnline: 'Keine Online-Sicherungen', firstOnline: 'Erstelle eine Online-Sicherung, um Dateien mit der Cloud zu synchronisieren',
    olderBackups: 'Ältere Sicherungen (Typ nicht festgelegt)', nameRequired: 'Gib einen Namen für die Sicherung ein',
    deleteConfirm: 'Möchtest du diese Sicherung wirklich löschen?',
    restoreConfirm: 'Möchtest du diese Sicherung wirklich wiederherstellen? Nicht gespeicherte Änderungen gehen verloren.',
    created: '{type}-Sicherung erfolgreich erstellt!', savingLocal: 'Sicherung wird lokal gespeichert…',
    savedLocal: 'Sicherung lokal gespeichert!', createError: 'Fehler beim Erstellen der Sicherung: {error}',
    deleted: 'Sicherung erfolgreich gelöscht!', deleteError: 'Fehler beim Löschen der Sicherung: {error}',
    restored: 'Sicherung erfolgreich wiederhergestellt!', restoreError: 'Fehler beim Wiederherstellen der Sicherung: {error}',
    localCreated: 'Lokale Sicherung erstellt!', localDeleted: 'Lokale Sicherung gelöscht!', localRestored: 'Lokale Sicherung wiederhergestellt!',
    restoreLabel: 'Sicherung wiederherstellen', deleteLabel: 'Sicherung löschen',
  },
  pt: {
    panelTitle: 'Gerenciamento de backups', panelDescription: '10 backups locais neste PC + 2 backups online — acesse seus arquivos sempre',
    encryptedBy: 'Criptografado por', createBackup: 'Criar backup', newBackup: 'Criar novo backup',
    createDescription: 'Salve o estado do projeto. Escolha salvar localmente (PC) ou online (nuvem).',
    backupType: 'Tipo de backup', local: 'Local', online: 'Online', name: 'Nome do backup *',
    namePlaceholder: 'ex.: Versão estável 1.0', description: 'Descrição (opcional)',
    descriptionPlaceholder: 'Adicione uma descrição para lembrar o conteúdo…', cancel: 'Cancelar',
    creating: 'Criando…', localBackups: 'Locais', onlineBackups: 'Online',
    loading: 'Carregando backups…', loadingOnline: 'Carregando backups online…',
    noLocal: 'Nenhum backup local', firstLocal: 'Crie seu primeiro backup local para salvar neste PC',
    noOnline: 'Nenhum backup online', firstOnline: 'Crie um backup online para sincronizar arquivos na nuvem',
    olderBackups: 'Backups anteriores (sem tipo)', nameRequired: 'Digite um nome para o backup',
    deleteConfirm: 'Tem certeza de que deseja excluir este backup?',
    restoreConfirm: 'Tem certeza de que deseja restaurar este backup? As alterações não salvas serão perdidas.',
    created: 'Backup {type} criado com sucesso!', savingLocal: 'Salvando backup localmente…',
    savedLocal: 'Backup salvo localmente!', createError: 'Erro ao criar backup: {error}',
    deleted: 'Backup excluído com sucesso!', deleteError: 'Erro ao excluir backup: {error}',
    restored: 'Backup restaurado com sucesso!', restoreError: 'Erro ao restaurar backup: {error}',
    localCreated: 'Backup local criado!', localDeleted: 'Backup local excluído!', localRestored: 'Backup local restaurado!',
    restoreLabel: 'Restaurar backup', deleteLabel: 'Excluir backup',
  },
  ru: {
    panelTitle: 'Управление резервными копиями', panelDescription: '10 локальных копий на этом ПК + 2 онлайн-копии — файлы всегда доступны',
    encryptedBy: 'Зашифровано', createBackup: 'Создать копию', newBackup: 'Создать резервную копию',
    createDescription: 'Сохраните состояние проекта. Выберите локальное сохранение (ПК) или онлайн (облако).',
    backupType: 'Тип копии', local: 'Локальная', online: 'Онлайн', name: 'Название копии *',
    namePlaceholder: 'например, стабильная версия 1.0', description: 'Описание (необязательно)',
    descriptionPlaceholder: 'Добавьте описание, чтобы помнить содержимое…', cancel: 'Отмена',
    creating: 'Создание…', localBackups: 'Локальные', onlineBackups: 'Онлайн',
    loading: 'Загрузка резервных копий…', loadingOnline: 'Загрузка онлайн-копий…',
    noLocal: 'Локальных копий нет', firstLocal: 'Создайте первую локальную копию на этом ПК',
    noOnline: 'Онлайн-копий нет', firstOnline: 'Создайте онлайн-копию для синхронизации файлов с облаком',
    olderBackups: 'Предыдущие копии (тип не указан)', nameRequired: 'Введите название копии',
    deleteConfirm: 'Удалить эту резервную копию?',
    restoreConfirm: 'Восстановить эту резервную копию? Несохранённые изменения будут потеряны.',
    created: 'Резервная копия ({type}) создана!', savingLocal: 'Сохранение копии локально…',
    savedLocal: 'Резервная копия сохранена локально!', createError: 'Ошибка создания резервной копии: {error}',
    deleted: 'Резервная копия удалена!', deleteError: 'Ошибка удаления резервной копии: {error}',
    restored: 'Резервная копия восстановлена!', restoreError: 'Ошибка восстановления резервной копии: {error}',
    localCreated: 'Локальная копия создана!', localDeleted: 'Локальная копия удалена!', localRestored: 'Локальная копия восстановлена!',
    restoreLabel: 'Восстановить копию', deleteLabel: 'Удалить копию',
  },
  zh: {
    panelTitle: '备份管理', panelDescription: '此电脑上有 10 个本地备份 + 2 个在线备份 — 随时访问文件',
    encryptedBy: '加密服务：', createBackup: '创建备份', newBackup: '创建新备份',
    createDescription: '保存项目状态。选择保存到本地（电脑）或在线（云端）。',
    backupType: '备份类型', local: '本地', online: '在线', name: '备份名称 *',
    namePlaceholder: '例如：稳定版本 1.0', description: '描述（可选）',
    descriptionPlaceholder: '添加描述以便记住备份内容…', cancel: '取消',
    creating: '正在创建…', localBackups: '本地', onlineBackups: '在线',
    loading: '正在加载备份…', loadingOnline: '正在加载在线备份…',
    noLocal: '没有本地备份', firstLocal: '创建第一个本地备份并保存到此电脑',
    noOnline: '没有在线备份', firstOnline: '创建在线备份以将文件同步到云端',
    olderBackups: '以前的备份（未设置类型）', nameRequired: '请输入备份名称',
    deleteConfirm: '确定要删除此备份吗？',
    restoreConfirm: '确定要恢复此备份吗？未保存的更改将丢失。',
    created: '已成功创建{type}备份！', savingLocal: '正在本地保存备份…',
    savedLocal: '备份已保存到本地！', createError: '创建备份时出错：{error}',
    deleted: '备份已成功删除！', deleteError: '删除备份时出错：{error}',
    restored: '备份已成功恢复！', restoreError: '恢复备份时出错：{error}',
    localCreated: '已创建本地备份！', localDeleted: '已删除本地备份！', localRestored: '已恢复本地备份！',
    restoreLabel: '恢复备份', deleteLabel: '删除备份',
  },
  ja: {
    panelTitle: 'バックアップ管理', panelDescription: 'この PC にローカルバックアップ 10 件 + オンラインバックアップ 2 件 — いつでもファイルにアクセス',
    encryptedBy: '暗号化：', createBackup: 'バックアップを作成', newBackup: '新しいバックアップを作成',
    createDescription: 'プロジェクトの状態を保存します。ローカル（PC）またはオンライン（クラウド）を選択してください。',
    backupType: 'バックアップの種類', local: 'ローカル', online: 'オンライン', name: 'バックアップ名 *',
    namePlaceholder: '例：安定版 1.0', description: '説明（任意）',
    descriptionPlaceholder: '内容を思い出せるよう説明を追加…', cancel: 'キャンセル',
    creating: '作成中…', localBackups: 'ローカル', onlineBackups: 'オンライン',
    loading: 'バックアップを読み込み中…', loadingOnline: 'オンラインバックアップを読み込み中…',
    noLocal: 'ローカルバックアップはありません', firstLocal: '最初のローカルバックアップを作成してこの PC に保存',
    noOnline: 'オンラインバックアップはありません', firstOnline: 'オンラインバックアップを作成してファイルをクラウドに同期',
    olderBackups: '以前のバックアップ（種類未設定）', nameRequired: 'バックアップ名を入力してください',
    deleteConfirm: 'このバックアップを削除しますか？',
    restoreConfirm: 'このバックアップを復元しますか？未保存の変更は失われます。',
    created: '{type}バックアップを作成しました！', savingLocal: 'バックアップをローカルに保存中…',
    savedLocal: 'バックアップをローカルに保存しました！', createError: 'バックアップ作成エラー：{error}',
    deleted: 'バックアップを削除しました！', deleteError: 'バックアップ削除エラー：{error}',
    restored: 'バックアップを復元しました！', restoreError: 'バックアップ復元エラー：{error}',
    localCreated: 'ローカルバックアップを作成しました！', localDeleted: 'ローカルバックアップを削除しました！', localRestored: 'ローカルバックアップを復元しました！',
    restoreLabel: 'バックアップを復元', deleteLabel: 'バックアップを削除',
  },
  ko: {
    panelTitle: '백업 관리', panelDescription: '이 PC에 로컬 백업 10개 + 온라인 백업 2개 — 언제든 파일에 액세스',
    encryptedBy: '암호화 제공:', createBackup: '백업 만들기', newBackup: '새 백업 만들기',
    createDescription: '프로젝트 상태를 저장합니다. 로컬(PC) 또는 온라인(클라우드) 저장을 선택하세요.',
    backupType: '백업 유형', local: '로컬', online: '온라인', name: '백업 이름 *',
    namePlaceholder: '예: 안정 버전 1.0', description: '설명(선택 사항)',
    descriptionPlaceholder: '내용을 기억할 수 있도록 설명을 추가하세요…', cancel: '취소',
    creating: '만드는 중…', localBackups: '로컬', onlineBackups: '온라인',
    loading: '백업을 불러오는 중…', loadingOnline: '온라인 백업을 불러오는 중…',
    noLocal: '로컬 백업이 없습니다', firstLocal: '첫 로컬 백업을 만들어 이 PC에 저장하세요',
    noOnline: '온라인 백업이 없습니다', firstOnline: '온라인 백업을 만들어 파일을 클라우드와 동기화하세요',
    olderBackups: '이전 백업(유형 없음)', nameRequired: '백업 이름을 입력하세요',
    deleteConfirm: '이 백업을 삭제할까요?',
    restoreConfirm: '이 백업을 복원할까요? 저장하지 않은 변경 사항은 사라집니다.',
    created: '{type} 백업을 만들었습니다!', savingLocal: '백업을 로컬에 저장하는 중…',
    savedLocal: '백업을 로컬에 저장했습니다!', createError: '백업 생성 오류: {error}',
    deleted: '백업을 삭제했습니다!', deleteError: '백업 삭제 오류: {error}',
    restored: '백업을 복원했습니다!', restoreError: '백업 복원 오류: {error}',
    localCreated: '로컬 백업을 만들었습니다!', localDeleted: '로컬 백업을 삭제했습니다!', localRestored: '로컬 백업을 복원했습니다!',
    restoreLabel: '백업 복원', deleteLabel: '백업 삭제',
  },
  ar: {
    panelTitle: 'إدارة النسخ الاحتياطية', panelDescription: '10 نسخ محلية على هذا الكمبيوتر + نسختان عبر الإنترنت — وصول دائم إلى ملفاتك',
    encryptedBy: 'التشفير بواسطة', createBackup: 'إنشاء نسخة احتياطية', newBackup: 'إنشاء نسخة جديدة',
    createDescription: 'احفظ حالة المشروع. اختر الحفظ محليًا (الكمبيوتر) أو عبر الإنترنت (السحابة).',
    backupType: 'نوع النسخة الاحتياطية', local: 'محلية', online: 'عبر الإنترنت', name: 'اسم النسخة *',
    namePlaceholder: 'مثال: الإصدار المستقر 1.0', description: 'الوصف (اختياري)',
    descriptionPlaceholder: 'أضف وصفًا لتتذكر محتوياتها…', cancel: 'إلغاء',
    creating: 'جارٍ الإنشاء…', localBackups: 'محلية', onlineBackups: 'عبر الإنترنت',
    loading: 'جارٍ تحميل النسخ الاحتياطية…', loadingOnline: 'جارٍ تحميل النسخ عبر الإنترنت…',
    noLocal: 'لا توجد نسخ محلية', firstLocal: 'أنشئ أول نسخة محلية واحفظها على هذا الكمبيوتر',
    noOnline: 'لا توجد نسخ عبر الإنترنت', firstOnline: 'أنشئ نسخة عبر الإنترنت لمزامنة الملفات مع السحابة',
    olderBackups: 'نسخ سابقة (النوع غير محدد)', nameRequired: 'أدخل اسمًا للنسخة الاحتياطية',
    deleteConfirm: 'هل تريد حذف هذه النسخة الاحتياطية؟',
    restoreConfirm: 'هل تريد استعادة هذه النسخة؟ ستُفقد التغييرات غير المحفوظة.',
    created: 'تم إنشاء النسخة {type} بنجاح!', savingLocal: 'جارٍ حفظ النسخة محليًا…',
    savedLocal: 'تم حفظ النسخة محليًا!', createError: 'خطأ في إنشاء النسخة الاحتياطية: {error}',
    deleted: 'تم حذف النسخة بنجاح!', deleteError: 'خطأ في حذف النسخة الاحتياطية: {error}',
    restored: 'تمت استعادة النسخة بنجاح!', restoreError: 'خطأ في استعادة النسخة الاحتياطية: {error}',
    localCreated: 'تم إنشاء نسخة محلية!', localDeleted: 'تم حذف النسخة المحلية!', localRestored: 'تمت استعادة النسخة المحلية!',
    restoreLabel: 'استعادة النسخة', deleteLabel: 'حذف النسخة',
  },
  hi: {
    panelTitle: 'बैकअप प्रबंधन', panelDescription: 'इस PC पर 10 स्थानीय बैकअप + 2 ऑनलाइन बैकअप — अपनी फ़ाइलों तक हमेशा पहुँचें',
    encryptedBy: 'एन्क्रिप्शन सेवा:', createBackup: 'बैकअप बनाएँ', newBackup: 'नया बैकअप बनाएँ',
    createDescription: 'प्रोजेक्ट की स्थिति सहेजें। स्थानीय (PC) या ऑनलाइन (क्लाउड) सहेजना चुनें।',
    backupType: 'बैकअप प्रकार', local: 'स्थानीय', online: 'ऑनलाइन', name: 'बैकअप नाम *',
    namePlaceholder: 'जैसे: स्थिर संस्करण 1.0', description: 'विवरण (वैकल्पिक)',
    descriptionPlaceholder: 'सामग्री याद रखने के लिए विवरण जोड़ें…', cancel: 'रद्द करें',
    creating: 'बनाया जा रहा है…', localBackups: 'स्थानीय', onlineBackups: 'ऑनलाइन',
    loading: 'बैकअप लोड हो रहे हैं…', loadingOnline: 'ऑनलाइन बैकअप लोड हो रहे हैं…',
    noLocal: 'कोई स्थानीय बैकअप नहीं', firstLocal: 'इस PC पर सहेजने के लिए अपना पहला स्थानीय बैकअप बनाएँ',
    noOnline: 'कोई ऑनलाइन बैकअप नहीं', firstOnline: 'फ़ाइलों को क्लाउड से सिंक करने के लिए ऑनलाइन बैकअप बनाएँ',
    olderBackups: 'पुराने बैकअप (प्रकार निर्धारित नहीं)', nameRequired: 'बैकअप के लिए नाम दर्ज करें',
    deleteConfirm: 'क्या आप वाकई यह बैकअप हटाना चाहते हैं?',
    restoreConfirm: 'क्या आप वाकई यह बैकअप पुनर्स्थापित करना चाहते हैं? सहेजे नहीं गए बदलाव खो जाएँगे।',
    created: '{type} बैकअप सफलतापूर्वक बनाया गया!', savingLocal: 'बैकअप स्थानीय रूप से सहेजा जा रहा है…',
    savedLocal: 'बैकअप स्थानीय रूप से सहेजा गया!', createError: 'बैकअप बनाने में त्रुटि: {error}',
    deleted: 'बैकअप सफलतापूर्वक हटाया गया!', deleteError: 'बैकअप हटाने में त्रुटि: {error}',
    restored: 'बैकअप सफलतापूर्वक पुनर्स्थापित हुआ!', restoreError: 'बैकअप पुनर्स्थापित करने में त्रुटि: {error}',
    localCreated: 'स्थानीय बैकअप बनाया गया!', localDeleted: 'स्थानीय बैकअप हटाया गया!', localRestored: 'स्थानीय बैकअप पुनर्स्थापित हुआ!',
    restoreLabel: 'बैकअप पुनर्स्थापित करें', deleteLabel: 'बैकअप हटाएँ',
  },
  pl: {
    panelTitle: 'Zarządzanie kopiami zapasowymi', panelDescription: '10 kopii lokalnych na tym komputerze + 2 kopie online — zawsze miej dostęp do plików',
    encryptedBy: 'Szyfrowanie: ', createBackup: 'Utwórz kopię', newBackup: 'Utwórz nową kopię',
    createDescription: 'Zapisz stan projektu. Wybierz zapis lokalny (komputer) lub online (chmura).',
    backupType: 'Typ kopii', local: 'Lokalna', online: 'Online', name: 'Nazwa kopii *',
    namePlaceholder: 'np. Stabilna wersja 1.0', description: 'Opis (opcjonalnie)',
    descriptionPlaceholder: 'Dodaj opis, aby pamiętać zawartość…', cancel: 'Anuluj',
    creating: 'Tworzenie…', localBackups: 'Lokalne', onlineBackups: 'Online',
    loading: 'Wczytywanie kopii…', loadingOnline: 'Wczytywanie kopii online…',
    noLocal: 'Brak lokalnych kopii', firstLocal: 'Utwórz pierwszą lokalną kopię i zapisz ją na tym komputerze',
    noOnline: 'Brak kopii online', firstOnline: 'Utwórz kopię online, aby synchronizować pliki z chmurą',
    olderBackups: 'Wcześniejsze kopie (bez określonego typu)', nameRequired: 'Wpisz nazwę kopii zapasowej',
    deleteConfirm: 'Czy na pewno chcesz usunąć tę kopię?',
    restoreConfirm: 'Czy na pewno chcesz przywrócić tę kopię? Niezapisane zmiany zostaną utracone.',
    created: 'Utworzono kopię {type}!', savingLocal: 'Zapisywanie kopii lokalnie…',
    savedLocal: 'Zapisano kopię lokalnie!', createError: 'Błąd tworzenia kopii: {error}',
    deleted: 'Usunięto kopię!', deleteError: 'Błąd usuwania kopii: {error}',
    restored: 'Przywrócono kopię!', restoreError: 'Błąd przywracania kopii: {error}',
    localCreated: 'Utworzono kopię lokalną!', localDeleted: 'Usunięto kopię lokalną!', localRestored: 'Przywrócono kopię lokalną!',
    restoreLabel: 'Przywróć kopię', deleteLabel: 'Usuń kopię',
  },
  nl: {
    panelTitle: 'Back-upbeheer', panelDescription: '10 lokale back-ups op deze pc + 2 online back-ups — altijd toegang tot je bestanden',
    encryptedBy: 'Versleuteld door', createBackup: 'Back-up maken', newBackup: 'Nieuwe back-up maken',
    createDescription: 'Sla de projectstatus op. Kies lokaal opslaan (pc) of online (cloud).',
    backupType: 'Back-uptype', local: 'Lokaal', online: 'Online', name: 'Back-upnaam *',
    namePlaceholder: 'bijv. Stabiele versie 1.0', description: 'Beschrijving (optioneel)',
    descriptionPlaceholder: 'Voeg een beschrijving toe zodat je onthoudt wat erin staat…', cancel: 'Annuleren',
    creating: 'Bezig met maken…', localBackups: 'Lokaal', onlineBackups: 'Online',
    loading: 'Back-ups laden…', loadingOnline: 'Online back-ups laden…',
    noLocal: 'Geen lokale back-ups', firstLocal: 'Maak je eerste lokale back-up op deze pc',
    noOnline: 'Geen online back-ups', firstOnline: 'Maak een online back-up om bestanden met de cloud te synchroniseren',
    olderBackups: 'Oudere back-ups (type niet ingesteld)', nameRequired: 'Voer een naam voor de back-up in',
    deleteConfirm: 'Weet je zeker dat je deze back-up wilt verwijderen?',
    restoreConfirm: 'Weet je zeker dat je deze back-up wilt herstellen? Niet-opgeslagen wijzigingen gaan verloren.',
    created: '{type} back-up gemaakt!', savingLocal: 'Back-up lokaal opslaan…',
    savedLocal: 'Back-up lokaal opgeslagen!', createError: 'Fout bij het maken van de back-up: {error}',
    deleted: 'Back-up verwijderd!', deleteError: 'Fout bij het verwijderen van de back-up: {error}',
    restored: 'Back-up hersteld!', restoreError: 'Fout bij het herstellen van de back-up: {error}',
    localCreated: 'Lokale back-up gemaakt!', localDeleted: 'Lokale back-up verwijderd!', localRestored: 'Lokale back-up hersteld!',
    restoreLabel: 'Back-up herstellen', deleteLabel: 'Back-up verwijderen',
  },
  tr: {
    panelTitle: 'Yedek yönetimi', panelDescription: 'Bu bilgisayarda 10 yerel yedek + 2 çevrimiçi yedek — dosyalarınıza her zaman erişin',
    encryptedBy: 'Şifreleyen:', createBackup: 'Yedek oluştur', newBackup: 'Yeni yedek oluştur',
    createDescription: 'Proje durumunu kaydedin. Yerel (PC) veya çevrimiçi (bulut) kaydetmeyi seçin.',
    backupType: 'Yedek türü', local: 'Yerel', online: 'Çevrimiçi', name: 'Yedek adı *',
    namePlaceholder: 'örn. Kararlı sürüm 1.0', description: 'Açıklama (isteğe bağlı)',
    descriptionPlaceholder: 'İçeriğini hatırlamak için açıklama ekleyin…', cancel: 'İptal',
    creating: 'Oluşturuluyor…', localBackups: 'Yerel', onlineBackups: 'Çevrimiçi',
    loading: 'Yedekler yükleniyor…', loadingOnline: 'Çevrimiçi yedekler yükleniyor…',
    noLocal: 'Yerel yedek yok', firstLocal: 'Bu bilgisayara kaydetmek için ilk yerel yedeğinizi oluşturun',
    noOnline: 'Çevrimiçi yedek yok', firstOnline: 'Dosyaları bulutla eşitlemek için çevrimiçi yedek oluşturun',
    olderBackups: 'Önceki yedekler (tür belirtilmemiş)', nameRequired: 'Yedek için bir ad girin',
    deleteConfirm: 'Bu yedeği silmek istediğinizden emin misiniz?',
    restoreConfirm: 'Bu yedeği geri yüklemek istediğinizden emin misiniz? Kaydedilmemiş değişiklikler kaybolacak.',
    created: '{type} yedek başarıyla oluşturuldu!', savingLocal: 'Yedek yerel olarak kaydediliyor…',
    savedLocal: 'Yedek yerel olarak kaydedildi!', createError: 'Yedek oluşturma hatası: {error}',
    deleted: 'Yedek başarıyla silindi!', deleteError: 'Yedek silme hatası: {error}',
    restored: 'Yedek başarıyla geri yüklendi!', restoreError: 'Yedek geri yükleme hatası: {error}',
    localCreated: 'Yerel yedek oluşturuldu!', localDeleted: 'Yerel yedek silindi!', localRestored: 'Yerel yedek geri yüklendi!',
    restoreLabel: 'Yedeği geri yükle', deleteLabel: 'Yedeği sil',
  },
  sv: {
    panelTitle: 'Säkerhetskopior', panelDescription: '10 lokala säkerhetskopior på den här datorn + 2 online — alltid åtkomst till dina filer',
    encryptedBy: 'Krypterad av', createBackup: 'Skapa säkerhetskopia', newBackup: 'Skapa ny säkerhetskopia',
    createDescription: 'Spara projektets status. Välj lokal lagring (dator) eller online (molnet).',
    backupType: 'Typ av säkerhetskopia', local: 'Lokal', online: 'Online', name: 'Namn på säkerhetskopia *',
    namePlaceholder: 't.ex. Stabil version 1.0', description: 'Beskrivning (valfritt)',
    descriptionPlaceholder: 'Lägg till en beskrivning så att du kommer ihåg innehållet…', cancel: 'Avbryt',
    creating: 'Skapar…', localBackups: 'Lokala', onlineBackups: 'Online',
    loading: 'Läser in säkerhetskopior…', loadingOnline: 'Läser in säkerhetskopior online…',
    noLocal: 'Inga lokala säkerhetskopior', firstLocal: 'Skapa din första lokala säkerhetskopia på den här datorn',
    noOnline: 'Inga säkerhetskopior online', firstOnline: 'Skapa en säkerhetskopia online för att synkronisera filer med molnet',
    olderBackups: 'Tidigare säkerhetskopior (typ saknas)', nameRequired: 'Ange ett namn på säkerhetskopian',
    deleteConfirm: 'Vill du ta bort den här säkerhetskopian?',
    restoreConfirm: 'Vill du återställa den här säkerhetskopian? Osparade ändringar går förlorade.',
    created: '{type} säkerhetskopia skapad!', savingLocal: 'Sparar säkerhetskopian lokalt…',
    savedLocal: 'Säkerhetskopian har sparats lokalt!', createError: 'Det gick inte att skapa säkerhetskopian: {error}',
    deleted: 'Säkerhetskopian har tagits bort!', deleteError: 'Det gick inte att ta bort säkerhetskopian: {error}',
    restored: 'Säkerhetskopian har återställts!', restoreError: 'Det gick inte att återställa säkerhetskopian: {error}',
    localCreated: 'Lokal säkerhetskopia skapad!', localDeleted: 'Lokal säkerhetskopia borttagen!', localRestored: 'Lokal säkerhetskopia återställd!',
    restoreLabel: 'Återställ säkerhetskopia', deleteLabel: 'Ta bort säkerhetskopia',
  },
  da: {
    panelTitle: 'Administration af sikkerhedskopier', panelDescription: '10 lokale sikkerhedskopier på denne pc + 2 online — altid adgang til dine filer',
    encryptedBy: 'Krypteret af', createBackup: 'Opret sikkerhedskopi', newBackup: 'Opret ny sikkerhedskopi',
    createDescription: 'Gem projektets tilstand. Vælg lokal lagring (pc) eller online (sky).',
    backupType: 'Type af sikkerhedskopi', local: 'Lokal', online: 'Online', name: 'Navn på sikkerhedskopi *',
    namePlaceholder: 'f.eks. Stabil version 1.0', description: 'Beskrivelse (valgfri)',
    descriptionPlaceholder: 'Tilføj en beskrivelse, så du kan huske indholdet…', cancel: 'Annuller',
    creating: 'Opretter…', localBackups: 'Lokale', onlineBackups: 'Online',
    loading: 'Indlæser sikkerhedskopier…', loadingOnline: 'Indlæser online-sikkerhedskopier…',
    noLocal: 'Ingen lokale sikkerhedskopier', firstLocal: 'Opret din første lokale sikkerhedskopi på denne pc',
    noOnline: 'Ingen online-sikkerhedskopier', firstOnline: 'Opret en online-sikkerhedskopi for at synkronisere filer med skyen',
    olderBackups: 'Tidligere sikkerhedskopier (type ikke angivet)', nameRequired: 'Angiv et navn til sikkerhedskopien',
    deleteConfirm: 'Er du sikker på, at du vil slette denne sikkerhedskopi?',
    restoreConfirm: 'Er du sikker på, at du vil gendanne denne sikkerhedskopi? Ikke-gemte ændringer går tabt.',
    created: '{type} sikkerhedskopi oprettet!', savingLocal: 'Gemmer sikkerhedskopi lokalt…',
    savedLocal: 'Sikkerhedskopi gemt lokalt!', createError: 'Fejl ved oprettelse af sikkerhedskopi: {error}',
    deleted: 'Sikkerhedskopi slettet!', deleteError: 'Fejl ved sletning af sikkerhedskopi: {error}',
    restored: 'Sikkerhedskopi gendannet!', restoreError: 'Fejl ved gendannelse af sikkerhedskopi: {error}',
    localCreated: 'Lokal sikkerhedskopi oprettet!', localDeleted: 'Lokal sikkerhedskopi slettet!', localRestored: 'Lokal sikkerhedskopi gendannet!',
    restoreLabel: 'Gendan sikkerhedskopi', deleteLabel: 'Slet sikkerhedskopi',
  },
  no: {
    panelTitle: 'Administrer sikkerhetskopier', panelDescription: '10 lokale sikkerhetskopier på denne PC-en + 2 på nettet — alltid tilgang til filene dine',
    encryptedBy: 'Kryptert av', createBackup: 'Opprett sikkerhetskopi', newBackup: 'Opprett ny sikkerhetskopi',
    createDescription: 'Lagre prosjektets tilstand. Velg lokal lagring (PC) eller på nettet (sky).',
    backupType: 'Type sikkerhetskopi', local: 'Lokal', online: 'På nettet', name: 'Navn på sikkerhetskopi *',
    namePlaceholder: 'f.eks. Stabil versjon 1.0', description: 'Beskrivelse (valgfritt)',
    descriptionPlaceholder: 'Legg til en beskrivelse så du husker innholdet…', cancel: 'Avbryt',
    creating: 'Oppretter…', localBackups: 'Lokale', onlineBackups: 'På nettet',
    loading: 'Laster sikkerhetskopier…', loadingOnline: 'Laster sikkerhetskopier på nettet…',
    noLocal: 'Ingen lokale sikkerhetskopier', firstLocal: 'Opprett din første lokale sikkerhetskopi på denne PC-en',
    noOnline: 'Ingen sikkerhetskopier på nettet', firstOnline: 'Opprett en sikkerhetskopi på nettet for å synkronisere filer med skyen',
    olderBackups: 'Tidligere sikkerhetskopier (type ikke angitt)', nameRequired: 'Skriv inn et navn på sikkerhetskopien',
    deleteConfirm: 'Vil du slette denne sikkerhetskopien?',
    restoreConfirm: 'Vil du gjenopprette denne sikkerhetskopien? Ulagrede endringer går tapt.',
    created: '{type} sikkerhetskopi opprettet!', savingLocal: 'Lagrer sikkerhetskopi lokalt…',
    savedLocal: 'Sikkerhetskopi lagret lokalt!', createError: 'Feil ved oppretting av sikkerhetskopi: {error}',
    deleted: 'Sikkerhetskopi slettet!', deleteError: 'Feil ved sletting av sikkerhetskopi: {error}',
    restored: 'Sikkerhetskopi gjenopprettet!', restoreError: 'Feil ved gjenoppretting av sikkerhetskopi: {error}',
    localCreated: 'Lokal sikkerhetskopi opprettet!', localDeleted: 'Lokal sikkerhetskopi slettet!', localRestored: 'Lokal sikkerhetskopi gjenopprettet!',
    restoreLabel: 'Gjenopprett sikkerhetskopi', deleteLabel: 'Slett sikkerhetskopi',
  },
  fi: {
    panelTitle: 'Varmuuskopioiden hallinta', panelDescription: '10 paikallista varmuuskopiota tällä tietokoneella + 2 verkossa — tiedostosi ovat aina käytettävissä',
    encryptedBy: 'Salauksen tarjoaa', createBackup: 'Luo varmuuskopio', newBackup: 'Luo uusi varmuuskopio',
    createDescription: 'Tallenna projektin tila. Valitse paikallinen tallennus (tietokone) tai verkkotallennus (pilvi).',
    backupType: 'Varmuuskopion tyyppi', local: 'Paikallinen', online: 'Verkossa', name: 'Varmuuskopion nimi *',
    namePlaceholder: 'esim. Vakaa versio 1.0', description: 'Kuvaus (valinnainen)',
    descriptionPlaceholder: 'Lisää kuvaus, jotta muistat sisällön…', cancel: 'Peruuta',
    creating: 'Luodaan…', localBackups: 'Paikalliset', onlineBackups: 'Verkossa',
    loading: 'Ladataan varmuuskopioita…', loadingOnline: 'Ladataan verkkovarmuuskopioita…',
    noLocal: 'Paikallisia varmuuskopioita ei ole', firstLocal: 'Luo ensimmäinen paikallinen varmuuskopio tälle tietokoneelle',
    noOnline: 'Verkkovarmuuskopioita ei ole', firstOnline: 'Luo verkkovarmuuskopio tiedostojen synkronoimiseksi pilveen',
    olderBackups: 'Aiemmat varmuuskopiot (tyyppiä ei määritetty)', nameRequired: 'Anna varmuuskopiolle nimi',
    deleteConfirm: 'Haluatko varmasti poistaa tämän varmuuskopion?',
    restoreConfirm: 'Haluatko varmasti palauttaa tämän varmuuskopion? Tallentamattomat muutokset menetetään.',
    created: '{type}-varmuuskopio luotu onnistuneesti!', savingLocal: 'Tallennetaan varmuuskopiota paikallisesti…',
    savedLocal: 'Varmuuskopio tallennettu paikallisesti!', createError: 'Varmuuskopion luontivirhe: {error}',
    deleted: 'Varmuuskopio poistettu!', deleteError: 'Varmuuskopion poistovirhe: {error}',
    restored: 'Varmuuskopio palautettu!', restoreError: 'Varmuuskopion palautusvirhe: {error}',
    localCreated: 'Paikallinen varmuuskopio luotu!', localDeleted: 'Paikallinen varmuuskopio poistettu!', localRestored: 'Paikallinen varmuuskopio palautettu!',
    restoreLabel: 'Palauta varmuuskopio', deleteLabel: 'Poista varmuuskopio',
  },
  uk: {
    panelTitle: 'Керування резервними копіями', panelDescription: '10 локальних копій на цьому ПК + 2 онлайн-копії — файли завжди доступні',
    encryptedBy: 'Зашифровано', createBackup: 'Створити резервну копію', newBackup: 'Створити нову копію',
    createDescription: 'Збережіть стан проєкту. Виберіть локальне збереження (ПК) або онлайн (хмара).',
    backupType: 'Тип резервної копії', local: 'Локальна', online: 'Онлайн', name: 'Назва копії *',
    namePlaceholder: 'наприклад, стабільна версія 1.0', description: 'Опис (необов’язково)',
    descriptionPlaceholder: 'Додайте опис, щоб пам’ятати вміст…', cancel: 'Скасувати',
    creating: 'Створення…', localBackups: 'Локальні', onlineBackups: 'Онлайн',
    loading: 'Завантаження резервних копій…', loadingOnline: 'Завантаження онлайн-копій…',
    noLocal: 'Локальних копій немає', firstLocal: 'Створіть першу локальну копію на цьому ПК',
    noOnline: 'Онлайн-копій немає', firstOnline: 'Створіть онлайн-копію, щоб синхронізувати файли з хмарою',
    olderBackups: 'Попередні копії (тип не вказано)', nameRequired: 'Введіть назву резервної копії',
    deleteConfirm: 'Ви впевнені, що хочете видалити цю резервну копію?',
    restoreConfirm: 'Ви впевнені, що хочете відновити цю копію? Незбережені зміни буде втрачено.',
    created: 'Резервну копію ({type}) створено!', savingLocal: 'Збереження копії локально…',
    savedLocal: 'Резервну копію збережено локально!', createError: 'Помилка створення резервної копії: {error}',
    deleted: 'Резервну копію видалено!', deleteError: 'Помилка видалення резервної копії: {error}',
    restored: 'Резервну копію відновлено!', restoreError: 'Помилка відновлення резервної копії: {error}',
    localCreated: 'Локальну копію створено!', localDeleted: 'Локальну копію видалено!', localRestored: 'Локальну копію відновлено!',
    restoreLabel: 'Відновити копію', deleteLabel: 'Видалити копію',
  },
  cs: {
    panelTitle: 'Správa záloh', panelDescription: '10 místních záloh na tomto počítači + 2 online zálohy — soubory máte vždy k dispozici',
    encryptedBy: 'Šifrování zajišťuje', createBackup: 'Vytvořit zálohu', newBackup: 'Vytvořit novou zálohu',
    createDescription: 'Uložte stav projektu. Vyberte místní uložení (počítač) nebo online (cloud).',
    backupType: 'Typ zálohy', local: 'Místní', online: 'Online', name: 'Název zálohy *',
    namePlaceholder: 'např. Stabilní verze 1.0', description: 'Popis (volitelný)',
    descriptionPlaceholder: 'Přidejte popis, abyste si zapamatovali obsah…', cancel: 'Zrušit',
    creating: 'Vytváření…', localBackups: 'Místní', onlineBackups: 'Online',
    loading: 'Načítání záloh…', loadingOnline: 'Načítání online záloh…',
    noLocal: 'Žádné místní zálohy', firstLocal: 'Vytvořte první místní zálohu na tomto počítači',
    noOnline: 'Žádné online zálohy', firstOnline: 'Vytvořte online zálohu a synchronizujte soubory s cloudem',
    olderBackups: 'Starší zálohy (typ není nastaven)', nameRequired: 'Zadejte název zálohy',
    deleteConfirm: 'Opravdu chcete tuto zálohu odstranit?',
    restoreConfirm: 'Opravdu chcete tuto zálohu obnovit? Neuložené změny budou ztraceny.',
    created: 'Záloha {type} byla vytvořena!', savingLocal: 'Ukládání zálohy místně…',
    savedLocal: 'Záloha byla uložena místně!', createError: 'Chyba při vytváření zálohy: {error}',
    deleted: 'Záloha byla odstraněna!', deleteError: 'Chyba při odstraňování zálohy: {error}',
    restored: 'Záloha byla obnovena!', restoreError: 'Chyba při obnovování zálohy: {error}',
    localCreated: 'Místní záloha byla vytvořena!', localDeleted: 'Místní záloha byla odstraněna!', localRestored: 'Místní záloha byla obnovena!',
    restoreLabel: 'Obnovit zálohu', deleteLabel: 'Odstranit zálohu',
  },
} as const;

export type EditorBackupLocale = keyof typeof backupCopy;
export type EditorBackupCopyKey = keyof typeof backupCopy.en;

export function getEditorBackupCopy(locale: EditorBackupLocale, key: EditorBackupCopyKey, values: Record<string, string | number> = {}): string {
  return backupCopy[locale][key].replace(/\{(\w+)\}/g, (_, name: string) => String(values[name] ?? `{${name}}`));
}
