const copy = {
  en: ['Quick templates', 'Choose a template and insert it into your editor', 'All', 'Insert', 'Copy', 'Code copied to clipboard!', 'Unable to copy the code.', 'Template "{name}" inserted!', 'Sponsored template offer', '[Sponsor] Template Pro Bundles — ideal for React & Tailwind', 'Bundles optimized for SEO, performance, and accessibility.', ['JavaScript Starter', 'TypeScript Starter', 'Python Starter', 'JSON Starter', 'SQL Starter', 'Java Starter', 'Responsive HTML', 'Gradient button'], ['Basic JavaScript class structure', 'Basic TypeScript structure with an interface', 'Basic Python class structure', 'Basic JSON file structure', 'Basic SQL structure with tables', 'Basic Java class structure', 'Basic responsive HTML structure', 'Button with a gradient and hover effect']],
  it: ['Template rapidi', 'Scegli un template e inseriscilo nell’editor', 'Tutti', 'Inserisci', 'Copia', 'Codice copiato negli appunti!', 'Impossibile copiare il codice.', 'Template "{name}" inserito!', 'Offerta sponsorizzata per template', '[Sponsor] Pacchetti Template Pro — ideali per React e Tailwind', 'Pacchetti ottimizzati per SEO, prestazioni e accessibilità.', ['Base JavaScript', 'Base TypeScript', 'Base Python', 'Base JSON', 'Base SQL', 'Base Java', 'HTML responsive', 'Pulsante sfumato'], ['Struttura base di una classe JavaScript', 'Struttura base di TypeScript con interfaccia', 'Struttura base di una classe Python', 'Struttura base di un file JSON', 'Struttura base SQL con tabelle', 'Struttura base di una classe Java', 'Struttura HTML responsive di base', 'Pulsante con sfumatura ed effetto hover']],
  es: ['Plantillas rápidas', 'Elige una plantilla e insértala en el editor', 'Todas', 'Insertar', 'Copiar', '¡Código copiado al portapapeles!', 'No se pudo copiar el código.', '¡Plantilla "{name}" insertada!', 'Oferta patrocinada de plantillas', '[Patrocinador] Paquetes Template Pro: ideales para React y Tailwind', 'Paquetes optimizados para SEO, rendimiento y accesibilidad.', ['Base de JavaScript', 'Base de TypeScript', 'Base de Python', 'Base de JSON', 'Base de SQL', 'Base de Java', 'HTML adaptable', 'Botón con degradado'], ['Estructura básica de una clase de JavaScript', 'Estructura básica de TypeScript con una interfaz', 'Estructura básica de una clase de Python', 'Estructura básica de un archivo JSON', 'Estructura básica de SQL con tablas', 'Estructura básica de una clase de Java', 'Estructura básica de HTML adaptable', 'Botón con degradado y efecto al pasar el cursor']],
  fr: ['Modèles rapides', 'Choisissez un modèle et insérez-le dans votre éditeur', 'Tous', 'Insérer', 'Copier', 'Code copié dans le presse-papiers !', 'Impossible de copier le code.', 'Modèle « {name} » inséré !', 'Offre de modèles sponsorisée', '[Sponsor] Packs Template Pro — idéaux pour React et Tailwind', 'Packs optimisés pour le SEO, les performances et l’accessibilité.', ['Base JavaScript', 'Base TypeScript', 'Base Python', 'Base JSON', 'Base SQL', 'Base Java', 'HTML adaptatif', 'Bouton dégradé'], ['Structure de base d’une classe JavaScript', 'Structure TypeScript de base avec interface', 'Structure de base d’une classe Python', 'Structure de base d’un fichier JSON', 'Structure SQL de base avec tables', 'Structure de base d’une classe Java', 'Structure HTML adaptative de base', 'Bouton avec dégradé et effet au survol']],
  de: ['Schnellvorlagen', 'Wähle eine Vorlage aus und füge sie in deinen Editor ein', 'Alle', 'Einfügen', 'Kopieren', 'Code in die Zwischenablage kopiert!', 'Code konnte nicht kopiert werden.', 'Vorlage „{name}“ eingefügt!', 'Gesponsertes Vorlagenangebot', '[Sponsor] Template-Pro-Pakete — ideal für React und Tailwind', 'Pakete, optimiert für SEO, Leistung und Barrierefreiheit.', ['JavaScript-Grundlage', 'TypeScript-Grundlage', 'Python-Grundlage', 'JSON-Grundlage', 'SQL-Grundlage', 'Java-Grundlage', 'Responsives HTML', 'Farbverlauf-Schaltfläche'], ['Grundstruktur einer JavaScript-Klasse', 'Grundstruktur für TypeScript mit Schnittstelle', 'Grundstruktur einer Python-Klasse', 'Grundstruktur einer JSON-Datei', 'SQL-Grundstruktur mit Tabellen', 'Grundstruktur einer Java-Klasse', 'Grundstruktur für responsives HTML', 'Schaltfläche mit Farbverlauf und Hover-Effekt']],
  pt: ['Templates rápidos', 'Escolha um template e insira-o no editor', 'Todos', 'Inserir', 'Copiar', 'Código copiado para a área de transferência!', 'Não foi possível copiar o código.', 'Template "{name}" inserido!', 'Oferta patrocinada de templates', '[Patrocinador] Pacotes Template Pro — ideais para React e Tailwind', 'Pacotes otimizados para SEO, desempenho e acessibilidade.', ['Base de JavaScript', 'Base de TypeScript', 'Base de Python', 'Base de JSON', 'Base de SQL', 'Base de Java', 'HTML responsivo', 'Botão com gradiente'], ['Estrutura básica de uma classe JavaScript', 'Estrutura básica de TypeScript com interface', 'Estrutura básica de uma classe Python', 'Estrutura básica de um arquivo JSON', 'Estrutura básica de SQL com tabelas', 'Estrutura básica de uma classe Java', 'Estrutura básica de HTML responsivo', 'Botão com gradiente e efeito ao passar o cursor']],
  ru: ['Быстрые шаблоны', 'Выберите шаблон и добавьте его в редактор', 'Все', 'Вставить', 'Копировать', 'Код скопирован в буфер обмена!', 'Не удалось скопировать код.', 'Шаблон «{name}» добавлен!', 'Рекламное предложение шаблонов', '[Реклама] Пакеты Template Pro — идеально для React и Tailwind', 'Пакеты, оптимизированные для SEO, производительности и доступности.', ['Основы JavaScript', 'Основы TypeScript', 'Основы Python', 'Основы JSON', 'Основы SQL', 'Основы Java', 'Адаптивный HTML', 'Градиентная кнопка'], ['Базовая структура класса JavaScript', 'Базовая структура TypeScript с интерфейсом', 'Базовая структура класса Python', 'Базовая структура файла JSON', 'Базовая структура SQL с таблицами', 'Базовая структура класса Java', 'Базовая структура адаптивного HTML', 'Кнопка с градиентом и эффектом при наведении']],
  zh: ['快速模板', '选择模板并将其插入编辑器', '全部', '插入', '复制', '代码已复制到剪贴板！', '无法复制代码。', '已插入模板“{name}”！', '赞助模板优惠', '[赞助商] Template Pro 套装 — 适用于 React 和 Tailwind', '针对 SEO、性能和无障碍体验优化的套装。', ['JavaScript 基础', 'TypeScript 基础', 'Python 基础', 'JSON 基础', 'SQL 基础', 'Java 基础', '响应式 HTML', '渐变按钮'], ['JavaScript 类的基本结构', '带接口的 TypeScript 基本结构', 'Python 类的基本结构', 'JSON 文件的基本结构', '带表的 SQL 基本结构', 'Java 类的基本结构', '响应式 HTML 基本结构', '带渐变和悬停效果的按钮']],
  ja: ['クイックテンプレート', 'テンプレートを選択してエディターに挿入します', 'すべて', '挿入', 'コピー', 'コードをクリップボードにコピーしました！', 'コードをコピーできませんでした。', 'テンプレート「{name}」を挿入しました！', 'テンプレートのスポンサー提供', '[スポンサー] Template Pro バンドル — React と Tailwind に最適', 'SEO、パフォーマンス、アクセシビリティに最適化されたバンドル。', ['JavaScript の基本', 'TypeScript の基本', 'Python の基本', 'JSON の基本', 'SQL の基本', 'Java の基本', 'レスポンシブ HTML', 'グラデーションボタン'], ['JavaScript クラスの基本構造', 'インターフェースを含む TypeScript の基本構造', 'Python クラスの基本構造', 'JSON ファイルの基本構造', 'テーブルを含む SQL の基本構造', 'Java クラスの基本構造', 'レスポンシブ HTML の基本構造', 'グラデーションとホバー効果のあるボタン']],
  ko: ['빠른 템플릿', '템플릿을 선택해 편집기에 삽입하세요', '전체', '삽입', '복사', '코드를 클립보드에 복사했습니다!', '코드를 복사할 수 없습니다.', '"{name}" 템플릿을 삽입했습니다!', '스폰서 템플릿 제안', '[스폰서] Template Pro 번들 — React 및 Tailwind에 적합', 'SEO, 성능 및 접근성에 최적화된 번들입니다.', ['JavaScript 기본', 'TypeScript 기본', 'Python 기본', 'JSON 기본', 'SQL 기본', 'Java 기본', '반응형 HTML', '그라데이션 버튼'], ['JavaScript 클래스 기본 구조', '인터페이스가 포함된 TypeScript 기본 구조', 'Python 클래스 기본 구조', 'JSON 파일 기본 구조', '테이블이 포함된 SQL 기본 구조', 'Java 클래스 기본 구조', '반응형 HTML 기본 구조', '그라데이션 및 마우스 오버 효과 버튼']],
  ar: ['قوالب سريعة', 'اختر قالبًا وأدرجه في المحرر', 'الكل', 'إدراج', 'نسخ', 'تم نسخ التعليمات البرمجية إلى الحافظة!', 'تعذّر نسخ التعليمات البرمجية.', 'تم إدراج القالب "{name}"!', 'عرض قوالب برعاية', '[راعي] حزم Template Pro — مثالية لـ React وTailwind', 'حزم محسّنة لتحسين محركات البحث والأداء وإمكانية الوصول.', ['أساسيات JavaScript', 'أساسيات TypeScript', 'أساسيات Python', 'أساسيات JSON', 'أساسيات SQL', 'أساسيات Java', 'HTML متجاوب', 'زر متدرج'], ['هيكل أساسي لفئة JavaScript', 'هيكل TypeScript أساسي مع واجهة', 'هيكل أساسي لفئة Python', 'هيكل أساسي لملف JSON', 'هيكل SQL أساسي مع جداول', 'هيكل أساسي لفئة Java', 'هيكل HTML متجاوب أساسي', 'زر بتدرج وتأثير عند المرور']],
  hi: ['त्वरित टेम्पलेट', 'टेम्पलेट चुनें और उसे संपादक में डालें', 'सभी', 'डालें', 'कॉपी करें', 'कोड क्लिपबोर्ड पर कॉपी किया गया!', 'कोड कॉपी नहीं हो सका।', '"{name}" टेम्पलेट डाला गया!', 'प्रायोजित टेम्पलेट ऑफ़र', '[प्रायोजक] Template Pro बंडल — React और Tailwind के लिए उपयुक्त', 'SEO, प्रदर्शन और सुलभता के लिए अनुकूलित बंडल।', ['JavaScript आधार', 'TypeScript आधार', 'Python आधार', 'JSON आधार', 'SQL आधार', 'Java आधार', 'उत्तरदायी HTML', 'ग्रेडिएंट बटन'], ['JavaScript क्लास की मूल संरचना', 'इंटरफ़ेस सहित TypeScript की मूल संरचना', 'Python क्लास की मूल संरचना', 'JSON फ़ाइल की मूल संरचना', 'टेबल सहित SQL की मूल संरचना', 'Java क्लास की मूल संरचना', 'उत्तरदायी HTML की मूल संरचना', 'ग्रेडिएंट और होवर प्रभाव वाला बटन']],
  pl: ['Szybkie szablony', 'Wybierz szablon i wstaw go do edytora', 'Wszystkie', 'Wstaw', 'Kopiuj', 'Kod skopiowano do schowka!', 'Nie można skopiować kodu.', 'Wstawiono szablon „{name}”!', 'Sponsorowana oferta szablonów', '[Sponsor] Pakiety Template Pro — idealne dla React i Tailwind', 'Pakiety zoptymalizowane pod kątem SEO, wydajności i dostępności.', ['Podstawy JavaScript', 'Podstawy TypeScript', 'Podstawy Python', 'Podstawy JSON', 'Podstawy SQL', 'Podstawy Java', 'Responsywny HTML', 'Przycisk gradientowy'], ['Podstawowa struktura klasy JavaScript', 'Podstawowa struktura TypeScript z interfejsem', 'Podstawowa struktura klasy Python', 'Podstawowa struktura pliku JSON', 'Podstawowa struktura SQL z tabelami', 'Podstawowa struktura klasy Java', 'Podstawowa struktura responsywnego HTML', 'Przycisk z gradientem i efektem najechania']],
  nl: ['Snelle templates', 'Kies een template en voeg deze in de editor in', 'Alle', 'Invoegen', 'Kopiëren', 'Code gekopieerd naar het klembord!', 'Kan de code niet kopiëren.', 'Template "{name}" ingevoegd!', 'Gesponsord template-aanbod', '[Sponsor] Template Pro-bundels — ideaal voor React en Tailwind', 'Bundels geoptimaliseerd voor SEO, prestaties en toegankelijkheid.', ['JavaScript-basis', 'TypeScript-basis', 'Python-basis', 'JSON-basis', 'SQL-basis', 'Java-basis', 'Responsieve HTML', 'Knop met kleurverloop'], ['Basisstructuur van een JavaScript-klasse', 'Basisstructuur van TypeScript met interface', 'Basisstructuur van een Python-klasse', 'Basisstructuur van een JSON-bestand', 'Basisstructuur van SQL met tabellen', 'Basisstructuur van een Java-klasse', 'Basisstructuur voor responsieve HTML', 'Knop met kleurverloop en hover-effect']],
  tr: ['Hızlı şablonlar', 'Bir şablon seçin ve düzenleyicinize ekleyin', 'Tümü', 'Ekle', 'Kopyala', 'Kod panoya kopyalandı!', 'Kod kopyalanamadı.', '"{name}" şablonu eklendi!', 'Sponsorlu şablon teklifi', '[Sponsor] Template Pro Paketleri — React ve Tailwind için ideal', 'SEO, performans ve erişilebilirlik için optimize edilmiş paketler.', ['JavaScript temeli', 'TypeScript temeli', 'Python temeli', 'JSON temeli', 'SQL temeli', 'Java temeli', 'Duyarlı HTML', 'Degrade düğme'], ['Temel JavaScript sınıf yapısı', 'Arayüz içeren temel TypeScript yapısı', 'Temel Python sınıf yapısı', 'Temel JSON dosya yapısı', 'Tablolarla temel SQL yapısı', 'Temel Java sınıf yapısı', 'Temel duyarlı HTML yapısı', 'Degrade ve üzerine gelme efektli düğme']],
  sv: ['Snabbmallar', 'Välj en mall och infoga den i redigeraren', 'Alla', 'Infoga', 'Kopiera', 'Koden har kopierats till urklipp!', 'Det gick inte att kopiera koden.', 'Mallen ”{name}” har infogats!', 'Sponsrat mallerbjudande', '[Sponsor] Template Pro-paket — perfekta för React och Tailwind', 'Paket optimerade för SEO, prestanda och tillgänglighet.', ['JavaScript-grund', 'TypeScript-grund', 'Python-grund', 'JSON-grund', 'SQL-grund', 'Java-grund', 'Responsiv HTML', 'Gradientknapp'], ['Grundläggande struktur för en JavaScript-klass', 'Grundläggande TypeScript-struktur med gränssnitt', 'Grundläggande struktur för en Python-klass', 'Grundläggande struktur för en JSON-fil', 'Grundläggande SQL-struktur med tabeller', 'Grundläggande struktur för en Java-klass', 'Grundläggande struktur för responsiv HTML', 'Knapp med gradient och hovringseffekt']],
  da: ['Hurtige skabeloner', 'Vælg en skabelon, og indsæt den i editoren', 'Alle', 'Indsæt', 'Kopiér', 'Koden er kopieret til udklipsholderen!', 'Koden kunne ikke kopieres.', 'Skabelonen "{name}" blev indsat!', 'Sponsoreret skabelontilbud', '[Sponsor] Template Pro-pakker — ideelle til React og Tailwind', 'Pakker optimeret til SEO, ydeevne og tilgængelighed.', ['JavaScript-grundlag', 'TypeScript-grundlag', 'Python-grundlag', 'JSON-grundlag', 'SQL-grundlag', 'Java-grundlag', 'Responsiv HTML', 'Knap med farveovergang'], ['Grundlæggende struktur for en JavaScript-klasse', 'Grundlæggende TypeScript-struktur med grænseflade', 'Grundlæggende struktur for en Python-klasse', 'Grundlæggende struktur for en JSON-fil', 'Grundlæggende SQL-struktur med tabeller', 'Grundlæggende struktur for en Java-klasse', 'Grundlæggende struktur for responsiv HTML', 'Knap med farveovergang og hover-effekt']],
  no: ['Hurtigmaler', 'Velg en mal og sett den inn i redigeringsprogrammet', 'Alle', 'Sett inn', 'Kopier', 'Koden er kopiert til utklippstavlen!', 'Kunne ikke kopiere koden.', 'Malen «{name}» er satt inn!', 'Sponset maltilbud', '[Sponsor] Template Pro-pakker — ideelle for React og Tailwind', 'Pakker optimalisert for SEO, ytelse og tilgjengelighet.', ['JavaScript-grunnlag', 'TypeScript-grunnlag', 'Python-grunnlag', 'JSON-grunnlag', 'SQL-grunnlag', 'Java-grunnlag', 'Responsiv HTML', 'Gradientknapp'], ['Grunnstruktur for en JavaScript-klasse', 'Grunnstruktur for TypeScript med grensesnitt', 'Grunnstruktur for en Python-klasse', 'Grunnstruktur for en JSON-fil', 'Grunnstruktur for SQL med tabeller', 'Grunnstruktur for en Java-klasse', 'Grunnstruktur for responsiv HTML', 'Knapp med gradient og hover-effekt']],
  fi: ['Pikamallit', 'Valitse malli ja lisää se editoriin', 'Kaikki', 'Lisää', 'Kopioi', 'Koodi kopioitiin leikepöydälle!', 'Koodin kopiointi epäonnistui.', 'Malli ”{name}” lisättiin!', 'Sponsoroitu mallitarjous', '[Sponsor] Template Pro -paketit — ihanteellisia Reactille ja Tailwindille', 'Paketit on optimoitu hakukoneille, suorituskyvylle ja esteettömyydelle.', ['JavaScript-perusta', 'TypeScript-perusta', 'Python-perusta', 'JSON-perusta', 'SQL-perusta', 'Java-perusta', 'Responsiivinen HTML', 'Liukuväripainike'], ['JavaScript-luokan perusrakenne', 'TypeScriptin perusrakenne käyttöliittymällä', 'Python-luokan perusrakenne', 'JSON-tiedoston perusrakenne', 'SQL:n perusrakenne tauluineen', 'Java-luokan perusrakenne', 'Responsiivisen HTML:n perusrakenne', 'Painike liukuvärillä ja hover-tehosteella']],
  uk: ['Швидкі шаблони', 'Виберіть шаблон і вставте його в редактор', 'Усі', 'Вставити', 'Копіювати', 'Код скопійовано до буфера обміну!', 'Не вдалося скопіювати код.', 'Шаблон «{name}» вставлено!', 'Рекламна пропозиція шаблонів', '[Реклама] Пакети Template Pro — ідеально для React і Tailwind', 'Пакети оптимізовано для SEO, продуктивності та доступності.', ['Основи JavaScript', 'Основи TypeScript', 'Основи Python', 'Основи JSON', 'Основи SQL', 'Основи Java', 'Адаптивний HTML', 'Градієнтна кнопка'], ['Базова структура класу JavaScript', 'Базова структура TypeScript з інтерфейсом', 'Базова структура класу Python', 'Базова структура файлу JSON', 'Базова структура SQL із таблицями', 'Базова структура класу Java', 'Базова структура адаптивного HTML', 'Кнопка з градієнтом та ефектом наведення']],
  cs: ['Rychlé šablony', 'Vyberte šablonu a vložte ji do editoru', 'Vše', 'Vložit', 'Kopírovat', 'Kód byl zkopírován do schránky!', 'Kód se nepodařilo zkopírovat.', 'Šablona „{name}“ byla vložena!', 'Sponzorovaná nabídka šablon', '[Sponzorováno] Balíčky Template Pro — ideální pro React a Tailwind', 'Balíčky optimalizované pro SEO, výkon a přístupnost.', ['Základy JavaScriptu', 'Základy TypeScriptu', 'Základy Pythonu', 'Základy JSON', 'Základy SQL', 'Základy Javy', 'Responzivní HTML', 'Tlačítko s přechodem'], ['Základní struktura třídy JavaScript', 'Základní struktura TypeScriptu s rozhraním', 'Základní struktura třídy Python', 'Základní struktura souboru JSON', 'Základní struktura SQL s tabulkami', 'Základní struktura třídy Java', 'Základní struktura responzivního HTML', 'Tlačítko s barevným přechodem a efektem při najetí']],
} as const;

export type EditorQuickTemplateLocale = keyof typeof copy;
export type EditorQuickTemplateId = 'js-base' | 'ts-base' | 'python-base' | 'json-base' | 'sql-base' | 'java-base' | 'html-responsive' | 'dark-button';
export type EditorQuickTemplateCopyKey = 'button' | 'description' | 'all' | 'insert' | 'copy' | 'copied' | 'copyError' | 'inserted' | 'sponsoredAria' | 'sponsoredTitle' | 'sponsoredDescription';

const keys: readonly EditorQuickTemplateCopyKey[] = ['button', 'description', 'all', 'insert', 'copy', 'copied', 'copyError', 'inserted', 'sponsoredAria', 'sponsoredTitle', 'sponsoredDescription'];

export function getEditorQuickTemplateCopy(locale: EditorQuickTemplateLocale, key: EditorQuickTemplateCopyKey, values: Record<string, string | number> = {}): string {
  const index = keys.indexOf(key);
  return (copy[locale][index] as string).replace(/\{(\w+)\}/g, (_, name: string) => String(values[name] ?? `{${name}}`));
}

const templateIds: readonly EditorQuickTemplateId[] = ['js-base', 'ts-base', 'python-base', 'json-base', 'sql-base', 'java-base', 'html-responsive', 'dark-button'];

export function getQuickTemplateContent(locale: EditorQuickTemplateLocale, id: EditorQuickTemplateId, field: 'name' | 'description'): string {
  const localized = copy[locale][field === 'name' ? 11 : 12] as readonly string[];
  return localized[templateIds.indexOf(id)] ?? id;
}
