type Locale = 'en' | 'it' | 'es' | 'fr' | 'de' | 'pt' | 'ru' | 'zh' | 'ja' | 'ko' | 'ar' | 'hi' | 'pl' | 'nl' | 'tr' | 'sv' | 'da' | 'no' | 'fi' | 'uk' | 'cs';
type LabelKey = 'expandPromo' | 'collapsePromo' | 'uploadFile' | 'openPurchasedTemplate' | 'uploadFolder' | 'noFileOpen' | 'backupManagement' | 'createManageBackup' | 'freeTrialLabel' | 'days' | 'plan' | 'fileDownloaded';

export const editorAppLabelFallbacks: Partial<Record<Locale, Partial<Record<LabelKey, string>>>> = {
  en: { expandPromo: 'Expand promotion', collapsePromo: 'Collapse promotion' },
  it: { expandPromo: 'Espandi promozione', collapsePromo: 'Comprimi promozione', uploadFile: 'Carica file' },
  es: { expandPromo: 'Expandir promoción', collapsePromo: 'Contraer promoción', uploadFile: 'Subir archivo' },
  fr: { expandPromo: 'Développer la promotion', collapsePromo: 'Réduire la promotion', uploadFile: 'Importer un fichier' },
  de: { expandPromo: 'Aktion ausklappen', collapsePromo: 'Aktion einklappen', uploadFile: 'Datei hochladen' },
  pt: { expandPromo: 'Expandir promoção', collapsePromo: 'Recolher promoção', uploadFile: 'Enviar arquivo' },
  ru: { expandPromo: 'Развернуть предложение', collapsePromo: 'Свернуть предложение', openPurchasedTemplate: 'Открыть купленный шаблон', uploadFolder: 'Загрузить папку (рекомендуется)', noFileOpen: 'Нет открытых файлов', backupManagement: 'Управление резервными копиями', createManageBackup: 'Создавайте резервные копии проекта и управляйте ими' },
  zh: { expandPromo: '展开优惠信息', collapsePromo: '收起优惠信息', openPurchasedTemplate: '打开已购模板', uploadFolder: '上传文件夹（推荐）', noFileOpen: '没有打开的文件', backupManagement: '备份管理', createManageBackup: '创建和管理项目备份' },
  ja: { expandPromo: 'プロモーションを展開', collapsePromo: 'プロモーションを折りたたむ', openPurchasedTemplate: '購入したテンプレートを開く', uploadFolder: 'フォルダーをアップロード（推奨）', noFileOpen: '開いているファイルはありません', backupManagement: 'バックアップ管理', createManageBackup: 'プロジェクトのバックアップを作成・管理します' },
  ko: { expandPromo: '프로모션 펼치기', collapsePromo: '프로모션 접기', openPurchasedTemplate: '구매한 템플릿 열기', uploadFolder: '폴더 업로드(권장)', noFileOpen: '열린 파일이 없습니다', backupManagement: '백업 관리', createManageBackup: '프로젝트 백업을 만들고 관리합니다' },
  ar: { expandPromo: 'توسيع العرض الترويجي', collapsePromo: 'طيّ العرض الترويجي' },
  hi: { expandPromo: 'प्रचार सामग्री फैलाएँ', collapsePromo: 'प्रचार सामग्री समेटें', freeTrialLabel: 'मुफ़्त परीक्षण', days: 'दिन', plan: 'प्लान: मुफ़्त', openPurchasedTemplate: 'खरीदा गया टेम्पलेट खोलें', uploadFolder: 'फ़ोल्डर अपलोड करें (अनुशंसित)', noFileOpen: 'कोई फ़ाइल खुली नहीं है', backupManagement: 'बैकअप प्रबंधन', createManageBackup: 'अपने प्रोजेक्ट के बैकअप बनाएँ और प्रबंधित करें', fileDownloaded: 'फ़ाइल डाउनलोड हो गई!' },
  pl: { expandPromo: 'Rozwiń promocję', collapsePromo: 'Zwiń promocję', openPurchasedTemplate: 'Otwórz kupiony szablon', uploadFolder: 'Prześlij folder (zalecane)', noFileOpen: 'Brak otwartych plików', backupManagement: 'Zarządzanie kopiami zapasowymi', createManageBackup: 'Twórz kopie zapasowe projektu i zarządzaj nimi' },
  nl: { expandPromo: 'Promotie uitklappen', collapsePromo: 'Promotie inklappen', freeTrialLabel: 'Gratis proefperiode', days: 'dagen', plan: 'Abonnement: GRATIS', openPurchasedTemplate: 'Gekochte template openen', uploadFolder: 'Map uploaden (aanbevolen)', noFileOpen: 'Geen bestand geopend', backupManagement: 'Back-upbeheer', createManageBackup: 'Maak back-ups van je project en beheer ze', fileDownloaded: 'Bestand gedownload!' },
  tr: { expandPromo: 'Tanıtımı genişlet', collapsePromo: 'Tanıtımı daralt', freeTrialLabel: 'Ücretsiz deneme', days: 'gün', plan: 'Plan: ÜCRETSİZ', openPurchasedTemplate: 'Satın alınan şablonu aç', uploadFolder: 'Klasör yükle (önerilir)', noFileOpen: 'Açık dosya yok', backupManagement: 'Yedek yönetimi', createManageBackup: 'Proje yedeklerinizi oluşturun ve yönetin', fileDownloaded: 'Dosya indirildi!' },
  sv: { expandPromo: 'Visa kampanj', collapsePromo: 'Dölj kampanj', openPurchasedTemplate: 'Öppna köpt mall', uploadFolder: 'Ladda upp mapp (rekommenderas)', noFileOpen: 'Ingen fil är öppen', backupManagement: 'Hantera säkerhetskopior', createManageBackup: 'Skapa och hantera säkerhetskopior av projektet', fileDownloaded: 'Filen har laddats ned!' },
  da: { expandPromo: 'Udvid kampagne', collapsePromo: 'Skjul kampagne', freeTrialLabel: 'Gratis prøveperiode', days: 'dage', plan: 'Abonnement: GRATIS' },
  no: { expandPromo: 'Utvid kampanje', collapsePromo: 'Skjul kampanje', freeTrialLabel: 'Gratis prøveperiode', days: 'dager', plan: 'Plan: GRATIS', openPurchasedTemplate: 'Åpne kjøpt mal', uploadFolder: 'Last opp mappe (anbefalt)', noFileOpen: 'Ingen fil er åpen', backupManagement: 'Administrer sikkerhetskopier', createManageBackup: 'Opprett og administrer sikkerhetskopier av prosjektet', fileDownloaded: 'Filen er lastet ned!' },
  fi: { expandPromo: 'Laajenna tarjous', collapsePromo: 'Pienennä tarjous', freeTrialLabel: 'Maksuton kokeilujakso', days: 'päivää', plan: 'Tilaus: ILMAINEN', openPurchasedTemplate: 'Avaa ostettu malli', uploadFolder: 'Lataa kansio (suositus)', noFileOpen: 'Tiedostoja ei ole avoinna', backupManagement: 'Varmuuskopioiden hallinta', createManageBackup: 'Luo projektin varmuuskopioita ja hallitse niitä', fileDownloaded: 'Tiedosto ladattiin!' },
  uk: { expandPromo: 'Розгорнути пропозицію', collapsePromo: 'Згорнути пропозицію', freeTrialLabel: 'Безкоштовний пробний період', days: 'днів', plan: 'План: БЕЗКОШТОВНО', openPurchasedTemplate: 'Відкрити придбаний шаблон', uploadFolder: 'Завантажити папку (рекомендовано)', noFileOpen: 'Немає відкритих файлів', backupManagement: 'Керування резервними копіями', createManageBackup: 'Створюйте резервні копії проєкту та керуйте ними', fileDownloaded: 'Файл завантажено!' },
  cs: { expandPromo: 'Rozbalit nabídku', collapsePromo: 'Sbalit nabídku', freeTrialLabel: 'Bezplatná zkušební verze', days: 'dní', plan: 'Plán: ZDARMA', openPurchasedTemplate: 'Otevřít zakoupenou šablonu', uploadFolder: 'Nahrát složku (doporučeno)', noFileOpen: 'Není otevřen žádný soubor', backupManagement: 'Správa záloh', createManageBackup: 'Vytvářejte a spravujte zálohy projektu', fileDownloaded: 'Soubor byl stažen!' },
};

export function getEditorAppLabelFallback(locale: Locale, key: LabelKey): string | undefined {
  return editorAppLabelFallbacks[locale]?.[key];
}
