import type { translations } from '@/lib/i18n';

const keys = [
  'backupButton', 'newBackup', 'backupHistory',
  'selectNextOccurrence', 'developerCourses',
  'previewSize', 'optimize', 'previewTitle', 'externalPreviewTitle',
  'nodeLabel',
  'configureTwoFactor', 'twoFactorTitle', 'scanQrDescription', 'qrCode', 'secretLabel', 'saveSecret',
  'codeLabel', 'verifying', 'verifyEnable', 'backupCodesTitle', 'backupCodesDescription', 'codesSaved',
  'loadingSecret', 'secretLoadError', 'retry', 'copyCode', 'twoFactorError', 'codeRequired',
  'newProjectTitle', 'createProjectDescription', 'addFilesDescription', 'projectName', 'projectPlaceholder',
  'characterCount', 'options', 'addFilesOptional', 'dragDropFiles', 'supportedFiles', 'selectedFiles',
  'back', 'addFiles', 'create', 'invalidFiles', 'projectNameRequired', 'projectNameTooLong', 'removeFile',
  'unknownFile',
  'categoryForm', 'categoryLayout', 'marketplaceTitle', 'marketplaceDescription', 'structuredDescription',
  'twoFactorEnabled',
] as const;

type CopyKey = (typeof keys)[number];
type CopyValues = readonly string[] & { readonly length: (typeof keys)['length'] };
type EditorOutsideLanguage = keyof typeof translations;

const values = {
  en: [
    'Backup', 'New backup', 'Backup history',
    'Select next occurrence', 'Developer courses',
    'Size: {size} KB', 'Optimize', 'Preview', 'External preview',
    'nodes',
    'Set up 2FA', 'Set up two-factor authentication', 'Scan the QR code with an authenticator app such as Google Authenticator.',
    'QR code', 'Secret key (backup)', 'Save this key somewhere safe. You can use it to recover access if you lose your device.',
    'Enter the 6-digit code', 'Verifying…', 'Verify and enable', 'Backup codes',
    'Save these codes somewhere safe. You can use them to sign in if you lose your device.', 'I have saved the codes',
    'Loading setup…', 'Could not load two-factor setup.', 'Try again', 'Copy code', 'Error: {error}', 'Enter the verification code.',
    'New project', 'Create a new project and start coding', 'Add files to your project (optional)', 'Project name *',
    'e.g. My Web App', '{count}/50 characters', 'Options', 'Add files (optional)', 'Drag files here or click to browse',
    'Supported: HTML, CSS, JS, JSON, XML, TXT, MD', 'Selected files ({count})', 'Back', 'Add files', 'Create project',
    '{count} unsupported file(s) (only .html, .css, .js, .json, .xml, .txt, .md)', 'Enter a project name.',
    'Project name cannot exceed 50 characters.', 'Remove file', 'Unknown file',
    'Forms', 'Layouts', 'Template Marketplace — React, HTML and Tailwind templates',
    'Download professional templates for React, Next.js, HTML and CSS. Templates optimized for SEO, accessibility and Core Web Vitals.',
    'Professional templates for developers: React, HTML, CSS and Tailwind.',
    'Two-factor authentication enabled!',
  ],
  it: [
    'Backup', 'Nuovo backup', 'Cronologia backup',
    'Seleziona l’occorrenza successiva', 'Corsi per sviluppatori',
    'Dimensione: {size} KB', 'Ottimizza', 'Anteprima', 'Anteprima esterna',
    'nodi',
    'Configura 2FA', 'Configura l’autenticazione a due fattori', 'Scansiona il codice QR con un’app di autenticazione come Google Authenticator.',
    'Codice QR', 'Chiave segreta (backup)', 'Salva questa chiave in un posto sicuro. Potrai usarla per recuperare l’accesso se perdi il dispositivo.',
    'Inserisci il codice a 6 cifre', 'Verifica in corso…', 'Verifica e abilita', 'Codici di backup',
    'Salva questi codici in un posto sicuro. Potrai usarli per accedere se perdi il dispositivo.', 'Ho salvato i codici',
    'Caricamento configurazione…', 'Impossibile caricare la configurazione della verifica in due passaggi.', 'Riprova', 'Copia codice', 'Errore: {error}', 'Inserisci il codice di verifica.',
    'Nuovo progetto', 'Crea un nuovo progetto e inizia a codificare', 'Aggiungi file al progetto (opzionale)', 'Nome progetto *',
    'Es. My Web App', '{count}/50 caratteri', 'Opzioni', 'Aggiungi file (opzionale)', 'Trascina qui i file o clicca per selezionarli',
    'Supportati: HTML, CSS, JS, JSON, XML, TXT, MD', 'File selezionati ({count})', 'Indietro', 'Aggiungi file', 'Crea progetto',
    '{count} file non supportati (solo .html, .css, .js, .json, .xml, .txt, .md)', 'Inserisci un nome per il progetto.',
    'Il nome del progetto non può superare 50 caratteri.', 'Rimuovi file', 'File sconosciuto',
    'Moduli', 'Layout', 'Marketplace di template — template React, HTML e Tailwind',
    'Scarica template professionali per React, Next.js, HTML e CSS. Template ottimizzati per SEO, accessibilità e Core Web Vitals.',
    'Template professionali per sviluppatori: React, HTML, CSS e Tailwind.',
    'Autenticazione a due fattori abilitata!',
  ],
  es: [
    'Copia de seguridad', 'Nueva copia de seguridad', 'Historial de copias de seguridad',
    'Seleccionar la siguiente coincidencia', 'Cursos para desarrolladores',
    'Tamaño: {size} KB', 'Optimizar', 'Vista previa', 'Vista previa externa',
    'nodos',
    'Configurar 2FA', 'Configurar la autenticación de dos factores', 'Escanea el código QR con una aplicación de autenticación como Google Authenticator.',
    'Código QR', 'Clave secreta (copia de seguridad)', 'Guarda esta clave en un lugar seguro. Puedes usarla para recuperar el acceso si pierdes el dispositivo.',
    'Introduce el código de 6 dígitos', 'Verificando…', 'Verificar y activar', 'Códigos de recuperación',
    'Guarda estos códigos en un lugar seguro. Puedes usarlos para iniciar sesión si pierdes el dispositivo.', 'He guardado los códigos',
    'Cargando configuración…', 'No se pudo cargar la configuración de la autenticación de dos factores.', 'Reintentar', 'Copiar código', 'Error: {error}', 'Introduce el código de verificación.',
    'Nuevo proyecto', 'Crea un proyecto y empieza a programar', 'Añade archivos al proyecto (opcional)', 'Nombre del proyecto *',
    'Ej.: My Web App', '{count}/50 caracteres', 'Opciones', 'Añadir archivos (opcional)', 'Arrastra archivos aquí o haz clic para seleccionarlos',
    'Admitidos: HTML, CSS, JS, JSON, XML, TXT, MD', 'Archivos seleccionados ({count})', 'Volver', 'Añadir archivos', 'Crear proyecto',
    '{count} archivo(s) no admitido(s) (solo .html, .css, .js, .json, .xml, .txt, .md)', 'Introduce un nombre para el proyecto.',
    'El nombre del proyecto no puede superar los 50 caracteres.', 'Quitar archivo', 'Archivo desconocido',
    'Formularios', 'Diseños', 'Marketplace de plantillas — plantillas para React, HTML y Tailwind',
    'Descarga plantillas profesionales para React, Next.js, HTML y CSS. Plantillas optimizadas para SEO, accesibilidad y Core Web Vitals.',
    'Plantillas profesionales para desarrolladores: React, HTML, CSS y Tailwind.',
    '¡Autenticación de dos factores activada!',
  ],
  fr: [
    'Sauvegarde', 'Nouvelle sauvegarde', 'Historique des sauvegardes',
    'Sélectionner l’occurrence suivante', 'Cours pour développeurs',
    'Taille : {size} Ko', 'Optimiser', 'Aperçu', 'Aperçu externe',
    'nœuds',
    'Configurer la 2FA', 'Configurer l’authentification à deux facteurs', 'Scannez le code QR avec une application d’authentification telle que Google Authenticator.',
    'Code QR', 'Clé secrète (sauvegarde)', 'Conservez cette clé dans un endroit sûr. Elle vous permettra de récupérer l’accès si vous perdez votre appareil.',
    'Saisissez le code à 6 chiffres', 'Vérification…', 'Vérifier et activer', 'Codes de secours',
    'Conservez ces codes dans un endroit sûr. Ils vous permettront de vous connecter si vous perdez votre appareil.', 'J’ai enregistré les codes',
    'Chargement de la configuration…', 'Impossible de charger la configuration de l’authentification à deux facteurs.', 'Réessayer', 'Copier le code', 'Erreur : {error}', 'Saisissez le code de vérification.',
    'Nouveau projet', 'Créez un projet et commencez à coder', 'Ajouter des fichiers au projet (facultatif)', 'Nom du projet *',
    'Ex. : My Web App', '{count}/50 caractères', 'Options', 'Ajouter des fichiers (facultatif)', 'Déposez les fichiers ici ou cliquez pour les choisir',
    'Formats acceptés : HTML, CSS, JS, JSON, XML, TXT, MD', 'Fichiers sélectionnés ({count})', 'Retour', 'Ajouter des fichiers', 'Créer le projet',
    '{count} fichier(s) non pris en charge (seuls .html, .css, .js, .json, .xml, .txt, .md)', 'Saisissez un nom de projet.',
    'Le nom du projet ne peut pas dépasser 50 caractères.', 'Supprimer le fichier', 'Fichier inconnu',
    'Formulaires', 'Mises en page', 'Marketplace de modèles — modèles React, HTML et Tailwind',
    'Téléchargez des modèles professionnels pour React, Next.js, HTML et CSS. Modèles optimisés pour le SEO, l’accessibilité et les Core Web Vitals.',
    'Modèles professionnels pour développeurs : React, HTML, CSS et Tailwind.',
    'Authentification à deux facteurs activée !',
  ],
  de: [
    'Backup', 'Neues Backup', 'Backup-Verlauf',
    'Nächstes Vorkommen auswählen', 'Kurse für Entwickler',
    'Größe: {size} KB', 'Optimieren', 'Vorschau', 'Externe Vorschau',
    'Knoten',
    '2FA einrichten', 'Zwei-Faktor-Authentifizierung einrichten', 'Scanne den QR-Code mit einer Authentifizierungs-App wie Google Authenticator.',
    'QR-Code', 'Geheimer Schlüssel (Backup)', 'Bewahre diesen Schlüssel sicher auf. Du kannst damit den Zugriff wiederherstellen, wenn du dein Gerät verlierst.',
    'Gib den 6-stelligen Code ein', 'Überprüfung läuft…', 'Überprüfen und aktivieren', 'Backup-Codes',
    'Bewahre diese Codes sicher auf. Mit ihnen kannst du dich anmelden, falls du dein Gerät verlierst.', 'Ich habe die Codes gespeichert',
    'Einrichtung wird geladen…', 'Die Einrichtung der Zwei-Faktor-Authentifizierung konnte nicht geladen werden.', 'Erneut versuchen', 'Code kopieren', 'Fehler: {error}', 'Gib den Bestätigungscode ein.',
    'Neues Projekt', 'Erstelle ein Projekt und beginne mit dem Programmieren', 'Dateien zum Projekt hinzufügen (optional)', 'Projektname *',
    'z. B. My Web App', '{count}/50 Zeichen', 'Optionen', 'Dateien hinzufügen (optional)', 'Dateien hierher ziehen oder zum Auswählen klicken',
    'Unterstützt: HTML, CSS, JS, JSON, XML, TXT, MD', 'Ausgewählte Dateien ({count})', 'Zurück', 'Dateien hinzufügen', 'Projekt erstellen',
    '{count} nicht unterstützte Datei(en) (nur .html, .css, .js, .json, .xml, .txt, .md)', 'Gib einen Projektnamen ein.',
    'Der Projektname darf höchstens 50 Zeichen lang sein.', 'Datei entfernen', 'Unbekannte Datei',
    'Formulare', 'Layouts', 'Template-Marktplatz — React-, HTML- und Tailwind-Vorlagen',
    'Lade professionelle Vorlagen für React, Next.js, HTML und CSS herunter. Vorlagen, optimiert für SEO, Barrierefreiheit und Core Web Vitals.',
    'Professionelle Vorlagen für Entwickler: React, HTML, CSS und Tailwind.',
    'Zwei-Faktor-Authentifizierung aktiviert!',
  ],
  pt: [
    'Backup', 'Novo backup', 'Histórico de backups',
    'Selecionar próxima ocorrência', 'Cursos para programadores',
    'Tamanho: {size} KB', 'Otimizar', 'Pré-visualização', 'Pré-visualização externa',
    'nós',
    'Configurar 2FA', 'Configurar autenticação de dois fatores', 'Leia o código QR com uma aplicação de autenticação, como o Google Authenticator.',
    'Código QR', 'Chave secreta (backup)', 'Guarde esta chave num local seguro. Pode usá-la para recuperar o acesso se perder o dispositivo.',
    'Introduza o código de 6 dígitos', 'A verificar…', 'Verificar e ativar', 'Códigos de recuperação',
    'Guarde estes códigos num local seguro. Pode usá-los para iniciar sessão se perder o dispositivo.', 'Guardei os códigos',
    'A carregar configuração…', 'Não foi possível carregar a configuração da autenticação de dois fatores.', 'Tentar novamente', 'Copiar código', 'Erro: {error}', 'Introduza o código de verificação.',
    'Novo projeto', 'Crie um projeto e comece a programar', 'Adicione ficheiros ao projeto (opcional)', 'Nome do projeto *',
    'Ex.: My Web App', '{count}/50 caracteres', 'Opções', 'Adicionar ficheiros (opcional)', 'Arraste ficheiros para aqui ou clique para selecionar',
    'Suportados: HTML, CSS, JS, JSON, XML, TXT, MD', 'Ficheiros selecionados ({count})', 'Voltar', 'Adicionar ficheiros', 'Criar projeto',
    '{count} ficheiro(s) não suportado(s) (apenas .html, .css, .js, .json, .xml, .txt, .md)', 'Introduza um nome para o projeto.',
    'O nome do projeto não pode exceder 50 caracteres.', 'Remover ficheiro', 'Ficheiro desconhecido',
    'Formulários', 'Layouts', 'Marketplace de modelos — modelos para React, HTML e Tailwind',
    'Transfira modelos profissionais para React, Next.js, HTML e CSS. Modelos otimizados para SEO, acessibilidade e Core Web Vitals.',
    'Modelos profissionais para programadores: React, HTML, CSS e Tailwind.',
    'Autenticação de dois fatores ativada!',
  ],
  ru: [
    'Резервная копия', 'Создать резервную копию', 'История резервных копий',
    'Выбрать следующее совпадение', 'Курсы для разработчиков',
    'Размер: {size} КБ', 'Оптимизировать', 'Предпросмотр', 'Внешний предпросмотр',
    'узлов',
    'Настроить 2FA', 'Настройка двухфакторной аутентификации', 'Отсканируйте QR-код приложением для аутентификации, например Google Authenticator.',
    'QR-код', 'Секретный ключ (резервный)', 'Храните этот ключ в безопасном месте. Он поможет восстановить доступ при потере устройства.',
    'Введите 6-значный код', 'Проверка…', 'Проверить и включить', 'Резервные коды',
    'Храните эти коды в безопасном месте. Их можно использовать для входа при потере устройства.', 'Я сохранил(а) коды',
    'Загрузка настроек…', 'Не удалось загрузить настройку двухфакторной аутентификации.', 'Повторить', 'Скопировать код', 'Ошибка: {error}', 'Введите код подтверждения.',
    'Новый проект', 'Создайте проект и начните программировать', 'Добавьте файлы в проект (необязательно)', 'Название проекта *',
    'Например: My Web App', '{count}/50 символов', 'Параметры', 'Добавить файлы (необязательно)', 'Перетащите файлы сюда или нажмите, чтобы выбрать',
    'Поддерживаются: HTML, CSS, JS, JSON, XML, TXT, MD', 'Выбранные файлы ({count})', 'Назад', 'Добавить файлы', 'Создать проект',
    'Файлов не поддерживается: {count} (только .html, .css, .js, .json, .xml, .txt, .md)', 'Введите название проекта.',
    'Название проекта не должно превышать 50 символов.', 'Удалить файл', 'Неизвестный файл',
    'Формы', 'Макеты', 'Маркетплейс шаблонов — шаблоны React, HTML и Tailwind',
    'Скачайте профессиональные шаблоны для React, Next.js, HTML и CSS. Шаблоны оптимизированы для SEO, доступности и Core Web Vitals.',
    'Профессиональные шаблоны для разработчиков: React, HTML, CSS и Tailwind.',
    'Двухфакторная аутентификация включена!',
  ],
  zh: [
    '备份', '新建备份', '备份历史记录',
    '选择下一个匹配项', '开发者课程',
    '大小：{size} KB', '优化', '预览', '外部预览',
    '个节点',
    '设置双重验证', '设置双重身份验证', '使用 Google Authenticator 等身份验证应用扫描二维码。',
    '二维码', '密钥（备份）', '请将此密钥保存在安全的地方。若设备丢失，可使用它恢复访问权限。',
    '输入 6 位验证码', '正在验证…', '验证并启用', '备用代码',
    '请将这些代码保存在安全的地方。若设备丢失，可使用它们登录。', '我已保存代码',
    '正在加载设置…', '无法加载双重身份验证设置。', '重试', '复制代码', '错误：{error}', '请输入验证码。',
    '新建项目', '创建项目并开始编写代码', '向项目添加文件（可选）', '项目名称 *',
    '例如：My Web App', '{count}/50 个字符', '选项', '添加文件（可选）', '将文件拖到此处或点击选择',
    '支持：HTML、CSS、JS、JSON、XML、TXT、MD', '已选文件（{count}）', '返回', '添加文件', '创建项目',
    '{count} 个文件不受支持（仅支持 .html、.css、.js、.json、.xml、.txt、.md）', '请输入项目名称。',
    '项目名称不能超过 50 个字符。', '移除文件', '未知文件',
    '表单', '布局', '模板市场 — React、HTML 和 Tailwind 模板',
    '下载适用于 React、Next.js、HTML 和 CSS 的专业模板。模板针对 SEO、无障碍体验和 Core Web Vitals 进行了优化。',
    '面向开发者的专业模板：React、HTML、CSS 和 Tailwind。',
    '双重身份验证已启用！',
  ],
  ja: [
    'バックアップ', '新しいバックアップ', 'バックアップ履歴',
    '次の一致箇所を選択', '開発者向けコース',
    'サイズ: {size} KB', '最適化', 'プレビュー', '外部プレビュー',
    'ノード',
    '2FAを設定', '2要素認証を設定', 'Google Authenticator などの認証アプリでQRコードをスキャンしてください。',
    'QRコード', '秘密鍵（バックアップ）', 'このキーを安全な場所に保存してください。デバイスを紛失した場合にアクセスを復旧できます。',
    '6桁のコードを入力', '確認中…', '確認して有効にする', 'バックアップコード',
    'これらのコードを安全な場所に保存してください。デバイスを紛失した場合のサインインに使用できます。', 'コードを保存しました',
    '設定を読み込み中…', '2要素認証の設定を読み込めませんでした。', '再試行', 'コードをコピー', 'エラー: {error}', '確認コードを入力してください。',
    '新しいプロジェクト', '新しいプロジェクトを作成してコーディングを始めましょう', 'プロジェクトにファイルを追加（任意）', 'プロジェクト名 *',
    '例: My Web App', '{count}/50 文字', 'オプション', 'ファイルを追加（任意）', 'ここにファイルをドラッグするか、クリックして選択',
    '対応形式: HTML、CSS、JS、JSON、XML、TXT、MD', '選択したファイル（{count}）', '戻る', 'ファイルを追加', 'プロジェクトを作成',
    '未対応ファイル {count} 個（.html、.css、.js、.json、.xml、.txt、.md のみ）', 'プロジェクト名を入力してください。',
    'プロジェクト名は50文字以内にしてください。', 'ファイルを削除', '不明なファイル',
    'フォーム', 'レイアウト', 'テンプレートマーケットプレイス — React、HTML、Tailwind テンプレート',
    'React、Next.js、HTML、CSS 向けのプロフェッショナルなテンプレートをダウンロード。SEO、アクセシビリティ、Core Web Vitals に最適化されています。',
    '開発者向けのプロフェッショナルテンプレート: React、HTML、CSS、Tailwind。',
    '2要素認証が有効になりました！',
  ],
  ko: [
    '백업', '새 백업', '백업 기록',
    '다음 일치 항목 선택', '개발자 강좌',
    '크기: {size} KB', '최적화', '미리보기', '외부 미리보기',
    '노드',
    '2단계 인증 설정', '2단계 인증 설정', 'Google Authenticator와 같은 인증 앱으로 QR 코드를 스캔하세요.',
    'QR 코드', '비밀 키(백업)', '이 키를 안전한 곳에 저장하세요. 기기를 분실한 경우 액세스를 복구하는 데 사용할 수 있습니다.',
    '6자리 코드 입력', '확인 중…', '확인 및 활성화', '백업 코드',
    '이 코드를 안전한 곳에 저장하세요. 기기를 분실한 경우 로그인에 사용할 수 있습니다.', '코드를 저장했습니다',
    '설정 로드 중…', '2단계 인증 설정을 불러오지 못했습니다.', '다시 시도', '코드 복사', '오류: {error}', '인증 코드를 입력하세요.',
    '새 프로젝트', '프로젝트를 만들고 코딩을 시작하세요', '프로젝트에 파일 추가(선택 사항)', '프로젝트 이름 *',
    '예: My Web App', '{count}/50자', '옵션', '파일 추가(선택 사항)', '파일을 여기로 끌거나 클릭하여 선택',
    '지원 형식: HTML, CSS, JS, JSON, XML, TXT, MD', '선택한 파일({count})', '뒤로', '파일 추가', '프로젝트 만들기',
    '지원하지 않는 파일 {count}개(.html, .css, .js, .json, .xml, .txt, .md만 지원)', '프로젝트 이름을 입력하세요.',
    '프로젝트 이름은 50자를 초과할 수 없습니다.', '파일 제거', '알 수 없는 파일',
    '양식', '레이아웃', '템플릿 마켓플레이스 — React, HTML 및 Tailwind 템플릿',
    'React, Next.js, HTML 및 CSS용 전문 템플릿을 다운로드하세요. SEO, 접근성 및 Core Web Vitals에 최적화되어 있습니다.',
    '개발자를 위한 전문 템플릿: React, HTML, CSS 및 Tailwind.',
    '2단계 인증이 활성화되었습니다!',
  ],
  ar: [
    'نسخة احتياطية', 'نسخة احتياطية جديدة', 'سجل النسخ الاحتياطية',
    'تحديد التطابق التالي', 'دورات للمطورين',
    'الحجم: {size} كيلوبايت', 'تحسين', 'معاينة', 'معاينة خارجية',
    'عُقد',
    'إعداد المصادقة الثنائية', 'إعداد المصادقة الثنائية', 'امسح رمز QR باستخدام تطبيق مصادقة مثل Google Authenticator.',
    'رمز QR', 'المفتاح السري (نسخة احتياطية)', 'احفظ هذا المفتاح في مكان آمن. يمكنك استخدامه لاستعادة الوصول إذا فقدت جهازك.',
    'أدخل الرمز المكوّن من 6 أرقام', 'جارٍ التحقق…', 'تحقق وفعّل', 'رموز احتياطية',
    'احفظ هذه الرموز في مكان آمن. يمكنك استخدامها لتسجيل الدخول إذا فقدت جهازك.', 'حفظت الرموز',
    'جارٍ تحميل الإعداد…', 'تعذر تحميل إعداد المصادقة الثنائية.', 'إعادة المحاولة', 'نسخ الرمز', 'خطأ: {error}', 'أدخل رمز التحقق.',
    'مشروع جديد', 'أنشئ مشروعًا جديدًا وابدأ البرمجة', 'أضف ملفات إلى مشروعك (اختياري)', 'اسم المشروع *',
    'مثال: My Web App', '{count}/50 حرفًا', 'خيارات', 'إضافة ملفات (اختياري)', 'اسحب الملفات إلى هنا أو انقر لاختيارها',
    'الأنواع المدعومة: HTML وCSS وJS وJSON وXML وTXT وMD', 'الملفات المحددة ({count})', 'رجوع', 'إضافة ملفات', 'إنشاء المشروع',
    '{count} ملف غير مدعوم (الأنواع المسموحة: .html و.css و.js و.json و.xml و.txt و.md)', 'أدخل اسمًا للمشروع.',
    'يجب ألا يتجاوز اسم المشروع 50 حرفًا.', 'إزالة الملف', 'ملف غير معروف',
    'نماذج', 'تخطيطات', 'سوق القوالب — قوالب React وHTML وTailwind',
    'نزّل قوالب احترافية لـ React وNext.js وHTML وCSS. قوالب محسّنة لتحسين محركات البحث وإمكانية الوصول وCore Web Vitals.',
    'قوالب احترافية للمطورين: React وHTML وCSS وTailwind.',
    'تم تفعيل المصادقة الثنائية!',
  ],
  hi: [
    'बैकअप', 'नया बैकअप', 'बैकअप इतिहास',
    'अगला मिलान चुनें', 'डेवलपर पाठ्यक्रम',
    'आकार: {size} KB', 'अनुकूलित करें', 'पूर्वावलोकन', 'बाहरी पूर्वावलोकन',
    'नोड',
    '2FA सेट अप करें', 'दो-कारक प्रमाणीकरण सेट अप करें', 'Google Authenticator जैसे प्रमाणीकरण ऐप से QR कोड स्कैन करें।',
    'QR कोड', 'गुप्त कुंजी (बैकअप)', 'इस कुंजी को सुरक्षित स्थान पर सहेजें। डिवाइस खोने पर आप इससे पहुंच पुनर्प्राप्त कर सकते हैं।',
    '6-अंकीय कोड दर्ज करें', 'सत्यापित हो रहा है…', 'सत्यापित करें और सक्षम करें', 'बैकअप कोड',
    'इन कोड को सुरक्षित स्थान पर सहेजें। डिवाइस खोने पर इनसे साइन इन किया जा सकता है।', 'मैंने कोड सहेज लिए हैं',
    'सेटअप लोड हो रहा है…', 'दो-कारक प्रमाणीकरण सेटअप लोड नहीं हो सका।', 'फिर से प्रयास करें', 'कोड कॉपी करें', 'त्रुटि: {error}', 'सत्यापन कोड दर्ज करें।',
    'नया प्रोजेक्ट', 'नया प्रोजेक्ट बनाएं और कोडिंग शुरू करें', 'अपने प्रोजेक्ट में फ़ाइलें जोड़ें (वैकल्पिक)', 'प्रोजेक्ट का नाम *',
    'उदा. My Web App', '{count}/50 अक्षर', 'विकल्प', 'फ़ाइलें जोड़ें (वैकल्पिक)', 'फ़ाइलें यहां खींचें या चुनने के लिए क्लिक करें',
    'समर्थित: HTML, CSS, JS, JSON, XML, TXT, MD', 'चुनी गई फ़ाइलें ({count})', 'वापस', 'फ़ाइलें जोड़ें', 'प्रोजेक्ट बनाएं',
    '{count} असमर्थित फ़ाइलें (केवल .html, .css, .js, .json, .xml, .txt, .md)', 'प्रोजेक्ट का नाम दर्ज करें।',
    'प्रोजेक्ट का नाम 50 अक्षरों से अधिक नहीं हो सकता।', 'फ़ाइल हटाएं', 'अज्ञात फ़ाइल',
    'फ़ॉर्म', 'लेआउट', 'टेम्पलेट मार्केटप्लेस — React, HTML और Tailwind टेम्पलेट',
    'React, Next.js, HTML और CSS के लिए पेशेवर टेम्पलेट डाउनलोड करें। SEO, पहुंच-योग्यता और Core Web Vitals के लिए अनुकूलित टेम्पलेट।',
    'डेवलपर के लिए पेशेवर टेम्पलेट: React, HTML, CSS और Tailwind।',
    'दो-कारक प्रमाणीकरण सक्षम है!',
  ],
  pl: [
    'Kopia zapasowa', 'Nowa kopia zapasowa', 'Historia kopii zapasowych',
    'Wybierz następne wystąpienie', 'Kursy dla programistów',
    'Rozmiar: {size} KB', 'Optymalizuj', 'Podgląd', 'Podgląd zewnętrzny',
    'węzły',
    'Skonfiguruj 2FA', 'Skonfiguruj uwierzytelnianie dwuskładnikowe', 'Zeskanuj kod QR aplikacją uwierzytelniającą, np. Google Authenticator.',
    'Kod QR', 'Tajny klucz (kopia zapasowa)', 'Zapisz ten klucz w bezpiecznym miejscu. Możesz go użyć, aby odzyskać dostęp po utracie urządzenia.',
    'Wpisz 6-cyfrowy kod', 'Weryfikowanie…', 'Zweryfikuj i włącz', 'Kody zapasowe',
    'Zapisz te kody w bezpiecznym miejscu. Możesz ich użyć do logowania po utracie urządzenia.', 'Kody zostały zapisane',
    'Wczytywanie konfiguracji…', 'Nie udało się wczytać konfiguracji uwierzytelniania dwuskładnikowego.', 'Spróbuj ponownie', 'Kopiuj kod', 'Błąd: {error}', 'Wpisz kod weryfikacyjny.',
    'Nowy projekt', 'Utwórz projekt i zacznij kodować', 'Dodaj pliki do projektu (opcjonalnie)', 'Nazwa projektu *',
    'Np. My Web App', '{count}/50 znaków', 'Opcje', 'Dodaj pliki (opcjonalnie)', 'Przeciągnij pliki tutaj lub kliknij, aby je wybrać',
    'Obsługiwane: HTML, CSS, JS, JSON, XML, TXT, MD', 'Wybrane pliki ({count})', 'Wstecz', 'Dodaj pliki', 'Utwórz projekt',
    '{count} nieobsługiwanych plików (tylko .html, .css, .js, .json, .xml, .txt, .md)', 'Wpisz nazwę projektu.',
    'Nazwa projektu nie może przekraczać 50 znaków.', 'Usuń plik', 'Nieznany plik',
    'Formularze', 'Układy', 'Marketplace szablonów — szablony React, HTML i Tailwind',
    'Pobierz profesjonalne szablony dla React, Next.js, HTML i CSS. Szablony zoptymalizowane pod kątem SEO, dostępności i Core Web Vitals.',
    'Profesjonalne szablony dla programistów: React, HTML, CSS i Tailwind.',
    'Uwierzytelnianie dwuskładnikowe zostało włączone!',
  ],
  nl: [
    'Back-up', 'Nieuwe back-up', 'Back-upgeschiedenis',
    'Volgende overeenkomst selecteren', 'Cursussen voor ontwikkelaars',
    'Grootte: {size} KB', 'Optimaliseren', 'Voorbeeld', 'Extern voorbeeld',
    'knooppunten',
    '2FA instellen', 'Tweeledige verificatie instellen', 'Scan de QR-code met een verificatie-app zoals Google Authenticator.',
    'QR-code', 'Geheime sleutel (back-up)', 'Bewaar deze sleutel op een veilige plek. Je kunt hiermee toegang herstellen als je je apparaat verliest.',
    'Voer de code van 6 cijfers in', 'Bezig met verifiëren…', 'Verifiëren en inschakelen', 'Back-upcodes',
    'Bewaar deze codes op een veilige plek. Je kunt ze gebruiken om in te loggen als je je apparaat verliest.', 'Ik heb de codes opgeslagen',
    'Instellingen laden…', 'De configuratie voor tweestapsverificatie kan niet worden geladen.', 'Opnieuw proberen', 'Code kopiëren', 'Fout: {error}', 'Voer de verificatiecode in.',
    'Nieuw project', 'Maak een project en begin met coderen', 'Voeg bestanden toe aan je project (optioneel)', 'Projectnaam *',
    'Bijv. My Web App', '{count}/50 tekens', 'Opties', 'Bestanden toevoegen (optioneel)', 'Sleep bestanden hierheen of klik om ze te kiezen',
    'Ondersteund: HTML, CSS, JS, JSON, XML, TXT, MD', 'Geselecteerde bestanden ({count})', 'Terug', 'Bestanden toevoegen', 'Project maken',
    '{count} niet-ondersteunde bestanden (alleen .html, .css, .js, .json, .xml, .txt, .md)', 'Voer een projectnaam in.',
    'De projectnaam mag maximaal 50 tekens bevatten.', 'Bestand verwijderen', 'Onbekend bestand',
    'Formulieren', 'Lay-outs', 'Template-marktplaats — React-, HTML- en Tailwind-templates',
    'Download professionele templates voor React, Next.js, HTML en CSS. Templates geoptimaliseerd voor SEO, toegankelijkheid en Core Web Vitals.',
    'Professionele templates voor ontwikkelaars: React, HTML, CSS en Tailwind.',
    'Tweestapsverificatie is ingeschakeld!',
  ],
  tr: [
    'Yedek', 'Yeni yedek', 'Yedek geçmişi',
    'Sonraki eşleşmeyi seç', 'Geliştirici kursları',
    'Boyut: {size} KB', 'Optimize et', 'Önizleme', 'Harici önizleme',
    'düğüm',
    '2FA ayarla', 'İki faktörlü kimlik doğrulamayı ayarla', 'QR kodunu Google Authenticator gibi bir kimlik doğrulama uygulamasıyla tarayın.',
    'QR kodu', 'Gizli anahtar (yedek)', 'Bu anahtarı güvenli bir yerde saklayın. Cihazınızı kaybederseniz erişimi kurtarmak için kullanabilirsiniz.',
    '6 haneli kodu girin', 'Doğrulanıyor…', 'Doğrula ve etkinleştir', 'Yedek kodları',
    'Bu kodları güvenli bir yerde saklayın. Cihazınızı kaybederseniz oturum açmak için kullanabilirsiniz.', 'Kodları kaydettim',
    'Kurulum yükleniyor…', 'İki faktörlü kimlik doğrulama kurulumu yüklenemedi.', 'Yeniden dene', 'Kodu kopyala', 'Hata: {error}', 'Doğrulama kodunu girin.',
    'Yeni proje', 'Yeni bir proje oluşturup kodlamaya başlayın', 'Projenize dosya ekleyin (isteğe bağlı)', 'Proje adı *',
    'Örn. My Web App', '{count}/50 karakter', 'Seçenekler', 'Dosya ekle (isteğe bağlı)', 'Dosyaları buraya sürükleyin veya seçmek için tıklayın',
    'Desteklenenler: HTML, CSS, JS, JSON, XML, TXT, MD', 'Seçilen dosyalar ({count})', 'Geri', 'Dosya ekle', 'Proje oluştur',
    '{count} desteklenmeyen dosya (yalnızca .html, .css, .js, .json, .xml, .txt, .md)', 'Proje adı girin.',
    'Proje adı 50 karakteri aşamaz.', 'Dosyayı kaldır', 'Bilinmeyen dosya',
    'Formlar', 'Düzenler', 'Şablon pazarı — React, HTML ve Tailwind şablonları',
    'React, Next.js, HTML ve CSS için profesyonel şablonları indirin. SEO, erişilebilirlik ve Core Web Vitals için optimize edilmiş şablonlar.',
    'Geliştiriciler için profesyonel şablonlar: React, HTML, CSS ve Tailwind.',
    'İki faktörlü kimlik doğrulama etkinleştirildi!',
  ],
  sv: [
    'Säkerhetskopia', 'Ny säkerhetskopia', 'Historik för säkerhetskopior',
    'Välj nästa förekomst', 'Kurser för utvecklare',
    'Storlek: {size} KB', 'Optimera', 'Förhandsgranskning', 'Extern förhandsgranskning',
    'noder',
    'Konfigurera 2FA', 'Konfigurera tvåfaktorsautentisering', 'Skanna QR-koden med en autentiseringsapp, till exempel Google Authenticator.',
    'QR-kod', 'Hemlig nyckel (säkerhetskopia)', 'Spara nyckeln på en säker plats. Du kan använda den för att återställa åtkomsten om du förlorar enheten.',
    'Ange den 6-siffriga koden', 'Verifierar…', 'Verifiera och aktivera', 'Reservkoder',
    'Spara koderna på en säker plats. Du kan använda dem för att logga in om du förlorar enheten.', 'Jag har sparat koderna',
    'Läser in konfiguration…', 'Det gick inte att läsa in konfigurationen för tvåfaktorsautentisering.', 'Försök igen', 'Kopiera kod', 'Fel: {error}', 'Ange verifieringskoden.',
    'Nytt projekt', 'Skapa ett projekt och börja koda', 'Lägg till filer i projektet (valfritt)', 'Projektnamn *',
    'T.ex. My Web App', '{count}/50 tecken', 'Alternativ', 'Lägg till filer (valfritt)', 'Dra filer hit eller klicka för att välja',
    'Format som stöds: HTML, CSS, JS, JSON, XML, TXT, MD', 'Valda filer ({count})', 'Tillbaka', 'Lägg till filer', 'Skapa projekt',
    '{count} filer stöds inte (endast .html, .css, .js, .json, .xml, .txt, .md)', 'Ange ett projektnamn.',
    'Projektnamnet får vara högst 50 tecken.', 'Ta bort fil', 'Okänd fil',
    'Formulär', 'Layouter', 'Mallmarknad — mallar för React, HTML och Tailwind',
    'Ladda ned professionella mallar för React, Next.js, HTML och CSS. Mallar optimerade för SEO, tillgänglighet och Core Web Vitals.',
    'Professionella mallar för utvecklare: React, HTML, CSS och Tailwind.',
    'Tvåfaktorsautentisering har aktiverats!',
  ],
  da: [
    'Sikkerhedskopi', 'Ny sikkerhedskopi', 'Historik over sikkerhedskopier',
    'Vælg næste forekomst', 'Kurser for udviklere',
    'Størrelse: {size} KB', 'Optimér', 'Eksempelvisning', 'Ekstern eksempelvisning',
    'noder',
    'Konfigurer 2FA', 'Konfigurer tofaktorgodkendelse', 'Scan QR-koden med en godkendelsesapp som Google Authenticator.',
    'QR-kode', 'Hemmelig nøgle (sikkerhedskopi)', 'Gem denne nøgle et sikkert sted. Du kan bruge den til at gendanne adgangen, hvis du mister din enhed.',
    'Indtast den 6-cifrede kode', 'Bekræfter…', 'Bekræft og aktivér', 'Sikkerhedskoder',
    'Gem disse koder et sikkert sted. Du kan bruge dem til at logge ind, hvis du mister din enhed.', 'Jeg har gemt koderne',
    'Indlæser konfiguration…', 'Kunne ikke indlæse konfigurationen for tofaktorgodkendelse.', 'Prøv igen', 'Kopiér kode', 'Fejl: {error}', 'Indtast bekræftelseskoden.',
    'Nyt projekt', 'Opret et projekt, og begynd at kode', 'Føj filer til projektet (valgfrit)', 'Projektnavn *',
    'F.eks. My Web App', '{count}/50 tegn', 'Indstillinger', 'Tilføj filer (valgfrit)', 'Træk filer hertil, eller klik for at vælge',
    'Understøttet: HTML, CSS, JS, JSON, XML, TXT, MD', 'Valgte filer ({count})', 'Tilbage', 'Tilføj filer', 'Opret projekt',
    '{count} filer understøttes ikke (kun .html, .css, .js, .json, .xml, .txt, .md)', 'Indtast et projektnavn.',
    'Projektnavnet må højst være 50 tegn.', 'Fjern fil', 'Ukendt fil',
    'Formularer', 'Layouts', 'Skabelonmarked — skabeloner til React, HTML og Tailwind',
    'Download professionelle skabeloner til React, Next.js, HTML og CSS. Skabeloner optimeret til SEO, tilgængelighed og Core Web Vitals.',
    'Professionelle skabeloner til udviklere: React, HTML, CSS og Tailwind.',
    'Tofaktorgodkendelse er aktiveret!',
  ],
  no: [
    'Sikkerhetskopi', 'Ny sikkerhetskopi', 'Sikkerhetskopihistorikk',
    'Velg neste forekomst', 'Kurs for utviklere',
    'Størrelse: {size} KB', 'Optimaliser', 'Forhåndsvisning', 'Ekstern forhåndsvisning',
    'noder',
    'Konfigurer 2FA', 'Konfigurer tofaktorautentisering', 'Skann QR-koden med en autentiseringsapp som Google Authenticator.',
    'QR-kode', 'Hemmelig nøkkel (sikkerhetskopi)', 'Lagre denne nøkkelen på et trygt sted. Du kan bruke den til å gjenopprette tilgangen hvis du mister enheten.',
    'Skriv inn den 6-sifrede koden', 'Bekrefter…', 'Bekreft og aktiver', 'Reservekoder',
    'Lagre disse kodene på et trygt sted. Du kan bruke dem til å logge inn hvis du mister enheten.', 'Jeg har lagret kodene',
    'Laster inn oppsett…', 'Kunne ikke laste inn oppsettet for tofaktorautentisering.', 'Prøv igjen', 'Kopier kode', 'Feil: {error}', 'Skriv inn bekreftelseskoden.',
    'Nytt prosjekt', 'Opprett et prosjekt og begynn å kode', 'Legg til filer i prosjektet (valgfritt)', 'Prosjektnavn *',
    'F.eks. My Web App', '{count}/50 tegn', 'Alternativer', 'Legg til filer (valgfritt)', 'Dra filer hit eller klikk for å velge',
    'Støttet: HTML, CSS, JS, JSON, XML, TXT, MD', 'Valgte filer ({count})', 'Tilbake', 'Legg til filer', 'Opprett prosjekt',
    '{count} filer støttes ikke (bare .html, .css, .js, .json, .xml, .txt, .md)', 'Skriv inn et prosjektnavn.',
    'Prosjektnavnet kan ikke være lengre enn 50 tegn.', 'Fjern fil', 'Ukjent fil',
    'Skjemaer', 'Oppsett', 'Malmarkedsplass — maler for React, HTML og Tailwind',
    'Last ned profesjonelle maler for React, Next.js, HTML og CSS. Maler optimalisert for SEO, tilgjengelighet og Core Web Vitals.',
    'Profesjonelle maler for utviklere: React, HTML, CSS og Tailwind.',
    'Tofaktorautentisering er aktivert!',
  ],
  fi: [
    'Varmuuskopio', 'Uusi varmuuskopio', 'Varmuuskopiohistoria',
    'Valitse seuraava esiintymä', 'Kehittäjäkurssit',
    'Koko: {size} KB', 'Optimoi', 'Esikatselu', 'Ulkoinen esikatselu',
    'solmua',
    'Ota 2FA käyttöön', 'Määritä kaksivaiheinen tunnistautuminen', 'Skannaa QR-koodi tunnistautumissovelluksella, kuten Google Authenticatorilla.',
    'QR-koodi', 'Salainen avain (varmuuskopio)', 'Tallenna tämä avain turvalliseen paikkaan. Voit palauttaa sen avulla käyttöoikeuden, jos laitteesi katoaa.',
    'Anna 6-numeroinen koodi', 'Vahvistetaan…', 'Vahvista ja ota käyttöön', 'Varmuuskopiokoodit',
    'Tallenna nämä koodit turvalliseen paikkaan. Voit kirjautua niillä sisään, jos laitteesi katoaa.', 'Olen tallentanut koodit',
    'Ladataan asetuksia…', 'Kaksivaiheisen tunnistautumisen asetusten lataaminen epäonnistui.', 'Yritä uudelleen', 'Kopioi koodi', 'Virhe: {error}', 'Anna vahvistuskoodi.',
    'Uusi projekti', 'Luo uusi projekti ja aloita koodaaminen', 'Lisää tiedostoja projektiin (valinnainen)', 'Projektin nimi *',
    'Esim. My Web App', '{count}/50 merkkiä', 'Asetukset', 'Lisää tiedostoja (valinnainen)', 'Vedä tiedostot tähän tai valitse ne napsauttamalla',
    'Tuetut: HTML, CSS, JS, JSON, XML, TXT, MD', 'Valitut tiedostot ({count})', 'Takaisin', 'Lisää tiedostoja', 'Luo projekti',
    '{count} tiedostoa ei tueta (vain .html, .css, .js, .json, .xml, .txt, .md)', 'Anna projektin nimi.',
    'Projektin nimi voi olla enintään 50 merkkiä pitkä.', 'Poista tiedosto', 'Tuntematon tiedosto',
    'Lomakkeet', 'Asettelu', 'Mallimarkkinapaikka — React-, HTML- ja Tailwind-mallit',
    'Lataa ammattimaisia malleja Reactille, Next.js:lle, HTML:lle ja CSS:lle. Mallit on optimoitu hakukoneille, saavutettavuudelle ja Core Web Vitalsille.',
    'Ammattimaisia malleja kehittäjille: React, HTML, CSS ja Tailwind.',
    'Kaksivaiheinen tunnistautuminen on otettu käyttöön!',
  ],
  uk: [
    'Резервна копія', 'Створити резервну копію', 'Історія резервних копій',
    'Вибрати наступний збіг', 'Курси для розробників',
    'Розмір: {size} КБ', 'Оптимізувати', 'Попередній перегляд', 'Зовнішній попередній перегляд',
    'вузлів',
    'Налаштувати 2FA', 'Налаштування двофакторної автентифікації', 'Відскануйте QR-код за допомогою програми автентифікації, наприклад Google Authenticator.',
    'QR-код', 'Секретний ключ (резервний)', 'Збережіть цей ключ у безпечному місці. Він допоможе відновити доступ у разі втрати пристрою.',
    'Введіть 6-значний код', 'Перевірка…', 'Перевірити й увімкнути', 'Резервні коди',
    'Збережіть ці коди в безпечному місці. Їх можна використовувати для входу в разі втрати пристрою.', 'Я зберіг(ла) коди',
    'Завантаження налаштувань…', 'Не вдалося завантажити налаштування двофакторної автентифікації.', 'Повторити', 'Копіювати код', 'Помилка: {error}', 'Введіть код підтвердження.',
    'Новий проєкт', 'Створіть проєкт і почніть програмувати', 'Додайте файли до проєкту (необов’язково)', 'Назва проєкту *',
    'Напр.: My Web App', '{count}/50 символів', 'Параметри', 'Додати файли (необов’язково)', 'Перетягніть файли сюди або натисніть, щоб вибрати',
    'Підтримуються: HTML, CSS, JS, JSON, XML, TXT, MD', 'Вибрані файли ({count})', 'Назад', 'Додати файли', 'Створити проєкт',
    '{count} непідтримуваних файлів (лише .html, .css, .js, .json, .xml, .txt, .md)', 'Введіть назву проєкту.',
    'Назва проєкту не може перевищувати 50 символів.', 'Видалити файл', 'Невідомий файл',
    'Форми', 'Макети', 'Маркетплейс шаблонів — шаблони React, HTML і Tailwind',
    'Завантажуйте професійні шаблони для React, Next.js, HTML і CSS. Шаблони оптимізовані для SEO, доступності та Core Web Vitals.',
    'Професійні шаблони для розробників: React, HTML, CSS і Tailwind.',
    'Двофакторну автентифікацію ввімкнено!',
  ],
  cs: [
    'Záloha', 'Nová záloha', 'Historie záloh',
    'Vybrat další výskyt', 'Kurzy pro vývojáře',
    'Velikost: {size} KB', 'Optimalizovat', 'Náhled', 'Externí náhled',
    'uzly',
    'Nastavit 2FA', 'Nastavení dvoufázového ověření', 'Naskenujte QR kód ověřovací aplikací, například Google Authenticator.',
    'QR kód', 'Tajný klíč (záloha)', 'Uložte tento klíč na bezpečné místo. Pokud zařízení ztratíte, můžete pomocí něj obnovit přístup.',
    'Zadejte 6místný kód', 'Ověřování…', 'Ověřit a zapnout', 'Záložní kódy',
    'Uložte tyto kódy na bezpečné místo. Pokud zařízení ztratíte, můžete se pomocí nich přihlásit.', 'Kódy jsem uložil(a)',
    'Načítání nastavení…', 'Nastavení dvoufázového ověření se nepodařilo načíst.', 'Zkusit znovu', 'Kopírovat kód', 'Chyba: {error}', 'Zadejte ověřovací kód.',
    'Nový projekt', 'Vytvořte projekt a začněte programovat', 'Přidejte do projektu soubory (volitelné)', 'Název projektu *',
    'Např. My Web App', '{count}/50 znaků', 'Možnosti', 'Přidat soubory (volitelné)', 'Přetáhněte sem soubory nebo kliknutím vyberte',
    'Podporováno: HTML, CSS, JS, JSON, XML, TXT, MD', 'Vybrané soubory ({count})', 'Zpět', 'Přidat soubory', 'Vytvořit projekt',
    '{count} nepodporovaných souborů (pouze .html, .css, .js, .json, .xml, .txt, .md)', 'Zadejte název projektu.',
    'Název projektu nesmí být delší než 50 znaků.', 'Odebrat soubor', 'Neznámý soubor',
    'Formuláře', 'Rozvržení', 'Tržiště šablon — šablony React, HTML a Tailwind',
    'Stáhněte si profesionální šablony pro React, Next.js, HTML a CSS. Šablony optimalizované pro SEO, přístupnost a Core Web Vitals.',
    'Profesionální šablony pro vývojáře: React, HTML, CSS a Tailwind.',
    'Dvoufázové ověření bylo zapnuto!',
  ],
} satisfies Record<EditorOutsideLanguage, CopyValues>;

export type EditorOutsideCopyKey = CopyKey;

export function getEditorOutsideCopy(
  language: EditorOutsideLanguage,
  key: CopyKey,
  replacements: Record<string, string | number> = {},
): string {
  let text = values[language][keys.indexOf(key)];
  for (const [name, value] of Object.entries(replacements)) {
    text = text.replaceAll(`{${name}}`, String(value));
  }
  return text;
}
