import { describe, expect, it } from 'vitest';
import { detectLanguageFromExtension } from './fileTemplates';

describe('file extension language detection', () => {
  it.each([
    ['index.html', 'html'],
    ['page.htm', 'html'],
    ['styles.css', 'css'],
    ['styles.scss', 'css'],
    ['styles.sass', 'css'],
    ['styles.less', 'css'],
    ['app.js', 'javascript'],
    ['app.jsx', 'javascript'],
    ['app.ts', 'typescript'],
    ['app.tsx', 'typescript'],
    ['data.json', 'json'],
    ['feed.xml', 'xml'],
    ['App.vue', 'html'],
    ['App.svelte', 'html'],
    ['main.py', 'python'],
    ['Main.java', 'java'],
    ['main.c', 'cpp'],
    ['main.cpp', 'cpp'],
    ['main.cc', 'cpp'],
    ['main.cxx', 'cpp'],
    ['Main.cs', 'csharp'],
    ['script.php', 'php'],
    ['script.rb', 'ruby'],
    ['main.go', 'go'],
    ['main.rs', 'rust'],
    ['Main.kt', 'kotlin'],
    ['main.swift', 'swift'],
    ['main.m', 'cpp'],
    ['main.mm', 'cpp'],
    ['main.dart', 'plaintext'],
    ['main.lua', 'plaintext'],
    ['analysis.r', 'plaintext'],
    ['query.sql', 'sql'],
    ['README.md', 'markdown'],
    ['README.markdown', 'markdown'],
    ['config.yaml', 'yaml'],
    ['config.yml', 'yaml'],
    ['config.toml', 'plaintext'],
    ['config.ini', 'plaintext'],
    ['settings.conf', 'plaintext'],
    ['script.sh', 'shell'],
    ['script.bash', 'shell'],
    ['script.zsh', 'shell'],
    ['script.fish', 'shell'],
    ['Dockerfile', 'dockerfile'],
    ['Makefile', 'plaintext'],
  ])('maps %s to editor mode %s', (fileName, language) => {
    expect(detectLanguageFromExtension(fileName)).toBe(language);
  });
});
