export type FilesLanguage = keyof typeof import('@/lib/i18n').translations;

export interface FilesPageCopy {
  loginRequired: string;
  loginPrompt: string;
  login: string;
  pageTitle: string;
  pageSubtitle: string;
  uploadFolder: string;
  uploading: string;
  selectFolderTitle: string;
  copy: string;
  copySelectedTitle: string;
  move: string;
  moveSelectedTitle: string;
  paste: string;
  pasteTitle: string;
  delete: string;
  deleteSelectedTitle: string;
  loadedFolders: string;
  fileCount: string;
  openInEditorTitle: string;
  editor: string;
  copiedTemplate: string;
  download: string;
  purchasedTemplates: string;
  copyTitle: string;
  expires: string;
  noPurchasedTemplates: string;
  onlineBackup: string;
  loading: string;
  noBackups: string;
  downloadBackupTitle: string;
  fileDetails: string;
  name: string;
  size: string;
  type: string;
  lastModified: string;
  notAvailable: string;
  copyContent: string;
  clipboardCopyFailed: string;
  toast: {
    downloadedFile: string;
    copiedContent: string;
    copiedFile: string;
    readyToMove: string;
    nothingToPaste: string;
    copiedPaste: string;
    movedPaste: string;
    deleting: string;
    deletedFile: string;
    deleteFailed: string;
    missingProject: string;
    uploadedFile: string;
    uploadFailed: string;
    folderNotSelected: string;
    folderEmpty: string;
    loadingFolder: string;
    folderUploaded: string;
    folderUploadFailed: string;
    fileReadFailed: string;
    renamedFile: string;
    deletedExplorerFile: string;
    savedFile: string;
    savedFolder: string;
    copiedTemplate: string;
    copiedTemplateVisible: string;
    copyTemplateFailed: string;
    downloadedBackup: string;
  };
  explorer: {
    saveFile: string;
    renameFile: string;
    refreshPreview: string;
    closeFile: string;
    deleteFile: string;
    saveFolder: string;
    deleteFolder: string;
    closeFolder: string;
    closeSelectedFile: string;
    closeFolderNamed: string;
    renameDialog: string;
    newName: string;
    cancel: string;
    confirmDelete: string;
    confirmDeleteNamed: string;
    empty: string;
    expandFolder: string;
    collapseFolder: string;
  };
  green: {
    projectStats: string;
    filesLabel: string;
    linesLabel: string;
    editingLabel: string;
    sizeLabel: string;
    minutes: string;
    pricePeriod: string;
    tipHeading: string;
    offerHeading: string;
    seeMore: string;
    close: string;
    tips: [string, string][];
    dealDescriptions: [string, string, string];
  };
}

export const filesPageCopy: Record<FilesLanguage, FilesPageCopy> = {
  en: {
    loginRequired: 'Sign-in required', loginPrompt: 'Please sign in to manage your files and folders.', login: 'Sign in',
    pageTitle: 'File Management', pageSubtitle: 'Organize and manage your files and folders',
    uploadFolder: 'Upload Folder', uploading: 'Uploading...', selectFolderTitle: 'Select a folder to upload',
    copy: 'Copy', copySelectedTitle: 'Copy selected file', move: 'Move', moveSelectedTitle: 'Move selected file',
    paste: 'Paste', pasteTitle: 'Paste copied/moved file', delete: 'Delete', deleteSelectedTitle: 'Delete selected file',
    loadedFolders: 'Uploaded Folders', fileCount: 'files', openInEditorTitle: 'Open in File Editor', editor: 'Editor',
    copiedTemplate: 'Copied Template', download: 'Download', purchasedTemplates: 'Purchased Templates',
    copyTitle: 'Copy', expires: 'Expires:', noPurchasedTemplates: 'No templates purchased',
    onlineBackup: 'Online Backup', loading: 'Loading...', noBackups: 'No backups saved',
    downloadBackupTitle: 'Download backup', fileDetails: 'File Details', name: 'Name', size: 'Size',
    type: 'Type', lastModified: 'Last modified', notAvailable: 'N/A', copyContent: 'Copy Content',
    clipboardCopyFailed: 'Could not copy to the clipboard.',
    toast: {
      downloadedFile: 'File "{name}" downloaded!', copiedContent: 'Content copied to clipboard!',
      copiedFile: 'File "{name}" copied! Paste it wherever you like.', readyToMove: 'File "{name}" is ready to move!',
      nothingToPaste: 'Nothing to paste', copiedPaste: 'Copied "{name}"!', movedPaste: 'Moved "{name}"!',
      deleting: 'Deleting...', deletedFile: 'File "{name}" deleted!', deleteFailed: 'Error deleting file',
      missingProject: 'Error: no project available', uploadedFile: 'File "{name}" uploaded successfully!',
      uploadFailed: 'Error uploading "{name}"', folderNotSelected: 'Error: no folder selected',
      folderEmpty: 'The folder is empty or was not selected correctly',
      loadingFolder: 'Uploading folder "{name}"... ({count} files)',
      folderUploaded: '✅ Folder "{name}" uploaded: {count}/{total} files',
      folderUploadFailed: 'Error uploading folder', fileReadFailed: 'Could not read file "{name}"',
      renamedFile: 'File renamed!', deletedExplorerFile: 'File deleted!', savedFile: 'File saved!',
      savedFolder: 'Folder saved!', copiedTemplate: 'Template copied!',
      copiedTemplateVisible: 'Template copied! It is shown in the "Copied Template" section',
      copyTemplateFailed: 'Unable to copy the template.', downloadedBackup: 'Backup "{name}" downloaded!',
    },
    explorer: {
      saveFile: 'Save file', renameFile: 'Rename file', refreshPreview: 'Refresh preview',
      closeFile: 'Close file', deleteFile: 'Delete file', saveFolder: 'Save folder',
      deleteFolder: 'Delete folder', closeFolder: 'Close folder', closeSelectedFile: 'Close selected file',
      closeFolderNamed: 'Close folder {name}', renameDialog: 'Rename', newName: 'New name',
      cancel: 'Cancel', confirmDelete: 'Confirm deletion', confirmDeleteNamed: 'Are you sure you want to delete {name}?',
      empty: 'No files or folders yet.', expandFolder: 'Expand folder {name}', collapseFolder: 'Collapse folder {name}',
    },
    green: {
      projectStats: 'Project statistics', filesLabel: 'Files', linesLabel: 'Lines of code',
      editingLabel: 'Editing time', sizeLabel: 'Project size', minutes: 'min', pricePeriod: '/month',
      tipHeading: '💡 Tip of the Day', offerHeading: '🎁 Exclusive Offer', seeMore: '→ Learn more', close: 'Close',
      tips: [
        ['⚡ Quick Shortcut', 'Use Ctrl+K to open the command palette'],
        ['📁 Organize Files', 'Group files into folders for a better preview'],
        ['🚀 Templates', 'Use templates to get started faster'],
        ['🎨 Dark Theme', 'Perfect for long work sessions'],
        ['💾 Automatic Backup', 'Set up automatic backups for peace of mind'],
      ],
      dealDescriptions: ['Unlimited vulnerability scanning', 'API testing and collaboration', 'Real-time performance insights'],
    },
  },
  it: {
    loginRequired: 'Accesso richiesto', loginPrompt: 'Accedi per gestire file e cartelle.', login: 'Accedi',
    pageTitle: 'Gestione file', pageSubtitle: 'Organizza e gestisci i tuoi file e le tue cartelle',
    uploadFolder: 'Carica cartella', uploading: 'Caricamento...', selectFolderTitle: 'Seleziona una cartella da caricare',
    copy: 'Copia', copySelectedTitle: 'Copia il file selezionato', move: 'Sposta', moveSelectedTitle: 'Sposta il file selezionato',
    paste: 'Incolla', pasteTitle: 'Incolla il file copiato o spostato', delete: 'Elimina', deleteSelectedTitle: 'Elimina il file selezionato',
    loadedFolders: 'Cartelle caricate', fileCount: 'file', openInEditorTitle: 'Apri con File Editor', editor: 'Editor',
    copiedTemplate: 'Template copiato', download: 'Scarica', purchasedTemplates: 'Template acquistati',
    copyTitle: 'Copia', expires: 'Scade:', noPurchasedTemplates: 'Nessun template acquistato',
    onlineBackup: 'Backup online', loading: 'Caricamento...', noBackups: 'Nessun backup salvato',
    downloadBackupTitle: 'Scarica backup', fileDetails: 'Dettagli file', name: 'Nome', size: 'Dimensione',
    type: 'Tipo', lastModified: 'Ultima modifica', notAvailable: 'N/D', copyContent: 'Copia contenuto',
    clipboardCopyFailed: 'Impossibile copiare negli appunti.',
    toast: {
      downloadedFile: 'File "{name}" scaricato!', copiedContent: 'Contenuto copiato negli appunti!',
      copiedFile: 'File "{name}" copiato! Incollalo dove vuoi.', readyToMove: 'File "{name}" pronto per essere spostato!',
      nothingToPaste: 'Nulla da incollare', copiedPaste: 'File "{name}" copiato!', movedPaste: 'File "{name}" spostato!',
      deleting: 'Eliminazione...', deletedFile: 'File "{name}" eliminato!', deleteFailed: 'Errore durante l’eliminazione del file',
      missingProject: 'Errore: nessun progetto disponibile', uploadedFile: 'File "{name}" caricato con successo!',
      uploadFailed: 'Errore durante il caricamento di "{name}"', folderNotSelected: 'Errore: nessuna cartella selezionata',
      folderEmpty: 'La cartella è vuota o non è stata selezionata correttamente',
      loadingFolder: 'Caricamento della cartella "{name}"... ({count} file)',
      folderUploaded: '✅ Cartella "{name}" caricata: {count}/{total} file',
      folderUploadFailed: 'Errore durante il caricamento della cartella', fileReadFailed: 'Impossibile leggere il file "{name}"',
      renamedFile: 'File rinominato!', deletedExplorerFile: 'File eliminato!', savedFile: 'File salvato!',
      savedFolder: 'Cartella salvata!', copiedTemplate: 'Template copiato!',
      copiedTemplateVisible: 'Template copiato! È visibile nella sezione "Template copiato"',
      copyTemplateFailed: 'Impossibile copiare il template.', downloadedBackup: 'Backup "{name}" scaricato!',
    },
    explorer: {
      saveFile: 'Salva file', renameFile: 'Rinomina file', refreshPreview: 'Aggiorna anteprima',
      closeFile: 'Chiudi file', deleteFile: 'Elimina file', saveFolder: 'Salva cartella',
      deleteFolder: 'Elimina cartella', closeFolder: 'Chiudi cartella', closeSelectedFile: 'Chiudi file selezionato',
      closeFolderNamed: 'Chiudi cartella {name}', renameDialog: 'Rinomina', newName: 'Nuovo nome',
      cancel: 'Annulla', confirmDelete: 'Conferma eliminazione', confirmDeleteNamed: 'Vuoi davvero eliminare {name}?',
      empty: 'Nessun file o cartella.', expandFolder: 'Espandi cartella {name}', collapseFolder: 'Comprimi cartella {name}',
    },
    green: {
      projectStats: 'Statistiche del progetto', filesLabel: 'File', linesLabel: 'Righe di codice',
      editingLabel: 'Tempo di modifica', sizeLabel: 'Dimensione progetto', minutes: 'min', pricePeriod: '/mese',
      tipHeading: '💡 Consiglio del giorno', offerHeading: '🎁 Offerta esclusiva', seeMore: '→ Scopri di più', close: 'Chiudi',
      tips: [
        ['⚡ Scorciatoia rapida', 'Usa Ctrl+K per aprire la palette dei comandi'],
        ['📁 Organizza i file', 'Raggruppa i file in cartelle per un’anteprima migliore'],
        ['🚀 Template', 'Usa i template per iniziare più velocemente'],
        ['🎨 Tema scuro', 'Perfetto per le sessioni di lavoro lunghe'],
        ['💾 Backup automatico', 'Configura backup automatici per maggiore sicurezza'],
      ],
      dealDescriptions: ['Scansione illimitata delle vulnerabilità', 'Test e collaborazione sulle API', 'Statistiche sulle prestazioni in tempo reale'],
    },
  },
  es: {
    loginRequired: 'Inicio de sesión necesario', loginPrompt: 'Inicia sesión para gestionar tus archivos y carpetas.', login: 'Iniciar sesión',
    pageTitle: 'Gestión de archivos', pageSubtitle: 'Organiza y gestiona tus archivos y carpetas',
    uploadFolder: 'Subir carpeta', uploading: 'Subiendo...', selectFolderTitle: 'Seleccionar una carpeta para subir',
    copy: 'Copiar', copySelectedTitle: 'Copiar el archivo seleccionado', move: 'Mover', moveSelectedTitle: 'Mover el archivo seleccionado',
    paste: 'Pegar', pasteTitle: 'Pegar el archivo copiado o movido', delete: 'Eliminar', deleteSelectedTitle: 'Eliminar el archivo seleccionado',
    loadedFolders: 'Carpetas subidas', fileCount: 'archivos', openInEditorTitle: 'Abrir con File Editor', editor: 'Editor',
    copiedTemplate: 'Plantilla copiada', download: 'Descargar', purchasedTemplates: 'Plantillas compradas',
    copyTitle: 'Copiar', expires: 'Caduca:', noPurchasedTemplates: 'No has comprado plantillas',
    onlineBackup: 'Copia de seguridad en línea', loading: 'Cargando...', noBackups: 'No hay copias guardadas',
    downloadBackupTitle: 'Descargar copia de seguridad', fileDetails: 'Detalles del archivo', name: 'Nombre', size: 'Tamaño',
    type: 'Tipo', lastModified: 'Última modificación', notAvailable: 'N/D', copyContent: 'Copiar contenido',
    clipboardCopyFailed: 'No se pudo copiar al portapapeles.',
    toast: {
      downloadedFile: '¡Archivo "{name}" descargado!', copiedContent: '¡Contenido copiado al portapapeles!',
      copiedFile: '¡Archivo "{name}" copiado! Pégalo donde quieras.', readyToMove: '¡El archivo "{name}" está listo para mover!',
      nothingToPaste: 'No hay nada que pegar', copiedPaste: '¡Archivo "{name}" copiado!', movedPaste: '¡Archivo "{name}" movido!',
      deleting: 'Eliminando...', deletedFile: '¡Archivo "{name}" eliminado!', deleteFailed: 'Error al eliminar el archivo',
      missingProject: 'Error: no hay ningún proyecto disponible', uploadedFile: '¡Archivo "{name}" subido correctamente!',
      uploadFailed: 'Error al subir "{name}"', folderNotSelected: 'Error: no se seleccionó ninguna carpeta',
      folderEmpty: 'La carpeta está vacía o no se seleccionó correctamente',
      loadingFolder: 'Subiendo la carpeta "{name}"... ({count} archivos)',
      folderUploaded: '✅ Carpeta "{name}" subida: {count}/{total} archivos',
      folderUploadFailed: 'Error al subir la carpeta', fileReadFailed: 'No se pudo leer el archivo "{name}"',
      renamedFile: '¡Archivo renombrado!', deletedExplorerFile: '¡Archivo eliminado!', savedFile: '¡Archivo guardado!',
      savedFolder: '¡Carpeta guardada!', copiedTemplate: '¡Plantilla copiada!',
      copiedTemplateVisible: '¡Plantilla copiada! Está en la sección "Plantilla copiada"',
      copyTemplateFailed: 'No se pudo copiar la plantilla.', downloadedBackup: '¡Copia "{name}" descargada!',
    },
    explorer: {
      saveFile: 'Guardar archivo', renameFile: 'Renombrar archivo', refreshPreview: 'Actualizar vista previa',
      closeFile: 'Cerrar archivo', deleteFile: 'Eliminar archivo', saveFolder: 'Guardar carpeta',
      deleteFolder: 'Eliminar carpeta', closeFolder: 'Cerrar carpeta', closeSelectedFile: 'Cerrar archivo seleccionado',
      closeFolderNamed: 'Cerrar carpeta {name}', renameDialog: 'Renombrar', newName: 'Nombre nuevo',
      cancel: 'Cancelar', confirmDelete: 'Confirmar eliminación', confirmDeleteNamed: '¿Seguro que quieres eliminar {name}?',
      empty: 'Aún no hay archivos ni carpetas.', expandFolder: 'Expandir carpeta {name}', collapseFolder: 'Contraer carpeta {name}',
    },
    green: {
      projectStats: 'Estadísticas del proyecto', filesLabel: 'Archivos', linesLabel: 'Líneas de código',
      editingLabel: 'Tiempo de edición', sizeLabel: 'Tamaño del proyecto', minutes: 'min', pricePeriod: '/mes',
      tipHeading: '💡 Consejo del día', offerHeading: '🎁 Oferta exclusiva', seeMore: '→ Más información', close: 'Cerrar',
      tips: [
        ['⚡ Atajo rápido', 'Usa Ctrl+K para abrir la paleta de comandos'],
        ['📁 Organiza tus archivos', 'Agrupa archivos en carpetas para mejorar la vista previa'],
        ['🚀 Plantillas', 'Usa plantillas para empezar más rápido'],
        ['🎨 Tema oscuro', 'Ideal para sesiones de trabajo largas'],
        ['💾 Copia automática', 'Configura copias automáticas para mayor seguridad'],
      ],
      dealDescriptions: ['Análisis ilimitado de vulnerabilidades', 'Pruebas y colaboración de API', 'Información de rendimiento en tiempo real'],
    },
  },
  fr: {
    loginRequired: 'Connexion requise', loginPrompt: 'Connectez-vous pour gérer vos fichiers et dossiers.', login: 'Se connecter',
    pageTitle: 'Gestion des fichiers', pageSubtitle: 'Organisez et gérez vos fichiers et dossiers',
    uploadFolder: 'Importer un dossier', uploading: 'Importation...', selectFolderTitle: 'Sélectionner un dossier à importer',
    copy: 'Copier', copySelectedTitle: 'Copier le fichier sélectionné', move: 'Déplacer', moveSelectedTitle: 'Déplacer le fichier sélectionné',
    paste: 'Coller', pasteTitle: 'Coller le fichier copié ou déplacé', delete: 'Supprimer', deleteSelectedTitle: 'Supprimer le fichier sélectionné',
    loadedFolders: 'Dossiers importés', fileCount: 'fichiers', openInEditorTitle: 'Ouvrir avec File Editor', editor: 'Éditeur',
    copiedTemplate: 'Modèle copié', download: 'Télécharger', purchasedTemplates: 'Modèles achetés',
    copyTitle: 'Copier', expires: 'Expire le :', noPurchasedTemplates: 'Aucun modèle acheté',
    onlineBackup: 'Sauvegarde en ligne', loading: 'Chargement...', noBackups: 'Aucune sauvegarde enregistrée',
    downloadBackupTitle: 'Télécharger la sauvegarde', fileDetails: 'Détails du fichier', name: 'Nom', size: 'Taille',
    type: 'Type', lastModified: 'Dernière modification', notAvailable: 'N/D', copyContent: 'Copier le contenu',
    clipboardCopyFailed: 'Impossible de copier dans le presse-papiers.',
    toast: {
      downloadedFile: 'Fichier « {name} » téléchargé !', copiedContent: 'Contenu copié dans le presse-papiers !',
      copiedFile: 'Fichier « {name} » copié ! Collez-le où vous voulez.', readyToMove: 'Fichier « {name} » prêt à être déplacé !',
      nothingToPaste: 'Rien à coller', copiedPaste: 'Fichier « {name} » copié !', movedPaste: 'Fichier « {name} » déplacé !',
      deleting: 'Suppression...', deletedFile: 'Fichier « {name} » supprimé !', deleteFailed: 'Erreur lors de la suppression du fichier',
      missingProject: 'Erreur : aucun projet disponible', uploadedFile: 'Fichier « {name} » importé avec succès !',
      uploadFailed: 'Erreur lors de l’importation de « {name} »', folderNotSelected: 'Erreur : aucun dossier sélectionné',
      folderEmpty: 'Le dossier est vide ou n’a pas été sélectionné correctement',
      loadingFolder: 'Importation du dossier « {name} »... ({count} fichiers)',
      folderUploaded: '✅ Dossier « {name} » importé : {count}/{total} fichiers',
      folderUploadFailed: 'Erreur lors de l’importation du dossier', fileReadFailed: 'Impossible de lire le fichier « {name} »',
      renamedFile: 'Fichier renommé !', deletedExplorerFile: 'Fichier supprimé !', savedFile: 'Fichier enregistré !',
      savedFolder: 'Dossier enregistré !', copiedTemplate: 'Modèle copié !',
      copiedTemplateVisible: 'Modèle copié ! Il apparaît dans la section « Modèle copié »',
      copyTemplateFailed: 'Impossible de copier le modèle.', downloadedBackup: 'Sauvegarde « {name} » téléchargée !',
    },
    explorer: {
      saveFile: 'Enregistrer le fichier', renameFile: 'Renommer le fichier', refreshPreview: 'Actualiser l’aperçu',
      closeFile: 'Fermer le fichier', deleteFile: 'Supprimer le fichier', saveFolder: 'Enregistrer le dossier',
      deleteFolder: 'Supprimer le dossier', closeFolder: 'Fermer le dossier', closeSelectedFile: 'Fermer le fichier sélectionné',
      closeFolderNamed: 'Fermer le dossier {name}', renameDialog: 'Renommer', newName: 'Nouveau nom',
      cancel: 'Annuler', confirmDelete: 'Confirmer la suppression', confirmDeleteNamed: 'Voulez-vous vraiment supprimer {name} ?',
      empty: 'Aucun fichier ni dossier pour le moment.', expandFolder: 'Développer le dossier {name}', collapseFolder: 'Réduire le dossier {name}',
    },
    green: {
      projectStats: 'Statistiques du projet', filesLabel: 'Fichiers', linesLabel: 'Lignes de code',
      editingLabel: 'Temps de modification', sizeLabel: 'Taille du projet', minutes: 'min', pricePeriod: '/mois',
      tipHeading: '💡 Conseil du jour', offerHeading: '🎁 Offre exclusive', seeMore: '→ En savoir plus', close: 'Fermer',
      tips: [
        ['⚡ Raccourci rapide', 'Utilisez Ctrl+K pour ouvrir la palette de commandes'],
        ['📁 Organisez vos fichiers', 'Regroupez les fichiers dans des dossiers pour un meilleur aperçu'],
        ['🚀 Modèles', 'Utilisez des modèles pour démarrer plus vite'],
        ['🎨 Thème sombre', 'Idéal pour les longues sessions de travail'],
        ['💾 Sauvegarde auto', 'Configurez des sauvegardes automatiques pour plus de sécurité'],
      ],
      dealDescriptions: ['Analyse illimitée des vulnérabilités', 'Tests et collaboration autour des API', 'Statistiques de performances en temps réel'],
    },
  },
  de: {
    loginRequired: 'Anmeldung erforderlich', loginPrompt: 'Melde dich an, um deine Dateien und Ordner zu verwalten.', login: 'Anmelden',
    pageTitle: 'Dateiverwaltung', pageSubtitle: 'Organisiere und verwalte deine Dateien und Ordner',
    uploadFolder: 'Ordner hochladen', uploading: 'Wird hochgeladen...', selectFolderTitle: 'Ordner zum Hochladen auswählen',
    copy: 'Kopieren', copySelectedTitle: 'Ausgewählte Datei kopieren', move: 'Verschieben', moveSelectedTitle: 'Ausgewählte Datei verschieben',
    paste: 'Einfügen', pasteTitle: 'Kopierte/verschobene Datei einfügen', delete: 'Löschen', deleteSelectedTitle: 'Ausgewählte Datei löschen',
    loadedFolders: 'Hochgeladene Ordner', fileCount: 'Dateien', openInEditorTitle: 'Mit File Editor öffnen', editor: 'Editor',
    copiedTemplate: 'Kopierte Vorlage', download: 'Herunterladen', purchasedTemplates: 'Gekaufte Vorlagen',
    copyTitle: 'Kopieren', expires: 'Läuft ab:', noPurchasedTemplates: 'Keine Vorlagen gekauft',
    onlineBackup: 'Online-Backup', loading: 'Wird geladen...', noBackups: 'Keine Backups gespeichert',
    downloadBackupTitle: 'Backup herunterladen', fileDetails: 'Dateidetails', name: 'Name', size: 'Größe',
    type: 'Typ', lastModified: 'Zuletzt geändert', notAvailable: 'k. A.', copyContent: 'Inhalt kopieren',
    clipboardCopyFailed: 'Kopieren in die Zwischenablage nicht möglich.',
    toast: {
      downloadedFile: 'Datei „{name}“ heruntergeladen!', copiedContent: 'Inhalt in die Zwischenablage kopiert!',
      copiedFile: 'Datei „{name}“ kopiert! Füge sie an beliebiger Stelle ein.', readyToMove: 'Datei „{name}“ kann verschoben werden!',
      nothingToPaste: 'Nichts zum Einfügen', copiedPaste: '„{name}“ kopiert!', movedPaste: '„{name}“ verschoben!',
      deleting: 'Wird gelöscht...', deletedFile: 'Datei „{name}“ gelöscht!', deleteFailed: 'Fehler beim Löschen der Datei',
      missingProject: 'Fehler: Kein Projekt verfügbar', uploadedFile: 'Datei „{name}“ erfolgreich hochgeladen!',
      uploadFailed: 'Fehler beim Hochladen von „{name}“', folderNotSelected: 'Fehler: Kein Ordner ausgewählt',
      folderEmpty: 'Der Ordner ist leer oder wurde nicht korrekt ausgewählt',
      loadingFolder: 'Ordner „{name}“ wird hochgeladen... ({count} Dateien)',
      folderUploaded: '✅ Ordner „{name}“ hochgeladen: {count}/{total} Dateien',
      folderUploadFailed: 'Fehler beim Hochladen des Ordners', fileReadFailed: 'Datei „{name}“ konnte nicht gelesen werden',
      renamedFile: 'Datei umbenannt!', deletedExplorerFile: 'Datei gelöscht!', savedFile: 'Datei gespeichert!',
      savedFolder: 'Ordner gespeichert!', copiedTemplate: 'Vorlage kopiert!',
      copiedTemplateVisible: 'Vorlage kopiert! Sie ist im Bereich „Kopierte Vorlage“ zu sehen',
      copyTemplateFailed: 'Vorlage konnte nicht kopiert werden.', downloadedBackup: 'Backup „{name}“ heruntergeladen!',
    },
    explorer: {
      saveFile: 'Datei speichern', renameFile: 'Datei umbenennen', refreshPreview: 'Vorschau aktualisieren',
      closeFile: 'Datei schließen', deleteFile: 'Datei löschen', saveFolder: 'Ordner speichern',
      deleteFolder: 'Ordner löschen', closeFolder: 'Ordner schließen', closeSelectedFile: 'Ausgewählte Datei schließen',
      closeFolderNamed: 'Ordner {name} schließen', renameDialog: 'Umbenennen', newName: 'Neuer Name',
      cancel: 'Abbrechen', confirmDelete: 'Löschen bestätigen', confirmDeleteNamed: 'Möchtest du {name} wirklich löschen?',
      empty: 'Noch keine Dateien oder Ordner vorhanden.', expandFolder: 'Ordner {name} aufklappen', collapseFolder: 'Ordner {name} zuklappen',
    },
    green: {
      projectStats: 'Projektstatistik', filesLabel: 'Dateien', linesLabel: 'Codezeilen',
      editingLabel: 'Bearbeitungszeit', sizeLabel: 'Projektgröße', minutes: 'Min.', pricePeriod: '/Monat',
      tipHeading: '💡 Tipp des Tages', offerHeading: '🎁 Exklusives Angebot', seeMore: '→ Mehr erfahren', close: 'Schließen',
      tips: [
        ['⚡ Schnellzugriff', 'Öffne die Befehlspalette mit Strg+K'],
        ['📁 Dateien organisieren', 'Gruppiere Dateien für eine bessere Vorschau in Ordnern'],
        ['🚀 Vorlagen', 'Starte mit Vorlagen schneller'],
        ['🎨 Dunkles Design', 'Ideal für lange Arbeitssitzungen'],
        ['💾 Automatisches Backup', 'Richte automatische Backups zur Sicherheit ein'],
      ],
      dealDescriptions: ['Unbegrenzte Schwachstellenscans', 'API-Tests und Zusammenarbeit', 'Leistungsanalysen in Echtzeit'],
    },
  },
  pt: {
    loginRequired: 'Início de sessão necessário', loginPrompt: 'Inicie sessão para gerir os seus ficheiros e pastas.', login: 'Iniciar sessão',
    pageTitle: 'Gestão de ficheiros', pageSubtitle: 'Organize e faça a gestão dos seus ficheiros e pastas',
    uploadFolder: 'Carregar pasta', uploading: 'A carregar...', selectFolderTitle: 'Selecione uma pasta para carregar',
    copy: 'Copiar', copySelectedTitle: 'Copiar ficheiro selecionado', move: 'Mover', moveSelectedTitle: 'Mover ficheiro selecionado',
    paste: 'Colar', pasteTitle: 'Colar ficheiro copiado/movido', delete: 'Eliminar', deleteSelectedTitle: 'Eliminar ficheiro selecionado',
    loadedFolders: 'Pastas carregadas', fileCount: 'ficheiros', openInEditorTitle: 'Abrir com File Editor', editor: 'Editor',
    copiedTemplate: 'Modelo copiado', download: 'Transferir', purchasedTemplates: 'Modelos comprados',
    copyTitle: 'Copiar', expires: 'Expira:', noPurchasedTemplates: 'Nenhum modelo comprado',
    onlineBackup: 'Cópia de segurança online', loading: 'A carregar...', noBackups: 'Nenhuma cópia guardada',
    downloadBackupTitle: 'Transferir cópia de segurança', fileDetails: 'Detalhes do ficheiro', name: 'Nome', size: 'Tamanho',
    type: 'Tipo', lastModified: 'Última modificação', notAvailable: 'N/D', copyContent: 'Copiar conteúdo',
    clipboardCopyFailed: 'Não foi possível copiar para a área de transferência.',
    toast: {
      downloadedFile: 'Ficheiro "{name}" transferido!', copiedContent: 'Conteúdo copiado para a área de transferência!',
      copiedFile: 'Ficheiro "{name}" copiado! Cole-o onde quiser.', readyToMove: 'O ficheiro "{name}" está pronto a mover!',
      nothingToPaste: 'Nada para colar', copiedPaste: 'Ficheiro "{name}" copiado!', movedPaste: 'Ficheiro "{name}" movido!',
      deleting: 'A eliminar...', deletedFile: 'Ficheiro "{name}" eliminado!', deleteFailed: 'Erro ao eliminar o ficheiro',
      missingProject: 'Erro: nenhum projeto disponível', uploadedFile: 'Ficheiro "{name}" carregado com sucesso!',
      uploadFailed: 'Erro ao carregar "{name}"', folderNotSelected: 'Erro: nenhuma pasta selecionada',
      folderEmpty: 'A pasta está vazia ou não foi selecionada corretamente',
      loadingFolder: 'A carregar a pasta "{name}"... ({count} ficheiros)',
      folderUploaded: '✅ Pasta "{name}" carregada: {count}/{total} ficheiros',
      folderUploadFailed: 'Erro ao carregar a pasta', fileReadFailed: 'Não foi possível ler o ficheiro "{name}"',
      renamedFile: 'Ficheiro renomeado!', deletedExplorerFile: 'Ficheiro eliminado!', savedFile: 'Ficheiro guardado!',
      savedFolder: 'Pasta guardada!', copiedTemplate: 'Modelo copiado!',
      copiedTemplateVisible: 'Modelo copiado! Está visível na secção "Modelo copiado"',
      copyTemplateFailed: 'Não foi possível copiar o modelo.', downloadedBackup: 'Cópia "{name}" transferida!',
    },
    explorer: {
      saveFile: 'Guardar ficheiro', renameFile: 'Mudar o nome do ficheiro', refreshPreview: 'Atualizar pré-visualização',
      closeFile: 'Fechar ficheiro', deleteFile: 'Eliminar ficheiro', saveFolder: 'Guardar pasta',
      deleteFolder: 'Eliminar pasta', closeFolder: 'Fechar pasta', closeSelectedFile: 'Fechar ficheiro selecionado',
      closeFolderNamed: 'Fechar pasta {name}', renameDialog: 'Mudar o nome', newName: 'Novo nome',
      cancel: 'Cancelar', confirmDelete: 'Confirmar eliminação', confirmDeleteNamed: 'Tem a certeza de que pretende eliminar {name}?',
      empty: 'Ainda não existem ficheiros ou pastas.', expandFolder: 'Expandir pasta {name}', collapseFolder: 'Recolher pasta {name}',
    },
    green: {
      projectStats: 'Estatísticas do projeto', filesLabel: 'Ficheiros', linesLabel: 'Linhas de código',
      editingLabel: 'Tempo de edição', sizeLabel: 'Tamanho do projeto', minutes: 'min', pricePeriod: '/mês',
      tipHeading: '💡 Sugestão do dia', offerHeading: '🎁 Oferta exclusiva', seeMore: '→ Saiba mais', close: 'Fechar',
      tips: [
        ['⚡ Atalho rápido', 'Use Ctrl+K para abrir a paleta de comandos'],
        ['📁 Organize ficheiros', 'Agrupe ficheiros em pastas para uma melhor pré-visualização'],
        ['🚀 Modelos', 'Use modelos para começar mais depressa'],
        ['🎨 Tema escuro', 'Ideal para longas sessões de trabalho'],
        ['💾 Cópia automática', 'Configure cópias automáticas para maior segurança'],
      ],
      dealDescriptions: ['Análise ilimitada de vulnerabilidades', 'Testes e colaboração de APIs', 'Informações de desempenho em tempo real'],
    },
  },
  ru: {
    loginRequired: 'Требуется вход', loginPrompt: 'Войдите, чтобы управлять файлами и папками.', login: 'Войти',
    pageTitle: 'Управление файлами', pageSubtitle: 'Организуйте файлы и папки и управляйте ими',
    uploadFolder: 'Загрузить папку', uploading: 'Загрузка...', selectFolderTitle: 'Выберите папку для загрузки',
    copy: 'Копировать', copySelectedTitle: 'Копировать выбранный файл', move: 'Переместить', moveSelectedTitle: 'Переместить выбранный файл',
    paste: 'Вставить', pasteTitle: 'Вставить скопированный/перемещённый файл', delete: 'Удалить', deleteSelectedTitle: 'Удалить выбранный файл',
    loadedFolders: 'Загруженные папки', fileCount: 'файлов', openInEditorTitle: 'Открыть в File Editor', editor: 'Редактор',
    copiedTemplate: 'Скопированный шаблон', download: 'Скачать', purchasedTemplates: 'Купленные шаблоны',
    copyTitle: 'Копировать', expires: 'Истекает:', noPurchasedTemplates: 'Нет купленных шаблонов',
    onlineBackup: 'Онлайн-резервная копия', loading: 'Загрузка...', noBackups: 'Нет сохранённых копий',
    downloadBackupTitle: 'Скачать резервную копию', fileDetails: 'Сведения о файле', name: 'Имя', size: 'Размер',
    type: 'Тип', lastModified: 'Последнее изменение', notAvailable: 'Н/Д', copyContent: 'Копировать содержимое',
    clipboardCopyFailed: 'Не удалось скопировать в буфер обмена.',
    toast: {
      downloadedFile: 'Файл «{name}» скачан!', copiedContent: 'Содержимое скопировано в буфер обмена!',
      copiedFile: 'Файл «{name}» скопирован! Вставьте его в нужное место.', readyToMove: 'Файл «{name}» готов к перемещению!',
      nothingToPaste: 'Нечего вставлять', copiedPaste: 'Файл «{name}» скопирован!', movedPaste: 'Файл «{name}» перемещён!',
      deleting: 'Удаление...', deletedFile: 'Файл «{name}» удалён!', deleteFailed: 'Не удалось удалить файл',
      missingProject: 'Ошибка: проект недоступен', uploadedFile: 'Файл «{name}» успешно загружен!',
      uploadFailed: 'Не удалось загрузить «{name}»', folderNotSelected: 'Ошибка: папка не выбрана',
      folderEmpty: 'Папка пуста или выбрана неправильно',
      loadingFolder: 'Загрузка папки «{name}»... (файлов: {count})',
      folderUploaded: '✅ Папка «{name}» загружена: {count}/{total} файлов',
      folderUploadFailed: 'Не удалось загрузить папку', fileReadFailed: 'Не удалось прочитать файл «{name}»',
      renamedFile: 'Файл переименован!', deletedExplorerFile: 'Файл удалён!', savedFile: 'Файл сохранён!',
      savedFolder: 'Папка сохранена!', copiedTemplate: 'Шаблон скопирован!',
      copiedTemplateVisible: 'Шаблон скопирован! Он отображается в разделе «Скопированный шаблон»',
      copyTemplateFailed: 'Не удалось скопировать шаблон.', downloadedBackup: 'Резервная копия «{name}» скачана!',
    },
    explorer: {
      saveFile: 'Сохранить файл', renameFile: 'Переименовать файл', refreshPreview: 'Обновить предпросмотр',
      closeFile: 'Закрыть файл', deleteFile: 'Удалить файл', saveFolder: 'Сохранить папку',
      deleteFolder: 'Удалить папку', closeFolder: 'Закрыть папку', closeSelectedFile: 'Закрыть выбранный файл',
      closeFolderNamed: 'Закрыть папку {name}', renameDialog: 'Переименование', newName: 'Новое имя',
      cancel: 'Отмена', confirmDelete: 'Подтвердите удаление', confirmDeleteNamed: 'Удалить {name}?',
      empty: 'Файлов и папок пока нет.', expandFolder: 'Развернуть папку {name}', collapseFolder: 'Свернуть папку {name}',
    },
    green: {
      projectStats: 'Статистика проекта', filesLabel: 'Файлы', linesLabel: 'Строки кода',
      editingLabel: 'Время редактирования', sizeLabel: 'Размер проекта', minutes: 'мин', pricePeriod: '/мес.',
      tipHeading: '💡 Совет дня', offerHeading: '🎁 Эксклюзивное предложение', seeMore: '→ Подробнее', close: 'Закрыть',
      tips: [
        ['⚡ Быстрая команда', 'Нажмите Ctrl+K, чтобы открыть палитру команд'],
        ['📁 Упорядочьте файлы', 'Группируйте файлы по папкам для удобного просмотра'],
        ['🚀 Шаблоны', 'Начните работу быстрее с помощью шаблонов'],
        ['🎨 Тёмная тема', 'Подходит для долгих рабочих сеансов'],
        ['💾 Автоматическая копия', 'Настройте автоматическое резервное копирование'],
      ],
      dealDescriptions: ['Неограниченное сканирование уязвимостей', 'Тестирование API и совместная работа', 'Аналитика производительности в реальном времени'],
    },
  },
  zh: {
    loginRequired: '需要登录', loginPrompt: '请登录以管理文件和文件夹。', login: '登录',
    pageTitle: '文件管理', pageSubtitle: '整理和管理文件及文件夹',
    uploadFolder: '上传文件夹', uploading: '正在上传…', selectFolderTitle: '选择要上传的文件夹',
    copy: '复制', copySelectedTitle: '复制所选文件', move: '移动', moveSelectedTitle: '移动所选文件',
    paste: '粘贴', pasteTitle: '粘贴已复制/移动的文件', delete: '删除', deleteSelectedTitle: '删除所选文件',
    loadedFolders: '已上传的文件夹', fileCount: '个文件', openInEditorTitle: '使用 File Editor 打开', editor: '编辑器',
    copiedTemplate: '已复制的模板', download: '下载', purchasedTemplates: '已购买的模板',
    copyTitle: '复制', expires: '到期时间：', noPurchasedTemplates: '尚未购买模板',
    onlineBackup: '在线备份', loading: '正在加载…', noBackups: '没有已保存的备份',
    downloadBackupTitle: '下载备份', fileDetails: '文件详情', name: '名称', size: '大小',
    type: '类型', lastModified: '上次修改', notAvailable: '不适用', copyContent: '复制内容',
    clipboardCopyFailed: '无法复制到剪贴板。',
    toast: {
      downloadedFile: '已下载文件“{name}”！', copiedContent: '内容已复制到剪贴板！',
      copiedFile: '已复制文件“{name}”！可在任意位置粘贴。', readyToMove: '文件“{name}”已准备好移动！',
      nothingToPaste: '没有可粘贴的内容', copiedPaste: '已复制“{name}”！', movedPaste: '已移动“{name}”！',
      deleting: '正在删除…', deletedFile: '已删除文件“{name}”！', deleteFailed: '删除文件时出错',
      missingProject: '错误：没有可用的项目', uploadedFile: '文件“{name}”已成功上传！',
      uploadFailed: '上传“{name}”时出错', folderNotSelected: '错误：未选择文件夹',
      folderEmpty: '文件夹为空或未正确选择',
      loadingFolder: '正在上传文件夹“{name}”…（{count} 个文件）',
      folderUploaded: '✅ 文件夹“{name}”已上传：{count}/{total} 个文件',
      folderUploadFailed: '上传文件夹时出错', fileReadFailed: '无法读取文件“{name}”',
      renamedFile: '文件已重命名！', deletedExplorerFile: '文件已删除！', savedFile: '文件已保存！',
      savedFolder: '文件夹已保存！', copiedTemplate: '模板已复制！',
      copiedTemplateVisible: '模板已复制！可在“已复制的模板”部分查看',
      copyTemplateFailed: '无法复制模板。', downloadedBackup: '已下载备份“{name}”！',
    },
    explorer: {
      saveFile: '保存文件', renameFile: '重命名文件', refreshPreview: '刷新预览',
      closeFile: '关闭文件', deleteFile: '删除文件', saveFolder: '保存文件夹',
      deleteFolder: '删除文件夹', closeFolder: '关闭文件夹', closeSelectedFile: '关闭所选文件',
      closeFolderNamed: '关闭文件夹 {name}', renameDialog: '重命名', newName: '新名称',
      cancel: '取消', confirmDelete: '确认删除', confirmDeleteNamed: '确定要删除 {name} 吗？',
      empty: '暂无文件或文件夹。', expandFolder: '展开文件夹 {name}', collapseFolder: '折叠文件夹 {name}',
    },
    green: {
      projectStats: '项目统计', filesLabel: '文件数', linesLabel: '代码行数',
      editingLabel: '编辑时间', sizeLabel: '项目大小', minutes: '分钟', pricePeriod: '/月',
      tipHeading: '💡 今日提示', offerHeading: '🎁 专属优惠', seeMore: '→ 了解更多', close: '关闭',
      tips: [
        ['⚡ 快捷操作', '按 Ctrl+K 打开命令面板'],
        ['📁 整理文件', '将文件归入文件夹，获得更好的预览效果'],
        ['🚀 模板', '使用模板，更快开始'],
        ['🎨 深色主题', '适合长时间工作'],
        ['💾 自动备份', '设置自动备份以确保安全'],
      ],
      dealDescriptions: ['无限次漏洞扫描', 'API 测试与协作', '实时性能分析'],
    },
  },
  ja: {
    loginRequired: 'ログインが必要です', loginPrompt: 'ファイルとフォルダーを管理するにはログインしてください。', login: 'ログイン',
    pageTitle: 'ファイル管理', pageSubtitle: 'ファイルとフォルダーを整理・管理',
    uploadFolder: 'フォルダーをアップロード', uploading: 'アップロード中…', selectFolderTitle: 'アップロードするフォルダーを選択',
    copy: 'コピー', copySelectedTitle: '選択したファイルをコピー', move: '移動', moveSelectedTitle: '選択したファイルを移動',
    paste: '貼り付け', pasteTitle: 'コピー/移動したファイルを貼り付け', delete: '削除', deleteSelectedTitle: '選択したファイルを削除',
    loadedFolders: 'アップロード済みフォルダー', fileCount: 'ファイル', openInEditorTitle: 'File Editor で開く', editor: 'エディター',
    copiedTemplate: 'コピーしたテンプレート', download: 'ダウンロード', purchasedTemplates: '購入済みテンプレート',
    copyTitle: 'コピー', expires: '有効期限：', noPurchasedTemplates: '購入済みテンプレートはありません',
    onlineBackup: 'オンラインバックアップ', loading: '読み込み中…', noBackups: '保存済みバックアップはありません',
    downloadBackupTitle: 'バックアップをダウンロード', fileDetails: 'ファイルの詳細', name: '名前', size: 'サイズ',
    type: '種類', lastModified: '最終更新日', notAvailable: '該当なし', copyContent: '内容をコピー',
    clipboardCopyFailed: 'クリップボードにコピーできませんでした。',
    toast: {
      downloadedFile: 'ファイル「{name}」をダウンロードしました！', copiedContent: '内容をクリップボードにコピーしました！',
      copiedFile: 'ファイル「{name}」をコピーしました。好きな場所に貼り付けてください。', readyToMove: 'ファイル「{name}」を移動できます！',
      nothingToPaste: '貼り付けるものがありません', copiedPaste: '「{name}」をコピーしました！', movedPaste: '「{name}」を移動しました！',
      deleting: '削除中…', deletedFile: 'ファイル「{name}」を削除しました！', deleteFailed: 'ファイルの削除中にエラーが発生しました',
      missingProject: 'エラー：利用可能なプロジェクトがありません', uploadedFile: 'ファイル「{name}」をアップロードしました！',
      uploadFailed: '「{name}」のアップロード中にエラーが発生しました', folderNotSelected: 'エラー：フォルダーが選択されていません',
      folderEmpty: 'フォルダーが空か、正しく選択されていません',
      loadingFolder: 'フォルダー「{name}」をアップロード中…（{count} ファイル）',
      folderUploaded: '✅ フォルダー「{name}」をアップロードしました：{count}/{total} ファイル',
      folderUploadFailed: 'フォルダーのアップロード中にエラーが発生しました', fileReadFailed: 'ファイル「{name}」を読み込めませんでした',
      renamedFile: 'ファイル名を変更しました！', deletedExplorerFile: 'ファイルを削除しました！', savedFile: 'ファイルを保存しました！',
      savedFolder: 'フォルダーを保存しました！', copiedTemplate: 'テンプレートをコピーしました！',
      copiedTemplateVisible: 'テンプレートをコピーしました。「コピーしたテンプレート」セクションに表示されています',
      copyTemplateFailed: 'テンプレートをコピーできませんでした。', downloadedBackup: 'バックアップ「{name}」をダウンロードしました！',
    },
    explorer: {
      saveFile: 'ファイルを保存', renameFile: 'ファイル名を変更', refreshPreview: 'プレビューを更新',
      closeFile: 'ファイルを閉じる', deleteFile: 'ファイルを削除', saveFolder: 'フォルダーを保存',
      deleteFolder: 'フォルダーを削除', closeFolder: 'フォルダーを閉じる', closeSelectedFile: '選択したファイルを閉じる',
      closeFolderNamed: 'フォルダー「{name}」を閉じる', renameDialog: '名前を変更', newName: '新しい名前',
      cancel: 'キャンセル', confirmDelete: '削除の確認', confirmDeleteNamed: '{name} を削除してもよろしいですか？',
      empty: 'ファイルやフォルダーはありません。', expandFolder: 'フォルダー「{name}」を展開', collapseFolder: 'フォルダー「{name}」を折りたたむ',
    },
    green: {
      projectStats: 'プロジェクト統計', filesLabel: 'ファイル数', linesLabel: 'コード行数',
      editingLabel: '編集時間', sizeLabel: 'プロジェクトサイズ', minutes: '分', pricePeriod: '/月',
      tipHeading: '💡 今日のヒント', offerHeading: '🎁 限定オファー', seeMore: '→ 詳細を見る', close: '閉じる',
      tips: [
        ['⚡ クイックショートカット', 'Ctrl+K でコマンドパレットを開く'],
        ['📁 ファイルを整理', 'ファイルをフォルダーにまとめてプレビューを改善'],
        ['🚀 テンプレート', 'テンプレートを使ってすばやく開始'],
        ['🎨 ダークテーマ', '長時間の作業に最適'],
        ['💾 自動バックアップ', '安全のために自動バックアップを設定'],
      ],
      dealDescriptions: ['脆弱性を無制限にスキャン', 'API のテストと共同作業', 'リアルタイムのパフォーマンス分析'],
    },
  },
  ko: {
    loginRequired: '로그인이 필요합니다', loginPrompt: '파일과 폴더를 관리하려면 로그인하세요.', login: '로그인',
    pageTitle: '파일 관리', pageSubtitle: '파일과 폴더를 정리하고 관리하세요',
    uploadFolder: '폴더 업로드', uploading: '업로드 중...', selectFolderTitle: '업로드할 폴더 선택',
    copy: '복사', copySelectedTitle: '선택한 파일 복사', move: '이동', moveSelectedTitle: '선택한 파일 이동',
    paste: '붙여넣기', pasteTitle: '복사/이동한 파일 붙여넣기', delete: '삭제', deleteSelectedTitle: '선택한 파일 삭제',
    loadedFolders: '업로드한 폴더', fileCount: '개 파일', openInEditorTitle: 'File Editor에서 열기', editor: '편집기',
    copiedTemplate: '복사한 템플릿', download: '다운로드', purchasedTemplates: '구매한 템플릿',
    copyTitle: '복사', expires: '만료:', noPurchasedTemplates: '구매한 템플릿이 없습니다',
    onlineBackup: '온라인 백업', loading: '불러오는 중...', noBackups: '저장된 백업이 없습니다',
    downloadBackupTitle: '백업 다운로드', fileDetails: '파일 세부정보', name: '이름', size: '크기',
    type: '유형', lastModified: '마지막 수정', notAvailable: '해당 없음', copyContent: '내용 복사',
    clipboardCopyFailed: '클립보드에 복사할 수 없습니다.',
    toast: {
      downloadedFile: '파일 "{name}"을(를) 다운로드했습니다!', copiedContent: '내용을 클립보드에 복사했습니다!',
      copiedFile: '파일 "{name}"을(를) 복사했습니다! 원하는 곳에 붙여넣으세요.', readyToMove: '파일 "{name}"을(를) 이동할 준비가 되었습니다!',
      nothingToPaste: '붙여넣을 항목이 없습니다', copiedPaste: '"{name}"을(를) 복사했습니다!', movedPaste: '"{name}"을(를) 이동했습니다!',
      deleting: '삭제 중...', deletedFile: '파일 "{name}"을(를) 삭제했습니다!', deleteFailed: '파일 삭제 중 오류가 발생했습니다',
      missingProject: '오류: 사용할 수 있는 프로젝트가 없습니다', uploadedFile: '파일 "{name}"을(를) 업로드했습니다!',
      uploadFailed: '"{name}" 업로드 중 오류가 발생했습니다', folderNotSelected: '오류: 폴더를 선택하지 않았습니다',
      folderEmpty: '폴더가 비어 있거나 올바르게 선택되지 않았습니다',
      loadingFolder: '폴더 "{name}" 업로드 중... ({count}개 파일)',
      folderUploaded: '✅ 폴더 "{name}" 업로드 완료: {count}/{total}개 파일',
      folderUploadFailed: '폴더 업로드 중 오류가 발생했습니다', fileReadFailed: '파일 "{name}"을(를) 읽을 수 없습니다',
      renamedFile: '파일 이름을 변경했습니다!', deletedExplorerFile: '파일을 삭제했습니다!', savedFile: '파일을 저장했습니다!',
      savedFolder: '폴더를 저장했습니다!', copiedTemplate: '템플릿을 복사했습니다!',
      copiedTemplateVisible: '템플릿을 복사했습니다! "복사한 템플릿" 섹션에서 확인할 수 있습니다',
      copyTemplateFailed: '템플릿을 복사할 수 없습니다.', downloadedBackup: '백업 "{name}"을(를) 다운로드했습니다!',
    },
    explorer: {
      saveFile: '파일 저장', renameFile: '파일 이름 변경', refreshPreview: '미리보기 새로고침',
      closeFile: '파일 닫기', deleteFile: '파일 삭제', saveFolder: '폴더 저장',
      deleteFolder: '폴더 삭제', closeFolder: '폴더 닫기', closeSelectedFile: '선택한 파일 닫기',
      closeFolderNamed: '폴더 {name} 닫기', renameDialog: '이름 변경', newName: '새 이름',
      cancel: '취소', confirmDelete: '삭제 확인', confirmDeleteNamed: '{name}을(를) 삭제하시겠습니까?',
      empty: '파일이나 폴더가 없습니다.', expandFolder: '폴더 {name} 펼치기', collapseFolder: '폴더 {name} 접기',
    },
    green: {
      projectStats: '프로젝트 통계', filesLabel: '파일', linesLabel: '코드 줄',
      editingLabel: '편집 시간', sizeLabel: '프로젝트 크기', minutes: '분', pricePeriod: '/월',
      tipHeading: '💡 오늘의 팁', offerHeading: '🎁 특별 혜택', seeMore: '→ 자세히 보기', close: '닫기',
      tips: [
        ['⚡ 빠른 단축키', 'Ctrl+K를 눌러 명령 팔레트를 여세요'],
        ['📁 파일 정리', '폴더에 파일을 모아 미리보기를 개선하세요'],
        ['🚀 템플릿', '템플릿으로 더 빠르게 시작하세요'],
        ['🎨 다크 테마', '긴 작업 세션에 적합합니다'],
        ['💾 자동 백업', '안전을 위해 자동 백업을 설정하세요'],
      ],
      dealDescriptions: ['무제한 취약점 검사', 'API 테스트 및 협업', '실시간 성능 분석'],
    },
  },
  ar: {
    loginRequired: 'تسجيل الدخول مطلوب', loginPrompt: 'سجّل الدخول لإدارة ملفاتك ومجلداتك.', login: 'تسجيل الدخول',
    pageTitle: 'إدارة الملفات', pageSubtitle: 'نظّم ملفاتك ومجلداتك وأدرها',
    uploadFolder: 'تحميل مجلد', uploading: 'جارٍ التحميل...', selectFolderTitle: 'اختر مجلدًا لتحميله',
    copy: 'نسخ', copySelectedTitle: 'نسخ الملف المحدد', move: 'نقل', moveSelectedTitle: 'نقل الملف المحدد',
    paste: 'لصق', pasteTitle: 'لصق الملف المنسوخ أو المنقول', delete: 'حذف', deleteSelectedTitle: 'حذف الملف المحدد',
    loadedFolders: 'المجلدات المحمّلة', fileCount: 'ملفات', openInEditorTitle: 'فتح باستخدام File Editor', editor: 'المحرر',
    copiedTemplate: 'القالب المنسوخ', download: 'تنزيل', purchasedTemplates: 'القوالب المشتراة',
    copyTitle: 'نسخ', expires: 'ينتهي في:', noPurchasedTemplates: 'لم يتم شراء أي قوالب',
    onlineBackup: 'نسخة احتياطية عبر الإنترنت', loading: 'جارٍ التحميل...', noBackups: 'لا توجد نسخ احتياطية محفوظة',
    downloadBackupTitle: 'تنزيل النسخة الاحتياطية', fileDetails: 'تفاصيل الملف', name: 'الاسم', size: 'الحجم',
    type: 'النوع', lastModified: 'آخر تعديل', notAvailable: 'غير متاح', copyContent: 'نسخ المحتوى',
    clipboardCopyFailed: 'تعذر النسخ إلى الحافظة.',
    toast: {
      downloadedFile: 'تم تنزيل الملف "{name}"!', copiedContent: 'تم نسخ المحتوى إلى الحافظة!',
      copiedFile: 'تم نسخ الملف "{name}"! الصقه أينما تريد.', readyToMove: 'الملف "{name}" جاهز للنقل!',
      nothingToPaste: 'لا يوجد شيء للصقه', copiedPaste: 'تم نسخ "{name}"!', movedPaste: 'تم نقل "{name}"!',
      deleting: 'جارٍ الحذف...', deletedFile: 'تم حذف الملف "{name}"!', deleteFailed: 'حدث خطأ أثناء حذف الملف',
      missingProject: 'خطأ: لا يتوفر أي مشروع', uploadedFile: 'تم تحميل الملف "{name}" بنجاح!',
      uploadFailed: 'حدث خطأ أثناء تحميل "{name}"', folderNotSelected: 'خطأ: لم يتم تحديد مجلد',
      folderEmpty: 'المجلد فارغ أو لم يتم تحديده بشكل صحيح',
      loadingFolder: 'جارٍ تحميل المجلد "{name}"... ({count} ملفات)',
      folderUploaded: '✅ تم تحميل المجلد "{name}": {count}/{total} ملفات',
      folderUploadFailed: 'حدث خطأ أثناء تحميل المجلد', fileReadFailed: 'تعذرت قراءة الملف "{name}"',
      renamedFile: 'تمت إعادة تسمية الملف!', deletedExplorerFile: 'تم حذف الملف!', savedFile: 'تم حفظ الملف!',
      savedFolder: 'تم حفظ المجلد!', copiedTemplate: 'تم نسخ القالب!',
      copiedTemplateVisible: 'تم نسخ القالب! يظهر في قسم "القالب المنسوخ"',
      copyTemplateFailed: 'تعذر نسخ القالب.', downloadedBackup: 'تم تنزيل النسخة الاحتياطية "{name}"!',
    },
    explorer: {
      saveFile: 'حفظ الملف', renameFile: 'إعادة تسمية الملف', refreshPreview: 'تحديث المعاينة',
      closeFile: 'إغلاق الملف', deleteFile: 'حذف الملف', saveFolder: 'حفظ المجلد',
      deleteFolder: 'حذف المجلد', closeFolder: 'إغلاق المجلد', closeSelectedFile: 'إغلاق الملف المحدد',
      closeFolderNamed: 'إغلاق المجلد {name}', renameDialog: 'إعادة التسمية', newName: 'اسم جديد',
      cancel: 'إلغاء', confirmDelete: 'تأكيد الحذف', confirmDeleteNamed: 'هل تريد بالتأكيد حذف {name}؟',
      empty: 'لا توجد ملفات أو مجلدات بعد.', expandFolder: 'توسيع المجلد {name}', collapseFolder: 'طي المجلد {name}',
    },
    green: {
      projectStats: 'إحصاءات المشروع', filesLabel: 'الملفات', linesLabel: 'أسطر التعليمات البرمجية',
      editingLabel: 'مدة التحرير', sizeLabel: 'حجم المشروع', minutes: 'دقيقة', pricePeriod: '/شهر',
      tipHeading: '💡 نصيحة اليوم', offerHeading: '🎁 عرض حصري', seeMore: '→ اكتشف المزيد', close: 'إغلاق',
      tips: [
        ['⚡ اختصار سريع', 'استخدم Ctrl+K لفتح لوحة الأوامر'],
        ['📁 نظّم الملفات', 'اجمع الملفات في مجلدات لتحسين المعاينة'],
        ['🚀 القوالب', 'استخدم القوالب للبدء بسرعة أكبر'],
        ['🎨 المظهر الداكن', 'مثالي لجلسات العمل الطويلة'],
        ['💾 نسخ احتياطي تلقائي', 'أعد النسخ الاحتياطي التلقائي لمزيد من الأمان'],
      ],
      dealDescriptions: ['فحص غير محدود للثغرات', 'اختبار واجهات API والتعاون', 'إحصاءات الأداء في الوقت الفعلي'],
    },
  },
  hi: {
    loginRequired: 'साइन इन आवश्यक है', loginPrompt: 'अपनी फ़ाइलें और फ़ोल्डर प्रबंधित करने के लिए साइन इन करें।', login: 'साइन इन',
    pageTitle: 'फ़ाइल प्रबंधन', pageSubtitle: 'अपनी फ़ाइलों और फ़ोल्डरों को व्यवस्थित और प्रबंधित करें',
    uploadFolder: 'फ़ोल्डर अपलोड करें', uploading: 'अपलोड हो रहा है...', selectFolderTitle: 'अपलोड करने के लिए फ़ोल्डर चुनें',
    copy: 'कॉपी करें', copySelectedTitle: 'चुनी हुई फ़ाइल कॉपी करें', move: 'स्थानांतरित करें', moveSelectedTitle: 'चुनी हुई फ़ाइल स्थानांतरित करें',
    paste: 'चिपकाएँ', pasteTitle: 'कॉपी/स्थानांतरित फ़ाइल चिपकाएँ', delete: 'हटाएँ', deleteSelectedTitle: 'चुनी हुई फ़ाइल हटाएँ',
    loadedFolders: 'अपलोड किए गए फ़ोल्डर', fileCount: 'फ़ाइलें', openInEditorTitle: 'File Editor में खोलें', editor: 'संपादक',
    copiedTemplate: 'कॉपी किया गया टेम्पलेट', download: 'डाउनलोड करें', purchasedTemplates: 'खरीदे गए टेम्पलेट',
    copyTitle: 'कॉपी करें', expires: 'समाप्ति:', noPurchasedTemplates: 'कोई टेम्पलेट नहीं खरीदा गया',
    onlineBackup: 'ऑनलाइन बैकअप', loading: 'लोड हो रहा है...', noBackups: 'कोई बैकअप सहेजा नहीं गया',
    downloadBackupTitle: 'बैकअप डाउनलोड करें', fileDetails: 'फ़ाइल विवरण', name: 'नाम', size: 'आकार',
    type: 'प्रकार', lastModified: 'अंतिम संशोधन', notAvailable: 'उपलब्ध नहीं', copyContent: 'सामग्री कॉपी करें',
    clipboardCopyFailed: 'क्लिपबोर्ड पर कॉपी नहीं किया जा सका।',
    toast: {
      downloadedFile: 'फ़ाइल "{name}" डाउनलोड हो गई!', copiedContent: 'सामग्री क्लिपबोर्ड पर कॉपी हो गई!',
      copiedFile: 'फ़ाइल "{name}" कॉपी हो गई! इसे कहीं भी चिपकाएँ।', readyToMove: 'फ़ाइल "{name}" स्थानांतरित करने के लिए तैयार है!',
      nothingToPaste: 'चिपकाने के लिए कुछ नहीं', copiedPaste: '"{name}" कॉपी हो गया!', movedPaste: '"{name}" स्थानांतरित हो गया!',
      deleting: 'हटाया जा रहा है...', deletedFile: 'फ़ाइल "{name}" हट गई!', deleteFailed: 'फ़ाइल हटाने में त्रुटि',
      missingProject: 'त्रुटि: कोई प्रोजेक्ट उपलब्ध नहीं', uploadedFile: 'फ़ाइल "{name}" सफलतापूर्वक अपलोड हुई!',
      uploadFailed: '"{name}" अपलोड करने में त्रुटि', folderNotSelected: 'त्रुटि: कोई फ़ोल्डर नहीं चुना गया',
      folderEmpty: 'फ़ोल्डर खाली है या सही तरीके से नहीं चुना गया',
      loadingFolder: 'फ़ोल्डर "{name}" अपलोड हो रहा है... ({count} फ़ाइलें)',
      folderUploaded: '✅ फ़ोल्डर "{name}" अपलोड हुआ: {count}/{total} फ़ाइलें',
      folderUploadFailed: 'फ़ोल्डर अपलोड करने में त्रुटि', fileReadFailed: 'फ़ाइल "{name}" पढ़ी नहीं जा सकी',
      renamedFile: 'फ़ाइल का नाम बदल गया!', deletedExplorerFile: 'फ़ाइल हट गई!', savedFile: 'फ़ाइल सहेजी गई!',
      savedFolder: 'फ़ोल्डर सहेजा गया!', copiedTemplate: 'टेम्पलेट कॉपी हो गया!',
      copiedTemplateVisible: 'टेम्पलेट कॉपी हो गया! यह "कॉपी किया गया टेम्पलेट" अनुभाग में दिखता है',
      copyTemplateFailed: 'टेम्पलेट कॉपी नहीं किया जा सका।', downloadedBackup: 'बैकअप "{name}" डाउनलोड हुआ!',
    },
    explorer: {
      saveFile: 'फ़ाइल सहेजें', renameFile: 'फ़ाइल का नाम बदलें', refreshPreview: 'पूर्वावलोकन ताज़ा करें',
      closeFile: 'फ़ाइल बंद करें', deleteFile: 'फ़ाइल हटाएँ', saveFolder: 'फ़ोल्डर सहेजें',
      deleteFolder: 'फ़ोल्डर हटाएँ', closeFolder: 'फ़ोल्डर बंद करें', closeSelectedFile: 'चुनी हुई फ़ाइल बंद करें',
      closeFolderNamed: 'फ़ोल्डर {name} बंद करें', renameDialog: 'नाम बदलें', newName: 'नया नाम',
      cancel: 'रद्द करें', confirmDelete: 'हटाने की पुष्टि करें', confirmDeleteNamed: 'क्या आप वाकई {name} हटाना चाहते हैं?',
      empty: 'अभी कोई फ़ाइल या फ़ोल्डर नहीं है।', expandFolder: 'फ़ोल्डर {name} खोलें', collapseFolder: 'फ़ोल्डर {name} बंद करें',
    },
    green: {
      projectStats: 'प्रोजेक्ट आँकड़े', filesLabel: 'फ़ाइलें', linesLabel: 'कोड पंक्तियाँ',
      editingLabel: 'संपादन समय', sizeLabel: 'प्रोजेक्ट आकार', minutes: 'मिनट', pricePeriod: '/माह',
      tipHeading: '💡 आज की सलाह', offerHeading: '🎁 विशेष ऑफ़र', seeMore: '→ और जानें', close: 'बंद करें',
      tips: [
        ['⚡ त्वरित शॉर्टकट', 'कमांड पैलेट खोलने के लिए Ctrl+K दबाएँ'],
        ['📁 फ़ाइलें व्यवस्थित करें', 'बेहतर पूर्वावलोकन के लिए फ़ाइलों को फ़ोल्डरों में रखें'],
        ['🚀 टेम्पलेट', 'तेज़ी से शुरू करने के लिए टेम्पलेट इस्तेमाल करें'],
        ['🎨 डार्क थीम', 'लंबे काम के सत्रों के लिए उपयुक्त'],
        ['💾 स्वचालित बैकअप', 'सुरक्षा के लिए स्वचालित बैकअप सेट करें'],
      ],
      dealDescriptions: ['असीमित भेद्यता स्कैनिंग', 'API परीक्षण और सहयोग', 'रीयल-टाइम प्रदर्शन जानकारी'],
    },
  },
  pl: {
    loginRequired: 'Wymagane logowanie', loginPrompt: 'Zaloguj się, aby zarządzać plikami i folderami.', login: 'Zaloguj się',
    pageTitle: 'Zarządzanie plikami', pageSubtitle: 'Organizuj pliki i foldery oraz zarządzaj nimi',
    uploadFolder: 'Prześlij folder', uploading: 'Przesyłanie...', selectFolderTitle: 'Wybierz folder do przesłania',
    copy: 'Kopiuj', copySelectedTitle: 'Kopiuj wybrany plik', move: 'Przenieś', moveSelectedTitle: 'Przenieś wybrany plik',
    paste: 'Wklej', pasteTitle: 'Wklej skopiowany/przeniesiony plik', delete: 'Usuń', deleteSelectedTitle: 'Usuń wybrany plik',
    loadedFolders: 'Przesłane foldery', fileCount: 'pliki', openInEditorTitle: 'Otwórz w File Editor', editor: 'Edytor',
    copiedTemplate: 'Skopiowany szablon', download: 'Pobierz', purchasedTemplates: 'Kupione szablony',
    copyTitle: 'Kopiuj', expires: 'Wygasa:', noPurchasedTemplates: 'Nie kupiono żadnych szablonów',
    onlineBackup: 'Kopia zapasowa online', loading: 'Ładowanie...', noBackups: 'Brak zapisanych kopii zapasowych',
    downloadBackupTitle: 'Pobierz kopię zapasową', fileDetails: 'Szczegóły pliku', name: 'Nazwa', size: 'Rozmiar',
    type: 'Typ', lastModified: 'Ostatnia modyfikacja', notAvailable: 'Brak danych', copyContent: 'Kopiuj zawartość',
    clipboardCopyFailed: 'Nie można skopiować do schowka.',
    toast: {
      downloadedFile: 'Pobrano plik „{name}”!', copiedContent: 'Skopiowano zawartość do schowka!',
      copiedFile: 'Skopiowano plik „{name}”. Wklej go w dowolnym miejscu.', readyToMove: 'Plik „{name}” jest gotowy do przeniesienia!',
      nothingToPaste: 'Brak elementów do wklejenia', copiedPaste: 'Skopiowano „{name}”!', movedPaste: 'Przeniesiono „{name}”!',
      deleting: 'Usuwanie...', deletedFile: 'Usunięto plik „{name}”!', deleteFailed: 'Błąd podczas usuwania pliku',
      missingProject: 'Błąd: brak dostępnego projektu', uploadedFile: 'Pomyślnie przesłano plik „{name}”!',
      uploadFailed: 'Błąd podczas przesyłania „{name}”', folderNotSelected: 'Błąd: nie wybrano folderu',
      folderEmpty: 'Folder jest pusty lub nie został prawidłowo wybrany',
      loadingFolder: 'Przesyłanie folderu „{name}”... (plików: {count})',
      folderUploaded: '✅ Przesłano folder „{name}”: {count}/{total} plików',
      folderUploadFailed: 'Błąd podczas przesyłania folderu', fileReadFailed: 'Nie można odczytać pliku „{name}”',
      renamedFile: 'Zmieniono nazwę pliku!', deletedExplorerFile: 'Usunięto plik!', savedFile: 'Zapisano plik!',
      savedFolder: 'Zapisano folder!', copiedTemplate: 'Skopiowano szablon!',
      copiedTemplateVisible: 'Skopiowano szablon! Jest widoczny w sekcji „Skopiowany szablon”',
      copyTemplateFailed: 'Nie można skopiować szablonu.', downloadedBackup: 'Pobrano kopię „{name}”!',
    },
    explorer: {
      saveFile: 'Zapisz plik', renameFile: 'Zmień nazwę pliku', refreshPreview: 'Odśwież podgląd',
      closeFile: 'Zamknij plik', deleteFile: 'Usuń plik', saveFolder: 'Zapisz folder',
      deleteFolder: 'Usuń folder', closeFolder: 'Zamknij folder', closeSelectedFile: 'Zamknij wybrany plik',
      closeFolderNamed: 'Zamknij folder {name}', renameDialog: 'Zmień nazwę', newName: 'Nowa nazwa',
      cancel: 'Anuluj', confirmDelete: 'Potwierdź usunięcie', confirmDeleteNamed: 'Czy na pewno chcesz usunąć {name}?',
      empty: 'Nie ma jeszcze plików ani folderów.', expandFolder: 'Rozwiń folder {name}', collapseFolder: 'Zwiń folder {name}',
    },
    green: {
      projectStats: 'Statystyki projektu', filesLabel: 'Pliki', linesLabel: 'Wiersze kodu',
      editingLabel: 'Czas edycji', sizeLabel: 'Rozmiar projektu', minutes: 'min', pricePeriod: '/mies.',
      tipHeading: '💡 Wskazówka dnia', offerHeading: '🎁 Oferta specjalna', seeMore: '→ Dowiedz się więcej', close: 'Zamknij',
      tips: [
        ['⚡ Szybki skrót', 'Użyj Ctrl+K, aby otworzyć paletę poleceń'],
        ['📁 Organizuj pliki', 'Grupuj pliki w folderach, aby poprawić podgląd'],
        ['🚀 Szablony', 'Korzystaj z szablonów, aby szybciej zacząć'],
        ['🎨 Ciemny motyw', 'Idealny na długie sesje pracy'],
        ['💾 Automatyczna kopia', 'Skonfiguruj automatyczne kopie zapasowe'],
      ],
      dealDescriptions: ['Nielimitowane skanowanie podatności', 'Testowanie API i współpraca', 'Analiza wydajności w czasie rzeczywistym'],
    },
  },
  nl: {
    loginRequired: 'Inloggen vereist', loginPrompt: 'Log in om je bestanden en mappen te beheren.', login: 'Inloggen',
    pageTitle: 'Bestandsbeheer', pageSubtitle: 'Organiseer en beheer je bestanden en mappen',
    uploadFolder: 'Map uploaden', uploading: 'Uploaden...', selectFolderTitle: 'Selecteer een map om te uploaden',
    copy: 'Kopiëren', copySelectedTitle: 'Geselecteerd bestand kopiëren', move: 'Verplaatsen', moveSelectedTitle: 'Geselecteerd bestand verplaatsen',
    paste: 'Plakken', pasteTitle: 'Gekopieerd/verplaatst bestand plakken', delete: 'Verwijderen', deleteSelectedTitle: 'Geselecteerd bestand verwijderen',
    loadedFolders: 'Geüploade mappen', fileCount: 'bestanden', openInEditorTitle: 'Openen met File Editor', editor: 'Editor',
    copiedTemplate: 'Gekopieerde sjabloon', download: 'Downloaden', purchasedTemplates: 'Gekochte sjablonen',
    copyTitle: 'Kopiëren', expires: 'Verloopt:', noPurchasedTemplates: 'Geen sjablonen gekocht',
    onlineBackup: 'Online back-up', loading: 'Laden...', noBackups: 'Geen back-ups opgeslagen',
    downloadBackupTitle: 'Back-up downloaden', fileDetails: 'Bestandsdetails', name: 'Naam', size: 'Grootte',
    type: 'Type', lastModified: 'Laatst gewijzigd', notAvailable: 'N.v.t.', copyContent: 'Inhoud kopiëren',
    clipboardCopyFailed: 'Kopiëren naar het klembord is niet gelukt.',
    toast: {
      downloadedFile: 'Bestand "{name}" gedownload!', copiedContent: 'Inhoud naar het klembord gekopieerd!',
      copiedFile: 'Bestand "{name}" gekopieerd! Plak het waar je wilt.', readyToMove: 'Bestand "{name}" is klaar om te verplaatsen!',
      nothingToPaste: 'Niets om te plakken', copiedPaste: '"{name}" gekopieerd!', movedPaste: '"{name}" verplaatst!',
      deleting: 'Verwijderen...', deletedFile: 'Bestand "{name}" verwijderd!', deleteFailed: 'Fout bij het verwijderen van het bestand',
      missingProject: 'Fout: er is geen project beschikbaar', uploadedFile: 'Bestand "{name}" is geüpload!',
      uploadFailed: 'Fout bij het uploaden van "{name}"', folderNotSelected: 'Fout: er is geen map geselecteerd',
      folderEmpty: 'De map is leeg of niet goed geselecteerd',
      loadingFolder: 'Map "{name}" uploaden... ({count} bestanden)',
      folderUploaded: '✅ Map "{name}" geüpload: {count}/{total} bestanden',
      folderUploadFailed: 'Fout bij het uploaden van de map', fileReadFailed: 'Bestand "{name}" kan niet worden gelezen',
      renamedFile: 'Bestand hernoemd!', deletedExplorerFile: 'Bestand verwijderd!', savedFile: 'Bestand opgeslagen!',
      savedFolder: 'Map opgeslagen!', copiedTemplate: 'Sjabloon gekopieerd!',
      copiedTemplateVisible: 'Sjabloon gekopieerd! Het staat in de sectie "Gekopieerde sjabloon"',
      copyTemplateFailed: 'Het sjabloon kan niet worden gekopieerd.', downloadedBackup: 'Back-up "{name}" gedownload!',
    },
    explorer: {
      saveFile: 'Bestand opslaan', renameFile: 'Bestand hernoemen', refreshPreview: 'Voorbeeld vernieuwen',
      closeFile: 'Bestand sluiten', deleteFile: 'Bestand verwijderen', saveFolder: 'Map opslaan',
      deleteFolder: 'Map verwijderen', closeFolder: 'Map sluiten', closeSelectedFile: 'Geselecteerd bestand sluiten',
      closeFolderNamed: 'Map {name} sluiten', renameDialog: 'Hernoemen', newName: 'Nieuwe naam',
      cancel: 'Annuleren', confirmDelete: 'Verwijderen bevestigen', confirmDeleteNamed: 'Weet je zeker dat je {name} wilt verwijderen?',
      empty: 'Er zijn nog geen bestanden of mappen.', expandFolder: 'Map {name} uitklappen', collapseFolder: 'Map {name} inklappen',
    },
    green: {
      projectStats: 'Projectstatistieken', filesLabel: 'Bestanden', linesLabel: 'Regels code',
      editingLabel: 'Bewerkingstijd', sizeLabel: 'Projectgrootte', minutes: 'min', pricePeriod: '/maand',
      tipHeading: '💡 Tip van de dag', offerHeading: '🎁 Exclusieve aanbieding', seeMore: '→ Meer informatie', close: 'Sluiten',
      tips: [
        ['⚡ Snelle sneltoets', 'Gebruik Ctrl+K om het opdrachtenvenster te openen'],
        ['📁 Bestanden ordenen', 'Groepeer bestanden in mappen voor een betere preview'],
        ['🚀 Sjablonen', 'Gebruik sjablonen om sneller aan de slag te gaan'],
        ['🎨 Donker thema', 'Perfect voor lange werksessies'],
        ['💾 Automatische back-up', 'Stel automatische back-ups in voor extra veiligheid'],
      ],
      dealDescriptions: ['Onbeperkt scannen op kwetsbaarheden', 'API-testen en samenwerking', 'Realtime inzichten in prestaties'],
    },
  },
  tr: {
    loginRequired: 'Giriş gerekli', loginPrompt: 'Dosyalarınızı ve klasörlerinizi yönetmek için giriş yapın.', login: 'Giriş yap',
    pageTitle: 'Dosya yönetimi', pageSubtitle: 'Dosyalarınızı ve klasörlerinizi düzenleyin ve yönetin',
    uploadFolder: 'Klasör yükle', uploading: 'Yükleniyor...', selectFolderTitle: 'Yüklenecek klasörü seçin',
    copy: 'Kopyala', copySelectedTitle: 'Seçili dosyayı kopyala', move: 'Taşı', moveSelectedTitle: 'Seçili dosyayı taşı',
    paste: 'Yapıştır', pasteTitle: 'Kopyalanan/taşınan dosyayı yapıştır', delete: 'Sil', deleteSelectedTitle: 'Seçili dosyayı sil',
    loadedFolders: 'Yüklenen klasörler', fileCount: 'dosya', openInEditorTitle: 'File Editor ile aç', editor: 'Düzenleyici',
    copiedTemplate: 'Kopyalanan şablon', download: 'İndir', purchasedTemplates: 'Satın alınan şablonlar',
    copyTitle: 'Kopyala', expires: 'Sona erme:', noPurchasedTemplates: 'Satın alınan şablon yok',
    onlineBackup: 'Çevrimiçi yedekleme', loading: 'Yükleniyor...', noBackups: 'Kaydedilmiş yedek yok',
    downloadBackupTitle: 'Yedeği indir', fileDetails: 'Dosya ayrıntıları', name: 'Ad', size: 'Boyut',
    type: 'Tür', lastModified: 'Son değiştirilme', notAvailable: 'Yok', copyContent: 'İçeriği kopyala',
    clipboardCopyFailed: 'Panoya kopyalanamadı.',
    toast: {
      downloadedFile: '"{name}" dosyası indirildi!', copiedContent: 'İçerik panoya kopyalandı!',
      copiedFile: '"{name}" dosyası kopyalandı! İstediğiniz yere yapıştırın.', readyToMove: '"{name}" dosyası taşınmaya hazır!',
      nothingToPaste: 'Yapıştırılacak bir şey yok', copiedPaste: '"{name}" kopyalandı!', movedPaste: '"{name}" taşındı!',
      deleting: 'Siliniyor...', deletedFile: '"{name}" dosyası silindi!', deleteFailed: 'Dosya silinirken hata oluştu',
      missingProject: 'Hata: kullanılabilir proje yok', uploadedFile: '"{name}" dosyası başarıyla yüklendi!',
      uploadFailed: '"{name}" yüklenirken hata oluştu', folderNotSelected: 'Hata: klasör seçilmedi',
      folderEmpty: 'Klasör boş veya doğru şekilde seçilmedi',
      loadingFolder: '"{name}" klasörü yükleniyor... ({count} dosya)',
      folderUploaded: '✅ "{name}" klasörü yüklendi: {count}/{total} dosya',
      folderUploadFailed: 'Klasör yüklenirken hata oluştu', fileReadFailed: '"{name}" dosyası okunamadı',
      renamedFile: 'Dosya yeniden adlandırıldı!', deletedExplorerFile: 'Dosya silindi!', savedFile: 'Dosya kaydedildi!',
      savedFolder: 'Klasör kaydedildi!', copiedTemplate: 'Şablon kopyalandı!',
      copiedTemplateVisible: 'Şablon kopyalandı! "Kopyalanan şablon" bölümünde görüntülenir',
      copyTemplateFailed: 'Şablon kopyalanamadı.', downloadedBackup: '"{name}" yedeği indirildi!',
    },
    explorer: {
      saveFile: 'Dosyayı kaydet', renameFile: 'Dosyayı yeniden adlandır', refreshPreview: 'Önizlemeyi yenile',
      closeFile: 'Dosyayı kapat', deleteFile: 'Dosyayı sil', saveFolder: 'Klasörü kaydet',
      deleteFolder: 'Klasörü sil', closeFolder: 'Klasörü kapat', closeSelectedFile: 'Seçili dosyayı kapat',
      closeFolderNamed: '{name} klasörünü kapat', renameDialog: 'Yeniden adlandır', newName: 'Yeni ad',
      cancel: 'İptal', confirmDelete: 'Silmeyi onayla', confirmDeleteNamed: '{name} öğesini silmek istediğinizden emin misiniz?',
      empty: 'Henüz dosya veya klasör yok.', expandFolder: '{name} klasörünü genişlet', collapseFolder: '{name} klasörünü daralt',
    },
    green: {
      projectStats: 'Proje istatistikleri', filesLabel: 'Dosyalar', linesLabel: 'Kod satırları',
      editingLabel: 'Düzenleme süresi', sizeLabel: 'Proje boyutu', minutes: 'dk', pricePeriod: '/ay',
      tipHeading: '💡 Günün ipucu', offerHeading: '🎁 Özel teklif', seeMore: '→ Daha fazla bilgi', close: 'Kapat',
      tips: [
        ['⚡ Hızlı kısayol', 'Komut paletini açmak için Ctrl+K tuşlarını kullanın'],
        ['📁 Dosyaları düzenleyin', 'Daha iyi önizleme için dosyaları klasörlerde gruplayın'],
        ['🚀 Şablonlar', 'Daha hızlı başlamak için şablonları kullanın'],
        ['🎨 Koyu tema', 'Uzun çalışma oturumları için ideal'],
        ['💾 Otomatik yedekleme', 'Güvenlik için otomatik yedeklemeleri ayarlayın'],
      ],
      dealDescriptions: ['Sınırsız güvenlik açığı taraması', 'API testi ve iş birliği', 'Gerçek zamanlı performans analizleri'],
    },
  },
  sv: {
    loginRequired: 'Inloggning krävs', loginPrompt: 'Logga in för att hantera dina filer och mappar.', login: 'Logga in',
    pageTitle: 'Filhantering', pageSubtitle: 'Organisera och hantera dina filer och mappar',
    uploadFolder: 'Ladda upp mapp', uploading: 'Laddar upp...', selectFolderTitle: 'Välj en mapp att ladda upp',
    copy: 'Kopiera', copySelectedTitle: 'Kopiera vald fil', move: 'Flytta', moveSelectedTitle: 'Flytta vald fil',
    paste: 'Klistra in', pasteTitle: 'Klistra in kopierad/flyttad fil', delete: 'Ta bort', deleteSelectedTitle: 'Ta bort vald fil',
    loadedFolders: 'Uppladdade mappar', fileCount: 'filer', openInEditorTitle: 'Öppna med File Editor', editor: 'Redigerare',
    copiedTemplate: 'Kopierad mall', download: 'Ladda ned', purchasedTemplates: 'Köpta mallar',
    copyTitle: 'Kopiera', expires: 'Upphör:', noPurchasedTemplates: 'Inga mallar köpta',
    onlineBackup: 'Säkerhetskopia online', loading: 'Laddar...', noBackups: 'Inga sparade säkerhetskopior',
    downloadBackupTitle: 'Ladda ned säkerhetskopia', fileDetails: 'Fildetaljer', name: 'Namn', size: 'Storlek',
    type: 'Typ', lastModified: 'Senast ändrad', notAvailable: 'Ej tillgänglig', copyContent: 'Kopiera innehåll',
    clipboardCopyFailed: 'Det gick inte att kopiera till urklipp.',
    toast: {
      downloadedFile: 'Filen "{name}" har laddats ned!', copiedContent: 'Innehållet har kopierats till urklipp!',
      copiedFile: 'Filen "{name}" har kopierats! Klistra in den där du vill.', readyToMove: 'Filen "{name}" är redo att flyttas!',
      nothingToPaste: 'Inget att klistra in', copiedPaste: '"{name}" kopierad!', movedPaste: '"{name}" flyttad!',
      deleting: 'Tar bort...', deletedFile: 'Filen "{name}" har tagits bort!', deleteFailed: 'Det gick inte att ta bort filen',
      missingProject: 'Fel: inget projekt är tillgängligt', uploadedFile: 'Filen "{name}" har laddats upp!',
      uploadFailed: 'Det gick inte att ladda upp "{name}"', folderNotSelected: 'Fel: ingen mapp har valts',
      folderEmpty: 'Mappen är tom eller valdes inte korrekt',
      loadingFolder: 'Laddar upp mappen "{name}"... ({count} filer)',
      folderUploaded: '✅ Mappen "{name}" har laddats upp: {count}/{total} filer',
      folderUploadFailed: 'Det gick inte att ladda upp mappen', fileReadFailed: 'Det gick inte att läsa filen "{name}"',
      renamedFile: 'Filen har bytt namn!', deletedExplorerFile: 'Filen har tagits bort!', savedFile: 'Filen har sparats!',
      savedFolder: 'Mappen har sparats!', copiedTemplate: 'Mallen har kopierats!',
      copiedTemplateVisible: 'Mallen har kopierats! Den visas i avsnittet "Kopierad mall"',
      copyTemplateFailed: 'Det gick inte att kopiera mallen.', downloadedBackup: 'Säkerhetskopian "{name}" har laddats ned!',
    },
    explorer: {
      saveFile: 'Spara fil', renameFile: 'Byt namn på fil', refreshPreview: 'Uppdatera förhandsgranskning',
      closeFile: 'Stäng fil', deleteFile: 'Ta bort fil', saveFolder: 'Spara mapp',
      deleteFolder: 'Ta bort mapp', closeFolder: 'Stäng mapp', closeSelectedFile: 'Stäng vald fil',
      closeFolderNamed: 'Stäng mappen {name}', renameDialog: 'Byt namn', newName: 'Nytt namn',
      cancel: 'Avbryt', confirmDelete: 'Bekräfta borttagning', confirmDeleteNamed: 'Vill du verkligen ta bort {name}?',
      empty: 'Det finns inga filer eller mappar ännu.', expandFolder: 'Expandera mappen {name}', collapseFolder: 'Fäll ihop mappen {name}',
    },
    green: {
      projectStats: 'Projektstatistik', filesLabel: 'Filer', linesLabel: 'Kodrader',
      editingLabel: 'Redigeringstid', sizeLabel: 'Projektstorlek', minutes: 'min', pricePeriod: '/månad',
      tipHeading: '💡 Dagens tips', offerHeading: '🎁 Exklusivt erbjudande', seeMore: '→ Läs mer', close: 'Stäng',
      tips: [
        ['⚡ Snabbgenväg', 'Använd Ctrl+K för att öppna kommandopaletten'],
        ['📁 Organisera filer', 'Gruppera filer i mappar för bättre förhandsgranskning'],
        ['🚀 Mallar', 'Använd mallar för att komma igång snabbare'],
        ['🎨 Mörkt tema', 'Perfekt för långa arbetspass'],
        ['💾 Automatisk säkerhetskopia', 'Ställ in automatiska säkerhetskopior för trygghet'],
      ],
      dealDescriptions: ['Obegränsad sårbarhetsskanning', 'API-testning och samarbete', 'Prestandainsikter i realtid'],
    },
  },
  da: {
    loginRequired: 'Login påkrævet', loginPrompt: 'Log ind for at administrere dine filer og mapper.', login: 'Log ind',
    pageTitle: 'Filhåndtering', pageSubtitle: 'Organisér og administrér dine filer og mapper',
    uploadFolder: 'Upload mappe', uploading: 'Uploader...', selectFolderTitle: 'Vælg en mappe, der skal uploades',
    copy: 'Kopiér', copySelectedTitle: 'Kopiér valgt fil', move: 'Flyt', moveSelectedTitle: 'Flyt valgt fil',
    paste: 'Indsæt', pasteTitle: 'Indsæt kopieret/flyttet fil', delete: 'Slet', deleteSelectedTitle: 'Slet valgt fil',
    loadedFolders: 'Uploadede mapper', fileCount: 'filer', openInEditorTitle: 'Åbn med File Editor', editor: 'Editor',
    copiedTemplate: 'Kopieret skabelon', download: 'Download', purchasedTemplates: 'Købte skabeloner',
    copyTitle: 'Kopiér', expires: 'Udløber:', noPurchasedTemplates: 'Ingen købte skabeloner',
    onlineBackup: 'Onlinebackup', loading: 'Indlæser...', noBackups: 'Ingen gemte sikkerhedskopier',
    downloadBackupTitle: 'Download sikkerhedskopi', fileDetails: 'Fildetaljer', name: 'Navn', size: 'Størrelse',
    type: 'Type', lastModified: 'Senest ændret', notAvailable: 'Ikke tilgængelig', copyContent: 'Kopiér indhold',
    clipboardCopyFailed: 'Kunne ikke kopiere til udklipsholderen.',
    toast: {
      downloadedFile: 'Filen "{name}" er downloadet!', copiedContent: 'Indholdet er kopieret til udklipsholderen!',
      copiedFile: 'Filen "{name}" er kopieret! Indsæt den, hvor du vil.', readyToMove: 'Filen "{name}" er klar til at blive flyttet!',
      nothingToPaste: 'Intet at indsætte', copiedPaste: '"{name}" er kopieret!', movedPaste: '"{name}" er flyttet!',
      deleting: 'Sletter...', deletedFile: 'Filen "{name}" er slettet!', deleteFailed: 'Fejl under sletning af filen',
      missingProject: 'Fejl: intet projekt er tilgængeligt', uploadedFile: 'Filen "{name}" er uploadet!',
      uploadFailed: 'Fejl under upload af "{name}"', folderNotSelected: 'Fejl: ingen mappe er valgt',
      folderEmpty: 'Mappen er tom eller blev ikke valgt korrekt',
      loadingFolder: 'Uploader mappen "{name}"... ({count} filer)',
      folderUploaded: '✅ Mappen "{name}" er uploadet: {count}/{total} filer',
      folderUploadFailed: 'Fejl under upload af mappen', fileReadFailed: 'Filen "{name}" kunne ikke læses',
      renamedFile: 'Filen er omdøbt!', deletedExplorerFile: 'Filen er slettet!', savedFile: 'Filen er gemt!',
      savedFolder: 'Mappen er gemt!', copiedTemplate: 'Skabelonen er kopieret!',
      copiedTemplateVisible: 'Skabelonen er kopieret! Den vises i afsnittet "Kopieret skabelon"',
      copyTemplateFailed: 'Skabelonen kunne ikke kopieres.', downloadedBackup: 'Sikkerhedskopien "{name}" er downloadet!',
    },
    explorer: {
      saveFile: 'Gem fil', renameFile: 'Omdøb fil', refreshPreview: 'Opdater forhåndsvisning',
      closeFile: 'Luk fil', deleteFile: 'Slet fil', saveFolder: 'Gem mappe',
      deleteFolder: 'Slet mappe', closeFolder: 'Luk mappe', closeSelectedFile: 'Luk valgt fil',
      closeFolderNamed: 'Luk mappen {name}', renameDialog: 'Omdøb', newName: 'Nyt navn',
      cancel: 'Annuller', confirmDelete: 'Bekræft sletning', confirmDeleteNamed: 'Er du sikker på, at du vil slette {name}?',
      empty: 'Der er ingen filer eller mapper endnu.', expandFolder: 'Udvid mappen {name}', collapseFolder: 'Skjul mappen {name}',
    },
    green: {
      projectStats: 'Projektstatistik', filesLabel: 'Filer', linesLabel: 'Kodelinjer',
      editingLabel: 'Redigeringstid', sizeLabel: 'Projektstørrelse', minutes: 'min.', pricePeriod: '/måned',
      tipHeading: '💡 Dagens tip', offerHeading: '🎁 Eksklusivt tilbud', seeMore: '→ Få mere at vide', close: 'Luk',
      tips: [
        ['⚡ Hurtig genvej', 'Brug Ctrl+K til at åbne kommandopaletten'],
        ['📁 Organisér filer', 'Gruppér filer i mapper for en bedre forhåndsvisning'],
        ['🚀 Skabeloner', 'Brug skabeloner for at komme hurtigere i gang'],
        ['🎨 Mørkt tema', 'Perfekt til lange arbejdssessioner'],
        ['💾 Automatisk sikkerhedskopi', 'Konfigurér automatiske sikkerhedskopier for ekstra tryghed'],
      ],
      dealDescriptions: ['Ubegrænset scanning efter sårbarheder', 'API-test og samarbejde', 'Ydeevneindsigt i realtid'],
    },
  },
  no: {
    loginRequired: 'Innlogging kreves', loginPrompt: 'Logg inn for å administrere filene og mappene dine.', login: 'Logg inn',
    pageTitle: 'Filbehandling', pageSubtitle: 'Organiser og administrer filene og mappene dine',
    uploadFolder: 'Last opp mappe', uploading: 'Laster opp...', selectFolderTitle: 'Velg en mappe som skal lastes opp',
    copy: 'Kopier', copySelectedTitle: 'Kopier valgt fil', move: 'Flytt', moveSelectedTitle: 'Flytt valgt fil',
    paste: 'Lim inn', pasteTitle: 'Lim inn kopiert/flyttet fil', delete: 'Slett', deleteSelectedTitle: 'Slett valgt fil',
    loadedFolders: 'Opplastede mapper', fileCount: 'filer', openInEditorTitle: 'Åpne med File Editor', editor: 'Redigerer',
    copiedTemplate: 'Kopiert mal', download: 'Last ned', purchasedTemplates: 'Kjøpte maler',
    copyTitle: 'Kopier', expires: 'Utløper:', noPurchasedTemplates: 'Ingen kjøpte maler',
    onlineBackup: 'Sikkerhetskopi på nett', loading: 'Laster...', noBackups: 'Ingen lagrede sikkerhetskopier',
    downloadBackupTitle: 'Last ned sikkerhetskopi', fileDetails: 'Fildetaljer', name: 'Navn', size: 'Størrelse',
    type: 'Type', lastModified: 'Sist endret', notAvailable: 'Ikke tilgjengelig', copyContent: 'Kopier innhold',
    clipboardCopyFailed: 'Kunne ikke kopiere til utklippstavlen.',
    toast: {
      downloadedFile: 'Filen «{name}» er lastet ned!', copiedContent: 'Innholdet er kopiert til utklippstavlen!',
      copiedFile: 'Filen «{name}» er kopiert! Lim den inn der du vil.', readyToMove: 'Filen «{name}» er klar til å flyttes!',
      nothingToPaste: 'Ingenting å lime inn', copiedPaste: '«{name}» er kopiert!', movedPaste: '«{name}» er flyttet!',
      deleting: 'Sletter...', deletedFile: 'Filen «{name}» er slettet!', deleteFailed: 'Feil ved sletting av filen',
      missingProject: 'Feil: ingen prosjekter er tilgjengelige', uploadedFile: 'Filen «{name}» er lastet opp!',
      uploadFailed: 'Feil ved opplasting av «{name}»', folderNotSelected: 'Feil: ingen mappe er valgt',
      folderEmpty: 'Mappen er tom eller ble ikke valgt riktig',
      loadingFolder: 'Laster opp mappen «{name}»... ({count} filer)',
      folderUploaded: '✅ Mappen «{name}» er lastet opp: {count}/{total} filer',
      folderUploadFailed: 'Feil ved opplasting av mappen', fileReadFailed: 'Filen «{name}» kunne ikke leses',
      renamedFile: 'Filen har fått nytt navn!', deletedExplorerFile: 'Filen er slettet!', savedFile: 'Filen er lagret!',
      savedFolder: 'Mappen er lagret!', copiedTemplate: 'Malen er kopiert!',
      copiedTemplateVisible: 'Malen er kopiert! Den vises i delen «Kopiert mal»',
      copyTemplateFailed: 'Malen kunne ikke kopieres.', downloadedBackup: 'Sikkerhetskopien «{name}» er lastet ned!',
    },
    explorer: {
      saveFile: 'Lagre fil', renameFile: 'Gi filen nytt navn', refreshPreview: 'Oppdater forhåndsvisning',
      closeFile: 'Lukk fil', deleteFile: 'Slett fil', saveFolder: 'Lagre mappe',
      deleteFolder: 'Slett mappe', closeFolder: 'Lukk mappe', closeSelectedFile: 'Lukk valgt fil',
      closeFolderNamed: 'Lukk mappen {name}', renameDialog: 'Gi nytt navn', newName: 'Nytt navn',
      cancel: 'Avbryt', confirmDelete: 'Bekreft sletting', confirmDeleteNamed: 'Vil du slette {name}?',
      empty: 'Det finnes ingen filer eller mapper ennå.', expandFolder: 'Utvid mappen {name}', collapseFolder: 'Skjul mappen {name}',
    },
    green: {
      projectStats: 'Prosjektstatistikk', filesLabel: 'Filer', linesLabel: 'Kodelinjer',
      editingLabel: 'Redigeringstid', sizeLabel: 'Prosjektstørrelse', minutes: 'min', pricePeriod: '/måned',
      tipHeading: '💡 Dagens tips', offerHeading: '🎁 Eksklusivt tilbud', seeMore: '→ Finn ut mer', close: 'Lukk',
      tips: [
        ['⚡ Rask snarvei', 'Bruk Ctrl+K for å åpne kommandopaletten'],
        ['📁 Organiser filer', 'Samle filer i mapper for en bedre forhåndsvisning'],
        ['🚀 Maler', 'Bruk maler for å komme raskere i gang'],
        ['🎨 Mørkt tema', 'Perfekt for lange arbeidsøkter'],
        ['💾 Automatisk sikkerhetskopi', 'Konfigurer automatiske sikkerhetskopier for trygghet'],
      ],
      dealDescriptions: ['Ubegrenset skanning etter sårbarheter', 'API-testing og samarbeid', 'Ytelsesinnsikt i sanntid'],
    },
  },
  fi: {
    loginRequired: 'Kirjautuminen vaaditaan', loginPrompt: 'Kirjaudu sisään hallitaksesi tiedostojasi ja kansioitasi.', login: 'Kirjaudu sisään',
    pageTitle: 'Tiedostojen hallinta', pageSubtitle: 'Järjestä ja hallitse tiedostojasi ja kansioitasi',
    uploadFolder: 'Lataa kansio', uploading: 'Ladataan...', selectFolderTitle: 'Valitse ladattava kansio',
    copy: 'Kopioi', copySelectedTitle: 'Kopioi valittu tiedosto', move: 'Siirrä', moveSelectedTitle: 'Siirrä valittu tiedosto',
    paste: 'Liitä', pasteTitle: 'Liitä kopioitu tai siirretty tiedosto', delete: 'Poista', deleteSelectedTitle: 'Poista valittu tiedosto',
    loadedFolders: 'Ladatut kansiot', fileCount: 'tiedostoa', openInEditorTitle: 'Avaa File Editorissa', editor: 'Editori',
    copiedTemplate: 'Kopioitu malli', download: 'Lataa', purchasedTemplates: 'Ostetut mallit',
    copyTitle: 'Kopioi', expires: 'Vanhenee:', noPurchasedTemplates: 'Ei ostettuja malleja',
    onlineBackup: 'Verkkovarmuuskopio', loading: 'Ladataan...', noBackups: 'Ei tallennettuja varmuuskopioita',
    downloadBackupTitle: 'Lataa varmuuskopio', fileDetails: 'Tiedoston tiedot', name: 'Nimi', size: 'Koko',
    type: 'Tyyppi', lastModified: 'Viimeksi muokattu', notAvailable: 'Ei saatavilla', copyContent: 'Kopioi sisältö',
    clipboardCopyFailed: 'Kopiointi leikepöydälle epäonnistui.',
    toast: {
      downloadedFile: 'Tiedosto ”{name}” ladattu!', copiedContent: 'Sisältö kopioitu leikepöydälle!',
      copiedFile: 'Tiedosto ”{name}” kopioitu! Liitä se haluamaasi paikkaan.', readyToMove: 'Tiedosto ”{name}” on valmis siirrettäväksi!',
      nothingToPaste: 'Ei liitettävää', copiedPaste: '”{name}” kopioitu!', movedPaste: '”{name}” siirretty!',
      deleting: 'Poistetaan...', deletedFile: 'Tiedosto ”{name}” poistettu!', deleteFailed: 'Tiedoston poistaminen epäonnistui',
      missingProject: 'Virhe: projektia ei ole saatavilla', uploadedFile: 'Tiedosto ”{name}” ladattiin onnistuneesti!',
      uploadFailed: 'Tiedoston ”{name}” lataaminen epäonnistui', folderNotSelected: 'Virhe: kansiota ei valittu',
      folderEmpty: 'Kansio on tyhjä tai sitä ei valittu oikein',
      loadingFolder: 'Ladataan kansiota ”{name}”... ({count} tiedostoa)',
      folderUploaded: '✅ Kansio ”{name}” ladattu: {count}/{total} tiedostoa',
      folderUploadFailed: 'Kansion lataaminen epäonnistui', fileReadFailed: 'Tiedoston ”{name}” lukeminen epäonnistui',
      renamedFile: 'Tiedosto nimettiin uudelleen!', deletedExplorerFile: 'Tiedosto poistettu!', savedFile: 'Tiedosto tallennettu!',
      savedFolder: 'Kansio tallennettu!', copiedTemplate: 'Malli kopioitu!',
      copiedTemplateVisible: 'Malli kopioitu! Se näkyy osiossa ”Kopioitu malli”',
      copyTemplateFailed: 'Mallin kopiointi epäonnistui.', downloadedBackup: 'Varmuuskopio ”{name}” ladattu!',
    },
    explorer: {
      saveFile: 'Tallenna tiedosto', renameFile: 'Nimeä tiedosto uudelleen', refreshPreview: 'Päivitä esikatselu',
      closeFile: 'Sulje tiedosto', deleteFile: 'Poista tiedosto', saveFolder: 'Tallenna kansio',
      deleteFolder: 'Poista kansio', closeFolder: 'Sulje kansio', closeSelectedFile: 'Sulje valittu tiedosto',
      closeFolderNamed: 'Sulje kansio {name}', renameDialog: 'Nimeä uudelleen', newName: 'Uusi nimi',
      cancel: 'Peruuta', confirmDelete: 'Vahvista poisto', confirmDeleteNamed: 'Haluatko varmasti poistaa kohteen {name}?',
      empty: 'Tiedostoja tai kansioita ei vielä ole.', expandFolder: 'Laajenna kansio {name}', collapseFolder: 'Supista kansio {name}',
    },
    green: {
      projectStats: 'Projektin tilastot', filesLabel: 'Tiedostot', linesLabel: 'Koodirivit',
      editingLabel: 'Muokkausaika', sizeLabel: 'Projektin koko', minutes: 'min', pricePeriod: '/kk',
      tipHeading: '💡 Päivän vinkki', offerHeading: '🎁 Erikoistarjous', seeMore: '→ Lue lisää', close: 'Sulje',
      tips: [
        ['⚡ Pikakomento', 'Avaa komentovalikko painamalla Ctrl+K'],
        ['📁 Järjestä tiedostot', 'Ryhmittele tiedostot kansioihin esikatselun parantamiseksi'],
        ['🚀 Mallit', 'Aloita nopeammin mallien avulla'],
        ['🎨 Tumma teema', 'Sopii pitkiin työskentelyjaksoihin'],
        ['💾 Automaattinen varmuuskopiointi', 'Määritä automaattiset varmuuskopiot turvallisuuden vuoksi'],
      ],
      dealDescriptions: ['Rajoittamaton haavoittuvuuksien skannaus', 'API-testaus ja yhteistyö', 'Reaaliaikaiset suorituskykytiedot'],
    },
  },
  uk: {
    loginRequired: 'Потрібен вхід', loginPrompt: 'Увійдіть, щоб керувати файлами й папками.', login: 'Увійти',
    pageTitle: 'Керування файлами', pageSubtitle: 'Упорядковуйте файли й папки та керуйте ними',
    uploadFolder: 'Завантажити папку', uploading: 'Завантаження...', selectFolderTitle: 'Виберіть папку для завантаження',
    copy: 'Копіювати', copySelectedTitle: 'Копіювати вибраний файл', move: 'Перемістити', moveSelectedTitle: 'Перемістити вибраний файл',
    paste: 'Вставити', pasteTitle: 'Вставити скопійований/переміщений файл', delete: 'Видалити', deleteSelectedTitle: 'Видалити вибраний файл',
    loadedFolders: 'Завантажені папки', fileCount: 'файлів', openInEditorTitle: 'Відкрити у File Editor', editor: 'Редактор',
    copiedTemplate: 'Скопійований шаблон', download: 'Завантажити', purchasedTemplates: 'Придбані шаблони',
    copyTitle: 'Копіювати', expires: 'Діє до:', noPurchasedTemplates: 'Немає придбаних шаблонів',
    onlineBackup: 'Онлайн-резервна копія', loading: 'Завантаження...', noBackups: 'Збережених копій немає',
    downloadBackupTitle: 'Завантажити резервну копію', fileDetails: 'Відомості про файл', name: 'Назва', size: 'Розмір',
    type: 'Тип', lastModified: 'Остання зміна', notAvailable: 'Н/Д', copyContent: 'Копіювати вміст',
    clipboardCopyFailed: 'Не вдалося скопіювати до буфера обміну.',
    toast: {
      downloadedFile: 'Файл «{name}» завантажено!', copiedContent: 'Вміст скопійовано до буфера обміну!',
      copiedFile: 'Файл «{name}» скопійовано! Вставте його в потрібне місце.', readyToMove: 'Файл «{name}» готовий до переміщення!',
      nothingToPaste: 'Немає що вставляти', copiedPaste: '«{name}» скопійовано!', movedPaste: '«{name}» переміщено!',
      deleting: 'Видалення...', deletedFile: 'Файл «{name}» видалено!', deleteFailed: 'Помилка під час видалення файлу',
      missingProject: 'Помилка: проєкт недоступний', uploadedFile: 'Файл «{name}» успішно завантажено!',
      uploadFailed: 'Помилка під час завантаження «{name}»', folderNotSelected: 'Помилка: папку не вибрано',
      folderEmpty: 'Папка порожня або вибрана неправильно',
      loadingFolder: 'Завантаження папки «{name}»... (файлів: {count})',
      folderUploaded: '✅ Папку «{name}» завантажено: {count}/{total} файлів',
      folderUploadFailed: 'Помилка під час завантаження папки', fileReadFailed: 'Не вдалося прочитати файл «{name}»',
      renamedFile: 'Файл перейменовано!', deletedExplorerFile: 'Файл видалено!', savedFile: 'Файл збережено!',
      savedFolder: 'Папку збережено!', copiedTemplate: 'Шаблон скопійовано!',
      copiedTemplateVisible: 'Шаблон скопійовано! Він відображається в розділі «Скопійований шаблон»',
      copyTemplateFailed: 'Не вдалося скопіювати шаблон.', downloadedBackup: 'Резервну копію «{name}» завантажено!',
    },
    explorer: {
      saveFile: 'Зберегти файл', renameFile: 'Перейменувати файл', refreshPreview: 'Оновити попередній перегляд',
      closeFile: 'Закрити файл', deleteFile: 'Видалити файл', saveFolder: 'Зберегти папку',
      deleteFolder: 'Видалити папку', closeFolder: 'Закрити папку', closeSelectedFile: 'Закрити вибраний файл',
      closeFolderNamed: 'Закрити папку {name}', renameDialog: 'Перейменувати', newName: 'Нова назва',
      cancel: 'Скасувати', confirmDelete: 'Підтвердьте видалення', confirmDeleteNamed: 'Ви справді хочете видалити {name}?',
      empty: 'Файлів і папок поки немає.', expandFolder: 'Розгорнути папку {name}', collapseFolder: 'Згорнути папку {name}',
    },
    green: {
      projectStats: 'Статистика проєкту', filesLabel: 'Файли', linesLabel: 'Рядки коду',
      editingLabel: 'Час редагування', sizeLabel: 'Розмір проєкту', minutes: 'хв', pricePeriod: '/міс.',
      tipHeading: '💡 Порада дня', offerHeading: '🎁 Ексклюзивна пропозиція', seeMore: '→ Докладніше', close: 'Закрити',
      tips: [
        ['⚡ Швидке сполучення', 'Натисніть Ctrl+K, щоб відкрити палітру команд'],
        ['📁 Упорядкуйте файли', 'Групуйте файли в папки для кращого перегляду'],
        ['🚀 Шаблони', 'Починайте швидше за допомогою шаблонів'],
        ['🎨 Темна тема', 'Ідеально для тривалих робочих сеансів'],
        ['💾 Автоматична копія', 'Налаштуйте автоматичне резервне копіювання'],
      ],
      dealDescriptions: ['Необмежене сканування вразливостей', 'Тестування API та спільна робота', 'Аналітика продуктивності в реальному часі'],
    },
  },
  cs: {
    loginRequired: 'Je vyžadováno přihlášení', loginPrompt: 'Přihlaste se ke správě souborů a složek.', login: 'Přihlásit se',
    pageTitle: 'Správa souborů', pageSubtitle: 'Organizujte a spravujte své soubory a složky',
    uploadFolder: 'Nahrát složku', uploading: 'Nahrávání...', selectFolderTitle: 'Vyberte složku k nahrání',
    copy: 'Kopírovat', copySelectedTitle: 'Kopírovat vybraný soubor', move: 'Přesunout', moveSelectedTitle: 'Přesunout vybraný soubor',
    paste: 'Vložit', pasteTitle: 'Vložit zkopírovaný/přesunutý soubor', delete: 'Odstranit', deleteSelectedTitle: 'Odstranit vybraný soubor',
    loadedFolders: 'Nahrané složky', fileCount: 'soubory', openInEditorTitle: 'Otevřít v File Editor', editor: 'Editor',
    copiedTemplate: 'Zkopírovaná šablona', download: 'Stáhnout', purchasedTemplates: 'Zakoupené šablony',
    copyTitle: 'Kopírovat', expires: 'Platnost do:', noPurchasedTemplates: 'Žádné zakoupené šablony',
    onlineBackup: 'Online záloha', loading: 'Načítání...', noBackups: 'Nejsou uloženy žádné zálohy',
    downloadBackupTitle: 'Stáhnout zálohu', fileDetails: 'Podrobnosti souboru', name: 'Název', size: 'Velikost',
    type: 'Typ', lastModified: 'Poslední změna', notAvailable: 'Není k dispozici', copyContent: 'Kopírovat obsah',
    clipboardCopyFailed: 'Kopírování do schránky se nezdařilo.',
    toast: {
      downloadedFile: 'Soubor „{name}“ byl stažen!', copiedContent: 'Obsah byl zkopírován do schránky!',
      copiedFile: 'Soubor „{name}“ byl zkopírován! Vložte ho, kam chcete.', readyToMove: 'Soubor „{name}“ je připraven k přesunutí!',
      nothingToPaste: 'Není co vložit', copiedPaste: '„{name}“ bylo zkopírováno!', movedPaste: '„{name}“ bylo přesunuto!',
      deleting: 'Odstraňování...', deletedFile: 'Soubor „{name}“ byl odstraněn!', deleteFailed: 'Při odstraňování souboru došlo k chybě',
      missingProject: 'Chyba: není k dispozici žádný projekt', uploadedFile: 'Soubor „{name}“ byl úspěšně nahrán!',
      uploadFailed: 'Při nahrávání „{name}“ došlo k chybě', folderNotSelected: 'Chyba: nebyla vybrána složka',
      folderEmpty: 'Složka je prázdná nebo nebyla správně vybrána',
      loadingFolder: 'Nahrávání složky „{name}“... (souborů: {count})',
      folderUploaded: '✅ Složka „{name}“ byla nahrána: {count}/{total} souborů',
      folderUploadFailed: 'Při nahrávání složky došlo k chybě', fileReadFailed: 'Soubor „{name}“ se nepodařilo přečíst',
      renamedFile: 'Soubor byl přejmenován!', deletedExplorerFile: 'Soubor byl odstraněn!', savedFile: 'Soubor byl uložen!',
      savedFolder: 'Složka byla uložena!', copiedTemplate: 'Šablona byla zkopírována!',
      copiedTemplateVisible: 'Šablona byla zkopírována! Zobrazuje se v části „Zkopírovaná šablona“',
      copyTemplateFailed: 'Šablonu se nepodařilo zkopírovat.', downloadedBackup: 'Záloha „{name}“ byla stažena!',
    },
    explorer: {
      saveFile: 'Uložit soubor', renameFile: 'Přejmenovat soubor', refreshPreview: 'Obnovit náhled',
      closeFile: 'Zavřít soubor', deleteFile: 'Odstranit soubor', saveFolder: 'Uložit složku',
      deleteFolder: 'Odstranit složku', closeFolder: 'Zavřít složku', closeSelectedFile: 'Zavřít vybraný soubor',
      closeFolderNamed: 'Zavřít složku {name}', renameDialog: 'Přejmenovat', newName: 'Nový název',
      cancel: 'Zrušit', confirmDelete: 'Potvrdit odstranění', confirmDeleteNamed: 'Opravdu chcete odstranit {name}?',
      empty: 'Zatím tu nejsou žádné soubory ani složky.', expandFolder: 'Rozbalit složku {name}', collapseFolder: 'Sbalit složku {name}',
    },
    green: {
      projectStats: 'Statistiky projektu', filesLabel: 'Soubory', linesLabel: 'Řádky kódu',
      editingLabel: 'Čas úprav', sizeLabel: 'Velikost projektu', minutes: 'min', pricePeriod: '/měsíc',
      tipHeading: '💡 Tip dne', offerHeading: '🎁 Exkluzivní nabídka', seeMore: '→ Další informace', close: 'Zavřít',
      tips: [
        ['⚡ Rychlá zkratka', 'Otevřete paletu příkazů pomocí Ctrl+K'],
        ['📁 Organizace souborů', 'Seskupte soubory do složek pro lepší náhled'],
        ['🚀 Šablony', 'Začněte rychleji pomocí šablon'],
        ['🎨 Tmavý motiv', 'Ideální pro dlouhé pracovní relace'],
        ['💾 Automatická záloha', 'Nastavte automatické zálohování pro větší bezpečí'],
      ],
      dealDescriptions: ['Neomezené skenování zranitelností', 'Testování API a spolupráce', 'Přehledy výkonu v reálném čase'],
    },
  },
};

export function formatFilesCopy(template: string, values: Record<string, string | number> = {}): string {
  return template.replace(/\{(\w+)\}/g, (_, key: string) => String(values[key] ?? `{${key}}`));
}
