type PricingPageCopy = {
  trialDetails: string;
  proDetails: string;
  freeDetails: string;
  freeAfterTrial: string;
  bonusHeading: string;
  bonusExplanation: string;
  bonusCap: string;
  stripeButton: string;
  paypalButton: string;
  schoolStatus: string;
  subscriptionStatus: string;
  paymentError: string;
  paypalError: string;
  contactIntro: string;
};

export const pricingPageCopy: Record<string, PricingPageCopy> = {
  it: {
    trialDetails: "Prova gratuita di 60 giorni. Alla scadenza resta disponibile il piano Free; Pro si attiva solo se scegli di abbonarti.",
    proDetails: "Tutte le funzionalità Pro, supporto prioritario e vantaggi premium per crescere con la piattaforma.",
    freeDetails: "Dopo la prova, il piano Free mantiene il backup locale; AI e backup online non sono inclusi.",
    freeAfterTrial: "Il piano Free si applica dopo i 60 giorni di prova.",
    bonusHeading: "Bonus fedeltà",
    bonusExplanation: "Più usi il sito, più risparmi: ogni bonus può applicare un credito di 2 € al rinnovo, fino a 2 bonus in ogni periodo di 30 giorni.",
    bonusCap: "Fino a 2 bonus in ogni periodo di 30 giorni.",
    stripeButton: "Completa l'ordine",
    paypalButton: "Completa l'ordine con PayPal",
    schoolStatus: "Accesso Pro attivo tramite il programma scuole.",
    subscriptionStatus: "Il tuo abbonamento Pro è attivo.",
    paymentError: "Non è stato possibile avviare il checkout. Riprova o contatta il supporto.",
    paypalError: "PayPal non è disponibile al momento. Riprova o scegli Stripe.",
    contactIntro: "Per domande su piani o pagamenti, contattaci tramite il modulo di supporto.",
  },
  en: {
    trialDetails: "Try Pro free for 60 days. The Free plan remains available afterward; a Pro subscription starts only if you choose to subscribe.",
    proDetails: "All Pro features, priority support, and premium benefits to grow with the platform.",
    freeDetails: "After the trial, the Free plan retains local backups; AI and online backups are not included.",
    freeAfterTrial: "The Free plan applies automatically after the 60-day trial.",
    bonusHeading: "Loyalty bonus",
    bonusExplanation: "The more you use the platform, the more you save: each bonus can apply a €2 credit toward renewal, up to 2 bonuses in each 30-day period.",
    bonusCap: "Up to 2 bonus credits in each 30-day period.",
    stripeButton: "Complete order",
    paypalButton: "Complete order with PayPal",
    schoolStatus: "Pro access is active through the school program.",
    subscriptionStatus: "Your Pro subscription is active.",
    paymentError: "Checkout could not be started. Please try again or contact support.",
    paypalError: "PayPal is currently unavailable. Please try again or choose Stripe.",
    contactIntro: "For questions about plans or payments, contact us using the support form.",
  },
  es: {
    trialDetails: "Prueba Pro gratis durante 60 días. Después seguirá disponible el plan Free; Pro solo se activa si decides suscribirte.",
    proDetails: "Todas las funciones Pro, soporte prioritario y ventajas premium para crecer con la plataforma.",
    freeDetails: "Al terminar la prueba, el plan Free conserva las copias de seguridad locales; no incluye IA ni copias en línea.",
    freeAfterTrial: "El plan Free se aplica automáticamente al terminar los 60 días de prueba.",
    bonusHeading: "Bono de fidelidad",
    bonusExplanation: "Cuanto más uses la plataforma, más ahorras: cada bono puede aplicar un crédito de 2 € en la renovación, hasta 2 bonos en cada periodo de 30 días.",
    bonusCap: "Hasta 2 bonos en cada periodo de 30 días.",
    stripeButton: "Continuar con Stripe",
    paypalButton: "Continuar con PayPal",
    schoolStatus: "El acceso Pro está activo mediante el programa escolar.",
    subscriptionStatus: "Tu suscripción Pro está activa.",
    paymentError: "No se pudo iniciar el pago. Inténtalo de nuevo o contacta con soporte.",
    paypalError: "PayPal no está disponible ahora. Inténtalo de nuevo o elige Stripe.",
    contactIntro: "Si tienes preguntas sobre los planes o los pagos, contáctanos mediante el formulario de soporte.",
  },
  fr: {
    trialDetails: "Essayez Pro gratuitement pendant 60 jours. L’offre Free reste disponible ensuite ; l’abonnement Pro ne démarre que si vous choisissez de vous abonner.",
    proDetails: "Toutes les fonctionnalités Pro, le support prioritaire et les avantages premium pour grandir avec la plateforme.",
    freeDetails: "Après l’essai, l’offre Free conserve les sauvegardes locales ; l’IA et les sauvegardes en ligne ne sont pas incluses.",
    freeAfterTrial: "L’offre Free s’applique automatiquement après les 60 jours d’essai.",
    bonusHeading: "Bonus de fidélité",
    bonusExplanation: "Plus vous utilisez la plateforme, plus vous économisez : chaque bonus peut appliquer un crédit de 2 € au renouvellement, jusqu’à 2 bonus par période de 30 jours.",
    bonusCap: "Jusqu’à 2 bonus par période de 30 jours.",
    stripeButton: "Continuer avec Stripe",
    paypalButton: "Continuer avec PayPal",
    schoolStatus: "L’accès Pro est actif via le programme scolaire.",
    subscriptionStatus: "Votre abonnement Pro est actif.",
    paymentError: "Impossible de démarrer le paiement. Réessayez ou contactez l’assistance.",
    paypalError: "PayPal est indisponible pour le moment. Réessayez ou choisissez Stripe.",
    contactIntro: "Pour toute question sur les offres ou les paiements, contactez-nous via le formulaire d’assistance.",
  },
  de: {
    trialDetails: "Teste Pro 60 Tage kostenlos. Danach bleibt der Free-Tarif verfügbar; ein Pro-Abo beginnt nur, wenn du es abschließt.",
    proDetails: "Alle Pro-Funktionen, priorisierter Support und Premium-Vorteile für nachhaltiges Wachstum auf der Plattform.",
    freeDetails: "Nach dem Testzeitraum bleiben im Free-Tarif lokale Backups verfügbar; KI und Online-Backups sind nicht enthalten.",
    freeAfterTrial: "Nach der 60-tägigen Testphase gilt automatisch der Free-Tarif.",
    bonusHeading: "Treuebonus",
    bonusExplanation: "Je mehr du die Plattform nutzt, desto mehr sparst du: Jeder Bonus kann bei der Verlängerung eine Gutschrift von 2 € einbringen, bis zu 2 Boni pro 30-Tage-Zeitraum.",
    bonusCap: "Bis zu 2 Boni pro 30-Tage-Zeitraum.",
    stripeButton: "Mit Stripe fortfahren",
    paypalButton: "Mit PayPal fortfahren",
    schoolStatus: "Der Pro-Zugang über das Schulprogramm ist aktiv.",
    subscriptionStatus: "Dein Pro-Abo ist aktiv.",
    paymentError: "Der Bezahlvorgang konnte nicht gestartet werden. Bitte versuche es erneut oder wende dich an den Support.",
    paypalError: "PayPal ist derzeit nicht verfügbar. Bitte versuche es erneut oder wähle Stripe.",
    contactIntro: "Bei Fragen zu Tarifen oder Zahlungen kontaktiere uns über das Supportformular.",
  },
  pt: {
    trialDetails: "Experimente o Pro gratuitamente por 60 dias. Depois, o plano Free continua disponível; a assinatura Pro só começa se você optar por assiná-la.",
    proDetails: "Todos os recursos Pro, suporte prioritário e vantagens premium para crescer com a plataforma.",
    freeDetails: "Após o teste, o plano Free mantém os backups locais; IA e backups online não estão incluídos.",
    freeAfterTrial: "O plano Free é aplicado automaticamente após os 60 dias de teste.",
    bonusHeading: "Bônus de fidelidade",
    bonusExplanation: "Quanto mais utilizar a plataforma, mais poupa: cada bónus pode aplicar um crédito de 2 € na renovação, até 2 bónus em cada período de 30 dias.",
    bonusCap: "Até 2 bônus em cada período de 30 dias.",
    stripeButton: "Continuar com Stripe",
    paypalButton: "Continuar com PayPal",
    schoolStatus: "O acesso Pro pelo programa escolar está ativo.",
    subscriptionStatus: "Sua assinatura Pro está ativa.",
    paymentError: "Não foi possível iniciar o pagamento. Tente novamente ou entre em contato com o suporte.",
    paypalError: "O PayPal está indisponível no momento. Tente novamente ou escolha Stripe.",
    contactIntro: "Para dúvidas sobre planos ou pagamentos, fale conosco pelo formulário de suporte.",
  },
  ru: {
    trialDetails: "Пользуйтесь Pro бесплатно в течение 60 дней. После этого останется доступен план Free; подписка Pro начнётся только по вашему выбору.",
    proDetails: "Все возможности Pro, приоритетная поддержка и премиальные преимущества для роста на платформе.",
    freeDetails: "После пробного периода в плане Free остаются локальные резервные копии; ИИ и онлайн-копии не включены.",
    freeAfterTrial: "После 60-дневного пробного периода автоматически применяется план Free.",
    bonusHeading: "Бонус лояльности",
    bonusExplanation: "Чем чаще вы пользуетесь платформой, тем больше экономите: каждый бонус может добавить кредит в размере 2 € к оплате продления подписки, не более 2 бонусов за 30-дневный период.",
    bonusCap: "До 2 бонусов за каждый 30-дневный период.",
    stripeButton: "Продолжить через Stripe",
    paypalButton: "Продолжить через PayPal",
    schoolStatus: "Доступ Pro по школьной программе активен.",
    subscriptionStatus: "Ваша подписка Pro активна.",
    paymentError: "Не удалось начать оплату. Повторите попытку или обратитесь в поддержку.",
    paypalError: "PayPal сейчас недоступен. Повторите попытку или выберите Stripe.",
    contactIntro: "Если у вас есть вопросы о тарифах или оплате, напишите нам через форму поддержки.",
  },
  zh: {
    trialDetails: "免费体验 Pro 60 天。试用期结束后仍可使用 Free 套餐；只有您主动订阅时才会开通 Pro。",
    proDetails: "所有 Pro 功能、优先支持和高级权益，助力你与平台共同成长。",
    freeDetails: "试用结束后，Free 套餐仍提供本地备份；不包含 AI 和在线备份。",
    freeAfterTrial: "60 天试用期结束后将自动转为 Free 套餐。",
    bonusHeading: "忠诚奖励",
    bonusExplanation: "您使用平台越多，节省越多：每次奖励可在续订时抵扣 2 欧元，每 30 天最多可获得 2 次奖励。",
    bonusCap: "每 30 天最多 2 次奖励。",
    stripeButton: "通过 Stripe 继续",
    paypalButton: "通过 PayPal 继续",
    schoolStatus: "学校计划提供的 Pro 权限已启用。",
    subscriptionStatus: "您的 Pro 订阅已启用。",
    paymentError: "无法开始结账。请重试或联系支持团队。",
    paypalError: "PayPal 暂时不可用。请重试或选择 Stripe。",
    contactIntro: "如有套餐或付款相关问题，请通过支持表单联系我们。",
  },
  ja: {
    trialDetails: "Proを60日間無料でお試しいただけます。その後もFreeプランをご利用いただけます。Proの契約は、ご自身で申し込んだ場合にのみ開始します。",
    proDetails: "すべてのPro機能、優先サポート、成長に役立つプレミアム特典を利用できます。",
    freeDetails: "トライアル終了後もFreeプランではローカルバックアップを利用できます。AI機能とオンラインバックアップは含まれません。",
    freeAfterTrial: "60日間のトライアル終了後はFreeプランが自動的に適用されます。",
    bonusHeading: "ロイヤルティ特典",
    bonusExplanation: "プラットフォームを利用するほどお得になります。各特典につき更新時に2ユーロ分のクレジットが適用され、30日ごとに最大2回まで特典を受け取れます。",
    bonusCap: "30日間ごとに最大2回の特典。",
    stripeButton: "Stripeで続行",
    paypalButton: "PayPalで続行",
    schoolStatus: "スクールプログラムによるProアクセスが有効です。",
    subscriptionStatus: "Proの契約は有効です。",
    paymentError: "決済を開始できませんでした。再試行するか、サポートへお問い合わせください。",
    paypalError: "現在PayPalを利用できません。再試行するか、Stripeをお選びください。",
    contactIntro: "プランやお支払いについてのご質問は、サポートフォームからお問い合わせください。",
  },
  ko: {
    trialDetails: "Pro를 60일 동안 무료로 이용해 보세요. 이후에도 Free 플랜을 사용할 수 있으며, Pro 구독은 직접 선택한 경우에만 시작됩니다.",
    proDetails: "모든 Pro 기능, 우선 지원, 플랫폼 성장에 도움이 되는 프리미엄 혜택을 누리세요.",
    freeDetails: "체험 기간이 끝난 뒤에도 Free 플랜에서 로컬 백업을 사용할 수 있습니다. AI와 온라인 백업은 포함되지 않습니다.",
    freeAfterTrial: "60일 체험이 끝나면 Free 플랜이 자동으로 적용됩니다.",
    bonusHeading: "충성도 보상",
    bonusExplanation: "플랫폼을 많이 사용할수록 더 절약할 수 있습니다. 보너스 1회당 갱신 시 2유로 크레딧이 적용되며, 30일마다 최대 2회 받을 수 있습니다.",
    bonusCap: "30일마다 최대 2회 보상.",
    stripeButton: "Stripe로 계속",
    paypalButton: "PayPal로 계속",
    schoolStatus: "학교 프로그램을 통한 Pro 이용이 활성화되었습니다.",
    subscriptionStatus: "Pro 구독이 활성화되었습니다.",
    paymentError: "결제를 시작할 수 없습니다. 다시 시도하거나 지원팀에 문의하세요.",
    paypalError: "현재 PayPal을 사용할 수 없습니다. 다시 시도하거나 Stripe를 선택하세요.",
    contactIntro: "요금제 또는 결제에 관한 문의는 지원 양식을 이용해 주세요.",
  },
  ar: {
    trialDetails: "جرّب Pro مجانًا لمدة 60 يومًا. تظل خطة Free متاحة بعد ذلك، ولا يبدأ اشتراك Pro إلا إذا اخترت الاشتراك.",
    proDetails: "جميع ميزات Pro، والدعم الأولوي، والمزايا المميزة للنمو مع المنصة.",
    freeDetails: "بعد انتهاء الفترة التجريبية، تحتفظ خطة Free بالنسخ الاحتياطية المحلية؛ ولا تشمل الذكاء الاصطناعي أو النسخ الاحتياطية عبر الإنترنت.",
    freeAfterTrial: "تُطبّق خطة Free تلقائيًا بعد انتهاء فترة التجربة البالغة 60 يومًا.",
    bonusHeading: "مكافأة الولاء",
    bonusExplanation: "كلما زاد استخدامك للمنصة، زاد توفيرك: تمنح كل مكافأة رصيدًا بقيمة 2 يورو عند التجديد، وبحد أقصى مكافأتين خلال كل فترة من 30 يومًا.",
    bonusCap: "حتى مكافأتين خلال كل فترة مدتها 30 يومًا.",
    stripeButton: "المتابعة عبر Stripe",
    paypalButton: "المتابعة عبر PayPal",
    schoolStatus: "الوصول إلى Pro عبر برنامج المدارس نشط.",
    subscriptionStatus: "اشتراك Pro نشط.",
    paymentError: "تعذّر بدء الدفع. حاول مرة أخرى أو تواصل مع الدعم.",
    paypalError: "PayPal غير متاح حاليًا. حاول مرة أخرى أو اختر Stripe.",
    contactIntro: "للاستفسار عن الخطط أو المدفوعات، تواصل معنا عبر نموذج الدعم.",
  },
  hi: {
    trialDetails: "60 दिनों तक Pro मुफ़्त आज़माएँ। इसके बाद Free योजना उपलब्ध रहती है; Pro सदस्यता केवल आपकी पसंद से शुरू होगी।",
    proDetails: "सभी Pro फीचर्स, प्रायोरिटी सपोर्ट और प्लेटफ़ॉर्म के साथ बढ़ने के लिए प्रीमियम लाभ।",
    freeDetails: "ट्रायल के बाद Free योजना लोकल बैकअप रखती है; AI और ऑनलाइन बैकअप शामिल नहीं हैं।",
    freeAfterTrial: "60-दिवसीय ट्रायल के बाद Free योजना स्वचालित रूप से लागू होती है।",
    bonusHeading: "निष्ठा बोनस",
    bonusExplanation: "प्लेटफ़ॉर्म का जितना अधिक उपयोग करेंगे, उतनी अधिक बचत होगी: हर बोनस पर नवीनीकरण के समय €2 का क्रेडिट मिलता है, और प्रत्येक 30-दिवसीय अवधि में अधिकतम 2 बोनस मिल सकते हैं।",
    bonusCap: "हर 30-दिवसीय अवधि में अधिकतम 2 बोनस।",
    stripeButton: "Stripe के साथ जारी रखें",
    paypalButton: "PayPal के साथ जारी रखें",
    schoolStatus: "स्कूल कार्यक्रम के माध्यम से Pro पहुंच सक्रिय है।",
    subscriptionStatus: "आपकी Pro सदस्यता सक्रिय है।",
    paymentError: "पेमेंट शुरू नहीं किया जा सका। कृपया दोबारा प्रयास करें या सहायता से संपर्क करें।",
    paypalError: "PayPal अभी उपलब्ध नहीं है। कृपया दोबारा प्रयास करें या Stripe चुनें।",
    contactIntro: "योजनाओं या भुगतान के बारे में प्रश्नों के लिए सहायता फॉर्म से संपर्क करें।",
  },
  pl: {
    trialDetails: "Wypróbuj Pro za darmo przez 60 dni. Po tym okresie nadal dostępny jest plan Free; subskrypcja Pro rozpoczyna się tylko wtedy, gdy zdecydujesz się ją aktywować.",
    proDetails: "Wszystkie funkcje Pro, priorytetowe wsparcie i premie dla rozwoju na platformie.",
    freeDetails: "Po okresie próbny plan Free zachowuje lokalne kopie zapasowe; AI i kopie zapasowe online nie są włączone.",
    freeAfterTrial: "Plan Free zostaje zastosowany automatycznie po 60 dniach okresu próbnego.",
    bonusHeading: "Premia lojalnościowa",
    bonusExplanation: "Im częściej korzystasz z platformy, tym więcej oszczędzasz: każdy bonus może zapewnić 2 € kredytu przy odnowieniu, maksymalnie 2 bonusy w każdym okresie 30 dni.",
    bonusCap: "Do 2 bonusów w każdym okresie 30 dni.",
    stripeButton: "Kontynuuj przez Stripe",
    paypalButton: "Kontynuuj przez PayPal",
    schoolStatus: "Dostęp Pro w ramach programu szkolnego jest aktywny.",
    subscriptionStatus: "Twoja subskrypcja Pro jest aktywna.",
    paymentError: "Nie udało się rozpocząć płatności. Spróbuj ponownie lub skontaktuj się z pomocą.",
    paypalError: "PayPal jest teraz niedostępny. Spróbuj ponownie lub wybierz Stripe.",
    contactIntro: "Pytania dotyczące planów lub płatności możesz przesłać przez formularz pomocy.",
  },
  nl: {
    trialDetails: "Probeer Pro 60 dagen gratis. Daarna blijft het Free-abonnement beschikbaar; een Pro-abonnement start alleen als je ervoor kiest.",
    proDetails: "Alle Pro-functies, prioritaire support en premium voordelen om met de platform te groeien.",
    freeDetails: "Na de proefperiode behoudt Free lokale back-ups; AI en online back-ups zijn niet inbegrepen.",
    freeAfterTrial: "Na de proefperiode van 60 dagen wordt het Free-abonnement automatisch toegepast.",
    bonusHeading: "Loyaliteitsbonus",
    bonusExplanation: "Hoe vaker je het platform gebruikt, hoe meer je bespaart: elke bonus kan €2 tegoed voor de verlenging opleveren, met maximaal 2 bonussen per periode van 30 dagen.",
    bonusCap: "Maximaal 2 bonussen per periode van 30 dagen.",
    stripeButton: "Doorgaan met Stripe",
    paypalButton: "Doorgaan met PayPal",
    schoolStatus: "Pro-toegang via het schoolprogramma is actief.",
    subscriptionStatus: "Je Pro-abonnement is actief.",
    paymentError: "De betaling kon niet worden gestart. Probeer het opnieuw of neem contact op met support.",
    paypalError: "PayPal is momenteel niet beschikbaar. Probeer het opnieuw of kies Stripe.",
    contactIntro: "Neem voor vragen over abonnementen of betalingen contact op via het supportformulier.",
  },
  tr: {
    trialDetails: "Pro'yu 60 gün ücretsiz deneyin. Sonrasında Free plan kullanılabilir; Pro aboneliği yalnızca siz seçerseniz başlar.",
    proDetails: "Tüm Pro özellikleri, öncelikli destek ve platformla büyümeye yardımcı premium avantajlar.",
    freeDetails: "Deneme süresinden sonra Free plan yerel yedeklemeleri korur; yapay zekâ ve çevrimiçi yedeklemeler dahil değildir.",
    freeAfterTrial: "60 günlük deneme süresinden sonra Free plan otomatik olarak uygulanır.",
    bonusHeading: "Sadakat ödülü",
    bonusExplanation: "Platformu ne kadar çok kullanırsanız o kadar tasarruf edersiniz: her bonus yenilemede 2 € kredi sağlayabilir ve 30 günlük dönemde en fazla 2 bonus alınabilir.",
    bonusCap: "Her 30 günlük dönemde en fazla 2 ödül.",
    stripeButton: "Stripe ile devam et",
    paypalButton: "PayPal ile devam et",
    schoolStatus: "Okul programı üzerinden Pro erişimi etkin.",
    subscriptionStatus: "Pro aboneliğiniz etkin.",
    paymentError: "Ödeme başlatılamadı. Yeniden deneyin veya destek ekibiyle iletişime geçin.",
    paypalError: "PayPal şu anda kullanılamıyor. Yeniden deneyin veya Stripe'ı seçin.",
    contactIntro: "Planlar veya ödemelerle ilgili sorularınız için destek formundan bize ulaşın.",
  },
  sv: {
    trialDetails: "Prova Pro kostnadsfritt i 60 dagar. Därefter finns Free-planen kvar; en Pro-prenumeration startar bara om du väljer att prenumerera.",
    proDetails: "Alla Pro-funktioner, prioriterad support och premiumfördelar för att växa med plattformen.",
    freeDetails: "Efter provperioden behåller Free-planen lokala säkerhetskopior; AI och säkerhetskopiering online ingår inte.",
    freeAfterTrial: "Free-planen tillämpas automatiskt efter den 60 dagar långa provperioden.",
    bonusHeading: "Lojalitetsbonus",
    bonusExplanation: "Ju mer du använder plattformen, desto mer sparar du: varje bonus kan ge 2 € i kredit vid förnyelsen, högst 2 bonusar per 30-dagarsperiod.",
    bonusCap: "Högst 2 bonusar under varje 30-dagarsperiod.",
    stripeButton: "Fortsätt med Stripe",
    paypalButton: "Fortsätt med PayPal",
    schoolStatus: "Pro-åtkomst via skolprogrammet är aktiv.",
    subscriptionStatus: "Din Pro-prenumeration är aktiv.",
    paymentError: "Det gick inte att starta betalningen. Försök igen eller kontakta supporten.",
    paypalError: "PayPal är inte tillgängligt just nu. Försök igen eller välj Stripe.",
    contactIntro: "Kontakta oss via supportformuläret om du har frågor om planer eller betalningar.",
  },
  da: {
    trialDetails: "Prøv Pro gratis i 60 dage. Derefter er Free-planen stadig tilgængelig; et Pro-abonnement starter kun, hvis du selv vælger det.",
    proDetails: "Alle Pro-funktioner, prioriteret support og premiumfordele til at vokse med platformen.",
    freeDetails: "Efter prøveperioden bevarer Free-planen lokale sikkerhedskopier; AI og online sikkerhedskopier er ikke inkluderet.",
    freeAfterTrial: "Free-planen anvendes automatisk efter prøveperioden på 60 dage.",
    bonusHeading: "Loyalitetsbonus",
    bonusExplanation: "Jo mere du bruger platformen, desto mere sparer du: hver bonus kan give 2 € i kredit ved fornyelse, højst 2 bonusser i hver 30-dages periode.",
    bonusCap: "Højst 2 bonusser i hver periode på 30 dage.",
    stripeButton: "Fortsæt med Stripe",
    paypalButton: "Fortsæt med PayPal",
    schoolStatus: "Pro-adgang via skoleprogrammet er aktiv.",
    subscriptionStatus: "Dit Pro-abonnement er aktivt.",
    paymentError: "Betalingen kunne ikke startes. Prøv igen, eller kontakt support.",
    paypalError: "PayPal er ikke tilgængelig lige nu. Prøv igen, eller vælg Stripe.",
    contactIntro: "Kontakt os via supportformularen, hvis du har spørgsmål om planer eller betaling.",
  },
  no: {
    trialDetails: "Prøv Pro gratis i 60 dager. Free-planen er fortsatt tilgjengelig etterpå; et Pro-abonnement starter bare hvis du velger det.",
    proDetails: "Alle Pro-funksjoner, prioritert støtte og premiumfordeler for å vokse med plattformen.",
    freeDetails: "Etter prøveperioden beholder Free-planen lokale sikkerhetskopier; AI og sikkerhetskopiering på nett er ikke inkludert.",
    freeAfterTrial: "Free-planen brukes automatisk etter prøveperioden på 60 dager.",
    bonusHeading: "Lojalitetsbonus",
    bonusExplanation: "Jo mer du bruker plattformen, desto mer sparer du: hver bonus kan gi 2 € i kreditt ved fornyelse, maksimalt 2 bonuser i hver 30-dagersperiode.",
    bonusCap: "Maksimalt 2 bonuser i hver 30-dagersperiode.",
    stripeButton: "Fortsett med Stripe",
    paypalButton: "Fortsett med PayPal",
    schoolStatus: "Pro-tilgang gjennom skoleprogrammet er aktiv.",
    subscriptionStatus: "Pro-abonnementet ditt er aktivt.",
    paymentError: "Betalingen kunne ikke startes. Prøv igjen eller kontakt brukerstøtte.",
    paypalError: "PayPal er ikke tilgjengelig akkurat nå. Prøv igjen eller velg Stripe.",
    contactIntro: "Kontakt oss via supportskjemaet hvis du har spørsmål om planer eller betalinger.",
  },
  fi: {
    trialDetails: "Kokeile Prota maksutta 60 päivän ajan. Sen jälkeen Free-tilaus on edelleen käytettävissä; Pro-tilaus alkaa vain, jos päätät tilata sen.",
    proDetails: "Kaikki Pro-ominaisuudet, prioriteettituki ja premium-edut kasvaa alustalla.",
    freeDetails: "Kokeilujakson jälkeen Free-tilaukseen jäävät paikalliset varmuuskopiot; tekoäly ja verkkovarmuuskopiot eivät sisälly siihen.",
    freeAfterTrial: "Free-tilaus tulee automaattisesti käyttöön 60 päivän kokeilujakson jälkeen.",
    bonusHeading: "Kanta-asiakashyvitys",
    bonusExplanation: "Mitä enemmän käytät alustaa, sitä enemmän säästät: kukin bonus voi tuoda 2 € hyvityksen tilauksen uusinnan yhteydessä, enintään kaksi bonusta 30 päivän jakson aikana.",
    bonusCap: "Enintään 2 bonusta jokaisella 30 päivän jaksolla.",
    stripeButton: "Jatka Stripellä",
    paypalButton: "Jatka PayPalilla",
    schoolStatus: "Pro-käyttö on aktiivinen koulutusohjelman kautta.",
    subscriptionStatus: "Pro-tilauksesi on aktiivinen.",
    paymentError: "Maksua ei voitu aloittaa. Yritä uudelleen tai ota yhteyttä tukeen.",
    paypalError: "PayPal ei ole tällä hetkellä käytettävissä. Yritä uudelleen tai valitse Stripe.",
    contactIntro: "Jos sinulla on kysymyksiä paketeista tai maksuista, ota yhteyttä tukilomakkeen kautta.",
  },
  uk: {
    trialDetails: "Спробуйте Pro безкоштовно протягом 60 днів. Після цього залишиться доступним план Free; підписка Pro почнеться, лише якщо ви вирішите її оформити.",
    proDetails: "Усі можливості Pro, пріоритетна підтримка та преміальні переваги для росту на платформі.",
    freeDetails: "Після пробного періоду в плані Free залишаються локальні резервні копії; ШІ та онлайн-копії не включені.",
    freeAfterTrial: "Після 60-денного пробного періоду автоматично застосовується план Free.",
    bonusHeading: "Бонус лояльності",
    bonusExplanation: "Що більше ви користуєтеся платформою, то більше заощаджуєте: кожен бонус може надати кредит 2 € для продовження підписки, не більше двох бонусів за 30-денний період.",
    bonusCap: "До 2 бонусів за кожен 30-денний період.",
    stripeButton: "Продовжити через Stripe",
    paypalButton: "Продовжити через PayPal",
    schoolStatus: "Доступ Pro через шкільну програму активний.",
    subscriptionStatus: "Ваша підписка Pro активна.",
    paymentError: "Не вдалося розпочати оплату. Спробуйте ще раз або зверніться в підтримку.",
    paypalError: "PayPal зараз недоступний. Спробуйте ще раз або виберіть Stripe.",
    contactIntro: "Якщо у вас є питання щодо тарифів або оплат, напишіть нам через форму підтримки.",
  },
  cs: {
    trialDetails: "Vyzkoušejte Pro zdarma po dobu 60 dní. Poté zůstává k dispozici plán Free; předplatné Pro se aktivuje jen tehdy, pokud se rozhodnete pro odběr.",
    proDetails: "Všechny funkce Pro, prioritní podpora a prémiové výhody pro růst na platformě.",
    freeDetails: "Po zkušební době plán Free zachovává lokální zálohy; AI a online zálohy nejsou zahrnuty.",
    freeAfterTrial: "Po 60denní zkušební době se automaticky použije plán Free.",
    bonusHeading: "Bonus loajality",
    bonusExplanation: "Čím více platformu používáte, tím více ušetříte: každý bonus může při obnovení přinést kredit 2 €, nejvýše 2 bonusy v každém 30denním období.",
    bonusCap: "Až 2 bonusy v každém 30denním období.",
    stripeButton: "Pokračovat přes Stripe",
    paypalButton: "Pokračovat přes PayPal",
    schoolStatus: "Přístup Pro přes školní program je aktivní.",
    subscriptionStatus: "Vaše předplatné Pro je aktivní.",
    paymentError: "Platbu se nepodařilo zahájit. Zkuste to znovu nebo kontaktujte podporu.",
    paypalError: "PayPal je momentálně nedostupný. Zkuste to znovu nebo vyberte Stripe.",
    contactIntro: "Máte-li dotazy ohledně plánů nebo plateb, kontaktujte nás přes formulář podpory.",
  },
};