type PricingDetailsCopy = {
  trialHighlights: string[];
  bonusHowToTitle: string;
  bonusSteps: string[];
  subscriptionExampleTitle: string;
  bonusExample: string[];
  bonusTagline: string;
  allTrialFeaturesTitle: string;
  allTrialFeatures: string[];
  collaborationUnavailable: string;
};

export const pricingDetailsCopy: Record<string, PricingDetailsCopy> = {
  en: {
    trialHighlights: ["Everything included with no restrictions", "Unlimited online backups", "Full AI assistant", "Real-time collaboration", "Advanced editor"],
    bonusHowToTitle: "How to earn the bonus",
    bonusSteps: ["Use the platform consistently", "Build up activity and participation", "Reach 100% activity to earn a €2 discount", "The discount is automatically applied to your monthly renewal"],
    subscriptionExampleTitle: "Subscription example",
    bonusExample: ["First month: €5.99", "Reach 100% activity", "Next month: €5.99 (€7.99 − €2 bonus)", "Reach another 100% activity", "€3.99 (€7.99 − 2 × €2 bonuses)", "The monthly cycle starts again", "Next month: €7.99 if you do not reach 100%"],
    bonusTagline: "Activity is rewarded: the more you use the platform, the more you save.",
    allTrialFeaturesTitle: "All features included in the trial",
    allTrialFeatures: ["Advanced CodeMirror editor", "Syntax highlighting for 50+ languages", "Real-time preview", "AI Co-pilot for code generation", "AI-assisted bug fixes", "Project optimization", "Local and online backups", "Full version history (in development)", "Two-factor authentication and advanced security", "File and folder management", "Custom themes (in development)", "Project export"],
    collaborationUnavailable: "Collaboration unavailable",
  },
  it: {
    trialHighlights: ["Tutto incluso senza limitazioni", "Backup online illimitato", "Assistente AI completo", "Collaborazione in tempo reale", "Editor avanzato"],
    bonusHowToTitle: "Come ottenere il bonus",
    bonusSteps: ["Usa la piattaforma con costanza", "Accumula attività e partecipazione", "Raggiungi il 100% di attività per ottenere 2 € di sconto", "Lo sconto viene applicato automaticamente al rinnovo mensile"],
    subscriptionExampleTitle: "Esempio di abbonamento",
    bonusExample: ["Primo mese: 5,99 €", "Raggiungi il 100% di attività", "Mese successivo: 5,99 € (7,99 € − 2 € di bonus)", "Raggiungi un ulteriore 100% di attività", "3,99 € (7,99 € − 2 bonus da 2 €)", "Il ciclo mensile ricomincia", "Mese successivo: 7,99 € se non raggiungi il 100%"],
    bonusTagline: "L’attività viene premiata: più usi la piattaforma, più risparmi.",
    allTrialFeaturesTitle: "Tutte le funzionalità incluse nella prova",
    allTrialFeatures: ["Editor avanzato CodeMirror", "Evidenziazione della sintassi per oltre 50 linguaggi", "Anteprima in tempo reale", "AI Co-pilot per generare codice", "Correzione dei bug con l’AI", "Ottimizzazione dei progetti", "Backup locali e online", "Cronologia completa delle versioni (in sviluppo)", "Autenticazione a due fattori e sicurezza avanzata", "Gestione di file e cartelle", "Temi personalizzati (in sviluppo)", "Esportazione dei progetti"],
    collaborationUnavailable: "Collaborazione non disponibile",
  },
  es: {
    trialHighlights: ["Todo incluido sin restricciones", "Copias de seguridad online ilimitadas", "Asistente de IA completo", "Colaboración en tiempo real", "Editor avanzado"],
    bonusHowToTitle: "Cómo obtener el bono",
    bonusSteps: ["Usa la plataforma con constancia", "Acumula actividad y participación", "Alcanza el 100 % de actividad y obtén 2 € de descuento", "El descuento se aplica automáticamente a la renovación mensual"],
    subscriptionExampleTitle: "Ejemplo de suscripción",
    bonusExample: ["Primer mes: 5,99 €", "Alcanza el 100 % de actividad", "Mes siguiente: 5,99 € (7,99 € − 2 € de bono)", "Alcanza otro 100 % de actividad", "3,99 € (7,99 € − 2 bonos de 2 €)", "El ciclo mensual vuelve a empezar", "Mes siguiente: 7,99 € si no alcanzas el 100 %"],
    bonusTagline: "Tu actividad tiene recompensa: cuanto más uses la plataforma, más ahorras.",
    allTrialFeaturesTitle: "Todas las funciones incluidas en la prueba",
    allTrialFeatures: ["Editor avanzado CodeMirror", "Resaltado de sintaxis para más de 50 lenguajes", "Vista previa en tiempo real", "AI Co-pilot para generar código", "Corrección de errores con IA", "Optimización de proyectos", "Copias de seguridad locales y online", "Historial completo de versiones (en desarrollo)", "Autenticación de dos factores y seguridad avanzada", "Gestión de archivos y carpetas", "Temas personalizados (en desarrollo)", "Exportación de proyectos"],
    collaborationUnavailable: "Colaboración no disponible",
  },
  fr: {
    trialHighlights: ["Toutes les fonctionnalités sans restriction", "Sauvegardes en ligne illimitées", "Assistant IA complet", "Collaboration en temps réel", "Éditeur avancé"],
    bonusHowToTitle: "Comment obtenir le bonus",
    bonusSteps: ["Utilisez régulièrement la plateforme", "Cumulez de l’activité et de la participation", "Atteignez 100 % d’activité pour obtenir 2 € de réduction", "La réduction est appliquée automatiquement au renouvellement mensuel"],
    subscriptionExampleTitle: "Exemple d’abonnement",
    bonusExample: ["Premier mois : 5,99 €", "Atteignez 100 % d’activité", "Mois suivant : 5,99 € (7,99 € − bonus de 2 €)", "Atteignez à nouveau 100 % d’activité", "3,99 € (7,99 € − 2 bonus de 2 €)", "Le cycle mensuel recommence", "Mois suivant : 7,99 € sans atteindre 100 %"],
    bonusTagline: "Votre activité est récompensée : plus vous utilisez la plateforme, plus vous économisez.",
    allTrialFeaturesTitle: "Toutes les fonctionnalités incluses dans l’essai",
    allTrialFeatures: ["Éditeur CodeMirror avancé", "Coloration syntaxique pour plus de 50 langages", "Aperçu en temps réel", "AI Co-pilot pour générer du code", "Correction de bugs par IA", "Optimisation de projets", "Sauvegardes locales et en ligne", "Historique complet des versions (en développement)", "Authentification à deux facteurs et sécurité avancée", "Gestion des fichiers et dossiers", "Thèmes personnalisés (en développement)", "Exportation de projets"],
    collaborationUnavailable: "Collaboration indisponible",
  },
  de: {
    trialHighlights: ["Alle Funktionen ohne Einschränkungen", "Unbegrenzte Online-Backups", "Vollständiger KI-Assistent", "Zusammenarbeit in Echtzeit", "Erweiterter Editor"],
    bonusHowToTitle: "So erhältst du den Bonus",
    bonusSteps: ["Nutze die Plattform regelmäßig", "Sammle Aktivität und Beteiligung", "Erreiche 100 % Aktivität und erhalte 2 € Rabatt", "Der Rabatt wird automatisch bei der monatlichen Verlängerung angerechnet"],
    subscriptionExampleTitle: "Beispiel für ein Abonnement",
    bonusExample: ["Erster Monat: 5,99 €", "Erreiche 100 % Aktivität", "Nächster Monat: 5,99 € (7,99 € − 2 € Bonus)", "Erreiche erneut 100 % Aktivität", "3,99 € (7,99 € − 2 × 2 € Bonus)", "Der monatliche Zyklus beginnt von vorn", "Nächster Monat: 7,99 €, wenn du keine 100 % erreichst"],
    bonusTagline: "Aktivität wird belohnt: Je mehr du die Plattform nutzt, desto mehr sparst du.",
    allTrialFeaturesTitle: "Alle Funktionen der Testphase",
    allTrialFeatures: ["Erweiterter CodeMirror-Editor", "Syntaxhervorhebung für über 50 Programmiersprachen", "Live-Vorschau", "AI Co-pilot zur Codegenerierung", "KI-gestützte Fehlerbehebung", "Projektoptimierung", "Lokale und Online-Backups", "Vollständiger Versionsverlauf (in Entwicklung)", "Zwei-Faktor-Authentifizierung und erweiterte Sicherheit", "Datei- und Ordnerverwaltung", "Individuelle Designs (in Entwicklung)", "Projekte exportieren"],
    collaborationUnavailable: "Zusammenarbeit nicht verfügbar",
  },
  pt: {
    trialHighlights: ["Tudo incluído sem restrições", "Cópias de segurança online ilimitadas", "Assistente de IA completo", "Colaboração em tempo real", "Editor avançado"],
    bonusHowToTitle: "Como obter o bónus",
    bonusSteps: ["Utilize a plataforma regularmente", "Acumule atividade e participação", "Atinja 100% de atividade e receba 2 € de desconto", "O desconto é aplicado automaticamente na renovação mensal"],
    subscriptionExampleTitle: "Exemplo de subscrição",
    bonusExample: ["Primeiro mês: 5,99 €", "Atinja 100% de atividade", "Mês seguinte: 5,99 € (7,99 € − bónus de 2 €)", "Atinja novamente 100% de atividade", "3,99 € (7,99 € − 2 bónus de 2 €)", "O ciclo mensal recomeça", "Mês seguinte: 7,99 € se não atingir 100%"],
    bonusTagline: "A atividade é recompensada: quanto mais utiliza a plataforma, mais poupa.",
    allTrialFeaturesTitle: "Todas as funcionalidades incluídas no período de teste",
    allTrialFeatures: ["Editor CodeMirror avançado", "Realce de sintaxe para mais de 50 linguagens", "Pré-visualização em tempo real", "AI Co-pilot para gerar código", "Correção de erros com IA", "Otimização de projetos", "Cópias de segurança locais e online", "Histórico completo de versões (em desenvolvimento)", "Autenticação de dois fatores e segurança avançada", "Gestão de ficheiros e pastas", "Temas personalizados (em desenvolvimento)", "Exportação de projetos"],
    collaborationUnavailable: "Colaboração indisponível",
  },
  ru: {
    trialHighlights: ["Все возможности без ограничений", "Неограниченное резервное копирование онлайн", "Полноценный ИИ-помощник", "Совместная работа в реальном времени", "Расширенный редактор"],
    bonusHowToTitle: "Как получить бонус",
    bonusSteps: ["Регулярно пользуйтесь платформой", "Накапливайте активность и участие", "Достигните 100% активности и получите скидку 2 €", "Скидка автоматически применяется при ежемесячном продлении"],
    subscriptionExampleTitle: "Пример подписки",
    bonusExample: ["Первый месяц: 5,99 €", "Достигните 100% активности", "Следующий месяц: 5,99 € (7,99 € − бонус 2 €)", "Снова достигните 100% активности", "3,99 € (7,99 € − 2 бонуса по 2 €)", "Месячный цикл начинается заново", "Следующий месяц: 7,99 €, если не достигнете 100%"],
    bonusTagline: "Активность вознаграждается: чем чаще вы пользуетесь платформой, тем больше экономите.",
    allTrialFeaturesTitle: "Все возможности пробного периода",
    allTrialFeatures: ["Расширенный редактор CodeMirror", "Подсветка синтаксиса для 50+ языков", "Предпросмотр в реальном времени", "AI Co-pilot для генерации кода", "Исправление ошибок с помощью ИИ", "Оптимизация проектов", "Локальное и облачное резервное копирование", "Полная история версий (в разработке)", "Двухфакторная аутентификация и расширенная безопасность", "Управление файлами и папками", "Пользовательские темы (в разработке)", "Экспорт проектов"],
    collaborationUnavailable: "Совместная работа недоступна",
  },
  zh: {
    trialHighlights: ["所有功能均不受限制", "无限在线备份", "完整 AI 助手", "实时协作", "高级编辑器"],
    bonusHowToTitle: "如何获得奖励",
    bonusSteps: ["持续使用平台", "累积活跃度和参与度", "达到 100% 活跃度即可获得 2 欧元折扣", "折扣将在每月续订时自动抵扣"],
    subscriptionExampleTitle: "订阅示例",
    bonusExample: ["首月：5.99 欧元", "达到 100% 活跃度", "次月：5.99 欧元（7.99 欧元 − 2 欧元奖励）", "再次达到 100% 活跃度", "3.99 欧元（7.99 欧元 − 2 个 2 欧元奖励）", "月度周期重新开始", "若未达到 100%，次月为 7.99 欧元"],
    bonusTagline: "活跃使用即可获得奖励：使用越多，节省越多。",
    allTrialFeaturesTitle: "试用期内包含的全部功能",
    allTrialFeatures: ["高级 CodeMirror 编辑器", "支持 50 多种语言的语法高亮", "实时预览", "AI Co-pilot 代码生成", "AI 辅助修复错误", "项目优化", "本地和在线备份", "完整版本历史（开发中）", "双重身份验证和高级安全功能", "文件和文件夹管理", "自定义主题（开发中）", "导出项目"],
    collaborationUnavailable: "协作功能不可用",
  },
  ja: {
    trialHighlights: ["すべての機能を制限なく利用", "無制限のオンラインバックアップ", "フル機能の AI アシスタント", "リアルタイム共同作業", "高機能エディター"],
    bonusHowToTitle: "ボーナスの獲得方法",
    bonusSteps: ["プラットフォームを継続的に利用する", "利用状況と参加度を積み上げる", "アクティビティ 100% 達成で 2 € の割引を獲得", "割引は毎月の更新時に自動適用されます"],
    subscriptionExampleTitle: "サブスクリプションの例",
    bonusExample: ["初月：5.99 €", "アクティビティ 100% を達成", "翌月：5.99 €（7.99 € − 2 € ボーナス）", "さらにアクティビティ 100% を達成", "3.99 €（7.99 € − 2 € のボーナス 2 件）", "月ごとのサイクルが再開", "100% 未達成の場合、翌月は 7.99 €"],
    bonusTagline: "利用状況に応じて還元：使うほどお得になります。",
    allTrialFeaturesTitle: "トライアルに含まれるすべての機能",
    allTrialFeatures: ["高機能 CodeMirror エディター", "50 以上の言語のシンタックスハイライト", "リアルタイムプレビュー", "コード生成 AI Co-pilot", "AI によるバグ修正", "プロジェクトの最適化", "ローカルとオンラインのバックアップ", "完全なバージョン履歴（開発中）", "二要素認証と高度なセキュリティ", "ファイルとフォルダーの管理", "カスタムテーマ（開発中）", "プロジェクトのエクスポート"],
    collaborationUnavailable: "共同作業は利用できません",
  },
  ko: {
    trialHighlights: ["모든 기능을 제한 없이 이용", "무제한 온라인 백업", "전체 AI 어시스턴트", "실시간 협업", "고급 편집기"],
    bonusHowToTitle: "보너스 획득 방법",
    bonusSteps: ["플랫폼을 꾸준히 사용하세요", "활동과 참여도를 쌓으세요", "활동률 100% 달성 시 €2 할인을 받습니다", "할인은 월간 갱신 시 자동 적용됩니다"],
    subscriptionExampleTitle: "구독 예시",
    bonusExample: ["첫 달: €5.99", "활동률 100% 달성", "다음 달: €5.99 (€7.99 − €2 보너스)", "활동률 100% 추가 달성", "€3.99 (€7.99 − €2 보너스 2개)", "월간 주기가 다시 시작됩니다", "100%를 달성하지 못하면 다음 달은 €7.99"],
    bonusTagline: "활동에 보상이 따릅니다. 플랫폼을 많이 사용할수록 더 많이 절약할 수 있습니다.",
    allTrialFeaturesTitle: "체험판에 포함된 모든 기능",
    allTrialFeatures: ["고급 CodeMirror 편집기", "50개 이상 언어의 구문 강조", "실시간 미리보기", "코드 생성을 위한 AI Co-pilot", "AI 버그 수정", "프로젝트 최적화", "로컬 및 온라인 백업", "전체 버전 기록(개발 중)", "2단계 인증 및 고급 보안", "파일 및 폴더 관리", "사용자 지정 테마(개발 중)", "프로젝트 내보내기"],
    collaborationUnavailable: "협업을 사용할 수 없음",
  },
  ar: {
    trialHighlights: ["جميع الميزات بلا قيود", "نسخ احتياطي غير محدود عبر الإنترنت", "مساعد ذكاء اصطناعي كامل", "تعاون في الوقت الفعلي", "محرر متقدم"],
    bonusHowToTitle: "كيفية الحصول على المكافأة",
    bonusSteps: ["استخدم المنصة بانتظام", "اجمع النشاط والمشاركة", "أكمل 100% من النشاط لتحصل على خصم 2 €", "يُطبّق الخصم تلقائيًا عند التجديد الشهري"],
    subscriptionExampleTitle: "مثال على الاشتراك",
    bonusExample: ["الشهر الأول: 5.99 €", "أكمل 100% من النشاط", "الشهر التالي: 5.99 € (7.99 € − مكافأة 2 €)", "أكمل 100% أخرى من النشاط", "3.99 € (7.99 € − مكافأتان بقيمة 2 €)", "تبدأ الدورة الشهرية من جديد", "الشهر التالي: 7.99 € إذا لم تكمل 100%"],
    bonusTagline: "يُكافأ نشاطك: كلما استخدمت المنصة أكثر، وفّرت أكثر.",
    allTrialFeaturesTitle: "جميع الميزات المشمولة في الفترة التجريبية",
    allTrialFeatures: ["محرر CodeMirror متقدم", "تمييز الصياغة لأكثر من 50 لغة", "معاينة فورية", "AI Co-pilot لإنشاء التعليمات البرمجية", "إصلاح الأخطاء بالذكاء الاصطناعي", "تحسين المشاريع", "نسخ احتياطية محلية وعبر الإنترنت", "سجل كامل للإصدارات (قيد التطوير)", "مصادقة ثنائية وعناصر أمان متقدمة", "إدارة الملفات والمجلدات", "سمات مخصصة (قيد التطوير)", "تصدير المشاريع"],
    collaborationUnavailable: "التعاون غير متاح",
  },
  hi: {
    trialHighlights: ["बिना किसी सीमा के सभी सुविधाएँ", "असीमित ऑनलाइन बैकअप", "पूर्ण AI सहायक", "रीयल-टाइम सहयोग", "उन्नत एडिटर"],
    bonusHowToTitle: "बोनस कैसे पाएँ",
    bonusSteps: ["प्लेटफ़ॉर्म का नियमित उपयोग करें", "गतिविधि और सहभागिता बढ़ाएँ", "100% गतिविधि पर €2 की छूट पाएँ", "छूट मासिक नवीनीकरण पर अपने आप लागू होगी"],
    subscriptionExampleTitle: "सदस्यता का उदाहरण",
    bonusExample: ["पहला महीना: €5.99", "100% गतिविधि हासिल करें", "अगला महीना: €5.99 (€7.99 − €2 बोनस)", "फिर से 100% गतिविधि हासिल करें", "€3.99 (€7.99 − €2 के 2 बोनस)", "मासिक चक्र फिर से शुरू होता है", "100% न होने पर अगला महीना: €7.99"],
    bonusTagline: "गतिविधि पर इनाम मिलता है: जितना अधिक उपयोग, उतनी अधिक बचत।",
    allTrialFeaturesTitle: "ट्रायल में शामिल सभी सुविधाएँ",
    allTrialFeatures: ["उन्नत CodeMirror एडिटर", "50+ भाषाओं के लिए सिंटैक्स हाइलाइटिंग", "रीयल-टाइम पूर्वावलोकन", "कोड बनाने के लिए AI Co-pilot", "AI से बग ठीक करना", "प्रोजेक्ट अनुकूलन", "स्थानीय और ऑनलाइन बैकअप", "पूरा संस्करण इतिहास (विकास में)", "2FA और उन्नत सुरक्षा", "फ़ाइल और फ़ोल्डर प्रबंधन", "कस्टम थीम (विकास में)", "प्रोजेक्ट निर्यात"],
    collaborationUnavailable: "सहयोग उपलब्ध नहीं",
  },
  pl: {
    trialHighlights: ["Wszystkie funkcje bez ograniczeń", "Nielimitowane kopie online", "Pełny asystent AI", "Współpraca w czasie rzeczywistym", "Zaawansowany edytor"],
    bonusHowToTitle: "Jak zdobyć bonus",
    bonusSteps: ["Korzystaj regularnie z platformy", "Zbieraj aktywność i zaangażowanie", "Osiągnij 100% aktywności, aby otrzymać 2 € zniżki", "Zniżka zostanie automatycznie naliczona przy miesięcznym odnowieniu"],
    subscriptionExampleTitle: "Przykład subskrypcji",
    bonusExample: ["Pierwszy miesiąc: 5,99 €", "Osiągnij 100% aktywności", "Następny miesiąc: 5,99 € (7,99 € − bonus 2 €)", "Ponownie osiągnij 100% aktywności", "3,99 € (7,99 € − 2 bonusy po 2 €)", "Cykl miesięczny zaczyna się od nowa", "Następny miesiąc: 7,99 €, jeśli nie osiągniesz 100%"],
    bonusTagline: "Aktywność się opłaca: im częściej korzystasz z platformy, tym więcej oszczędzasz.",
    allTrialFeaturesTitle: "Wszystkie funkcje dostępne w okresie próbnym",
    allTrialFeatures: ["Zaawansowany edytor CodeMirror", "Podświetlanie składni dla ponad 50 języków", "Podgląd na żywo", "AI Co-pilot do generowania kodu", "Poprawianie błędów przez AI", "Optymalizacja projektów", "Lokalne i internetowe kopie zapasowe", "Pełna historia wersji (w przygotowaniu)", "Uwierzytelnianie dwuskładnikowe i zaawansowane zabezpieczenia", "Zarządzanie plikami i folderami", "Niestandardowe motywy (w przygotowaniu)", "Eksport projektów"],
    collaborationUnavailable: "Współpraca niedostępna",
  },
  nl: {
    trialHighlights: ["Alle functies zonder beperkingen", "Onbeperkte onlineback-ups", "Volledige AI-assistent", "Realtime samenwerking", "Geavanceerde editor"],
    bonusHowToTitle: "Zo verdien je de bonus",
    bonusSteps: ["Gebruik het platform regelmatig", "Bouw activiteit en deelname op", "Bereik 100% activiteit en ontvang €2 korting", "De korting wordt automatisch verrekend bij de maandelijkse verlenging"],
    subscriptionExampleTitle: "Voorbeeld van een abonnement",
    bonusExample: ["Eerste maand: €5,99", "Bereik 100% activiteit", "Volgende maand: €5,99 (€7,99 − €2 bonus)", "Bereik opnieuw 100% activiteit", "€3,99 (€7,99 − 2 bonussen van €2)", "De maandelijkse cyclus begint opnieuw", "Volgende maand: €7,99 als je geen 100% bereikt"],
    bonusTagline: "Activiteit wordt beloond: hoe vaker je het platform gebruikt, hoe meer je bespaart.",
    allTrialFeaturesTitle: "Alle functies inbegrepen tijdens de proefperiode",
    allTrialFeatures: ["Geavanceerde CodeMirror-editor", "Syntaxmarkering voor 50+ talen", "Live voorbeeld", "AI Co-pilot voor codegeneratie", "Bugs oplossen met AI", "Projecten optimaliseren", "Lokale en online back-ups", "Volledige versiegeschiedenis (in ontwikkeling)", "Tweestapsverificatie en geavanceerde beveiliging", "Bestands- en mapbeheer", "Aangepaste thema’s (in ontwikkeling)", "Projecten exporteren"],
    collaborationUnavailable: "Samenwerking niet beschikbaar",
  },
  tr: {
    trialHighlights: ["Tüm özellikler sınırsız", "Sınırsız çevrim içi yedekleme", "Tam özellikli yapay zekâ asistanı", "Gerçek zamanlı iş birliği", "Gelişmiş düzenleyici"],
    bonusHowToTitle: "Bonus nasıl kazanılır",
    bonusSteps: ["Platformu düzenli kullanın", "Etkinlik ve katılım puanı biriktirin", "%100 etkinliğe ulaşıp 2 € indirim kazanın", "İndirim aylık yenilemede otomatik uygulanır"],
    subscriptionExampleTitle: "Abonelik örneği",
    bonusExample: ["İlk ay: 5,99 €", "%100 etkinliğe ulaşın", "Sonraki ay: 5,99 € (7,99 € − 2 € bonus)", "Yeniden %100 etkinliğe ulaşın", "3,99 € (7,99 € − 2 adet 2 € bonus)", "Aylık döngü yeniden başlar", "%100’e ulaşmazsanız sonraki ay: 7,99 €"],
    bonusTagline: "Etkinlik ödüllendirilir: platformu ne kadar çok kullanırsanız o kadar tasarruf edersiniz.",
    allTrialFeaturesTitle: "Deneme süresine dahil tüm özellikler",
    allTrialFeatures: ["Gelişmiş CodeMirror düzenleyicisi", "50’den fazla dilde sözdizimi vurgulama", "Gerçek zamanlı önizleme", "Kod üretimi için AI Co-pilot", "Yapay zekâ ile hata düzeltme", "Proje optimizasyonu", "Yerel ve çevrim içi yedekleme", "Tam sürüm geçmişi (geliştirme aşamasında)", "İki faktörlü kimlik doğrulama ve gelişmiş güvenlik", "Dosya ve klasör yönetimi", "Özel temalar (geliştirme aşamasında)", "Projeleri dışa aktarma"],
    collaborationUnavailable: "İş birliği kullanılamıyor",
  },
  sv: {
    trialHighlights: ["Alla funktioner utan begränsningar", "Obegränsade säkerhetskopior online", "Fullständig AI-assistent", "Samarbete i realtid", "Avancerad redigerare"],
    bonusHowToTitle: "Så tjänar du bonusen",
    bonusSteps: ["Använd plattformen regelbundet", "Samla aktivitet och deltagande", "Nå 100 % aktivitet och få 2 € rabatt", "Rabatten tillämpas automatiskt vid månadsförnyelsen"],
    subscriptionExampleTitle: "Prenumerationsexempel",
    bonusExample: ["Första månaden: 5,99 €", "Nå 100 % aktivitet", "Nästa månad: 5,99 € (7,99 € − 2 € bonus)", "Nå ytterligare 100 % aktivitet", "3,99 € (7,99 € − 2 bonusar à 2 €)", "Månadscykeln börjar om", "Nästa månad: 7,99 € om du inte når 100 %"],
    bonusTagline: "Aktivitet lönar sig: ju mer du använder plattformen, desto mer sparar du.",
    allTrialFeaturesTitle: "Alla funktioner som ingår i provperioden",
    allTrialFeatures: ["Avancerad CodeMirror-redigerare", "Syntaxmarkering för över 50 språk", "Förhandsvisning i realtid", "AI Co-pilot för kodgenerering", "AI-baserad buggfixning", "Projektoptimering", "Lokala säkerhetskopior och säkerhetskopior online", "Fullständig versionshistorik (under utveckling)", "Tvåfaktorsautentisering och avancerad säkerhet", "Fil- och mapphantering", "Anpassade teman (under utveckling)", "Exportera projekt"],
    collaborationUnavailable: "Samarbete är inte tillgängligt",
  },
  da: {
    trialHighlights: ["Alle funktioner uden begrænsninger", "Ubegrænsede onlinebackups", "Fuld AI-assistent", "Samarbejde i realtid", "Avanceret editor"],
    bonusHowToTitle: "Sådan optjener du bonus",
    bonusSteps: ["Brug platformen regelmæssigt", "Opbyg aktivitet og deltagelse", "Nå 100 % aktivitet og få 2 € i rabat", "Rabatten anvendes automatisk ved den månedlige fornyelse"],
    subscriptionExampleTitle: "Eksempel på abonnement",
    bonusExample: ["Første måned: 5,99 €", "Nå 100 % aktivitet", "Næste måned: 5,99 € (7,99 € − 2 € bonus)", "Nå yderligere 100 % aktivitet", "3,99 € (7,99 € − 2 bonusser à 2 €)", "Den månedlige cyklus starter forfra", "Næste måned: 7,99 €, hvis du ikke når 100 %"],
    bonusTagline: "Aktivitet belønnes: jo mere du bruger platformen, desto mere sparer du.",
    allTrialFeaturesTitle: "Alle funktioner inkluderet i prøveperioden",
    allTrialFeatures: ["Avanceret CodeMirror-editor", "Syntaksfremhævning for over 50 sprog", "Liveforhåndsvisning", "AI Co-pilot til kodegenerering", "AI-fejlrettelse", "Projektoptimering", "Lokale og onlinebackups", "Fuld versionshistorik (under udvikling)", "Totrinsgodkendelse og avanceret sikkerhed", "Fil- og mappehåndtering", "Tilpassede temaer (under udvikling)", "Eksport af projekter"],
    collaborationUnavailable: "Samarbejde er ikke tilgængeligt",
  },
  no: {
    trialHighlights: ["Alle funksjoner uten begrensninger", "Ubegrenset sikkerhetskopiering på nett", "Full AI-assistent", "Samarbeid i sanntid", "Avansert redigeringsverktøy"],
    bonusHowToTitle: "Slik tjener du bonusen",
    bonusSteps: ["Bruk plattformen regelmessig", "Bygg opp aktivitet og deltakelse", "Nå 100 % aktivitet og få 2 € rabatt", "Rabatten trekkes automatisk fra ved månedlig fornyelse"],
    subscriptionExampleTitle: "Eksempel på abonnement",
    bonusExample: ["Første måned: 5,99 €", "Nå 100 % aktivitet", "Neste måned: 5,99 € (7,99 € − 2 € bonus)", "Nå 100 % aktivitet igjen", "3,99 € (7,99 € − 2 bonuser à 2 €)", "Månedssyklusen starter på nytt", "Neste måned: 7,99 € hvis du ikke når 100 %"],
    bonusTagline: "Aktivitet belønnes: jo mer du bruker plattformen, desto mer sparer du.",
    allTrialFeaturesTitle: "Alle funksjoner inkludert i prøveperioden",
    allTrialFeatures: ["Avansert CodeMirror-redigeringsverktøy", "Syntaksutheving for over 50 språk", "Forhåndsvisning i sanntid", "AI Co-pilot for kodegenerering", "AI-basert feilretting", "Prosjektoptimalisering", "Lokale sikkerhetskopier og sikkerhetskopier på nett", "Full versjonshistorikk (under utvikling)", "Tofaktorautentisering og avansert sikkerhet", "Fil- og mappeadministrasjon", "Tilpassede temaer (under utvikling)", "Eksport av prosjekter"],
    collaborationUnavailable: "Samarbeid er ikke tilgjengelig",
  },
  fi: {
    trialHighlights: ["Kaikki ominaisuudet ilman rajoituksia", "Rajaton verkkovarmuuskopiointi", "Täysi tekoälyavustaja", "Reaaliaikainen yhteistyö", "Edistynyt editori"],
    bonusHowToTitle: "Näin ansaitset bonuksen",
    bonusSteps: ["Käytä alustaa säännöllisesti", "Kerrytä aktiivisuutta ja osallistumista", "Saavuta 100 % aktiivisuus ja saat 2 € alennuksen", "Alennus lisätään automaattisesti kuukausiuusintaan"],
    subscriptionExampleTitle: "Tilausesimerkki",
    bonusExample: ["Ensimmäinen kuukausi: 5,99 €", "Saavuta 100 % aktiivisuus", "Seuraava kuukausi: 5,99 € (7,99 € − 2 € bonus)", "Saavuta jälleen 100 % aktiivisuus", "3,99 € (7,99 € − 2 × 2 € bonusta)", "Kuukausijakso alkaa uudelleen", "Seuraava kuukausi: 7,99 €, jos et saavuta 100 %"],
    bonusTagline: "Aktiivisuudesta palkitaan: mitä enemmän käytät alustaa, sitä enemmän säästät.",
    allTrialFeaturesTitle: "Kaikki kokeilujaksoon sisältyvät ominaisuudet",
    allTrialFeatures: ["Edistynyt CodeMirror-editori", "Syntaksin korostus yli 50 kielelle", "Reaaliaikainen esikatselu", "AI Co-pilot koodin luomiseen", "Tekoälyavusteinen virheenkorjaus", "Projektien optimointi", "Paikalliset ja verkkovarmuuskopiot", "Täydellinen versiohistoria (kehitteillä)", "Kaksivaiheinen tunnistautuminen ja edistynyt tietoturva", "Tiedostojen ja kansioiden hallinta", "Mukautetut teemat (kehitteillä)", "Projektien vienti"],
    collaborationUnavailable: "Yhteistyö ei ole käytettävissä",
  },
  uk: {
    trialHighlights: ["Усі функції без обмежень", "Необмежене онлайн-резервне копіювання", "Повноцінний ШІ-помічник", "Спільна робота в реальному часі", "Розширений редактор"],
    bonusHowToTitle: "Як отримати бонус",
    bonusSteps: ["Регулярно користуйтеся платформою", "Накопичуйте активність і участь", "Досягніть 100% активності та отримайте знижку 2 €", "Знижка автоматично застосовується під час щомісячного поновлення"],
    subscriptionExampleTitle: "Приклад підписки",
    bonusExample: ["Перший місяць: 5,99 €", "Досягніть 100% активності", "Наступний місяць: 5,99 € (7,99 € − бонус 2 €)", "Знову досягніть 100% активності", "3,99 € (7,99 € − 2 бонуси по 2 €)", "Місячний цикл починається знову", "Наступний місяць: 7,99 €, якщо не досягнете 100%"],
    bonusTagline: "Активність винагороджується: що більше ви користуєтеся платформою, то більше заощаджуєте.",
    allTrialFeaturesTitle: "Усі функції пробного періоду",
    allTrialFeatures: ["Розширений редактор CodeMirror", "Підсвічування синтаксису для понад 50 мов", "Попередній перегляд у реальному часі", "AI Co-pilot для генерації коду", "Виправлення помилок за допомогою ШІ", "Оптимізація проєктів", "Локальне й онлайн-резервне копіювання", "Повна історія версій (у розробці)", "Двофакторна автентифікація та розширений захист", "Керування файлами й папками", "Власні теми (у розробці)", "Експорт проєктів"],
    collaborationUnavailable: "Спільна робота недоступна",
  },
  cs: {
    trialHighlights: ["Všechny funkce bez omezení", "Neomezené online zálohování", "Plnohodnotný AI asistent", "Spolupráce v reálném čase", "Pokročilý editor"],
    bonusHowToTitle: "Jak získat bonus",
    bonusSteps: ["Pravidelně používejte platformu", "Sbírejte aktivitu a zapojení", "Dosáhněte 100% aktivity a získejte slevu 2 €", "Sleva se automaticky uplatní při měsíčním obnovení"],
    subscriptionExampleTitle: "Příklad předplatného",
    bonusExample: ["První měsíc: 5,99 €", "Dosáhněte 100% aktivity", "Další měsíc: 5,99 € (7,99 € − bonus 2 €)", "Znovu dosáhněte 100% aktivity", "3,99 € (7,99 € − 2 bonusy po 2 €)", "Měsíční cyklus začíná znovu", "Další měsíc: 7,99 €, pokud nedosáhnete 100%"],
    bonusTagline: "Aktivita se vyplácí: čím více platformu používáte, tím více ušetříte.",
    allTrialFeaturesTitle: "Všechny funkce zahrnuté ve zkušební verzi",
    allTrialFeatures: ["Pokročilý editor CodeMirror", "Zvýraznění syntaxe pro více než 50 jazyků", "Náhled v reálném čase", "AI Co-pilot pro generování kódu", "Oprava chyb pomocí AI", "Optimalizace projektů", "Lokální a online zálohování", "Úplná historie verzí (ve vývoji)", "Dvoufázové ověření a pokročilé zabezpečení", "Správa souborů a složek", "Vlastní motivy (ve vývoji)", "Export projektů"],
    collaborationUnavailable: "Spolupráce není k dispozici",
  },
};
