export type PublicHomeCopy = {
  badge: string;
  headline: string;
  highlight: string;
  description: string;
  editorTitle: string;
  editorDescription: string;
  assistantTitle: string;
  assistantDescription: string;
  backupTitle: string;
  backupDescription: string;
  editorCta: string;
  marketplaceCta: string;
  seoTitle: string;
  seoDescription: string;
};

export const publicHomeCopy: Record<string, PublicHomeCopy> = {
  it: {
    badge: "Il tuo spazio per creare sul web",
    headline: "Dai forma alle tue idee web",
    highlight: "con gli strumenti giusti",
    description: "Scrivi e organizza codice nell’editor online, visualizza l’anteprima dei contenuti supportati ed esplora template per dare slancio al tuo prossimo progetto.",
    editorTitle: "Editor online",
    editorDescription: "Modifica i file del progetto nel browser e consulta l’anteprima per i contenuti web supportati.",
    assistantTitle: "Assistenza AI",
    assistantDescription: "Usa il pannello di assistenza AI nell’editor. Le funzionalità disponibili dipendono dalla configurazione del servizio.",
    backupTitle: "File e backup",
    backupDescription: "Organizza i file e usa gli strumenti disponibili per salvare il lavoro e gestire copie di backup.",
    editorCta: "Apri l’editor",
    marketplaceCta: "Esplora i template",
    seoTitle: "Tatik.space Pro | Editor di codice online",
    seoDescription: "Crea e modifica progetti web con l’editor online Tatik.space Pro. Anteprima, assistenza AI, backup, template e programma scuole.",
  },
  en: {
    badge: "Your workspace for building on the web",
    headline: "Bring your web ideas to life",
    highlight: "with practical tools",
    description: "Write and organize code in an online editor, preview supported web content, and explore templates to get your next project moving.",
    editorTitle: "Online editor",
    editorDescription: "Edit project files in your browser and preview supported web content.",
    assistantTitle: "AI assistance",
    assistantDescription: "Use the AI assistance panel in the editor. Available capabilities depend on service configuration.",
    backupTitle: "Files and backups",
    backupDescription: "Organize files and use the available tools to save your work and manage backups.",
    editorCta: "Open the editor",
    marketplaceCta: "Explore templates",
    seoTitle: "Tatik.space Pro | Online code editor",
    seoDescription: "Edit web projects online with Tatik.space Pro. Preview supported content, use AI assistance and backup tools, and explore templates and the school program.",
  },
  es: {
    badge: "Tu espacio para crear en la web",
    headline: "Haz realidad tus ideas web",
    highlight: "con herramientas prácticas",
    description: "Escribe y organiza código en un editor en línea, previsualiza contenido web compatible y explora plantillas para impulsar tu próximo proyecto.",
    editorTitle: "Editor en línea",
    editorDescription: "Edita archivos del proyecto en el navegador y previsualiza contenido web compatible.",
    assistantTitle: "Asistencia con IA",
    assistantDescription: "Usa el panel de asistencia con IA del editor. Las funciones disponibles dependen de la configuración del servicio.",
    backupTitle: "Archivos y copias de seguridad",
    backupDescription: "Organiza archivos y utiliza las herramientas disponibles para guardar tu trabajo y gestionar copias de seguridad.",
    editorCta: "Abrir el editor",
    marketplaceCta: "Explorar plantillas",
    seoTitle: "Tatik.space Pro | Editor de código en línea",
    seoDescription: "Edita proyectos web con Tatik.space Pro: vista previa compatible, asistencia con IA y copias de seguridad. Explora plantillas y el programa escolar.",
  },
  fr: {
    badge: "Votre espace pour créer sur le Web",
    headline: "Donnez vie à vos idées web",
    highlight: "avec des outils pratiques",
    description: "Écrivez et organisez votre code dans un éditeur en ligne, prévisualisez les contenus web pris en charge et découvrez des modèles pour lancer votre prochain projet.",
    editorTitle: "Éditeur en ligne",
    editorDescription: "Modifiez les fichiers de votre projet dans le navigateur et prévisualisez les contenus web pris en charge.",
    assistantTitle: "Assistance par IA",
    assistantDescription: "Utilisez le panneau d’assistance par IA de l’éditeur. Les fonctions disponibles dépendent de la configuration du service.",
    backupTitle: "Fichiers et sauvegardes",
    backupDescription: "Organisez vos fichiers et utilisez les outils disponibles pour enregistrer votre travail et gérer vos sauvegardes.",
    editorCta: "Ouvrir l’éditeur",
    marketplaceCta: "Découvrir les modèles",
    seoTitle: "Tatik.space Pro | Éditeur de code en ligne",
    seoDescription: "Créez vos projets web avec Tatik.space Pro : aperçu des contenus pris en charge, assistance par IA et sauvegardes. Découvrez les modèles et le programme scolaire.",
  },
  de: {
    badge: "Dein Arbeitsbereich fürs Web",
    headline: "Verwirkliche deine Webideen",
    highlight: "mit praktischen Werkzeugen",
    description: "Schreibe und organisiere Code im Online-Editor, zeige unterstützte Webinhalte in der Vorschau an und entdecke Vorlagen für dein nächstes Projekt.",
    editorTitle: "Online-Editor",
    editorDescription: "Bearbeite Projektdateien im Browser und zeige unterstützte Webinhalte in der Vorschau an.",
    assistantTitle: "KI-Unterstützung",
    assistantDescription: "Nutze den KI-Unterstützungsbereich im Editor. Die verfügbaren Funktionen hängen von der Dienstkonfiguration ab.",
    backupTitle: "Dateien und Backups",
    backupDescription: "Organisiere Dateien und nutze die verfügbaren Werkzeuge, um deine Arbeit zu speichern und Backups zu verwalten.",
    editorCta: "Editor öffnen",
    marketplaceCta: "Vorlagen entdecken",
    seoTitle: "Tatik.space Pro | Online-Code-Editor",
    seoDescription: "Bearbeite Webprojekte mit Tatik.space Pro: Vorschau für unterstützte Inhalte, KI-Unterstützung und Backups. Entdecke Vorlagen und das Schulprogramm.",
  },
  pt: {
    badge: "Seu espaço para criar na web",
    headline: "Dê vida às suas ideias para a web",
    highlight: "com ferramentas práticas",
    description: "Escreva e organize código em um editor online, visualize conteúdos web compatíveis e explore modelos para impulsionar seu próximo projeto.",
    editorTitle: "Editor online",
    editorDescription: "Edite arquivos do projeto no navegador e visualize conteúdos web compatíveis.",
    assistantTitle: "Assistência com IA",
    assistantDescription: "Use o painel de assistência com IA no editor. Os recursos disponíveis dependem da configuração do serviço.",
    backupTitle: "Arquivos e backups",
    backupDescription: "Organize arquivos e use as ferramentas disponíveis para salvar seu trabalho e gerenciar backups.",
    editorCta: "Abrir o editor",
    marketplaceCta: "Explorar modelos",
    seoTitle: "Tatik.space Pro | Editor de código online",
    seoDescription: "Crie projetos web com o Tatik.space Pro: prévia de conteúdo compatível, assistência com IA e backups. Explore modelos e o programa escolar.",
  },
  ru: {
    badge: "Ваше пространство для веб-разработки",
    headline: "Воплощайте веб-идеи",
    highlight: "с помощью удобных инструментов",
    description: "Пишите и упорядочивайте код в онлайн-редакторе, просматривайте поддерживаемый веб-контент и выбирайте шаблоны для следующего проекта.",
    editorTitle: "Онлайн-редактор",
    editorDescription: "Редактируйте файлы проекта в браузере и просматривайте поддерживаемый веб-контент.",
    assistantTitle: "Помощь ИИ",
    assistantDescription: "Используйте панель помощи ИИ в редакторе. Доступные возможности зависят от настроек сервиса.",
    backupTitle: "Файлы и резервные копии",
    backupDescription: "Упорядочивайте файлы и используйте доступные инструменты для сохранения работы и управления резервными копиями.",
    editorCta: "Открыть редактор",
    marketplaceCta: "Посмотреть шаблоны",
    seoTitle: "Tatik.space Pro | Онлайн-редактор кода",
    seoDescription: "Создавайте веб-проекты с Tatik.space Pro: просмотр поддерживаемого контента, помощь ИИ и резервное копирование. Шаблоны и школьная программа.",
  },
  zh: {
    badge: "专注网页创作的工作空间",
    headline: "让网页创意变成现实",
    highlight: "借助实用工具",
    description: "在在线编辑器中编写和整理代码，预览受支持的网页内容，并探索模板，为下一个项目做好准备。",
    editorTitle: "在线编辑器",
    editorDescription: "在浏览器中编辑项目文件，并预览受支持的网页内容。",
    assistantTitle: "AI 辅助",
    assistantDescription: "使用编辑器中的 AI 辅助面板。具体功能取决于服务配置。",
    backupTitle: "文件与备份",
    backupDescription: "整理文件，并使用现有工具保存工作和管理备份。",
    editorCta: "打开编辑器",
    marketplaceCta: "浏览模板",
    seoTitle: "Tatik.space Pro | 在线代码编辑器",
    seoDescription: "使用 Tatik.space Pro 在线创建和编辑网页项目，预览受支持内容，并使用 AI 辅助与备份工具。浏览模板并了解学校计划。",
  },
  ja: {
    badge: "Web制作のためのワークスペース",
    headline: "Webのアイデアを形に",
    highlight: "使いやすいツールとともに",
    description: "オンラインエディターでコードを作成・整理し、対応するWebコンテンツをプレビュー。テンプレートを活用して次のプロジェクトを始めましょう。",
    editorTitle: "オンラインエディター",
    editorDescription: "ブラウザーでプロジェクトのファイルを編集し、対応するWebコンテンツをプレビューできます。",
    assistantTitle: "AIアシスタンス",
    assistantDescription: "エディターのAIアシスタンスパネルを利用できます。利用可能な機能はサービス設定によって異なります。",
    backupTitle: "ファイルとバックアップ",
    backupDescription: "ファイルを整理し、利用可能なツールで作業を保存してバックアップを管理できます。",
    editorCta: "エディターを開く",
    marketplaceCta: "テンプレートを見る",
    seoTitle: "Tatik.space Pro | オンラインコードエディター",
    seoDescription: "Tatik.space ProでWebプロジェクトを作成・編集。対応コンテンツのプレビュー、AI支援、バックアップを利用し、テンプレートや学校向けプログラムをご覧ください。",
  },
  ko: {
    badge: "웹 제작을 위한 작업 공간",
    headline: "웹 아이디어를 현실로",
    highlight: "실용적인 도구와 함께",
    description: "온라인 편집기에서 코드를 작성하고 정리하며, 지원되는 웹 콘텐츠를 미리 보고 템플릿을 살펴 다음 프로젝트를 시작하세요.",
    editorTitle: "온라인 편집기",
    editorDescription: "브라우저에서 프로젝트 파일을 편집하고 지원되는 웹 콘텐츠를 미리 볼 수 있습니다.",
    assistantTitle: "AI 지원",
    assistantDescription: "편집기에서 AI 지원 패널을 사용하세요. 제공되는 기능은 서비스 구성에 따라 달라집니다.",
    backupTitle: "파일 및 백업",
    backupDescription: "파일을 정리하고 제공되는 도구를 사용해 작업을 저장하고 백업을 관리하세요.",
    editorCta: "편집기 열기",
    marketplaceCta: "템플릿 둘러보기",
    seoTitle: "Tatik.space Pro | 온라인 코드 편집기",
    seoDescription: "Tatik.space Pro에서 웹 프로젝트를 편집하고 지원 콘텐츠 미리보기, AI 지원, 백업 도구를 이용하세요. 템플릿과 학교 프로그램도 확인할 수 있습니다.",
  },
  ar: {
    badge: "مساحة عملك لإنشاء محتوى الويب",
    headline: "حوّل أفكار الويب إلى واقع",
    highlight: "باستخدام أدوات عملية",
    description: "اكتب التعليمات البرمجية ونظّمها في محرر عبر الإنترنت، واعرض معاينة للمحتوى المدعوم، واستكشف القوالب لبدء مشروعك التالي.",
    editorTitle: "محرر عبر الإنترنت",
    editorDescription: "عدّل ملفات المشروع في المتصفح واعرض معاينة لمحتوى الويب المدعوم.",
    assistantTitle: "مساعدة الذكاء الاصطناعي",
    assistantDescription: "استخدم لوحة المساعدة بالذكاء الاصطناعي في المحرر. تعتمد الإمكانات المتاحة على إعداد الخدمة.",
    backupTitle: "الملفات والنسخ الاحتياطية",
    backupDescription: "نظّم الملفات واستخدم الأدوات المتاحة لحفظ عملك وإدارة النسخ الاحتياطية.",
    editorCta: "افتح المحرر",
    marketplaceCta: "استكشف القوالب",
    seoTitle: "Tatik.space Pro | محرر أكواد عبر الإنترنت",
    seoDescription: "أنشئ مشاريع الويب باستخدام Tatik.space Pro، واعرض المحتوى المدعوم واستفد من مساعدة الذكاء الاصطناعي والنسخ الاحتياطي. اكتشف القوالب وبرنامج المدارس.",
  },
  hi: {
    badge: "वेब निर्माण के लिए आपका कार्यक्षेत्र",
    headline: "अपने वेब विचारों को साकार करें",
    highlight: "उपयोगी टूल के साथ",
    description: "ऑनलाइन एडिटर में कोड लिखें और व्यवस्थित करें, समर्थित वेब सामग्री का पूर्वावलोकन करें और अपने अगले प्रोजेक्ट के लिए टेम्पलेट खोजें।",
    editorTitle: "ऑनलाइन एडिटर",
    editorDescription: "ब्राउज़र में प्रोजेक्ट फ़ाइलें संपादित करें और समर्थित वेब सामग्री का पूर्वावलोकन करें।",
    assistantTitle: "AI सहायता",
    assistantDescription: "एडिटर में AI सहायता पैनल का उपयोग करें। उपलब्ध सुविधाएँ सेवा कॉन्फ़िगरेशन पर निर्भर करती हैं।",
    backupTitle: "फ़ाइलें और बैकअप",
    backupDescription: "फ़ाइलें व्यवस्थित करें और काम सहेजने तथा बैकअप प्रबंधित करने के लिए उपलब्ध टूल का उपयोग करें।",
    editorCta: "एडिटर खोलें",
    marketplaceCta: "टेम्पलेट देखें",
    seoTitle: "Tatik.space Pro | ऑनलाइन कोड एडिटर",
    seoDescription: "Tatik.space Pro में वेब प्रोजेक्ट संपादित करें, समर्थित सामग्री का पूर्वावलोकन करें और AI सहायता व बैकअप टूल इस्तेमाल करें। टेम्पलेट और स्कूल कार्यक्रम देखें।",
  },
  pl: {
    badge: "Twoja przestrzeń do tworzenia w sieci",
    headline: "Przekuj pomysły na projekty internetowe",
    highlight: "w praktyczne rozwiązania",
    description: "Pisz i porządkuj kod w edytorze online, wyświetlaj podgląd obsługiwanych treści internetowych i poznawaj szablony, które pomogą rozpocząć kolejny projekt.",
    editorTitle: "Edytor online",
    editorDescription: "Edytuj pliki projektu w przeglądarce i wyświetlaj podgląd obsługiwanych treści internetowych.",
    assistantTitle: "Wsparcie AI",
    assistantDescription: "Korzystaj z panelu AI w edytorze. Dostępne możliwości zależą od konfiguracji usługi.",
    backupTitle: "Pliki i kopie zapasowe",
    backupDescription: "Porządkuj pliki i korzystaj z dostępnych narzędzi do zapisywania pracy oraz zarządzania kopiami zapasowymi.",
    editorCta: "Otwórz edytor",
    marketplaceCta: "Przeglądaj szablony",
    seoTitle: "Tatik.space Pro | Internetowy edytor kodu",
    seoDescription: "Edytuj projekty internetowe w Tatik.space Pro, podglądaj obsługiwane treści i korzystaj ze wsparcia AI oraz kopii zapasowych. Poznaj szablony i program dla szkół.",
  },
  nl: {
    badge: "Jouw werkruimte voor het web",
    headline: "Breng je webideeën tot leven",
    highlight: "met praktische tools",
    description: "Schrijf en orden code in een online editor, bekijk ondersteunde webinhoud en ontdek sjablonen voor je volgende project.",
    editorTitle: "Online editor",
    editorDescription: "Bewerk projectbestanden in je browser en bekijk ondersteunde webinhoud.",
    assistantTitle: "AI-ondersteuning",
    assistantDescription: "Gebruik het AI-ondersteuningspaneel in de editor. Beschikbare functies zijn afhankelijk van de serviceconfiguratie.",
    backupTitle: "Bestanden en back-ups",
    backupDescription: "Orden bestanden en gebruik de beschikbare hulpmiddelen om je werk op te slaan en back-ups te beheren.",
    editorCta: "Editor openen",
    marketplaceCta: "Sjablonen bekijken",
    seoTitle: "Tatik.space Pro | Online code-editor",
    seoDescription: "Bewerk webprojecten met Tatik.space Pro, bekijk ondersteunde inhoud en gebruik AI-ondersteuning en back-ups. Ontdek sjablonen en het scholenprogramma.",
  },
  tr: {
    badge: "Web için üretim alanınız",
    headline: "Web fikirlerinizi hayata geçirin",
    highlight: "kullanışlı araçlarla",
    description: "Çevrimiçi düzenleyicide kod yazıp düzenleyin, desteklenen web içeriklerini önizleyin ve yeni projeniz için şablonları keşfedin.",
    editorTitle: "Çevrimiçi düzenleyici",
    editorDescription: "Proje dosyalarını tarayıcıda düzenleyin ve desteklenen web içeriklerini önizleyin.",
    assistantTitle: "Yapay zekâ desteği",
    assistantDescription: "Düzenleyicideki yapay zekâ destek panelini kullanın. Sunulan özellikler hizmet yapılandırmasına bağlıdır.",
    backupTitle: "Dosyalar ve yedekler",
    backupDescription: "Dosyalarınızı düzenleyin; çalışmanızı kaydetmek ve yedekleri yönetmek için sunulan araçları kullanın.",
    editorCta: "Düzenleyiciyi aç",
    marketplaceCta: "Şablonları keşfet",
    seoTitle: "Tatik.space Pro | Çevrimiçi kod düzenleyici",
    seoDescription: "Tatik.space Pro ile web projelerini düzenleyin, desteklenen içerikleri önizleyin ve yapay zekâ ile yedekleme araçlarından yararlanın. Şablonları ve okul programını keşfedin.",
  },
  sv: {
    badge: "Din arbetsyta för webben",
    headline: "Gör verklighet av dina webbidéer",
    highlight: "med praktiska verktyg",
    description: "Skriv och organisera kod i en onlineredigerare, förhandsgranska innehåll som stöds och utforska mallar för ditt nästa projekt.",
    editorTitle: "Onlineredigerare",
    editorDescription: "Redigera projektfiler i webbläsaren och förhandsgranska webbinnehåll som stöds.",
    assistantTitle: "AI-assistans",
    assistantDescription: "Använd AI-assistanspanelen i redigeraren. Tillgängliga funktioner beror på tjänstens konfiguration.",
    backupTitle: "Filer och säkerhetskopior",
    backupDescription: "Organisera filer och använd tillgängliga verktyg för att spara arbetet och hantera säkerhetskopior.",
    editorCta: "Öppna redigeraren",
    marketplaceCta: "Utforska mallar",
    seoTitle: "Tatik.space Pro | Onlinekodredigerare",
    seoDescription: "Redigera webbprojekt med Tatik.space Pro, förhandsgranska innehåll som stöds och använd AI-assistans och säkerhetskopior. Utforska mallar och skolprogrammet.",
  },
  da: {
    badge: "Dit arbejdsområde til webudvikling",
    headline: "Gør dine webidéer til virkelighed",
    highlight: "med praktiske værktøjer",
    description: "Skriv og organisér kode i en onlineeditor, få vist understøttet webindhold, og udforsk skabeloner til dit næste projekt.",
    editorTitle: "Onlineeditor",
    editorDescription: "Redigér projektfiler i browseren, og få vist understøttet webindhold.",
    assistantTitle: "AI-assistance",
    assistantDescription: "Brug AI-assistancepanelet i editoren. De tilgængelige funktioner afhænger af tjenestens konfiguration.",
    backupTitle: "Filer og sikkerhedskopier",
    backupDescription: "Organisér filer, og brug de tilgængelige værktøjer til at gemme dit arbejde og administrere sikkerhedskopier.",
    editorCta: "Åbn editoren",
    marketplaceCta: "Udforsk skabeloner",
    seoTitle: "Tatik.space Pro | Onlinekodeeditor",
    seoDescription: "Redigér webprojekter med Tatik.space Pro, få vist understøttet indhold, og brug AI-assistance og sikkerhedskopier. Udforsk skabeloner og skoleprogrammet.",
  },
  no: {
    badge: "Arbeidsområdet ditt for webutvikling",
    headline: "Gjør webideene dine til virkelighet",
    highlight: "med praktiske verktøy",
    description: "Skriv og organiser kode i en nettbasert editor, forhåndsvis støttet webinnhold og utforsk maler til ditt neste prosjekt.",
    editorTitle: "Nettbasert editor",
    editorDescription: "Rediger prosjektfiler i nettleseren og forhåndsvis støttet webinnhold.",
    assistantTitle: "AI-assistanse",
    assistantDescription: "Bruk AI-assistansepanelet i editoren. Tilgjengelige funksjoner avhenger av tjenestekonfigurasjonen.",
    backupTitle: "Filer og sikkerhetskopier",
    backupDescription: "Organiser filer og bruk tilgjengelige verktøy til å lagre arbeidet og administrere sikkerhetskopier.",
    editorCta: "Åpne editoren",
    marketplaceCta: "Utforsk maler",
    seoTitle: "Tatik.space Pro | Nettbasert kodeeditor",
    seoDescription: "Rediger webprosjekter med Tatik.space Pro, forhåndsvis støttet innhold og bruk AI-assistanse og sikkerhetskopier. Utforsk maler og skoleprogrammet.",
  },
  fi: {
    badge: "Työtila verkkokehitykseen",
    headline: "Tee verkkoideoistasi totta",
    highlight: "käytännöllisillä työkaluilla",
    description: "Kirjoita ja järjestä koodia verkkopohjaisessa editorissa, esikatsele tuettua verkkosisältöä ja tutustu seuraavan projektisi malleihin.",
    editorTitle: "Verkkopohjainen editori",
    editorDescription: "Muokkaa projektitiedostoja selaimessa ja esikatsele tuettua verkkosisältöä.",
    assistantTitle: "Tekoälyavustus",
    assistantDescription: "Käytä editorin tekoälyavustuspaneelia. Käytettävissä olevat ominaisuudet riippuvat palvelun määrityksistä.",
    backupTitle: "Tiedostot ja varmuuskopiot",
    backupDescription: "Järjestä tiedostot ja käytä käytettävissä olevia työkaluja työn tallentamiseen ja varmuuskopioiden hallintaan.",
    editorCta: "Avaa editori",
    marketplaceCta: "Tutustu malleihin",
    seoTitle: "Tatik.space Pro | Verkkopohjainen koodieditori",
    seoDescription: "Muokkaa verkkoprojekteja Tatik.space Prolla, esikatsele tuettua sisältöä ja käytä tekoälyavustusta sekä varmuuskopioita. Tutustu malleihin ja kouluohjelmaan.",
  },
  uk: {
    badge: "Ваш робочий простір для веброзробки",
    headline: "Втілюйте вебідеї в життя",
    highlight: "за допомогою зручних інструментів",
    description: "Пишіть і впорядковуйте код в онлайн-редакторі, переглядайте підтримуваний вебвміст і знаходьте шаблони для наступного проєкту.",
    editorTitle: "Онлайн-редактор",
    editorDescription: "Редагуйте файли проєкту в браузері та переглядайте підтримуваний вебвміст.",
    assistantTitle: "Допомога ШІ",
    assistantDescription: "Користуйтеся панеллю допомоги ШІ в редакторі. Доступні можливості залежать від налаштувань сервісу.",
    backupTitle: "Файли та резервні копії",
    backupDescription: "Упорядковуйте файли та використовуйте доступні інструменти для збереження роботи й керування резервними копіями.",
    editorCta: "Відкрити редактор",
    marketplaceCta: "Переглянути шаблони",
    seoTitle: "Tatik.space Pro | Онлайн-редактор коду",
    seoDescription: "Редагуйте вебпроєкти в Tatik.space Pro, переглядайте підтримуваний вміст і користуйтеся допомогою ШІ та резервними копіями. Шаблони й шкільна програма.",
  },
  cs: {
    badge: "Vaše pracovní prostředí pro web",
    headline: "Proměňte své webové nápady ve skutečnost",
    highlight: "s praktickými nástroji",
    description: "Pište a organizujte kód v online editoru, zobrazujte náhled podporovaného webového obsahu a vybírejte šablony pro svůj další projekt.",
    editorTitle: "Online editor",
    editorDescription: "Upravujte soubory projektu v prohlížeči a zobrazujte náhled podporovaného webového obsahu.",
    assistantTitle: "Podpora AI",
    assistantDescription: "Používejte panel podpory AI v editoru. Dostupné funkce závisí na konfiguraci služby.",
    backupTitle: "Soubory a zálohy",
    backupDescription: "Organizujte soubory a používejte dostupné nástroje k ukládání práce a správě záloh.",
    editorCta: "Otevřít editor",
    marketplaceCta: "Procházet šablony",
    seoTitle: "Tatik.space Pro | Online editor kódu",
    seoDescription: "Upravujte webové projekty v Tatik.space Pro, prohlížejte podporovaný obsah a využívejte podporu AI i zálohy. Objevte šablony a školní program.",
  },
};
