type SchoolProgramCopy = {
  institutionName: string;
  institutionEmail: string;
  loadingTerms: string;
  termsError: string;
  officialTermsNote: string;
  acceptTerms: string;
  registerInstitution: string;
  submitting: string;
  schoolStatus: string;
  accessUntil: string;
  activeStudentAccess: string;
  redeemTitle: string;
  redeemDescription: string;
  tokenLabel: string;
  tokenPlaceholder: string;
  verifyInvite: string;
  verifyingInvite: string;
  redeemInvite: string;
  invitesTitle: string;
  invitesDescription: string;
  studentEmail: string;
  createInvite: string;
  copyToken: string;
  staffTitle: string;
  staffDescription: string;
  approve: string;
  reject: string;
  approveGenerateToken: string;
  student: string;
  accessRevoked: string;
  accessExpired: string;
  accessUntilStudent: string;
  pending: string;
  approved: string;
  rejected: string;
  redeemed: string;
  requestSubmitted: string;
  institutionUpdated: string;
  inviteCreated: string;
  inviteApproved: string;
  inviteRedeemed: string;
  studentRevoked: string;
  tokenCopied: string;
  copyFailed: string;
  operationFailed: string;
  revokeStudent: string;
  staffEmpty: string;
  loadingData: string;
  queryError: string;
  seoTitle: string;
  seoDescription: string;
};

export const schoolProgramCopy: Record<string, SchoolProgramCopy> = {
  en: {
    institutionName: "Institution name", institutionEmail: "Institutional email", loadingTerms: "Loading program terms…", termsError: "Could not load program terms",
    officialTermsNote: "The official program terms are displayed in Italian as provided by Tatik. Please review them before accepting.",
    acceptTerms: "I have read and accept the school program terms", registerInstitution: "Register institution and accept terms", submitting: "Submitting request…",
    schoolStatus: "Institution status", accessUntil: "Access through", activeStudentAccess: "Your student access at",
    redeemTitle: "Redeem an invitation", redeemDescription: "Sign in with the email address the invitation was created for, then enter the token approved by the institution.",
    tokenLabel: "School invitation token", tokenPlaceholder: "Invitation token", verifyInvite: "Validate invitation", verifyingInvite: "Validating invitation…", redeemInvite: "Redeem invitation",
    invitesTitle: "Student invitations", invitesDescription: "Create an invitation for a student's email. Approve it to generate a single-use token valid for 7 days, then share the token with the student.",
    studentEmail: "Student email", createInvite: "Create invitation", copyToken: "Copy token",
    staffTitle: "Staff approvals", staffDescription: "Tatik administrators and staff can approve or reject institution applications.",
    approve: "Approve", reject: "Reject", approveGenerateToken: "Approve and generate token", student: "Student",
    accessRevoked: "Access revoked", accessExpired: "Access expired", accessUntilStudent: "Access through",
    pending: "Pending", approved: "Approved", rejected: "Rejected", redeemed: "Redeemed",
    requestSubmitted: "Application sent to Tatik staff.", institutionUpdated: "Institution status updated.",
    inviteCreated: "Invitation created. Tatik staff must approve it before it can be redeemed.",
    inviteApproved: "Invitation approved. Copy the token below and send it to the student.",
    inviteRedeemed: "Invitation redeemed. School access is active.", studentRevoked: "Student access revoked.",
    tokenCopied: "Token copied to clipboard.", copyFailed: "Could not copy. Select and copy the token manually.",
    operationFailed: "The operation could not be completed. Please try again or contact support.",
    revokeStudent: "Revoke access", staffEmpty: "There are no institution applications awaiting review.", loadingData: "Loading…", queryError: "Could not load this information. Please refresh the page or contact support.",
    seoTitle: "School program | Tatik.space Pro",
    seoDescription: "Request an approved 30-day school course for up to 30 students. Review program terms, manage student invitations, and check access status.",
  },
  it: {
    institutionName: "Nome dell’istituto", institutionEmail: "Email istituzionale", loadingTerms: "Caricamento dei termini del programma…", termsError: "Impossibile caricare i termini del programma",
    officialTermsNote: "I termini ufficiali del programma sono mostrati in italiano, nella versione fornita da Tatik. Consultali prima di accettarli.",
    acceptTerms: "Ho letto e accetto i termini del programma scuole", registerInstitution: "Registra l’istituto e accetta i termini", submitting: "Invio della richiesta…",
    schoolStatus: "Stato dell’istituto", accessUntil: "Accesso fino al", activeStudentAccess: "Il tuo accesso studente presso",
    redeemTitle: "Riscatta un invito", redeemDescription: "Accedi con l’indirizzo email per cui è stato creato l’invito, quindi inserisci il token approvato dall’istituto.",
    tokenLabel: "Token di invito scolastico", tokenPlaceholder: "Token di invito", verifyInvite: "Verifica l’invito", verifyingInvite: "Verifica dell’invito…", redeemInvite: "Riscatta l’invito",
    invitesTitle: "Inviti agli studenti", invitesDescription: "Crea un invito per l’email dello studente. Approvato l’invito, verrà generato un token monouso valido 7 giorni da condividere con lo studente.",
    studentEmail: "Email dello studente", createInvite: "Crea invito", copyToken: "Copia token",
    staffTitle: "Approvazioni dello staff", staffDescription: "Gli amministratori e i collaboratori Tatik possono approvare o rifiutare le richieste degli istituti.",
    approve: "Approva", reject: "Rifiuta", approveGenerateToken: "Approva e genera il token", student: "Studente",
    accessRevoked: "Accesso revocato", accessExpired: "Accesso scaduto", accessUntilStudent: "Accesso fino al",
    pending: "In attesa", approved: "Approvato", rejected: "Rifiutato", redeemed: "Riscattato",
    requestSubmitted: "Richiesta inviata allo staff Tatik.", institutionUpdated: "Stato dell’istituto aggiornato.",
    inviteCreated: "Invito creato. Lo staff Tatik deve approvarlo prima che possa essere riscattato.",
    inviteApproved: "Invito approvato. Copia il token qui sotto e invialo allo studente.",
    inviteRedeemed: "Invito riscattato. L’accesso scolastico è attivo.", studentRevoked: "Accesso dello studente revocato.",
    tokenCopied: "Token copiato negli appunti.", copyFailed: "Impossibile copiare. Seleziona e copia il token manualmente.",
    operationFailed: "Impossibile completare l’operazione. Riprova o contatta il supporto.",
    revokeStudent: "Revoca accesso", staffEmpty: "Non ci sono richieste di istituti da esaminare.", loadingData: "Caricamento…", queryError: "Impossibile caricare queste informazioni. Aggiorna la pagina o contatta il supporto.",
    seoTitle: "Programma scuole | Tatik.space Pro",
    seoDescription: "Richiedi l’attivazione di un corso scolastico approvato di 30 giorni per un massimo di 30 studenti. Consulta i termini e gestisci inviti e accessi.",
  },
  es: {
    institutionName: "Nombre de la institución", institutionEmail: "Correo institucional", loadingTerms: "Cargando las condiciones del programa…", termsError: "No se pudieron cargar las condiciones del programa",
    officialTermsNote: "Las condiciones oficiales se muestran en italiano, tal como las proporciona Tatik. Revísalas antes de aceptarlas.",
    acceptTerms: "He leído y acepto las condiciones del programa escolar", registerInstitution: "Registrar institución y aceptar las condiciones", submitting: "Enviando solicitud…",
    schoolStatus: "Estado de la institución", accessUntil: "Acceso hasta", activeStudentAccess: "Tu acceso de estudiante en",
    redeemTitle: "Canjear una invitación", redeemDescription: "Inicia sesión con el correo para el que se creó la invitación e introduce el token aprobado por la institución.",
    tokenLabel: "Token de invitación escolar", tokenPlaceholder: "Token de invitación", verifyInvite: "Validar invitación", verifyingInvite: "Validando invitación…", redeemInvite: "Canjear invitación",
    invitesTitle: "Invitaciones para estudiantes", invitesDescription: "Crea una invitación para el correo del estudiante. Apruébala para generar un token de un solo uso válido durante 7 días y compártelo con el estudiante.",
    studentEmail: "Correo del estudiante", createInvite: "Crear invitación", copyToken: "Copiar token",
    staffTitle: "Aprobaciones del equipo", staffDescription: "El personal y los administradores de Tatik pueden aprobar o rechazar las solicitudes de instituciones.",
    approve: "Aprobar", reject: "Rechazar", approveGenerateToken: "Aprobar y generar token", student: "Estudiante",
    accessRevoked: "Acceso revocado", accessExpired: "Acceso caducado", accessUntilStudent: "Acceso hasta",
    pending: "Pendiente", approved: "Aprobada", rejected: "Rechazada", redeemed: "Canjeada",
    requestSubmitted: "Solicitud enviada al equipo de Tatik.", institutionUpdated: "Estado de la institución actualizado.",
    inviteCreated: "Invitación creada. El equipo de Tatik debe aprobarla antes de que se pueda canjear.",
    inviteApproved: "Invitación aprobada. Copia el token y envíaselo al estudiante.",
    inviteRedeemed: "Invitación canjeada. El acceso escolar está activo.", studentRevoked: "Acceso del estudiante revocado.",
    tokenCopied: "Token copiado.", copyFailed: "No se pudo copiar. Selecciona y copia el token manualmente.",
    operationFailed: "No se pudo completar la operación. Inténtalo de nuevo o contacta con soporte.",
    revokeStudent: "Revocar acceso", staffEmpty: "No hay solicitudes de instituciones pendientes de revisión.", loadingData: "Cargando…", queryError: "No se pudo cargar esta información. Actualiza la página o contacta con soporte.",
    seoTitle: "Programa escolar | Tatik.space Pro", seoDescription: "Solicita un curso escolar aprobado de 30 días para un máximo de 30 estudiantes. Consulta las condiciones y gestiona invitaciones y accesos.",
  },
  fr: {
    institutionName: "Nom de l’établissement", institutionEmail: "E-mail institutionnel", loadingTerms: "Chargement des conditions du programme…", termsError: "Impossible de charger les conditions du programme",
    officialTermsNote: "Les conditions officielles sont affichées en italien, telles que fournies par Tatik. Veuillez les consulter avant de les accepter.",
    acceptTerms: "J’ai lu et j’accepte les conditions du programme scolaire", registerInstitution: "Inscrire l’établissement et accepter les conditions", submitting: "Envoi de la demande…",
    schoolStatus: "Statut de l’établissement", accessUntil: "Accès jusqu’au", activeStudentAccess: "Votre accès étudiant auprès de",
    redeemTitle: "Utiliser une invitation", redeemDescription: "Connectez-vous avec l’adresse e-mail pour laquelle l’invitation a été créée, puis saisissez le jeton approuvé par l’établissement.",
    tokenLabel: "Jeton d’invitation scolaire", tokenPlaceholder: "Jeton d’invitation", verifyInvite: "Vérifier l’invitation", verifyingInvite: "Vérification de l’invitation…", redeemInvite: "Utiliser l’invitation",
    invitesTitle: "Invitations des élèves", invitesDescription: "Créez une invitation à l’adresse e-mail de l’élève. Approuvez-la pour générer un jeton à usage unique valable 7 jours, puis transmettez-le à l’élève.",
    studentEmail: "E-mail de l’élève", createInvite: "Créer une invitation", copyToken: "Copier le jeton",
    staffTitle: "Approbations du personnel", staffDescription: "Le personnel et les administrateurs de Tatik peuvent approuver ou refuser les demandes des établissements.",
    approve: "Approuver", reject: "Refuser", approveGenerateToken: "Approuver et générer le jeton", student: "Élève",
    accessRevoked: "Accès révoqué", accessExpired: "Accès expiré", accessUntilStudent: "Accès jusqu’au",
    pending: "En attente", approved: "Approuvé", rejected: "Refusé", redeemed: "Utilisé",
    requestSubmitted: "Demande envoyée à l’équipe Tatik.", institutionUpdated: "Statut de l’établissement mis à jour.",
    inviteCreated: "Invitation créée. Le personnel de Tatik doit l’approuver avant qu’elle puisse être utilisée.",
    inviteApproved: "Invitation approuvée. Copiez le jeton ci-dessous et transmettez-le à l’élève.",
    inviteRedeemed: "Invitation utilisée. L’accès scolaire est actif.", studentRevoked: "Accès de l’élève révoqué.",
    tokenCopied: "Jeton copié.", copyFailed: "Impossible de copier. Sélectionnez et copiez le jeton manuellement.",
    operationFailed: "Impossible de terminer l’opération. Réessayez ou contactez l’assistance.",
    revokeStudent: "Révoquer l’accès", staffEmpty: "Aucune demande d’établissement n’est en attente d’examen.", loadingData: "Chargement…", queryError: "Impossible de charger ces informations. Actualisez la page ou contactez l’assistance.",
    seoTitle: "Programme scolaire | Tatik.space Pro", seoDescription: "Demandez un cours scolaire approuvé de 30 jours pour 30 élèves maximum. Consultez les conditions et gérez les invitations et les accès.",
  },
  de: {
    institutionName: "Name der Einrichtung", institutionEmail: "Institutionelle E-Mail-Adresse", loadingTerms: "Programmregeln werden geladen…", termsError: "Programmregeln konnten nicht geladen werden",
    officialTermsNote: "Die offiziellen Programmregeln werden auf Italienisch und unverändert so angezeigt, wie Tatik sie bereitstellt. Bitte lies sie vor der Zustimmung.",
    acceptTerms: "Ich habe die Regeln des Schulprogramms gelesen und akzeptiere sie", registerInstitution: "Einrichtung registrieren und Regeln akzeptieren", submitting: "Anfrage wird gesendet…",
    schoolStatus: "Status der Einrichtung", accessUntil: "Zugang bis", activeStudentAccess: "Dein Schülerzugang bei",
    redeemTitle: "Einladung einlösen", redeemDescription: "Melde dich mit der E-Mail-Adresse an, für die die Einladung erstellt wurde, und gib anschließend das von der Einrichtung genehmigte Token ein.",
    tokenLabel: "Schuleinladungstoken", tokenPlaceholder: "Einladungstoken", verifyInvite: "Einladung prüfen", verifyingInvite: "Einladung wird geprüft…", redeemInvite: "Einladung einlösen",
    invitesTitle: "Einladungen für Lernende", invitesDescription: "Erstelle eine Einladung für die E-Mail-Adresse eines Lernenden. Genehmige sie, um ein einmalig verwendbares, 7 Tage gültiges Token zu erstellen, und teile es anschließend mit dem Lernenden.",
    studentEmail: "E-Mail-Adresse des Lernenden", createInvite: "Einladung erstellen", copyToken: "Token kopieren",
    staffTitle: "Genehmigungen durch das Team", staffDescription: "Tatik-Administratoren und Mitarbeitende können Anträge von Einrichtungen genehmigen oder ablehnen.",
    approve: "Genehmigen", reject: "Ablehnen", approveGenerateToken: "Genehmigen und Token erstellen", student: "Lernende Person",
    accessRevoked: "Zugang widerrufen", accessExpired: "Zugang abgelaufen", accessUntilStudent: "Zugang bis",
    pending: "Ausstehend", approved: "Genehmigt", rejected: "Abgelehnt", redeemed: "Eingelöst",
    requestSubmitted: "Antrag an das Tatik-Team gesendet.", institutionUpdated: "Status der Einrichtung aktualisiert.",
    inviteCreated: "Einladung erstellt. Das Tatik-Team muss sie vor dem Einlösen genehmigen.",
    inviteApproved: "Einladung genehmigt. Kopiere das Token und sende es an die lernende Person.",
    inviteRedeemed: "Einladung eingelöst. Der Schulzugang ist aktiv.", studentRevoked: "Zugang der lernenden Person widerrufen.",
    tokenCopied: "Token in die Zwischenablage kopiert.", copyFailed: "Kopieren fehlgeschlagen. Markiere und kopiere das Token manuell.",
    operationFailed: "Der Vorgang konnte nicht abgeschlossen werden. Bitte versuche es erneut oder wende dich an den Support.",
    revokeStudent: "Zugang widerrufen", staffEmpty: "Es liegen keine Einrichtungsanträge zur Prüfung vor.", loadingData: "Wird geladen…", queryError: "Diese Informationen konnten nicht geladen werden. Bitte aktualisiere die Seite oder wende dich an den Support.",
    seoTitle: "Schulprogramm | Tatik.space Pro", seoDescription: "Beantrage einen genehmigten 30-tägigen Schulkurs für höchstens 30 Lernende. Lies die Regeln und verwalte Einladungen und Zugänge.",
  },
  pt: {
    institutionName: "Nome da instituição", institutionEmail: "Email institucional", loadingTerms: "A carregar os termos do programa…", termsError: "Não foi possível carregar os termos do programa",
    officialTermsNote: "Os termos oficiais são apresentados em italiano, tal como fornecidos pela Tatik. Leia-os antes de aceitar.",
    acceptTerms: "Li e aceito os termos do programa escolar", registerInstitution: "Registar instituição e aceitar os termos", submitting: "A enviar o pedido…",
    schoolStatus: "Estado da instituição", accessUntil: "Acesso até", activeStudentAccess: "O seu acesso de estudante em",
    redeemTitle: "Resgatar um convite", redeemDescription: "Inicie sessão com o endereço de email para o qual o convite foi criado e introduza o token aprovado pela instituição.",
    tokenLabel: "Token de convite escolar", tokenPlaceholder: "Token de convite", verifyInvite: "Validar convite", verifyingInvite: "A validar convite…", redeemInvite: "Resgatar convite",
    invitesTitle: "Convites para estudantes", invitesDescription: "Crie um convite para o email do estudante. Aprove-o para gerar um token de utilização única válido por 7 dias e partilhe-o com o estudante.",
    studentEmail: "Email do estudante", createInvite: "Criar convite", copyToken: "Copiar token",
    staffTitle: "Aprovações da equipa", staffDescription: "Os administradores e colaboradores da Tatik podem aprovar ou rejeitar pedidos de instituições.",
    approve: "Aprovar", reject: "Rejeitar", approveGenerateToken: "Aprovar e gerar token", student: "Estudante",
    accessRevoked: "Acesso revogado", accessExpired: "Acesso expirado", accessUntilStudent: "Acesso até",
    pending: "Pendente", approved: "Aprovado", rejected: "Rejeitado", redeemed: "Resgatado",
    requestSubmitted: "Pedido enviado à equipa Tatik.", institutionUpdated: "Estado da instituição atualizado.",
    inviteCreated: "Convite criado. A equipa Tatik tem de o aprovar antes de poder ser resgatado.",
    inviteApproved: "Convite aprovado. Copie o token abaixo e envie-o ao estudante.",
    inviteRedeemed: "Convite resgatado. O acesso escolar está ativo.", studentRevoked: "Acesso do estudante revogado.",
    tokenCopied: "Token copiado.", copyFailed: "Não foi possível copiar. Selecione e copie o token manualmente.",
    operationFailed: "Não foi possível concluir a operação. Tente novamente ou contacte o suporte.",
    revokeStudent: "Revogar acesso", staffEmpty: "Não existem pedidos de instituições por analisar.", loadingData: "A carregar…", queryError: "Não foi possível carregar estas informações. Atualize a página ou contacte o suporte.",
    seoTitle: "Programa escolar | Tatik.space Pro", seoDescription: "Peça um curso escolar aprovado de 30 dias para até 30 estudantes. Consulte os termos e faça a gestão dos convites e acessos.",
  },
  ru: {
    institutionName: "Название учреждения", institutionEmail: "Корпоративная почта учреждения", loadingTerms: "Загрузка условий программы…", termsError: "Не удалось загрузить условия программы",
    officialTermsNote: "Официальные условия отображаются на итальянском языке в исходном виде, предоставленном Tatik. Ознакомьтесь с ними перед принятием.",
    acceptTerms: "Я прочитал(а) и принимаю условия школьной программы", registerInstitution: "Зарегистрировать учреждение и принять условия", submitting: "Отправка заявки…",
    schoolStatus: "Статус учреждения", accessUntil: "Доступ до", activeStudentAccess: "Ваш ученический доступ в учреждении",
    redeemTitle: "Активировать приглашение", redeemDescription: "Войдите с адресом электронной почты, на который создано приглашение, затем введите токен, одобренный учреждением.",
    tokenLabel: "Токен школьного приглашения", tokenPlaceholder: "Токен приглашения", verifyInvite: "Проверить приглашение", verifyingInvite: "Проверка приглашения…", redeemInvite: "Активировать приглашение",
    invitesTitle: "Приглашения учеников", invitesDescription: "Создайте приглашение для электронной почты ученика. Одобрите его, чтобы создать одноразовый токен сроком действия 7 дней, и передайте токен ученику.",
    studentEmail: "Электронная почта ученика", createInvite: "Создать приглашение", copyToken: "Скопировать токен",
    staffTitle: "Одобрение сотрудниками", staffDescription: "Администраторы и сотрудники Tatik могут одобрять или отклонять заявки учреждений.",
    approve: "Одобрить", reject: "Отклонить", approveGenerateToken: "Одобрить и создать токен", student: "Ученик",
    accessRevoked: "Доступ отозван", accessExpired: "Срок доступа истёк", accessUntilStudent: "Доступ до",
    pending: "Ожидает", approved: "Одобрено", rejected: "Отклонено", redeemed: "Активировано",
    requestSubmitted: "Заявка отправлена сотрудникам Tatik.", institutionUpdated: "Статус учреждения обновлён.",
    inviteCreated: "Приглашение создано. Перед активацией его должны одобрить сотрудники Tatik.",
    inviteApproved: "Приглашение одобрено. Скопируйте токен ниже и отправьте его ученику.",
    inviteRedeemed: "Приглашение активировано. Доступ к школьной программе открыт.", studentRevoked: "Доступ ученика отозван.",
    tokenCopied: "Токен скопирован.", copyFailed: "Не удалось скопировать. Выделите токен и скопируйте его вручную.",
    operationFailed: "Не удалось выполнить операцию. Повторите попытку или обратитесь в поддержку.",
    revokeStudent: "Отозвать доступ", staffEmpty: "Нет заявок учреждений, ожидающих рассмотрения.", loadingData: "Загрузка…", queryError: "Не удалось загрузить эти данные. Обновите страницу или обратитесь в поддержку.",
    seoTitle: "Школьная программа | Tatik.space Pro", seoDescription: "Подайте заявку на одобренный 30-дневный школьный курс для максимум 30 учеников. Изучите условия и управляйте приглашениями и доступом.",
  },
  zh: {
    institutionName: "机构名称", institutionEmail: "机构邮箱", loadingTerms: "正在加载计划条款…", termsError: "无法加载计划条款",
    officialTermsNote: "官方计划条款以 Tatik 提供的意大利语原文显示，请在接受前仔细阅读。",
    acceptTerms: "我已阅读并接受学校计划条款", registerInstitution: "注册机构并接受条款", submitting: "正在提交申请…",
    schoolStatus: "机构状态", accessUntil: "访问有效期至", activeStudentAccess: "你在该机构的学生访问权限",
    redeemTitle: "兑换邀请", redeemDescription: "使用收到邀请时对应的邮箱登录，然后输入机构批准的令牌。",
    tokenLabel: "学校邀请令牌", tokenPlaceholder: "邀请令牌", verifyInvite: "验证邀请", verifyingInvite: "正在验证邀请…", redeemInvite: "兑换邀请",
    invitesTitle: "学生邀请", invitesDescription: "为学生邮箱创建邀请。批准后会生成有效期为 7 天、仅可使用一次的令牌，请将令牌交给学生。",
    studentEmail: "学生邮箱", createInvite: "创建邀请", copyToken: "复制令牌",
    staffTitle: "工作人员审批", staffDescription: "Tatik 管理员和工作人员可以批准或拒绝机构申请。",
    approve: "批准", reject: "拒绝", approveGenerateToken: "批准并生成令牌", student: "学生",
    accessRevoked: "访问权限已撤销", accessExpired: "访问权限已过期", accessUntilStudent: "访问有效期至",
    pending: "待处理", approved: "已批准", rejected: "已拒绝", redeemed: "已兑换",
    requestSubmitted: "申请已提交给 Tatik 工作人员。", institutionUpdated: "机构状态已更新。",
    inviteCreated: "邀请已创建。必须经 Tatik 工作人员批准后才能兑换。",
    inviteApproved: "邀请已批准。请复制下方令牌并发送给学生。",
    inviteRedeemed: "邀请已兑换，学校访问权限已启用。", studentRevoked: "学生访问权限已撤销。",
    tokenCopied: "令牌已复制。", copyFailed: "复制失败，请手动选择并复制令牌。",
    operationFailed: "操作未能完成，请重试或联系支持团队。",
    revokeStudent: "撤销访问权限", staffEmpty: "目前没有待审核的机构申请。", loadingData: "正在加载…", queryError: "无法加载此信息。请刷新页面或联系支持团队。",
    seoTitle: "学校计划 | Tatik.space Pro", seoDescription: "申请经批准的 30 天学校课程，最多 30 名学生。查看计划条款并管理学生邀请和访问权限。",
  },
  ja: {
    institutionName: "学校・機関名", institutionEmail: "学校・機関のメールアドレス", loadingTerms: "プログラム規約を読み込み中…", termsError: "プログラム規約を読み込めませんでした",
    officialTermsNote: "公式規約は Tatik が提供するイタリア語の原文のまま表示されます。承諾する前にご確認ください。",
    acceptTerms: "学校向けプログラムの規約を読み、同意します", registerInstitution: "機関を登録して規約に同意", submitting: "申請を送信中…",
    schoolStatus: "機関のステータス", accessUntil: "アクセス期限", activeStudentAccess: "学生アクセス先",
    redeemTitle: "招待を利用する", redeemDescription: "招待の送信先メールアドレスでログインし、機関が承認したトークンを入力してください。",
    tokenLabel: "学校招待トークン", tokenPlaceholder: "招待トークン", verifyInvite: "招待を確認", verifyingInvite: "招待を確認中…", redeemInvite: "招待を利用",
    invitesTitle: "学生への招待", invitesDescription: "学生のメールアドレス宛てに招待を作成します。承認すると7日間有効で1回のみ使用できるトークンが発行されます。学生に共有してください。",
    studentEmail: "学生のメールアドレス", createInvite: "招待を作成", copyToken: "トークンをコピー",
    staffTitle: "スタッフによる承認", staffDescription: "Tatik の管理者とスタッフは機関の申請を承認または却下できます。",
    approve: "承認", reject: "却下", approveGenerateToken: "承認してトークンを発行", student: "学生",
    accessRevoked: "アクセス権を取り消しました", accessExpired: "アクセス期限切れ", accessUntilStudent: "アクセス期限",
    pending: "保留中", approved: "承認済み", rejected: "却下", redeemed: "利用済み",
    requestSubmitted: "Tatik スタッフに申請を送信しました。", institutionUpdated: "機関のステータスを更新しました。",
    inviteCreated: "招待を作成しました。利用前に Tatik スタッフの承認が必要です。",
    inviteApproved: "招待が承認されました。下のトークンをコピーして学生に送ってください。",
    inviteRedeemed: "招待を利用しました。学校アクセスが有効です。", studentRevoked: "学生のアクセス権を取り消しました。",
    tokenCopied: "トークンをコピーしました。", copyFailed: "コピーできませんでした。トークンを選択して手動でコピーしてください。",
    operationFailed: "操作を完了できませんでした。再試行するかサポートにお問い合わせください。",
    revokeStudent: "アクセス権を取り消す", staffEmpty: "審査待ちの機関申請はありません。", loadingData: "読み込み中…", queryError: "情報を読み込めませんでした。ページを更新するかサポートにお問い合わせください。",
    seoTitle: "学校向けプログラム | Tatik.space Pro", seoDescription: "最大30名を対象とする承認制の30日間学校コースを申請できます。規約を確認し、学生の招待とアクセスを管理します。",
  },
  ko: {
    institutionName: "기관명", institutionEmail: "기관 이메일", loadingTerms: "프로그램 약관을 불러오는 중…", termsError: "프로그램 약관을 불러오지 못했습니다",
    officialTermsNote: "공식 프로그램 약관은 Tatik에서 제공한 이탈리아어 원문 그대로 표시됩니다. 동의하기 전에 확인하세요.",
    acceptTerms: "학교 프로그램 약관을 읽고 동의합니다", registerInstitution: "기관 등록 및 약관 동의", submitting: "요청을 제출하는 중…",
    schoolStatus: "기관 상태", accessUntil: "접근 가능 기간", activeStudentAccess: "학생 접근 권한 기관",
    redeemTitle: "초대 사용", redeemDescription: "초대가 생성된 이메일 주소로 로그인한 다음 기관에서 승인한 토큰을 입력하세요.",
    tokenLabel: "학교 초대 토큰", tokenPlaceholder: "초대 토큰", verifyInvite: "초대 확인", verifyingInvite: "초대 확인 중…", redeemInvite: "초대 사용",
    invitesTitle: "학생 초대", invitesDescription: "학생 이메일로 초대를 만드세요. 승인하면 7일 동안 유효하며 한 번만 사용할 수 있는 토큰이 생성됩니다. 토큰을 학생에게 전달하세요.",
    studentEmail: "학생 이메일", createInvite: "초대 만들기", copyToken: "토큰 복사",
    staffTitle: "직원 승인", staffDescription: "Tatik 관리자와 직원은 기관 신청을 승인하거나 거절할 수 있습니다.",
    approve: "승인", reject: "거절", approveGenerateToken: "승인 및 토큰 생성", student: "학생",
    accessRevoked: "접근 권한 취소됨", accessExpired: "접근 기간 만료", accessUntilStudent: "접근 가능 기간",
    pending: "대기 중", approved: "승인됨", rejected: "거절됨", redeemed: "사용됨",
    requestSubmitted: "Tatik 직원에게 신청을 보냈습니다.", institutionUpdated: "기관 상태가 업데이트되었습니다.",
    inviteCreated: "초대가 생성되었습니다. 사용하려면 Tatik 직원의 승인이 필요합니다.",
    inviteApproved: "초대가 승인되었습니다. 아래 토큰을 복사해 학생에게 보내세요.",
    inviteRedeemed: "초대를 사용했습니다. 학교 접근 권한이 활성화되었습니다.", studentRevoked: "학생 접근 권한이 취소되었습니다.",
    tokenCopied: "토큰을 복사했습니다.", copyFailed: "복사할 수 없습니다. 토큰을 직접 선택해 복사하세요.",
    operationFailed: "작업을 완료하지 못했습니다. 다시 시도하거나 지원팀에 문의하세요.",
    revokeStudent: "접근 권한 취소", staffEmpty: "검토 대기 중인 기관 신청이 없습니다.", loadingData: "불러오는 중…", queryError: "정보를 불러오지 못했습니다. 페이지를 새로 고치거나 지원팀에 문의하세요.",
    seoTitle: "학교 프로그램 | Tatik.space Pro", seoDescription: "최대 30명의 학생을 위한 승인된 30일 학교 과정을 신청하세요. 약관을 확인하고 학생 초대와 접근 권한을 관리하세요.",
  },
  ar: {
    institutionName: "اسم المؤسسة", institutionEmail: "البريد الإلكتروني للمؤسسة", loadingTerms: "جارٍ تحميل شروط البرنامج…", termsError: "تعذّر تحميل شروط البرنامج",
    officialTermsNote: "تُعرض الشروط الرسمية باللغة الإيطالية كما قدمتها Tatik. يُرجى مراجعتها قبل الموافقة.",
    acceptTerms: "قرأت شروط برنامج المدارس وأوافق عليها", registerInstitution: "تسجيل المؤسسة والموافقة على الشروط", submitting: "جارٍ إرسال الطلب…",
    schoolStatus: "حالة المؤسسة", accessUntil: "الوصول حتى", activeStudentAccess: "وصولك كطالب لدى",
    redeemTitle: "استخدام دعوة", redeemDescription: "سجّل الدخول باستخدام عنوان البريد الإلكتروني الذي أُنشئت له الدعوة، ثم أدخل الرمز الذي وافقت عليه المؤسسة.",
    tokenLabel: "رمز دعوة المدرسة", tokenPlaceholder: "رمز الدعوة", verifyInvite: "التحقق من الدعوة", verifyingInvite: "جارٍ التحقق من الدعوة…", redeemInvite: "استخدام الدعوة",
    invitesTitle: "دعوات الطلاب", invitesDescription: "أنشئ دعوة لبريد الطالب. وافق عليها لإنشاء رمز صالح لمدة 7 أيام ولمرة واحدة، ثم أرسل الرمز إلى الطالب.",
    studentEmail: "البريد الإلكتروني للطالب", createInvite: "إنشاء دعوة", copyToken: "نسخ الرمز",
    staffTitle: "موافقات فريق العمل", staffDescription: "يمكن لمسؤولي وموظفي Tatik الموافقة على طلبات المؤسسات أو رفضها.",
    approve: "موافقة", reject: "رفض", approveGenerateToken: "الموافقة وإنشاء رمز", student: "طالب",
    accessRevoked: "تم إلغاء الوصول", accessExpired: "انتهت صلاحية الوصول", accessUntilStudent: "الوصول حتى",
    pending: "قيد الانتظار", approved: "تمت الموافقة", rejected: "مرفوض", redeemed: "مستخدم",
    requestSubmitted: "أُرسل الطلب إلى فريق Tatik.", institutionUpdated: "تم تحديث حالة المؤسسة.",
    inviteCreated: "أُنشئت الدعوة. يجب أن يوافق عليها فريق Tatik قبل استخدامها.",
    inviteApproved: "تمت الموافقة على الدعوة. انسخ الرمز أدناه وأرسله إلى الطالب.",
    inviteRedeemed: "تم استخدام الدعوة وأصبح الوصول المدرسي نشطًا.", studentRevoked: "تم إلغاء وصول الطالب.",
    tokenCopied: "تم نسخ الرمز.", copyFailed: "تعذّر النسخ. حدّد الرمز وانسخه يدويًا.",
    operationFailed: "تعذّر إكمال العملية. حاول مرة أخرى أو تواصل مع الدعم.",
    revokeStudent: "إلغاء الوصول", staffEmpty: "لا توجد طلبات مؤسسات بانتظار المراجعة.", loadingData: "جارٍ التحميل…", queryError: "تعذّر تحميل هذه المعلومات. حدّث الصفحة أو تواصل مع الدعم.",
    seoTitle: "برنامج المدارس | Tatik.space Pro", seoDescription: "اطلب دورة مدرسية معتمدة لمدة 30 يومًا لما يصل إلى 30 طالبًا. راجع الشروط وأدر دعوات الطلاب وإمكانية الوصول.",
  },
  hi: {
    institutionName: "संस्था का नाम", institutionEmail: "संस्थागत ईमेल", loadingTerms: "कार्यक्रम की शर्तें लोड हो रही हैं…", termsError: "कार्यक्रम की शर्तें लोड नहीं हो सकीं",
    officialTermsNote: "आधिकारिक शर्तें Tatik द्वारा दिए गए इतालवी मूल रूप में दिखाई जाती हैं। स्वीकार करने से पहले उन्हें पढ़ें।",
    acceptTerms: "मैंने स्कूल कार्यक्रम की शर्तें पढ़ी हैं और उन्हें स्वीकार करता/करती हूँ", registerInstitution: "संस्था पंजीकृत करें और शर्तें स्वीकार करें", submitting: "अनुरोध भेजा जा रहा है…",
    schoolStatus: "संस्था की स्थिति", accessUntil: "इस तारीख तक पहुँच", activeStudentAccess: "आपकी छात्र पहुँच",
    redeemTitle: "आमंत्रण रिडीम करें", redeemDescription: "उस ईमेल पते से साइन इन करें जिसके लिए आमंत्रण बनाया गया था, फिर संस्था द्वारा स्वीकृत टोकन दर्ज करें।",
    tokenLabel: "स्कूल आमंत्रण टोकन", tokenPlaceholder: "आमंत्रण टोकन", verifyInvite: "आमंत्रण सत्यापित करें", verifyingInvite: "आमंत्रण सत्यापित हो रहा है…", redeemInvite: "आमंत्रण रिडीम करें",
    invitesTitle: "विद्यार्थियों के आमंत्रण", invitesDescription: "विद्यार्थी के ईमेल पर आमंत्रण बनाएँ। स्वीकृति के बाद 7 दिनों तक मान्य, एक बार उपयोग होने वाला टोकन बनेगा; इसे विद्यार्थी के साथ साझा करें।",
    studentEmail: "विद्यार्थी का ईमेल", createInvite: "आमंत्रण बनाएँ", copyToken: "टोकन कॉपी करें",
    staffTitle: "स्टाफ की स्वीकृतियाँ", staffDescription: "Tatik व्यवस्थापक और कर्मचारी संस्था के आवेदनों को स्वीकार या अस्वीकार कर सकते हैं।",
    approve: "स्वीकृत करें", reject: "अस्वीकार करें", approveGenerateToken: "स्वीकृत करें और टोकन बनाएँ", student: "विद्यार्थी",
    accessRevoked: "पहुँच रद्द", accessExpired: "पहुँच की अवधि समाप्त", accessUntilStudent: "पहुँच की अवधि",
    pending: "लंबित", approved: "स्वीकृत", rejected: "अस्वीकृत", redeemed: "रिडीम किया गया",
    requestSubmitted: "आवेदन Tatik स्टाफ को भेजा गया।", institutionUpdated: "संस्था की स्थिति अपडेट की गई।",
    inviteCreated: "आमंत्रण बनाया गया। रिडीम करने से पहले Tatik स्टाफ की स्वीकृति आवश्यक है।",
    inviteApproved: "आमंत्रण स्वीकृत है। नीचे दिया टोकन कॉपी करके विद्यार्थी को भेजें।",
    inviteRedeemed: "आमंत्रण रिडीम हुआ। स्कूल पहुँच सक्रिय है।", studentRevoked: "विद्यार्थी की पहुँच रद्द की गई।",
    tokenCopied: "टोकन कॉपी हुआ।", copyFailed: "कॉपी नहीं हो सका। टोकन चुनकर मैन्युअल रूप से कॉपी करें।",
    operationFailed: "कार्रवाई पूरी नहीं हो सकी। फिर से प्रयास करें या सहायता से संपर्क करें।",
    revokeStudent: "पहुँच रद्द करें", staffEmpty: "समीक्षा के लिए कोई संस्था आवेदन लंबित नहीं है।", loadingData: "लोड हो रहा है…", queryError: "यह जानकारी लोड नहीं हो सकी। पृष्ठ रीफ़्रेश करें या सहायता से संपर्क करें।",
    seoTitle: "स्कूल कार्यक्रम | Tatik.space Pro", seoDescription: "अधिकतम 30 विद्यार्थियों के लिए स्वीकृत 30-दिवसीय स्कूल कोर्स का अनुरोध करें। शर्तें देखें और विद्यार्थी आमंत्रण व पहुँच प्रबंधित करें।",
  },
  pl: {
    institutionName: "Nazwa placówki", institutionEmail: "Służbowy adres e-mail placówki", loadingTerms: "Wczytywanie warunków programu…", termsError: "Nie udało się wczytać warunków programu",
    officialTermsNote: "Oficjalne warunki programu są wyświetlane po włosku, w oryginalnej wersji przekazanej przez Tatik. Zapoznaj się z nimi przed akceptacją.",
    acceptTerms: "Przeczytałem(-am) i akceptuję warunki programu szkolnego", registerInstitution: "Zarejestruj placówkę i zaakceptuj warunki", submitting: "Wysyłanie zgłoszenia…",
    schoolStatus: "Status placówki", accessUntil: "Dostęp do", activeStudentAccess: "Twój dostęp ucznia w",
    redeemTitle: "Zrealizuj zaproszenie", redeemDescription: "Zaloguj się przy użyciu adresu e-mail, na który utworzono zaproszenie, a następnie wpisz token zatwierdzony przez placówkę.",
    tokenLabel: "Token zaproszenia szkolnego", tokenPlaceholder: "Token zaproszenia", verifyInvite: "Sprawdź zaproszenie", verifyingInvite: "Sprawdzanie zaproszenia…", redeemInvite: "Zrealizuj zaproszenie",
    invitesTitle: "Zaproszenia dla uczniów", invitesDescription: "Utwórz zaproszenie na adres e-mail ucznia. Zatwierdź je, aby wygenerować jednorazowy token ważny przez 7 dni, a następnie przekaż go uczniowi.",
    studentEmail: "Adres e-mail ucznia", createInvite: "Utwórz zaproszenie", copyToken: "Kopiuj token",
    staffTitle: "Zatwierdzenia personelu", staffDescription: "Administratorzy i pracownicy Tatik mogą zatwierdzać lub odrzucać zgłoszenia placówek.",
    approve: "Zatwierdź", reject: "Odrzuć", approveGenerateToken: "Zatwierdź i wygeneruj token", student: "Uczeń",
    accessRevoked: "Dostęp cofnięty", accessExpired: "Dostęp wygasł", accessUntilStudent: "Dostęp do",
    pending: "Oczekuje", approved: "Zatwierdzono", rejected: "Odrzucono", redeemed: "Zrealizowano",
    requestSubmitted: "Zgłoszenie wysłano do zespołu Tatik.", institutionUpdated: "Zaktualizowano status placówki.",
    inviteCreated: "Utworzono zaproszenie. Przed realizacją musi je zatwierdzić personel Tatik.",
    inviteApproved: "Zaproszenie zatwierdzono. Skopiuj poniższy token i prześlij go uczniowi.",
    inviteRedeemed: "Zrealizowano zaproszenie. Dostęp szkolny jest aktywny.", studentRevoked: "Cofnięto dostęp ucznia.",
    tokenCopied: "Skopiowano token.", copyFailed: "Nie udało się skopiować. Zaznacz i skopiuj token ręcznie.",
    operationFailed: "Nie udało się wykonać operacji. Spróbuj ponownie lub skontaktuj się z pomocą.",
    revokeStudent: "Cofnij dostęp", staffEmpty: "Brak zgłoszeń placówek oczekujących na rozpatrzenie.", loadingData: "Wczytywanie…", queryError: "Nie udało się wczytać tych informacji. Odśwież stronę lub skontaktuj się z pomocą.",
    seoTitle: "Program szkolny | Tatik.space Pro", seoDescription: "Złóż wniosek o zatwierdzony 30-dniowy kurs dla maksymalnie 30 uczniów. Zapoznaj się z warunkami i zarządzaj zaproszeniami oraz dostępem.",
  },
  nl: {
    institutionName: "Naam van de instelling", institutionEmail: "E-mailadres van de instelling", loadingTerms: "Programmavoorwaarden laden…", termsError: "Programmavoorwaarden konden niet worden geladen",
    officialTermsNote: "De officiële programmavoorwaarden worden in het Italiaans getoond, zoals aangeleverd door Tatik. Lees ze voordat je akkoord gaat.",
    acceptTerms: "Ik heb de voorwaarden van het scholenprogramma gelezen en ga ermee akkoord", registerInstitution: "Instelling registreren en voorwaarden accepteren", submitting: "Aanvraag indienen…",
    schoolStatus: "Status van de instelling", accessUntil: "Toegang tot", activeStudentAccess: "Je studententoegang bij",
    redeemTitle: "Een uitnodiging inwisselen", redeemDescription: "Log in met het e-mailadres waarvoor de uitnodiging is aangemaakt en voer daarna het door de instelling goedgekeurde token in.",
    tokenLabel: "Schooluitnodigingstoken", tokenPlaceholder: "Uitnodigingstoken", verifyInvite: "Uitnodiging controleren", verifyingInvite: "Uitnodiging controleren…", redeemInvite: "Uitnodiging inwisselen",
    invitesTitle: "Uitnodigingen voor studenten", invitesDescription: "Maak een uitnodiging voor het e-mailadres van een student. Keur deze goed om een eenmalig token te maken dat 7 dagen geldig is, en deel het token met de student.",
    studentEmail: "E-mailadres van de student", createInvite: "Uitnodiging maken", copyToken: "Token kopiëren",
    staffTitle: "Goedkeuring door medewerkers", staffDescription: "Tatik-beheerders en medewerkers kunnen aanvragen van instellingen goedkeuren of afwijzen.",
    approve: "Goedkeuren", reject: "Afwijzen", approveGenerateToken: "Goedkeuren en token maken", student: "Student",
    accessRevoked: "Toegang ingetrokken", accessExpired: "Toegang verlopen", accessUntilStudent: "Toegang tot",
    pending: "In behandeling", approved: "Goedgekeurd", rejected: "Afgewezen", redeemed: "Ingewisseld",
    requestSubmitted: "Aanvraag naar het Tatik-team verzonden.", institutionUpdated: "Instellingsstatus bijgewerkt.",
    inviteCreated: "Uitnodiging gemaakt. Het Tatik-team moet deze goedkeuren voordat de student hem kan inwisselen.",
    inviteApproved: "Uitnodiging goedgekeurd. Kopieer het token hieronder en stuur het naar de student.",
    inviteRedeemed: "Uitnodiging ingewisseld. Schooltoegang is actief.", studentRevoked: "Studententoegang ingetrokken.",
    tokenCopied: "Token gekopieerd.", copyFailed: "Kopiëren is mislukt. Selecteer en kopieer het token handmatig.",
    operationFailed: "De bewerking kon niet worden voltooid. Probeer het opnieuw of neem contact op met support.",
    revokeStudent: "Toegang intrekken", staffEmpty: "Er staan geen instellingsaanvragen klaar voor beoordeling.", loadingData: "Laden…", queryError: "Deze informatie kon niet worden geladen. Vernieuw de pagina of neem contact op met support.",
    seoTitle: "Scholenprogramma | Tatik.space Pro", seoDescription: "Vraag een goedgekeurde schoolcursus van 30 dagen aan voor maximaal 30 studenten. Bekijk de voorwaarden en beheer uitnodigingen en toegang.",
  },
  tr: {
    institutionName: "Kurum adı", institutionEmail: "Kurumsal e-posta", loadingTerms: "Program koşulları yükleniyor…", termsError: "Program koşulları yüklenemedi",
    officialTermsNote: "Resmî program koşulları Tatik tarafından sağlanan İtalyanca özgün metinle gösterilir. Kabul etmeden önce lütfen inceleyin.",
    acceptTerms: "Okul programı koşullarını okudum ve kabul ediyorum", registerInstitution: "Kurumu kaydet ve koşulları kabul et", submitting: "Başvuru gönderiliyor…",
    schoolStatus: "Kurum durumu", accessUntil: "Erişim bitişi", activeStudentAccess: "Öğrenci erişiminiz",
    redeemTitle: "Daveti kullan", redeemDescription: "Davetin oluşturulduğu e-posta adresiyle giriş yapın ve kurum tarafından onaylanan tokenı girin.",
    tokenLabel: "Okul davet tokenı", tokenPlaceholder: "Davet tokenı", verifyInvite: "Daveti doğrula", verifyingInvite: "Davet doğrulanıyor…", redeemInvite: "Daveti kullan",
    invitesTitle: "Öğrenci davetleri", invitesDescription: "Öğrencinin e-posta adresine bir davet oluşturun. Onaylayarak 7 gün geçerli, tek kullanımlık token üretin ve tokenı öğrenciyle paylaşın.",
    studentEmail: "Öğrenci e-postası", createInvite: "Davet oluştur", copyToken: "Tokenı kopyala",
    staffTitle: "Ekip onayları", staffDescription: "Tatik yöneticileri ve çalışanları kurum başvurularını onaylayabilir veya reddedebilir.",
    approve: "Onayla", reject: "Reddet", approveGenerateToken: "Onayla ve token oluştur", student: "Öğrenci",
    accessRevoked: "Erişim iptal edildi", accessExpired: "Erişim süresi doldu", accessUntilStudent: "Erişim bitişi",
    pending: "Beklemede", approved: "Onaylandı", rejected: "Reddedildi", redeemed: "Kullanıldı",
    requestSubmitted: "Başvuru Tatik ekibine gönderildi.", institutionUpdated: "Kurum durumu güncellendi.",
    inviteCreated: "Davet oluşturuldu. Kullanılabilmesi için Tatik ekibinin onaylaması gerekir.",
    inviteApproved: "Davet onaylandı. Aşağıdaki tokenı kopyalayıp öğrenciye gönderin.",
    inviteRedeemed: "Davet kullanıldı. Okul erişimi etkin.", studentRevoked: "Öğrencinin erişimi iptal edildi.",
    tokenCopied: "Token kopyalandı.", copyFailed: "Kopyalanamadı. Tokenı seçip elle kopyalayın.",
    operationFailed: "İşlem tamamlanamadı. Yeniden deneyin veya destek ekibiyle iletişime geçin.",
    revokeStudent: "Erişimi iptal et", staffEmpty: "İncelenmeyi bekleyen kurum başvurusu yok.", loadingData: "Yükleniyor…", queryError: "Bu bilgiler yüklenemedi. Sayfayı yenileyin veya destek ekibiyle iletişime geçin.",
    seoTitle: "Okul programı | Tatik.space Pro", seoDescription: "En fazla 30 öğrenci için onaylı 30 günlük bir okul kursu talep edin. Koşulları inceleyin, davetleri ve erişimi yönetin.",
  },
  sv: {
    institutionName: "Institutionens namn", institutionEmail: "Institutionens e-postadress", loadingTerms: "Läser in programmets villkor…", termsError: "Det gick inte att läsa in programmets villkor",
    officialTermsNote: "De officiella programvillkoren visas på italienska i den version som Tatik har tillhandahållit. Läs dem innan du godkänner.",
    acceptTerms: "Jag har läst och godkänner skolprogrammets villkor", registerInstitution: "Registrera institution och godkänn villkoren", submitting: "Skickar ansökan…",
    schoolStatus: "Institutionens status", accessUntil: "Åtkomst till", activeStudentAccess: "Din studentåtkomst hos",
    redeemTitle: "Lös in en inbjudan", redeemDescription: "Logga in med e-postadressen som inbjudan skapades för och ange sedan tokenen som institutionen har godkänt.",
    tokenLabel: "Skolinbjudningstoken", tokenPlaceholder: "Inbjudningstoken", verifyInvite: "Verifiera inbjudan", verifyingInvite: "Verifierar inbjudan…", redeemInvite: "Lös in inbjudan",
    invitesTitle: "Studentinbjudningar", invitesDescription: "Skapa en inbjudan till studentens e-postadress. Godkänn den för att skapa en engångstoken som gäller i 7 dagar och dela sedan tokenen med studenten.",
    studentEmail: "Studentens e-postadress", createInvite: "Skapa inbjudan", copyToken: "Kopiera token",
    staffTitle: "Personalens godkännanden", staffDescription: "Tatik-administratörer och medarbetare kan godkänna eller avslå institutionsansökningar.",
    approve: "Godkänn", reject: "Avslå", approveGenerateToken: "Godkänn och skapa token", student: "Student",
    accessRevoked: "Åtkomst återkallad", accessExpired: "Åtkomsten har upphört", accessUntilStudent: "Åtkomst till",
    pending: "Väntar", approved: "Godkänd", rejected: "Avslagen", redeemed: "Inlöst",
    requestSubmitted: "Ansökan har skickats till Tatik-teamet.", institutionUpdated: "Institutionens status har uppdaterats.",
    inviteCreated: "Inbjudan har skapats. Tatik-personal måste godkänna den innan den kan lösas in.",
    inviteApproved: "Inbjudan har godkänts. Kopiera tokenen nedan och skicka den till studenten.",
    inviteRedeemed: "Inbjudan har lösts in. Skolåtkomsten är aktiv.", studentRevoked: "Studentens åtkomst har återkallats.",
    tokenCopied: "Token kopierad.", copyFailed: "Det gick inte att kopiera. Markera och kopiera tokenen manuellt.",
    operationFailed: "Åtgärden kunde inte slutföras. Försök igen eller kontakta support.",
    revokeStudent: "Återkalla åtkomst", staffEmpty: "Det finns inga institutionsansökningar som väntar på granskning.", loadingData: "Läser in…", queryError: "Det gick inte att läsa in informationen. Uppdatera sidan eller kontakta support.",
    seoTitle: "Skolprogram | Tatik.space Pro", seoDescription: "Ansök om en godkänd 30-dagars skolkurs för högst 30 elever. Läs villkoren och hantera inbjudningar och åtkomst.",
  },
  da: {
    institutionName: "Institutionens navn", institutionEmail: "Institutionens e-mailadresse", loadingTerms: "Indlæser programmets vilkår…", termsError: "Programmets vilkår kunne ikke indlæses",
    officialTermsNote: "De officielle programvilkår vises på italiensk i den version, Tatik har leveret. Læs dem, før du accepterer.",
    acceptTerms: "Jeg har læst og accepterer skoleprogrammets vilkår", registerInstitution: "Registrér institution og acceptér vilkår", submitting: "Sender ansøgning…",
    schoolStatus: "Institutionens status", accessUntil: "Adgang til", activeStudentAccess: "Din elevadgang hos",
    redeemTitle: "Indløs en invitation", redeemDescription: "Log ind med den e-mailadresse, invitationen blev oprettet til, og indtast derefter tokenet, som institutionen har godkendt.",
    tokenLabel: "Skoleinvitationstoken", tokenPlaceholder: "Invitationstoken", verifyInvite: "Kontrollér invitation", verifyingInvite: "Kontrollerer invitation…", redeemInvite: "Indløs invitation",
    invitesTitle: "Invitationer til elever", invitesDescription: "Opret en invitation til elevens e-mailadresse. Godkend den for at generere et engangstoken, der gælder i 7 dage, og del derefter tokenet med eleven.",
    studentEmail: "Elevens e-mailadresse", createInvite: "Opret invitation", copyToken: "Kopiér token",
    staffTitle: "Godkendelser fra personalet", staffDescription: "Tatik-administratorer og medarbejdere kan godkende eller afvise institutionsansøgninger.",
    approve: "Godkend", reject: "Afvis", approveGenerateToken: "Godkend og opret token", student: "Elev",
    accessRevoked: "Adgang tilbagekaldt", accessExpired: "Adgangen er udløbet", accessUntilStudent: "Adgang til",
    pending: "Afventer", approved: "Godkendt", rejected: "Afvist", redeemed: "Indløst",
    requestSubmitted: "Ansøgningen er sendt til Tatik-teamet.", institutionUpdated: "Institutionens status er opdateret.",
    inviteCreated: "Invitationen er oprettet. Tatik-personalet skal godkende den, før den kan indløses.",
    inviteApproved: "Invitationen er godkendt. Kopiér tokenet nedenfor, og send det til eleven.",
    inviteRedeemed: "Invitationen er indløst. Skoleadgangen er aktiv.", studentRevoked: "Elevens adgang er tilbagekaldt.",
    tokenCopied: "Token kopieret.", copyFailed: "Kunne ikke kopiere. Markér og kopiér tokenet manuelt.",
    operationFailed: "Handlingen kunne ikke gennemføres. Prøv igen, eller kontakt support.",
    revokeStudent: "Tilbagekald adgang", staffEmpty: "Der er ingen institutionsansøgninger, som afventer gennemgang.", loadingData: "Indlæser…", queryError: "Oplysningerne kunne ikke indlæses. Opdater siden, eller kontakt support.",
    seoTitle: "Skoleprogram | Tatik.space Pro", seoDescription: "Ansøg om et godkendt 30-dages skolekursus for højst 30 elever. Læs vilkårene, og administrer invitationer og adgang.",
  },
  no: {
    institutionName: "Institusjonens navn", institutionEmail: "Institusjonens e-postadresse", loadingTerms: "Laster inn programvilkårene…", termsError: "Kunne ikke laste inn programvilkårene",
    officialTermsNote: "De offisielle programvilkårene vises på italiensk slik Tatik har levert dem. Les dem før du godtar.",
    acceptTerms: "Jeg har lest og godtar vilkårene for skoleprogrammet", registerInstitution: "Registrer institusjon og godta vilkårene", submitting: "Sender søknad…",
    schoolStatus: "Institusjonens status", accessUntil: "Tilgang til", activeStudentAccess: "Studenttilgangen din hos",
    redeemTitle: "Løs inn en invitasjon", redeemDescription: "Logg inn med e-postadressen invitasjonen ble opprettet for, og skriv deretter inn tokenet som institusjonen har godkjent.",
    tokenLabel: "Skoleinvitasjonstoken", tokenPlaceholder: "Invitasjonstoken", verifyInvite: "Kontroller invitasjonen", verifyingInvite: "Kontrollerer invitasjonen…", redeemInvite: "Løs inn invitasjonen",
    invitesTitle: "Invitasjoner til elever", invitesDescription: "Opprett en invitasjon til elevens e-postadresse. Godkjenn den for å lage et engangstoken som er gyldig i 7 dager, og del tokenet med eleven.",
    studentEmail: "Elevens e-postadresse", createInvite: "Opprett invitasjon", copyToken: "Kopier token",
    staffTitle: "Godkjenning fra ansatte", staffDescription: "Tatik-administratorer og ansatte kan godkjenne eller avslå søknader fra institusjoner.",
    approve: "Godkjenn", reject: "Avslå", approveGenerateToken: "Godkjenn og opprett token", student: "Elev",
    accessRevoked: "Tilgang tilbakekalt", accessExpired: "Tilgangen er utløpt", accessUntilStudent: "Tilgang til",
    pending: "Venter", approved: "Godkjent", rejected: "Avslått", redeemed: "Løst inn",
    requestSubmitted: "Søknaden er sendt til Tatik-teamet.", institutionUpdated: "Institusjonens status er oppdatert.",
    inviteCreated: "Invitasjonen er opprettet. Tatik-ansatte må godkjenne den før den kan løses inn.",
    inviteApproved: "Invitasjonen er godkjent. Kopier tokenet nedenfor og send det til eleven.",
    inviteRedeemed: "Invitasjonen er løst inn. Skoletilgangen er aktiv.", studentRevoked: "Elevens tilgang er tilbakekalt.",
    tokenCopied: "Token kopiert.", copyFailed: "Kunne ikke kopiere. Marker og kopier tokenet manuelt.",
    operationFailed: "Handlingen kunne ikke fullføres. Prøv igjen eller kontakt brukerstøtte.",
    revokeStudent: "Tilbakekall tilgang", staffEmpty: "Det er ingen institusjonssøknader som venter på behandling.", loadingData: "Laster…", queryError: "Kunne ikke laste inn denne informasjonen. Oppdater siden eller kontakt brukerstøtte.",
    seoTitle: "Skoleprogram | Tatik.space Pro", seoDescription: "Søk om et godkjent 30-dagers skolekurs for opptil 30 elever. Les vilkårene, og administrer invitasjoner og tilgang.",
  },
  fi: {
    institutionName: "Oppilaitoksen nimi", institutionEmail: "Oppilaitoksen sähköpostiosoite", loadingTerms: "Ladataan ohjelman ehtoja…", termsError: "Ohjelman ehtojen lataaminen epäonnistui",
    officialTermsNote: "Viralliset ohjelmaehdot näytetään Tatikin toimittamassa italiankielisessä alkuperäismuodossa. Tutustu niihin ennen hyväksymistä.",
    acceptTerms: "Olen lukenut kouluohjelman ehdot ja hyväksyn ne", registerInstitution: "Rekisteröi oppilaitos ja hyväksy ehdot", submitting: "Lähetetään hakemusta…",
    schoolStatus: "Oppilaitoksen tila", accessUntil: "Käyttöoikeus päättyy", activeStudentAccess: "Opiskelijan käyttöoikeutesi oppilaitoksessa",
    redeemTitle: "Lunasta kutsu", redeemDescription: "Kirjaudu sisään kutsun luomiseen käytetyllä sähköpostiosoitteella ja anna sitten oppilaitoksen hyväksymä tunniste.",
    tokenLabel: "Kouluohjelman kutsutunniste", tokenPlaceholder: "Kutsutunniste", verifyInvite: "Tarkista kutsu", verifyingInvite: "Tarkistetaan kutsua…", redeemInvite: "Lunasta kutsu",
    invitesTitle: "Opiskelijakutsut", invitesDescription: "Luo kutsu opiskelijan sähköpostiosoitteeseen. Hyväksy se, niin saat kertakäyttöisen tunnisteen, joka on voimassa 7 päivää. Jaa tunniste opiskelijalle.",
    studentEmail: "Opiskelijan sähköpostiosoite", createInvite: "Luo kutsu", copyToken: "Kopioi tunniste",
    staffTitle: "Henkilökunnan hyväksynnät", staffDescription: "Tatikin ylläpitäjät ja työntekijät voivat hyväksyä tai hylätä oppilaitosten hakemuksia.",
    approve: "Hyväksy", reject: "Hylkää", approveGenerateToken: "Hyväksy ja luo tunniste", student: "Opiskelija",
    accessRevoked: "Käyttöoikeus peruttu", accessExpired: "Käyttöoikeus päättynyt", accessUntilStudent: "Käyttöoikeus päättyy",
    pending: "Odottaa", approved: "Hyväksytty", rejected: "Hylätty", redeemed: "Lunastettu",
    requestSubmitted: "Hakemus lähetettiin Tatik-tiimille.", institutionUpdated: "Oppilaitoksen tila päivitettiin.",
    inviteCreated: "Kutsu luotiin. Tatikin henkilökunnan on hyväksyttävä se ennen lunastamista.",
    inviteApproved: "Kutsu hyväksyttiin. Kopioi alla oleva tunniste ja lähetä se opiskelijalle.",
    inviteRedeemed: "Kutsu lunastettiin. Kouluohjelman käyttöoikeus on aktiivinen.", studentRevoked: "Opiskelijan käyttöoikeus peruttiin.",
    tokenCopied: "Tunniste kopioitiin.", copyFailed: "Kopiointi epäonnistui. Valitse tunniste ja kopioi se käsin.",
    operationFailed: "Toimintoa ei voitu suorittaa. Yritä uudelleen tai ota yhteyttä tukeen.",
    revokeStudent: "Peru käyttöoikeus", staffEmpty: "Oppilaitoshakemuksia ei ole tarkistettavana.", loadingData: "Ladataan…", queryError: "Tietoja ei voitu ladata. Päivitä sivu tai ota yhteyttä tukeen.",
    seoTitle: "Kouluohjelma | Tatik.space Pro", seoDescription: "Hae hyväksyttyä 30 päivän koulukurssia enintään 30 opiskelijalle. Tutustu ehtoihin ja hallitse kutsuja ja käyttöoikeuksia.",
  },
  uk: {
    institutionName: "Назва закладу", institutionEmail: "Електронна пошта закладу", loadingTerms: "Завантаження умов програми…", termsError: "Не вдалося завантажити умови програми",
    officialTermsNote: "Офіційні умови програми відображаються італійською мовою в оригінальній версії, наданій Tatik. Ознайомтеся з ними перед прийняттям.",
    acceptTerms: "Я прочитав(-ла) та приймаю умови шкільної програми", registerInstitution: "Зареєструвати заклад і прийняти умови", submitting: "Надсилання заявки…",
    schoolStatus: "Статус закладу", accessUntil: "Доступ до", activeStudentAccess: "Ваш учнівський доступ у закладі",
    redeemTitle: "Активувати запрошення", redeemDescription: "Увійдіть за адресою електронної пошти, для якої створено запрошення, а потім введіть токен, схвалений закладом.",
    tokenLabel: "Токен шкільного запрошення", tokenPlaceholder: "Токен запрошення", verifyInvite: "Перевірити запрошення", verifyingInvite: "Перевірка запрошення…", redeemInvite: "Активувати запрошення",
    invitesTitle: "Запрошення для учнів", invitesDescription: "Створіть запрошення на електронну адресу учня. Схваліть його, щоб створити одноразовий токен, дійсний 7 днів, і передайте токен учню.",
    studentEmail: "Електронна адреса учня", createInvite: "Створити запрошення", copyToken: "Копіювати токен",
    staffTitle: "Схвалення персоналом", staffDescription: "Адміністратори та працівники Tatik можуть схвалювати або відхиляти заявки закладів.",
    approve: "Схвалити", reject: "Відхилити", approveGenerateToken: "Схвалити та створити токен", student: "Учень",
    accessRevoked: "Доступ відкликано", accessExpired: "Термін доступу минув", accessUntilStudent: "Доступ до",
    pending: "Очікує", approved: "Схвалено", rejected: "Відхилено", redeemed: "Активовано",
    requestSubmitted: "Заявку надіслано команді Tatik.", institutionUpdated: "Статус закладу оновлено.",
    inviteCreated: "Запрошення створено. Перед активацією його має схвалити персонал Tatik.",
    inviteApproved: "Запрошення схвалено. Скопіюйте токен нижче та надішліть його учню.",
    inviteRedeemed: "Запрошення активовано. Доступ до шкільної програми діє.", studentRevoked: "Доступ учня відкликано.",
    tokenCopied: "Токен скопійовано.", copyFailed: "Не вдалося скопіювати. Виділіть і скопіюйте токен вручну.",
    operationFailed: "Не вдалося виконати операцію. Спробуйте ще раз або зверніться до підтримки.",
    revokeStudent: "Відкликати доступ", staffEmpty: "Немає заявок закладів, що очікують на розгляд.", loadingData: "Завантаження…", queryError: "Не вдалося завантажити ці дані. Оновіть сторінку або зверніться до підтримки.",
    seoTitle: "Шкільна програма | Tatik.space Pro", seoDescription: "Подайте заявку на схвалений 30-денний курс для максимум 30 учнів. Перегляньте умови та керуйте запрошеннями й доступом.",
  },
  cs: {
    institutionName: "Název instituce", institutionEmail: "Institucionální e-mail", loadingTerms: "Načítání podmínek programu…", termsError: "Podmínky programu se nepodařilo načíst",
    officialTermsNote: "Oficiální podmínky programu se zobrazují v italštině v původním znění poskytnutém službou Tatik. Před přijetím si je přečtěte.",
    acceptTerms: "Přečetl(a) jsem podmínky školního programu a souhlasím s nimi", registerInstitution: "Zaregistrovat instituci a přijmout podmínky", submitting: "Odesílání žádosti…",
    schoolStatus: "Stav instituce", accessUntil: "Přístup do", activeStudentAccess: "Váš studentský přístup v instituci",
    redeemTitle: "Uplatnit pozvánku", redeemDescription: "Přihlaste se e-mailovou adresou, pro kterou byla pozvánka vytvořena, a zadejte token schválený institucí.",
    tokenLabel: "Token školní pozvánky", tokenPlaceholder: "Token pozvánky", verifyInvite: "Ověřit pozvánku", verifyingInvite: "Ověřování pozvánky…", redeemInvite: "Uplatnit pozvánku",
    invitesTitle: "Pozvánky pro studenty", invitesDescription: "Vytvořte pozvánku pro e-mail studenta. Schválením vytvoříte jednorázový token platný 7 dní; token pak předejte studentovi.",
    studentEmail: "E-mail studenta", createInvite: "Vytvořit pozvánku", copyToken: "Kopírovat token",
    staffTitle: "Schvalování pracovníky", staffDescription: "Správci a pracovníci Tatik mohou žádosti institucí schválit nebo zamítnout.",
    approve: "Schválit", reject: "Zamítnout", approveGenerateToken: "Schválit a vytvořit token", student: "Student",
    accessRevoked: "Přístup odebrán", accessExpired: "Přístup vypršel", accessUntilStudent: "Přístup do",
    pending: "Čeká na vyřízení", approved: "Schváleno", rejected: "Zamítnuto", redeemed: "Uplatněno",
    requestSubmitted: "Žádost byla odeslána týmu Tatik.", institutionUpdated: "Stav instituce byl aktualizován.",
    inviteCreated: "Pozvánka byla vytvořena. Před uplatněním ji musí schválit pracovníci Tatik.",
    inviteApproved: "Pozvánka byla schválena. Zkopírujte token níže a pošlete jej studentovi.",
    inviteRedeemed: "Pozvánka byla uplatněna. Školní přístup je aktivní.", studentRevoked: "Studentský přístup byl odebrán.",
    tokenCopied: "Token byl zkopírován.", copyFailed: "Kopírování se nezdařilo. Označte a zkopírujte token ručně.",
    operationFailed: "Operaci se nepodařilo dokončit. Zkuste to znovu nebo kontaktujte podporu.",
    revokeStudent: "Odebrat přístup", staffEmpty: "Žádné žádosti institucí nečekají na posouzení.", loadingData: "Načítání…", queryError: "Tyto informace se nepodařilo načíst. Obnovte stránku nebo kontaktujte podporu.",
    seoTitle: "Školní program | Tatik.space Pro", seoDescription: "Požádejte o schválený 30denní školní kurz pro nejvýše 30 studentů. Projděte si podmínky a spravujte pozvánky a přístup.",
  },
};
