export const sellerTermsTranslations: Record<string, string[]> = {
  en: [
    "The seller is solely responsible for the templates, files, and content offered, including their quality, accuracy, security, licensing, and compliance with applicable laws.",
    "The seller declares that they own or have all necessary rights and, to the extent permitted by law, indemnifies Tatik against claims arising from the product or third-party rights.",
    "The seller provides an accurate description, instructions, and product support, and handles the legal obligations owed to their buyers.",
    "Uploading malware, credentials, personal data, unlawful content, or material that infringes third-party rights is prohibited.",
    "Every file undergoes automated static checks. These checks do not certify security or legal compliance. Suspicious content may be held for review, and published listings may be suspended or removed.",
    "Tatik retains a 15% commission on each sale.",
    "The net balance remains pending until the anti-fraud period has expired and refunds have been reviewed.",
    "Refunds and disputes may result in deductions from the seller's balance.",
    "Payouts require KYC verification and a configured payment provider.",
    "Accepting these terms does not replace legal review or exclude any liability that cannot be waived by law.",
  ],
  it: [
    "Il venditore è l'unico responsabile del template, dei file e dei contenuti offerti, della loro qualità, correttezza, sicurezza, licenza e conformità alle leggi applicabili.",
    "Il venditore dichiara di possedere o disporre di tutti i diritti necessari e manleva Tatik nei limiti consentiti dalla legge da contestazioni derivanti dal prodotto o dai diritti di terzi.",
    "Il venditore fornisce descrizione veritiera, istruzioni e supporto sul prodotto e gestisce gli obblighi verso i propri acquirenti previsti dalla legge.",
    "È vietato caricare malware, credenziali, dati personali, contenuti illeciti o materiale che violi diritti di terzi.",
    "Ogni file viene sottoposto a controlli automatici statici. I controlli non certificano la sicurezza o la conformità legale; i contenuti sospetti possono essere trattenuti per revisione e i listing pubblicati possono essere sospesi o rimossi.",
    "Tatik trattiene una commissione del 15% su ogni vendita.",
    "Il saldo netto resta in sospeso fino alla scadenza del periodo anti-frode e alla verifica dei rimborsi.",
    "Rimborsi e contestazioni possono stornare il saldo del venditore.",
    "I payout richiedono verifica KYC e un provider di pagamento configurato.",
    "L'accettazione dei termini non sostituisce la revisione legale e non esclude responsabilità inderogabili previste dalla legge.",
  ],
  es: [
    "El vendedor es el único responsable de las plantillas, los archivos y el contenido ofrecidos, así como de su calidad, exactitud, seguridad, licencia y cumplimiento de las leyes aplicables.",
    "El vendedor declara que posee o dispone de todos los derechos necesarios e indemniza a Tatik, en la medida permitida por la ley, frente a reclamaciones derivadas del producto o de derechos de terceros.",
    "El vendedor proporciona una descripción veraz, instrucciones y asistencia sobre el producto, y gestiona las obligaciones legales que le corresponden frente a sus compradores.",
    "Está prohibido subir malware, credenciales, datos personales, contenido ilícito o material que infrinja derechos de terceros.",
    "Todos los archivos se someten a controles estáticos automatizados. Estos controles no certifican la seguridad ni el cumplimiento legal. El contenido sospechoso puede quedar retenido para su revisión y los anuncios publicados pueden suspenderse o retirarse.",
    "Tatik retiene una comisión del 15 % por cada venta.",
    "El saldo neto queda pendiente hasta que finalice el periodo antifraude y se revisen los reembolsos.",
    "Los reembolsos y las reclamaciones pueden dar lugar a deducciones del saldo del vendedor.",
    "Los pagos requieren verificación KYC y un proveedor de pagos configurado.",
    "La aceptación de estas condiciones no sustituye una revisión legal ni excluye responsabilidades que la ley no permita excluir.",
  ],
  fr: [
    "Le vendeur est seul responsable des modèles, fichiers et contenus proposés, ainsi que de leur qualité, exactitude, sécurité, licence et conformité aux lois applicables.",
    "Le vendeur déclare détenir ou disposer de tous les droits nécessaires et garantit Tatik, dans les limites autorisées par la loi, contre les réclamations liées au produit ou aux droits de tiers.",
    "Le vendeur fournit une description fidèle, des instructions et une assistance sur le produit, et assume les obligations légales qui lui incombent envers ses acheteurs.",
    "Il est interdit de téléverser des logiciels malveillants, des identifiants, des données personnelles, des contenus illicites ou des éléments portant atteinte aux droits de tiers.",
    "Chaque fichier fait l'objet de contrôles statiques automatisés. Ces contrôles ne certifient ni la sécurité ni la conformité juridique. Les contenus suspects peuvent être retenus pour examen et les annonces publiées peuvent être suspendues ou supprimées.",
    "Tatik prélève une commission de 15 % sur chaque vente.",
    "Le solde net reste en attente jusqu'à l'expiration de la période antifraude et à l'examen des remboursements.",
    "Les remboursements et litiges peuvent entraîner des déductions du solde du vendeur.",
    "Les versements nécessitent une vérification KYC et un prestataire de paiement configuré.",
    "L'acceptation de ces conditions ne remplace pas un examen juridique et n'exclut aucune responsabilité qui ne peut l'être en vertu de la loi.",
  ],
  de: [
    "Der Verkäufer ist allein für die angebotenen Vorlagen, Dateien und Inhalte sowie deren Qualität, Richtigkeit, Sicherheit, Lizenzierung und Übereinstimmung mit den geltenden Gesetzen verantwortlich.",
    "Der Verkäufer erklärt, alle erforderlichen Rechte zu besitzen oder darüber verfügen zu dürfen, und stellt Tatik im gesetzlich zulässigen Umfang von Ansprüchen frei, die sich aus dem Produkt oder Rechten Dritter ergeben.",
    "Der Verkäufer stellt eine wahrheitsgemäße Beschreibung, Anweisungen und Produktsupport bereit und erfüllt die gesetzlich vorgesehenen Pflichten gegenüber den eigenen Käufern.",
    "Das Hochladen von Malware, Zugangsdaten, personenbezogenen Daten, rechtswidrigen Inhalten oder Material, das Rechte Dritter verletzt, ist untersagt.",
    "Alle Dateien werden automatisierten statischen Prüfungen unterzogen. Diese Prüfungen bestätigen weder die Sicherheit noch die rechtliche Konformität. Verdächtige Inhalte können zur Überprüfung zurückgehalten und veröffentlichte Angebote ausgesetzt oder entfernt werden.",
    "Tatik behält bei jedem Verkauf eine Provision von 15 % ein.",
    "Der Nettosaldo bleibt bis zum Ablauf der Betrugspräventionsfrist und bis zur Prüfung möglicher Rückerstattungen ausstehend.",
    "Rückerstattungen und Streitfälle können zu einer Rückbuchung des Verkäufersaldos führen.",
    "Auszahlungen setzen eine KYC-Prüfung und einen konfigurierten Zahlungsanbieter voraus.",
    "Die Zustimmung zu diesen Bedingungen ersetzt keine rechtliche Prüfung und schließt zwingende gesetzliche Haftung nicht aus.",
  ],
  pt: [
    "O vendedor é o único responsável pelos modelos, ficheiros e conteúdos oferecidos, incluindo a sua qualidade, exatidão, segurança, licenciamento e conformidade com as leis aplicáveis.",
    "O vendedor declara possuir ou dispor de todos os direitos necessários e, nos limites permitidos por lei, indemniza a Tatik contra reclamações decorrentes do produto ou de direitos de terceiros.",
    "O vendedor fornece uma descrição verdadeira, instruções e assistência sobre o produto e cumpre as obrigações legais que lhe cabem perante os seus compradores.",
    "É proibido carregar malware, credenciais, dados pessoais, conteúdos ilícitos ou material que viole direitos de terceiros.",
    "Todos os ficheiros são submetidos a verificações estáticas automatizadas. Estas verificações não certificam a segurança nem a conformidade legal. Conteúdos suspeitos podem ficar retidos para análise e anúncios publicados podem ser suspensos ou removidos.",
    "A Tatik retém uma comissão de 15% em cada venda.",
    "O saldo líquido fica pendente até terminar o período antifraude e serem analisados os reembolsos.",
    "Reembolsos e litígios podem resultar em deduções ao saldo do vendedor.",
    "Os pagamentos exigem verificação KYC e um prestador de pagamentos configurado.",
    "A aceitação destes termos não substitui uma análise jurídica nem exclui responsabilidades que a lei não permita excluir.",
  ],
  ru: [
    "Продавец несёт исключительную ответственность за предлагаемые шаблоны, файлы и материалы, включая их качество, точность, безопасность, лицензирование и соответствие применимому законодательству.",
    "Продавец заявляет, что владеет всеми необходимыми правами или располагает ими, и в пределах, допускаемых законом, ограждает Tatik от претензий, связанных с продуктом или правами третьих лиц.",
    "Продавец предоставляет достоверное описание, инструкции и поддержку продукта, а также исполняет предусмотренные законом обязательства перед своими покупателями.",
    "Запрещено загружать вредоносное ПО, учётные данные, персональные данные, незаконные материалы или контент, нарушающий права третьих лиц.",
    "Каждый файл проходит автоматические статические проверки. Они не подтверждают безопасность или соответствие законодательству. Подозрительные материалы могут быть задержаны для проверки, а опубликованные объявления — приостановлены или удалены.",
    "Tatik удерживает комиссию в размере 15% с каждой продажи.",
    "Чистый остаток остаётся на удержании до окончания периода защиты от мошенничества и проверки возвратов.",
    "Возвраты и споры могут привести к списанию средств с баланса продавца.",
    "Для выплат необходимы проверка KYC и настроенный платёжный провайдер.",
    "Принятие этих условий не заменяет юридическую проверку и не исключает ответственность, от которой нельзя отказаться по закону.",
  ],
  zh: [
    "卖家对所提供的模板、文件和内容，以及其质量、准确性、安全性、许可和对适用法律的遵守情况承担全部责任。",
    "卖家声明其拥有或已取得所有必要权利，并在法律允许的范围内，就因产品或第三方权利引起的索赔向 Tatik 提供保障。",
    "卖家应提供真实的产品说明、使用指南和产品支持，并履行法律规定的对买家义务。",
    "禁止上传恶意软件、凭据、个人数据、违法内容或侵犯第三方权利的材料。",
    "每个文件都会接受自动静态检查。这些检查不构成对安全性或法律合规性的认证。可疑内容可能会被暂缓以供审核，已发布的商品也可能被暂停或移除。",
    "Tatik 对每笔销售收取 15% 的佣金。",
    "净余额将在反欺诈期结束且退款审核完成后解除待处理状态。",
    "退款和争议可能导致从卖家余额中扣款。",
    "提现需要完成 KYC 身份验证并配置支付服务提供商。",
    "接受本条款并不替代法律审查，也不免除法律规定不得排除的责任。",
  ],
  ja: [
    "販売者は、提供するテンプレート、ファイルおよびコンテンツについて、その品質、正確性、安全性、ライセンスならびに適用法令への適合性を含め、単独で責任を負います。",
    "販売者は必要なすべての権利を保有している、または使用する権限を有していることを表明し、法律で認められる範囲で、商品または第三者の権利に起因する申し立てから Tatik を免責します。",
    "販売者は正確な説明、使用方法および商品サポートを提供し、購入者に対して法律上負う義務を履行します。",
    "マルウェア、認証情報、個人データ、違法なコンテンツ、または第三者の権利を侵害する素材のアップロードは禁止されています。",
    "すべてのファイルは自動の静的チェックを受けます。このチェックは安全性や法令遵守を保証するものではありません。不審なコンテンツは審査のため保留され、公開済みの出品は停止または削除される場合があります。",
    "Tatik は各販売から 15% の手数料を差し引きます。",
    "純残高は、不正防止期間が終了し、返金の確認が完了するまで保留されます。",
    "返金や紛争により、販売者の残高から金額が差し引かれる場合があります。",
    "出金には KYC 確認と決済プロバイダーの設定が必要です。",
    "本規約への同意は法的審査に代わるものではなく、法律上免除できない責任を排除するものではありません。",
  ],
  ko: [
    "판매자는 제공하는 템플릿, 파일 및 콘텐츠와 그 품질, 정확성, 보안, 라이선스 및 관련 법률 준수에 대해 전적으로 책임을 집니다.",
    "판매자는 필요한 모든 권리를 보유하거나 사용할 권한이 있음을 선언하며, 법률이 허용하는 범위에서 제품 또는 제3자 권리로 인해 발생하는 청구로부터 Tatik을 면책합니다.",
    "판매자는 정확한 설명, 사용 안내 및 제품 지원을 제공하고 구매자에 대한 법적 의무를 이행합니다.",
    "악성코드, 인증 정보, 개인정보, 불법 콘텐츠 또는 제3자의 권리를 침해하는 자료를 업로드하는 행위는 금지됩니다.",
    "모든 파일은 자동 정적 검사를 받습니다. 이 검사는 보안이나 법률 준수를 인증하지 않습니다. 의심스러운 콘텐츠는 검토를 위해 보류될 수 있으며 게시된 상품은 일시 중지되거나 삭제될 수 있습니다.",
    "Tatik은 각 판매 금액의 15%를 수수료로 보유합니다.",
    "순 잔액은 사기 방지 기간이 끝나고 환불 검토가 완료될 때까지 보류됩니다.",
    "환불 및 분쟁으로 인해 판매자 잔액에서 금액이 차감될 수 있습니다.",
    "지급을 받으려면 KYC 인증과 결제 제공업체 설정이 필요합니다.",
    "본 약관에 동의하더라도 법률 검토를 대체하지 않으며 법률상 배제할 수 없는 책임을 면제하지 않습니다.",
  ],
  ar: [
    "يتحمل البائع وحده المسؤولية عن القوالب والملفات والمحتوى المعروض، بما في ذلك جودته ودقته وأمانه وترخيصه وامتثاله للقوانين المعمول بها.",
    "يقرّ البائع بأنه يملك جميع الحقوق اللازمة أو لديه الحق في استخدامها، ويعوض Tatik، بالقدر الذي يسمح به القانون، عن المطالبات الناشئة عن المنتج أو حقوق الغير.",
    "يقدم البائع وصفًا دقيقًا وتعليمات ودعمًا للمنتج، ويتولى الوفاء بالالتزامات القانونية تجاه المشترين.",
    "يُحظر تحميل البرمجيات الخبيثة أو بيانات الاعتماد أو البيانات الشخصية أو المحتوى غير القانوني أو المواد التي تنتهك حقوق الغير.",
    "تخضع كل الملفات لفحوصات ثابتة آلية. ولا تثبت هذه الفحوصات الأمان أو الامتثال القانوني. قد يُحتجز المحتوى المريب للمراجعة، وقد تُعلّق الإعلانات المنشورة أو تُزال.",
    "تحتفظ Tatik بعمولة قدرها 15% من كل عملية بيع.",
    "يظل صافي الرصيد قيد الانتظار حتى انتهاء فترة مكافحة الاحتيال ومراجعة المبالغ المستردة.",
    "قد تؤدي عمليات الاسترداد والنزاعات إلى خصم مبالغ من رصيد البائع.",
    "تتطلب المدفوعات التحقق من الهوية وفق KYC وإعداد مزود للدفع.",
    "لا يحل قبول هذه الشروط محل المراجعة القانونية ولا يستبعد أي مسؤولية لا يسمح القانون باستبعادها.",
  ],
  hi: [
    "विक्रेता पेश किए गए टेम्पलेट, फ़ाइलों और सामग्री तथा उनकी गुणवत्ता, सटीकता, सुरक्षा, लाइसेंस और लागू कानूनों के अनुपालन के लिए पूरी तरह जिम्मेदार है।",
    "विक्रेता घोषित करता है कि उसके पास सभी आवश्यक अधिकार हैं या उनका उपयोग करने की अनुमति है, और कानून द्वारा अनुमत सीमा तक उत्पाद या तीसरे पक्ष के अधिकारों से उत्पन्न दावों के विरुद्ध Tatik को क्षतिपूर्ति देता है।",
    "विक्रेता सटीक विवरण, निर्देश और उत्पाद सहायता देता है तथा खरीदारों के प्रति अपने कानूनी दायित्वों को पूरा करता है।",
    "मैलवेयर, लॉगिन क्रेडेंशियल, व्यक्तिगत डेटा, गैरकानूनी सामग्री या तीसरे पक्ष के अधिकारों का उल्लंघन करने वाली सामग्री अपलोड करना प्रतिबंधित है।",
    "हर फ़ाइल की स्वचालित स्थिर जांच की जाती है। ये जांच सुरक्षा या कानूनी अनुपालन प्रमाणित नहीं करतीं। संदिग्ध सामग्री समीक्षा के लिए रोकी जा सकती है और प्रकाशित लिस्टिंग निलंबित या हटाई जा सकती हैं।",
    "Tatik प्रत्येक बिक्री पर 15% कमीशन रखता है।",
    "धोखाधड़ी-रोधी अवधि समाप्त होने और रिफंड की समीक्षा पूरी होने तक शुद्ध शेष राशि लंबित रहती है।",
    "रिफंड और विवादों के कारण विक्रेता की शेष राशि से कटौती हो सकती है।",
    "भुगतान प्राप्त करने के लिए KYC सत्यापन और भुगतान प्रदाता का कॉन्फ़िगरेशन आवश्यक है।",
    "इन शर्तों को स्वीकार करना कानूनी समीक्षा का विकल्प नहीं है और कानून के तहत अपवर्जित न की जा सकने वाली देयता को समाप्त नहीं करता।",
  ],
  pl: [
    "Sprzedawca ponosi wyłączną odpowiedzialność za oferowane szablony, pliki i treści, w tym za ich jakość, poprawność, bezpieczeństwo, licencję i zgodność z obowiązującym prawem.",
    "Sprzedawca oświadcza, że posiada wszystkie niezbędne prawa lub może z nich korzystać, oraz w zakresie dozwolonym przez prawo zwalnia Tatik z roszczeń wynikających z produktu lub praw osób trzecich.",
    "Sprzedawca zapewnia rzetelny opis, instrukcje i pomoc dotyczącą produktu oraz wypełnia obowiązki prawne wobec swoich nabywców.",
    "Zabrania się przesyłania złośliwego oprogramowania, danych uwierzytelniających, danych osobowych, treści niezgodnych z prawem lub materiałów naruszających prawa osób trzecich.",
    "Każdy plik podlega automatycznym kontrolom statycznym. Kontrole te nie potwierdzają bezpieczeństwa ani zgodności z prawem. Podejrzane treści mogą zostać wstrzymane do kontroli, a opublikowane oferty mogą zostać zawieszone lub usunięte.",
    "Tatik pobiera prowizję w wysokości 15% od każdej sprzedaży.",
    "Saldo netto pozostaje wstrzymane do końca okresu przeciwdziałania oszustwom i sprawdzenia zwrotów.",
    "Zwroty i spory mogą skutkować potrąceniami z salda sprzedawcy.",
    "Wypłaty wymagają weryfikacji KYC i skonfigurowanego operatora płatności.",
    "Akceptacja tych warunków nie zastępuje kontroli prawnej ani nie wyłącza odpowiedzialności, której nie można wyłączyć na mocy prawa.",
  ],
  nl: [
    "De verkoper is als enige verantwoordelijk voor de aangeboden sjablonen, bestanden en inhoud, en voor de kwaliteit, juistheid, veiligheid, licentie en naleving van toepasselijke wetgeving.",
    "De verkoper verklaart alle benodigde rechten te bezitten of te mogen gebruiken en vrijwaart Tatik, voor zover wettelijk toegestaan, tegen claims die voortvloeien uit het product of rechten van derden.",
    "De verkoper verstrekt een juiste beschrijving, instructies en productondersteuning en voldoet aan de wettelijke verplichtingen tegenover eigen kopers.",
    "Het uploaden van malware, inloggegevens, persoonsgegevens, onwettige inhoud of materiaal dat rechten van derden schendt, is verboden.",
    "Elk bestand wordt automatisch statisch gecontroleerd. Deze controles garanderen geen veiligheid of wettelijke naleving. Verdachte inhoud kan worden vastgehouden voor beoordeling en gepubliceerde aanbiedingen kunnen worden geschorst of verwijderd.",
    "Tatik houdt 15% commissie in op elke verkoop.",
    "Het nettosaldo blijft in behandeling totdat de fraudepreventieperiode is verstreken en terugbetalingen zijn beoordeeld.",
    "Terugbetalingen en geschillen kunnen leiden tot inhoudingen op het saldo van de verkoper.",
    "Uitbetalingen vereisen KYC-verificatie en een geconfigureerde betalingsprovider.",
    "Aanvaarding van deze voorwaarden vervangt geen juridische beoordeling en sluit aansprakelijkheid die wettelijk niet kan worden uitgesloten niet uit.",
  ],
  tr: [
    "Satıcı; sunduğu şablonlardan, dosyalardan ve içeriklerden, bunların kalitesinden, doğruluğundan, güvenliğinden, lisansından ve yürürlükteki yasalara uygunluğundan münhasıran sorumludur.",
    "Satıcı gerekli tüm haklara sahip olduğunu veya bunları kullanma yetkisi bulunduğunu beyan eder ve yasaların izin verdiği ölçüde, ürün veya üçüncü taraf haklarından doğan taleplere karşı Tatik'i tazmin eder.",
    "Satıcı doğru bir açıklama, talimatlar ve ürün desteği sağlar ve alıcılarına karşı yasal yükümlülüklerini yerine getirir.",
    "Kötü amaçlı yazılım, kimlik bilgileri, kişisel veriler, yasa dışı içerik veya üçüncü tarafların haklarını ihlal eden materyallerin yüklenmesi yasaktır.",
    "Her dosya otomatik statik kontrollerden geçirilir. Bu kontroller güvenliği veya yasal uygunluğu belgelemez. Şüpheli içerik inceleme için bekletilebilir ve yayımlanmış ilanlar askıya alınabilir veya kaldırılabilir.",
    "Tatik her satıştan %15 komisyon alır.",
    "Net bakiye, dolandırıcılığı önleme süresi sona erene ve iadeler incelenene kadar beklemede kalır.",
    "İadeler ve anlaşmazlıklar satıcı bakiyesinden kesintilere yol açabilir.",
    "Ödeme alınabilmesi için KYC doğrulaması ve yapılandırılmış bir ödeme sağlayıcısı gerekir.",
    "Bu koşulların kabulü hukuki incelemenin yerini tutmaz ve yasalar uyarınca hariç tutulamayacak sorumlulukları ortadan kaldırmaz.",
  ],
  sv: [
    "Säljaren ansvarar ensam för de mallar, filer och det innehåll som erbjuds, inklusive kvalitet, riktighet, säkerhet, licensiering och efterlevnad av tillämpliga lagar.",
    "Säljaren intygar att hen äger eller har rätt att använda alla nödvändiga rättigheter och håller, i den utsträckning lagen tillåter, Tatik skadeslöst från anspråk som uppstår genom produkten eller tredje parts rättigheter.",
    "Säljaren tillhandahåller en korrekt beskrivning, instruktioner och produktsupport samt fullgör sina lagstadgade skyldigheter gentemot köparna.",
    "Det är förbjudet att ladda upp skadlig kod, inloggningsuppgifter, personuppgifter, olagligt innehåll eller material som kränker tredje parts rättigheter.",
    "Alla filer genomgår automatiska statiska kontroller. Kontrollerna intygar inte säkerhet eller rättslig efterlevnad. Misstänkt innehåll kan hållas kvar för granskning och publicerade annonser kan stängas av eller tas bort.",
    "Tatik behåller en provision på 15 % av varje försäljning.",
    "Nettosaldot hålls inne tills bedrägeriförebyggande perioden har löpt ut och återbetalningar har granskats.",
    "Återbetalningar och tvister kan leda till avdrag från säljarens saldo.",
    "Utbetalningar kräver KYC-verifiering och en konfigurerad betalningsleverantör.",
    "Godkännande av dessa villkor ersätter inte juridisk granskning och utesluter inte ansvar som enligt lag inte får avtalas bort.",
  ],
  da: [
    "Sælgeren er eneansvarlig for de tilbudte skabeloner, filer og det tilbudte indhold, herunder kvalitet, korrekthed, sikkerhed, licensering og overholdelse af gældende lovgivning.",
    "Sælgeren erklærer at eje eller have ret til at bruge alle nødvendige rettigheder og holder, i det omfang loven tillader det, Tatik skadesløs for krav, der udspringer af produktet eller tredjeparts rettigheder.",
    "Sælgeren giver en retvisende beskrivelse, instruktioner og produktsupport og opfylder sine lovmæssige forpligtelser over for køberne.",
    "Det er forbudt at uploade malware, loginoplysninger, personoplysninger, ulovligt indhold eller materiale, der krænker tredjeparts rettigheder.",
    "Alle filer gennemgår automatiske statiske kontroller. Kontrollerne certificerer ikke sikkerhed eller juridisk overholdelse. Mistænkeligt indhold kan tilbageholdes til gennemgang, og offentliggjorte annoncer kan suspenderes eller fjernes.",
    "Tatik tilbageholder en provision på 15 % af hvert salg.",
    "Nettosaldoen forbliver tilbageholdt, indtil perioden for forebyggelse af svindel er udløbet, og tilbagebetalinger er gennemgået.",
    "Tilbagebetalinger og tvister kan medføre fradrag i sælgerens saldo.",
    "Udbetalinger kræver KYC-verifikation og en konfigureret betalingsudbyder.",
    "Accept af disse vilkår erstatter ikke juridisk gennemgang og udelukker ikke ansvar, der ikke kan fraskrives efter loven.",
  ],
  no: [
    "Selgeren er eneansvarlig for malene, filene og innholdet som tilbys, inkludert kvalitet, nøyaktighet, sikkerhet, lisensiering og overholdelse av gjeldende lover.",
    "Selgeren erklærer å eie eller ha rett til å bruke alle nødvendige rettigheter og holder, i den grad loven tillater det, Tatik skadesløs for krav som følger av produktet eller tredjeparts rettigheter.",
    "Selgeren gir en korrekt beskrivelse, instruksjoner og produktstøtte og oppfyller sine lovpålagte forpliktelser overfor kjøperne.",
    "Det er forbudt å laste opp skadelig programvare, påloggingsinformasjon, personopplysninger, ulovlig innhold eller materiale som krenker tredjeparts rettigheter.",
    "Alle filer gjennomgår automatiske statiske kontroller. Kontrollene bekrefter ikke sikkerhet eller juridisk samsvar. Mistenkelig innhold kan holdes tilbake for gjennomgang, og publiserte annonser kan suspenderes eller fjernes.",
    "Tatik holder tilbake en provisjon på 15 % av hvert salg.",
    "Nettosaldoen holdes tilbake til perioden for svindelforebygging er utløpt og refusjoner er gjennomgått.",
    "Refusjoner og tvister kan føre til trekk fra selgerens saldo.",
    "Utbetalinger krever KYC-verifisering og en konfigurert betalingstilbyder.",
    "Aksept av disse vilkårene erstatter ikke juridisk gjennomgang og utelukker ikke ansvar som ikke kan fraskrives etter loven.",
  ],
  fi: [
    "Myyjä vastaa yksin tarjoamistaan malleista, tiedostoista ja sisällöistä sekä niiden laadusta, oikeellisuudesta, turvallisuudesta, lisensoinnista ja sovellettavien lakien noudattamisesta.",
    "Myyjä vakuuttaa omistavansa kaikki tarvittavat oikeudet tai olevansa oikeutettu käyttämään niitä ja vapauttaa lain sallimissa rajoissa Tatikin tuotteesta tai kolmansien osapuolten oikeuksista johtuvista vaatimuksista.",
    "Myyjä antaa totuudenmukaisen kuvauksen, ohjeet ja tuotetuen sekä hoitaa ostajilleen kuuluvat lakisääteiset velvoitteet.",
    "Haittaohjelmien, tunnistetietojen, henkilötietojen, lainvastaisen sisällön tai kolmansien osapuolten oikeuksia loukkaavan aineiston lataaminen on kielletty.",
    "Kaikki tiedostot tarkastetaan automaattisilla staattisilla tarkistuksilla. Tarkistukset eivät sertifioi turvallisuutta tai lainmukaisuutta. Epäilyttävä sisältö voidaan pidättää tarkastusta varten, ja julkaistut ilmoitukset voidaan keskeyttää tai poistaa.",
    "Tatik pidättää jokaisesta myynnistä 15 prosentin palkkion.",
    "Nettosaldo pysyy odottavana, kunnes petostentorjunta-aika on päättynyt ja hyvitykset on tarkistettu.",
    "Hyvitykset ja riidat voivat johtaa vähennyksiin myyjän saldosta.",
    "Maksut edellyttävät KYC-tunnistautumista ja määritettyä maksupalveluntarjoajaa.",
    "Näiden ehtojen hyväksyminen ei korvaa oikeudellista tarkastelua eikä sulje pois vastuuta, jota ei lain mukaan voida sulkea pois.",
  ],
  uk: [
    "Продавець несе одноосібну відповідальність за запропоновані шаблони, файли й вміст, зокрема за їхню якість, точність, безпеку, ліцензування та відповідність чинному законодавству.",
    "Продавець заявляє, що володіє всіма необхідними правами або має право ними користуватися, і в межах, дозволених законом, відшкодовує Tatik претензії, що виникають через продукт або права третіх осіб.",
    "Продавець надає достовірний опис, інструкції та підтримку продукту й виконує передбачені законом зобов'язання перед покупцями.",
    "Заборонено завантажувати шкідливе програмне забезпечення, облікові дані, персональні дані, незаконний вміст або матеріали, що порушують права третіх осіб.",
    "Усі файли проходять автоматичні статичні перевірки. Ці перевірки не підтверджують безпеку чи відповідність законодавству. Підозрілий вміст може бути затриманий для перевірки, а опубліковані оголошення — призупинені або видалені.",
    "Tatik утримує комісію в розмірі 15% з кожного продажу.",
    "Чистий залишок залишається на утриманні до завершення періоду протидії шахрайству та перевірки повернень.",
    "Повернення коштів і спори можуть призвести до списань із балансу продавця.",
    "Для виплат потрібні перевірка KYC і налаштований платіжний провайдер.",
    "Прийняття цих умов не замінює юридичну перевірку й не виключає відповідальність, якої не можна уникнути за законом.",
  ],
  cs: [
    "Prodávající nese výhradní odpovědnost za nabízené šablony, soubory a obsah, včetně jejich kvality, správnosti, bezpečnosti, licencování a souladu s platnými právními předpisy.",
    "Prodávající prohlašuje, že vlastní všechna potřebná práva nebo je oprávněn je užívat, a v rozsahu povoleném zákonem odškodní Tatik za nároky vyplývající z produktu nebo práv třetích osob.",
    "Prodávající poskytuje pravdivý popis, pokyny a podporu k produktu a plní zákonné povinnosti vůči svým kupujícím.",
    "Je zakázáno nahrávat malware, přihlašovací údaje, osobní údaje, nezákonný obsah nebo materiály porušující práva třetích osob.",
    "Každý soubor prochází automatickými statickými kontrolami. Tyto kontroly nepotvrzují bezpečnost ani soulad s právními předpisy. Podezřelý obsah může být zadržen k přezkoumání a zveřejněné nabídky mohou být pozastaveny nebo odstraněny.",
    "Tatik si z každého prodeje ponechává provizi ve výši 15 %.",
    "Čistý zůstatek zůstává pozastavený do uplynutí období ochrany proti podvodům a kontroly vrácených plateb.",
    "Vrácení plateb a spory mohou vést ke srážkám ze zůstatku prodávajícího.",
    "Výplaty vyžadují ověření KYC a nakonfigurovaného poskytovatele plateb.",
    "Přijetí těchto podmínek nenahrazuje právní posouzení a nevylučuje odpovědnost, kterou nelze podle zákona vyloučit.",
  ],
};

export const officialSellerTermsLabels: Record<string, string> = {
  en: "Show the official Italian terms",
  it: "Mostra i termini ufficiali in italiano",
  es: "Mostrar las condiciones oficiales en italiano",
  fr: "Afficher les conditions officielles en italien",
  de: "Verbindliche italienische Originalfassung anzeigen",
  pt: "Mostrar os termos oficiais em italiano",
  ru: "Показать официальные условия на итальянском языке",
  zh: "显示意大利语官方条款",
  ja: "イタリア語の公式規約を表示",
  ko: "이탈리아어 공식 약관 보기",
  ar: "عرض الشروط الرسمية باللغة الإيطالية",
  hi: "आधिकारिक इतालवी शर्तें दिखाएँ",
  pl: "Pokaż oficjalne warunki w języku włoskim",
  nl: "De officiële Italiaanse voorwaarden weergeven",
  tr: "Resmî İtalyanca koşulları göster",
  sv: "Visa de officiella villkoren på italienska",
  da: "Vis de officielle vilkår på italiensk",
  no: "Vis de offisielle vilkårene på italiensk",
  fi: "Näytä viralliset italiankieliset ehdot",
  uk: "Показати офіційні умови італійською мовою",
  cs: "Zobrazit oficiální podmínky v italštině",
};
