export const siteSurfaceCopy = {
  en: {
    navbar: {
      home: 'Tatik.space home',
      logo: 'Tatik logo',
      menu: 'Menu',
      openMenu: 'Open navigation menu',
      closeMenu: 'Close navigation menu',
      developerMarketplace: 'Developer Marketplace',
    },
    footer: {
      navigation: 'Footer navigation',
      schools: 'School program',
      copyright: 'All rights reserved',
      authorCredit: 'Developed by Tatik, the author’s identifying pseudonym under art. 9 of the Civil Code.',
    },
    cookies: {
      title: 'Use of Cookies',
      intro: 'See our',
      and: 'and',
      necessary: 'Necessary Cookies',
      necessaryDescription: 'Essential for the website to work (authentication, security).',
      functional: 'Functional Cookies',
      functionalDescription: 'Remember your preferences (language, theme).',
      analytics: 'Analytics Cookies',
      analyticsDescription: 'Help us understand how you use the website.',
      marketing: 'Marketing Cookies',
      marketingDescription: 'Personalize advertising content.',
      duration: 'Your consent is valid for 12 months.',
      modalDescription: 'Choose which cookie categories you want to accept.',
      required: '(required)',
    },
  },
  it: {
    navbar: {
      home: 'Pagina iniziale di Tatik.space',
      logo: 'Logo Tatik',
      menu: 'Menu',
      openMenu: 'Apri il menu di navigazione',
      closeMenu: 'Chiudi il menu di navigazione',
      developerMarketplace: 'Marketplace sviluppatori',
    },
    footer: {
      navigation: 'Navigazione del piè di pagina',
      schools: 'Programma scuole',
      copyright: 'Tutti i diritti riservati',
      authorCredit: 'Sviluppato da Tatik, pseudonimo identificativo dell’autore ai sensi dell’art. 9 c.c.',
    },
    cookies: {
      title: 'Utilizzo dei Cookie',
      intro: 'Consulta la nostra',
      and: 'e',
      necessary: 'Cookie Necessari',
      necessaryDescription: 'Essenziali per il funzionamento del sito (autenticazione, sicurezza).',
      functional: 'Cookie Funzionali',
      functionalDescription: 'Memorizzano le tue preferenze (lingua, tema).',
      analytics: 'Cookie Analitici',
      analyticsDescription: 'Ci aiutano a capire come utilizzi il sito.',
      marketing: 'Cookie Marketing',
      marketingDescription: 'Personalizzano i contenuti pubblicitari.',
      duration: 'Il consenso è valido per 12 mesi.',
      modalDescription: 'Seleziona quali categorie di cookie vuoi accettare.',
      required: '(obbligatorio)',
    },
  },
  es: {
    navbar: {
      home: 'Inicio de Tatik.space',
      logo: 'Logotipo de Tatik',
      menu: 'Menú',
      openMenu: 'Abrir menú de navegación',
      closeMenu: 'Cerrar menú de navegación',
      developerMarketplace: 'Marketplace para desarrolladores',
    },
    footer: {
      navigation: 'Navegación del pie de página',
      schools: 'Programa para escuelas',
      copyright: 'Todos los derechos reservados',
      authorCredit: 'Desarrollado por Tatik, seudónimo identificativo del autor conforme al art. 9 del Código Civil.',
    },
    cookies: {
      title: 'Uso de cookies',
      intro: 'Consulta nuestra',
      and: 'y',
      necessary: 'Cookies necesarias',
      necessaryDescription: 'Esenciales para el funcionamiento del sitio (autenticación y seguridad).',
      functional: 'Cookies funcionales',
      functionalDescription: 'Recuerdan tus preferencias (idioma y tema).',
      analytics: 'Cookies analíticas',
      analyticsDescription: 'Nos ayudan a entender cómo utilizas el sitio.',
      marketing: 'Cookies de marketing',
      marketingDescription: 'Personalizan el contenido publicitario.',
      duration: 'Tu consentimiento es válido durante 12 meses.',
      modalDescription: 'Selecciona qué categorías de cookies quieres aceptar.',
      required: '(obligatorias)',
    },
  },
  fr: {
    navbar: {
      home: 'Accueil de Tatik.space',
      logo: 'Logo Tatik',
      menu: 'Menu',
      openMenu: 'Ouvrir le menu de navigation',
      closeMenu: 'Fermer le menu de navigation',
      developerMarketplace: 'Marketplace des développeurs',
    },
    footer: {
      navigation: 'Navigation de pied de page',
      schools: 'Programme scolaire',
      copyright: 'Tous droits réservés',
      authorCredit: 'Développé par Tatik, pseudonyme identifiant l’auteur au sens de l’art. 9 du Code civil.',
    },
    cookies: {
      title: 'Utilisation des cookies',
      intro: 'Consultez notre',
      and: 'et',
      necessary: 'Cookies nécessaires',
      necessaryDescription: 'Essentiels au fonctionnement du site (authentification, sécurité).',
      functional: 'Cookies fonctionnels',
      functionalDescription: 'Mémorisent vos préférences (langue, thème).',
      analytics: 'Cookies analytiques',
      analyticsDescription: 'Nous aident à comprendre comment vous utilisez le site.',
      marketing: 'Cookies marketing',
      marketingDescription: 'Personnalisent le contenu publicitaire.',
      duration: 'Votre consentement est valable pendant 12 mois.',
      modalDescription: 'Choisissez les catégories de cookies que vous souhaitez accepter.',
      required: '(obligatoire)',
    },
  },
  de: {
    navbar: {
      home: 'Tatik.space-Startseite',
      logo: 'Tatik-Logo',
      menu: 'Menü',
      openMenu: 'Navigationsmenü öffnen',
      closeMenu: 'Navigationsmenü schließen',
      developerMarketplace: 'Marketplace für Entwickler',
    },
    footer: {
      navigation: 'Footer-Navigation',
      schools: 'Schulprogramm',
      copyright: 'Alle Rechte vorbehalten',
      authorCredit: 'Entwickelt von Tatik, dem Identifikationspseudonym des Autors gemäß Art. 9 des Zivilgesetzbuchs.',
    },
    cookies: {
      title: 'Verwendung von Cookies',
      intro: 'Lesen Sie unsere',
      and: 'und',
      necessary: 'Notwendige Cookies',
      necessaryDescription: 'Für den Betrieb der Website erforderlich (Authentifizierung, Sicherheit).',
      functional: 'Funktionale Cookies',
      functionalDescription: 'Speichern Ihre Einstellungen (Sprache, Design).',
      analytics: 'Analyse-Cookies',
      analyticsDescription: 'Helfen uns zu verstehen, wie Sie die Website nutzen.',
      marketing: 'Marketing-Cookies',
      marketingDescription: 'Personalisieren Werbeinhalte.',
      duration: 'Ihre Einwilligung ist 12 Monate gültig.',
      modalDescription: 'Wählen Sie aus, welche Cookie-Kategorien Sie akzeptieren möchten.',
      required: '(erforderlich)',
    },
  },
  pt: {
    navbar: {
      home: 'Página inicial da Tatik.space',
      logo: 'Logótipo da Tatik',
      menu: 'Menu',
      openMenu: 'Abrir menu de navegação',
      closeMenu: 'Fechar menu de navegação',
      developerMarketplace: 'Marketplace para desenvolvedores',
    },
    footer: {
      navigation: 'Navegação do rodapé',
      schools: 'Programa escolar',
      copyright: 'Todos os direitos reservados',
      authorCredit: 'Desenvolvido por Tatik, pseudónimo identificador do autor nos termos do art. 9.º do Código Civil.',
    },
    cookies: {
      title: 'Utilização de cookies',
      intro: 'Consulte a nossa',
      and: 'e',
      necessary: 'Cookies necessários',
      necessaryDescription: 'Essenciais para o funcionamento do site (autenticação, segurança).',
      functional: 'Cookies funcionais',
      functionalDescription: 'Memorizam as suas preferências (idioma, tema).',
      analytics: 'Cookies analíticos',
      analyticsDescription: 'Ajudam-nos a compreender como utiliza o site.',
      marketing: 'Cookies de marketing',
      marketingDescription: 'Personalizam o conteúdo publicitário.',
      duration: 'O seu consentimento é válido por 12 meses.',
      modalDescription: 'Selecione as categorias de cookies que pretende aceitar.',
      required: '(obrigatório)',
    },
  },
  ru: {
    navbar: {
      home: 'Главная страница Tatik.space',
      logo: 'Логотип Tatik',
      menu: 'Меню',
      openMenu: 'Открыть меню навигации',
      closeMenu: 'Закрыть меню навигации',
      developerMarketplace: 'Маркетплейс для разработчиков',
    },
    footer: {
      navigation: 'Навигация в нижней части страницы',
      schools: 'Программа для школ',
      copyright: 'Все права защищены',
      authorCredit: 'Разработано Tatik — идентифицирующий псевдоним автора согласно ст. 9 Гражданского кодекса.',
    },
    cookies: {
      title: 'Использование файлов cookie',
      intro: 'Ознакомьтесь с нашей',
      and: 'и',
      necessary: 'Обязательные файлы cookie',
      necessaryDescription: 'Необходимы для работы сайта (аутентификация, безопасность).',
      functional: 'Функциональные файлы cookie',
      functionalDescription: 'Сохраняют ваши предпочтения (язык, тема).',
      analytics: 'Аналитические файлы cookie',
      analyticsDescription: 'Помогают нам понять, как вы используете сайт.',
      marketing: 'Маркетинговые файлы cookie',
      marketingDescription: 'Персонализируют рекламный контент.',
      duration: 'Согласие действительно в течение 12 месяцев.',
      modalDescription: 'Выберите категории файлов cookie, которые хотите разрешить.',
      required: '(обязательно)',
    },
  },
  zh: {
    navbar: {
      home: 'Tatik.space 首页',
      logo: 'Tatik 标志',
      menu: '菜单',
      openMenu: '打开导航菜单',
      closeMenu: '关闭导航菜单',
      developerMarketplace: '开发者市场',
    },
    footer: {
      navigation: '页脚导航',
      schools: '学校计划',
      copyright: '版权所有',
      authorCredit: '由 Tatik 开发；Tatik 是作者依据《民法典》第 9 条使用的身份识别笔名。',
    },
    cookies: {
      title: 'Cookie 的使用',
      intro: '请查看我们的',
      and: '和',
      necessary: '必要 Cookie',
      necessaryDescription: '网站运行所必需（身份验证、安全）。',
      functional: '功能性 Cookie',
      functionalDescription: '记住您的偏好设置（语言、主题）。',
      analytics: '分析 Cookie',
      analyticsDescription: '帮助我们了解您如何使用网站。',
      marketing: '营销 Cookie',
      marketingDescription: '个性化广告内容。',
      duration: '您的同意有效期为 12 个月。',
      modalDescription: '选择您希望接受的 Cookie 类别。',
      required: '（必需）',
    },
  },
  ja: {
    navbar: {
      home: 'Tatik.space ホーム',
      logo: 'Tatik ロゴ',
      menu: 'メニュー',
      openMenu: 'ナビゲーションメニューを開く',
      closeMenu: 'ナビゲーションメニューを閉じる',
      developerMarketplace: '開発者マーケットプレイス',
    },
    footer: {
      navigation: 'フッターナビゲーション',
      schools: '学校向けプログラム',
      copyright: '無断転載を禁じます',
      authorCredit: 'Tatik が開発。Tatik は民法第9条に基づく著者の識別用仮名です。',
    },
    cookies: {
      title: 'Cookie の使用',
      intro: 'こちらをご覧ください：',
      and: 'および',
      necessary: '必須 Cookie',
      necessaryDescription: 'サイトの動作（認証・セキュリティ）に必要です。',
      functional: '機能 Cookie',
      functionalDescription: '設定（言語・テーマ）を保存します。',
      analytics: '分析 Cookie',
      analyticsDescription: 'サイトの利用状況の把握に役立ちます。',
      marketing: 'マーケティング Cookie',
      marketingDescription: '広告コンテンツをパーソナライズします。',
      duration: '同意の有効期間は12か月です。',
      modalDescription: '受け入れる Cookie のカテゴリを選択してください。',
      required: '（必須）',
    },
  },
  ko: {
    navbar: {
      home: 'Tatik.space 홈',
      logo: 'Tatik 로고',
      menu: '메뉴',
      openMenu: '탐색 메뉴 열기',
      closeMenu: '탐색 메뉴 닫기',
      developerMarketplace: '개발자 마켓플레이스',
    },
    footer: {
      navigation: '바닥글 탐색',
      schools: '학교 프로그램',
      copyright: '모든 권리 보유',
      authorCredit: 'Tatik 제작. Tatik은 민법 제9조에 따른 저자의 식별용 필명입니다.',
    },
    cookies: {
      title: '쿠키 사용',
      intro: '다음 정책을 확인하세요:',
      and: '및',
      necessary: '필수 쿠키',
      necessaryDescription: '사이트 작동(인증, 보안)에 필요합니다.',
      functional: '기능 쿠키',
      functionalDescription: '환경설정(언어, 테마)을 기억합니다.',
      analytics: '분석 쿠키',
      analyticsDescription: '사이트 이용 방식을 파악하는 데 도움이 됩니다.',
      marketing: '마케팅 쿠키',
      marketingDescription: '광고 콘텐츠를 개인화합니다.',
      duration: '동의는 12개월 동안 유효합니다.',
      modalDescription: '허용할 쿠키 카테고리를 선택하세요.',
      required: '(필수)',
    },
  },
  ar: {
    navbar: {
      home: 'الصفحة الرئيسية لـ Tatik.space',
      logo: 'شعار Tatik',
      menu: 'القائمة',
      openMenu: 'فتح قائمة التنقل',
      closeMenu: 'إغلاق قائمة التنقل',
      developerMarketplace: 'سوق المطورين',
    },
    footer: {
      navigation: 'التنقل في تذييل الصفحة',
      schools: 'برنامج المدارس',
      copyright: 'جميع الحقوق محفوظة',
      authorCredit: 'طُوّر بواسطة Tatik، وهو الاسم المستعار المعرّف للمؤلف وفقًا للمادة 9 من القانون المدني.',
    },
    cookies: {
      title: 'استخدام ملفات تعريف الارتباط',
      intro: 'راجع',
      and: 'و',
      necessary: 'ملفات تعريف الارتباط الضرورية',
      necessaryDescription: 'ضرورية لعمل الموقع (المصادقة والأمان).',
      functional: 'ملفات تعريف الارتباط الوظيفية',
      functionalDescription: 'تتذكر تفضيلاتك (اللغة والمظهر).',
      analytics: 'ملفات تعريف الارتباط التحليلية',
      analyticsDescription: 'تساعدنا على فهم كيفية استخدامك للموقع.',
      marketing: 'ملفات تعريف الارتباط التسويقية',
      marketingDescription: 'تخصص محتوى الإعلانات.',
      duration: 'تظل موافقتك سارية لمدة 12 شهرًا.',
      modalDescription: 'اختر فئات ملفات تعريف الارتباط التي تريد قبولها.',
      required: '(مطلوبة)',
    },
  },
  hi: {
    navbar: {
      home: 'Tatik.space होम',
      logo: 'Tatik लोगो',
      menu: 'मेन्यू',
      openMenu: 'नेविगेशन मेन्यू खोलें',
      closeMenu: 'नेविगेशन मेन्यू बंद करें',
      developerMarketplace: 'डेवलपर मार्केटप्लेस',
    },
    footer: {
      navigation: 'फ़ूटर नेविगेशन',
      schools: 'स्कूल कार्यक्रम',
      copyright: 'सर्वाधिकार सुरक्षित',
      authorCredit: 'Tatik द्वारा विकसित; Tatik नागरिक संहिता के अनुच्छेद 9 के तहत लेखक का पहचानसूचक छद्मनाम है।',
    },
    cookies: {
      title: 'कुकीज़ का उपयोग',
      intro: 'हमारी',
      and: 'और',
      necessary: 'आवश्यक कुकीज़',
      necessaryDescription: 'वेबसाइट के कामकाज (प्रमाणीकरण, सुरक्षा) के लिए आवश्यक।',
      functional: 'कार्यात्मक कुकीज़',
      functionalDescription: 'आपकी प्राथमिकताएँ (भाषा, थीम) याद रखती हैं।',
      analytics: 'विश्लेषणात्मक कुकीज़',
      analyticsDescription: 'यह समझने में मदद करती हैं कि आप वेबसाइट का उपयोग कैसे करते हैं।',
      marketing: 'मार्केटिंग कुकीज़',
      marketingDescription: 'विज्ञापन सामग्री को वैयक्तिकृत करती हैं।',
      duration: 'आपकी सहमति 12 महीनों तक मान्य है।',
      modalDescription: 'वे कुकी श्रेणियाँ चुनें जिन्हें आप स्वीकार करना चाहते हैं।',
      required: '(आवश्यक)',
    },
  },
  pl: {
    navbar: {
      home: 'Strona główna Tatik.space',
      logo: 'Logo Tatik',
      menu: 'Menu',
      openMenu: 'Otwórz menu nawigacyjne',
      closeMenu: 'Zamknij menu nawigacyjne',
      developerMarketplace: 'Marketplace dla deweloperów',
    },
    footer: {
      navigation: 'Nawigacja stopki',
      schools: 'Program dla szkół',
      copyright: 'Wszelkie prawa zastrzeżone',
      authorCredit: 'Opracowane przez Tatik, pseudonim identyfikujący autora w rozumieniu art. 9 Kodeksu cywilnego.',
    },
    cookies: {
      title: 'Wykorzystanie plików cookie',
      intro: 'Zapoznaj się z naszą',
      and: 'i',
      necessary: 'Niezbędne pliki cookie',
      necessaryDescription: 'Niezbędne do działania strony (uwierzytelnianie, bezpieczeństwo).',
      functional: 'Funkcjonalne pliki cookie',
      functionalDescription: 'Zapamiętują Twoje preferencje (język, motyw).',
      analytics: 'Analityczne pliki cookie',
      analyticsDescription: 'Pomagają nam zrozumieć, jak korzystasz ze strony.',
      marketing: 'Marketingowe pliki cookie',
      marketingDescription: 'Personalizują treści reklamowe.',
      duration: 'Zgoda jest ważna przez 12 miesięcy.',
      modalDescription: 'Wybierz kategorie plików cookie, które chcesz zaakceptować.',
      required: '(wymagane)',
    },
  },
  nl: {
    navbar: {
      home: 'Tatik.space-homepage',
      logo: 'Tatik-logo',
      menu: 'Menu',
      openMenu: 'Navigatiemenu openen',
      closeMenu: 'Navigatiemenu sluiten',
      developerMarketplace: 'Marketplace voor ontwikkelaars',
    },
    footer: {
      navigation: 'Voetnavigatie',
      schools: 'Schoolprogramma',
      copyright: 'Alle rechten voorbehouden',
      authorCredit: 'Ontwikkeld door Tatik, het identificerende pseudoniem van de auteur volgens art. 9 van het Burgerlijk Wetboek.',
    },
    cookies: {
      title: 'Gebruik van cookies',
      intro: 'Bekijk ons',
      and: 'en',
      necessary: 'Noodzakelijke cookies',
      necessaryDescription: 'Essentieel voor de werking van de website (authenticatie, beveiliging).',
      functional: 'Functionele cookies',
      functionalDescription: 'Onthouden uw voorkeuren (taal, thema).',
      analytics: 'Analytische cookies',
      analyticsDescription: 'Helpen ons te begrijpen hoe u de website gebruikt.',
      marketing: 'Marketingcookies',
      marketingDescription: 'Personaliseren advertentie-inhoud.',
      duration: 'Uw toestemming is 12 maanden geldig.',
      modalDescription: 'Kies welke cookiecategorieën u wilt accepteren.',
      required: '(vereist)',
    },
  },
  tr: {
    navbar: {
      home: 'Tatik.space ana sayfası',
      logo: 'Tatik logosu',
      menu: 'Menü',
      openMenu: 'Gezinme menüsünü aç',
      closeMenu: 'Gezinme menüsünü kapat',
      developerMarketplace: 'Geliştirici Pazaryeri',
    },
    footer: {
      navigation: 'Alt bilgi gezinmesi',
      schools: 'Okul programı',
      copyright: 'Tüm hakları saklıdır',
      authorCredit: 'Tatik tarafından geliştirildi; Tatik, Medeni Kanun’un 9. maddesi uyarınca yazarın kimlik belirleyici takma adıdır.',
    },
    cookies: {
      title: 'Çerezlerin Kullanımı',
      intro: 'Şu politikalarımıza göz atın:',
      and: 've',
      necessary: 'Gerekli Çerezler',
      necessaryDescription: 'Sitenin çalışması için gereklidir (kimlik doğrulama, güvenlik).',
      functional: 'İşlevsel Çerezler',
      functionalDescription: 'Tercihlerinizi (dil, tema) hatırlar.',
      analytics: 'Analitik Çerezler',
      analyticsDescription: 'Siteyi nasıl kullandığınızı anlamamıza yardımcı olur.',
      marketing: 'Pazarlama Çerezleri',
      marketingDescription: 'Reklam içeriklerini kişiselleştirir.',
      duration: 'Onayınız 12 ay boyunca geçerlidir.',
      modalDescription: 'Kabul etmek istediğiniz çerez kategorilerini seçin.',
      required: '(zorunlu)',
    },
  },
  sv: {
    navbar: {
      home: 'Tatik.space startsida',
      logo: 'Tatik-logotyp',
      menu: 'Meny',
      openMenu: 'Öppna navigeringsmenyn',
      closeMenu: 'Stäng navigeringsmenyn',
      developerMarketplace: 'Utvecklarmarknad',
    },
    footer: {
      navigation: 'Sidfotsnavigering',
      schools: 'Skolprogram',
      copyright: 'Alla rättigheter förbehållna',
      authorCredit: 'Utvecklad av Tatik, författarens identifierande pseudonym enligt artikel 9 i civillagen.',
    },
    cookies: {
      title: 'Användning av cookies',
      intro: 'Se vår',
      and: 'och',
      necessary: 'Nödvändiga cookies',
      necessaryDescription: 'Nödvändiga för att webbplatsen ska fungera (autentisering, säkerhet).',
      functional: 'Funktionella cookies',
      functionalDescription: 'Kommer ihåg dina inställningar (språk, tema).',
      analytics: 'Analyscookies',
      analyticsDescription: 'Hjälper oss att förstå hur du använder webbplatsen.',
      marketing: 'Marknadsföringscookies',
      marketingDescription: 'Anpassar reklaminnehåll.',
      duration: 'Ditt samtycke gäller i 12 månader.',
      modalDescription: 'Välj vilka cookiekategorier du vill godkänna.',
      required: '(obligatoriskt)',
    },
  },
  da: {
    navbar: {
      home: 'Tatik.space-startside',
      logo: 'Tatik-logo',
      menu: 'Menu',
      openMenu: 'Åbn navigationsmenu',
      closeMenu: 'Luk navigationsmenu',
      developerMarketplace: 'Udviklermarked',
    },
    footer: {
      navigation: 'Sidefodsnavigation',
      schools: 'Skoleprogram',
      copyright: 'Alle rettigheder forbeholdes',
      authorCredit: 'Udviklet af Tatik, forfatterens identificerende pseudonym i henhold til artikel 9 i civilloven.',
    },
    cookies: {
      title: 'Brug af cookies',
      intro: 'Se vores',
      and: 'og',
      necessary: 'Nødvendige cookies',
      necessaryDescription: 'Nødvendige for at hjemmesiden fungerer (godkendelse, sikkerhed).',
      functional: 'Funktionelle cookies',
      functionalDescription: 'Husker dine præferencer (sprog, tema).',
      analytics: 'Analysecookies',
      analyticsDescription: 'Hjælper os med at forstå, hvordan du bruger hjemmesiden.',
      marketing: 'Marketingcookies',
      marketingDescription: 'Tilpasser reklameindhold.',
      duration: 'Dit samtykke gælder i 12 måneder.',
      modalDescription: 'Vælg de cookiekategorier, du vil acceptere.',
      required: '(påkrævet)',
    },
  },
  no: {
    navbar: {
      home: 'Tatik.space-hjem',
      logo: 'Tatik-logo',
      menu: 'Meny',
      openMenu: 'Åpne navigasjonsmenyen',
      closeMenu: 'Lukk navigasjonsmenyen',
      developerMarketplace: 'Utviklermarked',
    },
    footer: {
      navigation: 'Navigasjon i bunnteksten',
      schools: 'Skoleprogram',
      copyright: 'Med enerett',
      authorCredit: 'Utviklet av Tatik, forfatterens identifiserende pseudonym i henhold til artikkel 9 i sivilloven.',
    },
    cookies: {
      title: 'Bruk av informasjonskapsler',
      intro: 'Se vår',
      and: 'og',
      necessary: 'Nødvendige informasjonskapsler',
      necessaryDescription: 'Nødvendige for at nettstedet skal fungere (autentisering, sikkerhet).',
      functional: 'Funksjonelle informasjonskapsler',
      functionalDescription: 'Husker preferansene dine (språk, tema).',
      analytics: 'Analyseinformasjonskapsler',
      analyticsDescription: 'Hjelper oss med å forstå hvordan du bruker nettstedet.',
      marketing: 'Markedsføringsinformasjonskapsler',
      marketingDescription: 'Tilpasser annonseinnhold.',
      duration: 'Samtykket ditt er gyldig i 12 måneder.',
      modalDescription: 'Velg hvilke kategorier av informasjonskapsler du vil godta.',
      required: '(påkrevd)',
    },
  },
  fi: {
    navbar: {
      home: 'Tatik.space-etusivu',
      logo: 'Tatik-logo',
      menu: 'Valikko',
      openMenu: 'Avaa navigointivalikko',
      closeMenu: 'Sulje navigointivalikko',
      developerMarketplace: 'Kehittäjien markkinapaikka',
    },
    footer: {
      navigation: 'Alatunnisteen navigointi',
      schools: 'Kouluohjelma',
      copyright: 'Kaikki oikeudet pidätetään',
      authorCredit: 'Tatikin kehittämä; Tatik on tekijän yksilöivä salanimi siviililain 9 artiklan mukaisesti.',
    },
    cookies: {
      title: 'Evästeiden käyttö',
      intro: 'Tutustu',
      and: 'ja',
      necessary: 'Välttämättömät evästeet',
      necessaryDescription: 'Välttämättömiä sivuston toiminnalle (todennus, tietoturva).',
      functional: 'Toiminnalliset evästeet',
      functionalDescription: 'Muistavat asetuksesi (kieli, teema).',
      analytics: 'Analytiikkaevästeet',
      analyticsDescription: 'Auttaa meitä ymmärtämään, miten käytät sivustoa.',
      marketing: 'Markkinointievästeet',
      marketingDescription: 'Mukauttavat mainossisältöä.',
      duration: 'Suostumuksesi on voimassa 12 kuukautta.',
      modalDescription: 'Valitse, mitkä evästeluokat haluat hyväksyä.',
      required: '(pakollinen)',
    },
  },
  uk: {
    navbar: {
      home: 'Головна сторінка Tatik.space',
      logo: 'Логотип Tatik',
      menu: 'Меню',
      openMenu: 'Відкрити меню навігації',
      closeMenu: 'Закрити меню навігації',
      developerMarketplace: 'Маркетплейс для розробників',
    },
    footer: {
      navigation: 'Навігація в нижній частині сторінки',
      schools: 'Програма для шкіл',
      copyright: 'Усі права захищено',
      authorCredit: 'Розроблено Tatik — ідентифікаційний псевдонім автора згідно зі ст. 9 Цивільного кодексу.',
    },
    cookies: {
      title: 'Використання файлів cookie',
      intro: 'Перегляньте нашу',
      and: 'і',
      necessary: 'Обов’язкові файли cookie',
      necessaryDescription: 'Необхідні для роботи сайту (автентифікація, безпека).',
      functional: 'Функціональні файли cookie',
      functionalDescription: 'Запам’ятовують ваші налаштування (мова, тема).',
      analytics: 'Аналітичні файли cookie',
      analyticsDescription: 'Допомагають нам зрозуміти, як ви користуєтеся сайтом.',
      marketing: 'Маркетингові файли cookie',
      marketingDescription: 'Персоналізують рекламний вміст.',
      duration: 'Згода дійсна протягом 12 місяців.',
      modalDescription: 'Виберіть категорії файлів cookie, які бажаєте прийняти.',
      required: '(обов’язково)',
    },
  },
  cs: {
    navbar: {
      home: 'Domovská stránka Tatik.space',
      logo: 'Logo Tatik',
      menu: 'Nabídka',
      openMenu: 'Otevřít navigační nabídku',
      closeMenu: 'Zavřít navigační nabídku',
      developerMarketplace: 'Marketplace pro vývojáře',
    },
    footer: {
      navigation: 'Navigace v zápatí',
      schools: 'Školní program',
      copyright: 'Všechna práva vyhrazena',
      authorCredit: 'Vyvinul Tatik, identifikační pseudonym autora podle čl. 9 občanského zákoníku.',
    },
    cookies: {
      title: 'Používání cookies',
      intro: 'Projděte si naše zásady:',
      and: 'a',
      necessary: 'Nezbytné cookies',
      necessaryDescription: 'Nezbytné pro fungování webu (ověřování, zabezpečení).',
      functional: 'Funkční cookies',
      functionalDescription: 'Ukládají vaše preference (jazyk, motiv).',
      analytics: 'Analytické cookies',
      analyticsDescription: 'Pomáhají nám porozumět tomu, jak web používáte.',
      marketing: 'Marketingové cookies',
      marketingDescription: 'Přizpůsobují reklamní obsah.',
      duration: 'Váš souhlas platí 12 měsíců.',
      modalDescription: 'Vyberte kategorie cookies, které chcete přijmout.',
      required: '(povinné)',
    },
  },
} as const;

export type SiteSurfaceLanguage = keyof typeof siteSurfaceCopy;

export const profileBadgeCopy: Record<SiteSurfaceLanguage, {
  openMenu: string;
  closeMenu: string;
  profile: string;
  schools: string;
  myFiles: string;
  daysShort: string;
  microJobAlerts: string;
  signOut: string;
}> = {
  en: { openMenu: 'Open account menu', closeMenu: 'Close account menu', profile: 'Profile', schools: 'School program', myFiles: 'My Files', daysShort: 'd', microJobAlerts: 'Micro-Job Alerts', signOut: 'Sign Out' },
  it: { openMenu: 'Apri il menu account', closeMenu: 'Chiudi il menu account', profile: 'Profilo', schools: 'Programma scuole', myFiles: 'I miei file', daysShort: 'g', microJobAlerts: 'Avvisi micro-lavori', signOut: 'Esci' },
  es: { openMenu: 'Abrir menú de cuenta', closeMenu: 'Cerrar menú de cuenta', profile: 'Perfil', schools: 'Programa para escuelas', myFiles: 'Mis archivos', daysShort: 'd', microJobAlerts: 'Alertas de microtrabajos', signOut: 'Cerrar sesión' },
  fr: { openMenu: 'Ouvrir le menu du compte', closeMenu: 'Fermer le menu du compte', profile: 'Profil', schools: 'Programme scolaire', myFiles: 'Mes fichiers', daysShort: 'j', microJobAlerts: 'Alertes de micro-missions', signOut: 'Se déconnecter' },
  de: { openMenu: 'Kontomenü öffnen', closeMenu: 'Kontomenü schließen', profile: 'Profil', schools: 'Schulprogramm', myFiles: 'Meine Dateien', daysShort: 'T', microJobAlerts: 'Microjob-Benachrichtigungen', signOut: 'Abmelden' },
  pt: { openMenu: 'Abrir menu da conta', closeMenu: 'Fechar menu da conta', profile: 'Perfil', schools: 'Programa escolar', myFiles: 'Meus ficheiros', daysShort: 'd', microJobAlerts: 'Alertas de microtarefas', signOut: 'Terminar sessão' },
  ru: { openMenu: 'Открыть меню аккаунта', closeMenu: 'Закрыть меню аккаунта', profile: 'Профиль', schools: 'Программа для школ', myFiles: 'Мои файлы', daysShort: 'дн.', microJobAlerts: 'Уведомления о микрозаданиях', signOut: 'Выйти' },
  zh: { openMenu: '打开账户菜单', closeMenu: '关闭账户菜单', profile: '个人资料', schools: '学校计划', myFiles: '我的文件', daysShort: '天', microJobAlerts: '微任务提醒', signOut: '退出登录' },
  ja: { openMenu: 'アカウントメニューを開く', closeMenu: 'アカウントメニューを閉じる', profile: 'プロフィール', schools: '学校向けプログラム', myFiles: 'マイファイル', daysShort: '日', microJobAlerts: 'マイクロジョブ通知', signOut: 'ログアウト' },
  ko: { openMenu: '계정 메뉴 열기', closeMenu: '계정 메뉴 닫기', profile: '프로필', schools: '학교 프로그램', myFiles: '내 파일', daysShort: '일', microJobAlerts: '마이크로 작업 알림', signOut: '로그아웃' },
  ar: { openMenu: 'فتح قائمة الحساب', closeMenu: 'إغلاق قائمة الحساب', profile: 'الملف الشخصي', schools: 'برنامج المدارس', myFiles: 'ملفاتي', daysShort: 'ي', microJobAlerts: 'تنبيهات المهام الصغيرة', signOut: 'تسجيل الخروج' },
  hi: { openMenu: 'खाता मेन्यू खोलें', closeMenu: 'खाता मेन्यू बंद करें', profile: 'प्रोफ़ाइल', schools: 'स्कूल कार्यक्रम', myFiles: 'मेरी फ़ाइलें', daysShort: 'दि', microJobAlerts: 'माइक्रो-जॉब अलर्ट', signOut: 'साइन आउट' },
  pl: { openMenu: 'Otwórz menu konta', closeMenu: 'Zamknij menu konta', profile: 'Profil', schools: 'Program dla szkół', myFiles: 'Moje pliki', daysShort: 'd', microJobAlerts: 'Powiadomienia o mikro-zleceniach', signOut: 'Wyloguj się' },
  nl: { openMenu: 'Accountmenu openen', closeMenu: 'Accountmenu sluiten', profile: 'Profiel', schools: 'Schoolprogramma', myFiles: 'Mijn bestanden', daysShort: 'd', microJobAlerts: 'Meldingen over micro-opdrachten', signOut: 'Afmelden' },
  tr: { openMenu: 'Hesap menüsünü aç', closeMenu: 'Hesap menüsünü kapat', profile: 'Profil', schools: 'Okul programı', myFiles: 'Dosyalarım', daysShort: 'g', microJobAlerts: 'Mikro iş bildirimleri', signOut: 'Oturumu kapat' },
  sv: { openMenu: 'Öppna kontomenyn', closeMenu: 'Stäng kontomenyn', profile: 'Profil', schools: 'Skolprogram', myFiles: 'Mina filer', daysShort: 'd', microJobAlerts: 'Aviseringar om mikrouppdrag', signOut: 'Logga ut' },
  da: { openMenu: 'Åbn kontomenuen', closeMenu: 'Luk kontomenuen', profile: 'Profil', schools: 'Skoleprogram', myFiles: 'Mine filer', daysShort: 'd', microJobAlerts: 'Meddelelser om mikroopgaver', signOut: 'Log ud' },
  no: { openMenu: 'Åpne kontomenyen', closeMenu: 'Lukk kontomenyen', profile: 'Profil', schools: 'Skoleprogram', myFiles: 'Mine filer', daysShort: 'd', microJobAlerts: 'Varsler om mikrojobber', signOut: 'Logg av' },
  fi: { openMenu: 'Avaa tilivalikko', closeMenu: 'Sulje tilivalikko', profile: 'Profiili', schools: 'Kouluohjelma', myFiles: 'Omat tiedostot', daysShort: 'pv', microJobAlerts: 'Mikrotehtävien ilmoitukset', signOut: 'Kirjaudu ulos' },
  uk: { openMenu: 'Відкрити меню облікового запису', closeMenu: 'Закрити меню облікового запису', profile: 'Профіль', schools: 'Програма для шкіл', myFiles: 'Мої файли', daysShort: 'дн.', microJobAlerts: 'Сповіщення про мікрозавдання', signOut: 'Вийти' },
  cs: { openMenu: 'Otevřít nabídku účtu', closeMenu: 'Zavřít nabídku účtu', profile: 'Profil', schools: 'Školní program', myFiles: 'Moje soubory', daysShort: 'd', microJobAlerts: 'Upozornění na mikrozakázky', signOut: 'Odhlásit se' },
};
