import { translations } from "@/lib/i18n";

type SiteShellCopy = {
  betaTitle: string;
  betaMessage: string;
  reportIssue: string;
  notFoundTitle: string;
  notFoundMessage: string;
  goHome: string;
};

export const siteShellCopy: Record<keyof typeof translations, SiteShellCopy> = {
  en: {
    betaTitle: "Testing and updates in progress",
    betaMessage: "Tatik.space Pro is under active development. Some features are still being tested, including version history and custom themes. Your feedback helps us improve.",
    reportIssue: "Report an issue",
    notFoundTitle: "Page not found",
    notFoundMessage: "Sorry, the page you are looking for does not exist. It may have been moved or deleted.",
    goHome: "Go home",
  },
  it: {
    betaTitle: "Fase di test e aggiornamento",
    betaMessage: "Tatik.space Pro è in fase di sviluppo attivo. Alcune funzionalità sono ancora in test, tra cui la cronologia delle versioni e i temi personalizzati. I tuoi feedback ci aiutano a migliorare.",
    reportIssue: "Segnala un problema",
    notFoundTitle: "Pagina non trovata",
    notFoundMessage: "La pagina che cerchi non esiste. Potrebbe essere stata spostata o eliminata.",
    goHome: "Torna alla home",
  },
  es: {
    betaTitle: "Pruebas y actualizaciones en curso",
    betaMessage: "Tatik.space Pro está en desarrollo activo. Algunas funciones todavía se están probando, como el historial de versiones y los temas personalizados. Tus comentarios nos ayudan a mejorar.",
    reportIssue: "Informar de un problema",
    notFoundTitle: "Página no encontrada",
    notFoundMessage: "La página que buscas no existe. Es posible que se haya movido o eliminado.",
    goHome: "Ir al inicio",
  },
  fr: {
    betaTitle: "Tests et mises à jour en cours",
    betaMessage: "Tatik.space Pro est en développement actif. Certaines fonctionnalités, comme l’historique des versions et les thèmes personnalisés, sont encore en test. Vos commentaires nous aident à améliorer le service.",
    reportIssue: "Signaler un problème",
    notFoundTitle: "Page introuvable",
    notFoundMessage: "La page que vous recherchez n’existe pas. Elle a peut-être été déplacée ou supprimée.",
    goHome: "Retour à l’accueil",
  },
  de: {
    betaTitle: "Tests und Aktualisierungen laufen",
    betaMessage: "Tatik.space Pro wird aktiv weiterentwickelt. Einige Funktionen, darunter Versionsverlauf und benutzerdefinierte Designs, werden noch getestet. Dein Feedback hilft uns, den Dienst zu verbessern.",
    reportIssue: "Problem melden",
    notFoundTitle: "Seite nicht gefunden",
    notFoundMessage: "Die gesuchte Seite existiert nicht. Sie wurde möglicherweise verschoben oder gelöscht.",
    goHome: "Zur Startseite",
  },
  pt: {
    betaTitle: "Testes e atualizações em andamento",
    betaMessage: "O Tatik.space Pro está em desenvolvimento ativo. Alguns recursos ainda estão em teste, incluindo o histórico de versões e os temas personalizados. Seu feedback nos ajuda a melhorar.",
    reportIssue: "Comunicar um problema",
    notFoundTitle: "Página não encontrada",
    notFoundMessage: "A página que você procura não existe. Ela pode ter sido movida ou excluída.",
    goHome: "Ir para a página inicial",
  },
  ru: {
    betaTitle: "Идут тестирование и обновление",
    betaMessage: "Tatik.space Pro активно разрабатывается. Некоторые функции, включая историю версий и пользовательские темы, ещё тестируются. Ваши отзывы помогают нам улучшать сервис.",
    reportIssue: "Сообщить о проблеме",
    notFoundTitle: "Страница не найдена",
    notFoundMessage: "Страница, которую вы ищете, не существует. Возможно, её переместили или удалили.",
    goHome: "На главную",
  },
  zh: {
    betaTitle: "正在测试和更新",
    betaMessage: "Tatik.space Pro 正在积极开发中。部分功能仍在测试，包括版本历史记录和自定义主题。您的反馈有助于我们持续改进。",
    reportIssue: "报告问题",
    notFoundTitle: "未找到页面",
    notFoundMessage: "抱歉，您要查找的页面不存在，可能已被移动或删除。",
    goHome: "返回首页",
  },
  ja: {
    betaTitle: "テストと更新を実施中",
    betaMessage: "Tatik.space Pro は現在も開発中です。バージョン履歴やカスタムテーマなど、一部の機能はまだテスト段階です。フィードバックをお寄せいただくことで改善につながります。",
    reportIssue: "問題を報告",
    notFoundTitle: "ページが見つかりません",
    notFoundMessage: "お探しのページは存在しないか、移動または削除された可能性があります。",
    goHome: "ホームへ戻る",
  },
  ko: {
    betaTitle: "테스트 및 업데이트 진행 중",
    betaMessage: "Tatik.space Pro는 활발히 개발 중입니다. 버전 기록과 사용자 지정 테마를 포함한 일부 기능은 아직 테스트 중입니다. 의견을 보내 주시면 서비스 개선에 도움이 됩니다.",
    reportIssue: "문제 신고",
    notFoundTitle: "페이지를 찾을 수 없습니다",
    notFoundMessage: "찾으시는 페이지가 존재하지 않습니다. 이동되었거나 삭제되었을 수 있습니다.",
    goHome: "홈으로 이동",
  },
  ar: {
    betaTitle: "الاختبار والتحديثات مستمرة",
    betaMessage: "يجري تطوير Tatik.space Pro بنشاط. لا تزال بعض الميزات، مثل سجل الإصدارات والسمات المخصصة، قيد الاختبار. تساعدنا ملاحظاتك على التحسين.",
    reportIssue: "الإبلاغ عن مشكلة",
    notFoundTitle: "الصفحة غير موجودة",
    notFoundMessage: "عذرًا، الصفحة التي تبحث عنها غير موجودة. ربما تم نقلها أو حذفها.",
    goHome: "العودة إلى الصفحة الرئيسية",
  },
  hi: {
    betaTitle: "परीक्षण और अपडेट जारी हैं",
    betaMessage: "Tatik.space Pro का सक्रिय विकास जारी है। संस्करण इतिहास और कस्टम थीम सहित कुछ सुविधाएँ अभी परीक्षण में हैं। आपकी प्रतिक्रिया हमें सुधार करने में मदद करती है।",
    reportIssue: "समस्या की रिपोर्ट करें",
    notFoundTitle: "पृष्ठ नहीं मिला",
    notFoundMessage: "क्षमा करें, आप जिस पृष्ठ को ढूँढ़ रहे हैं वह मौजूद नहीं है। हो सकता है उसे स्थानांतरित या हटा दिया गया हो।",
    goHome: "होम पर जाएँ",
  },
  pl: {
    betaTitle: "Trwają testy i aktualizacje",
    betaMessage: "Tatik.space Pro jest aktywnie rozwijany. Niektóre funkcje, w tym historia wersji i własne motywy, są nadal testowane. Twoja opinia pomaga nam ulepszać usługę.",
    reportIssue: "Zgłoś problem",
    notFoundTitle: "Nie znaleziono strony",
    notFoundMessage: "Szukana strona nie istnieje. Mogła zostać przeniesiona lub usunięta.",
    goHome: "Przejdź do strony głównej",
  },
  nl: {
    betaTitle: "Tests en updates zijn bezig",
    betaMessage: "Tatik.space Pro wordt actief ontwikkeld. Sommige functies, waaronder versiegeschiedenis en aangepaste thema’s, worden nog getest. Met je feedback kunnen we de service verbeteren.",
    reportIssue: "Een probleem melden",
    notFoundTitle: "Pagina niet gevonden",
    notFoundMessage: "De pagina die je zoekt bestaat niet. Deze is mogelijk verplaatst of verwijderd.",
    goHome: "Naar de startpagina",
  },
  tr: {
    betaTitle: "Test ve güncellemeler sürüyor",
    betaMessage: "Tatik.space Pro aktif olarak geliştirilmektedir. Sürüm geçmişi ve özel temalar dâhil bazı özellikler hâlâ test aşamasındadır. Geri bildiriminiz hizmeti iyileştirmemize yardımcı olur.",
    reportIssue: "Sorun bildir",
    notFoundTitle: "Sayfa bulunamadı",
    notFoundMessage: "Aradığınız sayfa mevcut değil. Taşınmış veya silinmiş olabilir.",
    goHome: "Ana sayfaya git",
  },
  sv: {
    betaTitle: "Testning och uppdateringar pågår",
    betaMessage: "Tatik.space Pro utvecklas aktivt. Vissa funktioner, bland annat versionshistorik och anpassade teman, testas fortfarande. Din feedback hjälper oss att förbättra tjänsten.",
    reportIssue: "Rapportera ett problem",
    notFoundTitle: "Sidan kunde inte hittas",
    notFoundMessage: "Sidan du söker finns inte. Den kan ha flyttats eller tagits bort.",
    goHome: "Gå till startsidan",
  },
  da: {
    betaTitle: "Test og opdateringer er i gang",
    betaMessage: "Tatik.space Pro er under aktiv udvikling. Nogle funktioner, herunder versionshistorik og brugerdefinerede temaer, testes stadig. Din feedback hjælper os med at forbedre tjenesten.",
    reportIssue: "Rapportér et problem",
    notFoundTitle: "Siden blev ikke fundet",
    notFoundMessage: "Siden, du leder efter, findes ikke. Den kan være flyttet eller slettet.",
    goHome: "Gå til startsiden",
  },
  no: {
    betaTitle: "Testing og oppdateringer pågår",
    betaMessage: "Tatik.space Pro er under aktiv utvikling. Noen funksjoner, blant annet versjonshistorikk og egendefinerte temaer, testes fortsatt. Tilbakemeldinger hjelper oss med å forbedre tjenesten.",
    reportIssue: "Rapporter et problem",
    notFoundTitle: "Siden ble ikke funnet",
    notFoundMessage: "Siden du leter etter finnes ikke. Den kan ha blitt flyttet eller slettet.",
    goHome: "Gå til startsiden",
  },
  fi: {
    betaTitle: "Testaus ja päivitykset ovat käynnissä",
    betaMessage: "Tatik.space Prota kehitetään aktiivisesti. Osa ominaisuuksista, kuten versiohistoria ja mukautetut teemat, on vielä testauksessa. Palautteesi auttaa meitä parantamaan palvelua.",
    reportIssue: "Ilmoita ongelmasta",
    notFoundTitle: "Sivua ei löytynyt",
    notFoundMessage: "Etsimääsi sivua ei ole olemassa. Se on voitu siirtää tai poistaa.",
    goHome: "Siirry etusivulle",
  },
  uk: {
    betaTitle: "Триває тестування та оновлення",
    betaMessage: "Tatik.space Pro активно розробляється. Деякі функції, зокрема історія версій і власні теми, ще тестуються. Ваші відгуки допомагають нам покращувати сервіс.",
    reportIssue: "Повідомити про проблему",
    notFoundTitle: "Сторінку не знайдено",
    notFoundMessage: "Сторінки, яку ви шукаєте, не існує. Її могли перемістити або видалити.",
    goHome: "На головну",
  },
  cs: {
    betaTitle: "Probíhá testování a aktualizace",
    betaMessage: "Tatik.space Pro se aktivně vyvíjí. Některé funkce, například historie verzí a vlastní motivy, se stále testují. Vaše zpětná vazba nám pomáhá službu zlepšovat.",
    reportIssue: "Nahlásit problém",
    notFoundTitle: "Stránka nebyla nalezena",
    notFoundMessage: "Hledaná stránka neexistuje. Mohla být přesunuta nebo odstraněna.",
    goHome: "Přejít na úvodní stránku",
  },
};
