type SupportPageCopy = {
  title: string;
  home: string;
  heading: string;
  intro: string;
  documentation: string;
  documentationDescription: string;
  documentationLink: string;
  guides: string;
  guidesDescription: string;
  guidesLink: string;
  forum: string;
  forumDescription: string;
  contact: string;
  contactDescription: string;
  contactLink: string;
  faq: string;
  faqs: [string, string][];
  seoTitle: string;
  seoDescription: string;
};

export const supportPageCopy: Record<string, SupportPageCopy> = {
  it: {
    title: "Supporto",
    home: "Torna alla Home",
    heading: "Centro assistenza",
    intro: "Trova risposte alle domande più comuni o contatta il nostro team.",
    documentation: "Documentazione",
    documentationDescription: "Consulta le guide sulle funzioni disponibili di Tatik.space Pro.",
    documentationLink: "Vai alla documentazione",
    guides: "Guide pratiche",
    guidesDescription: "Segui le guide per editor, backup e pubblicazione tramite provider esterni.",
    guidesLink: "Apri le guide",
    forum: "Forum della community",
    forumDescription: "Il forum non è ancora disponibile. Ti aggiorneremo quando sarà possibile confrontarsi con altri utenti.",
    contact: "Contatto diretto",
    contactDescription: "Scrivi al team per ricevere assistenza.",
    contactLink: "Contatta il supporto",
    faq: "Domande frequenti",
    faqs: [
      ["Come accedo al mio account?", "Inserisci l’indirizzo email nella pagina di accesso. Se l’indirizzo è registrato, riceverai un link monouso valido 10 minuti. Non serve una password."],
      ["Come posso consultare i piani?", "Apri la pagina Prezzi per consultare i piani e le relative condizioni. Gli acquisti e gli abbonamenti si avviano dal checkout disponibile sul sito."],
      ["Come posso esportare i miei progetti?", "Puoi scaricare i file dall’editor o usare Backup per creare uno snapshot del progetto. Non è disponibile l’esportazione del progetto come pacchetto pronto per il deploy."],
      ["Come funziona la cronologia delle versioni?", "La cronologia disponibile nell’editor riguarda le versioni della sessione corrente. È temporanea: non sostituisce i backup e non è una cronologia cloud permanente."],
    ],
    seoTitle: "Centro assistenza | Tatik.space",
    seoDescription: "Consulta risposte sull’accesso con link email, editor, backup e funzionalità disponibili su Tatik.space Pro.",
  },
  en: {
    title: "Support",
    home: "Back to Home",
    heading: "Help center",
    intro: "Find answers to common questions or contact our team.",
    documentation: "Documentation",
    documentationDescription: "Read guides to the features currently available in Tatik.space Pro.",
    documentationLink: "View documentation",
    guides: "Practical guides",
    guidesDescription: "Follow guides for the editor, backups, and publishing through external providers.",
    guidesLink: "Open guides",
    forum: "Community forum",
    forumDescription: "The forum is not available yet. We’ll share an update when community discussions are ready.",
    contact: "Contact the team",
    contactDescription: "Get in touch with our team for help.",
    contactLink: "Contact support",
    faq: "Frequently asked questions",
    faqs: [
      ["How do I access my account?", "Enter your email address on the login page. If it is registered, you’ll receive a single-use link that is valid for 10 minutes. No password is needed."],
      ["Where can I compare plans?", "Visit the Pricing page to review plans and their terms. Purchases and subscriptions are started through the checkout available on the site."],
      ["How can I export my projects?", "Download files from the editor or use Backup to create a project snapshot. Exporting a project as a deployment-ready package is not available."],
      ["How does version history work?", "The editor’s available history covers versions from the current session. It is temporary; it does not replace backups or provide permanent cloud history."],
    ],
    seoTitle: "Help center | Tatik.space",
    seoDescription: "Find answers about email-link sign-in, the editor, backups, and features available in Tatik.space Pro.",
  },
  es: {
    title: "Soporte",
    home: "Volver al inicio",
    heading: "Centro de ayuda",
    intro: "Encuentra respuestas a las preguntas frecuentes o contacta con nuestro equipo.",
    documentation: "Documentación",
    documentationDescription: "Consulta las guías sobre las funciones disponibles actualmente en Tatik.space Pro.",
    documentationLink: "Ver documentación",
    guides: "Guías prácticas",
    guidesDescription: "Sigue las guías del editor, las copias de seguridad y la publicación mediante proveedores externos.",
    guidesLink: "Abrir las guías",
    forum: "Foro de la comunidad",
    forumDescription: "El foro aún no está disponible. Te avisaremos cuando se puedan compartir ideas con otros usuarios.",
    contact: "Contacto directo",
    contactDescription: "Escribe a nuestro equipo para recibir ayuda.",
    contactLink: "Contactar con soporte",
    faq: "Preguntas frecuentes",
    faqs: [
      ["¿Cómo accedo a mi cuenta?", "Introduce tu correo en la página de acceso. Si está registrado, recibirás un enlace de un solo uso válido durante 10 minutos. No necesitas contraseña."],
      ["¿Dónde puedo comparar los planes?", "Visita la página de Precios para consultar los planes y sus condiciones. Las compras y suscripciones se inician desde el checkout del sitio."],
      ["¿Cómo puedo exportar mis proyectos?", "Descarga archivos desde el editor o usa Backup para crear una instantánea del proyecto. No está disponible la exportación como paquete listo para publicar."],
      ["¿Cómo funciona el historial de versiones?", "El historial disponible en el editor abarca las versiones de la sesión actual. Es temporal; no sustituye las copias de seguridad ni ofrece un historial permanente en la nube."],
    ],
    seoTitle: "Centro de ayuda | Tatik.space",
    seoDescription: "Resuelve dudas sobre el acceso mediante enlace de correo, el editor, las copias de seguridad y las funciones de Tatik.space Pro.",
  },
  fr: {
    title: "Assistance",
    home: "Retour à l’accueil",
    heading: "Centre d’aide",
    intro: "Trouvez des réponses aux questions fréquentes ou contactez notre équipe.",
    documentation: "Documentation",
    documentationDescription: "Consultez les guides sur les fonctionnalités actuellement disponibles dans Tatik.space Pro.",
    documentationLink: "Voir la documentation",
    guides: "Guides pratiques",
    guidesDescription: "Suivez les guides sur l’éditeur, les sauvegardes et la publication via des fournisseurs externes.",
    guidesLink: "Ouvrir les guides",
    forum: "Forum communautaire",
    forumDescription: "Le forum n’est pas encore disponible. Nous vous informerons dès que les échanges entre utilisateurs seront ouverts.",
    contact: "Contact direct",
    contactDescription: "Écrivez à notre équipe pour obtenir de l’aide.",
    contactLink: "Contacter l’assistance",
    faq: "Questions fréquentes",
    faqs: [
      ["Comment accéder à mon compte ?", "Saisissez votre adresse e-mail sur la page de connexion. Si elle est enregistrée, vous recevrez un lien à usage unique valable 10 minutes. Aucun mot de passe n’est nécessaire."],
      ["Où comparer les offres ?", "Consultez la page Tarifs pour découvrir les offres et leurs conditions. Les achats et abonnements démarrent depuis le paiement en ligne du site."],
      ["Comment exporter mes projets ?", "Téléchargez les fichiers depuis l’éditeur ou utilisez Backup pour créer un instantané du projet. L’export du projet sous forme de paquet prêt à déployer n’est pas disponible."],
      ["Comment fonctionne l’historique des versions ?", "L’historique disponible dans l’éditeur concerne les versions de la session en cours. Il est temporaire et ne remplace pas les sauvegardes ni un historique cloud permanent."],
    ],
    seoTitle: "Centre d’aide | Tatik.space",
    seoDescription: "Réponses sur la connexion par lien e-mail, l’éditeur, les sauvegardes et les fonctionnalités de Tatik.space Pro.",
  },
  de: {
    title: "Support",
    home: "Zurück zur Startseite",
    heading: "Hilfe-Center",
    intro: "Finde Antworten auf häufige Fragen oder kontaktiere unser Team.",
    documentation: "Dokumentation",
    documentationDescription: "Lies die Anleitungen zu den aktuell verfügbaren Funktionen von Tatik.space Pro.",
    documentationLink: "Dokumentation ansehen",
    guides: "Praktische Anleitungen",
    guidesDescription: "Anleitungen zu Editor, Backups und Veröffentlichung über externe Anbieter.",
    guidesLink: "Anleitungen öffnen",
    forum: "Community-Forum",
    forumDescription: "Das Forum ist noch nicht verfügbar. Wir informieren dich, sobald der Austausch mit anderen Nutzern möglich ist.",
    contact: "Direkter Kontakt",
    contactDescription: "Wende dich an unser Team, wenn du Hilfe benötigst.",
    contactLink: "Support kontaktieren",
    faq: "Häufig gestellte Fragen",
    faqs: [
      ["Wie melde ich mich bei meinem Konto an?", "Gib auf der Anmeldeseite deine E-Mail-Adresse ein. Ist sie registriert, erhältst du einen einmalig verwendbaren Link, der 10 Minuten gültig ist. Ein Passwort ist nicht erforderlich."],
      ["Wo kann ich die Tarife vergleichen?", "Auf der Preisseite findest du die Tarife und Bedingungen. Käufe und Abonnements startest du über den Checkout auf der Website."],
      ["Wie kann ich meine Projekte exportieren?", "Lade Dateien im Editor herunter oder erstelle mit Backup einen Projektsnapshot. Der Export als bereitstellungspaket ist nicht verfügbar."],
      ["Wie funktioniert der Versionsverlauf?", "Der im Editor verfügbare Verlauf umfasst Versionen der aktuellen Sitzung. Er ist temporär und ersetzt weder Backups noch einen dauerhaften Cloud-Verlauf."],
    ],
    seoTitle: "Hilfe-Center | Tatik.space",
    seoDescription: "Antworten zur Anmeldung per E-Mail-Link, zum Editor, zu Backups und zu den Funktionen von Tatik.space Pro.",
  },
  pt: {
    title: "Suporte",
    home: "Voltar ao início",
    heading: "Centro de ajuda",
    intro: "Encontre respostas às perguntas frequentes ou fale com a nossa equipa.",
    documentation: "Documentação",
    documentationDescription: "Consulte os guias sobre as funcionalidades atualmente disponíveis no Tatik.space Pro.",
    documentationLink: "Ver documentação",
    guides: "Guias práticos",
    guidesDescription: "Siga os guias do editor, das cópias de segurança e da publicação por fornecedores externos.",
    guidesLink: "Abrir os guias",
    forum: "Fórum da comunidade",
    forumDescription: "O fórum ainda não está disponível. Avisaremos quando for possível trocar ideias com outros utilizadores.",
    contact: "Contacto direto",
    contactDescription: "Fale com a nossa equipa para obter ajuda.",
    contactLink: "Contactar o suporte",
    faq: "Perguntas frequentes",
    faqs: [
      ["Como acedo à minha conta?", "Introduza o seu email na página de acesso. Se estiver registado, receberá uma ligação de utilização única válida por 10 minutos. Não precisa de palavra-passe."],
      ["Onde posso comparar os planos?", "Consulte a página de Preços para ver os planos e as respetivas condições. As compras e subscrições são iniciadas no checkout do site."],
      ["Como posso exportar os meus projetos?", "Descarregue ficheiros no editor ou use Backup para criar uma cópia instantânea do projeto. Não é possível exportar o projeto como um pacote pronto a publicar."],
      ["Como funciona o histórico de versões?", "O histórico disponível no editor inclui versões da sessão atual. É temporário e não substitui as cópias de segurança nem um histórico permanente na nuvem."],
    ],
    seoTitle: "Centro de ajuda | Tatik.space",
    seoDescription: "Encontre respostas sobre acesso por ligação de email, editor, cópias de segurança e funcionalidades do Tatik.space Pro.",
  },
  ru: {
    title: "Поддержка",
    home: "На главную",
    heading: "Центр поддержки",
    intro: "Найдите ответы на частые вопросы или свяжитесь с нашей командой.",
    documentation: "Документация",
    documentationDescription: "Читайте руководства по функциям, доступным в Tatik.space Pro.",
    documentationLink: "Открыть документацию",
    guides: "Практические руководства",
    guidesDescription: "Руководства по редактору, резервному копированию и публикации через внешних провайдеров.",
    guidesLink: "Открыть руководства",
    forum: "Форум сообщества",
    forumDescription: "Форум пока недоступен. Мы сообщим, когда пользователи смогут общаться друг с другом.",
    contact: "Связаться с командой",
    contactDescription: "Напишите нашей команде, если вам нужна помощь.",
    contactLink: "Связаться с поддержкой",
    faq: "Частые вопросы",
    faqs: [
      ["Как войти в аккаунт?", "Введите адрес электронной почты на странице входа. Если адрес зарегистрирован, вы получите одноразовую ссылку сроком действия 10 минут. Пароль не требуется."],
      ["Где можно сравнить тарифы?", "На странице цен можно посмотреть тарифы и условия. Покупка и оформление подписки начинаются через checkout на сайте."],
      ["Как экспортировать проекты?", "Скачайте файлы из редактора или создайте снимок проекта с помощью Backup. Экспорт проекта в виде готового к развёртыванию пакета недоступен."],
      ["Как работает история версий?", "Доступная в редакторе история охватывает версии текущего сеанса. Она временная и не заменяет резервные копии или постоянную облачную историю."],
    ],
    seoTitle: "Центр поддержки | Tatik.space",
    seoDescription: "Ответы о входе по ссылке из письма, редакторе, резервных копиях и возможностях Tatik.space Pro.",
  },
  zh: {
    title: "支持",
    home: "返回首页",
    heading: "帮助中心",
    intro: "查找常见问题的答案，或联系支持团队。",
    documentation: "文档",
    documentationDescription: "查看 Tatik.space Pro 当前可用功能的指南。",
    documentationLink: "查看文档",
    guides: "实用指南",
    guidesDescription: "了解编辑器、备份以及通过外部服务商发布项目的操作指南。",
    guidesLink: "打开指南",
    forum: "社区论坛",
    forumDescription: "论坛尚未开放。开放用户交流后，我们会及时告知。",
    contact: "直接联系",
    contactDescription: "如需帮助，请联系支持团队。",
    contactLink: "联系支持",
    faq: "常见问题",
    faqs: [
      ["如何登录我的账户？", "在登录页面输入邮箱。如果邮箱已注册，你会收到一条有效期为 10 分钟的一次性链接，无需密码。"],
      ["在哪里可以比较方案？", "请访问价格页面查看方案和相关条款。可通过网站提供的结账流程开始购买或订阅。"],
      ["如何导出项目？", "可以在编辑器中下载文件，或使用 Backup 创建项目快照。目前不支持导出为可直接部署的项目包。"],
      ["版本历史如何工作？", "编辑器中的历史记录仅包含当前会话的版本，属于临时记录；它不能替代备份，也不提供永久云端历史记录。"],
    ],
    seoTitle: "帮助中心 | Tatik.space",
    seoDescription: "了解邮箱链接登录、编辑器、备份以及 Tatik.space Pro 当前提供的功能。",
  },
  ja: {
    title: "サポート",
    home: "ホームに戻る",
    heading: "ヘルプセンター",
    intro: "よくある質問を確認するか、サポートチームにお問い合わせください。",
    documentation: "ドキュメント",
    documentationDescription: "Tatik.space Pro で現在利用できる機能のガイドを確認できます。",
    documentationLink: "ドキュメントを見る",
    guides: "実践ガイド",
    guidesDescription: "エディター、バックアップ、外部プロバイダーを使った公開方法を確認できます。",
    guidesLink: "ガイドを開く",
    forum: "コミュニティフォーラム",
    forumDescription: "フォーラムはまだ利用できません。ユーザー同士の交流が可能になった際にお知らせします。",
    contact: "直接問い合わせる",
    contactDescription: "サポートが必要な場合はチームにご連絡ください。",
    contactLink: "サポートに問い合わせる",
    faq: "よくある質問",
    faqs: [
      ["アカウントにログインするには？", "ログインページにメールアドレスを入力してください。登録済みの場合、10分間有効な1回限りのリンクが届きます。パスワードは不要です。"],
      ["プランはどこで比較できますか？", "料金ページでプランと条件をご確認ください。購入やサブスクリプションはサイト上のチェックアウトから開始できます。"],
      ["プロジェクトをエクスポートするには？", "エディターからファイルをダウンロードするか、Backup でプロジェクトのスナップショットを作成できます。デプロイ可能なパッケージとしての書き出しには対応していません。"],
      ["バージョン履歴の仕組みは？", "エディターの履歴には現在のセッション中に作成されたバージョンが表示されます。一時的な履歴であり、バックアップや永続的なクラウド履歴の代わりにはなりません。"],
    ],
    seoTitle: "ヘルプセンター | Tatik.space",
    seoDescription: "メールリンクでのログイン、エディター、バックアップ、Tatik.space Pro の機能についてご案内します。",
  },
  ko: {
    title: "지원",
    home: "홈으로 돌아가기",
    heading: "도움말 센터",
    intro: "자주 묻는 질문을 확인하거나 지원팀에 문의하세요.",
    documentation: "문서",
    documentationDescription: "Tatik.space Pro에서 현재 제공되는 기능에 대한 가이드를 확인하세요.",
    documentationLink: "문서 보기",
    guides: "실용 가이드",
    guidesDescription: "편집기, 백업, 외부 제공업체를 통한 게시 방법을 안내합니다.",
    guidesLink: "가이드 열기",
    forum: "커뮤니티 포럼",
    forumDescription: "포럼은 아직 제공되지 않습니다. 사용자 간 토론이 가능해지면 안내해 드리겠습니다.",
    contact: "직접 문의",
    contactDescription: "도움이 필요하면 지원팀에 문의하세요.",
    contactLink: "지원팀에 문의",
    faq: "자주 묻는 질문",
    faqs: [
      ["계정에 어떻게 로그인하나요?", "로그인 페이지에 이메일 주소를 입력하세요. 등록된 주소라면 10분 동안 유효한 일회용 링크를 받게 됩니다. 비밀번호는 필요하지 않습니다."],
      ["요금제는 어디서 비교할 수 있나요?", "가격 페이지에서 요금제와 조건을 확인하세요. 사이트의 결제 절차를 통해 구매 또는 구독을 시작할 수 있습니다."],
      ["프로젝트를 어떻게 내보내나요?", "편집기에서 파일을 다운로드하거나 Backup으로 프로젝트 스냅샷을 만들 수 있습니다. 배포 준비가 된 패키지로 내보내는 기능은 제공되지 않습니다."],
      ["버전 기록은 어떻게 작동하나요?", "편집기에서 확인할 수 있는 기록은 현재 세션의 버전에 한정됩니다. 임시 기록이며 백업이나 영구 클라우드 기록을 대체하지 않습니다."],
    ],
    seoTitle: "도움말 센터 | Tatik.space",
    seoDescription: "이메일 링크 로그인, 편집기, 백업 및 Tatik.space Pro의 제공 기능에 대한 답변을 확인하세요.",
  },
  ar: {
    title: "الدعم",
    home: "العودة إلى الرئيسية",
    heading: "مركز المساعدة",
    intro: "اعثر على إجابات للأسئلة الشائعة أو تواصل مع فريقنا.",
    documentation: "التوثيق",
    documentationDescription: "اطّلع على أدلة الميزات المتاحة حاليًا في Tatik.space Pro.",
    documentationLink: "عرض التوثيق",
    guides: "أدلة عملية",
    guidesDescription: "اتبع أدلة المحرر والنسخ الاحتياطي والنشر عبر مزوّدين خارجيين.",
    guidesLink: "فتح الأدلة",
    forum: "منتدى المجتمع",
    forumDescription: "المنتدى غير متاح بعد. سنخبرك عند إتاحة النقاش بين المستخدمين.",
    contact: "تواصل مباشر",
    contactDescription: "تواصل مع فريقنا للحصول على المساعدة.",
    contactLink: "التواصل مع الدعم",
    faq: "الأسئلة الشائعة",
    faqs: [
      ["كيف يمكنني الدخول إلى حسابي؟", "أدخل بريدك الإلكتروني في صفحة الدخول. إذا كان مسجلًا، ستتلقى رابطًا صالحًا لمرة واحدة لمدة 10 دقائق. لا تحتاج إلى كلمة مرور."],
      ["أين يمكنني مقارنة الخطط؟", "زر صفحة الأسعار للاطلاع على الخطط وشروطها. يمكنك بدء الشراء أو الاشتراك من خلال الدفع المتاح على الموقع."],
      ["كيف يمكنني تصدير مشاريعي؟", "نزّل الملفات من المحرر أو استخدم Backup لإنشاء لقطة للمشروع. لا يتوفر تصدير المشروع كحزمة جاهزة للنشر."],
      ["كيف يعمل سجل الإصدارات؟", "يعرض السجل المتاح في المحرر إصدارات الجلسة الحالية فقط. وهو مؤقت ولا يحل محل النسخ الاحتياطية أو سجل سحابي دائم."],
    ],
    seoTitle: "مركز المساعدة | Tatik.space",
    seoDescription: "إجابات حول تسجيل الدخول برابط البريد الإلكتروني والمحرر والنسخ الاحتياطي والميزات المتاحة في Tatik.space Pro.",
  },
  hi: {
    title: "सहायता",
    home: "होम पर वापस जाएँ",
    heading: "सहायता केंद्र",
    intro: "आम सवालों के जवाब पाएँ या हमारी टीम से संपर्क करें।",
    documentation: "दस्तावेज़",
    documentationDescription: "Tatik.space Pro में अभी उपलब्ध सुविधाओं के लिए गाइड देखें।",
    documentationLink: "दस्तावेज़ देखें",
    guides: "व्यावहारिक गाइड",
    guidesDescription: "एडिटर, बैकअप और बाहरी प्रदाताओं के ज़रिए प्रकाशित करने की गाइड पढ़ें।",
    guidesLink: "गाइड खोलें",
    forum: "कम्युनिटी फ़ोरम",
    forumDescription: "फ़ोरम अभी उपलब्ध नहीं है। उपयोगकर्ताओं के बीच चर्चा शुरू होने पर हम जानकारी देंगे।",
    contact: "सीधा संपर्क",
    contactDescription: "मदद के लिए हमारी टीम से संपर्क करें।",
    contactLink: "सहायता से संपर्क करें",
    faq: "अक्सर पूछे जाने वाले सवाल",
    faqs: [
      ["मैं अपने खाते में कैसे प्रवेश करूँ?", "लॉगिन पेज पर अपना ईमेल दर्ज करें। यदि यह पंजीकृत है, तो आपको 10 मिनट तक मान्य एक बार इस्तेमाल होने वाला लिंक मिलेगा। पासवर्ड की आवश्यकता नहीं है।"],
      ["मैं योजनाओं की तुलना कहाँ कर सकता हूँ?", "योजनाओं और उनकी शर्तों के लिए कीमत पेज देखें। साइट पर उपलब्ध checkout से खरीद या सदस्यता शुरू की जा सकती है।"],
      ["मैं अपने प्रोजेक्ट कैसे निर्यात करूँ?", "एडिटर से फ़ाइलें डाउनलोड करें या प्रोजेक्ट स्नैपशॉट बनाने के लिए Backup का उपयोग करें। सीधे तैनाती के लिए तैयार पैकेज के रूप में निर्यात उपलब्ध नहीं है।"],
      ["वर्ज़न हिस्ट्री कैसे काम करती है?", "एडिटर में उपलब्ध हिस्ट्री केवल मौजूदा सत्र के वर्ज़न दिखाती है। यह अस्थायी है और बैकअप या स्थायी क्लाउड हिस्ट्री का विकल्प नहीं है।"],
    ],
    seoTitle: "सहायता केंद्र | Tatik.space",
    seoDescription: "ईमेल लिंक से लॉगिन, एडिटर, बैकअप और Tatik.space Pro में उपलब्ध सुविधाओं के बारे में उत्तर पाएँ।",
  },
  pl: {
    title: "Pomoc",
    home: "Wróć na stronę główną",
    heading: "Centrum pomocy",
    intro: "Znajdź odpowiedzi na częste pytania lub skontaktuj się z naszym zespołem.",
    documentation: "Dokumentacja",
    documentationDescription: "Zapoznaj się z instrukcjami dotyczącymi funkcji dostępnych obecnie w Tatik.space Pro.",
    documentationLink: "Zobacz dokumentację",
    guides: "Praktyczne poradniki",
    guidesDescription: "Skorzystaj z poradników dotyczących edytora, kopii zapasowych i publikowania przez zewnętrznych dostawców.",
    guidesLink: "Otwórz poradniki",
    forum: "Forum społeczności",
    forumDescription: "Forum nie jest jeszcze dostępne. Poinformujemy, gdy użytkownicy będą mogli wymieniać się doświadczeniami.",
    contact: "Bezpośredni kontakt",
    contactDescription: "Skontaktuj się z naszym zespołem, aby uzyskać pomoc.",
    contactLink: "Skontaktuj się z pomocą",
    faq: "Często zadawane pytania",
    faqs: [
      ["Jak zalogować się na konto?", "Wpisz adres e-mail na stronie logowania. Jeśli jest zarejestrowany, otrzymasz jednorazowy link ważny przez 10 minut. Hasło nie jest potrzebne."],
      ["Gdzie mogę porównać plany?", "Odwiedź stronę Cennik, aby sprawdzić plany i ich warunki. Zakup lub subskrypcję rozpoczniesz przez checkout dostępny w serwisie."],
      ["Jak wyeksportować projekty?", "Pobierz pliki z edytora lub użyj Backup, aby utworzyć migawkę projektu. Eksport do pakietu gotowego do wdrożenia nie jest dostępny."],
      ["Jak działa historia wersji?", "Historia dostępna w edytorze obejmuje wersje z bieżącej sesji. Jest tymczasowa i nie zastępuje kopii zapasowych ani trwałej historii w chmurze."],
    ],
    seoTitle: "Centrum pomocy | Tatik.space",
    seoDescription: "Odpowiedzi na pytania o logowanie linkiem e-mail, edytor, kopie zapasowe i funkcje Tatik.space Pro.",
  },
  nl: {
    title: "Support",
    home: "Terug naar home",
    heading: "Helpcentrum",
    intro: "Vind antwoorden op veelgestelde vragen of neem contact op met ons team.",
    documentation: "Documentatie",
    documentationDescription: "Bekijk handleidingen voor functies die momenteel beschikbaar zijn in Tatik.space Pro.",
    documentationLink: "Documentatie bekijken",
    guides: "Praktische handleidingen",
    guidesDescription: "Volg handleidingen voor de editor, back-ups en publiceren via externe providers.",
    guidesLink: "Handleidingen openen",
    forum: "Communityforum",
    forumDescription: "Het forum is nog niet beschikbaar. We laten het weten zodra gebruikers met elkaar kunnen overleggen.",
    contact: "Direct contact",
    contactDescription: "Neem contact op met ons team als je hulp nodig hebt.",
    contactLink: "Contact opnemen met support",
    faq: "Veelgestelde vragen",
    faqs: [
      ["Hoe log ik in op mijn account?", "Vul je e-mailadres in op de inlogpagina. Als het is geregistreerd, ontvang je een eenmalige link die 10 minuten geldig is. Een wachtwoord is niet nodig."],
      ["Waar kan ik abonnementen vergelijken?", "Bekijk de pagina Prijzen voor abonnementen en voorwaarden. Je start een aankoop of abonnement via de checkout op de website."],
      ["Hoe exporteer ik mijn projecten?", "Download bestanden vanuit de editor of gebruik Backup om een projectmomentopname te maken. Exporteren als een kant-en-klaar implementatiepakket is niet beschikbaar."],
      ["Hoe werkt de versiegeschiedenis?", "De geschiedenis in de editor bevat versies uit de huidige sessie. Deze is tijdelijk en vervangt geen back-ups of permanente cloudgeschiedenis."],
    ],
    seoTitle: "Helpcentrum | Tatik.space",
    seoDescription: "Antwoorden over inloggen via e-maillink, de editor, back-ups en functies van Tatik.space Pro.",
  },
  tr: {
    title: "Destek",
    home: "Ana sayfaya dön",
    heading: "Yardım merkezi",
    intro: "Sık sorulan soruların yanıtlarını bulun veya ekibimizle iletişime geçin.",
    documentation: "Belgeler",
    documentationDescription: "Tatik.space Pro'da şu anda sunulan özelliklerin kılavuzlarını inceleyin.",
    documentationLink: "Belgeleri görüntüle",
    guides: "Uygulamalı kılavuzlar",
    guidesDescription: "Düzenleyici, yedekler ve harici sağlayıcılarla yayınlama hakkında kılavuzları izleyin.",
    guidesLink: "Kılavuzları aç",
    forum: "Topluluk forumu",
    forumDescription: "Forum henüz kullanıma açık değil. Kullanıcılar arası paylaşım başladığında sizi bilgilendireceğiz.",
    contact: "Doğrudan iletişim",
    contactDescription: "Yardım almak için ekibimize yazın.",
    contactLink: "Destek ekibiyle iletişime geç",
    faq: "Sık sorulan sorular",
    faqs: [
      ["Hesabıma nasıl giriş yaparım?", "Giriş sayfasına e-posta adresinizi girin. Kayıtlıysa 10 dakika geçerli, tek kullanımlık bir bağlantı alırsınız. Parola gerekmez."],
      ["Planları nerede karşılaştırabilirim?", "Planları ve koşullarını incelemek için Fiyatlar sayfasını ziyaret edin. Satın alma veya abonelik işlemleri sitedeki ödeme adımından başlatılır."],
      ["Projelerimi nasıl dışa aktarabilirim?", "Dosyaları düzenleyiciden indirin veya proje anlık görüntüsü oluşturmak için Backup'ı kullanın. Dağıtıma hazır paket olarak dışa aktarma özelliği yoktur."],
      ["Sürüm geçmişi nasıl çalışır?", "Düzenleyicideki geçmiş yalnızca geçerli oturumdaki sürümleri içerir. Geçicidir; yedeklerin veya kalıcı bulut geçmişinin yerini tutmaz."],
    ],
    seoTitle: "Yardım merkezi | Tatik.space",
    seoDescription: "E-posta bağlantısıyla giriş, düzenleyici, yedekler ve Tatik.space Pro özellikleri hakkında yanıtları bulun.",
  },
  sv: {
    title: "Support",
    home: "Tillbaka till startsidan",
    heading: "Hjälpcenter",
    intro: "Hitta svar på vanliga frågor eller kontakta vårt team.",
    documentation: "Dokumentation",
    documentationDescription: "Läs guider om funktioner som för närvarande finns i Tatik.space Pro.",
    documentationLink: "Visa dokumentation",
    guides: "Praktiska guider",
    guidesDescription: "Följ guider om redigeraren, säkerhetskopior och publicering via externa leverantörer.",
    guidesLink: "Öppna guider",
    forum: "Communityforum",
    forumDescription: "Forumet är inte tillgängligt ännu. Vi meddelar när användare kan diskutera med varandra.",
    contact: "Direktkontakt",
    contactDescription: "Kontakta vårt team om du behöver hjälp.",
    contactLink: "Kontakta support",
    faq: "Vanliga frågor",
    faqs: [
      ["Hur loggar jag in på mitt konto?", "Ange din e-postadress på inloggningssidan. Om den är registrerad får du en engångslänk som gäller i 10 minuter. Inget lösenord behövs."],
      ["Var kan jag jämföra abonnemang?", "Besök prissidan för att läsa om abonnemang och villkor. Köp och prenumerationer startas via webbplatsens kassa."],
      ["Hur exporterar jag mina projekt?", "Ladda ned filer från redigeraren eller använd Backup för att skapa en ögonblicksbild av projektet. Export som ett färdigt distributionspaket är inte tillgänglig."],
      ["Hur fungerar versionshistoriken?", "Historiken i redigeraren gäller versioner från den aktuella sessionen. Den är tillfällig och ersätter inte säkerhetskopior eller permanent molnhistorik."],
    ],
    seoTitle: "Hjälpcenter | Tatik.space",
    seoDescription: "Svar om inloggning via e-postlänk, redigeraren, säkerhetskopior och funktioner i Tatik.space Pro.",
  },
  da: {
    title: "Support",
    home: "Tilbage til forsiden",
    heading: "Hjælpecenter",
    intro: "Find svar på ofte stillede spørgsmål, eller kontakt vores team.",
    documentation: "Dokumentation",
    documentationDescription: "Læs vejledninger om de funktioner, der aktuelt er tilgængelige i Tatik.space Pro.",
    documentationLink: "Se dokumentation",
    guides: "Praktiske vejledninger",
    guidesDescription: "Følg vejledninger til editoren, sikkerhedskopier og publicering via eksterne udbydere.",
    guidesLink: "Åbn vejledninger",
    forum: "Communityforum",
    forumDescription: "Forumet er endnu ikke tilgængeligt. Vi giver besked, når brugere kan udveksle erfaringer.",
    contact: "Direkte kontakt",
    contactDescription: "Kontakt vores team, hvis du har brug for hjælp.",
    contactLink: "Kontakt support",
    faq: "Ofte stillede spørgsmål",
    faqs: [
      ["Hvordan logger jeg ind på min konto?", "Indtast din e-mailadresse på login-siden. Hvis den er registreret, modtager du et engangslink, der er gyldigt i 10 minutter. Du behøver ikke en adgangskode."],
      ["Hvor kan jeg sammenligne abonnementer?", "Besøg prissiden for at se abonnementer og vilkår. Køb og abonnementer startes via webstedets betaling."],
      ["Hvordan eksporterer jeg mine projekter?", "Download filer fra editoren, eller brug Backup til at oprette et øjebliksbillede af projektet. Eksport som en pakke, der er klar til udrulning, er ikke tilgængelig."],
      ["Hvordan fungerer versionshistorikken?", "Historikken i editoren omfatter versioner fra den aktuelle session. Den er midlertidig og erstatter ikke sikkerhedskopier eller permanent cloudhistorik."],
    ],
    seoTitle: "Hjælpecenter | Tatik.space",
    seoDescription: "Find svar om login via e-mail-link, editoren, sikkerhedskopier og funktionerne i Tatik.space Pro.",
  },
  no: {
    title: "Brukerstøtte",
    home: "Tilbake til forsiden",
    heading: "Hjelpesenter",
    intro: "Finn svar på vanlige spørsmål eller kontakt teamet vårt.",
    documentation: "Dokumentasjon",
    documentationDescription: "Les veiledninger om funksjonene som for øyeblikket er tilgjengelige i Tatik.space Pro.",
    documentationLink: "Vis dokumentasjon",
    guides: "Praktiske veiledninger",
    guidesDescription: "Følg veiledninger for editoren, sikkerhetskopier og publisering via eksterne leverandører.",
    guidesLink: "Åpne veiledninger",
    forum: "Fellesskapsforum",
    forumDescription: "Forumet er ikke tilgjengelig ennå. Vi gir beskjed når brukere kan dele erfaringer.",
    contact: "Direkte kontakt",
    contactDescription: "Kontakt teamet vårt hvis du trenger hjelp.",
    contactLink: "Kontakt brukerstøtte",
    faq: "Vanlige spørsmål",
    faqs: [
      ["Hvordan logger jeg inn på kontoen min?", "Skriv inn e-postadressen på innloggingssiden. Hvis den er registrert, får du en engangslenke som er gyldig i 10 minutter. Passord er ikke nødvendig."],
      ["Hvor kan jeg sammenligne abonnementer?", "Gå til prissiden for å se abonnementer og vilkår. Kjøp og abonnement startes via betalingen på nettstedet."],
      ["Hvordan eksporterer jeg prosjektene mine?", "Last ned filer fra editoren, eller bruk Backup for å opprette et øyeblikksbilde av prosjektet. Eksport som en distribusjonsklar pakke er ikke tilgjengelig."],
      ["Hvordan fungerer versjonshistorikken?", "Historikken i editoren omfatter versjoner fra den gjeldende økten. Den er midlertidig og erstatter ikke sikkerhetskopier eller permanent skyhistorikk."],
    ],
    seoTitle: "Hjelpesenter | Tatik.space",
    seoDescription: "Svar om innlogging med e-postlenke, editoren, sikkerhetskopier og funksjoner i Tatik.space Pro.",
  },
  fi: {
    title: "Tuki",
    home: "Takaisin etusivulle",
    heading: "Ohjekeskus",
    intro: "Etsi vastauksia yleisiin kysymyksiin tai ota yhteyttä tiimiimme.",
    documentation: "Dokumentaatio",
    documentationDescription: "Lue Tatik.space Pron tällä hetkellä saatavilla olevien toimintojen ohjeet.",
    documentationLink: "Näytä dokumentaatio",
    guides: "Käytännön oppaat",
    guidesDescription: "Oppaita editorin käyttöön, varmuuskopioihin ja julkaisemiseen ulkoisten palveluntarjoajien kautta.",
    guidesLink: "Avaa oppaat",
    forum: "Yhteisöfoorumi",
    forumDescription: "Foorumi ei ole vielä käytettävissä. Ilmoitamme, kun käyttäjät voivat keskustella keskenään.",
    contact: "Suora yhteys",
    contactDescription: "Ota yhteyttä tiimiimme, jos tarvitset apua.",
    contactLink: "Ota yhteyttä tukeen",
    faq: "Usein kysytyt kysymykset",
    faqs: [
      ["Miten kirjaudun tililleni?", "Anna sähköpostiosoitteesi kirjautumissivulla. Jos osoite on rekisteröity, saat kertakäyttöisen linkin, joka on voimassa 10 minuuttia. Salasanaa ei tarvita."],
      ["Missä voin vertailla tilauksia?", "Tutustu tilauksiin ja ehtoihin Hinnat-sivulla. Ostot ja tilaukset aloitetaan sivuston maksutoiminnon kautta."],
      ["Miten vien projektini?", "Lataa tiedostot editorista tai luo projektin tilannekuva Backup-toiminnolla. Projektin vieminen suoraan käyttöönotettavana pakettina ei ole mahdollista."],
      ["Miten versiohistoria toimii?", "Editorin historia sisältää nykyisen istunnon versiot. Se on väliaikainen eikä korvaa varmuuskopioita tai pysyvää pilvihistoriaa."],
    ],
    seoTitle: "Ohjekeskus | Tatik.space",
    seoDescription: "Vastauksia sähköpostilinkillä kirjautumiseen, editoriin, varmuuskopioihin ja Tatik.space Pron ominaisuuksiin.",
  },
  uk: {
    title: "Підтримка",
    home: "На головну",
    heading: "Центр підтримки",
    intro: "Знайдіть відповіді на поширені запитання або зв’яжіться з нашою командою.",
    documentation: "Документація",
    documentationDescription: "Перегляньте посібники щодо функцій, доступних у Tatik.space Pro.",
    documentationLink: "Переглянути документацію",
    guides: "Практичні посібники",
    guidesDescription: "Посібники з редактора, резервного копіювання та публікації через зовнішніх провайдерів.",
    guidesLink: "Відкрити посібники",
    forum: "Форум спільноти",
    forumDescription: "Форум ще недоступний. Ми повідомимо, коли користувачі зможуть спілкуватися між собою.",
    contact: "Прямий зв’язок",
    contactDescription: "Напишіть нашій команді, якщо вам потрібна допомога.",
    contactLink: "Зв’язатися з підтримкою",
    faq: "Поширені запитання",
    faqs: [
      ["Як увійти до свого облікового запису?", "Введіть адресу електронної пошти на сторінці входу. Якщо вона зареєстрована, ви отримаєте одноразове посилання, дійсне 10 хвилин. Пароль не потрібен."],
      ["Де порівняти плани?", "Відвідайте сторінку цін, щоб переглянути плани та умови. Покупки й підписки оформлюються через checkout на сайті."],
      ["Як експортувати проєкти?", "Завантажте файли з редактора або створіть знімок проєкту за допомогою Backup. Експорт у вигляді готового до розгортання пакета недоступний."],
      ["Як працює історія версій?", "Історія редактора містить версії поточного сеансу. Вона тимчасова й не замінює резервні копії або постійну хмарну історію."],
    ],
    seoTitle: "Центр підтримки | Tatik.space",
    seoDescription: "Відповіді про вхід за посиланням з електронної пошти, редактор, резервні копії та функції Tatik.space Pro.",
  },
  cs: {
    title: "Podpora",
    home: "Zpět na hlavní stránku",
    heading: "Centrum nápovědy",
    intro: "Najděte odpovědi na časté otázky nebo kontaktujte náš tým.",
    documentation: "Dokumentace",
    documentationDescription: "Projděte si návody k funkcím, které jsou v Tatik.space Pro aktuálně dostupné.",
    documentationLink: "Zobrazit dokumentaci",
    guides: "Praktické návody",
    guidesDescription: "Návody k editoru, zálohám a publikování prostřednictvím externích poskytovatelů.",
    guidesLink: "Otevřít návody",
    forum: "Komunitní fórum",
    forumDescription: "Fórum zatím není dostupné. Dáme vám vědět, až bude možné diskutovat s ostatními uživateli.",
    contact: "Přímý kontakt",
    contactDescription: "Pokud potřebujete pomoc, napište našemu týmu.",
    contactLink: "Kontaktovat podporu",
    faq: "Časté dotazy",
    faqs: [
      ["Jak se přihlásím ke svému účtu?", "Na přihlašovací stránce zadejte e-mailovou adresu. Pokud je registrovaná, obdržíte jednorázový odkaz platný 10 minut. Heslo není potřeba."],
      ["Kde mohu porovnat tarify?", "Na stránce Ceník najdete tarify a jejich podmínky. Nákup nebo předplatné zahájíte přes checkout na webu."],
      ["Jak mohu exportovat projekty?", "Stáhněte soubory z editoru nebo použijte Backup k vytvoření snímku projektu. Export projektu jako balíčku připraveného k nasazení není dostupný."],
      ["Jak funguje historie verzí?", "Historie dostupná v editoru zahrnuje verze z aktuální relace. Je dočasná a nenahrazuje zálohy ani trvalou cloudovou historii."],
    ],
    seoTitle: "Centrum nápovědy | Tatik.space",
    seoDescription: "Odpovědi k přihlášení pomocí e-mailového odkazu, editoru, zálohám a funkcím Tatik.space Pro.",
  },
};
