const templateIds = [
  "agency-site",
  "saas-dashboard",
  "shop-minimal",
  "seo-landing",
  "doc-site",
  "contact-form-pro",
  "saas-landing-pro",
  "ecommerce-luxury",
  "portfolio-developer",
  "business-corporate",
  "blog-magazine",
  "react-portfolio-pro",
] as const;

type TemplateId = (typeof templateIds)[number];
type TemplateDescriptions = Record<TemplateId, string>;

export const templateMarketplaceContentCopy: Record<string, TemplateDescriptions> = {
  en: {
    "agency-site": "Creative agency website with animated hero, portfolio grid, team profiles, case studies, services, client logos, contact call to action, and testimonials.",
    "saas-dashboard": "Complete admin dashboard with sidebar navigation, six metric cards and charts, activity log, user management, dark-mode toggle, responsive layout, and chart integration.",
    "shop-minimal": "Minimal online store with a responsive four-column product grid, search and filters, persistent cart, quick-view modal, wishlist, visible prices, and a clean white theme.",
    "seo-landing": "SEO-ready landing page with structured metadata, schema.org markup, fast loading, mobile optimization, internal links, strategic calls to action, and newsletter form.",
    "doc-site": "Technical documentation site with sidebar navigation, table of contents, code highlighting, working search, dark mode, breadcrumbs, and version selector.",
    "contact-form-pro": "Advanced contact form with real-time validation, clear error and success messages, spam protection, file uploads, reCAPTCHA, email confirmation, and responsive layout.",
    "saas-landing-pro": "Enterprise SaaS landing page with animated gradient hero, six feature cards, three-tier dynamic pricing, sticky blurred navigation, testimonial carousel, KPI statistics, and newsletter.",
    "ecommerce-luxury": "Luxury online store with premium product imagery, advanced filters, interactive wishlist, available color options, ratings, stock indicator, and elegant checkout.",
    "portfolio-developer": "Developer portfolio with dark hero and call to action, animated skill bars, screenshot project gallery, experience timeline, testimonials, contact form, and GitHub/LinkedIn links.",
    "business-corporate": "Corporate website with blue-gradient hero, team profiles and roles, service cards, customer testimonials, contact section, and certified footer.",
    "blog-magazine": "Editorial magazine blog with featured-article hero, numbered trending sidebar, article grid, newsletter signup, elegant dark theme, and serif typography.",
    "react-portfolio-pro": "Advanced React portfolio with component examples, scroll-aware navigation, animated skill bars, filterable projects, GitHub integration, and dark neon theme.",
  },
  it: {
    "agency-site": "Sito per agenzia creativa con hero animata, griglia portfolio, profili del team, casi di studio, servizi, loghi dei clienti, invito al contatto e testimonianze.",
    "saas-dashboard": "Dashboard amministrativa completa con navigazione laterale, sei schede statistiche con grafici, registro attività, gestione utenti, modalità scura, layout responsive e grafici integrati.",
    "shop-minimal": "Negozio online minimalista con griglia prodotti responsive a quattro colonne, ricerca e filtri, carrello persistente, anteprima rapida, lista dei desideri, prezzi visibili e tema bianco.",
    "seo-landing": "Landing page ottimizzata per SEO con metadati strutturati, markup schema.org, caricamento rapido, ottimizzazione mobile, link interni, inviti all’azione e modulo newsletter.",
    "doc-site": "Sito di documentazione tecnica con navigazione laterale, indice, evidenziazione del codice, ricerca funzionante, modalità scura, breadcrumb e selettore di versione.",
    "contact-form-pro": "Modulo di contatto avanzato con convalida in tempo reale, messaggi chiari di errore e conferma, protezione antispam, caricamento file, reCAPTCHA, conferma email e layout responsive.",
    "saas-landing-pro": "Landing page SaaS enterprise con hero animata a gradiente, sei schede funzionalità, prezzi dinamici a tre livelli, navigazione fissa sfocata, carosello testimonianze, statistiche KPI e newsletter.",
    "ecommerce-luxury": "Negozio online di lusso con immagini premium, filtri avanzati, lista dei desideri interattiva, colori disponibili, valutazioni, indicatore scorte e checkout elegante.",
    "portfolio-developer": "Portfolio per sviluppatori con hero scura e invito all’azione, barre delle competenze animate, progetti con screenshot, timeline delle esperienze, testimonianze, modulo contatti e link GitHub/LinkedIn.",
    "business-corporate": "Sito aziendale con hero a gradiente blu, team e ruoli, schede dei servizi, testimonianze dei clienti, sezione contatti e piè di pagina con certificazioni.",
    "blog-magazine": "Blog editoriale in stile magazine con articolo in evidenza, barra laterale delle tendenze numerate, griglia articoli, iscrizione alla newsletter, tema scuro elegante e caratteri serif.",
    "react-portfolio-pro": "Portfolio React avanzato con esempi di componenti, navigazione sincronizzata allo scorrimento, competenze animate, progetti filtrabili, integrazione GitHub e tema scuro neon.",
  },
  es: {
    "agency-site": "Sitio para agencia creativa con portada animada, cuadrícula de proyectos, perfiles del equipo, casos de estudio, servicios, logotipos de clientes, llamada de contacto y testimonios.",
    "saas-dashboard": "Panel de administración completo con navegación lateral, seis tarjetas métricas con gráficos, registro de actividad, gestión de usuarios, modo oscuro, diseño adaptable e integración de gráficos.",
    "shop-minimal": "Tienda online minimalista con cuadrícula adaptable de productos en cuatro columnas, búsqueda y filtros, carrito persistente, vista rápida, lista de deseos, precios visibles y tema blanco.",
    "seo-landing": "Página de destino optimizada para SEO con metadatos estructurados, marcado schema.org, carga rápida, optimización móvil, enlaces internos, llamadas a la acción y formulario de boletín.",
    "doc-site": "Sitio de documentación técnica con navegación lateral, índice, resaltado de código, búsqueda funcional, modo oscuro, migas de pan y selector de versión.",
    "contact-form-pro": "Formulario de contacto avanzado con validación en tiempo real, mensajes claros de error y confirmación, protección contra spam, carga de archivos, reCAPTCHA, confirmación por correo y diseño adaptable.",
    "saas-landing-pro": "Página SaaS empresarial con portada animada en degradado, seis tarjetas de funciones, precios dinámicos de tres niveles, navegación fija difuminada, carrusel de testimonios, métricas KPI y boletín.",
    "ecommerce-luxury": "Tienda online de lujo con imágenes premium, filtros avanzados, lista de deseos interactiva, colores disponibles, valoraciones, indicador de existencias y pago elegante.",
    "portfolio-developer": "Portafolio para desarrolladores con portada oscura y llamada a la acción, barras de habilidades animadas, proyectos con capturas, cronología profesional, testimonios, formulario y enlaces a GitHub/LinkedIn.",
    "business-corporate": "Sitio corporativo con portada en degradado azul, perfiles y cargos del equipo, tarjetas de servicios, testimonios de clientes, sección de contacto y pie con certificaciones.",
    "blog-magazine": "Blog editorial tipo revista con artículo destacado, barra lateral de tendencias numeradas, cuadrícula de artículos, suscripción al boletín, tema oscuro elegante y tipografía serif.",
    "react-portfolio-pro": "Portafolio avanzado en React con ejemplos de componentes, navegación vinculada al desplazamiento, habilidades animadas, proyectos filtrables, integración con GitHub y tema oscuro neón.",
  },
  fr: {
    "agency-site": "Site d’agence créative avec bannière animée, grille de portfolio, profils de l’équipe, études de cas, services, logos clients, appel au contact et témoignages.",
    "saas-dashboard": "Tableau de bord d’administration complet avec navigation latérale, six cartes de statistiques et graphiques, journal d’activité, gestion des utilisateurs, mode sombre, mise en page adaptative et graphiques intégrés.",
    "shop-minimal": "Boutique en ligne minimaliste avec grille de produits adaptative sur quatre colonnes, recherche et filtres, panier persistant, aperçu rapide, liste de souhaits, prix visibles et thème blanc.",
    "seo-landing": "Page d’atterrissage optimisée SEO avec métadonnées structurées, balisage schema.org, chargement rapide, optimisation mobile, liens internes, appels à l’action et formulaire de newsletter.",
    "doc-site": "Site de documentation technique avec navigation latérale, table des matières, coloration du code, recherche fonctionnelle, mode sombre, fil d’Ariane et sélecteur de version.",
    "contact-form-pro": "Formulaire de contact avancé avec validation en temps réel, messages d’erreur et de confirmation clairs, protection antispam, téléversement de fichiers, reCAPTCHA, confirmation par e-mail et mise en page adaptative.",
    "saas-landing-pro": "Page SaaS d’entreprise avec bannière dégradée animée, six cartes de fonctionnalités, tarifs dynamiques à trois niveaux, navigation fixe floutée, carrousel de témoignages, statistiques KPI et newsletter.",
    "ecommerce-luxury": "Boutique en ligne de luxe avec images premium, filtres avancés, liste de souhaits interactive, couleurs disponibles, évaluations, indicateur de stock et paiement élégant.",
    "portfolio-developer": "Portfolio développeur avec bannière sombre et appel à l’action, barres de compétences animées, projets illustrés, chronologie professionnelle, témoignages, formulaire de contact et liens GitHub/LinkedIn.",
    "business-corporate": "Site d’entreprise avec bannière en dégradé bleu, profils et rôles de l’équipe, cartes de services, témoignages clients, section contact et pied de page avec certifications.",
    "blog-magazine": "Blog de magazine éditorial avec article vedette, barre latérale des tendances numérotées, grille d’articles, inscription à la newsletter, thème sombre élégant et typographie à empattement.",
    "react-portfolio-pro": "Portfolio React avancé avec exemples de composants, navigation synchronisée au défilement, compétences animées, projets filtrables, intégration GitHub et thème sombre néon.",
  },
  de: {
    "agency-site": "Website für eine Kreativagentur mit animiertem Hero-Bereich, Portfolio-Raster, Teamprofilen, Fallstudien, Services, Kundenlogos, Kontaktaufruf und Erfahrungsberichten.",
    "saas-dashboard": "Vollständiges Admin-Dashboard mit Seitennavigation, sechs Statistik-Karten mit Diagrammen, Aktivitätsprotokoll, Benutzerverwaltung, Dark Mode, responsivem Layout und Diagrammintegration.",
    "shop-minimal": "Minimalistischer Onlineshop mit responsivem Produkt-Raster in vier Spalten, Suche und Filtern, dauerhaftem Warenkorb, Schnellansicht, Wunschliste, sichtbaren Preisen und hellem Design.",
    "seo-landing": "SEO-optimierte Landingpage mit strukturierten Metadaten, schema.org-Markup, schnellem Laden, mobiler Optimierung, internen Links, Handlungsaufrufen und Newsletter-Formular.",
    "doc-site": "Technische Dokumentationswebsite mit Seitennavigation, Inhaltsverzeichnis, Code-Hervorhebung, funktionierender Suche, Dark Mode, Breadcrumbs und Versionsauswahl.",
    "contact-form-pro": "Erweitertes Kontaktformular mit Echtzeitvalidierung, klaren Fehler- und Erfolgsmeldungen, Spamschutz, Datei-Upload, reCAPTCHA, E-Mail-Bestätigung und responsivem Layout.",
    "saas-landing-pro": "Enterprise-SaaS-Landingpage mit animiertem Farbverlauf im Hero-Bereich, sechs Funktionskarten, dynamischen Preisen in drei Stufen, fixierter unscharfer Navigation, Testimonial-Karussell, KPI-Statistiken und Newsletter.",
    "ecommerce-luxury": "Luxus-Onlineshop mit Premium-Produktfotos, erweiterten Filtern, interaktiver Wunschliste, verfügbaren Farben, Bewertungen, Lageranzeige und elegantem Checkout.",
    "portfolio-developer": "Entwicklerportfolio mit dunklem Hero-Bereich und Handlungsaufruf, animierten Kompetenzbalken, Projektgalerie mit Screenshots, Erfahrungstimeline, Erfahrungsberichten, Kontaktformular und GitHub-/LinkedIn-Links.",
    "business-corporate": "Unternehmenswebsite mit blauem Farbverlauf im Hero-Bereich, Teamprofilen und Rollen, Servicekarten, Kundenstimmen, Kontaktbereich und Fußzeile mit Zertifizierungen.",
    "blog-magazine": "Redaktioneller Magazin-Blog mit hervorgehobenem Artikel, nummerierter Trend-Seitenleiste, Artikelraster, Newsletter-Anmeldung, elegantem dunklem Design und Serifenschrift.",
    "react-portfolio-pro": "Fortgeschrittenes React-Portfolio mit Komponentenbeispielen, scrollabhängiger Navigation, animierten Kompetenzen, filterbaren Projekten, GitHub-Integration und dunklem Neon-Design.",
  },
  pt: {
    "agency-site": "Site para agência criativa com destaque animado, grelha de portfólio, perfis da equipa, estudos de caso, serviços, logótipos de clientes, chamada de contacto e testemunhos.",
    "saas-dashboard": "Painel de administração completo com navegação lateral, seis cartões de métricas com gráficos, registo de atividade, gestão de utilizadores, modo escuro, esquema responsivo e integração de gráficos.",
    "shop-minimal": "Loja online minimalista com grelha responsiva de produtos em quatro colunas, pesquisa e filtros, carrinho persistente, pré-visualização rápida, lista de desejos, preços visíveis e tema branco.",
    "seo-landing": "Página de destino otimizada para SEO com metadados estruturados, marcação schema.org, carregamento rápido, otimização móvel, ligações internas, chamadas à ação e formulário de newsletter.",
    "doc-site": "Site de documentação técnica com navegação lateral, índice, realce de código, pesquisa funcional, modo escuro, navegação estrutural e seletor de versão.",
    "contact-form-pro": "Formulário de contacto avançado com validação em tempo real, mensagens claras de erro e sucesso, proteção contra spam, carregamento de ficheiros, reCAPTCHA, confirmação por e-mail e esquema responsivo.",
    "saas-landing-pro": "Página SaaS empresarial com destaque animado em gradiente, seis cartões de funcionalidades, preços dinâmicos em três níveis, navegação fixa desfocada, carrossel de testemunhos, métricas KPI e newsletter.",
    "ecommerce-luxury": "Loja online de luxo com imagens premium, filtros avançados, lista de desejos interativa, cores disponíveis, avaliações, indicador de stock e finalização de compra elegante.",
    "portfolio-developer": "Portfólio de programador com destaque escuro e chamada à ação, barras de competências animadas, projetos com capturas de ecrã, cronologia profissional, testemunhos, formulário de contacto e ligações GitHub/LinkedIn.",
    "business-corporate": "Site empresarial com destaque em gradiente azul, perfis e funções da equipa, cartões de serviços, testemunhos de clientes, secção de contacto e rodapé com certificações.",
    "blog-magazine": "Blog editorial de revista com artigo em destaque, barra lateral de tendências numeradas, grelha de artigos, subscrição da newsletter, tema escuro elegante e tipografia serifada.",
    "react-portfolio-pro": "Portfólio React avançado com exemplos de componentes, navegação ligada à deslocação, competências animadas, projetos filtráveis, integração GitHub e tema escuro neon.",
  },
  ru: {
    "agency-site": "Сайт креативного агентства: анимированный главный экран, сетка портфолио, профили команды, кейсы, услуги, логотипы клиентов, призыв связаться и отзывы.",
    "saas-dashboard": "Полная панель администратора: боковая навигация, шесть карточек показателей с графиками, журнал действий, управление пользователями, тёмная тема, адаптивная вёрстка и графики.",
    "shop-minimal": "Минималистичный интернет-магазин: адаптивная сетка товаров в четыре колонки, поиск и фильтры, постоянная корзина, быстрый просмотр, список желаний, цены и светлая тема.",
    "seo-landing": "SEO-оптимизированная целевая страница: структурированные метаданные, разметка schema.org, быстрая загрузка, мобильная оптимизация, внутренние ссылки, призывы к действию и форма рассылки.",
    "doc-site": "Сайт технической документации: боковая навигация, оглавление, подсветка кода, работающий поиск, тёмная тема, хлебные крошки и выбор версии.",
    "contact-form-pro": "Расширенная контактная форма: проверка в реальном времени, понятные сообщения об ошибках и успехе, защита от спама, загрузка файлов, reCAPTCHA, подтверждение по почте и адаптивная вёрстка.",
    "saas-landing-pro": "Корпоративная SaaS-страница: анимированный градиентный экран, шесть карточек функций, динамические тарифы из трёх уровней, закреплённая размытая навигация, карусель отзывов, KPI и рассылка.",
    "ecommerce-luxury": "Роскошный интернет-магазин: премиальные изображения товаров, расширенные фильтры, интерактивный список желаний, варианты цветов, оценки, наличие на складе и элегантная оплата.",
    "portfolio-developer": "Портфолио разработчика: тёмный главный экран с призывом к действию, анимированные шкалы навыков, проекты со скриншотами, хронология опыта, отзывы, контакты и ссылки GitHub/LinkedIn.",
    "business-corporate": "Корпоративный сайт: главный экран с синим градиентом, профили и роли команды, карточки услуг, отзывы клиентов, контакты и подвал с сертификатами.",
    "blog-magazine": "Редакционный блог-журнал: главный экран с избранной статьёй, боковая панель трендов с нумерацией, сетка статей, подписка на рассылку, элегантная тёмная тема и шрифт с засечками.",
    "react-portfolio-pro": "Продвинутое портфолио React: примеры компонентов, навигация по прокрутке, анимированные навыки, фильтруемые проекты, интеграция GitHub и тёмная неоновая тема.",
  },
  zh: {
    "agency-site": "创意机构网站，包含动画主视觉、作品集网格、团队简介、案例研究、服务、客户标志、联系行动按钮和客户评价。",
    "saas-dashboard": "完整管理后台，包含侧边导航、六个指标图表卡片、活动记录、用户管理、深色模式、响应式布局和图表集成。",
    "shop-minimal": "极简网店，包含响应式四列商品网格、搜索和筛选、常驻购物车、快速查看窗口、愿望清单、商品价格和简洁白色主题。",
    "seo-landing": "SEO 优化落地页，包含结构化元数据、schema.org 标记、快速加载、移动端优化、内部链接、行动按钮和新闻订阅表单。",
    "doc-site": "技术文档网站，包含侧边导航、目录、代码高亮、可用搜索、深色模式、面包屑导航和版本选择器。",
    "contact-form-pro": "高级联系表单，包含实时验证、清晰的错误和成功提示、垃圾信息防护、文件上传、reCAPTCHA、邮件确认和响应式布局。",
    "saas-landing-pro": "企业级 SaaS 落地页，包含渐变动画主视觉、六个功能卡片、三级动态定价、固定模糊导航、评价轮播、KPI 数据和新闻订阅。",
    "ecommerce-luxury": "奢华网店，包含高品质商品图片、高级筛选、互动愿望清单、可选颜色、评分、库存提示和优雅结账流程。",
    "portfolio-developer": "开发者作品集，包含深色主视觉和行动按钮、动画技能条、项目截图、工作经历时间线、评价、联系表单及 GitHub/LinkedIn 链接。",
    "business-corporate": "企业网站，包含蓝色渐变主视觉、团队成员和职位、服务卡片、客户评价、联系区域及带认证信息的页脚。",
    "blog-magazine": "编辑杂志博客，包含特色文章主视觉、编号趋势侧栏、文章网格、新闻订阅、优雅深色主题和衬线字体。",
    "react-portfolio-pro": "高级 React 作品集，包含组件示例、滚动联动导航、动画技能、可筛选项目、GitHub 集成和深色霓虹主题。",
  },
  ja: {
    "agency-site": "クリエイティブエージェンシーのサイト。アニメーション付きヒーロー、ポートフォリオ一覧、チーム紹介、事例、サービス、顧客ロゴ、問い合わせ導線、推薦文を掲載。",
    "saas-dashboard": "管理用ダッシュボード。サイドナビ、グラフ付き統計カード6枚、操作ログ、ユーザー管理、ダークモード、レスポンシブ表示、グラフ連携を備えています。",
    "shop-minimal": "ミニマルなオンラインストア。4列のレスポンシブ商品一覧、検索とフィルター、常時表示カート、クイックビュー、ウィッシュリスト、価格表示、白基調のテーマを備えています。",
    "seo-landing": "SEO向けランディングページ。構造化メタデータ、schema.orgマークアップ、高速表示、モバイル最適化、内部リンク、行動喚起、ニュースレターフォームを備えています。",
    "doc-site": "技術ドキュメントサイト。サイドナビ、目次、コードのハイライト、検索、ダークモード、パンくずリスト、バージョン選択を備えています。",
    "contact-form-pro": "高度な問い合わせフォーム。リアルタイム検証、明確なエラー・完了メッセージ、迷惑送信対策、ファイル添付、reCAPTCHA、メール確認、レスポンシブ表示を備えています。",
    "saas-landing-pro": "エンタープライズSaaSページ。グラデーションアニメーションのヒーロー、機能カード6枚、3段階の動的料金、固定ぼかしナビ、推薦文カルーセル、KPI統計、ニュースレターを備えています。",
    "ecommerce-luxury": "高級オンラインストア。プレミアム商品画像、高度なフィルター、インタラクティブなウィッシュリスト、色の選択、評価、在庫表示、洗練された決済を備えています。",
    "portfolio-developer": "開発者向けポートフォリオ。ダークなヒーローと行動喚起、アニメーション付きスキルバー、スクリーンショット付きプロジェクト、経歴タイムライン、推薦文、問い合わせフォーム、GitHub/LinkedInリンクを掲載。",
    "business-corporate": "企業サイト。青いグラデーションのヒーロー、チーム紹介と役職、サービスカード、顧客の推薦文、問い合わせ欄、認証情報付きフッターを備えています。",
    "blog-magazine": "雑誌風の編集ブログ。注目記事のヒーロー、番号付きトレンド欄、記事一覧、ニュースレター登録、上品なダークテーマ、セリフ体を備えています。",
    "react-portfolio-pro": "高度なReactポートフォリオ。コンポーネント例、スクロール連動ナビ、アニメーション付きスキル、絞り込み可能なプロジェクト、GitHub連携、ダークネオンテーマを備えています。",
  },
  ko: {
    "agency-site": "애니메이션 히어로, 포트폴리오 그리드, 팀 프로필, 사례 연구, 서비스, 고객 로고, 문의 버튼과 추천사를 갖춘 크리에이티브 에이전시 웹사이트입니다.",
    "saas-dashboard": "사이드바 탐색, 차트가 포함된 통계 카드 6개, 활동 기록, 사용자 관리, 다크 모드, 반응형 레이아웃과 차트 통합을 갖춘 관리자 대시보드입니다.",
    "shop-minimal": "반응형 4열 상품 그리드, 검색과 필터, 고정 장바구니, 빠른 보기 창, 위시리스트, 가격 표시와 깔끔한 흰색 테마를 갖춘 미니멀 온라인 스토어입니다.",
    "seo-landing": "구조화된 메타데이터, schema.org 마크업, 빠른 로딩, 모바일 최적화, 내부 링크, 행동 유도 버튼과 뉴스레터 양식을 갖춘 SEO 랜딩 페이지입니다.",
    "doc-site": "사이드바 탐색, 목차, 코드 강조 표시, 검색, 다크 모드, 이동 경로와 버전 선택기를 갖춘 기술 문서 사이트입니다.",
    "contact-form-pro": "실시간 검증, 명확한 오류 및 성공 메시지, 스팸 방지, 파일 업로드, reCAPTCHA, 이메일 확인과 반응형 레이아웃을 갖춘 고급 문의 양식입니다.",
    "saas-landing-pro": "애니메이션 그라데이션 히어로, 기능 카드 6개, 3단계 동적 요금, 고정 흐림 탐색, 추천사 캐러셀, KPI 통계와 뉴스레터를 갖춘 엔터프라이즈 SaaS 페이지입니다.",
    "ecommerce-luxury": "프리미엄 상품 이미지, 고급 필터, 대화형 위시리스트, 색상 옵션, 평점, 재고 표시와 세련된 결제를 갖춘 럭셔리 온라인 스토어입니다.",
    "portfolio-developer": "어두운 히어로와 행동 유도 버튼, 애니메이션 기술 막대, 스크린샷 프로젝트, 경력 타임라인, 추천사, 문의 양식과 GitHub/LinkedIn 링크를 갖춘 개발자 포트폴리오입니다.",
    "business-corporate": "파란 그라데이션 히어로, 팀 프로필과 역할, 서비스 카드, 고객 추천사, 문의 섹션과 인증 정보가 있는 바닥글을 갖춘 기업 웹사이트입니다.",
    "blog-magazine": "주요 기사 히어로, 번호가 매겨진 트렌드 사이드바, 기사 그리드, 뉴스레터 가입, 우아한 다크 테마와 세리프 글꼴을 갖춘 편집형 매거진 블로그입니다.",
    "react-portfolio-pro": "컴포넌트 예제, 스크롤 연동 탐색, 애니메이션 기술, 필터링 가능한 프로젝트, GitHub 통합과 다크 네온 테마를 갖춘 고급 React 포트폴리오입니다.",
  },
  ar: {
    "agency-site": "موقع لوكالة إبداعية يضم واجهة رئيسية متحركة، وشبكة أعمال، وملفات الفريق، ودراسات حالة، وخدمات، وشعارات العملاء، ودعوة للتواصل، وآراء العملاء.",
    "saas-dashboard": "لوحة إدارة متكاملة تضم تنقلًا جانبيًا، وست بطاقات مؤشرات ورسومًا بيانية، وسجل نشاط، وإدارة مستخدمين، ووضعًا داكنًا، وتصميمًا متجاوبًا، وتكاملًا للرسوم.",
    "shop-minimal": "متجر إلكتروني بسيط يضم شبكة منتجات متجاوبة بأربعة أعمدة، وبحثًا وفلاتر، وسلة ثابتة، ومعاينة سريعة، وقائمة رغبات، وأسعارًا واضحة، ومظهرًا أبيض نظيفًا.",
    "seo-landing": "صفحة هبوط محسّنة لمحركات البحث تضم بيانات وصفية منظمة، وترميز schema.org، وتحميلًا سريعًا، وتحسينًا للهواتف، وروابط داخلية، ودعوات لاتخاذ إجراء، ونموذج نشرة بريدية.",
    "doc-site": "موقع توثيق تقني يضم تنقلًا جانبيًا، وفهرس محتويات، وتمييزًا للكود، وبحثًا فعّالًا، ووضعًا داكنًا، ومسار تنقل، ومحدد إصدار.",
    "contact-form-pro": "نموذج اتصال متقدم يضم تحققًا فوريًا، ورسائل واضحة للخطأ والنجاح، وحماية من الرسائل المزعجة، ورفع ملفات، وreCAPTCHA، وتأكيدًا بالبريد، وتصميمًا متجاوبًا.",
    "saas-landing-pro": "صفحة SaaS للمؤسسات تضم واجهة متدرجة متحركة، وست بطاقات ميزات، وتسعيرًا ديناميكيًا بثلاث فئات، وتنقلًا ثابتًا ضبابيًا، ودوّارة آراء، ومؤشرات KPI، ونشرة بريدية.",
    "ecommerce-luxury": "متجر إلكتروني فاخر يضم صور منتجات مميزة، وفلاتر متقدمة، وقائمة رغبات تفاعلية، وألوانًا متاحة، وتقييمات، ومؤشر مخزون، وإتمام شراء أنيقًا.",
    "portfolio-developer": "معرض أعمال للمطورين يضم واجهة داكنة ودعوة لاتخاذ إجراء، وأشرطة مهارات متحركة، ومشاريع بصور، وتسلسلًا زمنيًا للخبرة، وآراء، ونموذج تواصل، وروابط GitHub وLinkedIn.",
    "business-corporate": "موقع شركة يضم واجهة بتدرج أزرق، وملفات الفريق ومناصبهم، وبطاقات خدمات، وآراء العملاء، وقسم تواصل، وتذييلًا للشهادات.",
    "blog-magazine": "مدونة تحريرية بأسلوب المجلات تضم واجهة لمقال مميز، وشريط اتجاهات مرقمًا، وشبكة مقالات، واشتراكًا بالنشرة، ومظهرًا داكنًا أنيقًا، وخطوطًا ذات زوائد.",
    "react-portfolio-pro": "معرض React متقدم يضم أمثلة مكونات، وتنقلًا مرتبطًا بالتمرير، ومهارات متحركة، ومشاريع قابلة للتصفية، وتكامل GitHub، ومظهرًا داكنًا نيونّيًا.",
  },
  hi: {
    "agency-site": "एनिमेटेड हीरो, पोर्टफोलियो ग्रिड, टीम प्रोफ़ाइल, केस स्टडी, सेवाएँ, ग्राहक लोगो, संपर्क कार्रवाई और प्रशंसापत्र वाला रचनात्मक एजेंसी वेबसाइट।",
    "saas-dashboard": "साइडबार नेविगेशन, चार्ट सहित छह आँकड़ा कार्ड, गतिविधि लॉग, उपयोगकर्ता प्रबंधन, डार्क मोड, रिस्पॉन्सिव लेआउट और चार्ट एकीकरण वाला पूरा एडमिन डैशबोर्ड।",
    "shop-minimal": "रिस्पॉन्सिव चार-कॉलम उत्पाद ग्रिड, खोज और फ़िल्टर, स्थायी कार्ट, त्वरित दृश्य, इच्छा-सूची, स्पष्ट कीमतें और साफ़ सफ़ेद थीम वाला न्यूनतम ऑनलाइन स्टोर।",
    "seo-landing": "संरचित मेटाडेटा, schema.org मार्कअप, तेज़ लोडिंग, मोबाइल अनुकूलन, आंतरिक लिंक, कार्रवाई बटन और न्यूज़लेटर फ़ॉर्म वाला SEO-अनुकूल लैंडिंग पेज।",
    "doc-site": "साइडबार नेविगेशन, विषय-सूची, कोड हाइलाइटिंग, काम करने वाली खोज, डार्क मोड, ब्रेडक्रंब और संस्करण चयन वाला तकनीकी दस्तावेज़ साइट।",
    "contact-form-pro": "रीयल-टाइम सत्यापन, स्पष्ट त्रुटि और सफलता संदेश, स्पैम सुरक्षा, फ़ाइल अपलोड, reCAPTCHA, ईमेल पुष्टि और रिस्पॉन्सिव लेआउट वाला उन्नत संपर्क फ़ॉर्म।",
    "saas-landing-pro": "एनिमेटेड ग्रेडिएंट हीरो, छह सुविधा कार्ड, तीन स्तर की गतिशील कीमतें, स्थिर धुंधला नेविगेशन, प्रशंसापत्र कैरोसेल, KPI आँकड़े और न्यूज़लेटर वाला एंटरप्राइज़ SaaS पेज।",
    "ecommerce-luxury": "प्रीमियम उत्पाद चित्र, उन्नत फ़िल्टर, इंटरैक्टिव इच्छा-सूची, उपलब्ध रंग, रेटिंग, स्टॉक संकेतक और आकर्षक चेकआउट वाला लक्ज़री ऑनलाइन स्टोर।",
    "portfolio-developer": "डार्क हीरो और कार्रवाई बटन, एनिमेटेड कौशल बार, स्क्रीनशॉट वाले प्रोजेक्ट, अनुभव टाइमलाइन, प्रशंसापत्र, संपर्क फ़ॉर्म और GitHub/LinkedIn लिंक वाला डेवलपर पोर्टफोलियो।",
    "business-corporate": "नीले ग्रेडिएंट हीरो, टीम प्रोफ़ाइल और भूमिकाओं, सेवा कार्ड, ग्राहक प्रशंसापत्र, संपर्क अनुभाग और प्रमाणपत्र वाले फ़ूटर की कॉर्पोरेट साइट।",
    "blog-magazine": "विशेष लेख हीरो, क्रमांकित ट्रेंड साइडबार, लेख ग्रिड, न्यूज़लेटर सदस्यता, सुरुचिपूर्ण डार्क थीम और सेरिफ़ टाइपोग्राफी वाला संपादकीय मैगज़ीन ब्लॉग।",
    "react-portfolio-pro": "कंपोनेंट उदाहरण, स्क्रॉल-सिंक नेविगेशन, एनिमेटेड कौशल, फ़िल्टर योग्य प्रोजेक्ट, GitHub एकीकरण और डार्क नियॉन थीम वाला उन्नत React पोर्टफोलियो।",
  },
  pl: {
    "agency-site": "Witryna agencji kreatywnej z animowanym nagłówkiem, siatką portfolio, profilami zespołu, studiami przypadków, usługami, logotypami klientów, zachętą do kontaktu i opiniami.",
    "saas-dashboard": "Pełny panel administracyjny z nawigacją boczną, sześcioma kartami statystyk i wykresami, dziennikiem aktywności, zarządzaniem użytkownikami, trybem ciemnym, responsywnym układem i wykresami.",
    "shop-minimal": "Minimalistyczny sklep online z responsywną czterokolumnową siatką produktów, wyszukiwaniem i filtrami, stałym koszykiem, szybkim podglądem, listą życzeń, cenami i jasnym motywem.",
    "seo-landing": "Strona docelowa SEO z uporządkowanymi metadanymi, znacznikami schema.org, szybkim ładowaniem, optymalizacją mobilną, linkami wewnętrznymi, wezwaniami do działania i formularzem newslettera.",
    "doc-site": "Techniczna witryna dokumentacji z nawigacją boczną, spisem treści, podświetlaniem kodu, działającym wyszukiwaniem, trybem ciemnym, ścieżką nawigacji i wyborem wersji.",
    "contact-form-pro": "Zaawansowany formularz kontaktowy z walidacją w czasie rzeczywistym, jasnymi komunikatami o błędach i powodzeniu, ochroną przed spamem, przesyłaniem plików, reCAPTCHA, potwierdzeniem e-mail i responsywnym układem.",
    "saas-landing-pro": "Firmowa strona SaaS z animowanym gradientowym nagłówkiem, sześcioma kartami funkcji, dynamicznymi cenami w trzech poziomach, przyklejoną rozmytą nawigacją, karuzelą opinii, statystykami KPI i newsletterem.",
    "ecommerce-luxury": "Luksusowy sklep online z wysokiej jakości zdjęciami produktów, zaawansowanymi filtrami, interaktywną listą życzeń, wariantami kolorów, ocenami, stanem magazynowym i elegancką płatnością.",
    "portfolio-developer": "Portfolio programisty z ciemnym nagłówkiem i wezwaniem do działania, animowanymi paskami umiejętności, projektami ze zrzutami ekranu, osią czasu doświadczenia, opiniami, formularzem kontaktowym i linkami GitHub/LinkedIn.",
    "business-corporate": "Witryna firmy z niebieskim gradientowym nagłówkiem, profilami i rolami zespołu, kartami usług, opiniami klientów, sekcją kontaktową i stopką z certyfikatami.",
    "blog-magazine": "Redakcyjny blog magazynowy z wyróżnionym artykułem, numerowanym panelem trendów, siatką artykułów, zapisem do newslettera, eleganckim ciemnym motywem i krojem szeryfowym.",
    "react-portfolio-pro": "Zaawansowane portfolio React z przykładami komponentów, nawigacją powiązaną z przewijaniem, animowanymi umiejętnościami, filtrowanymi projektami, integracją GitHub i ciemnym motywem neonowym.",
  },
  nl: {
    "agency-site": "Website voor een creatief bureau met geanimeerde hero, portfolio-overzicht, teamprofielen, casestudy's, diensten, klantlogo's, contactoproep en testimonials.",
    "saas-dashboard": "Compleet beheerdashboard met zijbalknavigatie, zes statistiekkaarten met grafieken, activiteitenlogboek, gebruikersbeheer, donkere modus, responsieve indeling en grafiekintegratie.",
    "shop-minimal": "Minimalistische webwinkel met responsief productraster van vier kolommen, zoeken en filters, vaste winkelwagen, snelle weergave, verlanglijst, zichtbare prijzen en een helder wit thema.",
    "seo-landing": "SEO-landingspagina met gestructureerde metadata, schema.org-markering, snelle laadtijd, mobiele optimalisatie, interne links, actieknoppen en nieuwsbriefregistratie.",
    "doc-site": "Technische documentatiesite met zijbalknavigatie, inhoudsopgave, codeaccentuering, werkende zoekfunctie, donkere modus, broodkruimels en versie­keuze.",
    "contact-form-pro": "Geavanceerd contactformulier met realtime validatie, duidelijke fout- en succesmeldingen, spambeveiliging, bestandsuploads, reCAPTCHA, e-mailbevestiging en responsieve indeling.",
    "saas-landing-pro": "Enterprise-SaaS-landingspagina met geanimeerde verloophero, zes functiekaarten, dynamische prijzen in drie niveaus, vaste vervaagde navigatie, testimonialcarrousel, KPI-statistieken en nieuwsbrief.",
    "ecommerce-luxury": "Luxe webwinkel met premium productafbeeldingen, geavanceerde filters, interactieve verlanglijst, beschikbare kleuren, beoordelingen, voorraadindicator en elegante checkout.",
    "portfolio-developer": "Developerportfolio met donkere hero en actieknop, geanimeerde vaardigheidsbalken, projecten met screenshots, ervaringslijn, testimonials, contactformulier en GitHub-/LinkedIn-links.",
    "business-corporate": "Bedrijfswebsite met blauwe verloophero, teamprofielen en rollen, servicekaarten, klantgetuigenissen, contactgedeelte en footer met certificeringen.",
    "blog-magazine": "Redactionele magazineblog met uitgelicht artikel, genummerde trendzijbalk, artikelraster, nieuwsbriefinschrijving, elegant donker thema en schreeflettertype.",
    "react-portfolio-pro": "Geavanceerd React-portfolio met componentvoorbeelden, scrollgekoppelde navigatie, geanimeerde vaardigheden, filterbare projecten, GitHub-integratie en donker neonthema.",
  },
  tr: {
    "agency-site": "Animasyonlu ana bölüm, portföy ızgarası, ekip profilleri, vaka çalışmaları, hizmetler, müşteri logoları, iletişim çağrısı ve referanslar içeren yaratıcı ajans sitesi.",
    "saas-dashboard": "Kenar çubuğu gezinmesi, grafiklerle altı istatistik kartı, etkinlik kaydı, kullanıcı yönetimi, karanlık mod, duyarlı düzen ve grafik entegrasyonu içeren yönetim paneli.",
    "shop-minimal": "Duyarlı dört sütunlu ürün ızgarası, arama ve filtreler, sabit sepet, hızlı görünüm penceresi, istek listesi, görünür fiyatlar ve sade beyaz tema içeren minimal çevrimiçi mağaza.",
    "seo-landing": "Yapılandırılmış meta veriler, schema.org işaretlemesi, hızlı yükleme, mobil optimizasyon, dahili bağlantılar, eylem çağrıları ve bülten formu içeren SEO uyumlu açılış sayfası.",
    "doc-site": "Kenar çubuğu gezinmesi, içindekiler, kod vurgulama, çalışan arama, karanlık mod, kırıntı yolu ve sürüm seçici içeren teknik dokümantasyon sitesi.",
    "contact-form-pro": "Gerçek zamanlı doğrulama, anlaşılır hata ve başarı mesajları, spam koruması, dosya yükleme, reCAPTCHA, e-posta onayı ve duyarlı düzen içeren gelişmiş iletişim formu.",
    "saas-landing-pro": "Animasyonlu gradyan ana bölüm, altı özellik kartı, üç seviyeli dinamik fiyatlandırma, sabit bulanık gezinme, referans karuseli, KPI istatistikleri ve bülten içeren kurumsal SaaS sayfası.",
    "ecommerce-luxury": "Premium ürün görselleri, gelişmiş filtreler, etkileşimli istek listesi, renk seçenekleri, puanlar, stok göstergesi ve şık ödeme adımı içeren lüks çevrimiçi mağaza.",
    "portfolio-developer": "Koyu ana bölüm ve eylem çağrısı, animasyonlu beceri çubukları, ekran görüntülü projeler, deneyim zaman çizelgesi, referanslar, iletişim formu ve GitHub/LinkedIn bağlantıları içeren geliştirici portföyü.",
    "business-corporate": "Mavi gradyan ana bölüm, ekip profilleri ve rolleri, hizmet kartları, müşteri referansları, iletişim alanı ve sertifikalı altbilgi içeren kurumsal site.",
    "blog-magazine": "Öne çıkan makale bölümü, numaralı trend kenar çubuğu, makale ızgarası, bülten kaydı, zarif koyu tema ve serif yazı tipi içeren editoryal dergi blogu.",
    "react-portfolio-pro": "Bileşen örnekleri, kaydırma bağlantılı gezinme, animasyonlu beceriler, filtrelenebilir projeler, GitHub entegrasyonu ve koyu neon tema içeren gelişmiş React portföyü.",
  },
  sv: {
    "agency-site": "Webbplats för kreativ byrå med animerad hero, portfolioöversikt, teamprofiler, fallstudier, tjänster, kundlogotyper, kontaktuppmaning och kundomdömen.",
    "saas-dashboard": "Komplett adminpanel med sidnavigering, sex statistik- och diagramkort, aktivitetslogg, användarhantering, mörkt läge, responsiv layout och diagramintegration.",
    "shop-minimal": "Minimal webbutik med responsivt produktnät i fyra kolumner, sökning och filter, beständig kundvagn, snabbvisning, önskelista, synliga priser och rent vitt tema.",
    "seo-landing": "SEO-optimerad landningssida med strukturerad metadata, schema.org-markup, snabb laddning, mobilanpassning, interna länkar, uppmaningar och nyhetsbrevsformulär.",
    "doc-site": "Teknisk dokumentationswebbplats med sidnavigering, innehållsförteckning, kodmarkering, fungerande sökning, mörkt läge, brödsmulor och versionsväljare.",
    "contact-form-pro": "Avancerat kontaktformulär med realtidsvalidering, tydliga fel- och bekräftelsemeddelanden, skräppostskydd, filuppladdning, reCAPTCHA, e-postbekräftelse och responsiv layout.",
    "saas-landing-pro": "SaaS-landningssida för företag med animerad gradienthero, sex funktionskort, dynamisk prissättning i tre nivåer, fast oskarp navigering, omdömeskarusell, KPI-statistik och nyhetsbrev.",
    "ecommerce-luxury": "Lyxig webbutik med premiumproduktbilder, avancerade filter, interaktiv önskelista, färgval, betyg, lagersaldo och elegant kassa.",
    "portfolio-developer": "Utvecklarportfolio med mörk hero och uppmaning, animerade färdighetsstaplar, projekt med skärmbilder, erfarenhetstidslinje, omdömen, kontaktformulär och GitHub-/LinkedIn-länkar.",
    "business-corporate": "Företagswebbplats med blå gradienthero, teamprofiler och roller, tjänstekort, kundomdömen, kontaktsektion och sidfot med certifieringar.",
    "blog-magazine": "Redaktionell magasinblogg med utvald artikelhero, numrerad trendpanel, artikelrutnät, nyhetsbrevsanmälan, elegant mörkt tema och seriftypografi.",
    "react-portfolio-pro": "Avancerad React-portfolio med komponentexempel, scrollkopplad navigering, animerade färdigheter, filtrerbara projekt, GitHub-integration och mörkt neontema.",
  },
  da: {
    "agency-site": "Websted til kreativt bureau med animeret hero, portfoliogitter, teamprofiler, cases, tjenester, kundelogoer, kontaktopfordring og kundeudtalelser.",
    "saas-dashboard": "Komplet administrationspanel med sidebjælkenavigation, seks statistik- og diagramkort, aktivitetslog, brugeradministration, mørk tilstand, responsivt layout og diagramintegration.",
    "shop-minimal": "Minimal webshop med responsivt produktgitter i fire kolonner, søgning og filtre, fast indkøbskurv, hurtig visning, ønskeliste, synlige priser og rent hvidt tema.",
    "seo-landing": "SEO-optimeret landingsside med strukturerede metadata, schema.org-markering, hurtig indlæsning, mobiloptimering, interne links, handlingsopfordringer og nyhedsbrevsformular.",
    "doc-site": "Teknisk dokumentationswebsted med sidebjælkenavigation, indholdsfortegnelse, kodefremhævning, fungerende søgning, mørk tilstand, brødkrummer og versionsvælger.",
    "contact-form-pro": "Avanceret kontaktformular med validering i realtid, tydelige fejl- og succesbeskeder, spam-beskyttelse, filupload, reCAPTCHA, e-mailbekræftelse og responsivt layout.",
    "saas-landing-pro": "SaaS-landingsside til virksomheder med animeret gradienthero, seks funktionskort, dynamiske priser i tre niveauer, fast sløret navigation, testimonialkarrusel, KPI-statistik og nyhedsbrev.",
    "ecommerce-luxury": "Luksuswebshop med premium-produktbilleder, avancerede filtre, interaktiv ønskeliste, farvevalg, bedømmelser, lagerstatus og elegant betaling.",
    "portfolio-developer": "Udviklerportfolio med mørk hero og handlingsopfordring, animerede færdighedsbjælker, projekter med skærmbilleder, erfarings-tidslinje, kundeudtalelser, kontaktformular og GitHub-/LinkedIn-links.",
    "business-corporate": "Virksomhedswebsted med blå gradienthero, teamprofiler og roller, servicekort, kundeudtalelser, kontaktsektion og sidefod med certificeringer.",
    "blog-magazine": "Redaktionel magasinblog med fremhævet artikelhero, nummereret trendsidepanel, artikelgitter, nyhedsbrevsabonnement, elegant mørkt tema og seriftypografi.",
    "react-portfolio-pro": "Avanceret React-portfolio med komponenteksempler, scrollkoblet navigation, animerede færdigheder, filtrerbare projekter, GitHub-integration og mørkt neontema.",
  },
  no: {
    "agency-site": "Nettsted for kreativt byrå med animert hero, porteføljenett, teamprofiler, casestudier, tjenester, kundelogoer, kontaktoppfordring og kundeuttalelser.",
    "saas-dashboard": "Komplett administrasjonspanel med sidemeny, seks statistikkort med diagrammer, aktivitetslogg, brukeradministrasjon, mørk modus, responsivt oppsett og diagramintegrasjon.",
    "shop-minimal": "Minimal nettbutikk med responsivt produktnett i fire kolonner, søk og filtre, fast handlekurv, hurtigvisning, ønskeliste, synlige priser og rent hvitt tema.",
    "seo-landing": "SEO-optimalisert landingsside med strukturerte metadata, schema.org-merking, rask lasting, mobiloptimalisering, interne lenker, handlingsoppfordringer og nyhetsbrevskjema.",
    "doc-site": "Teknisk dokumentasjonsnettsted med sidemeny, innholdsfortegnelse, kodeutheving, fungerende søk, mørk modus, brødsmuler og versjonsvelger.",
    "contact-form-pro": "Avansert kontaktskjema med sanntidsvalidering, tydelige feil- og suksessmeldinger, spamvern, filopplasting, reCAPTCHA, e-postbekreftelse og responsivt oppsett.",
    "saas-landing-pro": "SaaS-landingsside for bedrifter med animert gradienthero, seks funksjonskort, dynamisk prising i tre nivåer, fast uskarp navigasjon, karusell med uttalelser, KPI-statistikk og nyhetsbrev.",
    "ecommerce-luxury": "Luksuriøs nettbutikk med premium-produktbilder, avanserte filtre, interaktiv ønskeliste, fargevalg, vurderinger, lagerindikator og elegant betaling.",
    "portfolio-developer": "Utviklerportefølje med mørk hero og handlingsoppfordring, animerte ferdighetslinjer, prosjekter med skjermbilder, erfaringslinje, uttalelser, kontaktskjema og GitHub-/LinkedIn-lenker.",
    "business-corporate": "Bedriftsnettsted med blå gradienthero, teamprofiler og roller, tjenestekort, kundeuttalelser, kontaktseksjon og bunntekst med sertifiseringer.",
    "blog-magazine": "Redaksjonell magasinblogg med fremhevet artikkel, nummerert trendpanel, artikkelnett, nyhetsbrevregistrering, elegant mørkt tema og seriftypografi.",
    "react-portfolio-pro": "Avansert React-portefølje med komponenteksempler, rullestyrt navigasjon, animerte ferdigheter, filtrerbare prosjekter, GitHub-integrasjon og mørkt neontema.",
  },
  fi: {
    "agency-site": "Luovan toimiston sivusto, jossa on animoitu pääosio, portfolioruudukko, tiimiprofiilit, tapaustutkimukset, palvelut, asiakaslogot, yhteydenottokehotus ja suositukset.",
    "saas-dashboard": "Täydellinen hallintapaneeli, jossa on sivupalkkivalikko, kuusi kaavioita sisältävää tilastokorttia, toimintaloki, käyttäjähallinta, tumma tila, responsiivinen asettelu ja kaaviot.",
    "shop-minimal": "Minimalistinen verkkokauppa, jossa on responsiivinen nelisarakkeinen tuoteruudukko, haku ja suodattimet, pysyvä ostoskori, pikakatselu, toivelista, näkyvät hinnat ja selkeä vaalea teema.",
    "seo-landing": "Hakukoneoptimoitu laskeutumissivu, jossa on rakenteiset metatiedot, schema.org-merkinnät, nopea lataus, mobiilioptimointi, sisäiset linkit, toimintakehotteet ja uutiskirjelomake.",
    "doc-site": "Tekninen dokumentaatiosivusto, jossa on sivupalkkivalikko, sisällysluettelo, koodin korostus, toimiva haku, tumma tila, murupolku ja version valitsin.",
    "contact-form-pro": "Edistynyt yhteydenottolomake, jossa on reaaliaikainen validointi, selkeät virhe- ja onnistumisviestit, roskapostisuoja, tiedostojen lähetys, reCAPTCHA, sähköpostivahvistus ja responsiivinen asettelu.",
    "saas-landing-pro": "Yritystason SaaS-laskeutumissivu, jossa on animoitu liukuväripääosio, kuusi ominaisuuskorttia, kolmivaiheinen dynaaminen hinnoittelu, kiinnitetty sumennettu valikko, suosituskaruselli, KPI-tilastot ja uutiskirje.",
    "ecommerce-luxury": "Ylellinen verkkokauppa, jossa on premium-tuotekuvat, edistyneet suodattimet, vuorovaikutteinen toivelista, värivaihtoehdot, arviot, varastosaldo ja tyylikäs maksaminen.",
    "portfolio-developer": "Kehittäjän portfolio, jossa on tumma pääosio toimintakehotteineen, animoidut taitopalkit, kuvakaappauksin esitellyt projektit, kokemusaikajana, suositukset, yhteydenottolomake ja GitHub-/LinkedIn-linkit.",
    "business-corporate": "Yrityssivusto, jossa on sininen liukuväripääosio, tiimiprofiilit ja roolit, palvelukortit, asiakaspalautteet, yhteystieto-osio ja sertifikaatit sisältävä alatunniste.",
    "blog-magazine": "Toimituksellinen aikakauslehtiblogi, jossa on esitellyn artikkelin pääosio, numeroitu trendisivupalkki, artikkeliruudukko, uutiskirjetilaus, tyylikäs tumma teema ja päätteellinen kirjasin.",
    "react-portfolio-pro": "Edistynyt React-portfolio, jossa on komponenttiesimerkkejä, vieritykseen sidottu navigointi, animoidut taidot, suodatettavat projektit, GitHub-integraatio ja tumma neon-teema.",
  },
  uk: {
    "agency-site": "Сайт творчої агенції з анімованим головним блоком, сіткою портфоліо, профілями команди, кейсами, послугами, логотипами клієнтів, закликом до контакту та відгуками.",
    "saas-dashboard": "Повна панель адміністратора з бічною навігацією, шістьма картками показників і графіками, журналом активності, керуванням користувачами, темною темою, адаптивною версткою та графіками.",
    "shop-minimal": "Мінімалістичний інтернет-магазин з адаптивною сіткою товарів у чотири стовпці, пошуком і фільтрами, постійним кошиком, швидким переглядом, списком бажань, цінами та світлою темою.",
    "seo-landing": "SEO-оптимізована цільова сторінка зі структурованими метаданими, розміткою schema.org, швидким завантаженням, мобільною оптимізацією, внутрішніми посиланнями, закликами до дії та формою розсилки.",
    "doc-site": "Сайт технічної документації з бічною навігацією, змістом, підсвічуванням коду, пошуком, темною темою, навігаційним ланцюжком і вибором версії.",
    "contact-form-pro": "Розширена контактна форма з перевіркою в реальному часі, зрозумілими повідомленнями про помилки та успіх, захистом від спаму, завантаженням файлів, reCAPTCHA, підтвердженням поштою й адаптивною версткою.",
    "saas-landing-pro": "Корпоративна SaaS-сторінка з анімованим градієнтним блоком, шістьма картками функцій, динамічними цінами трьох рівнів, закріпленою розмитою навігацією, каруселлю відгуків, KPI та розсилкою.",
    "ecommerce-luxury": "Розкішний інтернет-магазин із преміальними зображеннями товарів, розширеними фільтрами, інтерактивним списком бажань, вибором кольорів, оцінками, індикатором запасів і зручним оформленням покупки.",
    "portfolio-developer": "Портфоліо розробника з темним головним блоком і закликом до дії, анімованими шкалами навичок, проєктами зі знімками екрана, хронологією досвіду, відгуками, контактною формою та посиланнями GitHub/LinkedIn.",
    "business-corporate": "Корпоративний сайт із синім градієнтним блоком, профілями та ролями команди, картками послуг, відгуками клієнтів, контактним розділом і нижнім колонтитулом із сертифікатами.",
    "blog-magazine": "Редакційний блог-журнал із головним блоком вибраної статті, нумерованою бічною панеллю трендів, сіткою статей, підпискою на розсилку, елегантною темною темою та шрифтом із засічками.",
    "react-portfolio-pro": "Розширене портфоліо React із прикладами компонентів, навігацією за прокручуванням, анімованими навичками, фільтрованими проєктами, інтеграцією GitHub і темною неоновою темою.",
  },
  cs: {
    "agency-site": "Web kreativní agentury s animovanou úvodní částí, mřížkou portfolia, profily týmu, případovými studiemi, službami, logy klientů, výzvou ke kontaktu a referencemi.",
    "saas-dashboard": "Kompletní administrační panel s boční navigací, šesti statistickými kartami s grafy, protokolem aktivit, správou uživatelů, tmavým režimem, responzivním rozvržením a grafy.",
    "shop-minimal": "Minimalistický internetový obchod s responzivní čtyřsloupcovou mřížkou produktů, vyhledáváním a filtry, trvalým košíkem, rychlým náhledem, seznamem přání, cenami a čistým světlým motivem.",
    "seo-landing": "SEO optimalizovaná vstupní stránka se strukturovanými metadaty, značkami schema.org, rychlým načítáním, optimalizací pro mobily, interními odkazy, výzvami k akci a formulářem newsletteru.",
    "doc-site": "Web technické dokumentace s boční navigací, obsahem, zvýrazněním kódu, funkčním vyhledáváním, tmavým režimem, drobečkovou navigací a výběrem verze.",
    "contact-form-pro": "Pokročilý kontaktní formulář s průběžnou validací, jasnými chybovými a úspěšnými zprávami, ochranou proti spamu, nahráváním souborů, reCAPTCHA, potvrzením e-mailem a responzivním rozvržením.",
    "saas-landing-pro": "Firemní SaaS stránka s animovanou gradientní úvodní částí, šesti kartami funkcí, dynamickými cenami ve třech úrovních, pevnou rozmazanou navigací, karuselem referencí, KPI statistikami a newsletterem.",
    "ecommerce-luxury": "Luxusní internetový obchod s prémiovými obrázky produktů, pokročilými filtry, interaktivním seznamem přání, výběrem barev, hodnocením, ukazatelem skladových zásob a elegantní platbou.",
    "portfolio-developer": "Portfolio vývojáře s tmavou úvodní částí a výzvou k akci, animovanými ukazateli dovedností, projekty se snímky obrazovky, časovou osou zkušeností, referencemi, kontaktním formulářem a odkazy GitHub/LinkedIn.",
    "business-corporate": "Firemní web s modrou gradientní úvodní částí, profily a rolemi týmu, kartami služeb, referencemi zákazníků, kontaktní sekcí a patičkou s certifikacemi.",
    "blog-magazine": "Redakční magazínový blog s úvodním blokem doporučeného článku, očíslovaným panelem trendů, mřížkou článků, přihlášením k newsletteru, elegantním tmavým motivem a patkovým písmem.",
    "react-portfolio-pro": "Pokročilé React portfolio s ukázkami komponent, navigací navázanou na posouvání, animovanými dovednostmi, filtrovatelnými projekty, integrací GitHub a tmavým neonovým motivem.",
  },
};

export function getLocalizedTemplateDescription(
  templateId: string,
  originalDescription: string,
  language: string,
): string {
  const descriptions = templateMarketplaceContentCopy[language];
  if (!descriptions || !templateIds.includes(templateId as TemplateId)) return originalDescription;
  return descriptions[templateId as TemplateId] ?? originalDescription;
}
