import './styles.css';
import {
  maxPythonInputBytes,
  maxPythonOutputBytes,
  maxPythonPlotBytes,
  maxPythonSourceBytes,
  pythonExecutionTimeoutMs,
  pythonStartupTimeoutMs,
  truncateUtf8,
  utf8ByteLength,
  type PythonSourceUpdate,
  type PythonWorkerMessage,
} from './protocol';

const title = document.querySelector<HTMLHeadingElement>('#title');
const fileName = document.querySelector<HTMLElement>('#file-name');
const stdin = document.querySelector<HTMLTextAreaElement>('#stdin');
const stdinLabel = document.querySelector<HTMLLabelElement>('#stdin-label');
const runButton = document.querySelector<HTMLButtonElement>('#run');
const stopButton = document.querySelector<HTMLButtonElement>('#stop');
const status = document.querySelector<HTMLElement>('#status');
const output = document.querySelector<HTMLPreElement>('#output');
const plots = document.querySelector<HTMLDivElement>('#plots');

if (!title || !fileName || !stdin || !stdinLabel || !runButton || !stopButton || !status || !output || !plots) {
  throw new Error('Python runner UI is incomplete.');
}

const ui = { title, fileName, stdin, stdinLabel, runButton, stopButton, status, output, plots };
const trustedParentOrigin = (origin: string) =>
  origin === 'https://www.tatik.space'
  || origin === 'https://tatik.space'
  || /^https:\/\/tatik-space-pro1-[a-z0-9-]+-tatikspace-beeps-projects\.vercel\.app$/i.test(origin);

const copy = {
  it: {
    title: 'Esecuzione Python',
    waiting: "In attesa dell'Editor",
    file: 'File Python',
    input: 'Input standard (opzionale)',
    run: 'Esegui',
    stop: 'Interrompi',
    loading: 'Caricamento runtime Python nel browser...',
    running: 'Esecuzione in corso...',
    finished: 'Esecuzione completata.',
    failed: 'Errore durante l’esecuzione.',
    timedOut: 'Tempo massimo superato; esecuzione interrotta.',
    startupTimedOut: 'Timeout durante il caricamento del runtime Python.',
    stopped: 'Esecuzione interrotta.',
    sourceTooLarge: 'Il file supera il limite di 100 KB.',
    inputTooLarge: 'L’input supera il limite di 10 KB.',
    outputLimit: 'Output troncato al limite di 100 KB.',
    plotLimit: 'Grafico non visualizzato: limite complessivo di 1 MB superato.',
    plotAlt: 'Grafico generato da Python',
    noSource: 'Apri un file .py nell’Editor.',
  },
  en: {
    title: 'Python execution',
    waiting: 'Waiting for the editor',
    file: 'Python file',
    input: 'Standard input (optional)',
    run: 'Run',
    stop: 'Stop',
    loading: 'Loading the Python runtime in your browser...',
    running: 'Running...',
    finished: 'Execution finished.',
    failed: 'Execution failed.',
    timedOut: 'Execution timed out and was stopped.',
    startupTimedOut: 'Python runtime startup timed out.',
    stopped: 'Execution stopped.',
    sourceTooLarge: 'The file exceeds the 100 KB limit.',
    inputTooLarge: 'Input exceeds the 10 KB limit.',
    outputLimit: 'Output truncated at the 100 KB limit.',
    plotLimit: 'Plot not displayed: the 1 MB combined display limit was exceeded.',
    plotAlt: 'Plot generated by Python',
    noSource: 'Open a .py file in the editor.',
  },
} as const;

let locale: 'it' | 'en' = 'it';
let source = '';
let activeFileName = '';
let currentWorker: Worker | undefined;
let runId = 0;
let outputBytes = 0;
let plotBytes = 0;
let runTimer: number | undefined;
let executionTimerStarted = false;

const text = () => copy[locale];
const setStatus = (value: string) => { ui.status.textContent = value; };

function stopCurrentRun(message?: string) {
  if (runTimer !== undefined) window.clearTimeout(runTimer);
  runTimer = undefined;
  currentWorker?.terminate();
  currentWorker = undefined;
  ui.runButton.disabled = !source;
  ui.stopButton.disabled = true;
  if (message) setStatus(message);
}

function appendOutput(value: string) {
  const available = maxPythonOutputBytes - outputBytes;
  if (available <= 0) {
    stopCurrentRun(text().outputLimit);
    return;
  }
  const clipped = truncateUtf8(value, available);
  ui.output.textContent += clipped.text;
  outputBytes += clipped.bytes;
  if (clipped.text.length < value.length || outputBytes >= maxPythonOutputBytes) {
    stopCurrentRun(text().outputLimit);
  }
}

function runPython() {
  if (!source || currentWorker) return;
  if (utf8ByteLength(source) > maxPythonSourceBytes) {
    setStatus(text().sourceTooLarge);
    return;
  }
  if (utf8ByteLength(ui.stdin.value) > maxPythonInputBytes) {
    setStatus(text().inputTooLarge);
    return;
  }

  runId += 1;
  const currentRun = runId;
  outputBytes = 0;
  plotBytes = 0;
  executionTimerStarted = false;
  ui.output.textContent = '';
  ui.plots.replaceChildren();
  ui.runButton.disabled = true;
  ui.stopButton.disabled = false;
  setStatus(text().loading);

  try {
    currentWorker = new Worker(new URL('./python.worker.ts', import.meta.url), { type: 'module' });
  } catch (error) {
    stopCurrentRun(text().failed);
    appendOutput(error instanceof Error ? error.message : String(error));
    return;
  }

  const worker = currentWorker;
  worker.addEventListener('message', (event: MessageEvent<PythonWorkerMessage>) => {
    const message = event.data;
    if (
      !message
      || typeof message !== 'object'
      || message.runId !== currentRun
      || worker !== currentWorker
    ) return;
    if (message.type === 'loading') {
      setStatus(text().loading);
      return;
    }
    if (message.type === 'ready') {
      if (!executionTimerStarted) {
        executionTimerStarted = true;
        if (runTimer !== undefined) window.clearTimeout(runTimer);
        runTimer = window.setTimeout(
          () => stopCurrentRun(text().timedOut),
          pythonExecutionTimeoutMs,
        );
        setStatus(text().running);
      }
      return;
    }
    if (message.type === 'stdout' || message.type === 'stderr') {
      appendOutput(message.text);
      return;
    }
    if (message.type === 'plot') {
      const bytes = Math.ceil(message.data.length * 3 / 4);
      if (bytes > maxPythonPlotBytes - plotBytes) {
        appendOutput(text().plotLimit);
        return;
      }
      plotBytes += bytes;
      const image = document.createElement('img');
      image.alt = text().plotAlt;
      image.src = `data:image/png;base64,${message.data}`;
      ui.plots.append(image);
      return;
    }
    if (message.type === 'error') {
      stopCurrentRun(text().failed);
      appendOutput(message.message);
      return;
    }
    if (message.type === 'finished') {
      stopCurrentRun(text().finished);
    }
  });
  worker.addEventListener('error', event => {
    if (worker !== currentWorker) return;
    stopCurrentRun(text().failed);
    appendOutput(event.message || 'Python worker failed.');
  });
  runTimer = window.setTimeout(
    () => stopCurrentRun(text().startupTimedOut),
    pythonStartupTimeoutMs,
  );
  worker.postMessage({
    type: 'run',
    runId: currentRun,
    source,
    stdin: ui.stdin.value,
  });
}

window.addEventListener('message', (event: MessageEvent<PythonSourceUpdate>) => {
  if (event.source !== window.parent || !trustedParentOrigin(event.origin)) return;
  const message = event.data;
  if (
    !message
    || message.type !== 'source-update'
    || typeof message.source !== 'string'
    || typeof message.fileName !== 'string'
    || !/\.py$/i.test(message.fileName)
  ) return;

  stopCurrentRun();
  if (utf8ByteLength(message.source) > maxPythonSourceBytes) {
    source = '';
    activeFileName = message.fileName;
    locale = message.locale === 'en' ? 'en' : 'it';
    ui.fileName.textContent = `${text().file}: ${activeFileName}`;
    ui.runButton.disabled = true;
    setStatus(text().sourceTooLarge);
    return;
  }
  source = message.source;
  activeFileName = message.fileName;
  locale = message.locale === 'en' ? 'en' : 'it';
  document.documentElement.lang = locale;
  ui.title.textContent = text().title;
  ui.fileName.textContent = `${text().file}: ${activeFileName}`;
  ui.stdinLabel.textContent = text().input;
  ui.runButton.textContent = text().run;
  ui.stopButton.textContent = text().stop;
  ui.output.setAttribute('aria-label', text().title);
  ui.plots.setAttribute('aria-label', text().plotAlt);
  ui.output.textContent = '';
  ui.plots.replaceChildren();
  ui.runButton.disabled = !source;
  ui.stopButton.disabled = true;
  setStatus(source ? text().waiting : text().noSource);
});

ui.runButton.addEventListener('click', runPython);
ui.stopButton.addEventListener('click', () => stopCurrentRun(text().stopped));
