import type { IncomingMessage, ServerResponse } from "http";

// The bundle is generated by build:vercel and is intentionally JavaScript.
// @ts-ignore The generated CommonJS bundle has no source-level TypeScript declarations.
import { appRouter, createContext, enhanceVercelResponse, resolveResponse } from "./_server-bundle.cjs";

function applyCorsHeaders(res: ServerResponse, req: IncomingMessage) {
    const origin = typeof req.headers.origin === "string" ? req.headers.origin : "*";
    res.setHeader("Access-Control-Allow-Origin", origin);
    res.setHeader("Access-Control-Allow-Methods", "GET,POST,PUT,DELETE,OPTIONS");
    res.setHeader("Access-Control-Allow-Headers", "Content-Type,Authorization,X-Requested-With,X-TRPC-BATCH,X-TRPC-TRAILER");
    res.setHeader("Access-Control-Allow-Credentials", "true");
}

export default async function handler(req: IncomingMessage & { body?: unknown }, res: ServerResponse) {
    const response = enhanceVercelResponse(res);
    applyCorsHeaders(response, req);

    if (req.method === "OPTIONS") {
        response.statusCode = 204;
        response.end();
        return;
    }

    try {
        const url = new URL(req.url || "/", `http://${req.headers.host || "localhost"}`);
        const body = req.body === undefined
            ? undefined
            : typeof req.body === "string"
                ? req.body
                : JSON.stringify(req.body);
        const headers = new Headers();
        for (const [name, value] of Object.entries(req.headers)) {
            if (value !== undefined) headers.set(name, Array.isArray(value) ? value.join(", ") : value);
        }

        const webRequest = new Request(url, { method: req.method, headers, body });
        const path = decodeURIComponent(url.pathname.replace(/^\/api\/trpc\/?/, ""));
        const trpcResponse = await resolveResponse({
            router: appRouter,
            req: webRequest,
            path,
            createContext: async (opts: any) => createContext({ req: req as any, res: response, info: opts.info }),
        } as any);

        response.statusCode = trpcResponse.status;
        trpcResponse.headers.forEach((value, key) => response.setHeader(key, value));
        response.end(Buffer.from(await trpcResponse.arrayBuffer()));
    } catch (error: any) {
        console.error("[API tRPC] Handler error:", error);
        if (!(response as any).headersSent) {
            response.statusCode = 500;
            response.setHeader("Content-Type", "application/json; charset=utf-8");
            response.end(JSON.stringify({ error: error?.message || "Internal server error" }));
        }
    }
}
